kubeflow/pipelines

example/parameterized.yaml
resources/scheduledworkflow/util/scheduled_workflow_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/13)

Fixing bug in parameterized sample.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/157)

Acknowledge Argo.

---

samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/181)

Modify sample notebook.

---

sdk/python/kfp/components/_structures.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/173)

SDK/Components - Switched the generated inputs/outputs structure from dict to list

---

test/minikube/install_docker.sh
test/minikube/install_docker_minikube_argo.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/189)

Tests/Minikube - Downgraded Docker to 18.06.1

---

components/kubeflow/container/deployer/deploy.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/211)

Use kubeflow as default namespace for tf serving

---

sdk/python/tests/compiler/component_builder_test.py
sdk/python/tests/components/test_python_op.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/217)

minor fixes

---

test/sample-test/run_test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/230)

Tests - Simplified test/sample-test/run_tests.sh a bit

---

frontend/server/k8s-helper.ts

So it can access to GCS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/273)

attach service account to tensorboard pod

---

frontend/server/k8s-helper.ts

- Use generateName instead of name
- remove selector
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/283)

Update frontend tensorboard spec

---

backend/src/apiserver/interceptor.go

To help profile API requests on the backend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/386)

Add finish timestamp to backend API interceptor

---

test/presubmit-tests-with-pipeline-deployment.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/410)

Clean up the resource after test finish

---

sdk/python/kfp/compiler/_k8s_helper.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/423)

Propagate secret to kaniko

---

frontend/src/components/viewers/Tensorboard.test.tsx

To avoid the "cb is not a function" error when running this test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/427)

Fix tb viewer test

---

sdk/python/tests/components/test_components.py

See https://github.com/kubeflow/pipelines/issues/431
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/432)

Testing - Fix Travis tests (SDK/Components)

---

sdk/python/kfp/dsl/_container_op.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/435)

DSL - return self for .after()

---

sdk/python/kfp/compiler/_component_builder.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/442)

SDK/PythonContainer - Compiling pipelines without needing kubernetes

---

test/presubmit-tests.sh

https://github.com/kubeflow/pipelines/issues/403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/433)

Tests - Try fix GCS file being inaccessible right after upload

---

pipeline/pipeline/prototypes/pipeline.jsonnet

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/484)

Bump default pipeline version to v0.1.3

---

samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb

1) deployer model has name restrictions: cannot have '-' in the name
2) surface potential errors in deployer because it could be permission issues, model name error etc
3) update the tensorflow image with python3 because python_component_build uses python3 as the entrypoint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/517)

Improve the notebook TFX sample

---

components/local/confusion_matrix/src/confusion_matrix.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/526)

Remove the workaround in confusion matrix component for correctly handling boolean cases.

---

sdk/python/kfp/compiler/_k8s_helper.py

If the jupyter environment includes default k8s cluster config, it should just work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/535)

Support Kaniko job in a outside-cluster jupyter.

---

test/sample-test/run_basic_test.py
test/sample-test/run_kubeflow_test.py
test/sample-test/run_tfx_test.py
test/sample-test/run_xgboost_test.py

fix #515
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/635)

Print sample test logs in case of exception throw

---

backend/src/crd/controller/viewer/reconciler/reconciler.go

Fixes #646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/648)

Fix shadowing errors in Viewer reconciler

---

sdk/python/tests/run_tests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/556)

SDK - Fixed the unittest script

---

sdk/python/kfp/components/_structures.py
sdk/python/tests/components/test_components.py
sdk/python/tests/components/test_data/python_add.component.yaml

The new names feel more understandable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/659)

SDK/Components - Renamed serialized command-line argument tokens

---

components/kubeflow/launcher/src/train.template.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/689)

add gcp credential for tf-job template

---

ROADMAP.md

Adding roadmap file for 2019 development
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/786)

Creating ROADMAP.md

---

samples/notebooks/Lightweight Python components - basics.ipynb

PipelineParam has been simplified, this change reflects that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/782)

Update Basic Pipeline example notebook

---

sdk/python/build.sh
sdk/python/kfp/_auth.py
sdk/python/kfp/_client.py
sdk/python/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/779)

Support to send default service account jwt token for pipeline client.

---

components/third_party_licenses.csv

Unblock #805
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/806)

add trainer license to unblock release

---

components/third_party_licenses.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/810)

add pyarrow in license csv.

---

.release.cloudbuild.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/811)

add ViewerCrdController to cloud builder release spec

---

backend/src/crd/README.md
backend/src/crd/samples/viewer/tensorboard-local-volume.yaml

Also edited the README for viewer CRD usage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/822)

Adds a local volume sample for the Viewer CRD

---

components/dataflow/tfdv/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/828)

fix apache-beam and pandas versions in tfdv image

---

ROADMAP.md

No changes to the actual substance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/846)

ROADMAP.md cosmetic changes

---

component_sdk/python/kfp_component/google/bigquery/__init__.py
component_sdk/python/kfp_component/google/bigquery/_query.py
component_sdk/python/requirements.txt
component_sdk/python/tests/google/bigquery/test__query.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/836)

Support BigQuery command to query and export to GCS

---

components/dataflow/tfdv/Dockerfile

Follow-up to #852
Tested with `cloud-build-local`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/856)

Removes accidental package from TFDV Dockerfile

---

components/third_party_licenses.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/857)

add attrs and pyrsistent

---

.cloudbuild.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/860)

fix typo in cloud build

---

.cloudbuild.yaml
components/third_party_licenses.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/861)

fix bug in the gcp oob

---

component_sdk/python/kfp_component/google/dataflow/_launch_python.py
component_sdk/python/kfp_component/google/storage/_download_blob.py
component_sdk/python/tests/google/storage/test__download_blob.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/870)

Fix bugs in dataflow component

---

components/gcp/container/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/876)

Switch to python 2.7 and install beam for the gcp image.

---

developer_guide.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/853)

link anchor text nit

---

components/gcp/bigquery/query/component.yaml
components/gcp/dataflow/launch_python/component.yaml
components/gcp/dataflow/launch_template/component.yaml
components/gcp/ml_engine/batch_predict/component.yaml
components/gcp/ml_engine/deploy/component.yaml
components/gcp/ml_engine/train/component.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/887)

GCPcomponents yaml spec

---

component_sdk/python/kfp_component/core/_display.py
component_sdk/python/tests/core/test__display.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/895)

Change viewer to markdown instead of html according to FE changes.

---

component_sdk/python/kfp_component/core/_display.py
component_sdk/python/kfp_component/google/ml_engine/_create_version.py
component_sdk/python/tests/core/test__display.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/914)

Add online prediction instructions and print friendly msg in console.

---

components/third_party_licenses.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/917)

fix license links

---

component_sdk/python/kfp_component/google/bigquery/_query.py
components/gcp/bigquery/query/component.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/921)

Fix bugs in bigquery component

---

samples/tfx-oss/TFX Example.ipynb

Add instructions on how to query ML Metadata for output artifacts from TFX components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/932)

Add notebook instructions on how to query ML Metadata for output artifacts

---

components/gcp/bigquery/query/component.yaml
components/gcp/dataflow/launch_python/component.yaml
components/gcp/dataflow/launch_template/component.yaml
components/gcp/dataproc/create_cluster/component.yaml
components/gcp/dataproc/delete_cluster/component.yaml
components/gcp/dataproc/submit_hadoop_job/component.yaml
components/gcp/dataproc/submit_hive_job/component.yaml
components/gcp/dataproc/submit_pig_job/component.yaml
components/gcp/dataproc/submit_pyspark_job/component.yaml
components/gcp/dataproc/submit_spark_job/component.yaml
components/gcp/dataproc/submit_sparksql_job/component.yaml
components/gcp/ml_engine/batch_predict/component.yaml
components/gcp/ml_engine/deploy/component.yaml
components/gcp/ml_engine/train/component.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/987)

Update component.yaml for dataflow and cmle with recent changes.

---

components/ibm-components/watson/deploy/component.yaml

Minor fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1002)

Updating the description for model_uid param

---

frontend/src/components/SideNav.tsx
frontend/src/components/__snapshots__/SideNav.test.tsx.snap

Changes sidenav to lower-contrast gray instead of blue. Updates selection and hover styling as well.
Addresses https://github.com/kubeflow/kubeflow/issues/2678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1010)

Update sidebar styling

---

component_sdk/python/kfp_component/google/dataproc/_create_cluster.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1028)

Fix a missing precheck in create cluster component

---

components/gcp/bigquery/query/README.md
components/gcp/bigquery/query/sample.ipynb
components/gcp/dataflow/launch_python/README.md
components/gcp/dataflow/launch_python/sample.ipynb
components/gcp/dataflow/launch_template/README.md
components/gcp/dataflow/launch_template/sample.ipynb
components/gcp/dataproc/create_cluster/README.md
components/gcp/dataproc/create_cluster/sample.ipynb
components/gcp/dataproc/delete_cluster/README.md
components/gcp/dataproc/delete_cluster/sample.ipynb
components/gcp/dataproc/submit_hadoop_job/README.md
components/gcp/dataproc/submit_hadoop_job/sample.ipynb
components/gcp/dataproc/submit_hive_job/README.md
components/gcp/dataproc/submit_hive_job/sample.ipynb
components/gcp/dataproc/submit_pig_job/README.md
components/gcp/dataproc/submit_pig_job/sample.ipynb
components/gcp/dataproc/submit_pyspark_job/README.md
components/gcp/dataproc/submit_pyspark_job/sample.ipynb
components/gcp/dataproc/submit_spark_job/README.md
components/gcp/dataproc/submit_spark_job/sample.ipynb
components/gcp/dataproc/submit_sparksql_job/README.md
components/gcp/dataproc/submit_sparksql_job/sample.ipynb
components/gcp/ml_engine/batch_predict/README.md
components/gcp/ml_engine/batch_predict/sample.ipynb
components/gcp/ml_engine/deploy/README.md
components/gcp/ml_engine/deploy/sample.ipynb
components/gcp/ml_engine/train/README.md
components/gcp/ml_engine/train/sample.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1037)

Pin the component.yaml version in all the samples.

---

backend/src/apiserver/metadata/BUILD.bazel
backend/src/apiserver/metadata/metadata_store.go
backend/src/apiserver/metadata/metadata_store_test.go
backend/src/apiserver/storage/BUILD.bazel

These tests check for correct recording of metadata (specifically those
produced by TFX components).
Also, ensure that we check for non-nil values of output parameter values
before attempting to parse the value for metadata.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1030)

Add more tests for metadata store.

---

sdk/python/tests/compiler/compiler_tests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1048)

Fix compiler unit test bug

---

proxy/Dockerfile

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1054)

add license file to proxy agent docker image

---

components/third_party_licenses.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1056)

add licenses for katib-launcher

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1083)

Update CHANGELOG for release 0.1.15

---

components/local/confusion_matrix/component.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1091)

Added "Target lambda" parameter to "Confusion matrix" component

---

sdk/python/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1107)

incremented app version

---

.cloudbuild.yaml

Fixes https://github.com/kubeflow/pipelines/issues/1123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1124)

Fixed CloudBuild failure

---

test/deploy-kubeflow.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1143)

use kubeflow/pipelines branch for deployment in test

---

backend/src/apiserver/storage/job_store.go
backend/src/apiserver/storage/job_store_test.go
backend/src/apiserver/storage/run_store.go
backend/src/apiserver/storage/run_store_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1151)

fix missing filter for list call

---

samples/resnet-cmle/resnet-train-pipeline.py

Fixes #1142
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1154)

bug fix in resnet sample

---

samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py

Moving the pipeline to use components, as well as some minor changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1148)

using comp yaml for ffdl pipeline

---

components/ibm-components/ffdl/serve/README.md
components/ibm-components/ffdl/train/README.md

Component READMEs for IBM OSS components
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1147)

component readmes

---

sdk/python/kfp/_client.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1178)

SDK/Client - Stopped extracting pipeline file to disk during submission

---

samples/OWNERS

have been reviewing quite a few, and should be able to handle general review for sample pipleines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1174)

adding myself as reviewer for samples

---

samples/basic/parallel_join.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1110)

Updated the "Basic - Parallel execution" sample

---

samples/basic/sequential.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1112)

Updated the "Basic - Sequential execution" sample

---

samples/basic/recursion.py

/label area/samples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1113)

Updated the "Basic - Recursive loop" sample

---

samples/tfx/taxi-cab-classification-pipeline.py

/label area/samples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1115)

Updated the "TFX Taxi Cab Classification Pipeline" sample

---

components/arena/docker/arena_launcher.py
components/arena/python/arena/_arena_mpi_op.py
components/arena/python/arena/_arena_standalone_op.py
samples/arena-samples/standalonejob/standalone_pipeline.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1179)

Update arena component with git support

---

contrib/components/openvino/ovms-deployer/containers/requirements.txt

See https://nvd.nist.gov/vuln/detail/CVE-2019-10906
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1193)

Updated vulnerable package

---

components/dataflow/predict/component.yaml
components/dataflow/tfdv/component.yaml
components/dataflow/tfma/component.yaml
components/dataflow/tft/component.yaml
components/gcp/dataflow/launch_python/README.md
components/gcp/dataflow/launch_python/sample.ipynb
components/gcp/dataproc/submit_hive_job/README.md
components/gcp/dataproc/submit_hive_job/sample.ipynb
components/kubeflow/deployer/component.yaml
components/kubeflow/dnntrainer/component.yaml
components/kubeflow/katib-launcher/component.yaml
components/local/confusion_matrix/component.yaml
components/local/roc/component.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1206)

update types to defined core type names

---

test/postsubmit-tests-with-pipeline-deployment.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1210)

Testing - Fixed the postsubmit tests

---

samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py

simplifying params based on @Ark-kun suggestion for ffdl-train-serve pipeline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1230)

simplifying-ffdl-params

---

samples/tfx-oss/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1245)

fix the link for tfx taxi example

---

test/presubmit-tests-with-pipeline-deployment.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1249)

remove unnecessary args

---

frontend/src/lib/StatusUtils.test.tsx
frontend/src/lib/StatusUtils.ts
frontend/src/lib/Utils.test.ts
frontend/src/lib/Utils.ts
frontend/src/lib/WorkflowParser.test.ts
frontend/src/lib/WorkflowParser.ts
frontend/src/pages/ExperimentList.test.tsx
frontend/src/pages/ExperimentList.tsx
frontend/src/pages/RunDetails.test.tsx
frontend/src/pages/RunDetails.tsx
frontend/src/pages/RunList.test.tsx
frontend/src/pages/RunList.tsx
frontend/src/pages/Status.test.tsx
frontend/src/pages/Status.tsx

Fixes #1236 
Bug fix code is line 79 of `Utils.ts`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1262)

Pulls most functions out of Status and into StatusUtils

---

components/release.sh

The script now clones clean repo, makes the changes and commits them.
Then it optionally pushes the changes to a new release branch and even opens the web-browser with a pull request page ready.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1172)

Automated the component image release script

---

test/deploy-pipeline.sh
test/presubmit-tests-with-pipeline-deployment.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1279)

keep the api image name consistent between the presubmit test and staging

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1296)

changelog for v0.1.19

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1275)

Tests/Travis - Simplified the Python SDK package installation

---

.cloudbuild.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1277)

Release - Simplified python package building

---

backend/Dockerfile.scheduledworkflow

this config allow specifying what namespace the persistent agent listen to
/assign @ywskycn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1309)

expose namespace config for scheduled workflow

---

test/OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1312)

Adding myself to test owners

---

components/dataflow/predict/src/setup.py
components/dataflow/tfdv/src/validation/setup.py
components/dataflow/tfma/src/analysis/setup.py
components/kubeflow/dnntrainer/src/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1315)

update tf version to 1.12.1

---

components/release.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1328)

switch the release script from staging to test

---

test/postsubmit-tests-with-pipeline-deployment.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1322)

ml-pipeline-test has a cb job

---

sdk/python/setup.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1330)

bump kfp version in sdk

---

component_sdk/python/setup.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1329)

bump kfp version in component sdk

---

test/postsubmit-tests-with-pipeline-deployment.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1333)

add argo install in postsubmit

---

components/arena/docker/job_generator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1337)

check if data and env format

---

.cloudbuild.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1336)

update proxy image build path

---

manifests/base/pipeline/ml-pipeline-ui-role.yaml

to reflect change here
https://github.com/kubeflow/kubeflow/pull/3255/files#diff-a843466b38824bfb7c7053bf4d4a6bf7R158
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1350)

update kfp ui rbac permission

---

frontend/src/components/UploadPipelineDialog.test.tsx
frontend/src/components/UploadPipelineDialog.tsx

Fixes #1340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1349)

Trim the file extension from suggested pipeline names

---

sdk/python/kfp/dsl/_ops_group.py

A fix of a docstring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1356)

Fix docstring for _ops_group Condition

---

backend/api/swagger/kfp_api_single_file.swagger.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1408)

add single API swagger json file

---

sdk/python/kfp/_client.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1403)

update DSL client documentation

---

component_sdk/python/kfp_component/google/bigquery/_query.py

Fix #1343
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1399)

set dataset_location as the default location.

---

frontend/server/package-lock.json
frontend/server/package.json
frontend/server/server.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1415)

Updates Google Cloud Storage and pins axios version

---

manifests/base/kustomization.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1424)

Update pipeline version in KFP manifest to 0.1.21 https://github.com/kubeflow/pipelines/releases/tag/0.1.21

---

manifests/base/argo/workflow-controller-configmap.yaml
manifests/base/argo/workflow-controller-deployment.yaml
manifests/base/kustomization.yaml
manifests/namespaced-install.yaml
manifests/namespaced-install/workflow-controller-configmap.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1425)

Manifests: Update Argo version to v2.3.0

---

test/install-argo.sh
test/minikube/install_argo_client.sh
test/minikube/install_docker_minikube_argo.sh
test/sample-test/run_test.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1427)

Testing - Updated Argo CLI to v2.3.0

---

manifests/base/kustomization.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1431)

enable proxy by default

---

WORKSPACE
go.mod
go.sum

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1428)

Backend - Updated Argo package from v2.3.0 RC to final version

---

components/third_party_licenses.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1445)

Added license URL for google-cloud-datastore

---

test/frontend-integration-test/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1457)

Pin selenium chrome version

---

test/frontend-integration-test/OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1447)

Add rileyjbauer as to frontend integration tests OWNERS

---

.travis.yml
sdk/python/tests/run_tests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1200)

SDK - Improved test script compatibility with editable package installation

---

component_sdk/python/kfp_component/google/ml_engine/_create_job.py

Fix #1456
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1459)

Output default job_dir.txt file

---

sdk/python/kfp/gcp.py

Fixes https://github.com/kubeflow/pipelines/issues/1376
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1379)

SDK - Use different volume names for different secrets

---

manifests/README.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1454)

update manifest/ readme

---

OWNERS

/assign @vicaire 
Realized I'm not able to approve any PRs. Feel free to push back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1503)

Add myself as a approver/reviewer.

---

samples/ibm-samples/watson/watson_train_serve_pipeline.py

There are few updates with the Watson components in the past week and we need to update the pipeline to the latest commit to reflect those changes.
/assign @animeshsingh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1533)

Update Watson pipeline component source to the latest commit

---

frontend/mock-backend/fixed-data.ts
frontend/src/lib/CompareUtils.test.ts
frontend/src/lib/CompareUtils.ts
frontend/src/pages/Compare.tsx
frontend/src/pages/RunDetails.tsx
frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap

Screenshot using dummy data:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1530)

Add metrics table to run details page, run outputs tab

---

sdk/python/kfp/_client.py

Fixes https://github.com/kubeflow/pipelines/issues/1130
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1535)

SDK/Client - Added the upload_pipeline API

---

component_sdk/python/setup.py
manifests/base/kustomization.yaml
manifests/namespaced-install.yaml
sdk/python/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1538)

increment sdk versions

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1492)

add issue template

---

sdk/python/kfp/_client.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1543)

SDK/Client - Add optional parameter "name" to upload_pipeline method

---

sdk/python/kfp/dsl/_pipeline_volume.py
sdk/python/kfp/notebook/_magic.py
sdk/python/tests/dsl/pipeline_volume_tests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1550)

configurable timeout and namespace in docker magic

---

manifests/base/kustomization.yaml
manifests/namespaced-install.yaml
sdk/python/setup.py

Also updates `setup.py`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1567)

Update manifests for 0.1.23

---

components/gcp/bigquery/query/component.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1579)

Pass dataset_location to container

---

sdk/python/kfp/compiler/compiler.py
sdk/python/tests/compiler/testdata/recursive_while.py
sdk/python/tests/compiler/testdata/recursive_while.yaml

Fixing https://github.com/kubeflow/pipelines/issues/1582
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1583)

fix recursion bug

---

manifests/base/pipeline/pipeline-runner-role.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1576)

Add PV/PVC admin permission for pipeline runner

---

sdk/python/kfp/compiler/compiler.py

fixing https://github.com/kubeflow/pipelines/issues/1615
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1616)

fix dependency bug in the recursion support

---

component_sdk/python/setup.py
manifests/base/kustomization.yaml
manifests/namespaced-install.yaml
sdk/python/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1617)

update manifest and sdk version

---

components/aws/OWNERS
samples/aws-samples/OWNERS

We have a intern help add and refine aws components and examples. Add me and Igor to the OWNERS file to help review and approve AWS specific changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1633)

Add OWNERS file in aws components and examples

---

sdk/python/kfp/dsl/_volume_op.py

Closes #1593.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1595)

SDK/DSL: Fix bug when specifying custom resource for VolumeOp

---

.travis.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1649)

update python test to use python3

---

sdk/python/kfp/compiler/_component_builder.py
sdk/python/tests/compiler/testdata/kaniko.basic.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1652)

update kaniko executor version to speed up image build

---

components/third_party_licenses.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1655)

Fix broken license link

---

frontend/src/lib/Apis.test.ts
frontend/src/lib/Apis.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1675)

Add visualization API service to frontend

---

samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb

Remove some redundant imports from a notebook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1656)

Remove redundant import.

---

component_sdk/python/setup.py
manifests/base/kustomization.yaml
sdk/python/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1674)

Increase KFP version in (1) sdk/python/setup.py (2) component_sdk/python/setup.py (3) manifests/base/kustomization.yaml

---

manifests/namespaced-install.yaml

Missed this change in the previous PR https://github.com/kubeflow/pipelines/pull/1674
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1684)

Increase version in namespaced-install.yaml too

---

samples/OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1705)

add jxzheng to the reviewers for samples

---

backend/api/build_kfp_server_api_python_package.sh

Fixes https://github.com/kubeflow/pipelines/issues/1685
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1686)

API - Updated swagger-codegen-cli version

---

backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/apiserver/server/job_server.go
backend/src/apiserver/server/job_server_test.go

Such jobs will be placed within the Default experiment
Part of #1266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1702)

Allows creation of jobs without experiments

---

sdk/python/kfp/components/_python_op.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1671)

SDK/Lightweight - Updated default image to tensorflow:1.13.2-py3

---

backend/src/apiserver/client_manager.go
backend/src/apiserver/config.go
backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/storage/object_store.go
backend/src/apiserver/storage/object_store_fake.go
backend/src/apiserver/storage/object_store_util.go

Add env var for single part support.
AddFile will have the option to send single part. for backend which doesn't support multipart.
in order to use it change ObjectStoreConfig.Disable.Multipart value to true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1713)

Support Single part PutFile

---

backend/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1733)

fix cloudbuild failure

---

.cloudbuild.yaml
.release.cloudbuild.yaml

see the title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1764)

remove copying the samples since we are not releasing the samples in the GCS

---

.cloudbuild.yaml
.release.cloudbuild.yaml
backend/src/apiserver/visualization/third_party_licenses.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1738)

Add Visualization Server to Cloud Build yaml Files

---

backend/Dockerfile.visualization

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1783)

Fixed Dockerfile used for buildVisualizationServer in Cloud Build

---

sdk/python/kfp/compiler/_component_builder.py
sdk/python/kfp/compiler/_container_builder.py
sdk/python/kfp/compiler/_k8s_helper.py
sdk/python/tests/compiler/testdata/kaniko.basic.yaml

Image building functions now return image name with digest: image_repo@sha256:digest
Fixes https://github.com/kubeflow/pipelines/issues/1715
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1768)

SDK - Containers - Returning image name with digest

---

backend/Dockerfile
backend/Dockerfile.persistenceagent
backend/Dockerfile.scheduledworkflow
backend/Dockerfile.viewercontroller

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1788)

skip storing log to files

---

frontend/server/package-lock.json
frontend/server/package.json
test/frontend-integration-test/package-lock.json
test/frontend-integration-test/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1798)

Fix github security alert.

---

backend/test/integration/run_api_test.go

Temporarily addresses https://github.com/kubeflow/pipelines/issues/1762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1809)

Disable flaky tests temporarily

---

.cloudbuild.yaml

Fixes https://github.com/kubeflow/pipelines/issues/1815
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1816)

Build - Fix CloudBuild bug

---

sdk/python/kfp/compiler/compiler.py
sdk/python/tests/compiler/testdata/add_pod_env.yaml
sdk/python/tests/compiler/testdata/artifact_location.yaml
sdk/python/tests/compiler/testdata/basic.yaml
sdk/python/tests/compiler/testdata/coin.yaml
sdk/python/tests/compiler/testdata/compose.yaml
sdk/python/tests/compiler/testdata/default_value.yaml
sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
sdk/python/tests/compiler/testdata/param_op_transform.yaml
sdk/python/tests/compiler/testdata/param_substitutions.yaml
sdk/python/tests/compiler/testdata/pipelineparams.yaml
sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
sdk/python/tests/compiler/testdata/recursive_do_while.yaml
sdk/python/tests/compiler/testdata/recursive_while.yaml
sdk/python/tests/compiler/testdata/resourceop_basic.yaml
sdk/python/tests/compiler/testdata/retry.yaml
sdk/python/tests/compiler/testdata/sidecar.yaml
sdk/python/tests/compiler/testdata/timeout.yaml
sdk/python/tests/compiler/testdata/volume.yaml
sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml
sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
sdk/python/tests/compiler/testdata/volumeop_basic.yaml
sdk/python/tests/compiler/testdata/volumeop_dag.yaml
sdk/python/tests/compiler/testdata/volumeop_parallel.yaml
sdk/python/tests/compiler/testdata/volumeop_sequential.yaml

Fixes https://github.com/kubeflow/pipelines/issues/448
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1381)

SDK - Preserving the pipeline input information in the compiled Workflow

---

samples/core/model_serving_component/model_serving_component.ipynb

Adding a new sample for in cluster serving using kfp serving component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1830)

Adding a sample for serving component

---

components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_create_version.py
samples/core/kubeflow_pipeline_using_TFX_OSS_components/KubeFlow Pipeline Using TFX OSS Components.ipynb

fixing https://github.com/kubeflow/pipelines/issues/1862
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1863)

update gcloud ml-engine to ai-platform

---

components/gcp/container/component_sdk/python/setup.py
sdk/python/setup.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1860)

Update Python SDK versions for release.

---

.release.cloudbuild.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1871)

Remove copying of tfx data for cloudbuild release steps.

---

manifests/kustomize/base/kustomization.yaml
manifests/kustomize/namespaced-install.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1870)

Update manifests to point to 0.26 release.

---

sdk/python/kfp/compiler/_container_builder.py
sdk/python/tests/compiler/container_builder_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1892)

fix unit tests and address some comments

---

sdk/python/kfp/components/modelbase.py
sdk/python/tests/components/test_structure_model_base.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1874)

SDK - Components - Fixed ModelBase comparison bug

---

manifests/kustomize/namespaced-install.yaml

To include recent added components. 
/assign @ajchili
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1926)

update namespaced-install.yaml 

---

OWNERS
backend/OWNERS
components/OWNERS
sdk/OWNERS
test/api-integration-test/OWNERS
test/imagebuilder/OWNERS
test/initialization-test/OWNERS
third_party/OWNERS

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1928)

clean up owner file

---

sdk/python/kfp/compiler/_op_to_template.py
sdk/python/kfp/dsl/_container_op.py
sdk/python/tests/compiler/compiler_tests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1886)
Fix #1884

Support Affinity for ContainerOps

---

manifests/kustomize/namespaced-install.yaml

/assign @ajchili
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1932)

sync namespaced install file

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1935)

Update changelog for 0.1.27

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml

/assign @ajchili
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1980)

update kubeflow pipelines application name

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1996)

pass pipeline runner service account to api server

---

.release.cloudbuild.yaml

As required in here.
https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/managed-updates.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2005)

update release CB to copy images to marketplace compliant location

---

backend/src/apiserver/main.go
backend/src/apiserver/server/visualization_server.go
backend/src/apiserver/server/visualization_server_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2004)

Changed isVisualizationServiceAlive implementation to not block API server startup

---

.release.cloudbuild.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2008)

fix cb for release

---

.release.cloudbuild.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2022)

update release cb yaml

---

sdk/python/kfp/compiler/compiler.py
sdk/python/tests/compiler/testdata/coin.yaml
sdk/python/tests/compiler/testdata/recursive_do_while.yaml
sdk/python/tests/compiler/testdata/recursive_while.yaml

Fixes https://github.com/kubeflow/pipelines/issues/1950
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2043)

SDK - Compiler - Fixed dsl.Condition when parameter resolves to string with spaces

---

envoy-entrypoint.sh
envoy.Dockerfile
frontend/src/components/Router.tsx
frontend/src/components/SideNav.tsx
frontend/src/components/__snapshots__/Router.test.tsx.snap
frontend/src/components/__snapshots__/SideNav.test.tsx.snap
frontend/src/pages/ExecutionDetails.tsx
frontend/src/pages/ExecutionList.tsx

Still needs tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2059)

Add execution list and details pages

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/schema.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2065)

fixes name inconsistency for marketplace manifest and bump kfp version

---

components/deprecated/dataflow/base/build_image.sh
components/deprecated/dataflow/predict/build_image.sh
components/deprecated/dataflow/tfdv/build_image.sh
components/deprecated/dataflow/tfma/build_image.sh
components/deprecated/dataflow/tft/build_image.sh
components/deprecated/dataproc/analyze/build_image.sh
components/deprecated/dataproc/base/build_image.sh
components/deprecated/dataproc/create_cluster/build_image.sh
components/deprecated/dataproc/delete_cluster/build_image.sh
components/deprecated/dataproc/predict/build_image.sh
components/deprecated/dataproc/train/build_image.sh
components/deprecated/dataproc/transform/build_image.sh

Fixes CloudBuild failures after https://github.com/kubeflow/pipelines/pull/2031
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2063)

Release - Fixed the deprecated component image build

---

manifests/gcp_marketplace/schema.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2079)

Expose DB username to marketplace schema.yaml

---

frontend/src/pages/NewRun.test.tsx
frontend/src/pages/NewRun.tsx
frontend/src/pages/__snapshots__/NewRun.test.tsx.snap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2016)

Add warning message when there are empty parameters in NewRun.tsx

---

components/gcp/container/component_sdk/python/setup.py
sdk/python/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2100)

update sdk versions

---

sdk/python/kfp/compiler/_component_builder.py

fixing https://github.com/kubeflow/pipelines/issues/2108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2107)

fix bug: list.pop() is not expecting keyword arg

---

manifests/kustomize/namespaced-install.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2111)

update kustomize(for 0.1.30 release)

---

sdk/python/kfp/components/_python_op.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2035)

SDK - Lightweigh - Made wrapper code compatible with python2

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/proxy.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
manifests/gcp_marketplace/schema.yaml

Move service accounts out of schema.yaml
Fixes for marketplace server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2122)

A few fixes for Marketplace manifests

---

frontend/src/pages/ExecutionDetails.tsx

Before the fix: https://drive.google.com/file/d/1LJbth1bK-_ZCTe5d60M8nDRzrFjgux-n/view
After the fix: https://drive.google.com/file/d/1grx6CHhWKlkBbhpJJ1QXZh-AK-pMkb1D/view
/cc @neuromage 
/kind bug
part of https://github.com/kubeflow/pipelines/issues/2086
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2127)

Fix execution detail page fetch params.

---

.gitignore

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2123)

Update gitignore to ignore all .iml files

---

sdk/python/kfp/containers/_build_image_api.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2116)

SDK - Containers - Fixed kfp.containers.get_default_image_builder

---

manifests/gcp_marketplace/README.md

/assign @rmgogogo @erikerlandson @sarahmaddox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2128)

Add documentation for Marketplace CLI deployment

---

sdk/python/kfp/compiler/_component_builder.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2143)

SDK - Components - Fixed build_python_component

---

test/sample-test/configs/retry.config.yaml
test/sample-test/run_sample_test.py
test/sample_test.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2141)

add retry tests

---

backend/OWNERS

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2164)

Update backend owner file

---

frontend/src/components/ResourceInfo.tsx
frontend/src/pages/ArtifactDetails.tsx
frontend/src/pages/ExecutionDetails.tsx

video: https://drive.google.com/file/d/1fASKYbU0JJPnV16MhE8J9EjbmiSYQOpb/view
@neuromage WDYT?
Part of https://github.com/kubeflow/pipelines/issues/2086
/kind feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2157)

Add URI to artifact details page

---

test/OWNERS

/assign @Bobgy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2166)

Add Bobgy to test infra owner

---

components/kubeflow/kfserving/component.yaml
components/kubeflow/kfserving/src/kfservingdeployer.py

Updating kfserving pipeline for custom action
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2102)

kfserving pipeline update

---

third_party/OWNERS

/assign @dushyanthsc @Bobgy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2168)

Update owner for thirdparty

---

backend/src/crd/controller/viewer/reconciler/reconciler.go
backend/src/crd/controller/viewer/reconciler/reconciler_test.go

Fixes #2131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2140)

Use latest Tensorflow image for Tensorboard.

---

.cloudbuild.yaml
.release.cloudbuild.yaml
third_party/metadata_envoy/Dockerfile
third_party/metadata_envoy/README.md
third_party/metadata_envoy/dependencies.json
third_party/metadata_envoy/dependency_helper.py
third_party/metadata_envoy/envoy.yaml

Change to introduce building metadata-envoy docker image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2178)

metadata-envoy: Build script for metadata-envoy docker image

---

third_party/metadata_envoy/Dockerfile

/assign @dushyanthsc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2197)

update dockerfile for envoy

---

third_party/metadata_envoy/Dockerfile

/assign @dushyanthsc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2200)

fix envoy dockerfile

---

sdk/python/kfp/components/_python_op.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2194)

SDK - Removed some dead code

---

.release.cloudbuild.yaml
manifests/kustomize/README.md

/assign @numerology
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2204)

fix release CB and update readme

---

sdk/python/kfp/components/_python_op.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2193)

SDK - Components - Simplified arg-parsing code using argparse.SUPPRESS

---

sdk/python/kfp/gcp.py
sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml

Fixes #1796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2205)

add support for hard and soft constraint in the preemptible nodepools

---

manifests/kustomize/README.md

/cc @jingzhang36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2217)

Fix pipeline lite README

---

docs/source/kfp.containers.rst
docs/source/kfp.rst
sdk/python/kfp/containers/_build_image_api.py

And fixed the docstring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2182)

Docs - Added kfp.containers module

---

.release.cloudbuild.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2214)

fix release cloud build YAML to generate pipeline-lite YAML

---

.release.cloudbuild.yaml

Verified it's working now. This should be the final fix. 
/assign @Bobgy 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2231)

Fix publishing deploy YAML in .release.cloudbuild.yaml

---

sdk/python/kfp/notebook/_magic.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2266)

SDK - Notebooks - Deprecated the docker magic

---

sdk/python/kfp/compiler/_data_passing_rewriter.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2259)

SDK - Compiler - Fixed small bug in data passing rewriter

---

sdk/python/kfp/gcp.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2280)

Remove usage of deprecated ContainerOp methods in use_gcp_secret

---

components/gcp/dataproc/create_cluster/README.md

@hongye-sun I have edited these please review. Add facets at line 12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2285)

tech writer edits

---

components/gcp/ml_engine/deploy/component.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2296)

Add CMLE deploy comment missing parameters

---

sdk/python/kfp/components/_python_op.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2257)

SDK - Components - Deprecate the get and set methods for default image in favor of plain variable

---

backend/src/apiserver/visualization/third_party_licenses.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2344)

[License] Fix third-party license

---

manifests/gcp_marketplace/guide.md

Fix a typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2342)

[Doc] Fix a typo in MKP guide

---

samples/core/ai_platform/ai_platform.ipynb

use python -m pip to install packages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2349)

Fix potential issue of the ai platform sample when running it in the ai platform notebook

---

components/gcp/dataproc/create_cluster/README.md
components/gcp/dataproc/create_cluster/component.yaml
components/gcp/dataproc/create_cluster/sample.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2366)

Components - Updated the gcp dataproc create_cluster component image

---

samples/OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2371)

[Samples] Add numerology as samples/OWNERS

---

backend/src/apiserver/config/sample_config.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2361)

[Doc] Fix some description of preload samples

---

components/kubeflow/kfserving/OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2380)

add animesh to the approvers of the kfserving

---

test/sample-test/configs/dataflow.config.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2387)

enable the check for dataflow

---

components/kubeflow/kfserving/src/kfservingdeployer.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2390)

quick custom spec fix

---

samples/core/ai_platform/ai_platform.ipynb

Fixes #2399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2400)

[Test/Sample test] Fix model version in AI platform sample

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2190)

Added the backend Go module cache to .gitignote

---

components/gcp/container/component_sdk/python/setup.py
manifests/kustomize/base/kustomization.yaml
sdk/python/kfp/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2434)

Update sdk release version

---

sdk/python/kfp/_client.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2438)

SDK - Client - Makes the create_run output nicer

---

manifests/gcp_marketplace/OWNERS

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2436)

Add owner files for marketplace deployment

---

sdk/python/kfp/aws.py
sdk/python/kfp/azure.py
sdk/python/tests/compiler/testdata/withitem_basic.py
sdk/python/tests/compiler/testdata/withitem_basic.yaml
sdk/python/tests/compiler/testdata/withitem_nested.py
sdk/python/tests/compiler/testdata/withitem_nested.yaml
sdk/python/tests/compiler/testdata/withparam_global.py
sdk/python/tests/compiler/testdata/withparam_global.yaml
sdk/python/tests/compiler/testdata/withparam_global_dict.py
sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
sdk/python/tests/components/test_components.py
sdk/python/tests/components/test_graph_components.py
sdk/python/tests/components/test_python_op.py
sdk/python/tests/dsl/aws_extensions_tests.py
sdk/python/tests/dsl/test_azure_extensions.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2336)

SDK - Tests - Fixed most of the test warnings

---

CONTRIBUTING.md

/cc @numerology 
/area docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2464)

[Frontend] Update CONTRIBUTING.md with frontend code style info

---

manifests/gcp_marketplace/deployer/Dockerfile

/assign @rmgogogo @numerology
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2484)

update base image to fix the GKE GC issue for marketplace deployment

---

frontend/mock-backend/fixed-data.ts
frontend/src/components/Description.test.tsx
frontend/src/components/Description.tsx
frontend/src/pages/NewRun.tsx
frontend/src/pages/PipelineDetails.tsx
frontend/src/pages/PipelineList.tsx
frontend/src/pages/__snapshots__/NewRun.test.tsx.snap

Fixes https://github.com/kubeflow/pipelines/issues/154
changes:
* added mock data with a pipeline description in markdown
* Fixed typo: Description
* changed description to markdown
* changed dialog styling to make it wider
for actual code change avoiding formatting issues, read this [link](https://github.com/kubeflow/pipelines/pull/2494/commits/04fd834ebadedc3b2b9e326bdcb00ffd0e96401c)
screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2494)

Enlarge choose pipeline dialog to show more description

---

samples/core/tfx-oss/README.md
samples/core/tfx-oss/TFX Example.ipynb

to prevent confusion like #2475
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2499)

[Sample] Replace deprecated KubeflowRunner in TFX sample

---

manifests/kustomize/base/crds/viewer-crd.yaml

/assign @Bobgy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2511)

clean up viewer crd spec

---

manifests/kustomize/base/pipeline/ml-pipeline-ui-rolebinding.yaml

/assign @Bobgy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2510)

remove unnecessary namespace in UI rolebinding spec

---

release/OWNERS
release/RELEASE.md

The format of releasing note is copied from TFX repo. Any suggestions are welcome. Also, added a OWNER file so development could be more agile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2549)

[Misc] Add releasing note

---

sdk/python/kfp/cli/cli.py
sdk/python/kfp/cli/diagnose_me_cli.py

This change is to add the diagnose_me command to CLI tool. This will allow users to run the command via 
` kfp diagnose_me `
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2543)

Adding diagnose_me to CLI tool

---

sdk/python/kfp/dsl/_artifact_location.py
sdk/python/kfp/dsl/_container_op.py
sdk/python/tests/compiler/testdata/artifact_location.py
sdk/python/tests/compiler/testdata/artifact_location.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2326)

SDK - DSL - Deprecated ArtifactLocation

---

components/kubeflow/kfserving/src/kfservingdeployer.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2551)

Fix wrong kfserving url

---

components/gcp/container/component_sdk/python/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2565)

Increase kfp version in component sdk

---

manifests/kustomize/base/kustomization.yaml
sdk/python/kfp/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2567)

Increase kfp version in kustomize and sdk init

---

backend/api/experiment.proto
backend/api/job.proto
backend/api/pipeline.proto
backend/api/run.proto

Re-submitting several changes that were made for the now-closed [PR 2483](https://github.com/kubeflow/pipelines/pull/2483), just focusing on comments for the runservice endpoints and link update for filter.proto.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2550)

MDez patch 1

---

samples/core/helloworld/hello_world.py

/assign @gaoning777 @Ark-kun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2583)

Add a minimum sample to print hello world

---

samples/core/pipeline_transformers/pipeline_transformers.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2592)

Fix transformer sample message

---

components/gcp/container/component_sdk/python/setup.py
manifests/kustomize/base/kustomization.yaml
sdk/python/kfp/__init__.py

Changes:
* bump sdk version
https://github.com/kubeflow/pipelines/pull/2599 should be merged first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2598)

Bump version to 0.1.35

---

manifests/kustomize/OWNERS

I think I have enough knowledge to own manifests changes. WDYT? This will facilitate future release process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2600)

Add Bobgy to OWNERS of kustomize manifests

---

CHANGELOG.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2608)

Changelog of 0.1.35 release

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2613)

add community meeting/slack onto README

---

samples/contrib/seldon/mnist_tf.py
samples/contrib/seldon/mnist_tf_volume.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2597)

Fix error tfjob definition

---

frontend/src/components/UploadPipelineDialog.test.tsx
frontend/src/components/UploadPipelineDialog.tsx

Mitigates https://github.com/kubeflow/pipelines/issues/2596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2630)

[UI] Trim pipeline upload url before sending to backend

---

sdk/python/kfp/components/structures/components.proto
sdk/python/kfp/components/structures/generate_proto_code.sh

This PR adds a .proto version of the JsonSchema component spec (#669).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2636)

SDK - Protobuf version of the component schema

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
manifests/gcp_marketplace/cli.md
manifests/gcp_marketplace/schema.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2656)

Mkp better release - SemVersion

---

components/gcp/container/component_sdk/python/setup.py
manifests/kustomize/base/kustomization.yaml
sdk/python/kfp/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2661)

Bump version to 0.1.36

---

.travis.yml

After https://github.com/kubernetes/test-infra/pull/15381 is merged, we can merge this.
@IronPan Can you help me approve?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2647)

Remove travis CI frontend tests

---

developer_guide.md

fixes https://github.com/kubeflow/pipelines/issues/2675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2681)

fix visualization-server doc link

---

manifests/kustomize/base/kustomization.yaml
sdk/python/kfp/__init__.py
sdk/python/kfp/_client.py
sdk/python/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2701)

update server and sdk version to 0.1.37

---

third_party/cli/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2707)

Improve golang license CLI tools README

---

backend/src/apiserver/client_manager.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2715)

update kfam service host env variable

---

.travis.yml

Recent coverage upgrade break Travis CI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2740)

[Test] Pin the versions of coverage and coveralls

---

backend/src/apiserver/main.go
backend/src/apiserver/server/job_server.go
backend/src/apiserver/server/visualization_server.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2733)

temporarily disable the jobservice in the multi-user mode

---

.cloudbuild.yaml
components/release.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2736)

Build - Fix building TF images

---

sdk/python/kfp/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2734)

SDK - Bump version to 0.1.38

---

frontend/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2776)

Fix vscode README of prettier integration

---

manifests/kustomize/README.md

to 0.1.38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2785)

[Manifest] Bump standalone deployment version in doc

---

manifests/kustomize/base/kustomization.yaml
sdk/python/kfp/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2799)

release 0.1.39

---

frontend/server/aws-helper.ts
frontend/server/configs.ts
frontend/server/k8s-helper.ts
frontend/server/minio-helper.ts
frontend/server/package-lock.json
frontend/server/package.json
frontend/server/utils.ts
frontend/server/workflow-helper.ts

Fix typing problems when I try to run node server unit tests locally.
This is initial step to https://github.com/kubeflow/pipelines/issues/2808
/area frontend
/kind bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2807)

Fix node server typing problems

---

backend/Dockerfile
test/sample-test/Dockerfile
test/sample_test.yaml

Should fix #2811
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2813)

Pin pyarrow version

---

components/OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2804)

add jiaxiao to the component owners

---

frontend/server/handlers/gke-metadata.ts
frontend/start-proxy-standalone-and-server.sh
frontend/start-proxy-standalone.sh

/cc @avdaredevil
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2836)

[UI] Simplify start server script and fix local cluster name endpoint

---

manifests/kustomize/base/proxy/kustomization.yaml

Fix https://github.com/kubeflow/pipelines/issues/2848
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2849)

Opt out proxy agent configmap

---

components/tfx/_samples/TFX_pipeline.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2867)

Samples - Updated the TFX-KFP pipeline

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
manifests/gcp_marketplace/schema.yaml
manifests/kustomize/base/kustomization.yaml
manifests/kustomize/base/pipeline-application.yaml
manifests/kustomize/base/proxy/kustomization.yaml
sdk/python/kfp/__init__.py

we introduced MLMD writer and also renamed MLMD configmap. it requires version bump.
After so many months hard working to introduce so many new feature, also worth a minor version bump
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2872)

from 0.1.40 to 0.2.0

---

manifests/gcp_marketplace/schema.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2878)

fix the metadata writer manifest

---

backend/Dockerfile
backend/src/apiserver/config/sample_config.json

Part of https://github.com/kubeflow/pipelines/issues/2721#issuecomment-565287314
/cc @Ark-kun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2880)

Pin sample doc links during backend image build

---

test/OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2890)

Add numerology to test OWNERS

---

components/diagnostics/diagnose_me/component.py
components/diagnostics/diagnose_me/component.yaml

This is a diagnose_me component based on the diagnose_me libraries that verifies bucket , API and Auth for a given project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2948)

diagnose me component

---

backend/Dockerfile
backend/src/apiserver/config/sample_config.json
samples/tutorials/DSL - Control structures/DSL - Control structures.py
samples/tutorials/Data passing in python components/Data passing in python components - Files.py

Add the "Data passing in python components" tutorial and the combined "DSL control structures" tutorial.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2944)

Samples - Add and change preloaded samples

---

frontend/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2959)

[Doc] Improve vscode settings documentation

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/schema.yaml
manifests/kustomize/base/kustomization.yaml
manifests/kustomize/base/pipeline-application.yaml
sdk/python/kfp/__init__.py

/assign @numerology
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2961)

Bump version for release 0.2.1 of Pipelines

---

frontend/package-lock.json
frontend/package.json

/cc @kwasi 
/cc @rmgogogo 
Creating a new PR to quickly approve to get into next release. Supercedes https://github.com/kubeflow/pipelines/pull/2970.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2976)

[Frontend] Use latest kf frontend with bug fixes

---

backend/src/apiserver/visualization/third_party_licenses.csv
components/third_party_licenses.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2975)

[License] Another license fix

---

manifests/gcp_marketplace/deployer/Dockerfile
manifests/gcp_marketplace/deployer/init_action.sh
manifests/gcp_marketplace/deployer/overlay_deploy.sh
manifests/gcp_marketplace/deployer/overlay_deploy_with_tests.sh

1. work for "mpdev verify"
2. correct exit code
3. check whether already created
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2980)

fix for Init Action

---

components/third_party_licenses.csv

See [here](https://pantheon.corp.google.com/cloud-build/builds/7b774665-ddcd-472c-969c-39f754c503b2;step=26?organizationId=433637338589&project=ml-pipeline-test)
```
--2020-02-04 13:55:38--  https://raw.githubusercontent.com/GoogleCloudPlatform/google-cloud-python/master/pubsub/LICENSE
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-04 13:55:38 ERROR 404: Not Found.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2982)

Another license fix

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2962)

Update changelog for 0.2.1 release.

---

components/third_party_licenses.csv

This should fix the components build bits.
Let's see if there's anything remaining.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2984)

Another fix of licenses

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/schema.yaml
manifests/kustomize/base/kustomization.yaml
manifests/kustomize/base/pipeline-application.yaml
sdk/python/kfp/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2988)

bump version to 0.2.2

---

sdk/OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3006)

Add numerology to SDK owner

---

frontend/src/pages/GettingStarted.tsx

/area frontend
/kind bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3012)

[UI] Fix starting page casing

---

backend/Dockerfile
backend/src/apiserver/config/sample_config.json

Unpin the tfx notebook sample from 0.1.40
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3002)

[Sample] Update notebook sample link

---

samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb

Update module file to latest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3017)

[Samples] Update TFX module file

---

.travis.yml

This PR fixes travis build failure issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3035)

Fix build failure

---

sdk/python/kfp/cli/diagnose_me/gcp.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3052)

Adding auth list support for diagnose_me

---

backend/src/apiserver/config/sample_config.json

To better accommodate hosted beta situation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3034)

[Samples] Update preloaded samples' descriptions

---

backend/src/apiserver/visualization/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3060)

update TFDV to 0.21.1 which can work for Chrome 80

---

backend/src/apiserver/visualization/third_party_licenses.csv
frontend/src/lib/Apis.ts
frontend/src/lib/Buttons.ts
frontend/src/pages/NewPipelineVersion.tsx
frontend/src/pages/PipelineDetails.tsx
frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap

UI of https://github.com/kubeflow/pipelines/issues/2977
demo: https://youtu.be/3dLjggHFqxg
TODO: add unit tests
/area frontend
/priority p0
/kind feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3059)

[UI] Upload pipeline version from local package

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/schema.yaml
manifests/kustomize/README.md
manifests/kustomize/base/kustomization.yaml
manifests/kustomize/base/pipeline-application.yaml
sdk/python/kfp/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3072)

update version from 0.2.2 to 0.2.3 for kfp

---

backend/Dockerfile.visualization
backend/src/apiserver/visualization/requirements.txt

https://github.com/kubeflow/pipelines/issues/3079
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3083)

Pin Pyarrow version to 0.15.1 after we upgrade to use tfdv 0.21.1

---

components/diagnostics/diagnose_me/component.py
components/diagnostics/diagnose_me/component.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3075)

quick fix for quota list

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md

Changes:
1. add /kind bug label for reporter
2. adjust steps section to first section, because I think natural mental order is describing what they did to reproduce the bug, then describe result and expected result
Update:
1. Added a section to let users tell their environment (versions)
2. Added area labels to let users assign areas by themselves
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3081)

[Community] Improve BUG_REPORT.md

---

samples/core/xgboost_training_cm/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3092)

[Doc] Call out quota requirement in XGBoost sample

---

WORKSPACE

Fixes https://github.com/kubeflow/pipelines/issues/2468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2856)

Backend - Removed Tensorflow from backend WORKSPACE

---

frontend/package-lock.json
frontend/package.json

/hold
/assign @kwasi 
/priority p0
Hold for https://github.com/kubeflow/frontend/pull/44.
Updates version of kubeflow/frontend to pickup fix for inaccurate Lineage lines reported in the KFP bug bash.
See description in https://github.com/kubeflow/frontend/pull/39 and https://github.com/kubeflow/frontend/pull/44.
https://6d1629804d56a867-dot-us-central2.pipelines.googleusercontent.com/#/artifact_types/Examples/artifacts/2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3102)

[Lineage] Update kubeflow/frontend to latest hash to pick up bug bash fixes

---

backend/Dockerfile
backend/src/apiserver/visualization/requirements.txt
test/sample-test/Dockerfile

Reference, avro-python3 issue is already fixed in https://issues.apache.org/jira/browse/AVRO-2737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3096)

Remove pinning avro-python3, because it is already fixed

---

backend/Dockerfile
samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
test/sample-test/Dockerfile

from 0.21.0rc to 0.21.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3121)

Bump TFX dependency

---

sdk/python/kfp/compiler/compiler.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3122)

SDK - Compiler - Fix incompatibility with python3.5

---

samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3125)

[Sample] typo fix

---

samples/core/parameterized_tfx_oss/README.md
samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3127)

[Sample] update README

---

.travis.yml
backend/Dockerfile
test/sample-test/Dockerfile

for tfx-bsl bumped its version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3146)

[Test] Turn back on TFX unit test

---

frontend/src/pages/GettingStarted.tsx
frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap

Link to GitHub code rather than the notebook opening page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3150)

Update 'TFX demo link'

---

frontend/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3147)

[Frontend] Pin links in getting started page when release

---

frontend/package.json
frontend/src/__serializers__/mock-function.js
frontend/src/atoms/Hr.tsx
frontend/src/atoms/IconWithTooltip.tsx
frontend/src/atoms/Input.tsx
frontend/src/atoms/Separator.tsx
frontend/src/atoms/__snapshots__/MD2Tabs.test.tsx.snap
frontend/src/components/DetailsTable.tsx
frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
frontend/src/components/__snapshots__/PlotCard.test.tsx.snap
frontend/src/components/__snapshots__/Trigger.test.tsx.snap
frontend/src/components/__snapshots__/UploadPipelineDialog.test.tsx.snap
frontend/src/components/viewers/__snapshots__/VisualizationCreator.test.tsx.snap
frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
frontend/src/pages/__snapshots__/Archive.test.tsx.snap
frontend/src/pages/__snapshots__/Compare.test.tsx.snap
frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
frontend/src/pages/__snapshots__/NewExperiment.test.tsx.snap
frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap
frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
frontend/src/pages/__snapshots__/PipelineVersionList.test.tsx.snap
frontend/src/pages/__snapshots__/RecurringRunDetails.test.tsx.snap
frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
frontend/src/pages/__snapshots__/RunList.test.tsx.snap

Changes:
1. MockFunction no longer serialize in snapshots.
2. Anonymous function components are properly named now.
Unblocks https://github.com/kubeflow/pipelines/pull/3156
/area frontend
/area engprod
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3159)

[Frontend] Prepare snapshot updates for cra migration

---

backend/api/build_kfp_server_api_python_package.sh
backend/api/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_version_parameters.go
backend/api/swagger/kfp_api_single_file.swagger.json
backend/api/swagger/pipeline.upload.swagger.json

1. Added the pipelineid parameter in swagger json.
2. Reran the swagger codegen for Backend
3. TODO: will rerun codegen for Frontend as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3160)

Fix a missing query parameter in swagger json file for version upload api

---

backend/src/apiserver/config/sample_config.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3144)

Fix broken doc link

---

test/images/README.md

Per offline discussion, move to ml-pipeline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3151)

[Test] Update doc about image position

---

manifests/gcp_marketplace/guide.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3097)

nit: Add BigQuery role

---

backend/src/apiserver/client_manager.go
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml

Reverts kubeflow/pipelines#3168
Reference: https://github.com/kubeflow/pipelines/commit/5cb158d3130ac4f68d2923c198fa602116fe33f9#commitcomment-37539034
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3192)

Revert "minio: Set secure=true to enable TLS by default"

---

sdk/python/kfp/__main__.py
sdk/python/kfp/_client.py
sdk/python/kfp/cli/pipeline.py

- Implementation of `delete` pipeline command
- Check local environment like below 
```
❯ kfp pipeline list
+--------------------------------------+--------------------------------------------------------+---------------------------+
| Pipeline ID                          | Name                                                   | Uploaded at               |
+======================================+========================================================+===========================+
| 25e3aefb-a6b5-4125-9a20-cc8616d61938 | hello_world                                            | 2020-01-20T07:22:23+00:00 |
+--------------------------------------+--------------------------------------------------------+---------------------------+
| 4f308d97-f994-416d-ab98-c27f6e5d4919 | …
```

SDK/CLI: Implement CLI delete pipeline command

---

.cloudbuild.yaml

fixes #3244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3245)

Fix ill-formed Cloud Build config

---

.travis.yml

Since we have backend unit tests in prow test (kubeflow-pipeline-backend-test)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3264)

Remove backend unit tests from Travis config

---

frontend/package-lock.json
frontend/package.json
frontend/server/package-lock.json

/area frontend
/area engprod
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3281)

[Frontend] Fix reported vulnerabilities

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/kustomize/base/argo/workflow-controller-configmap.yaml
manifests/kustomize/env/gcp/gcp-configurations-patch.yaml
manifests/kustomize/namespaced/workflow-controller-configmap.yaml

Improve log persistence especially in on-prem scenarios.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3301)

Enable archiving logs

---

samples/core/exit_handler/exit_handler.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3306)

Remove unused parameter

---

sdk/python/kfp/compiler/_op_to_template.py
sdk/python/kfp/components/_structures.py
sdk/python/kfp/components/structures/components.json_schema.json
sdk/python/kfp/components/structures/components.json_schema.outline.yaml
sdk/python/kfp/dsl/_container_op.py
sdk/python/tests/compiler/compiler_tests.py
sdk/python/tests/components/test_graph_components.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3318)

SDK - Added support for maxCacheStaleness

---

sdk/python/tests/components/test_python_op.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3325)

SDK - Tests - Moved imports to the start of the file

---

sdk/python/kfp/compiler/_k8s_helper.py
sdk/python/kfp/compiler/_op_to_template.py
sdk/python/kfp/dsl/_container_op.py
sdk/python/kfp/dsl/_pipeline_param.py
sdk/python/kfp/dsl/_resource_op.py
sdk/python/setup.py

Fixes https://github.com/kubeflow/pipelines/issues/3275
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3319)

SDK - Support kubernetes client v11

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/schema.yaml
manifests/kustomize/README.md
manifests/kustomize/base/kustomization.yaml
manifests/kustomize/base/pipeline-application.yaml
sdk/python/kfp/__init__.py
sdk/python/requirements.txt
sdk/python/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3329)

Bump version to 0.3.0

---

.release.cloudbuild.yaml

/assign @neuromage 
/assign @Bobgy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3331)

Reduce steps for release cloud build yaml

---

sdk/python/kfp/_client.py

This change depends on 
1. kfp-server-api > 0.2.6 (pending next release to include #3198)
1. Backend implementation #3243 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3272)

[SDK][Multi-user] Add namespace to experiment SDK calls

---

frontend/server/app.test.ts
frontend/server/app.ts

Resolves https://github.com/kubeflow/pipelines/issues/3293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3334)

[UI Server] Blocks non public KFP report APIs

---

sdk/python/tests/components/test_python_op.py
sdk/python/tests/dsl/component_bridge_tests.py

Added test_fail_on_handling_list_arguments_containing_python_objects
Added test_handling_list_arguments_containing_serializable_python_objects
Moved test_handling_list_arguments_containing_pipelineparam to component_bridge_tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3326)

SDK - Tests - Improved tests for serializing lists containing objects

---

frontend/server/k8s-helper.ts

I introduced a bug when parsing the image for Tensorboard in https://github.com/kubeflow/pipelines/pull/3235. This fixes it.
cc @Bobgy

Fix Tensorboard viewer image parsing

---

backend/src/apiserver/client_manager.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3132)

apiserver: Handle BucketExists() error

---

third_party/metadata_envoy/envoy.yaml

(introduced by another PR this week)

quick fix envoy proxy service name

---

samples/core/iris/iris.py

enable native Keras + TFMA visualization

enable native Keras + TFMA

---

components/aws/sagemaker/Dockerfile
components/aws/sagemaker/LICENSE.txt
components/aws/sagemaker/NOTICE.txt
components/aws/sagemaker/THIRD-PARTY-LICENSES.txt

Added license file
and updated the Dockerfile to use AmazonLinux

AWS sagemaker : Added license files and updated Dockerfile to use AmazonLinux

---

backend/src/apiserver/common/config.go
backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/server/run_server_test.go

/cc @chensun 
First step of https://github.com/kubeflow/pipelines/issues/3415

[Backend] Keep workflow service account when not default or empty

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/schema.yaml
manifests/kustomize/README.md
manifests/kustomize/base/kustomization.yaml
manifests/kustomize/base/pipeline-application.yaml
sdk/python/kfp/__init__.py

[Release] update version

---

test/presubmit-tests-mkp.sh

presubmit for MKP/Hosted
It's not enabled in Prow yet. It can be run before submit a PR.

presubmit for MKP/Hosted

---

test/deploy-pipeline-lite.sh

After 0.4.0 release this TODO should be filled.

[Test] fix upgrade test

---

components/aws/sagemaker/batch_transform/README.md
components/aws/sagemaker/deploy/README.md
components/aws/sagemaker/model/README.md

Added READMEs for the following components:
- CreateModel
- CreateEndpoint
- CreateTransformJob
Tip: md files can be hard to review in a PR diff, please click options -> View file to see the rendered content for each md file in the pull request

Update documentation for AWS components

---

frontend/package-lock.json
frontend/package.json
frontend/server/package-lock.json

/area frontend
/area engprod
/kind bug
Fixes https://github.com/kubeflow/pipelines/issues/3302

[Frontend] Fix npm reported vulnerabilities

---

frontend/src/lib/KubeflowClient.tsx
frontend/src/pages/Compare.test.tsx
frontend/src/pages/Compare.tsx
frontend/src/pages/ExperimentDetails.tsx
frontend/src/pages/RunDetails.test.tsx
frontend/src/pages/RunDetails.tsx

/area frontend
/kind feature
Part of https://github.com/kubeflow/pipelines/issues/3296
/cc @chensun

[UI] Redirect to experiment list page when namespace changes in RunDetails or Compare page

---

samples/core/ai_platform/ai_platform.ipynb
samples/core/lightweight_component/lightweight_component.ipynb

Adding some changes to 'lightweight component' and 'ai platform' sample notebooks. These are being integrated into a Self-Paced lab on the Qwiklabs platform and will be executed on a Cloud AI Platform notebook, note Kubeflow notebook server.
Changes are minor and make them more suitable and understandable in that environment.

Qwiklab caip updates

---

WORKSPACE
backend/src/apiserver/client/BUILD.bazel
backend/src/apiserver/server/BUILD.bazel
backend/src/cache/BUILD.bazel
backend/src/cache/client/BUILD.bazel
backend/src/cache/model/BUILD.bazel
backend/src/cache/server/BUILD.bazel
backend/src/cache/storage/BUILD.bazel

updated/generated by running `bazel run //:gazelle -- update-repos --from_file=go.mod`
/cc @rui5i @Ark-kun

Upadate backend BUILD files

---

backend/src/apiserver/server/visualization_server.go

Lift the multi-user check, so that visualization server at least works with shared permission.

[Backend][Multi-user] Reenable visualization server in multi-user mode

---

manifests/gcp_marketplace/deployer/init_action.sh

one project share one default bucket

one GCP project share one default bucket

---

backend/metadata_writer/src/metadata_helpers.py
backend/metadata_writer/src/metadata_writer.py

Fixes https://github.com/kubeflow/pipelines/issues/3462

Metadata Writer - Log pod names

---

sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/components/_yaml_utils.py

See the root cause explanation in https://github.com/kubeflow/pipelines/issues/3519
Fixes https://github.com/kubeflow/pipelines/issues/3519
Fixes https://github.com/kubeflow/pipelines/issues/2495

SDK - Made YAML dumping more awesome

---

components/third_party_licenses.csv

To fix the cloud build error: https://pantheon.corp.google.com/cloud-build/builds/bbec4fd2-bb41-4759-bcbe-6dab7db1496a?project=ml-pipeline-test

add missing license for component image

---

test/check-build-image-status.sh

Thanks for helping figuring out the root cause!
Fixes https://github.com/kubeflow/pipelines/issues/3532

[Testing] Fix not waiting for api server cloudbuild

---

backend/metadata_writer/src/metadata_helpers.py

Fixes https://github.com/kubeflow/pipelines/issues/3552

Services - Metadata Writer - Added support for custom_properties in all helper methods

---

manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
manifests/kustomize/base/cache/cache-deployment.yaml
manifests/kustomize/base/kustomization.yaml
manifests/kustomize/base/metadata/metadata-writer-deployment.yaml
manifests/kustomize/base/params.env
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
manifests/kustomize/env/gcp/inverse-proxy/proxy-deployment.yaml
test/deploy-pipeline-lite.sh
test/manifests/cluster-scoped-resources/kustomization.yaml
test/manifests/dev/kustomization.yaml

1. kubectl -k can't work with kustomize edited version
2. varRef can't work with kustomize edit image
here parameterize imagePrefix. It actually helps a lot for other clean-up work very well, although not kustomize-native solution.

Fix test which uses Kustomize edit image but can't work with valueRef

---

backend/src/apiserver/server/experiment_server.go
backend/src/apiserver/server/experiment_server_test.go

As a follow up on #3417, in single-user mode, if user passes non-empty namespace to `CreateExperiment` and `ListExperiments` request, api-server should return errors.
Runs and Jobs APIs are in a different situation. In single-user mode, by default, Runs and Jobs are in the "kubeflow" namespace, so it is a legit request to list runs or jobs filtering by non-empty namespace.

[Backend] In signle-user mode, reject experiment API requests with non-empty user namespace

---

samples/core/ai_platform/local/Chicago Crime Research.ipynb

Ran into some issues running this notebook, seemed to just be some minor package issues.

Minor updates to packages

---

backend/metadata_writer/src/metadata_helpers.py
backend/metadata_writer/src/metadata_writer.py

Fixes https://github.com/kubeflow/pipelines/issues/3552

Metadata  Writer - Fixed pod name property setting

---

frontend/src/apis/experiment/api.ts
frontend/src/apis/visualization/api.ts
frontend/src/lib/Apis.ts
frontend/src/lib/OutputArtifactLoader.ts
frontend/src/pages/RunDetails.tsx

/cc @chensun 
Fixes https://github.com/kubeflow/pipelines/issues/2899

[UI] Migrate to namespaced visualization request

---

frontend/src/lib/StatusUtils.test.tsx
frontend/src/lib/StatusUtils.ts
frontend/src/lib/WorkflowParser.ts
frontend/src/pages/Status.tsx
frontend/src/pages/__snapshots__/Status.test.tsx.snap

Fixes https://github.com/kubeflow/pipelines/issues/2904
Demo: https://youtu.be/Zb4CA1G8dxE

[UI] Show cached steps

---

backend/src/apiserver/client_manager.go

* Add index on run details on experiment UUID & conditions & finished time, for better use

Add index on run details on experiment UUID & conditions & finished time

---

backend/src/cache/server/mutation.go

I think we should still have the label in place. We'll very likely need it later.

[Caching] Add a cached label for cached pods

---

sdk/python/kfp/components/_python_op.py
sdk/python/tests/components/test_python_op.py

This is pretty useful and multiple TFX components already have optional inputs.

SDK - Enabled file inputs to be optional

---

proxy/attempt-register-vm-on-proxy.sh

fix https://github.com/kubeflow/pipelines/issues/3143

fix proxy URL issue

---

components/gcp/container/component_sdk/python/kfp_component/google/common/_utils.py

Properly handle LRO error case

---

.travis.yml

Fixes https://github.com/kubeflow/pipelines/issues/3689

Fixed the TFX conflicts in tests

---

frontend/package-lock.json
frontend/package.json

/cc @rmgogogo 
Includes upstream fixes:
* https://github.com/kubeflow/frontend/pull/47
* https://github.com/kubeflow/frontend/pull/49
Fixes https://github.com/kubeflow/pipelines/issues/3625
Fixes https://github.com/kubeflow/pipelines/issues/3648

[UI] Update @kubeflow/frontend with fixes for #3625 and #3648

---

backend/src/cache/deployer/deploy-cache-service.sh

The grep version seems to be different in the base image

Cache - Fixed the cache deployer script

---

sdk/python/kfp/containers/_gcs_helper.py

Fixes https://github.com/kubeflow/pipelines/issues/3674

3674: check if gcs bucket exist before creation

---

frontend/src/lib/Buttons.ts

Remove an accidentally committed debugging log

---

sdk/python/kfp/compiler/_op_to_template.py
sdk/python/kfp/dsl/_component_bridge.py
sdk/python/tests/compiler/compiler_tests.py

This preserves the information about the digest of the component and the location from which the component was loaded.

SDK - Annotate pods with component_ref

---

manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
manifests/kustomize/base/cache/cache-deployment.yaml
manifests/kustomize/base/cache/kustomization.yaml
manifests/kustomize/base/kustomization.yaml
manifests/kustomize/base/metadata/metadata-writer-deployment.yaml
manifests/kustomize/base/params.env
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
manifests/kustomize/env/gcp/inverse-proxy/proxy-deployment.yaml
test/deploy-pipeline-lite.sh
test/manifests/dev/kustomization.yaml

/cc @IronPan 
Part of https://github.com/kubeflow/pipelines/issues/2884
> Images listed in kustomization.yaml: required

[Manifest] Use kustomize native image transformer to override image

---

docs/source/kfp.client.rst

Fixes https://github.com/kubeflow/pipelines/issues/3216

Client - Added documentation for the generated members

---

sdk/python/kfp/_client.py

Fixes https://github.com/kubeflow/pipelines/issues/3825

Client - Allow specifying pipeline description when uploading

---

components/aws/sagemaker/ground_truth/component.yaml
components/aws/sagemaker/tests/integration_tests/README.md
components/aws/sagemaker/tests/integration_tests/component_tests/test_groundtruth_component.py
components/aws/sagemaker/tests/integration_tests/component_tests/test_workteam_component.py
components/aws/sagemaker/tests/integration_tests/conftest.py
components/aws/sagemaker/tests/integration_tests/resources/config/create-workteam/config.yaml
components/aws/sagemaker/tests/integration_tests/resources/config/image-classification-groundtruth/config.yaml
components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-endpoint/config.yaml
components/aws/sagemaker/tests/integration_tests/resources/definition/groundtruth_pipeline.py
components/aws/sagemaker/tests/integration_tests/resources/definition/workteam_pipeline.py
components/aws/sagemaker/tests/integration_tests/utils/kfp_client_utils.py
components/aws/sagemaker/tests/integration_tests/utils/sagemaker_utils.py

(Copy of PR #3771 )
This PR adds integration tests for following components:
1. SageMaker WorkTeam
2. SageMaker GroundTruth
Todo:
- Add a bot for groundtruth labeling
- Remove the extra comments from the code.
- Also fixes a minor bug in the GroundTruth component.yaml file.

[AWS SageMaker] Integration Test for AWS SageMaker GroundTruth Component

---

components/XGBoost/Predict/component.py
components/XGBoost/Predict/component.yaml
components/XGBoost/Train/component.py
components/XGBoost/Train/component.yaml
components/XGBoost/_samples/sample_pipeline.py

* Train
* Predict
* Sample pipeline

Components - XGBoost

---

proxy/attempt-register-vm-on-proxy.sh

revert the fix in proxy-agent to make sure hostname won't be changed
It means the issue in https://github.com/kubeflow/pipelines/issues/3143 should be fixed in proxy-server side.

revert the fix in proxy-agent to make sure hostname won't be changed

---

components/_converters/ApacheParquet/_samples/sample_pipeline.py
components/_converters/ApacheParquet/from_ApacheArrowFeather/component.py
components/_converters/ApacheParquet/from_ApacheArrowFeather/component.yaml
components/_converters/ApacheParquet/from_CSV/component.py
components/_converters/ApacheParquet/from_CSV/component.yaml
components/_converters/ApacheParquet/from_TSV/component.py
components/_converters/ApacheParquet/from_TSV/component.yaml
components/_converters/ApacheParquet/to_ApacheArrowFeather/component.py
components/_converters/ApacheParquet/to_ApacheArrowFeather/component.yaml

Added components that convert to and from Apache Parquet data format

Components - Apache Parquet converters

---

.travis.yml

Depends on https://github.com/kubeflow/pipelines/pull/3837

Testing - Fixed skipped SDK Travis tests

---

sdk/python/kfp/dsl/_container_op.py

* Modify docstrings to replace 'InitContainer' to 'UserContainer'
* Related PR: https://github.com/kubeflow/pipelines/pull/1650

Modify docstrings to replace 'InitContainer' to 'UserContainer'

---

components/pipeline_component_repository.yaml

Added a marker file that marks the location of a repository of Kubeflow Pipelines components.
This marker file makes it easier to find public repositories online.

Components - Added the pipeline component repository marker file

---

samples/core/AutoML tables/AutoML Tables - Retail product stockout prediction.ipynb
samples/core/dataflow/dataflow.ipynb
samples/core/exit_handler/exit_handler.py
samples/core/iris/iris.py
samples/core/parallel_join/parallel_join.py
samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
samples/core/secret/secret.py
samples/core/sequential/sequential.py
samples/core/xgboost_training_cm/xgboost_training_cm.py

...because the playground bucket was intended to be unstable, and subject to change.

[Samples] Change the data url to point to ml-pipeline instead of ml-pipeline-playground

---

docs/source/kfp.client.rst

Fixes https://github.com/kubeflow/pipelines/issues/3216

Docs - Added docs for kfp_server_api.models

---

backend/api/go_http_client/experiment_client/experiment_service/list_experiment_parameters.go
backend/api/go_http_client/job_client/job_service/list_jobs_parameters.go
backend/api/go_http_client/pipeline_client/pipeline_service/list_pipeline_versions_parameters.go
backend/api/go_http_client/pipeline_client/pipeline_service/list_pipelines_parameters.go
backend/api/go_http_client/run_client/run_service/list_runs_parameters.go
backend/api/python_http_client/docs/ExperimentServiceApi.md
backend/api/python_http_client/docs/JobServiceApi.md
backend/api/python_http_client/docs/PipelineServiceApi.md
backend/api/python_http_client/docs/RunServiceApi.md
backend/api/python_http_client/kfp_server_api/api/experiment_service_api.py
backend/api/python_http_client/kfp_server_api/api/job_service_api.py
backend/api/python_http_client/kfp_server_api/api/pipeline_service_api.py
backend/api/python_http_client/kfp_server_api/api/run_service_api.py
backend/api/swagger/experiment.swagger.json
backend/api/swagger/job.swagger.json
backend/api/swagger/kfp_api_single_file.swagger.json
backend/api/swagger/pipeline.swagger.json
backend/api/swagger/run.swagger.json

[Api] Regenerate clients after proto description des -> desc fix

---

manifests/gcp_marketplace/cli.md

To address https://github.com/kubeflow/pipelines/issues/3382 . (I know things are going to get an overhaul, but I still think it's useful to update it here).

create cluster using 'cloud-platform' scope

---

.cloudbuild.yaml
.release.cloudbuild.yaml
RELEASE.md
manifests/kustomize/hack/release.sh
sdk/python/requirements.in
sdk/python/setup.py

Part of https://github.com/kubeflow/pipelines/issues/3729
Fixes https://github.com/kubeflow/pipelines/issues/3919

[Release] Various fixes to release script

---

.cloudbuild.yaml

Fixes https://github.com/kubeflow/pipelines/issues/3000

[Release] Fix missing $TAG_NAME in .cloudbuild.yaml

---

.cloudbuild.yaml

Cherry pick #3924: [Release] Fix $(cat VERSION) not in bash script

---

OWNERS

Add Bobgy to OWNERS

---

backend/src/common/util/workflow.go

Fixes https://github.com/kubeflow/pipelines/issues/3939

Only pending or running workflows are considered not-final

---

sdk/python/kfp/compiler/_default_transformers.py

(cherry picked from commit 7fbb7cae567d24e766ae851cc494b8db0f239e54)

Cherry picking #3934

---

backend/src/common/util/workflow.go

* only pending or running workflows are considered not-final
* rephrase comment

CherryPick: Only pending or running workflows are considered not-final (#3940)

---

hack/format.sh
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/hack/format.sh
manifests/gcp_marketplace/schema.yaml
manifests/kustomize/base/kustomization.yaml
manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
manifests/kustomize/hack/format.sh

Part of #3729 
This makes yaml files that need to be automated during release conformed to the tool's auto format.
Also added a script to automate this:
```
./hack/format.sh
```

[Format] Format yaml files that will be automated

---

sdk/python/kfp/compiler/compiler.py

Fixes https://github.com/kubeflow/pipelines/issues/3367

SDK - Compiler - Made compiler compatible with @wraps

---

RELEASE.md

/assign @jingzhang36 @Ark-kun @rmgogogo

[Doc] Cherry pick process for release branch

---

manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml
manifests/kustomize/base/pipeline/ml-pipeline-ui-service.yaml
manifests/kustomize/env/platform-agnostic/minio/minio-service.yaml
manifests/kustomize/env/platform-agnostic/mysql/mysql-service.yaml

These are requirements for enabling multi user mode in kubeflow 1.1

chore(manifests): add missing port name and other cleanups

---

RELEASE.md

/assign @jingzhang36 @rmgogogo

doc(release): detailed release steps and commands

---

sdk/python/kfp/_client.py
sdk/python/kfp/cli/pipeline.py

Implementation of pipeline list-versions command.
`kfp pipeline list-versions <version_id>`
It may help when using run command as the version id may be provided to run a specific version of a pipeline.
```
$ kfp pipeline list
+--------------------------------------+-------------------------------------------------+---------------------------+
| Pipeline ID                          | Name                                            | Uploaded at               |
+======================================+=================================================+===========================+
| 33e7e535-b4f5-4a5c-857e-c017f9abf905 | my_pipeline                                     | 2020-06-05T09:10:05+00:00 |
+--------------------------------------+-------------------------------------------------+-------- …
```

SDK/CLI: Implement CLI pipeline list-versions command

---

components/aws/sagemaker/Changelog.md
components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
components/aws/sagemaker/batch_transform/component.yaml
components/aws/sagemaker/deploy/component.yaml
components/aws/sagemaker/ground_truth/component.yaml
components/aws/sagemaker/hyperparameter_tuning/component.yaml
components/aws/sagemaker/model/component.yaml
components/aws/sagemaker/process/component.yaml
components/aws/sagemaker/train/component.yaml
components/aws/sagemaker/workteam/component.yaml

Update the component fields to use the new 0.4.1 release version

[AWS SageMaker] Component 0.4.1 Release

---

.cloudbuild.yaml
.release.cloudbuild.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml
test/tag_for_hosted.sh

Change to upgrade Metadata store to use Metadata grpc server image version 0.22.1

MetadataStore:Update metadata grpc server image to use version 0.22.1

---

components/third_party_licenses.csv

Fix build-per-commit cloudbuild job
**Checklist:**
- Do you want this PR cherry picked to release branch?
If yes, please either
* ask the approver to add label `cherrypick-approved`, so that release manager
will handle it in batch
* or create a cherry pick PR to the release branch after this PR is merged
(You can refer to [RELEASE.md](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option---git-cherry-pick) for how to do it.)

chore: fix subprocess32 license url

---

manifests/gcp_marketplace/hack/release.sh
manifests/gcp_marketplace/schema.yaml

chore(marketplace): fix version in release note

---

backend/metadata_writer/requirements.in
backend/metadata_writer/requirements.txt

This change updates Metadata writer to use MLMD library version 0.22.0

Metadata-Writer: Updates metadata writer to use mlmd 0.22.0

---

RELEASE.md

/assign @rmgogogo @jingzhang36

chore(release): instructions for updating version in kubeflow.org

---

components/aws/sagemaker/Changelog.md
components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
components/aws/sagemaker/batch_transform/component.yaml
components/aws/sagemaker/batch_transform/src/batch_transform.py
components/aws/sagemaker/common/_utils.py
components/aws/sagemaker/deploy/component.yaml
components/aws/sagemaker/ground_truth/component.yaml
components/aws/sagemaker/hyperparameter_tuning/component.yaml
components/aws/sagemaker/model/component.yaml
components/aws/sagemaker/process/component.yaml
components/aws/sagemaker/process/src/process.py
components/aws/sagemaker/train/component.yaml
components/aws/sagemaker/train/src/train.py
components/aws/sagemaker/workteam/component.yaml

Print SageMaker job logs from cloudwatch in kfp UI
Prints logs for Training, Transform and processing job
https://github.com/kubeflow/pipelines/issues/3744
https://github.com/kubeflow/pipelines/issues/3670

[AWS SageMaker] Print SageMaker job logs in kfp UI

---

sdk/python/kfp/_client.py

Allows the user to list available pipeline versions for a given pipeline id.

[SDK] Add list_pipeline_versions to kfp.Client

---

backend/metadata_writer/src/metadata_writer.py

Fixes https://github.com/kubeflow/pipelines/issues/4036

Metadata Writer - Added timeouts

---

backend/src/apiserver/config/sample_config.json
frontend/src/config/sample_config_from_backend.json
frontend/src/pages/GettingStarted.test.tsx
frontend/src/pages/GettingStarted.tsx
frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap

1. TensorBoard is added in TFX repo (google3)
2. Adjust sequence in this PR

better native-keras based sample

---

components/XGBoost/Predict/component.py
components/XGBoost/Predict/component.yaml
components/XGBoost/Train/component.py
components/XGBoost/Train/component.yaml

The built-in parser does not understand headers.

Components - XGBoost - Parsing CSV using pandas

---

components/XGBoost/Predict/from_ApacheParquet/component.py
components/XGBoost/Predict/from_ApacheParquet/component.yaml
components/XGBoost/Train/from_ApacheParquet/component.py
components/XGBoost/Train/from_ApacheParquet/component.yaml
components/XGBoost/_samples/sample_pipeline.py

The existing trainer and predictor only work with CSV.

Components - XGBoost - Train and Predict from Apache Parquet

---

components/pandas/Transform_DataFrame/_samples/sample_pipeline.py
components/pandas/Transform_DataFrame/in_ApacheParquet_format/component.py
components/pandas/Transform_DataFrame/in_ApacheParquet_format/component.yaml
components/pandas/Transform_DataFrame/in_CSV_format/component.py
components/pandas/Transform_DataFrame/in_CSV_format/component.yaml

One of the scenarios was not working due to variable scoping.

Components - pandas - Transform DataFrame - Fixed transforms that replace dataframe

---

components/ml_metrics/Calculate_regression_metrics/_samples/sample_pipleine.py
components/ml_metrics/Calculate_regression_metrics/from_CSV/component.py
components/ml_metrics/Calculate_regression_metrics/from_CSV/component.yaml

The metrics are:
max_absolute_error
mean_absolute_error
mean_squared_error
root_mean_squared_error

Components - Calculate_regression_metrics

---

sdk/python/kfp/compiler/compiler.py

Fixes https://github.com/kubeflow/pipelines/issues/4021

SDK - Compiler - Fixed error message

---

.travis.yml

Updated the argo binary version

test(sdk): Travis - Fixed pipeline validation

---

components/XGBoost/_samples/recursive_training.py

This pipeline demonstrates continuous training using a train-eval-check recursive loop.
The main pipeline trains the initial model and then gradually trains the model some more until the model evaluation metrics are good enough.

Components - XGBoost - Added the recursive training pipeline

---

sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml
sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml

Fixes https://github.com/kubeflow/pipelines/issues/4102
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to …

test(sdk) Restored the ParallelFor compiler test data

---

sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/dsl/_component.py
sdk/python/tests/compiler/compiler_tests.py

fix(sdk): Compiler - Fixed the input argument mapping when using dsl.graph_component. Fixes #3915

---

RELEASE.md

introduce release schedule, refine instructions
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the …

docs(release): introduce release schedule, refine instructions

---

components/aws/sagemaker/tests/unit_tests/run_all_tests.sh
components/aws/sagemaker/tests/unit_tests/tests/test_batch_transform.py
components/aws/sagemaker/tests/unit_tests/tests/test_deploy.py
components/aws/sagemaker/tests/unit_tests/tests/test_ground_truth.py
components/aws/sagemaker/tests/unit_tests/tests/test_hpo.py
components/aws/sagemaker/tests/unit_tests/tests/test_model.py
components/aws/sagemaker/tests/unit_tests/tests/test_process.py
components/aws/sagemaker/tests/unit_tests/tests/test_train.py
components/aws/sagemaker/tests/unit_tests/tests/test_utils.py
components/aws/sagemaker/tests/unit_tests/tests/test_workteam.py

Add unit test to check the util function which prints  cloudwatch logs for components 
Also removed unused imports

[AWS SageMaker] Add unit tests for cloudwatch logs 

---

backend/OWNERS
components/OWNERS
manifests/kustomize/OWNERS
proxy/OWNERS
samples/OWNERS
sdk/OWNERS
test/OWNERS
third_party/OWNERS

Remove inactive reviewers from OWNERS, so that external PRs are assigned to active maintainers.
**Checklist:**

chore: remove inactive reviewers

---

components/aws/sagemaker/Changelog.md
components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
components/aws/sagemaker/batch_transform/component.yaml
components/aws/sagemaker/common/_utils.py
components/aws/sagemaker/deploy/component.yaml
components/aws/sagemaker/ground_truth/component.yaml
components/aws/sagemaker/hyperparameter_tuning/component.yaml
components/aws/sagemaker/model/component.yaml
components/aws/sagemaker/process/component.yaml
components/aws/sagemaker/tests/unit_tests/tests/test_ground_truth.py
components/aws/sagemaker/train/component.yaml
components/aws/sagemaker/workteam/component.yaml

Added more region lambda ARNs to the algorithm map as per the SageMaker documentation: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_labeling_job
Closes #3916

[AWS SageMaker] GroundTruth Pre/Post Lambda function region additions

---

backend/src/apiserver/visualization/third_party_licenses.csv
components/third_party_licenses.csv

```
--2020-07-02 02:18:01--  https://raw.githubusercontent.com/kjd/idna/master/LICENSE.rst
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-02 02:18:01 ERROR 404: Not Found.
```
Fix build failure
**Checklist:**
Use `chore` to indicate that …

chore: fix kjd/idna license location change

---

sdk/python/requirements-test.txt
sdk/python/setup.py

test(sdk): SDK - Added the mock package to the test requirements

---

test/presubmit-tests-sdk.sh

tests: Presubmits - Added presubmit unit tests for KFP SDK

---

test/presubmit-backend-visualization.sh

test: Added presubmit unit tests for the backend visualizations

---

components/diagnostics/diagnose_me/component.yaml
components/git/clone/component.yaml
components/google-cloud/storage/list/component.yaml
sdk/python/kfp/dsl/_component_bridge.py
sdk/python/tests/dsl/component_bridge_tests.py

Volatile components do not reuse the cached results by default.
The pipeline authors can re-enable cache reuse if they want.
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the …

feat(sdk): DSL - Added support for volatile components

---

backend/Dockerfile
samples/core/iris/iris.py

Fixes https://github.com/kubeflow/pipelines/issues/4117
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to …

chore(backend): Only compiling the preloaded samples. Fixes #4117

---

manifests/gcp_marketplace/schema.yaml

Updated schema.yaml with wording and branding changes.
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the …

docs(deployment): Suggested wording changes for schema.yaml.

---

test/presubmit-tests-tfx.sh

test: Presubmits - Added presubmit tests against TFX

---

sdk/python/kfp/_client.py

**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to …

fix(sdk): Fix get_experiment when there are no experiments. Fixes #4176

---

backend/src/cache/deployer/deploy-cache-service.sh

cache-deployer should check both secret and config
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the …

fix(cache): cache-deployer should check both secret and config

---

manifests/kustomize/env/gcp/cloudsql-proxy/cloudsql-proxy-deployment.yaml
manifests/kustomize/env/gcp/cloudsql-proxy/cloudsql-proxy-sa.yaml
manifests/kustomize/env/gcp/cloudsql-proxy/kustomization.yaml
manifests/kustomize/env/gcp/minio-gcs-gateway/kustomization.yaml
manifests/kustomize/env/gcp/minio-gcs-gateway/minio-gcs-gateway-deployment.yaml
manifests/kustomize/env/gcp/minio-gcs-gateway/minio-gcs-gateway-sa.yaml
manifests/kustomize/gcp-workload-identity-setup.sh

Fixes #4183
These deployments need GCP permissions and we recommend workload identity. So each of them should have their own service account.
**Checklist:**
* **(Recommended.)** Ask the PR approver to …

fix(deployment): gcp - add service account to deployments that need workload identity. Fixes #4183

---

sdk/python/kfp/_client.py

Fixes https://github.com/kubeflow/pipelines/issues/4189
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to …

fix(sdk): fixes the default value for _is_refresh_token. Fixes #4189

---

sdk/python/kfp/compiler/_op_to_template.py
sdk/python/tests/compiler/compiler_tests.py

Fixes https://github.com/kubeflow/pipelines/issues/4163

feat(sdk): SDK - Enable placeholders in task display names. Fixes #4163

---

test/sample-test/sample_test_launcher.py

Part of #4189 
component image tag now can contain ".", e.g. tag can be "1.0.0-rc.3".
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The …

test: fix postsubmit test component image injection. Part of #4189

---

manifests/gcp_marketplace/schema.yaml

fix(deployment): fix database name prefix description

---

test/presubmit-component-yaml.sh

test: Added presubmit unit tests for the component.yaml definitions

---

OWNERS

This will help me review and approve changes to the files in the root of the repo (tests, build scripts, README etc).
Recently there are many new test infra instabilities and to fix them I need to approve the changes to the files in the root directory (after getting LGTM from the peers).
This will also help the reviewing bandwidth and releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2254)

Add myself as approver/reviewer

---

backend/metadata_writer/src/metadata_writer.py

The DSL compiler has changed the output name sanitization rules, so we should change them here accordingly.
Fixes https://github.com/kubeflow/pipelines/issues/3971

fix(backend): Metadata Writer - Fixed regression with artifact type retrieval. Fixes #3971

---

test/presubmit-tests-tfx.sh

Fixes https://github.com/kubeflow/pipelines/issues/4221

test: Fixed the presubmit TFX test by switching from protoc to Bazel

---

.travis.yml

Fixes https://github.com/kubeflow/pipelines/issues/4221

test: Fixed the Travis TFX tests since TFX now requires Bazel. Fixes #4221

---

RELEASE.md

doc(release): instructions for update master branch version and etc

---

sdk/python/kfp/_client.py

reserve the host protocal (http or https) so that http host can work
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds …

fix(sdk/client): reserve the host protocal (http or https) so that http host can work. Fixes #4277

---

components/gcp/bigquery/query/sample.ipynb
components/gcp/bigquery/query/to_CSV/component.yaml
components/gcp/bigquery/query/to_gcs/README.md
components/gcp/bigquery/query/to_gcs/component.yaml
components/gcp/bigquery/query/to_table/component.yaml

- We should avoid referencing docker images with no tag or with "latest" tag, it would lead to unpredictable and unrepeatable behaviors.
- Also fix missing "$" for variable reference.
**Checklist:**
* …

fix(components): Add explicit image tag and fix variable references.

---

backend/src/apiserver/visualization/license-download.sh
backend/src/apiserver/visualization/third_party_licenses.csv
backend/src/apiserver/visualization/third_party_licenses/argon2-cffi.LICENSE
backend/src/apiserver/visualization/third_party_licenses/cffi.LICENSE
backend/src/apiserver/visualization/third_party_licenses/pycparser.LICENSE

**Checklist:**
*  After this PR is merged, create a cherry-pick PR …

build: fix visualization server build failure by adding missing licenses for new deps

---

backend/src/cache/deployer/deploy-cache-service.sh
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml
manifests/kustomize/base/cache-deployer/cache-deployer-role.yaml
manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-clusterrole.yaml

Fixes https://github.com/kubeflow/pipelines/issues/4299

fix(backend): Backend - Cache - Fixed reinstallation. Fixes #4299

---

components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_create_version.py
components/gcp/ml_engine/deploy/README.md
components/gcp/ml_engine/deploy/sample.ipynb

* Update the docstring of `kfp_component/google/ml_engine/_create_version.py` to specify `dict` instead of `str`.
* Update examples of the ml_engine deploy component to use `{}` instead of `''` to demostrate correct type.
**Checklist:**
If …

fix(sdk/component): ml_engine deploy version is incorrect type. Fixes #4291

---

samples/OWNERS
samples/contrib/OWNERS

multiple sample being requested to review and approve. And have been reviewing them for more than a year now.

update owners file

---

components/ibm-components/watson/deploy/Dockerfile
components/ibm-components/watson/store/Dockerfile
components/ibm-components/watson/train/Dockerfile
components/ibm-components/watson/train/src/wml-train.py

Watson ML updated the new V4 API in the past few days which requires the new client. Also, removing training_uid reference because it's now the same as run_id in the new API.
**Checklist:**
* …

fix(components): Update watson ml sdk with the Aug 2020 release

---

samples/core/train_until_good/train_until_good.py

This sample demonstrates continuous training using a train-eval-check recursive loop.
The main pipeline trains the initial model and then gradually trains the model some more until the model evaluation metrics are good enough.

samples: Added the Train until good pipeline

---

components/dataset_manipulation/split_data_into_folds/in_CSV/component.py
components/dataset_manipulation/split_data_into_folds/in_CSV/component.yaml

The component splits the data table into the specified number of folds.

components: Added dataset_manipulation - split_data_into_folds component

---

backend/src/apiserver/client_manager.go

Fixes #4334
**Checklist:**
*  After …

fix(backend): logs error when failing to init mysql. Fixes #4334

---

backend/src/cache/server/mutation.go
backend/src/cache/server/mutation_test.go

Fixes https://github.com/kubeflow/pipelines/issues/4038
Fixes https://github.com/kubeflow/pipelines/issues/3972

feat(cache):  Explicitly specifying which attributes affect the cache key

---

backend/src/apiserver/storage/experiment_store.go

Improve compatibility during DB schema change
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release …

fix(backend): improve forward / backward compatibility on experiment table

---

test/presubmit-tests-tfx.sh

test(tfx): Testing against the released version

---

backend/src/apiserver/storage/db_status_store.go

Improve compatibility during DB schema change
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release …

fix(backend): improve forward / backward compatibility on db status table

---

test/presubmit-tests-tfx.sh

Cherrypick to release 1.0 branch - test(tfx): Testing against the released version (#4365)

---

test/presubmit-tests-tfx.sh

Unpinned the TFX version.
This fixes the protoc issue.
The ml_metadata issue is already fixed in master.
Fixes https://github.com/kubeflow/pipelines/issues/4390

tests: Fixed the kubeflow-pipelines-tfx-python36 test. Fixes #4390

---

backend/Dockerfile.visualization

Decrease failures like the following: https://00e9e64bac96f3b5ceb1c3cfb1005d0a00d4d7f2cd03a990dc-apidata.googleusercontent.com/download/storage/v1/b/363997316495.cloudbuild-logs.googleusercontent.com/o/log-4b63e78a-ea23-4c52-b3f8-adcfa52f7dce.txt?qk=AD5uMEtFzOOoFfudNzxaUuDUFdIaxG_zPSxzo-bRUvvcNMZcfl4hOOouQsL6l6WObtQzXTlxCdNKGYS9eD1oRPD6QkBD7Tb5eTO2s2LECqJUkBMAiHyiaJYqyWHbNvKk6l3l5wjGrQx2ToBQkBTCJhNO_lttWaQUvTDN1acZU85s1K7X51e3Z7sB_hBMDKdHdjZPlNJKaHaQvUshQJRlE_4HMA40sEhECxMWb8xncijYL1Wijnppj1Y6f9ANFcqR2DsNqeC-fLVqPYpegj9idSVBW_z23iRZRCjzCOXzk-LLkkbe-O1XK_NCIeaUrzoDNll8hiI2tJ4Yy_ozVYXj4UNtMV4sxAR72i6w7dy2u-Q1U6I1ocwSCSH84UV0LPzPmo3c9w6vacjJVLm4DnQNBDc6RfNgojutNGXL8_hn8TXOVgXKMRs4SbbLr216QpQlXn9McG84GOsWM-V1ayyS5aUpW-4DubF3-aeGNKgyvMwnTBqVDTHoi1NflKXxRCDDAW1i43q4hbeiq4LJXRl_5OqHl1PEC8gAGgLKND …

chore(backend): Visualization: Using the correct Tensorflow image to prevent build time-outs

---

backend/src/cache/server/watcher.go

Fixes https://github.com/kubeflow/pipelines/issues/3507

fix(cache): Cache executions with no outputs. Fixes #3507

---

test/deploy-cluster.sh

Fixes https://github.com/kubeflow/pipelines/issues/4412

tests: Fixed presubmits. Fixes #4412

---

sdk/python/kfp/dsl/_resource_op.py
sdk/python/tests/dsl/resource_op_tests.py
sdk/python/tests/dsl/volume_op_tests.py

Part of the efforts to make the DSL orchestrator-agnostic. https://github.com/kubeflow/pipelines/issues/4083

refactor(sdk): Refactored ResourceOp deletion

---

samples/core/xgboost_training_cm/README.md

Fixed the `workers` definition in readme.

Fix (readme): fixed a typo.

---

components/license.sh
components/third_party_licenses.csv

Fixes https://github.com/kubeflow/pipelines/issues/4416

build(components): Added licenses

---

backend/Dockerfile.visualization

build(backend): fix "ModuleNotFoundError: No module named setuptools_distutils". Part of #4443

---

backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/apiserver/storage/run_store.go
backend/src/apiserver/storage/run_store_test.go

Fix typo in index / table selection
Fix missing experiment UUID when reporting cron job
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The …

fix(backend): fix typo in reference key type

---

backend/test/integration/upgrade_test.go
backend/test/test_utils.go

test(backend): Fix upgrade_test flakiness. Fixes #4426

---

.cloudbuild.yaml
components/kubeflow/dnntrainer/build_image.sh

Part of https://github.com/kubeflow/pipelines/issues/4361

chore(release): cherry pick more PRs for 1.0.1

---

RELEASE.md
hack/cherry-pick.sh

Read the readme changes to understand this

release: automate batch cherry pick process

---

test/sample_test.yaml

Part of #4361
**Checklist:**
* …

test: disable kf-tf-serving sample test to unblock release.

---

frontend/mock-backend/fixed-data.ts
frontend/mock-backend/mock-retry-runtime.ts
frontend/src/lib/WorkflowParser.test.ts
frontend/src/lib/WorkflowParser.ts

- Added `Retry` to list of virtual nodes to filter out when parsing DAG graph in the front-end.
- Added `retry-runtime` to mock server to visualize the change in rendered DAG.
The `Retry` node is a virtual node in Argo workflow (there are no corresponding physical pod for it, it is just used to internally monitor the actual pod to see if retry is required). It can be confusing to users if it is rendered in the UI (see #4425 #2705) as users will expect non-existence logs and other "physical" information to be returned when clicking on the node.
Before: Node 2 is the Retry node
After: Node 2 is removed from the DAG
**Checklist:**
* …

fix(frontend): do not render Retry nodes in UI DAG as they are virtual nodes. Fixes #4425 #2705

---

hack/cherry-pick.sh
hack/release.sh

chore(release): auto configure changelog genreartion for stable/pre releases. Fixes #4248

---

sdk/python/kfp/components/_data_passing.py
sdk/python/kfp/components/_python_op.py
sdk/python/kfp/components_tests/test_components.py
sdk/python/kfp/dsl/_component_bridge.py
sdk/python/tests/dsl/component_bridge_tests.py

Fixes https://github.com/kubeflow/pipelines/issues/4040

feat(sdk): Components - Prevent passing unserializable objects to components. Fixes #4040

---

manifests/gcp_marketplace/README.md
manifests/gcp_marketplace/cli.md

Reduce some confusion of marketplace CLI installation
**Checklist:**

doc(gcp): recommend KFP standalone over marketplace CLI installation

---

test/presubmit-tests-tfx.sh

test: fix TFX related test failure due to protobuf version.

---

sdk/python/kfp/components/_python_op.py
sdk/python/kfp/components_tests/test_python_op.py
sdk/python/requirements.in
sdk/python/requirements.txt
sdk/python/setup.py

- improvements to docstring parsing
NOTE : I didn't find any changes in UI with this update, with kfp 1.0.0. This PR just lays the groundwork for #4513 , further changes are needed in sdk or backend to see any visible improvements.
**Checklist:**

feat(sdk): Python components - Parse component input/output descriptions from the function docstring

---

sdk/python/kfp/dsl/_container_op.py

- Added support for [ephemeral-storage](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage) in container-op
- Added some type annotation to make it IDE friendly
**Checklist:**

feat(sdk): adds support for ephemeral-storage in container-op

---

components/ml_metrics/Calculate_classification_metrics/_samples/sample_pipleine.py
components/ml_metrics/Calculate_classification_metrics/from_CSV/component.py
components/ml_metrics/Calculate_classification_metrics/from_CSV/component.yaml

Added a component to calculate the classification metrics, based on a similar component for regression metrics.

feat(components): Added Calculate classification metrics component

---

components/_converters/TensorflowJSLayersModel/from_KerasModelHdf5/component.yaml
components/_converters/TensorflowJSLayersModel/from_TensorflowSavedModel/component.yaml

Added converter components for TensorflowJS LayersModel

feat(components): Added converter components for TensorflowJS LayersModel

---

components/_converters/TensorflowLiteModel/from_KerasModelHdf5/component.yaml
components/_converters/TensorflowLiteModel/from_TensorflowSavedModel/component.yaml

Added converter components for Tensorflow Lite models

feat(components): Added converter components for Tensorflow Lite models

---

sdk/python/kfp/_client.py

In some cases, it may need extra header to handle the API calls.
Directly add `header_name` and `header_value` props in
`.config/kfp/context.json` and pass the name/value pair
to APIClient.
Here is one of the use cases:
if the service is protected by istio RBAC and need JWT header
for authentication, you can specify the JWT id-token in
the .config/kfp/context.json with these two new props.
The id-token would be carried in the specified header name.
Then the API call can be properly authentiecated and checked
if the user has the permission to access the service.
Fixes: #4377 
**Checklist:**
* `feat(backend): configurable service account. …

feat(sdk/cli): add extra header for cli

---

frontend/src/pages/RunDetails.test.tsx
frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap

Solves the problem in https://github.com/kubeflow/pipelines/pull/4180#discussion_r471256649.
**Checklist:**

test(frontend): make run details graph captured in unit test snapshot

---

components/google-cloud/storage/download/component.yaml

gsutil rsync cannot copy a single blob

fix(components): Fixed the Download from GCS components for blob URIs

---

api/v2alpha1/pipeline_spec.proto

/assign @hongye-sun @numerology 
/cc @neuromage

Update ImporterSpec artifact_uri type

---

components/_converters/OnnxModel/from_KerasModelHdf5/component.yaml
components/_converters/OnnxModel/from_TensorflowSavedModel/component.yaml

Added converters to OnnxModel from Tensorflow and Keras

feat(components): Added converters to OnnxModel from Tensorflow and Keras

---

sdk/python/kfp/dsl/_container_op.py
sdk/python/kfp/dsl/_pipeline.py
sdk/python/tests/compiler/compiler_tests.py

Fixes https://github.com/kubeflow/pipelines/issues/4522

fix(sdk): DSL - Enabled arbitrary ContainerOp names

---

backend/src/cache/deployer/deploy-cache-service.sh

Fixes https://github.com/kubeflow/pipelines/issues/4505

fix(cache): Cache deployer - Using the same kubectl version as the server

---

samples/core/secret/secret.py

The sample started failing with "ImportError: cannot import name 'collections_abc' from 'six.moves' (unknown location)".
While fixing the issue I saw that the sample is pretty outdated (for example, we've deprecated the direct ContainerOp construction), so I've decided to update the sample along the way.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4585/kubeflow-pipeline-sample-test/1313222398857711616

fix(samples): Updated and fixed the secrets sample

---

sdk/python/kfp/_client.py

Using `here` as link text is an anti-pattern. See a [recent post about the rationale](https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/).
**Checklist:**

fix(sdk): use a meaningful link text in ipython

---

components/aws/sagemaker/tests/integration_tests/component_tests/test_groundtruth_component.py

workteam cleanup fails if groundthruth pipeline fail and unbound variable exception if workteam pipeline fails

chore(components): SageMaker integ tests, fix for unbound variable

---

components/azure/OWNERS
components/azure/azuredevops/queue-pipeline/Dockerfile
components/azure/azuredevops/queue-pipeline/build_image.sh
components/azure/azuredevops/queue-pipeline/component.yaml
components/azure/azuredevops/queue-pipeline/readme.md
components/azure/azuredevops/queue-pipeline/src/queue_pipeline.py
components/azure/azuredevops/readme.md
components/azure/azureml/aml-register-model/Dockerfile
components/azure/azureml/aml-register-model/README.MD
components/azure/azureml/aml-register-model/build.sh
components/azure/azureml/aml-register-model/component.yaml
components/azure/azureml/aml-register-model/requirements.txt
components/azure/azureml/aml-register-model/src/register.py

> Azure Component to Register ML model with Azure ML 
> Azure Component to queue AzureDevOps Pipeline 
>Added owners for the Azure Components

sample azure components

---

frontend/README.md
frontend/package-lock.json
frontend/package.json

Fixes https://github.com/kubeflow/pipelines/issues/4013
Part of https://github.com/kubeflow/pipelines/issues/4540
**Checklist:**

chore: update @kubeflow/frontend to include MLMD client upgrade to 0.22.1

---

proxy/Dockerfile

Fixes https://github.com/kubeflow/pipelines/issues/4531
Verification: gcr.io/gongyuan-pipeline-test/proxy-agent@sha256:e13b292ba7df483003a22d8b6169ce19344a4218bcd6b1542ffc4287e3864457
Verified newly built image no longer have the vulnerabilities found previously.
Also verified newly built image works in a real cluster.
**Checklist:**

build: update proxy agent to fix CVE vulnerabilities. Fixes #4531

---

manifests/kustomize/env/aws/README.md

Use Managed NodeGroup for EKS Cluster
**Checklist:**

fix(doc): Use Managed NodeGroup for EKS Cluster

---

manifests/kustomize/env/azure/OWNERS
manifests/kustomize/env/azure/kustomization.yaml
manifests/kustomize/env/azure/minio-azure-gateway/kustomization.yaml
manifests/kustomize/env/azure/minio-azure-gateway/minio-artifact-secret.env
manifests/kustomize/env/azure/minio-azure-gateway/minio-azure-gateway-deployment.yaml
manifests/kustomize/env/azure/minio-azure-gateway/minio-azure-gateway-service.yaml
manifests/kustomize/env/azure/mysql-secret.env
manifests/kustomize/env/azure/params.env
manifests/kustomize/env/azure/readme.md

Kustomize manifest for KFP deployment using Azure Database for MySQL and MinIO gateway to Azure Blobstore
**Checklist:**

feat(deployment): Kustomize manifest for Azure deployments

---

components/notebooks/Run_notebook_using_papermill/component.yaml
components/notebooks/samples/sample_pipeline.py
components/notebooks/samples/test_notebook.ipynb

feat(components): Added the Run notebook using papermill component. Fixes #497

---

RELEASE.md

Part of https://github.com/kubeflow/pipelines/issues/4584
**Checklist:**

doc(release): drop python 3.5 support. Part of #4584

---

components/google-cloud/Optimizer/Suggest_parameter_sets_based_on_measurements/component.py
components/google-cloud/Optimizer/Suggest_parameter_sets_based_on_measurements/component.yaml
components/google-cloud/Optimizer/_samples/multi_stage_optimization_atomic_pipeline.py

Also added the multi-stage optimization sample pipeline.

feat(components): Google Cloud Optimizer - Added the "Suggest parameter sets from measurements" component

---

sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/fancy_trainer_component.yaml
sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/ingestion_component.yaml
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.json
sdk/python/kfp/v2/dsl/type_utils.py
sdk/python/kfp/v2/dsl/type_utils_test.py

Add more semantically expressive artifact ontology to IR compiler.
Including:
- Dataset
- Metrics
- Schema
**Checklist:**

chore: Add more semantically expressive artifact ontology to IR compiler.

---

test/sample-test/Dockerfile

Fixes https://github.com/kubeflow/pipelines/issues/4653

test: Updated base image version for sample tests. Fixes #4653

---

components/ibm-components/ffdl/serve/component.yaml
components/ibm-components/ffdl/serve/src/serve.py
components/ibm-components/ffdl/train/component.yaml
components/ibm-components/ffdl/train/src/train.py
components/ibm-components/spark/data_preprocess_spark/component.yaml
components/ibm-components/spark/data_preprocess_spark/src/data_preprocess_spark.py
components/ibm-components/spark/store_spark_model/component.yaml
components/ibm-components/spark/store_spark_model/src/store_spark_model.py
components/ibm-components/spark/train_spark/component.yaml
components/ibm-components/spark/train_spark/src/train_spark.py
components/ibm-components/watson/manage/subscribe/component.yaml
components/ibm-components/watson/manage/subscribe/src/subscribe.py

fix https://github.com/kubeflow/pipelines/issues/4129 to de-hardcode the output paths for IBM components.
**Checklist:**

fix(components): Move output path as arguments for ibm components

---

test/presubmit-tests-sdk.sh

Verifying that the component authoring library can work standalone.

test(sdk): Testing the component library

---

sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/concat_placeholder_component.yaml
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.py

Add test to verify that concat placeholder is supported in v2 compiler.
**Checklist:**
/cc @numerology @Ark-kun @neuromage
/assign @numerology @neuromage

chore(sdk): Add test for concat placeholder

---

frontend/src/components/Graph.tsx

Fixes https://github.com/kubeflow/pipelines/issues/3989

feat(frontend): Show full node names. Fixes #3989

---

sdk/python/kfp/v2/compiler/compiler_test.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.py
sdk/python/kfp/v2/dsl/__init__.py
sdk/python/kfp/v2/dsl/_component.py
sdk/python/kfp/v2/dsl/_ops_group.py

- Raise errors on the following features which aren't supported yet in KFP v2 compiler:
- dsl.Condition
- dsl.ExitHandler
- dsl.ParallelFor
- dsl.graph_component (dsl.Graph)
- Add unittests for each of the usages above
**Checklist:**

chore(sdk): Raises error on unsupported features in v2 compiler

---

sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
sdk/python/kfp/v2/dsl/component_bridge.py
sdk/python/kfp/v2/dsl/type_utils.py
sdk/python/kfp/v2/dsl/type_utils_test.py

- Allow arbitrary types including no type.
- "Unknown" types are mapped to STRING value parameter type.
**Checklist:**
/assign @numerology @neuromage 
/cc @numerology @neuromage, @Ark-kun

chore(sdk): Allow arbitrary input/output types in v2 compiler

---

test/deploy-cluster.sh

test: make details log url easier to select

---

.pylintrc

Increase the indent in .pylintrc to 4 spaces.
**Checklist:**

fix(sdk): Fixes #4703: conflict between .pylintrc and .yapf

---

backend/test/integration/job_api_test.go

Added missing assert statement in job_api_test. 
**Checklist:**

test(backend): added missing assert statement in job_api_test . 

---

sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
sdk/python/kfp/v2/dsl/component_bridge.py
sdk/python/kfp/v2/dsl/type_utils.py
sdk/python/kfp/v2/dsl/type_utils_test.py

**Checklist:**
/cc @numerology @neuromage @Ark-kun 
/assign @numerology @neuromage

chore(sdk): Allow arbitrary input/output types with default to generic artifact.

---

backend/src/apiserver/server/pipeline_upload_server_test.go

Addes setup functions for common parts of the tests to reduce duplicated code and simplify adding new test.  
Fixes #4630
**Checklist:**

fix(backend): added setup structure to simplify adding new tests and removing duplicated code. Fixes #4630

---

sdk/python/kfp/__init__.py

Update SDK version to 1.1.0
**Checklist:**

chore(sdk): update SDK version to 1.1.0

---

sdk/python/kfp/v2/components/structures.py

Use custom warning format for two warnings in v2, so that warning doesn't repeat the first line of code.
**Checklist:**

chore(sdk): custom warning format in v2 structures.

---

test/manifests/dev/proxy-agent-patch.yaml

/cc @chensun 
I heard we can use staging proxy instance now, sending a PR to verify that.
**Checklist:**

test(proxy): use staging inverse proxy instance

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml

We already have stackdriver, the additional archiveLogs has no benefit.
**Checklist:**

feat(gcp): turn off archiveLogs for GCP marketplace

---

test/presubmit-tests-tfx.sh

Test from TFX head again, and use nightly dependency to mitigate the broken head problem.
Also add some newly-added unittests.
**Checklist:**

test: Improve TFX related unittests

---

components/README.md

Previously the readme linked to deprecated components and some legacy documentation pages.

docs(components): Updated the readme

---

backend/README.md

This PR updates the README for the backend in order to follow recent updates to use native go test and build instead of Bazel. 
**Checklist:**

fix(Process): update backend development README. Fixes #4750

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml

Reverts kubeflow/pipelines#4758

feat(gcp): Revert "turn off archiveLogs for GCP marketplace #4758"

---

frontend/src/components/Router.tsx
frontend/src/components/SideNav.test.tsx
frontend/src/components/SideNav.tsx
frontend/src/components/__snapshots__/SideNav.test.tsx.snap

github should now be the major source of samples
**Checklist:**

chore(frontend): update external urls

---

OWNERS

Update reviewers to active reviewers
**Checklist:**

chore: update root reviewers

---

sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/add_component.yaml
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.py
sdk/python/kfp/v2/dsl/_pipeline.py
sdk/python/kfp/v2/dsl/component_bridge.py

Use the unique `task.name` rather than `component_spec.name` to fill in IR task spec, so that one component can be used multiple times in the same pipeline.
**Checklist:**
/assign @numerology @neuromage

chore(sdk.v2): Allow component to be reused in a pipeline

---

sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.py
sdk/python/kfp/v2/dsl/component_bridge.py

Support task dependency specified via `op2.after(op1)`.
**Checklist:**

chore(sdk.v2): Support explicit task dependency

---

RELEASE.md

/assign @hilcj 
**Checklist:**

docs: Update RELEASE.md to include release from master branch instructions

---

README.md

docs: add KFP installation options overview to root README.md

---

hack/check-release-needed-tools.sh

chore(release): check go setup

---

frontend/package-lock.json
frontend/package.json

chore(release): update @kubeflow/frontend to include MLMD client upgrade to 0.25.1

---

RELEASE.md

docs(release): add note for expected postsubmit failure in RELEASE.md

---

RELEASE.md

This PR updates release descriptions on step11.
**Checklist:**

docs(release): updating release descriptions on step11

---

sdk/python/setup.py

/cc @rui5i 
I think you need to merge this PR before current release to make sure the version dependency is correct
https://github.com/kubeflow/pipelines/pull/4638 made `kfp` depend on the new `kfp-server-api` package (on master, and not released yet).
Related to https://github.com/kubeflow/pipelines/issues/4847.
EDIT: kfp-server-api 1.1.1b1 should already include the healthz endpoint.
**Checklist:**

chore(sdk): bump sdk's dependency on kfp-server-api

---

RELEASE.md

docs(release): introduce how to find cloudbuild status

---

backend/src/apiserver/client/scheduled_workflow_fake.go
backend/src/apiserver/client/swf.go
backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/common/util/error.go
backend/test/integration/job_api_test.go

fix(backend): job api -- deletion/disabling should succeed when swf not found. Fixes #4871

---

api/OWNERS

chore: add OWNER file to api folder

---

api/v2alpha1/python/setup.py
sdk/python/setup.py

Sorry 0.1.3 was a bad build.
**Checklist:**

chore: Bump kfp-pipeline-spec to 0.1.3.1

---

sdk/python/kfp/compiler/_op_to_template.py
sdk/python/kfp/dsl/_container_op.py
sdk/python/tests/compiler/compiler_tests.py

This fixes the second part of the issue described in #4333
The first part was addressed in #4392
**Checklist:**

feat(sdk): add ability to set retry policy

---

backend/README.md

/cc @capri-xiyue 
**Checklist:**

docs(backend): clean up readme

---

sdk/python/kfp/v2/dsl/artifact.py
sdk/python/kfp/v2/dsl/artifact_test.py
sdk/python/requirements.in
sdk/python/requirements.txt

Adds base `Artifact` Python class.
The base Python class mainly serves two purposes:
1. Help implementing the contract described in https://github.com/kubeflow/pipelines/blob/7a66414cf72ba5c746cac7fc6c8ecad67fc5e885/api/v2alpha1/pipeline_spec.proto#L397, so that user logic can access/manipulate MLMD properties easily during runtime.
2. Serve as a foundation for artifact ontology in the Python SDK
This implementation is similar to https://github.com/tensorflow/tfx/blob/master/tfx/types/artifact.py with two major differences:
1. KFP `Artifact` class is backed by `RuntimeArtifact` in its IR pb spec instead of Artifact pb message in MLMD.
2. The type schema is described as a YAML spec instead of pb spec. 
**Checklist:**
[Learn more about cherry-picking updates …

feat(SDK): adds Artifact base class.

---

backend/src/cache/deployer/Dockerfile

Address build failure in https://github.com/kubeflow/pipelines/pull/4899
**Checklist:**

test(cache): fix cache deployer image build in apk add command

---

sdk/python/kfp/_client.py

update comments of _create_job_config
**Checklist:**

docs(sdk): update comments of _create_job_config

---

frontend/package-lock.json
frontend/package.json

fix(frontend): fixed getting executions failure. Fixes #4903

---

sdk/python/setup.py

chore(sdk): bump kfp-server-api dependency to >= 1.1.2

---

samples/core/ai_platform/ai_platform.ipynb

The notebook is run as part of the post-submit integration tests. Without the model deletion, we would run out of quota on number of models per project.
**Checklist:**

chore(sample): Uncomment model deletion commands

---

api/v2alpha1/pipeline_spec.proto

Add control flow features to the pipeline_spec.proto.

feat(backend): sync pipeline_spec.proto

---

go.mod
go.sum

Upgrade Go SQL driver for MySQL
**Checklist:**
Closes #4910

feat(backend): Bump Go SQL driver to v1.5.0. Fixes #4910

---

backend/README.md

update docs of deploying apiserver with the image you own build
**Checklist:**

docs(backend)update docs of deploying apiserver

---

backend/src/apiserver/resource/client_manager_fake.go
backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/apiserver/resource/resource_manager_util.go
backend/src/apiserver/resource/resource_manager_util_test.go
backend/src/apiserver/server/job_server.go
backend/src/apiserver/server/job_server_test.go
backend/src/apiserver/server/run_server.go
backend/src/apiserver/server/run_server_test.go
backend/src/apiserver/server/test_util.go
backend/src/apiserver/server/util.go
backend/src/apiserver/server/util_test.go

Fixed #4900 
fixed validation logic and resource manager logic when creating job and run based on discussion of #4900
**Checklist:**

fix(backend): fixed validation logic and resource manager logic when creating job and run

---

sdk/python/kfp/_client.py

`des` is not recognized and it should be `desc`.
**Checklist:**

fix(sdk): fixes typo of 'desc'.

---

samples/core/parallelism_sub_dag/parallelism_sub_dag.py
samples/core/parallelism_sub_dag_with_op_output/parallelism_sub_dag_with_op_output.py
sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/_ops_group.py
test/sample-test/configs/parallelism_sub_dag.yaml
test/sample_test.yaml

This PR  adds parallelism limits for sub-DAG:s. This is a continuation (https://github.com/kubeflow/pipelines/pull/4149) which relate to  [issue](https://github.com/kubeflow/pipelines/issues/4089). 
**Checklist:**
If yes, use one of the …

feat(compiler): add dsl operation for parallelism on sub dag level

---

backend/OWNERS
test/api-integration-test/OWNERS

Add @capri-xiyue as backend reviewer.
**Checklist:**

chore: add capri-xiyue as backend reviewer

---

frontend/src/pages/RunDetails.tsx
frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap

Extend RunDetails config table with the run ID and the underlying workflow name.
Part of #4921.
**Checklist:**

feat(frontend): Add run ID and workflow name in RunDetails config. Part of #4921

---

sdk/python/kfp/dsl/_ops_group.py
sdk/python/kfp/dsl/_pipeline.py

Based upon discussion in 4199, https://github.com/kubeflow/pipelines/pull/4199#discussion_r535751512
**Checklist:**

Added checks for parallism values

---

sdk/python/kfp/_auth.py

Suggested fix for #4987
**Checklist:**

chore: add instruction detail in _auth.py print statement. Fixes #4987

---

api/v2alpha1/python/setup.py

To make the latest change available for development/testing.
**Checklist:**

Bump kfp-pipeline-spec version to 0.1.4

---

backend/src/agent/persistence/worker/persistence_worker.go
backend/src/apiserver/model/run.go
backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/storage/run_store.go

Fixed #4886 
Change enqueue base delay in non-error mode to 1 second
**Checklist:**

fix(backend):Change enqueue base delay in non-error mode to 1 second for persistent agent

---

components/gcp/bigquery/query/to_gcs/component.yaml
components/gcp/container/component_sdk/python/kfp_component/google/bigquery/_query.py
components/gcp/container/component_sdk/python/tests/google/bigquery/test__query.py

Currently, BigQuery output to GCS only supports CSV.
Given the fact that there are repeating columns, we have added support for outputting to json.
**Checklist:**

feat(components): Add json format for BigQuery output to GCS

---

sdk/python/kfp/containers/_component_builder.py

Add a component annotation for new-styled KFP component when users specify such. So that downstream logic can be conditioned on this.
**Checklist:**

chore(sdk): Add annotations for new-styled KFP component

---

manifests/gcp_marketplace/schema.yaml

See https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/schema.md#type-service_account
Fixes https://buganizer.corp.google.com/issues/177083468

fix(mkp): Added service account description to prevent validation errors

---

sdk/python/kfp/compiler/_data_passing_rewriter.py
sdk/python/kfp/components/_components.py
sdk/python/kfp/components/_structures.py
sdk/python/kfp/components_tests/test_components.py
sdk/python/tests/compiler/testdata/uri_artifacts.py
sdk/python/tests/compiler/testdata/uri_artifacts.yaml

Add several placeholders that'll be used in the v2 components in the future, with more expressive MLMD semantics. This includes
- `inputMetadata`
- `inputOutputPortName`
- `outputMetadata`
**Checklist:**

feat(sdk): Artifact metadata related placeholder for components.

---

test/manifests/dev/proxy-agent-patch.yaml

/assign @capri-xiyue 
**Checklist:**

chore(proxy): use production inverse proxy

---

manifests/gcp_marketplace/schema.yaml

Parameters that do not have a default value in /data/schema.yaml, should be declared in data-test/schema.yaml."
https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/verification-integration.md#2-writing-the-test-schemayaml
Fixes https://b.corp.google.com/issues/177083468

fix(mkp): Added default values for parameters

---

backend/src/apiserver/filter/filter.go
backend/src/apiserver/filter/filter_test.go

I detailed the issue a few days ago [here](https://github.com/kubeflow/pipelines/issues/4975). Ended up taking a look and saw that it was a relatively small fix.
The main change is that the fields of the Filter struct now map strings (keys) to *slices* of structs (values), rather than to a single struct.
Also added a couple of unit tests for the new functionality, but would be happy to add more if deemed necessary. All tests passed and expected functionality seems to work on a local deployment.
**Checklist:**

fix(backend): allow multiple values per key/op in filter. Fixes #4975

---

sdk/python/kfp/components/_components.py

By changing handcrafted paths to `pathlib`.
**Checklist:**

chore: Resolve comments in #5003

---

frontend/src/components/Trigger.tsx
frontend/src/components/__snapshots__/Trigger.test.tsx.snap

Update the docs to point to the correct description of the implementation of cron expressions. 
**Checklist:**

fix(frontend): updated the docs to point to the correct cron expression descriptions. Fixes #2654

---

backend/Dockerfile
backend/update_requirements.sh

E2E test, sample test and upgrade test are failing because of python 3.5 not supporting f"string" context. This PR is for fixing the test failure issue which might have been blocking everyone.
**Checklist:**

fix(test): Fix presubmit with python version upgrade

---

backend/src/crd/controller/scheduledworkflow/util/periodic_schedule.go
backend/src/crd/controller/scheduledworkflow/util/periodic_schedule_test.go

Update the periodic scheduler to execute the first job at the start time or later. 
Fixes #3935
**Checklist:**

fix(backend): fix periodic schedule to begin at start time. Fixes #3935

---

api/v2alpha1/pipeline_spec.proto

feat(api): Add AI Platform Custom Job spec to IR

---

components/aws/sagemaker/tests/integration_tests/component_tests/test_groundtruth_component.py

Add a missing condition to GT test assertion

chore(components): SageMaker fix flaky groundtruth test

---

components/gcp/automl/create_dataset_for_tables/component.py
components/gcp/automl/create_dataset_for_tables/component.yaml

Cast return value of gcp/automl/create_dataset_for_tables. Fixes #5053 
**Quality assurance**
I confirmed that the patched component.yaml fixes the issue.
_Before_
_After: Loading the patched component.yaml. (same inputs)_
</details>
**Checklist:**

fix(components): cast return value of gcp/automl/create_dataset_for_tables. Fixes #5053

---

test/presubmit-tests-tfx.sh

fix(test): Pin pip version in presubmit-tests-tfx.sh Fixes #5049

---

backend/src/crd/controller/scheduledworkflow/util/parameter_formatter.go
backend/src/crd/controller/scheduledworkflow/util/parameter_formatter_test.go
backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go

Part of https://github.com/kubeflow/pipelines/issues/4700
**Context**
Scheduled Workflows support macros in pipeline parameters. Existing macros are documented here: https://github.com/kubeflow/pipelines/blob/34d23aa924720ead13fe67ebca5c1ab9926585ee/backend/src/crd/samples/scheduledworkflow/parameterized.yaml
**What**
This PR adds a new macro `[[RunUUID]]` which gets replaced with the KFP Run UUID.
**Why**
User code, running inside a pipeline step, might access some external system (i.e. a database) to write data or perform some operation. In these scenarios the pipeline can leave an auditable trace using the Run UUID in the external system, so that someone looking at it later on can go back to the original KFP run.
**Checklist:**
[Learn more about cherry-picking updates into the release …

feat(swf): Add a [[RunUUID]] macro

---

backend/Dockerfile.visualization
proxy/Dockerfile
third_party/metadata_envoy/Dockerfile

Part of https://github.com/kubeflow/pipelines/issues/3857
**Checklist:**

fix: upgrade some images to reduce vulnerabilities

---

.github/renovate.json5

chore: update renovate.json5 - preserve semver range

---

.github/renovate.json5

Part of https://github.com/kubeflow/pipelines/issues/4682
**Checklist:**

chore: change renovate config to rangeStrategy=update-lock file for npm

---

frontend/OWNERS

Hi @zijianjoy, I think being added as reviewer is a good way to involve more.
What do you think?
**Checklist:**

chore: Add zijianjoy as frontend reviewer

---

api/v2alpha1/pipeline_spec.proto

feat(API): Add TriggerPolicy to pipeline_spec

---

sdk/python/kfp/__init__.py

release(sdk): Bump KFP SDK version to 1.4.0

---

api/v2alpha1/python/setup.py

release(api): Bump kfp-pipeline-spec version to 0.1.5

---

sdk/python/setup.py

We have SDK code relying on this, for example:
https://github.com/kubeflow/pipelines/blob/279694ec6d4d0467bef26380ebdae37c487518c2/sdk/python/kfp/dsl/artifact.py#L17
**Checklist:**

chore(sdk): add `absl-py` in kfp install_requires

---

sdk/python/kfp/components/_python_op.py
sdk/python/kfp/containers/_component_builder.py
sdk/python/kfp/containers/entrypoint.py
sdk/python/kfp/containers/entrypoint_utils.py
sdk/python/kfp/containers_tests/component_builder_test.py
sdk/python/kfp/containers_tests/entrypoint_test.py
sdk/python/kfp/containers_tests/testdata/expected_component.yaml
sdk/python/kfp/containers_tests/testdata/test_source.py
sdk/python/kfp/dsl/artifact.py
sdk/python/tests/compiler/component_builder_test.py

This PR supersedes https://github.com/kubeflow/pipelines/pull/5030.
Synced offline and we decide to implement such component on v2 KFP first and the metadata interaction implementation on conventional KFP stack is TBD. 
The compiler changes required in KFP v2 will be in a follow up PR.
**Checklist:**

feat(sdk): Add v2 component to build_python_component

---

test/component_test.yaml
test/sample_test.yaml

test: Temporarily disable XGBoost tests

---

sdk/python/setup.py

It was removed by https://github.com/kubeflow/pipelines/pull/5042, but wasn't added back in https://github.com/kubeflow/pipelines/pull/5083/.
Without this line, normal import still works, but the compiler cli tool is broken.
**Checklist:**

fix(sdk): Add back 'kfp.v2.components' as a package in setup.py

---

frontend/OWNERS

Adding myself to the frontend reviewers list.  I would like to stay more in the the loop of UI reviews.
/cc @Bobgy
**Checklist:**

chore(frontend): Add StefanoFioravanzo to reviewers

---

sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler/compiler_utils.py
sdk/python/kfp/v2/compiler/compiler_utils_test.py

feat(sdk.v2): Update v2 compiler to support v2 component.

---

components/azure/OWNERS

Chore: Adds additional (and more active) Azure reviewers and approvers for the Azure Pipelines Components.
**Checklist:**

chore: adds more Azure Approvers and Reviewers

---

components/kubeflow/launcher/OWNERS

Signed-off-by: cegao <cegao@tencent.com>
/cc @Bobgy @NikeNano 
Ref https://github.com/kubeflow/pipelines/pull/4806
**Checklist:**

chore(tfjob-launcher): Add gaocegege and NikeNano as approver

---

go.mod
test/presubmit-backend-test.sh
tools/tools.go

/assign @capri-xiyue 
**Checklist:**

chore(backend): include protoc-gen-go-grpc as tools dependency and add go mod tidy check in CI

---

README.md

Add references for Tekton backend

---

sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/components/_components.py
sdk/python/kfp/components_tests/test_components.py
sdk/python/kfp/dsl/__init__.py
sdk/python/tests/compiler/testdata/uri_artifacts.yaml

The pipeline root will be always specified as a pipeline parameter, whose runtime value can be overwritten when submitting pipeline run. The user-supplied value at compile time will be the default of this parameter.
**Checklist:**

feat(sdk): Always add pipeline root as a pipeline parameter

---

backend/Dockerfile
backend/src/apiserver/config/sample_config.json
frontend/src/config/sample_config_from_backend.json
frontend/src/pages/GettingStarted.test.tsx
frontend/src/pages/GettingStarted.tsx
frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
samples/core/train_until_good/train_until_good.py

fix(backend): Replaced the XGBoost sample. Fixes #5089

---

sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler/compiler_test.py
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.json
sdk/python/kfp/v2/dsl/__init__.py
sdk/python/kfp/v2/dsl/_ops_group.py
sdk/python/kfp/v2/dsl/_pipeline.py
sdk/python/kfp/v2/dsl/component_spec.py
sdk/python/kfp/v2/dsl/component_spec_test.py
sdk/python/kfp/v2/dsl/type_utils.py
sdk/python/kfp/v2/dsl/type_utils_test.py
sdk/python/setup.py

feat(sdk.v2): support dsl.Condition in v2.

---

RELEASE.md

Update RELEASE.md with GOPATH error instruction that I faced during release.

chore(release): Update RELEASE.md

---

api/v2alpha1/python/setup.py

chore(api): Fix kfp-pipeline-spec dependency. Fixes #5134

---

api/v2alpha1/pipeline_spec.proto

feat(api): Update pipeline_spec.proto - Add metadata to ArtifactSpec

---

api/v2alpha1/python/setup.py

release(api): Bump kfp-pipeline-spec version to 0.1.6

---

components/kubeflow/launcher/component.yaml
components/kubeflow/launcher/sample.py

When trying to use the sample for the tfjob launcher component, I found the following issues:
- The data types had to be updated from Json to JsonObject
- The workerNum where formatted like strings in the dict -> "3" instead of 3, to fix this a python component where created.
**Checklist:**

fix(components): fixes issues with tfjob launcher component.

---

sdk/python/kfp/compiler/compiler.py

Fixes #5119.
**Quality assurance**
Verify that the patched `dsl-compile` generates pipeline.yaml with `generateName: pipeline-`
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
generateName: pipeline-
...
```
and confirm I can create run for the newly uploaded pipeline.
**Checklist:**

fix(sdk): generate valid pipeline from non-ascii name. Fixes #5119

---

backend/api/Makefile

Follow up of https://github.com/kubeflow/pipelines/pull/4906#issuecomment-778945609
/assign @capri-xiyue @NikeNano 
**Checklist:**

chore(api): build api clients using a prebuilt image

---

components/aws/sagemaker/Changelog.md
components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
components/aws/sagemaker/batch_transform/component.yaml
components/aws/sagemaker/batch_transform/src/sagemaker_transform_component.py
components/aws/sagemaker/create_simulation_app/component.yaml
components/aws/sagemaker/delete_simulation_app/component.yaml
components/aws/sagemaker/deploy/component.yaml
components/aws/sagemaker/ground_truth/component.yaml
components/aws/sagemaker/hyperparameter_tuning/component.yaml
components/aws/sagemaker/model/component.yaml
components/aws/sagemaker/process/component.yaml
components/aws/sagemaker/process/src/sagemaker_process_component.py
components/aws/sagemaker/rlestimator/component.yaml
components/aws/sagemaker/simulation_job/component.yaml
components/aws/sagemaker/simulation_job_batch/component.yaml
components/aws/sagemaker/tests/unit_tests/tests/batch_transform/test_transform_component.py
components/aws/sagemaker/tests/unit_tests/tests/process/test_process_component.py
components/aws/sagemaker/tests/unit_tests/tests/train/test_train_component.py
components/aws/sagemaker/train/component.yaml
components/aws/sagemaker/workteam/component.yaml

During code refactoring we missed adding cloudwatch logs functionality to Batch Transform and Processing jobs.
Adding it back now

fix(components): Print logs for AWS SageMaker components

---

frontend/src/lib/OutputArtifactLoader.ts

Fixed issue in https://github.com/kubeflow/pipelines/issues/5137#issuecomment-785012674 (there are multiple issues in the issue, this is fixing the one mentioned in this comment)
**Checklist:**

fix(frontend): example-validator visualization for TFX 0.27.0. Part of #5137

---

sdk/python/requirements.in
sdk/python/requirements.txt
sdk/python/setup.py

https://github.com/kubeflow/pipelines/blob/master/sdk/python/setup.py
https://github.com/kubeflow/pipelines/blob/master/sdk/python/requirements.in
the two should be in sync
Part of https://github.com/kubeflow/pipelines/issues/5137
**Checklist:**

chore(sdk): update requirements.in to be in sync with setup.py

---

components/release-in-place.sh

The change reduces time complexity from O(N^2) to O(N), the script will take <30s to run now.
**Checklist:**

chore(release): drastically make component release script faster

---

sdk/python/kfp/compiler/compiler.py

https://github.com/kubeflow/pipelines/blob/cfe59139be68705dadaa1a268f095923042b829c/sdk/python/kfp/compiler/compiler.py#L58-L67
is redundant to
https://github.com/kubeflow/pipelines/blob/1fee4054a77d39877d997ec94374201188fa87d0/sdk/python/kfp/dsl/_pipeline_param.py#L172-L177
**Checklist:**

chore(sdk): remove redundant method: `_pipelineparam_full_name()`

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
manifests/kustomize/base/argo/workflow-controller-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
manifests/kustomize/env/azure/minio-azure-gateway/minio-azure-gateway-deployment.yaml
manifests/kustomize/env/gcp/minio-gcs-gateway/minio-gcs-gateway-deployment.yaml
manifests/kustomize/env/platform-agnostic/minio/minio-deployment.yaml

Update the manifests with k8s resource requests,  this change will give the update resources the `Burstable` class. 
**Checklist:**

fix(deployment): Updated the manifests with resource requests. Fixes #5148

---

backend/metadata_writer/src/metadata_helpers.py

fix(backend): add brackets if metadata service host is ipv6. Part of #5605

---

samples/core/sidecar/sidecar.py

Improve flakiness of sidecar sample test, because image pull can take a long time.
**Checklist:**

test(samples): reduce sidecar sample test flakiness

---

sdk/python/kfp/v2/google/aiplatform_e2e_test.py

fix(tests): Alter hardcoded sdk version in aiplatform_e2e_test.py test data before comparison.

---

manifests/kustomize/base/argo/workflow-controller-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
manifests/kustomize/env/gcp/params.env

https://github.com/kubeflow/manifests/pull/1752
**Checklist:**

fix(backend):Update with to allow eviction of pods with empty dir. Fixes #4530

---

sdk/python/kfp/dsl/_component.py
sdk/python/kfp/dsl/_component_bridge.py
sdk/python/kfp/dsl/_container_op.py
sdk/python/kfp/dsl/_for_loop.py
sdk/python/kfp/dsl/_metadata.py
sdk/python/kfp/dsl/_ops_group.py
sdk/python/kfp/dsl/_pipeline.py
sdk/python/kfp/dsl/_pipeline_param.py
sdk/python/kfp/dsl/_pipeline_volume.py
sdk/python/kfp/dsl/_resource_op.py
sdk/python/kfp/dsl/_volume_op.py
sdk/python/kfp/dsl/_volume_snapshot_op.py
sdk/python/kfp/dsl/data_passing_methods.py
sdk/python/kfp/dsl/types.py

Code formatting change only
- use 2 spaces indentation
- make (most) lines fit under 80 characters limit.
This is PR (1/2) for merging v2 dsl code back to v1.
**Checklist:**

chore(sdk): formatting code under kfp/dsl

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml

Fixes https://github.com/kubeflow/pipelines/issues/5236
**Checklist:**

deployment: adjust default resource requests. Fixes #5236

---

sdk/python/MANIFEST.in

Follow up on #5197 to include the schema yaml files into setuptools
Fixes https://github.com/kubeflow/pipelines/issues/5240
**Checklist:**

fix(sdk): include ontology_type_schemas/*.yaml in setuptools

---

api/v2alpha1/pipeline_spec.proto
api/v2alpha1/python/setup.py

Add parameter_expression_selector
**Checklist:**

release(api): Update pipeline_spec.proto and bump kfp-pipeline-spec version to 0.1.7.

---

frontend/public/index.html
frontend/server/app.test.ts
frontend/server/configs.ts
frontend/server/handlers/index-html.ts
frontend/server/integration-tests/test-helper.ts
frontend/src/components/SideNav.tsx
frontend/src/lib/Flags.ts

Hide the navigation sidebar when in `KUBEFLOW` deployment.
Related issue: https://github.com/kubeflow/pipelines/issues/5199 
**Checklist:**

feat(frontend): Hide sidebar in Kubeflow mode. Fixes #5199

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml

Fixes https://github.com/kubeflow/pipelines/issues/5232
Changes:
* manifests are copied from argo manifests of v2.12.9
**Checklist:**

feat(deployment): [GCP marketplace] upgrade argo to v2.12.9. Part of #5232

---

test/install-argo-cli.sh
test/sample-test/check_notebook_results.py
test/sample-test/run_resnet_cmle_test.py
test/sample-test/run_sample_test.py

test(samples): fix sample-test argo logs command. Fixes #5283

---

manifests/gcp_marketplace/schema.yaml

feat(deployment): Update deployer ksa roles so that it can unlock MKP side change which refines deployer KSA's permissions.
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the …

refactor(deployment): GCP marketplace detailed deployer KSA's permissions

---

sdk/python/kfp/dsl/artifact.py
sdk/python/kfp/dsl/artifact_utils.py
sdk/python/kfp/dsl/metrics_utils.py
sdk/python/kfp/dsl/ontology_artifacts.py
sdk/python/kfp/dsl/type_schemas/classification_metrics.yaml
sdk/python/kfp/dsl/type_schemas/confidence_metrics.yaml
sdk/python/kfp/dsl/type_schemas/confusion_matrix.yaml
sdk/python/kfp/dsl/type_schemas/metrics.yaml
sdk/python/kfp/dsl/type_schemas/sliced_classification_metrics.yaml
sdk/python/tests/dsl/artifact_test.py
sdk/python/tests/dsl/metric_utils_test.py
sdk/python/tests/dsl/test_data/expected_bulk_loaded_classification_metrics.json
sdk/python/tests/dsl/test_data/expected_bulk_loaded_confusion_matrix.json
sdk/python/tests/dsl/test_data/expected_classification_metrics.json
sdk/python/tests/dsl/test_data/expected_confusion_matrix.json
sdk/python/tests/dsl/test_data/expected_metrics.json
sdk/python/tests/dsl/test_data/expected_sliced_classification_metrics.json

Adds Metrics and ClassificationMetrics to ontology types. Common methods used by helper metric classes and Artifact class are moved to _artifact_utils.py

feat(sdk): Adds Metrics & ClassificationMetrics ontology types

---

manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py

fix(deployment): Set default resource requests and limits for pipeline pods. Fixes #5214

---

sdk/python/requirements.in
sdk/python/setup.py

- Fill in missing lower bounds using versions from https://github.com/kubeflow/pipelines/pull/3303
- Fill in missing upper bounds using the next major versions (assuming they all use semantic versioning, no the next major version could have incompatible changes).
**Checklist:**

chore(sdk): enforce lower and upper bounds on all dependencies.

---

sdk/python/kfp/_client.py

Part of https://github.com/kubeflow/pipelines/issues/5230.
**Checklist:**

feat(sdk): Uses 'https' as the default host protocol if users didn't specify any.

---

frontend/README.md
frontend/src/pages/ArtifactList.test.tsx
frontend/src/pages/ArtifactList.tsx

Internal bug link: b/156279314
Make pipeline names and component items to be underlined, so people understand that they are clickable. Also add a test file for `ArtifactList` using react testing library.
Screenshot: 
**Checklist:**

feat(frontend): Make pipeline and component clickable on Artifact list

---

backend/metadata_writer/src/metadata_writer.py

/assign @Ark-kun @neuromage 
try the image at gcr.io/ml-pipeline-test/11c3b5de629f880a49adc8b3de9cce59fcc2aa40/metadata-writer@sha256:5293b899cbe0e3cfc8b7891a394cc7ee5accb02543aac5173f3cbc65f0c5e1bc
**Checklist:**

chore(v2/metadata): metadata-writer skips v2 pods

---

manifests/kustomize/env/platform-agnostic-pns/kustomization.yaml
manifests/kustomize/env/platform-agnostic-pns/workflow-controller-configmap-patch.yaml
manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml

Part of #5285.
PNS executor still has some problems we need to resolve.
**Checklist:**

feat(deployment): keep defaulting to argo docker container runtime executor. Part of #5285

---

frontend/src/TestUtils.ts
frontend/src/lib/MlmdUtils.test.ts
frontend/src/lib/MlmdUtils.ts
frontend/src/pages/RunDetails.test.tsx
frontend/src/pages/RunDetails.tsx

Integrates ML Metadata tab with v2 metadata as produced in https://github.com/kubeflow/pipelines/pull/5261.
EDIT: you can try out the image [gcr.io/ml-pipeline-test/9812cafacd4f67051f481c9fecf5d670ca55ed13/frontend@sha256:3d5c35cb89ba2494bb04c4b9ab4231a0289b471de83c2d7e757f0c7574777c6c](gcr.io/ml-pipeline-test/9812cafacd4f67051f481c9fecf5d670ca55ed13/frontend@sha256:3d5c35cb89ba2494bb04c4b9ab4231a0289b471de83c2d7e757f0c7574777c6c) in your cluster to get the patched UI.
**Checklist:**

chore(v2/frontend): integrate ML Metadata tab with v2 metadata

---

sdk/python/kfp/__init__.py

chore(release): KFP SDK 1.4.1-rc.0

---

sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.json

chore(sdk.v2): Do not inject component input for loop arguments from component output

---

sdk/python/kfp/__init__.py

chore(release): KFP SDK 1.4.1-rc.1

---

components/kubeflow/kfserving/component.yaml
components/kubeflow/kfserving/requirements.txt

This PR updates the KFServing python package version used in this component. The image has already been pushed to quay.io.

feat(components) Update KFServing component to use v0.5.1

---

sdk/python/kfp/compiler/compiler.py

Fixes #5296
Update the validation of argo cli to be a small but a correct workflow. Open for discussion if we really like to validate with a workflow, but an empty string is not supported by argo lint any longer. 
**Checklist:**

fix(sdk): make workflow validation compatible with argo CLI v2.12+. Fixes #4775, Fixes #5296

---

frontend/src/__serializers__/mock-function.js
frontend/src/assets.d.ts
frontend/src/atoms/ExternalLink.tsx
frontend/src/atoms/HelpButton.tsx
frontend/src/components/ArtifactLink.tsx
frontend/src/components/CustomTableNameColumn.tsx
frontend/src/components/ExperimentList.tsx
frontend/src/components/MinioArtifactPreview.tsx
frontend/src/components/PodYaml.test.tsx
frontend/src/components/PodYaml.tsx
frontend/src/lib/Flags.ts
frontend/src/lib/GkeMetadata.tsx
frontend/src/lib/KubeflowClient.tsx
frontend/src/lib/MlmdUtils.test.ts
frontend/src/lib/MlmdUtils.ts
frontend/src/lib/ParserUtils.ts
frontend/src/pages/GettingStarted.test.tsx
frontend/src/react-app-env.d.ts

Fixes https://github.com/kubeflow/pipelines/pull/5308#discussion_r596233860
**Checklist:**

chore(frontend): add missing license notices

---

manifests/kustomize/base/cache-deployer/kustomization.yaml
manifests/kustomize/base/cache/kustomization.yaml
manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
manifests/kustomize/base/metadata/kustomization.yaml
manifests/kustomize/base/pipeline/kustomization.yaml
manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
manifests/kustomize/hack/release.sh

We refactored `params.env` to `pipeline-install-config.yaml`, updating release script correspondingly.
**Checklist:**

chore(release): fix release script

---

RELEASE.md

docs(release): update release instructions

---

test/OWNERS

chore(test): add chensun to test/OWNERS, remove numerology

---

test/presubmit-tests-tfx.sh

Fixes https://github.com/kubeflow/pipelines/issues/5355
**Checklist:**

test: Update bazel version in presubmit-tests-tfx.sh

---

test/README.md

Links are out-of-date in the README file.
**Checklist:**

fix(test): Update reference link in test README.md

---

api/v2alpha1/pipeline_spec.proto

chore(api): deprecate AIPlatformCustomJobSpec

---

.github/ISSUE_TEMPLATE/BUG_BACKEND.md
.github/ISSUE_TEMPLATE/BUG_FRONTEND.md
.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/BUG_SDK.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md

To help triaging issues better, and collect necessary information for debugging, create issue templates for users to select with predefined areas.
**Checklist:**

chore: Add issue templates for GitHub issue creation

---

sdk/python/kfp/_client.py
sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml
sdk/python/kfp/compiler/v2_compat.py
sdk/python/kfp/compiler/v2_compatible_compiler_test.py

Allow the launcher image to be configurable. Especially useful for tests.
**Checklist:**

chore(sdk): Allow the launcher image to be configurable. 

---

.github/ISSUE_TEMPLATE/BUG_FRONTEND.md

Minor change to remove empty bullet point.
**Checklist:**

chore: Minor update on GitHub issue bug template

---

backend/metadata_writer/src/metadata_writer.py

Apply the same fix of https://github.com/kubeflow/pipelines/pull/5188 to metadata-writer
**Checklist:**

fix(metadata-writer): skip latest TFX pods

---

v2/test/samples/fail_test.py
v2/test/samples/two_step_test.py

Part of https://github.com/kubeflow/pipelines/issues/3505
Put all v2_sample_test sample pipeline runs into an experiment called v2_sample_test_samples
**Checklist:**

test: create v2_sample_test samples in its own experiment

---

samples/contrib/mnist/README.md

The link https://www.kubeflow.org/docs/components/jupyter/ is broken and returns a 404 believe it should be https://www.kubeflow.org/docs/components/notebooks/
**Checklist:**

docs(readme): update url

---

sdk/python/kfp/dsl/_component_bridge.py
sdk/python/kfp/dsl/_pipeline_param.py
sdk/python/kfp/dsl/component_spec.py
sdk/python/kfp/dsl/component_spec_test.py
sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler/compiler_test.py
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.py
sdk/python/tests/dsl/pipeline_param_tests.py

Fixing issues where
- subgroup tasks cannot access outputs outside the DAG.
- possible missing types for PipelineParam.
- possible inconsistence in name sanitization.
- possible name collisions between original component inputs and compiler-injected inputs.
**Checklist:**

chore(sdk.v2): fix a couple of issues related to cross-DAG i/o referencing and more.

---

samples/contrib/kubeflow-katib/mpi-job-horovod.py

…
A user might want to run the experiment again and again and thus choose a different name each time. This will not require him to compile and upload the pipeline each time.
Similarly, a users namespaces may be different from "anonymous".
**Checklist:**

fix(samples): Allow user to set the namespace and name  for the sample as parameters.

---

manifests/kustomize/base/installs/multi-user/api-service/deployment-patch.yaml
manifests/kustomize/base/installs/multi-user/pipelines-ui/deployment-patch.yaml
manifests/kustomize/base/installs/multi-user/virtual-service.yaml
manifests/kustomize/env/platform-agnostic-multi-user-legacy/kustomization.yaml
manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml
manifests/kustomize/third-party/argo/upstream/manifests/cluster-install/workflow-controller-rbac/kustomization.yaml
manifests/kustomize/third-party/metacontroller/base/cluster-role-binding.yaml
manifests/kustomize/third-party/metacontroller/base/crd.yaml
manifests/kustomize/third-party/metacontroller/base/kustomization.yaml
manifests/kustomize/third-party/metacontroller/base/service-account.yaml
manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml

Fix https://github.com/kubeflow/pipelines/issues/5402
Fix https://github.com/kubeflow/pipelines/issues/5398
Fix https://github.com/kubeflow/pipelines/issues/5399
Fix https://github.com/kubeflow/pipelines/issues/5400

fix(deployment): Manifests fixes for KF 1.3

---

manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py

Follow up of https://github.com/kubeflow/kubeflow/pull/5762
**Checklist:**

fix(deployment): pipelines profile controller uses pipelines.kubeflow.org/enabled label

---

.cloudbuild.yaml
.release.cloudbuild.yaml
manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
manifests/kustomize/hack/format.sh
manifests/kustomize/hack/presubmit.sh
manifests/kustomize/hack/release.sh
test/tag_for_hosted.sh

Error during release
```
+ yq w -i /go/src/github.com/kubeflow/pipelines/manifests/kustomize/hack/../base/metadata/kustomization.yaml 'images[*].newTag' 1.5.0-rc.1
Error: stat /go/src/github.com/kubeflow/pipelines/manifests/kustomize/hack/../base/metadata/kustomization.yaml: no such file or directory
```
Changes:
* fix the dir move
* add presubmit to verify release script keeps working
**Checklist:**

chore(release): fix metadata release script and add presubmit

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml
manifests/kustomize/third-party/minio/minio-deployment.yaml
manifests/kustomize/third-party/mysql/mysql-deployment.yaml
test/presubmit-tests-mkp.sh

Fixes #5148 
Changes:
1. memory should use 'Mi' unit, instead of 'm'
2. add back resource request for argo deployment
3. adjust defaults according to https://github.com/kubeflow/pipelines/pull/5237
**Checklist:**

fix(deployment): fix default resource requests. Fixes #5148

---

sdk/python/kfp/dsl/component_spec.py
sdk/python/kfp/dsl/component_spec_test.py
sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.py

The "punching holes" was incomplete for `component_input_parameter` and `component_input_artifact`.
**Checklist:**

fix(sdk.v2): fix bug for component input parameter/artifact referencing

---

components/aws/sagemaker/tests/integration_tests/Dockerfile
components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests

enable ssm on eks worker nodes to enable patching on worker node
option exists in latest eksctl - https://eksctl.io/introduction/#ssh-access
**Checklist:**

chore(components): AWS SageMaker tests enable ssm on eks worker nodes

---

sdk/python/kfp/compiler/_data_passing_rewriter.py
sdk/python/kfp/components/_components.py
sdk/python/kfp/components_tests/test_components.py
sdk/python/kfp/dsl/_component_bridge.py
sdk/python/tests/dsl/component_bridge_tests.py

Moved the execution engine specific code to the component bridge.

chore(sdk): Refactored command-line resolving

---

sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/dsl/_container_op.py
sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.py
sdk/python/kfp/v2/google/aiplatform.py
sdk/python/kfp/v2/google/aiplatform_test.py
sdk/python/kfp/v2/google/testdata/expected_custom_job_pipeline.json

Support setting custom job spec. If the jobSpec is omitted, we auto-fill it using the existing container spec.
**Checklist:**

feat(sdk.v2): Support setting custom job spec in v2.

---

RELEASE.md

introduce how to resolve this error message in release
**Checklist:**

chore(release): instructions for docker.sock: permission denied resolution

---

sdk/python/kfp/dsl/component_spec.py
sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.py
sdk/python/requirements.in
sdk/python/requirements.txt
sdk/python/setup.py

- Fixes loop DAG topology: insert an intermediate component to hold loop arguments items from each loop iteration so that loop subtasks are not iterating independently.
- Supports iterating over `subvar` (a key in a map) for loop arguments from pipeline param or component output.
- Adds a test case that covers multi-layer nested conditions and loops - testing the "punch holes" logic.
**Checklist:**

feat(sdk.v2): fix loop implementation and add subvar support

---

components/google-cloud/google_cloud_components/aiplatform/__init__.py
components/google-cloud/google_cloud_components/aiplatform/remote_runner.py
components/google-cloud/google_cloud_components/aiplatform/utils.py

Updating the method signature to match the new format in aiplatfrom for datasets. Also includes a few unrelated nit corrections.

components: google-cloud-sdk - Updates based on changes to aiplatform.Datasets

---

components/google-cloud/README.md

Updating `README.md` with package description, high level over view and build / install instructions.

components: google-cloud-sdk - Add build and install instructions in readme

---

test/presubmit-tests-tfx.sh

Install extra packages for test: https://github.com/tensorflow/tfx/blob/5b6182c6ced3cf7495ca1446db3318fd9afa73c3/setup.py#L206
Fixes #5476
**Checklist:**

test: fix presubmit kubeflow-pipelines-tfx-python36

---

frontend/package.json

Tested in Chinese Mandarin locale to validate that this resolve the time formatting issues in snapshot test.
Fixes https://github.com/kubeflow/pipelines/issues/5457 
**Checklist:**

test(frontend): Resolve locale issue in tests from machine other than US. Fix #5457 

---

components/google-cloud/README.md
components/google-cloud/google_cloud_components/aiplatform/__init__.py

Adding name and description of supported OPs to readme file.

components: (google-cloud-sdk) Add supported OP names and description to readme.

---

components/google-cloud/google_cloud_components/aiplatform/__init__.py
components/google-cloud/google_cloud_components/aiplatform/utils.py

fix: pass in class directly

---

components/google-cloud/google_cloud_components/aiplatform/__init__.py
components/google-cloud/google_cloud_components/aiplatform/utils.py

Branched from this PR: https://github.com/kubeflow/pipelines/pull/5488
Block this PR until 5488 is in.
**Checklist:**

[google-cloud-component-sdk] fix: Ignore none

---

sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/dsl/_pipeline.py
sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler/compiler_test.py
sdk/python/kfp/v2/compiler/main.py
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.py

Remove `pipeline_root` from Compiler.compile(...) function arguments.
**Checklist:**

feat(sdk.v2): remove pipeline_root from compiler interface

---

samples/core/exit_handler/exit_handler.py
samples/core/exit_handler/exit_handler_test.py
samples/core/loop_parallelism/loop_parallelism_test.py
samples/core/output_a_directory/output_a_directory.py
samples/core/output_a_directory/output_a_directory_test.py
samples/test/config.yaml
samples/test/legacy_exit_handler.py
samples/test/legacy_exit_handler_test.py

Either the old sample and updated sample fails, not sure if it's related to exit handler or not.
**Checklist:**

test: add exit_handler, loop_parallism and output_a_directory pipelines to v2 sample test

---

samples/core/resource_spec/resource_spec_test.py
samples/test/fail_parameter_value_missing_test.py
samples/test/fail_test.py
samples/test/legacy_exit_handler_test.py
samples/test/lightweight_python_functions_v2_pipeline_test.py
samples/test/lightweight_python_functions_v2_with_outputs_test.py
samples/test/parameter_with_format_test.py
samples/test/placeholder_concat_test.py
samples/test/reused_component_test.py
samples/test/simple_pipeline_without_importer_test.py
samples/test/two_step.py
samples/test/two_step_test.py
samples/test/util.py
samples/test/various_io_types_test.py
v2/test/Dockerfile
v2/test/Makefile
v2/test/README.md
v2/test/requirements.txt

Example test to verify MLMD state of a pipeline
**Checklist:**

test(v2/samples): verify sample mlmd state

---

components/deprecated/tfx/ExampleValidator/component.py
components/deprecated/tfx/ExampleValidator/component.yaml

The URL https://www.tensorflow.org/tfx/data_validation returns a 404 belive it should instead be https://www.tensorflow.org/tfx/data_validation/get_started
**Checklist:**

DOCS url 404

---

components/google-cloud/container/aiplatform/Dockerfile
components/google-cloud/dependencies.py

chore(components/google-cloud): update python-aiplatform dependency to pypi

---

sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler/compiler_test.py

Per feedback from Amy
**Checklist:**

chore(sdk.v2): Remove warning on missing pipeline root at compile time

---

samples/test/util.py
v2/.gitignore
v2/Makefile
v2/README
v2/README.md
v2/launcher_container/Dockerfile
v2/launcher_container/Dockerfile.dev
v2/test/README.md

Changes:
* let v2 sample test load from local env var "KFP_LAUNCHER_IMAGE" as default
* speed up kfp-launcher image build by setting up Makefile and Dockerfile.dev to build launcher binary locally and copy into a docker container
* document how to configure the above using one's own project
**Checklist:**

chore: local dev workflow for v2 launcher + sample test

---

v2/Makefile
v2/go.mod
v2/metadata/client.go
v2/metadata/client_test.go

Fixes race condition that causes error:
```
"Failed to successfuly execute component: rpc error: code = AlreadyExists desc = Given node already exists: type_id: 2"
Internal: mysql_query failed: errno: 1062, error: Duplicate entry '2-pipeline-with-loop-parameter-beta' for key 'type_id'
```
**Checklist:**

chore(v2/launcher): fix race condition that causes intermittent AlreadyExists error

---

sdk/python/kfp/v2/compiler/compiler.py

chore(sdk.v2): block recursive subgroup in v2.

---

samples/test/util.py

to mitigate flakiness like https://github.com/kubeflow/pipelines/pull/5562#issuecomment-828909893
**Checklist:**

test: add backoff retry to kfp api call

---

samples/core/loop_parameter/loop_parameter.py
samples/core/loop_parameter/loop_parameter_test.py

chore(sample): Update loop_parameter.py sample so it's compatible in both v1 and v2

---

sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/v2_compat.py

add-v2-compact-metrics-label
**Checklist:**

chore(sdk.v2):add v2 compact metrics label

---

samples/test/two_step_test.py
samples/test/util.py
v2/component/runtime_info.go
v2/component/runtime_info_test.go

add name as custom property of MLMD artifacts
**Checklist:**

chore(v2): add name as custom property of MLMD artifacts

---

frontend/OWNERS

/assign @zijianjoy 
**Checklist:**

Add zijianjoy to frontend/OWNERS

---

v2/test/components/kaniko.yaml

Debug logs are in https://github.com/kubeflow/pipelines/issues/5586
**Checklist:**

test(v2): fix kaniko component digest

---

sdk/python/kfp/compiler/_default_transformers.py
sdk/python/kfp/compiler/compiler.py
sdk/python/tests/compiler/compiler_tests.py
sdk/python/tests/compiler/testdata/basic_no_decorator.yaml

Add pod labels for telemetry purpose
**Checklist:**

[SDK] Add pod labels for telemetry purpose

---

samples/test/util.py

added double value. (FYI: https://github.com/kubeflow/pipelines/pull/5567#discussion_r626507183)
**Checklist:**

fix(v2):added double value

---

.cloudbuild.yaml
.release.cloudbuild.yaml
backend/metadata_writer/requirements.in
backend/metadata_writer/requirements.txt
manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
test/tag_for_hosted.sh
v2/Makefile
v2/test/requirements.txt

updated mlmd to 0.30.0
**Checklist:**

feat: update MLMD to 0.30.0

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/ResourceInfo.tsx
frontend/src/lib/MlmdUtils.ts

/assign @capri-xiyue 
Part of https://github.com/kubeflow/pipelines/pull/5575
**Checklist:**

chore(frontend): upgrade kubeflow/frontend lib

---

v2/OWNERS

/assign @capri-xiyue @neuromage 
**Checklist:**

Add OWNERS for v2 folder

---

sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.py

Follow up on https://github.com/kubeflow/pipelines/pull/5491, use the new prediction components.
**Checklist:**

test(sdk.v2): update xgboost sample pipeline

---

test/presubmit-tests-tfx.sh

Fixes https://github.com/kubeflow/pipelines/issues/5614
**Checklist:**

test: pin google-cloud-bigquery to fix TFX presubmit

---

test/presubmit-tests-tfx.sh

Replace `taxi_pipeline_kubeflow_gcp_test.py` with `penguin_pipeline_kubeflow_gcp_test.py`
Fixes: https://github.com/kubeflow/pipelines/issues/5627
**Checklist:**

test: Update test cases in presubmit-tests-tfx.sh

---

v2/component/launcher.go

added mlmd error logging
**Checklist:**

chore(v2): added mlmd error logging

---

sdk/python/kfp/_client.py

Add `pipeline_root` as an optional argument to KFP client's public **run** methods, so that users can specify `pipeline_root` for pipelines compiled with V2_COMPATIBLE or V2_ENGINE mode.
**Checklist:**

feat(sdk.v1): Add pipeline_root as an argument to client's public run methods.
