backend/src/crd/controller/viewer/reconciler/reconciler.go, backend/src/crd/controller/viewer/reconciler/reconciler_test.go
Using latest causes various uncertainties due to tensorflow backward incompatibility especially new 2.0.
In long term we should allow user specify the tensorboard image version. 
cc @jingzhang36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2513)
=> Pin tensorboard version to 1.13.2

.travis.yml
The test was broken due to recent renaming of TFX files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2521)
=> [Test] Fix TFX related Travis tests

sdk/python/kfp/compiler/_data_passing_rewriter.py
Also fixes handling other cases with double curly braces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2522)
=> SDK - Compiler - Fixed failures on Jinja placeholders

samples/contrib/parameterized_tfx_oss/README.md, samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.py
Sample background: 
There is a breaking change introduced in TFX side in [this PR](https://github.com/tensorflow/tfx/commit/9b79f8af839ff01bdde079c873e3f9d3225d3209#diff-93a4c8b6e41081e9ae98c006808a0bb6), adding a required argument `component_config` to `container_entrypoint.py`. As a result, if a user compile this uDSL file using TFX head but try to run it against our `patched-tfx:0.1.32` image, it will fail due to missing argument. 
I think it would a reasonable fix if we align this sample with TFX for now. After this change, when the user compile this sample from TFX head, a pipeline using latest TFX nightly build would be returned, which is consistent with the yaml spec. Though the generated yaml spec is slightly different from what we baked into our backend server, which I think is …
=> [Sample] Align preload TFX sample with TFX head

frontend/src/components/ArtifactLink.tsx, frontend/src/components/GcsLink.tsx, frontend/src/components/ResourceInfo.tsx, frontend/src/pages/ArtifactList.tsx
Currently the Artifacts list makes artifact URLs clickable only when they are 'gs://'.
This commit adds support for https: links.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2517)
=> Frontend - Added support for https artifact links

frontend/package.json
Format check should happen before linting, because format is easier to fix and some of lint errors can be fixed by format.
/approve
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2525)
=> Frontend format check should be before linting.

sdk/python/kfp/_client.py
URLs joining should not depend on OS path separator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2524)
=> SDK - Client - Fixed client on Windows

backend/src/apiserver/visualization/third_party_licenses.csv
Presubmit tests fail because of this
/kind bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2546)
=> Fix broken license link for jupyter notebook

components/third_party_licenses.csv
This is blocking this week's release.
follows up on https://github.com/kubeflow/pipelines/pull/2546
/kind bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2552)
=> Fix more notebook license issues

test/deploy-cluster.sh
For debugging postsubmit test failure: pod with image pull back off.
Related reference:
* https://cheatsheet.dennyzhang.com/cheatsheet-kubernetes-a4
* The approach we use won't work with CrashLooPBackOff, https://github.com/kubernetes/kubernetes/issues/49387#issuecomment-504405180
However, I don't want to workaround kubectl limitations. This one is good enough. We can improve when we actually see crash loop back off issue.
/area testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2554)
=> [Testing] Describe unhealthy pods when tests clean up.

test/component_test.yaml
These two steps should be sequential, but they are written as parallel.
Reference: https://github.com/argoproj/argo/blob/master/examples/steps.yaml
The issue this bug caused:
If image failed to build in postsubmit tests, the test will timeout in 2 hours instead of failing with error message right away, because the second step will be stuck in ImagePullBackOff, and it never stops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2557)
=> Fix postsubmit test which times out

test/sample-test/Dockerfile
I want to first test if this fix actually help.
part of https://github.com/kubeflow/pipelines/issues/2556
The fix come from https://stackoverflow.com/a/37531821
/kind bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2563)
=> Fixes test flakiness caused by "unsupported operand type(s) for -=: 'Retry' and 'int'"

test/cloudbuild/batch_build.yaml
Even in a successful test, we can see inverse proxy is in ImagePullBackOff state. It's not used in any e2e tests, so it doesn't break presubmit.
example log: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/2563/kubeflow-pipeline-e2e-test/1192300433008234496#1:build-log.txt%3A1426
However, this issue breaks image caching. Inverse proxy agent is always not in gcr because we didn't push it there. This PR fixes the issue.
Benefit of the fix: rerunning tests will skip the image building step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2566)
=> Fix inverse proxy agent in e2e tests

test/cloudbuild/batch_build.yaml
This dockerfile assumes it is called in its containing dir as workspace. It's different from most other dockerfiles which assumes project root.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2568)
=> Fix inverse-proxy test cloudbuild yaml

backend/src/apiserver/client/sql.go, backend/src/apiserver/client_manager.go, backend/src/apiserver/config/config.json
Fix for KFP issue: #2310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2497)
=> Set DB GroupConcatMaxLen config to default of 4MB

sdk/python/kfp/components/_python_op.py
This fixes formatting for components where function does not have a return annotation.
The low-level cause of issue: Trailing whitespace when there are no serializers.
Trailing whitespace triggers ugly YAML string formatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2529)
=> SDK - Components - Fixed YAML formatting for some components

frontend/server/aws-helper.ts, frontend/server/k8s-helper.ts, frontend/server/minio-helper.ts, frontend/server/package-lock.json, frontend/server/package.json, frontend/server/server.ts, frontend/server/workflow-helper.ts, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml
A possible workaround for #1803 
Currently, I persist pod logs with argo's archiveLogs config to s3 bucket. 
This PR allow the UI to fallback to retrieving GCed pods logs from the argo archive artifactory - this can be either minio store or a s3 bucket.
This feature can be enabled by setting the following env variables:
```js
/** Is Argo log archive enabled? */
ARGO_ARCHIVE_LOGS = "true",
/** Use minio or s3 client to retrieve archives. */
ARGO_ARCHIVE_ARTIFACTORY = 'minio',
/** Bucket to retrive logs from */
ARGO_ARCHIVE_BUCKETNAME = 'mlpipeline',
/** Prefix to logs. */
ARGO_ARCHIVE_PREFIX = 'logs',
```
Investigate the feasibility of getting pod logs archive location from argo workflow status:
- conclusion is yes, but if the pipeline did not complete successfully, the status will not be …
=> [pipeline-ui] Retrieve pod logs from argo archive

backend/Dockerfile, backend/Dockerfile.bazel, backend/build_api_server.sh, developer_guide.md, frontend/Dockerfile
Referencing [comment ](https://github.com/kubeflow/kubeflow/issues/2337#issuecomment-524690065)and issue [#2337](https://github.com/kubeflow/kubeflow/issues/2337)
We are working on Kubeflow supporting arm64 platform. We now rebuilt some images and installed Kubeflow on arm64, and hence contribute the Dockerfile.
Tested on both arm64 machine and x86_64 machine
Signed-off-by: Henry Wang <<henry.wang@arm.com>>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2507)
=> Add arm64 support for ml-pipeline

components/google-cloud/storage/download/component.yaml, components/google-cloud/storage/download_blob/component.yaml, components/google-cloud/storage/download_dir/component.yaml, components/google-cloud/storage/list/component.yaml, components/google-cloud/storage/upload_to_explicit_uri/component.yaml, components/google-cloud/storage/upload_to_unique_uri/component.yaml, release/RELEASE.md
Added components for Google Cloud Storage:
* Upload
* Download
* List blobs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2532)
=> Components - Google Cloud Storage

samples/core/loop_static/loop_static.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_for_loop.py
Partially fix #2570 
Question: I can imagine for withparams we have the same problem if user provides arbitrary names in the loop variable's runtime value. How to prevent that from happening? Shall we bypass k8s name sanitization in this case?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2572)
=> [SDK] Fix withItem loop

frontend/src/lib/Apis.ts
Fixes https://github.com/kubeflow/pipelines/issues/1572#issuecomment-510264328
Before fix:
All api requests fail in Firefox because cookie is not sent by default.
After fix:
Cookies are sent with 'credentials: same-origin' policy. All the UI work properly in Firefox.
Verification
Built a new image locally and swaps into a marketplace deployed cluster, verified firefox can now use the UI properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2580)
=> [UI] Fix firefox compatibility

manifests/gcp_marketplace/guide.md
Change the way of specifying namespace.
Sometimes `--current` option might not work for gcloud in MacOS, causing empty secret and permission issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2576)
=> [Doc] Minor fix to MKP secret setup guide

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2586)
=> 0.1.34 changelog

frontend/src/lib/Apis.ts
I just realized the fix in https://github.com/kubeflow/pipelines/pull/2580 could be much simpler, because `protected fields` in constructor only means this field will become a protected field after construction. It can still be specified explicitly from outside in constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2587)
=> [UI] Simplify firefox fix in pull/2580

frontend/mock-backend/mock-api-middleware.ts, frontend/src/pages/PipelineDetails.test.tsx, frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx
Fixes an issue related to #2488.
If you click certain buttons before the full page has loaded then there will be adverse results due to no pipeline/run id being specified. An example is clicking the "Delete" button on the pipeline details page before the page has fully loaded will result in receiving a popup saying "Delete succeeded for this pipeline", but nothing will be deleted.
In the pipeline details page the "Create Experiment" and "Delete" buttons were changed to include the pipeline id.
In the run details page the "Retry", "Clone Run", and "Terminate" buttons were changed to include the run id.
My only concern is that I am not sure if the api is fail safe in regards to being asked to terminate a run for a run id which is already finished running. This is possible because the …
=> Fix missing run and pipeline id when buttons are clicked before content load

samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.py
Cleaned up some unused import and linting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2594)
=> [Sample] Lint and clean up parameterized TFX sample

sdk/python/kfp/components/structures/components.json_schema.json, sdk/python/kfp/components/structures/components.json_schema.outline.yaml
See the much shorter outline of the schema: https://github.com/kubeflow/pipelines/blob/ae7cefede4cc005b5d2f443156450f317220a99e/sdk/python/kfp/components/structures/components.json_schema.outline.yaml
It's not an example. It's an outline. It's a component schema with sub-schemas inlined and without any extra info.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/669)
=> SDK/Components  - Added Json Schema spec for the component format

backend/src/apiserver/storage/pipeline_store.go
(1) a typo (2) r.Close to avoid bad connection error (3) forgot to return after commit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2611)
=> Fix a few bugs in delete pipeline version that are discovered in integration test

sdk/python/setup.py
The `kfp.cli.diagnose_me` package was missing from the setup.py packages list and so wasn't included in the latest release pushed to pypi.org.
This package is required to run the `kfp` CLI - it raises a "Module Not Found" exception if not present
Fixes #2609
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2610)
=> Adding missing kfp.cli.diagnose_me package to setup.py Fixes #2609

components/gcp/container/component_sdk/python/kfp_component/google/bigquery/_query.py
Small fix for #2612 by constructing a QueryJobConfig object from the `job_config` dict if it is given.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2616)
=> casting job_config to QueryJobConfig if supplied by user

manifests/kustomize/base/proxy/proxy-deployment.yaml
When switching to GKE workload identity, the pods can't access to metadata server anymore by default due to metadata concealment. 
This can be unlocked by explicitly enable hostnetwork for the pod. 
https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#concealment
This should be OK as proxy is an optional component. In any case when user feel this not a secure option he/she could opt out it.
/assign @Bobgy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2614)
=> Enable inverse proxy to access host network

sdk/python/kfp/compiler/compiler.py
As issue raised in https://github.com/kubeflow/pipelines/issues/2495
The output from yaml.dump does not work well with golang's backend causing the pipeline to return 500 when triggered due to yaml parsing error
Maybe it's better to detect when the string is too long and apply block style accordingly than applying for every field, that's up to the maintainer, but this fixes the 500 as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2591)
=> [fix] default yaml.dump to block style

frontend/mock-backend/mock-api-server.ts, frontend/src/components/Router.test.tsx, frontend/src/components/Router.tsx, frontend/src/components/Toolbar.tsx, frontend/src/components/__snapshots__/Router.test.tsx.snap, frontend/src/components/__snapshots__/Toolbar.test.tsx.snap, frontend/src/index.tsx, frontend/tslint.json
Toolbar, title, ... state used to get shared between pages. This caused unpredictable behavior when dangling network requests come back. It was reported in https://github.com/kubeflow/pipelines/issues/2590.
For review, [this file](https://github.com/kubeflow/pipelines/pull/2622/commits/2feaf2d3f73cb351cc4bc4c72abb2ff0b39ed575#diff-49667469ed86eeaa60660982d608ef4e
) contains all the major changes.
Changes in this PR:
* Refactor related components to facilitate testing.
* Add a failing test to reflect this bug.
* Fix the bug and verify the test passes now.
* Disable lint errors for test files.
Videos: https://github.com/kubeflow/pipelines/issues/2590#issuecomment-554897861
Fixes https://github.com/kubeflow/pipelines/issues/2590
--- …
=> [UI] Separate page state for each page instance

sdk/python/kfp/_auth.py, sdk/python/kfp/_client.py, sdk/python/kfp/cli/cli.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2626)
For local dev, it opens up a tab in the webbrowser; For notebooks, it displays a link.
It also stores the credentials locally in $HOME/.config/kfp/credentials.db such that future requests can be automated.
=> Add support for user account auth with IAP

.travis.yml, frontend/package-lock.json, frontend/package.json, frontend/scripts/get-coveralls-repo-token.js, frontend/scripts/report-coveralls.sh
Note, test configuration in prow lives in https://github.com/kubernetes/test-infra/pull/15358
Update, this is ready for review and merge.
This is part of https://github.com/kubeflow/pipelines/issues/1653
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2637)
=> Move frontend unit tests to prow

backend/src/apiserver/server/api_converter.go, backend/src/apiserver/server/api_converter_test.go
Api resource type conversion needs to convert pipeline version type, since now pipeline version shows as a type of resource reference in run
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2648)
=> api resource type conversion needs to convert pipeline version type

frontend/public/index.html, frontend/server/server.ts
Pipeline UI pod will pass this feature flag to client: "DEPLOYMENT=KUBEFLOW".
In browser UI code, the flag can be accessed as `window.KFP_FLAGS.DEPLOYMENT`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2631)
=> Frontend server: add feature flag for kubeflow deployment

samples/core/loop_static/loop_static.py, samples/core/volume_ops/volume_ops.py, sdk/python/kfp/_client.py, sdk/python/kfp/compiler/_k8s_helper.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_pipeline_param.py, sdk/python/tests/compiler/testdata/pipelineparams.yaml, sdk/python/tests/compiler/testdata/recursive_while.yaml, sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml, sdk/python/tests/compiler/testdata/withitem_basic.yaml, sdk/python/tests/compiler/testdata/withitem_nested.yaml, sdk/python/tests/compiler/testdata/withparam_global.yaml, sdk/python/tests/compiler/testdata/withparam_global_dict.yaml, test/sample-test/configs/xgboost_training_cm.config.yaml
Let k8s sanitization allows capital letters and under score in the names of parameters/outputs. This change will allow users to refer to self-defined attributes of a complex structure in a more Pythonic way. 
One implication of this change would be, we have to delegate to users the responsibility of ensuring the argo naming convention when they create any k8s object within the pipeline. For example, in the [volume ops example](https://github.com/kubeflow/pipelines/tree/master/samples/core/volume_ops), a user should specify `name='create-pvc'` instead of `name='create_pvc'` to comply with argo naming convention.
Fixes #2570
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines …
=> [SDK] Relax k8s sanitization

components/git/clone/component.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2658)
=> Components - Git clone

components/filesystem/get_file/component.yaml, components/filesystem/get_subdirectory/component.yaml, components/filesystem/list_items/component.yaml
* Get subdirectory
* Get file
* List items
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2659)
=> Components - Filesystem

frontend/src/components/ArtifactLink.tsx, frontend/src/lib/Utils.test.ts, frontend/src/lib/Utils.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2645)
=> Frontend - Add support for Minio artifact URIs

frontend/package.json
/area frontend
/kind bug
Fixes error messages like the following when running `npm run test:coverage` during presubmit tests
```
Failed to collect coverage from /home/prow/go/src/github.com/kubeflow/pipelines/frontend/src/generated/src/apis/metadata/metadata_store_service_pb_service.d.ts
ERROR: Debug Failure. Output generation failed
STACK: Error: Debug Failure. Output generation failed
at Object.transpileModule (/home/prow/go/src/github.com/kubeflow/pipelines/frontend/node_modules/typescript/lib/typescript.js:112350:29)
at Object.process (/home/prow/go/src/github.com/kubeflow/pipelines/frontend/node_modules/ts-jest/dist/preprocessor.js:20:28)
at ScriptTransformer.transformSource (/home/prow/go/src/github.com/kubeflow/pipelines/frontend/node_modules/jest-runtime/build/script_transformer.js …
```
=> Configure jest to hide noisy message about no coverage data on .d.ts files

test/cloudbuild/api_server.yaml, test/cloudbuild/batch_build.yaml
This should make reading cloudbuild error message a lot easier
Build log looks like the following now, it's clear which step is building which image
```
Starting Step #5 - "inverse-proxy-agent"
Starting Step #1 - "scheduledworkflow"
Starting Step #3 - "viewer-crd-controller"
Starting Step #0 - "persistenceagent"
Starting Step #2 - "frontend"
Starting Step #4 - "visualization-server"
Step #5 - "inverse-proxy-agent": Already have image (with digest): gcr.io/cloud-builders/docker
Step #1 - "scheduledworkflow": Already have image (with digest): gcr.io/cloud-builders/docker
Step #0 - "persistenceagent": Already have image (with digest): gcr.io/cloud-builders/docker
Step #3 - "viewer-crd-controller": Already have image (with digest): gcr.io/cloud-builders/docker
Step #4 - …
```
=> Add readable step id for test cloudbuild steps

frontend/public/index.html, frontend/server/server.ts, frontend/src/index.tsx, frontend/src/lib/Flags.ts, frontend/src/lib/KubeflowClient.ts, frontend/src/lib/KubeflowClient.tsx, frontend/tslint.json
Needed for kubeflow multi user support
/cc @gaoning777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2655)
=> [UI] Get kubeflow namespace from kfp UI

backend/src/apiserver/resource/model_converter.go, backend/src/apiserver/resource/model_converter_test.go, backend/src/apiserver/server/api_converter.go, backend/src/apiserver/storage/resource_reference_store.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2698)
=> Store ns in db

sdk/python/kfp/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py
Fixes https://github.com/kubeflow/pipelines/issues/428
Case exhibiting the problem:
```
def some_name():
dsl.ContainerOp(
name='some_name',
image='alpine:latest',
)
kfp.compiler.Compiler().compile(some_name)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1555)
=> SDK/Compiler - Preventing pipeline entrypoint template name from clashing with other template names

sdk/python/kfp/components/_python_op.py
When auto-creating components from functions I want the generated component names to look "human". For example "def do_something()" should result in "Do something".
I thought that `capitalize` was doing exactly what I want, but it turned out that its behavior is different. It lowers the case of all subsequent characters, transforming "CsvExampleGen" to "Csvexamplegen". 
This PR fixes that issue and only changes the first character.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2688)
=> SDK - Fixed the capitalization in _python_function_name_to_component_name

test/cloudbuild/api_server.yaml, test/cloudbuild/batch_build.yaml
@Ark-kun 
Improve readability by putting id as the first line
improves on https://github.com/kubeflow/pipelines/pull/2673
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2703)
=> Improve test cloudbuild yaml readability

backend/src/apiserver/client_manager.go, backend/src/apiserver/model/pipeline_version.go
The current implementation of combined unique key is not working. The unique_index should be defined on the two columns (name and pipeline id) in order for those two columns to be combined unique key. So remove the old (not-working) index and add the new combined unique keys. (BTW, the current implementation makes the name globally unique)
Test: manual test with a deployment of KFP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2712)
=> Fix combined unique keys

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml, manifests/kustomize/base/metadata/metadata-configmap.yaml, manifests/kustomize/base/metadata/metadata-deployment.yaml
This change adds the necessary config-map related to gRPC MLMD server.
To make the names more clear, this change also modifies the existing 'metadata-configmap' which provides mysql configurations to 'metadata-mysql-configmap'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2723)
=> Metadata: Adding metadata-grpc config map

frontend/package-lock.json, frontend/server/package-lock.json
This is result of `npm audit fix`.
There are also vulnerabilities that we cannot fix automatically. Almost all of them come from create-react-app-ts, we should finish https://github.com/kubeflow/pipelines/issues/2432 to reduce other vulnerabilities.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2724)
=> [UI] Fix npm vulnerabilities

backend/src/apiserver/config/sample_config.json
Use a fixed version instead of master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2722)
=> [Doc] Fix links in preload sample

sdk/python/kfp/containers/_k8s_job_helper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2683)
=> 2682: Support a custom kube config location in K8sJobHelper

manifests/gcp_marketplace/README.md, manifests/gcp_marketplace/guide.md
The UI on the GCP Console marks the Kubeflow Pipelines Marketplace deployment as **Alpha**. The Marketplace UI links to this GitHub repo for a guide to the deployment. I think we should therefore put an "Alpha" notice on the guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2749)
=> Added alpha notice to READMEs for KFP Marketplace

components/gcp/bigquery/query/component.yaml, components/gcp/container/component_sdk/python/kfp_component/launcher/__main__.py, components/gcp/dataflow/launch_python/component.yaml, components/gcp/dataflow/launch_template/component.yaml, components/gcp/dataproc/create_cluster/component.yaml, components/gcp/dataproc/submit_hadoop_job/component.yaml, components/gcp/dataproc/submit_hive_job/component.yaml, components/gcp/dataproc/submit_pig_job/component.yaml, components/gcp/dataproc/submit_pyspark_job/component.yaml, components/gcp/dataproc/submit_spark_job/component.yaml, components/gcp/dataproc/submit_sparksql_job/component.yaml, components/gcp/ml_engine/batch_predict/component.yaml, components/gcp/ml_engine/deploy/component.yaml, components/gcp/ml_engine/train/component.yaml
Part of the effort to de-hardcode all output paths in the components which is problematie for portability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2697)
=> Components - De-hardcoded the UI metadata file path in GCP components

sdk/python/kfp/dsl/_pipeline_volume.py, sdk/python/tests/dsl/pipeline_volume_tests.py
Volume name must be no more than 63 characters
---
Example of faulty behavior mentioned in kubeflow-kale/kale#30:
```
This step is in Error state with this message: Pod "rwx-test2-et0i4-tkphz-2706597555" is invalid: [spec.volumes[2].name: Invalid value: "pvolume-ca6c4cec0854efe7746ed49b8661abc2a924aef77f23218ad5c43fc8258b0dfe": must be no more than 63 characters, spec.containers[0].volumeMounts[2].name: Not found: "pvolume-ca6c4cec0854efe7746ed49b8661abc2a924aef77f23218ad5c43fc8258b0dfe", spec.containers[1].volumeMounts[0].name: Not found: "pvolume-ca6c4cec0854efe7746ed49b8661abc2a924aef77f23218ad5c43fc8258b0dfe"]
```
--- …
=> SDK/DSL: Fix PipelineVolume name length

CONTRIBUTING.md, samples/README.md
Per suggestion in #2722 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2727)
=> [Doc] Fix link validation complaint.

components/gcp/bigquery/query/component.yaml, components/gcp/container/component_sdk/python/kfp_component/launcher/__main__.py, components/gcp/container/component_sdk/python/kfp_component/launcher/launcher.py, components/gcp/dataflow/launch_python/component.yaml, components/gcp/dataflow/launch_template/component.yaml, components/gcp/dataproc/create_cluster/component.yaml, components/gcp/dataproc/submit_hadoop_job/component.yaml, components/gcp/dataproc/submit_hive_job/component.yaml, components/gcp/dataproc/submit_pig_job/component.yaml, components/gcp/dataproc/submit_pyspark_job/component.yaml, components/gcp/dataproc/submit_spark_job/component.yaml, components/gcp/dataproc/submit_sparksql_job/component.yaml, components/gcp/ml_engine/batch_predict/component.yaml, components/gcp/ml_engine/deploy/component.yaml, components/gcp/ml_engine/train/component.yaml
Rollforward of #2697 
Provide a default value of mlpipeline ui metadata path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2760)
=> [Component] Rollforward of PR#2697

frontend/src/lib/Buttons.ts, frontend/src/pages/RunDetails.test.tsx
/kind bug
/area frontend
Bug behavior: error dialog and success snackbar shows together.
After fix: only error dialog shows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2766)
=> [UI] Succeed snackbar shouldn't show when there is an error

backend/src/apiserver/client/sql.go, backend/src/apiserver/client/sql_test.go, backend/src/apiserver/client_manager.go, backend/src/apiserver/common/config.go
allow flexible configuration of the client connection for mysql, by providing an extra object in the JSON configuration. For instance:
```json
{
"DBConfig": {
"DriverName": "mysql",
"DBName": "test",
"ExtraParams": { "tls": "true"}
}
}
``` 
This could replace the GroupConcatMaxLen parameter defined now as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2668)
=> support extra parameters for mysql connection

manifests/kustomize/env/gcp/gcp-configurations-patch.yaml
Fixes https://github.com/kubeflow/pipelines/issues/2719
* I wanted to patch only related entries in the JSON configmap, but this isn't currently supported by kustomize: https://github.com/kubernetes-sigs/kustomize/issues/680, we can only duplicate it.
```
$ kubectl kustomize env/gcp/ | grep workflow-controller-configmap -C 30
component: metadata-server
name: metadata-mysql-configmap
namespace: kubeflow
---
apiVersion: v1
data:
config: |
{
namespace: kubeflow,
executorImage: gcr.io/ml-pipeline/argoexec:v2.3.0-license-compliance,
artifactRepository:
{
s3: {
bucket: '', # Replace this with the same bucket as OBJECTSTORECONFIG_BUCKETNAME.
keyPrefix: artifacts,
endpoint: minio-service.kubeflow:9000,
insecure: true,
accessKeySecret: {
name: mlpipeline-minio-artifact,
key: accesskey
}, …
```
=> [Standalone] Fix GCP cloudsql manifest

frontend/src/components/Graph.test.tsx, frontend/src/components/Graph.tsx, frontend/src/components/__snapshots__/Graph.test.tsx.snap, frontend/src/pages/PipelineDetails.test.tsx, frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Fixes one of the issues (UI crashing) in https://github.com/kubeflow/pipelines/issues/2692
/area frontend
/kind bug
Steps to reproduce:
1. Upload an invalid pipeline
2. Visit pipeline detail page
Current bug behavior: UI crashes and the page turns blank.
After this PR's fix: A proper error message is shown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2774)
=> [UI] Fix UI crash when invalid pipeline uploaded

sdk/python/kfp/components/_python_op.py, sdk/python/kfp/dsl/_component.py, sdk/python/kfp/dsl/_metadata.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/kfp/dsl/types.py, sdk/python/tests/compiler/testdata/artifact_location.yaml, sdk/python/tests/compiler/testdata/basic.yaml, sdk/python/tests/compiler/testdata/imagepullsecrets.yaml, sdk/python/tests/components/test_python_op.py, sdk/python/tests/dsl/component_tests.py, sdk/python/tests/dsl/pipeline_tests.py, sdk/python/tests/dsl/type_tests.py
Problem: The SDK had were three different code paths that that parsed the python function signatures:
* `_extract_component_interface` which was used by `func_to_container_op`
* `_extract_pipeline_metadata` which was used by the DSL compiler during the compilation
* `_extract_component_metadata`  which was used by the `@component` decorator
The parsing code was pretty similar, but also had inconsistencies. This leads to problems (for example when the pipeline parameter types were parsed differently from the component input types).
This PR unifies the signature parsing code paths.
This is mostly a refactoring, so it does not introduce any changes for the SDK user (apart from fixing the inconsistency bugs).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> SDK - Unified the function signature parsing implementations

components/gcp/container/component_sdk/python/kfp_component/launcher/__main__.py, components/gcp/container/component_sdk/python/kfp_component/launcher/launcher.py
The actual root cause is simply missing default value. We do not need to pass ui-metadata-path into the actual component functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2779)
=> [Components] Roll forward of #2697 for real.

test/deploy-cluster.sh
Try the new version with newer GKE metadata server (which relates to workload identity implementation) and see if it helps.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2777)
=> Use new K8s version to improve workload identity stability

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2778)
=> [Manifest] fix metadata configmap

test/sample-test/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2786)
=> [Sample tests] Upgrade GCP sdk to 272 in sample test

frontend/src/components/SideNav.test.tsx, frontend/src/components/SideNav.tsx, frontend/src/components/__snapshots__/SideNav.test.tsx.snap, frontend/src/components/viewers/Tensorboard.test.tsx
Changes:
1. Shows cluster name
2. Provides a tooltip and a link to show the cluster in GCP UI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2789)
=> [UI] Show corresponding GKE cluster name

sdk/python/kfp/dsl/_pipeline_volume.py, sdk/python/tests/dsl/pipeline_volume_tests.py
The name no longer depends on unset parameters or the version of the Kubernetes package.
Needed for https://github.com/kubeflow/pipelines/pull/2780
Fixes  https://travis-ci.com/kubeflow/pipelines/jobs/270786161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2794)
=> SKL - DSL - Stabilized the PipelineVolume names

test/check-argo-status.sh, test/deploy-cluster.sh
Unhealthy pod description is usually too long and very distracting. e.g. https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/2786/kubeflow-pipeline-sample-test/1211813796222341120#1:build-log.txt%3A7345 the description section is too long that it's hard to find which steps passed.
But they are usually not even enough, we also need pod logs to identify the issue.
Save information related to each pod in a text file in artifacts.
Each file contains:
1. pod yaml
2. pod description
3. pod logs link
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2791)
=> [Testing] Save pod desc text and stackdriver link as artifacts

test/deploy-cluster.sh
Reduce distracting command log at end of test, so that test result is easier to read
/area testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2796)
=> [Testing] Reduce distracting command log

samples/tutorials/mnist/00_Kubeflow_Cluster_Setup.ipynb, samples/tutorials/mnist/01_Lightweight_Python_Components.ipynb, samples/tutorials/mnist/02_Local_Development_with_Docker_Image_Components.ipynb, samples/tutorials/mnist/03_Reusable_Components.ipynb, samples/tutorials/mnist/04_Reusable_and_Pre-build_Components_as_Pipeline.ipynb, samples/tutorials/mnist/OWNERS, samples/tutorials/mnist/README.md
In this tutorial, we designed a series of notebooks to demonstrate how to interact with `Kubeflow Pipelines` through [Python SDK](https://github.com/kubeflow/pipelines/tree/master/sdk/python/kfp) step by step. In particular
- [00 Kubeflow Cluster Setup](00_Kubeflow_Cluster_Setup.ipynb): this notebook helps you deploy a Kubeflow cluster through CLI. The [UI](https://www.kubeflow.org/docs/gke/deploy/deploy-ui/) method of deploying a Kubeflow cluster does not support Kubeflow v0.7 yet.
Then, notebooks 01-04 use one concrete use case, i.e., 
[MNIST classification](http://yann.lecun.com/exdb/mnist/), to demonstrate different ways of authoring a pipeline component: 
- [01 Lightweight Python Components](01_Lightweight_Python_Components.ipynb): this notebook demonstrates how to build a 
component …
=> Add step by step tutorial using mnist as use case

components/gcp/bigquery/query/component.yaml, components/gcp/dataflow/launch_python/component.yaml, components/gcp/dataflow/launch_template/component.yaml, components/gcp/dataproc/create_cluster/component.yaml, components/gcp/dataproc/submit_hadoop_job/component.yaml, components/gcp/dataproc/submit_hive_job/component.yaml, components/gcp/dataproc/submit_pig_job/component.yaml, components/gcp/dataproc/submit_pyspark_job/component.yaml, components/gcp/dataproc/submit_spark_job/component.yaml, components/gcp/dataproc/submit_sparksql_job/component.yaml, components/gcp/ml_engine/batch_predict/component.yaml, components/gcp/ml_engine/deploy/component.yaml, components/gcp/ml_engine/train/component.yaml
Fix some issues surfaced in #2795
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2803)
=> [Component] Fix the component arguments

manifests/kustomize/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2797)
=> [Manifest/Doc] Another version bumping

frontend/server/app.test.ts, frontend/server/aws-helper.ts, frontend/server/configs.ts, frontend/server/handlers/artifacts.ts, frontend/server/k8s-helper.ts, frontend/server/minio-helper.ts, frontend/server/package-lock.json, frontend/server/package.json, frontend/server/utils.ts, frontend/server/workflow-helper.ts
Error message when getting artifact:
```
Storage key is missing from artifact request
```
The bug was introduced in https://github.com/kubeflow/pipelines/pull/2745/files#diff-ac560cff381b58853d96359ba19782e9L179.
The query parameter should be "key", but it was renamed to "encodedKey".
/cc @eterna2
This PR depends on https://github.com/kubeflow/pipelines/pull/2807.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2809)
=> [UI] fix artifact handler query parameter key

backend/src/apiserver/client_manager.go, backend/src/apiserver/resource/resource_manager.go
/assign @gaoning777 
/kind bug
There are two different problems:
<details>
<summary>error log 1</summary>
<pre>
I0107 09:03:28.062672       1 interceptor.go:29] /api.ReportService/ReportWorkflow handler starting
I0107 09:03:28.103541       1 error.go:218] Failed to update run
github.com/kubeflow/pipelines/backend/src/apiserver/storage.(*RunStore).UpdateRun
backend/src/apiserver/storage/run_store.go:405
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).ReportWorkflowResource
backend/src/apiserver/resource/resource_manager.go:613
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*ReportServer).ReportWorkflow
backend/src/apiserver/server/report_server.go:39
github.com/kubeflow/pipelines/backend/api/go_client._ReportService_ReportWorkflow_Handler.func1 …
=> [Backend] Report workflow should use its namespace

sdk/python/requirements.txt, sdk/python/setup.py
Fixes https://github.com/kubeflow/pipelines/issues/2771
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2780)
=> SDK - Bumping the upper version of Kubernetes package

backend/src/apiserver/server/pipeline_upload_server.go, backend/src/apiserver/server/pipeline_upload_server_test.go, frontend/src/lib/Apis.test.ts, frontend/src/lib/Apis.ts, frontend/src/pages/NewPipelineVersion.test.tsx, frontend/src/pages/NewPipelineVersion.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/PipelineList.tsx
When we create pipeline using a local file (instead of using a url) from UI, the description specified in the text box in UI is not actually passed to backend's pipeline_upload_server; and pipeline_upload_server.go simply uses "" as description. This change lets frontend passes the description to backend and let backend uses the received description. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2783)
=> Let frontend pass pipeline description when upload a local file

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/kustomize/base/pipeline/kustomization.yaml, manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml, manifests/kustomize/base/pipeline/ml-pipeline-visualization-sa.yaml, manifests/kustomize/gcp-workload-identity-setup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2822)
=> visualization server wants kubernetes serivce account too

frontend/src/components/viewers/Tensorboard.test.tsx, frontend/src/components/viewers/Tensorboard.tsx, frontend/src/components/viewers/__snapshots__/Tensorboard.test.tsx.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2832)
=> Fix a  typo in Tensorboard.tsx. Add a default TB version.

sdk/python/kfp/dsl/_container_op.py
Hi
I've fix some example codes.
when I ran latest dsl-compile with your current example code, I got error as below
```
File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\ProgramData\Miniconda3\Scripts\dsl-compile.exe\__main__.py", line 7, in <module>
File "c:\programdata\miniconda3\lib\site-packages\kfp\compiler\main.py", line 123, in main
compile_pyfile(args.py, args.function, args.output, not args.disable_type_check)
File "c:\programdata\miniconda3\lib\site-packages\kfp\compiler\main.py", line 112, in compile_pyfile
_compile_pipeline_function(pipeline_funcs, function_name, output_path, type_check)
File …
```
=> Fix wrong example with container_op

frontend/src/lib/Apis.ts, frontend/src/pages/ArtifactDetails.tsx, frontend/src/pages/ArtifactList.tsx, frontend/src/pages/ExecutionDetails.tsx, frontend/src/pages/ExecutionList.tsx
Adapting to the recent TFX changes https://github.com/kubeflow/pipelines/issues/2562#issuecomment-572818936
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2854)
=> Frontend - Metadata - Use custom properties in addition to plain properties

backend/src/apiserver/config/sample_config.json
so that the user can open the ipynb file in JaaS notebook. Inspired by [fastai](https://docs.fast.ai/applications.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2839)
=> [Doc] Update link of preload TFX sample

manifests/gcp_marketplace/schema.yaml, manifests/kustomize/base/proxy/kustomization.yaml
enable full scope for testing version first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2871)
=> enable full scope for testing version

frontend/package.json, frontend/scripts/report-coveralls.sh
This is part of https://github.com/kubeflow/pipelines/issues/2215
Some investigation:
Ideally, I'd want to merge both coverage reports into one report in coveralls: https://docs.coveralls.io/parallel-build-webhook, but it's not well supported for now: https://github.com/nickmerwin/node-coveralls/issues/134.
Decided to not try to fix that, this simply submits two entries for each build.
/area frontend
/assign @Bobgy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2877)
=> Coverage reporting for frontend server

test/presubmit-tests-with-pipeline-deployment.sh, test/sample-test/configs/default.config.yaml
enlarge timeout to 45m to avoid flakyness
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2875)
=> enlarge timeout to 45m to avoid flakyness

CHANGELOG.md
changelog for 0.2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2881)
=> changelog for 0.2.0

manifests/kustomize/base/kustomization.yaml
It looks like `metadata-writer`'s image reference is missing from `kustomization.yaml`, so the generated manifests point to `gcr.io/ml-pipeline/metadata-writer:0.1.40` as that deployment's image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2882)
=> Manifests/Kustomize: Add metadata-writer to images

.gitignore, samples/contrib/azure-samples/databricks-pipelines/README.md, samples/contrib/azure-samples/databricks-pipelines/databricks_cluster_pipeline.py, samples/contrib/azure-samples/databricks-pipelines/databricks_job_pipeline.py, samples/contrib/azure-samples/databricks-pipelines/databricks_notebook_pipeline.py, samples/contrib/azure-samples/databricks-pipelines/databricks_run_pipeline.py, samples/contrib/azure-samples/databricks-pipelines/databricks_secretscope_pipeline.py, samples/contrib/azure-samples/databricks-pipelines/databricks_workspaceitem_pipeline.py, samples/contrib/azure-samples/databricks-pipelines/notebooks/ScalaExampleNotebook, samples/contrib/azure-samples/kfp-azure-databricks/README.md, samples/contrib/azure-samples/kfp-azure-databricks/databricks/__init__.py, samples/contrib/azure-samples/kfp-azure-databricks/databricks/_cluster_op.py, samples/contrib/azure-samples/kfp-azure-databricks/databricks/_dbfsblocks_op.py, samples/contrib/azure-samples/kfp-azure-databricks/databricks/_job_op.py, samples/contrib/azure-samples/kfp-azure-databricks/databricks/_run_op.py, samples/contrib/azure-samples/kfp-azure-databricks/databricks/_secretscope_op.py, samples/contrib/azure-samples/kfp-azure-databricks/databricks/_workspaceitem_op.py, samples/contrib/azure-samples/kfp-azure-databricks/setup.py, samples/contrib/azure-samples/kfp-azure-databricks/tests/dbfsblock_spec.json, samples/contrib/azure-samples/kfp-azure-databricks/tests/run_tests.sh, samples/contrib/azure-samples/kfp-azure-databricks/tests/secretscope_spec.json, samples/contrib/azure-samples/kfp-azure-databricks/tests/test_cluster_op.py, samples/contrib/azure-samples/kfp-azure-databricks/tests/test_dbfsblock_op.py, samples/contrib/azure-samples/kfp-azure-databricks/tests/test_job_op.py, samples/contrib/azure-samples/kfp-azure-databricks/tests/test_run_op.py, samples/contrib/azure-samples/kfp-azure-databricks/tests/test_secretscope_op.py, samples/contrib/azure-samples/kfp-azure-databricks/tests/test_workspaceitem_op.py, samples/contrib/azure-samples/kfp-azure-databricks/tests/workspaceitem_spec.json
Adds new Ops to Azure Databricks for Kubeflow Pipelines:
* CreateSecretScopeOp, to create a secret scope in Databricks.
* DeleteSecretScopeOp, to delete a secret scope created with CreateSecretScopeOp.
* ImportWorkspaceItemOp, to import an item into a Databricks Workspace.
* DeleteWorkspaceItemOp, to delete an item imported with ImportWorkspaceItemOp.
* CreateDbfsBlockOp, to create Dbfs block in Databricks.
* DeleteDbfsBlockOp, to delete Dbfs block created with CreateDbfsBlockOp.
Adds new pipeline samples to show the usage of these new Ops.
Fixes some typos in existing Ops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2817)
=> Add new Ops to Azure Databricks for KFP: secretscope, workspaceitem & dbfsblock

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2891)
=> Have custom visualization on by default

frontend/mock-backend/fixed-data.ts, frontend/src/components/CustomTableNameColumn.tsx, frontend/src/components/Graph.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/PipelineList.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Demo: https://drive.google.com/file/d/1i_0mvv2u5nM1E9wSzER4DfYjy_dnhU4C/view
Address long existing problem: "names are too long to read in lists".
/area frontend
/kind feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2894)
=> [UI] Add tooltips to table name columns so they can be read fully

sdk/python/kfp/_auth.py
/cc @IronPan 
There was a recent report that kfp client doesn't work in cloud functions. After long troubleshooting from multiple engineers. We found os.popen is hiding underneath error that gcloud doesn't exist in cloud functions.
This PR addresses the silent error issue first.
`os.popen` is already deprecated in doc: https://docs.python.org/2/library/os.html#os.popen because it silently hides internal errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2896)
=> [SDK] kfp client should not silently fail using gcloud

frontend/start-proxies.ps1
This PR adds a cross-platform PowerShell script that can deploy proxies for Mac / Linux / Windows environments.
Image |
--- |
_**Note:** I don't have a properly deployed cluster currently, but it's identical to the Linux counterpart found [here](https://github.com/kubeflow/pipelines/blob/master/frontend/start-proxy-standalone-and-server.sh)_
/area pipelines
/priority p1
/assign @avdaredevil
/cc @kwasi @Bobgy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2835)
=> [Windows] PowerShell script added to start proxies for front-end UI

backend/Dockerfile, test/sample-test/Dockerfile
Apache beam 2.18 introduced breaking change for multi-threading, which is incompatible with TFX 0.15.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2909)
=> [Fix] Temporarily pin beam version to 2.17

test/deploy-cluster.sh
1.14.8-gke.17 is no longer supported while 1.14.10-gke.17 and 1.14.9-gke.23 have broken Workflow Identity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2912)
=> Tests - Fixed presubmit tests

sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_dsl_bridge.py, sdk/python/kfp/components/_python_to_graph_component.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/tests/components/test_components.py, sdk/python/tests/components/test_graph_components.py, sdk/python/tests/components/test_python_op.py
This change is a pure refactoring of the implementation of component task creation.
For pipelines compiled using the DSL compiler (the compile() function or the command-line program) nothing should change.
The main goal of the refactoring is to change the way the component instantiation can be customized.
Previously, the flow was like this:
`ComponentSpec` + arguments --> `TaskSpec` --resolving+transform--> `ContainerOp`
This PR changes it to more direct path:
`ComponentSpec` + arguments --constructor--> `ContainerOp`
or
`ComponentSpec` + arguments --constructor--> `TaskSpec`
or
`ComponentSpec` + arguments --constructor--> `SomeCustomTask`
The original approach where the flow always passes through `TaskSpec` had some issues since TaskSpec only accepts string arguments (and two
other …
=> SDK - Components refactoring

sdk/python/kfp/components/_python_op.py
Added the `create_component_from_func` function as alias for `func_to_container_op`.
It behaves exactly the same, but the name now does not imply that you'll always get `ContainerOp` from it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2911)
=> SDK - Components -  Added the create_component_from_func alias

backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go, backend/src/apiserver/server/run_server_test.go, backend/src/common/util/consts.go, backend/src/common/util/workflow.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2902)
=> Backend - Annotate Workflow with the run name

.cloudbuild.yaml, backend/src/apiserver/server/pipeline_upload_server.go, backend/src/apiserver/server/pipeline_upload_server_test.go
Make created_at value of default_version in UploadPiplineResponse follow RFC3339 time format.
It returned `created_at` value as a json dictionary, for example
`"created_at":{"seconds":1576824474}`, and broke SDK parser.  `jsonpb`
will be used to take care of all json marshaling including time format
conversion.
See https://github.com/kubeflow/pipelines/issues/2764 for the detail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2876)
=> Make created_at value follows RFC3339 time format.

manifests/gcp_marketplace/deployer/Dockerfile, manifests/gcp_marketplace/deployer/init_action.sh
in order to automatically create a bucket.
It also populate a configmap named 'gcp-default-config' for later use.
~~Pending manual tests.~~
Verified auto bucket creation and configmap creation is working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2932)
=> [MKP] Add initializaion action for MKP deployer

sdk/python/kfp/cli/diagnose_me/kubernetes_cluster.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2941)
=> Adding support for getting all configmaps

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/components/_component_store.py, sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_dsl_bridge.py, sdk/python/kfp/components/_python_op.py, sdk/python/kfp/components/structures/__init__.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/kfp/dsl/_metadata.py, sdk/python/tests/components/test_components.py, sdk/python/tests/components/test_graph_components.py, sdk/python/tests/components/test_python_op.py, sdk/python/tests/dsl/component_tests.py, sdk/python/tests/dsl/metadata_tests.py, sdk/python/tests/dsl/pipeline_tests.py
Make the classes like `ComponentSpec` accessible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2860)
=> SDK - Components - Made it easier to access component spec classes

frontend/server/app.test.ts, frontend/server/configs.ts, frontend/server/handlers/index-html.ts, frontend/src/atoms/ExternalLink.tsx, frontend/src/components/Router.tsx, frontend/src/components/SideNav.tsx, frontend/src/components/__snapshots__/Description.test.tsx.snap, frontend/src/components/__snapshots__/Router.test.tsx.snap, frontend/src/lib/Flags.ts, frontend/src/pages/GettingStarted.tsx, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
UPDATE: also implemented layout similar to designed documentation
UPDATE2: adjusted page title
Content of this page is purely rendered from markdown here: https://github.com/kubeflow/pipelines/pull/2935/files#diff-1e8357336f0f74b158fbf0751ac2d9daR31. So it's super easy for anyone to update later.
demo when feature flag turned on: https://drive.google.com/file/d/12dyaTLQY3AvwG38YC3TmBhCGOYqSUmGg/view
Changes:
1. Add a separate getting started page for tfx usage (~~exact content of this page is merely a copy from https://github.com/kubeflow/pipelines/pull/2928~~ implemented requested layout, please adjust content with markdown based on further discussion).
2. Add a feature flag for pipelines in gcp marketplace. (ml-pipeline-ui deployment with env variable DEPLOYMENT=MARKETPLACE will turn on …
=> [UI] Getting started page for hosted pipelines

frontend/src/components/Banner.tsx, frontend/src/components/__snapshots__/Banner.test.tsx.snap, frontend/src/pages/RunDetails.tsx
Adding a UI link to FAQ / Trouble shooting guide when pipelines fail. This is WIP posting for early feedback.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2930)
=> [UI] Adding Troubleshooting guide link to Error / Warning Banner

frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
to better reflect the actual content. Pipeline source should be its DSL def in Python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2951)
=> [Frontend] Change Tab name from source to YAML

backend/Dockerfile, samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py, samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb, test/sample-test/Dockerfile
And modernize of usage of TFX API.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2949)
=> Bump TFX dependency to 0.21.0rc0

frontend/src/pages/GettingStarted.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2955)
=> [UI] Updating starting page UI links

backend/Dockerfile.visualization, backend/src/apiserver/visualization/requirements.txt, backend/src/apiserver/visualization/third_party_licenses.csv, components/third_party_licenses.csv
As asked by @Realsen
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2946)
=> Visualizations - Updated the TFMA and TFDV versions

backend/src/apiserver/visualization/third_party_licenses.csv, components/third_party_licenses.csv
Currently cloud build is failing at:
```
The following packages are not found for licenses tracking.
Please add an entry in /ml/third_party_licenses.csv for each of them.
typing-extensions
The command '/bin/sh -c mkdir /usr/licenses &&     /ml/license.sh /ml/third_party_licenses.csv /usr/licenses' returned a non-zero code: 1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2972)
=> Fix third party license

frontend/src/pages/AllRunsList.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
Internal bug thread b/135048320, reporting the metric columns of some runs are  missing when displayed in RunList. This is not actually a bug but because the runs of the list are not required to have the same set of metrics and we currently show metric columns based on the first run in the list.
Reasoning: 
1. Given the fact that the main intention of displaying metric columns in a run list is for comparing these metrics across runs, we can conclude that the metric columns in run list make sense if the runs under comparison have the same set of metrics. On the other hand, in AllRun list, the runs are from *all* runs of *unrelated* pipelines in the system, and their metric sets have no inherent connection or comparison need. Therefore, in the AllRun list, we disable metric columns display. …
=> Clean up metric columns

sdk/python/kfp/_auth.py
Fixes #2985
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2986)
=> [SDK] Fix CLI authentication

samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/README.md, samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/cloudbuild.yaml, samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/component.yaml, samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/curl.bash, samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/helloworld/Dockerfile, samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/helloworld/helloworld.py, samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/pipeline.py
#1 piece for CI samples: 
<To make the repo more easily reviewable, pr 2784(https://github.com/kubeflow/pipelines/pull/2784) will be broken into smaller prs>
This sample is the simplest helloworld sample for versioned pipeline CI. 
- Use cloudbuild for CI process
- Use curl(REST API) to interact with kfp server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2833)
=> [Sample] CI Sample: helloworld

backend/src/apiserver/main.go
* The default ServerOption [MaxRecvMsgSize](https://godoc.org/google.golang.org/grpc#MaxRecvMsgSize) is 4MB, and we might hit this limit when loading a large number of runs. Increase the limit to 2GB (MaxInt32).
* Minor fix: golang import ordering/grouping
@jingzhang36 @IronPan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3004)
=> Fix issue with "grpc: received message larger than max ..."

test/deploy-pipeline-lite.sh, test/install-argo.sh, test/scripts/retry.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3008)
=> [Testing] Reduce flakiness caused by iam bindings

backend/src/apiserver/client/minio.go
Background
---
As of current, supplying a minioServiceHost of `s3.amazonaws.com` with
any port incurs an error.
Per the results of:
```GO
testBucket := func(hostPort string) error {
client, _ := minio.New(hostPort, accessKey, secretKey, false)
_, err := client.BucketExists(bucket)
return err
}
for _, endpoint := range []string{
"s3.amazonaws.com:443",
"s3.amazonaws.com:80",
"s3.amazonaws.com:",
"s3.amazonaws.com",
} {
fmt.Printf("Endpoint: %s, Error: %v\n", endpoint, testBucket(endpoint))
}
```
```
Endpoint: s3.amazonaws.com:443, Error: Get http://s3.amazonaws.com:443/kflow-test/?location=: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x00\x00\x00\x02\x01\x00"
Endpoint: s3.amazonaws.com:80, Error: Head http://s3.amazonaws.com/kflow-test/: 301 response …
```
=> Allow blank port for minio client to work with S3

test/presubmit-tests-with-pipeline-deployment.sh
After switching to 1.14.8-gke.33 in https://github.com/kubeflow/pipelines/pull/2912/files. Tests have been super flaky. It's affecting daily development a lot. Each test takes forever to retry tests.
But I think we don't need to test too much about workload identity now. Also, test coverage of KFP code is not in anyway different between workload identity and full scope cluster (because both are transparent layer to handle authentication to GCP).
Therefore, I think it would be the best if we switch presubmit tests to full scope. When there's a stable GKE version with workload identity support, we can switch back to workload identity or add workload identity as postsubmit test.
Let's retry a few times to verify if full scope cluster will indeed solve flakiness problem.
---
This change …
=> [Testing] Use full scope cluster for testing to reduce flakiness

frontend/src/components/SideNav.tsx, frontend/src/lib/Flags.ts
/cc @rui5i 
Thanks for finding out the problem.
After the fix:
Before the fix:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3015)
=> [UI] Fix side nav text alignment after adding start page

sdk/python/kfp/components/_python_to_graph_component.py
The return behavior is now consistent with `create_component_from_func`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2971)
=> SDK - Components - create_graph_component_from_pipeline_func now returns a function

components/diagnostics/diagnose_me/component.py, components/diagnostics/diagnose_me/component.yaml
Updating the API update links to point to cloud.console 
also changing the service account message to remove confusing around possible action items when users see : 
```
To set the active account, run:
$ gcloud config set account `ACCOUNT`
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3044)
=> updating links and service account message

frontend/src/lib/OutputArtifactLoader.ts
This completes the work to visualize TFDV artifacts - TFMA artifacts still need to be investigated further.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3026)
=> Add visualizations for Schema and ExampleAnomalies

tools/diagnose/OWNERS, tools/diagnose/kfp.sh
- It's to be launched from Cloud Shell or any CLI.
- It may still reuse existing diagnose tool inside KFP SDK, so bash will install KFP
- Or it may directly run gcloud and kubectl to do checking or all a golang/python script if bash is hard to handle complex logics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3028)
=> place holder for diagnose entry

frontend/src/lib/OutputArtifactLoader.ts, frontend/src/pages/ExecutionList.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
TFX visualization usually takes a long time, I implemented a circular progress to reduce the pain of not knowing how long to wait for it.
Demo: https://www.youtube.com/watch?v=avbPeIT7KyI
* Refactor RunDetails to extract artifact side panel tab as an individual component
* Let loading function report progress
* Add the circular progress with animation
In addition to the main purpose, this also fixed some leaking async behavior.
Fixes https://github.com/kubeflow/pipelines/issues/3020
/area frontend
/kind feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3043)
=> [UI] Circular progress for TFX visualization

backend/src/apiserver/filter/filter.go, backend/src/apiserver/filter/filter_test.go, backend/src/apiserver/list/list.go, backend/src/apiserver/storage/pipeline_store.go, backend/src/apiserver/storage/pipeline_store_test.go
This PR fixes issue #2945 by adding filter to the `ListPipelines` API. 
Because `ListPipelines` joins table `pipelines` and `pipeline_versions`, and they both have a column `name`, we need to fully qualify the column in `NewWithKeyMap` to avoid "ambiguous column name" error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3040)
=> Implement filtering in ListPipelines

backend/src/apiserver/resource/resource_manager.go
We set them optional already for one-time run (https://github.com/kubeflow/pipelines/pull/1289). We should also set them for recurring run.
Manual test on kfp deployment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3041)
=> Set auto-added artifacts optional in recurring run (job)

manifests/kustomize/OWNERS, samples/OWNERS, test/OWNERS
PR is moved from https://github.com/kubeflow/pipelines/pull/2893/files
That PR has CLA issue while after I follow the guide, it still can't be fixed. So copy out a new PR and submit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3027)
=> add myself to manifest/sample/test owner

backend/src/apiserver/config/sample_config.json, samples/core/parameterized_tfx_oss/README.md, samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb, samples/core/xgboost_training_cm/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3066)
=> [Doc] Make it explicit that hosted beta does not require GCP SA

components/diagnostics/diagnose_me/component.py, components/diagnostics/diagnose_me/component.yaml
This change adds quota check to diagnose me component.
An optional input of a list of quota entries is expected. Then, the component compare what's available with this input to see if there is any shortage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3062)
=> [Component] Add quota check in diagnose me component.

frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Fixes https://github.com/kubeflow/pipelines/issues/3080
Changes: this fixes the bug by only refetching data when selected node phase changes to completed.
/area frontend
/kind bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3082)
=> [UI] Visualization only loads on completed nodes

backend/src/apiserver/config/sample_config.json, samples/tutorials/DSL - Control structures/DSL - Control structures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3076)
=> Samples - Add explanation about pipeline failing intentionally

backend/api/generate_api.sh
We should allow executing the script from git repo's root directory, as implied in this [README](https://github.com/kubeflow/pipelines/tree/master/backend#building-go-client-library-and-swagger-files).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3090)
=> Fix api generation script

sdk/python/kfp/gcp.py, sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
It was generating broken Kubernetes structures that made the workflow fail at submission time.
Fixes https://github.com/kubeflow/pipelines/issues/2847
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3091)
=> SDK - Fixed the broken kfp.gcp.use_preemptible_nodepool extension

backend/src/apiserver/visualization/requirements.txt, backend/src/apiserver/visualization/types/tfdv.py, frontend/src/lib/OutputArtifactLoader.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3089)
=> enable tfdv, remove hardcode as a sample for following PRs

samples/core/xgboost_training_cm/xgboost_training_cm.py, test/sample-test/configs/xgboost_training_cm.config.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3093)
=> XGBoost demo - change quota calculation 

components/gcp/ml_engine/batch_predict/README.md, components/gcp/ml_engine/deploy/README.md
The output sections of the deploy and batch_prediction component's READMEs are
incorrect. Updated to reflect the actual outputs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3103)
=> ml_engine component READMEs incorrect

sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_data_passing.py, sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
Refactored `_data_passing.py` interface to expose functions instead of dictionaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3107)
=> SDK - Components - Fixed dict-style type annotations

sdk/python/kfp/compiler/compiler.py
Argo CLI tool must be in path for this feature to work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3094)
=> SDK - Compiler - Add optional Argo validation

frontend/src/lib/OutputArtifactLoader.ts
We add TFMA auto-visualization for TFX components in KFP. 
Note: Widgets in TFMA visualization depend on tfma_widget_js file, which unfortunately doesn't work outside Notebook (as of now). So this PR depends on the work of @Bobgy https://cdn.jsdelivr.net/gh/Bobgy/model-analysis@kfp/tensorflow_model_analysis/notebook/jupyter/js/dist/, which provides a bundle of js files that can support TFMA widgets to work in KFP context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3111)
=> TFMA auto-visualization for TFX components in KFP

backend/src/apiserver/config/sample_config.json, frontend/src/pages/GettingStarted.tsx, frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml, manifests/gcp_marketplace/guide.md, manifests/gcp_marketplace/schema.yaml, manifests/kustomize/README.md, manifests/kustomize/base/kustomization.yaml, manifests/kustomize/base/pipeline-application.yaml, sdk/python/kfp/__init__.py
bump version to 0.2.4 and tiny BTW doc fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3115)
=> bump version to 0.2.4 and tiny BTW doc fix

backend/src/apiserver/visualization/exporter.py, backend/src/apiserver/visualization/templates/full.tpl, frontend/server/app.ts, test/cloudbuild/visualization.yaml
Mitigates https://github.com/kubeflow/pipelines/issues/3114#issuecomment-588071746
/cc @ajchili 
/area visualization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3116)
=> [Visualization] Clean up full.tpl to improve vis loading time

.travis.yml, backend/Dockerfile, test/sample-test/Dockerfile
There is a breakage at TFX head.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3135)
=> [Test] Temporarily bypass TFX unittest

backend/src/apiserver/model/job.go, backend/src/apiserver/resource/model_converter.go, backend/src/apiserver/resource/model_converter_test.go, backend/src/apiserver/server/api_converter.go, backend/src/apiserver/server/api_converter_test.go, backend/src/apiserver/storage/job_store.go, backend/src/apiserver/storage/job_store_test.go, backend/src/common/util/scheduled_workflow.go, test/cloudbuild/scheduledworkflow.yaml
Part of https://github.com/kubeflow/pipelines/issues/3055
Recommend hiding whitespace difference when reviewing, because there seems to be some format inconsistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3129)
=> [DB] Add NoCatchup field to Job db model

frontend/README.md, frontend/src/apis/job/api.ts, frontend/src/atoms/HelpButton.tsx, frontend/src/components/Trigger.test.tsx, frontend/src/components/Trigger.tsx, frontend/src/components/__snapshots__/Trigger.test.tsx.snap, frontend/src/lib/Apis.ts, frontend/src/lib/RunUtils.ts, frontend/src/pages/GettingStarted.test.tsx, frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/RecurringRunDetails.test.tsx, frontend/src/pages/RecurringRunDetails.tsx, frontend/src/pages/__snapshots__/RecurringRunDetails.test.tsx.snap
Demo: https://youtu.be/33ZoXJHq3jA
/area frontend
Part of https://github.com/kubeflow/pipelines/issues/3055
The feature works e2e:
All the four recurring runs have past start date and end date of from 10:00am to 10:02am and interval of 1 minute. Those with catchup = false has only one run, those with catchup = true has two runs.
Recurring run details page also shows catchup field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3131)
=> [UI] Scheduled workflow catchup=false option

backend/test/integration/README.md, backend/test/integration/experiment_api_test.go, backend/test/integration/flags.go, backend/test/integration/job_api_test.go, backend/test/integration/pipeline_api_test.go, backend/test/integration/run_api_test.go, backend/test/integration/run_tests_locally.sh, backend/test/integration/visualization_api_test.go
Add README and script to help run backend integration tests locally.
Also moved cleanup steps to test setup stage, so that
* each test doesn't depend on cluster initial state, e.g. if you halt your test in the middle, rerunning the test would fail because of the cluster being in an intermediate state. With this change, test will just pass.
* dev can debug manually after a test fails
UPDATE: tests will clean up both before and after it runs, to unblock frontend-integration-test which depends on the cluster being empty, but clean up after test is disabled in dev mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3138)
=> [Backend] Refactor integration tests, facilitate local testing

frontend/src/pages/RunDetails.tsx
Parallelizing async API calls using Promise.all instead of using two awaits.
There are no issues related to this. It is a minor performance related improvement and makes the code consistent across the repository for fetching `clusterName` and `projectId` - For example, the same format is followed [here](https://github.com/kubeflow/pipelines/blob/b90040a00fe53129f699a5d8c1ec0dcace02d041/frontend/src/components/SideNav.tsx#L232) in `/frontend/src/components/SideNav.tsx`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3140)
=> [frontend]: Use Promise.all to fetch clusterName and projectId

frontend/README.md
/area frontend
/area docs
/assign @Bobgy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3153)
=> [UI] Update frontend/README.md

samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/README.md, samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/cloudbuild.yaml, samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/create_pipeline_version_and_run.py, samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/pipeline.py, samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/tensorboard/Dockerfile, samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/tensorboard/component.yaml, samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/tensorboard/tensorboard.py, samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/train/Dockerfile, samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/train/component.yaml, samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/train/mnist.py
#2 piece for CI samples:
<To make the repo more easily reviewable, pr 2784(#2784) will be broken into smaller prs>
This sample is the mnist sample for versioned pipeline CI. Data scientists can make the least effort to migrate their original code to implement KFP CI by wrapping the whole training code in one step and other adds-on like visualizations in other steps.
- Use cloudbuild for CI process
- Use KFP SDK to connect to KFP API server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3013)
=> [Sample] CI Sample: mnist

sdk/python/kfp/_client.py
This PR includes code to add the functionality to schedule a pipeline from the python sdk. The added code is written to be similar to the implementation of how to run a pipeline in order to keep the API togheter. 
I believe this is a feature that would be great to have in Kubeflow and also allow people to use it for CI/CD/MLops where the pipelines are run on schedule. 
I am new to swagger and how the API works so please feel free to point out all possible improvements!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2981)
=> Updated with scheduling capability for kfp.Client

frontend/src/pages/GettingStarted.tsx, frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Add a message to remind users to choose a Tensorflow 2.1 notebook instance.
/assign @IreneGi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3152)
=> Add a message in 'Get Started Page'

sdk/python/kfp/components/_dynamic.py
Fixes the follwoing error: "TypeError: code() takes at least 14 arguments (13 given)".
The cause of the issue is a breaking change in CodeType constructor in Python 3.8.
https://bugs.python.org/issue37221
This should have been fixed by https://github.com/python/cpython/pull/13959 and https://github.com/python/cpython/pull/14505, but the code still fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3126)
=> SDK - Fix SDK on Python 3.8

frontend/src/components/Router.tsx, frontend/src/components/__snapshots__/Router.test.tsx.snap, frontend/src/pages/ArtifactDetails.tsx
This is the long term solution mentioned in https://github.com/kubeflow/pipelines/pull/3137.
demo: https://youtu.be/1zK8I6UzQXc
/assign @kwasi 
/area frontend
/priority p0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3141)
=>  [MLMD][Lineage] Navigate to ArtifactDetails Overview on row click [long term]

frontend/README.md, frontend/package.json, frontend/src/TestUtils.tsx, frontend/src/components/SideNav.test.tsx, frontend/src/components/__snapshots__/SideNav.test.tsx.snap, frontend/src/components/viewers/Tensorboard.test.tsx, frontend/src/components/viewers/__snapshots__/Tensorboard.test.tsx.snap, frontend/src/pages/GettingStarted.test.tsx, frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Changes:
1. Use inline snapshots
2. Configure snapshot-diff to remove line number
3. Configure snapshot-diff to remove escaped characters
4. Common test utils for diffing HTML and shallow
Best practices:
1. Only use inline snapshots (this makes snapshots easier to read when reading tests, also it's clear when a snapshot is too long)
2. Avoid long snapshots, use snapshot diff or non-snapshot testing instead
This PR is aligned with https://kentcdodds.com/blog/effective-snapshot-testing/
/area frontend
/area engprod
Part of #2407 
Unblocks https://github.com/kubeflow/pipelines/issues/2652
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3166)
=> [Frontend] snapshot diff setup

frontend/.eslintrc.yaml, frontend/package-lock.json, frontend/package.json, frontend/src/apis/run/api.ts, frontend/src/atoms/ExternalLink.tsx, frontend/src/components/CompareTable.test.tsx, frontend/src/components/CustomTableRow.test.tsx, frontend/src/components/DetailsTable.test.tsx, frontend/src/components/viewers/ConfusionMatrix.test.tsx, frontend/src/components/viewers/PagedTable.test.tsx, frontend/src/lib/CompareUtils.test.ts, frontend/src/lib/OutputArtifactLoader.test.ts, frontend/src/lib/StaticGraphParser.test.ts, frontend/src/pages/AllRunsList.tsx, frontend/src/pages/Compare.test.tsx, frontend/src/pages/ExperimentDetails.test.tsx, frontend/src/pages/ExperimentDetails.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/GettingStarted.tsx, frontend/src/pages/NewPipelineVersion.tsx, frontend/src/pages/PipelineDetails.test.tsx, frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/RunList.test.tsx, frontend/tsconfig.json
/area frontend
/assign @Bobgy
Part of https://github.com/kubeflow/pipelines/issues/2407
UPDATE: I cannot fix the test configs, it seems this is also blocked by https://github.com/kubeflow/pipelines/issues/2432, because create-react-app-ts has restriction on which jest and ts-jest version to use.
UPDATE2: After #2432 fixed, also upgraded typescript, this works now.
Optional chaining example usage: https://github.com/kubeflow/pipelines/pull/3154/files#diff-1e8357336f0f74b158fbf0751ac2d9da
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3154)
=> [Frontend] Update deps to bring optional chaining js language feature

backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go, backend/src/apiserver/resource/resource_manager_util.go, backend/src/apiserver/server/run_server.go, backend/src/apiserver/server/run_server_test.go, backend/src/apiserver/server/util.go, backend/src/common/util/workflow.go
Previous patching does not work for the following codepath:
In SDK use placeholder in parameter default value → In SDK create_run_from_pipeline_func/package → Run triggered and failed 
Change to patch RunDetail and WorkflowSpec in resource manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3145)
=> [Backend] Fix parameter patching

samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
In TFX 0.21.0 release it's not guaranteed to work well with 6 vCPU. Disable it for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3170)
=> [Sample] Disable multi-threading for TFX demo notebook

backend/src/apiserver/server/pipeline_upload_server.go
Our api client assumes the enum being string e.g. https://github.com/kubeflow/pipelines/blob/master/backend/api/go_http_client/pipeline_upload_model/api_resource_type.go
So when we populate the response, we need to treat enum as string instead of int, in order for our api client to parse it correctly.
Needed to unblock another PR at https://github.com/kubeflow/pipelines/pull/3174
Tested on my own KFP instance with latest image at https://pantheon.corp.google.com/kubernetes/deployment/us-central1-a/kubeflow-pipelines-standalone/kubeflow/ml-pipeline?project=jingzhangjz-project&organizationId=433637338589&tab=overview&deployment_overview_active_revisions_tablesize=50&duration=PT1H&pod_summary_list_tablesize=20&service_list_datatablesize=20
--- …
=> Upload pipeline version return a response with enum as string

backend/src/apiserver/storage/db_status_store.go, backend/src/apiserver/storage/default_experiment_store.go
Reusing tx before closing rows (might) result in the following error:
[mysql] 2020/02/17 11:55:38 packets.go:427: busy buffer
This closes #3098
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3099)
=> apiserver: Close rows before reusing tx

frontend/src/Css.tsx, frontend/src/components/Toolbar.tsx, frontend/src/pages/GettingStarted.tsx, frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
start page updates according latest feedback
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3175)
=> start page updates according latest feedback

frontend/package-lock.json, frontend/package.json
/area frontend
/priority p0
/cc @Bobgy 
This is the Pipelines half of https://github.com/kubeflow/frontend/pull/45.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3176)
=> Bump to latest kubeflow/frontend hash with many-to-many execution fix

frontend/src/lib/OutputArtifactLoader.test.ts, frontend/src/lib/OutputArtifactLoader.ts
/area frontend
/kind feature
Resolves https://github.com/kubeflow/pipelines/issues/3133
Related to #3162 
Metadata format is consistent with existing inline markdown:
```
metadata = {
'outputs': [{
'storage': 'inline',
'source': '# Inline Markdown\n[A link](https://www.kubeflow.org/)',
'type': 'markdown',
}, {
'storage': 'inline',
'source': '<body>Hello, World!</body>',
'type': 'web-app',
}]
}
```
Tried with the following pipeline.
```
import kfp
import kfp.components as comp
from typing import NamedTuple
#Define a Python function
def hello_world(name) -> NamedTuple('HelloWorldOutput', [(
'echo', 'string'), ('mlpipeline_ui_metadata', 'UI_metadata')]):
import json
hello_world = """
<html>
<body>
Hello_World
</body>
</html>
"""
metadata = {
'outputs': [{
'storage': 'inline',
'source': '# …
```
=> [UI] Supports storage: "inline" for all types of visualizations

sdk/python/kfp/_client.py
There is a bug in the code the the kfp.client scheduling. Currently the schedule is hard coded which where noticed by Yaron Haviv. I have also update the hard coded job name and description to be set by the user. 
This was legacy from the development phase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3173)
=> Update to fix bug in kip.client for scheduling

backend/src/apiserver/client_manager.go, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Not using TLS is a security concern, especially if using cloud storage
like S3. This should be set to secure to avoid people unknowingly not
using TLS.
To make the bundled minio still work, I've submitted
https://github.com/kubeflow/manifests/pull/950 to set secure=false in
this case explicitly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3168)
=> minio: Set secure=true to enable TLS by default

frontend/Dockerfile
Previously we pin the link due to the existence of the TFX demo notebook, which located in KFP's repo. 
However, it's actually redundant and problematic now b/c we no longer use that anymore, and it mistakenly replace the link for the TFX template notebook, causing 404 when CAIP notebook attempting to load it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3183)
=> [Frontend] Unpin notebook permalink when release

frontend/src/pages/ExecutionList.tsx
/area frontend
The execution name field was not populated by tfx, so I didn't show it in previous implementation.
Fixes https://github.com/kubeflow/pipelines/issues/3109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3196)
=> [UI] Get execution name from name field

frontend/server/handlers/artifacts.ts, frontend/server/server.ts, frontend/server/utils.ts
/area frontend
/area engprod
/kind misc
This helped me debug https://github.com/kubeflow/manifests/pull/970.
/assign @Bobgy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3197)
=> [UI] Better logging in UI server

backend/Dockerfile, test/sample-test/Dockerfile
Currently TFX team are during their releasing process, causing a dependency discrepancy. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3209)
=> Pin TFT to 0.21.0

samples/tutorials/mnist/00_Kubeflow_Cluster_Setup.ipynb, samples/tutorials/mnist/01_Lightweight_Python_Components.ipynb
- The way of sending metadata output was not updated in https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/mnist/01_Lightweight_Python_Components.ipynb
- Also add an instruction to avoid running "gcloud auth application-default login" on AI Platform notebooks in  https://github.com/kubeflow/pipelines/blob/master/samples/tutorials/mnist/00_Kubeflow_Cluster_Setup.ipynb
Fixes #3182
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3186)
=> [Tutorial] - Fixed lightweight component tutorial with bad metadata usage

frontend/src/components/Trigger.tsx, frontend/src/components/__snapshots__/Trigger.test.tsx.snap, sdk/python/kfp/_client.py
Fixes https://github.com/kubeflow/pipelines/issues/3055
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3201)
=> [SDK] New fields for schedule pipeline

frontend/mock-backend/mock-api-middleware.ts, frontend/server/app.test.ts, frontend/server/handlers/gke-metadata.ts
/area frontend
/kind bug
This also fixes the issue mentioned in https://github.com/kubeflow/kubeflow/issues/4829.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3218)
=> [Frontend] GKE metadata endpoint should fail when fetched response is not ok

backend/src/apiserver/client_manager.go, backend/src/apiserver/config/config.json
With reference to PR #2080 :
param to customize the pipeline path to save the pipeline templates (`PipelineFolder`) was supposed to be renamed to `PipelinePath`. However, the `config.json` as well as the config field was not renamed. 
This PR fix this oversight - i.e. rename the config field to `PipelinePath`, and updates the `config.json`.
cc: @Jeffwan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3056)
=> Fix config fieldname `PipelineFolder` to `PipelinePath`

sdk/python/kfp/dsl/_ops_group.py, sdk/python/tests/dsl/ops_group_tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3212)
=> add an optional name for dsl.Condition (kubeflow#3210)

backend/src/apiserver/client_manager.go, backend/src/apiserver/model/experiment.go, backend/src/apiserver/storage/experiment_store.go, backend/src/apiserver/storage/experiment_store_test.go
Experiment data model changes:
* Add `Namespace` column to `experiments` table.
* Change experiment `Name` from globally unique to unique within a namespace.
* Fix a bug where errors weren't propagated from ExperimentStore scanRows method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3184)
=> [Backend][Multi-user] Add 'Namespace' to Experiment data model

WORKSPACE, backend/src/common/util/BUILD.bazel, backend/src/common/util/formatter_test.go, go.mod, go.sum
We use kataras_iris only for its /core/errors package; and this error package is only used in our tests; and moreover, /core/errors is removed from kataras_iris in v12 and gets moved to /core/errgroup. I figured that, instead of updating the usage in our tests, we can just stop depending on it in our tests but switch to standard errors (and especially that this switch wouldn't change our production code)
Also, this dependency causes backend prow test failure when we try to migrate, due to not found the package error.  Hence this pr will fix that as well.
https://github.com/kubeflow/pipelines/issues/2885
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3240)
=> Clean up kataras dependency

frontend/src/lib/ParserUtils.ts, frontend/src/lib/StaticGraphParser.test.ts, frontend/src/lib/StaticGraphParser.ts, frontend/src/lib/WorkflowParser.test.ts, frontend/src/lib/WorkflowParser.ts
Fixes https://github.com/kubeflow/pipelines/issues/2353
/area frontend
/cc @Ark-kun 
Before change:
After change:
Both pipeline details page and run details page are updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3225)
=> [UI] Human readable workflow task display names

samples/core/retry/retry.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3231)
=> retry pipeline always fail (#3230)

frontend/src/components/SideNav.tsx
/area frontend
/kind bug
Context: the bug has been like this since the very beginning, but after some recent changes to add more info in the env info section, the bug can be easily triggered now.
Before the fix: when sidenav collapsed, the page grows tall and overflows the screen (notice the scrollbar on the right).
After the fix: it is the same height as expanded state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3239)
=> [UI] Fix SideNav too tall when collapsed

frontend/src/lib/OutputArtifactLoader.ts
Reason:
Currently for output artifact resolution we only consider executions with COMPLETE status. However, when cache is used, the current execution with the right argo pod name will be published with CACHED status [1]. Those should also be considered.
[1] https://github.com/tensorflow/tfx/blob/29349c9bd0196af3a7c0336a5339897406cbfdb3/tfx/components/base/base_driver.py#L263
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3228)
=> [Frontend] Fix the TFMA/TFDV viz behavior when caching is used.

sdk/python/kfp/dsl/_resource_op.py, sdk/python/tests/dsl/resource_op_tests.py, sdk/python/tests/dsl/volume_op_tests.py
Related to #1779.
This PR enables performing the `delete` action on a resource that's highly connected to the workflow (e.g., a PVC created using a `VolumeOp`).
The approach of #3194 is aligned to this one, but is a subset of it. I decided to submit this PR to have a generic `delete()` method that would work out of the box with any `ResourceOp` (or subclass).
cc @PatrickXYS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3213)
=> SDK/DSL: Enable the deletion of a resource via ResourceOp method

sdk/python/requirements.txt, sdk/python/setup.py
/assign @numerology
We should release a patched kfp shortly after then.
Context: https://github.com/kubeflow/pipelines/issues/2977#issuecomment-595598865
We should change kfp package dependency when releasing a new kfp-server-api package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3224)
=> [SDK] Use new released kfp-server-api package

sdk/python/kfp/components/modelbase.py
This commit makes it possiblt to put TaskSpec or InputSpec into python set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3258)
=> SDK - Components - Make component structures hashable

sdk/python/tests/components/test_components.py, sdk/python/tests/dsl/component_bridge_tests.py, sdk/python/tests/dsl/main.py
After the recent refactoring of the task resolving flow in the component library, some tests we left unupdated with compatibility shims added to make the tests pass.
This PR updates the remaining tests and removes the shims.
This mostly involves using explicitly using `_resolve_command_line_and_paths`.
Some tests that validate the behavior of the dsl bridge were moved to `component_bridge_tests.py`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3257)
=> SDK - Tests - Testing command-line resolving explicitly

backend/src/apiserver/client_manager.go, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
/cc @discordianfish
This reverts the revert for #3168
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3217)
=> [Deployment] Add secure=false explicitly in manifests for better observability

components/aws/athena/query/component.yaml, components/aws/athena/query/src/query.py
@Jeffwan Not sure if you want this here. But at least we needed this option. If you want me to commit more changes etc. I can do that too. I noticed that you had some todos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3254)
=> Added 'workgroup' as optional argument to athena component 

sdk/python/kfp/components/_python_op.py, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml, sdk/python/tests/components/test_python_op.py
Problem: Python components with single unnamed collection outputs are handled incorrectly.
Fixes https://github.com/kubeflow/pipelines/issues/3262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3263)
=> SDK - Components - Fixed handling collection return values

sdk/python/kfp/dsl/_component_bridge.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/tests/dsl/component_bridge_tests.py
This is a pure refactoring change.
The components library should not have any dependencies on the DSL library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3267)
=> SDK - Moved _dsl_bridge to dsl

test/tools/project-cleaner/resource_spec.yaml
Two changes:
1. also recycle clusters with `upgrade-` prefix
2. Recycle clusters earlier, 2 hours after test finish can reduce some test flakiness caused by too many clusters in the project
/assign @dushyanthsc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3282)
=> [Testing] Recycle upgrade- clusters and reduce time lapse

sdk/python/kfp/_client.py
Part of #3280 
Automatic stripping http(s) prefix and redundant '/', and throwing warnings when users only provide the backend id.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3287)
=> [SDK] Improve host name handling

frontend/src/apis/experiment/api.ts, frontend/src/pages/ExperimentList.test.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/NewExperiment.test.tsx, frontend/src/pages/NewExperiment.tsx, frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/__snapshots__/ExperimentsAndRuns.test.tsx.snap
/area frontend
Fixes https://github.com/kubeflow/pipelines/issues/3291
Pass namespace to all experiment api calls:
* listExperiment
* createExperiment
@chensun I built UI image that you can try first: gcr.io/gongyuan-pipeline-test/dev/frontend@sha256:f6d3ac5de4994cb3a9ed92e773544e580ec515435502ac5162f69b7f8108504a
I verified the image works, please have a try.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3252)
=> [UI] Pass namespace to experiment api calls

backend/Dockerfile
Add Argo CLI so that the validation introduced in https://github.com/kubeflow/pipelines/pull/3094 is triggered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3120)
=> Backend - Validate compiled samples

.travis.yml
It's likely because TFX switched their head to depending on TF2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3299)
=> [Test] Switch Travis dependency to TF2

backend/src/apiserver/resource/BUILD.bazel, backend/src/apiserver/resource/model_converter.go, backend/src/apiserver/resource/model_converter_test.go, backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go, backend/src/apiserver/server/api_converter.go, backend/src/apiserver/server/experiment_server.go, backend/src/apiserver/server/experiment_server_test.go, backend/src/apiserver/server/run_server_test.go, backend/src/apiserver/server/test_util.go, backend/src/apiserver/server/util_test.go, backend/src/apiserver/storage/experiment_store.go, backend/src/apiserver/storage/experiment_store_test.go
Conduct user authorization on namespace for the following experiment APIs:
* CreateExperiment
* GetExperiment
* ListExperiment
* DeleteExperiment
Image for testing: gcr.io/chesu-dev/api-server:pr3243
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3243)
=> [Backend][Multi-user] Add namespace to Experiment API implementation

test/presubmit-tests-with-pipeline-deployment.sh, test/sample_test.yaml
Part of #3256 
Follow up of #3298 
Expose the flag defined in #3298 so that prow job config can set it.
Also, light-weighted test cases should run unconditionally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3307)
=> [Test] expose integration test flag

frontend/src/pages/ExperimentDetails.test.tsx, frontend/src/pages/ExperimentDetails.tsx, frontend/src/pages/ExperimentList.test.tsx, frontend/src/pages/ExperimentList.tsx
Fixes https://github.com/kubeflow/pipelines/issues/3296
/area frontend
/cc @chensun
Built image for preview:
```
gcr.io/gongyuan-pipeline-test/dev/frontend@sha256:60e2ee94c910f04a86e499a08ef73a9fc3dcbdba8160f5b03f8e2db1eed7a8f9
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3297)
=> [UI] Auto refresh/redirect experiment list/detail page when user selects a different namespace

backend/src/apiserver/resource/resource_manager.go
/assign @IronPan @chensun 
/area backend
To unblock https://github.com/kubeflow/kubeflow/issues/3866#issuecomment-600409563, KFP should always disable istio sidecar injection after kubeflow namespace enables auto injection, so that single user mode KFP can keep working in kubeflow deployment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3305)
=> [Backend] Always disable istio sidecar injection

frontend/server/app.test.ts, frontend/server/app.ts, frontend/server/handlers/gke-metadata.ts, frontend/server/handlers/pod-info.ts, frontend/server/handlers/pod-logs.ts, frontend/server/handlers/tensorboard.ts, frontend/server/k8s-helper.ts, frontend/server/proxy-middleware.ts, frontend/src/TestUtils.tsx, frontend/src/components/PodYaml.test.tsx, frontend/src/components/PodYaml.tsx, frontend/src/lib/Apis.ts, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml
/area frontend
/kind feature
**Demo for pod yaml**: https://youtu.be/HvsPvUEW4Kk
**Demo for pod events**: https://youtu.be/R-zdTEwoNmw
Resolves https://github.com/kubeflow/pipelines/issues/2094
Resolves https://github.com/kubeflow/pipelines/issues/1711
Resolves https://github.com/kubeflow/pipelines/issues/3112
TODO:
Extra changes in this PR:
* I wrote new react component tests using `@testing-library/react`: https://github.com/kubeflow/pipelines/pull/3304/files#diff-0fc4f908858a81da473a9fcae07bcd30.
This the first PR with a very comprehensive test using `@testing-library/react`: https://github.com/kubeflow/pipelines/issues/2732.
* Refactored k8s-helper to no longer export `inCluster` property, so that I could unit test newly added handlers that use k8s-helper: …
=> [UI] Show step pod yaml and events in RunDetails page

components/ibm-components/watson/deploy/component.yaml, components/ibm-components/watson/deploy/src/wml-deploy.py, components/ibm-components/watson/store/component.yaml, components/ibm-components/watson/store/src/wml-store.py, components/ibm-components/watson/train/component.yaml, components/ibm-components/watson/train/src/wml-train.py, samples/contrib/ibm-samples/watson/watson_train_serve_pipeline.py
We want to add Tekton support for this pipeline. Since Tekton only allows parameter to be passed under certain path, updating the Watson ML example to take output param path. Also improving some usability on the existing example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3316)
=> Update Watson ML example to take output param path

sdk/python/tests/components/test_python_op.py, sdk/python/tests/dsl/component_bridge_tests.py
Getting rid of stray dependencies on kfp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3323)
=> SDK - Moved python op pipeline compilation test to bridge tests

sdk/python/kfp/components/_python_op.py, sdk/python/kfp/dsl/_component.py, sdk/python/tests/components/test_python_op.py, sdk/python/tests/dsl/component_tests.py
Removing stray dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3324)
=> SDK - Moved the @python_component decorator test to dsl tests

test/manifests/dev/kustomization.yaml
/cc @rui5i 
Failure error message: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/3193/kubeflow-pipeline-upgrade-test/1241989672616333312#1:build-log.txt%3A938
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3333)
=> [Testing] Disable cache-deployer temporarily because it blocks upgrade tests

frontend/server/app.test.ts, frontend/server/handlers/artifacts.ts, frontend/server/minio-helper.test.ts, frontend/server/minio-helper.ts, frontend/server/package-lock.json, frontend/server/package.json, frontend/server/utils.test.ts, frontend/server/utils.ts, frontend/server/workflow-helper.test.ts
Refer #2172
Server:
- swap node modules `tar` with `tar-stream` and `maybe-gunzip` to support tarballs with and w/o compression
- updated artifact endpoints with optional `peek` flag, which will return the first <peek> chars/bytes of the artifact if flag is provided.
UI
- Updated MinioArtifactLink to call artifact endpoint and replace link text with preview.
Automated build for this PR can be found (tag=artifact-preview)
link: https://hub.docker.com/repository/docker/e2forks/ml-pipeline-ui
Server
- All artifact handlers now support preview with `PreviewStream` (stream first x bytes if peek is provided, other acts like passthrough)
- s3 and minio artifacts now share the common `getObjectStream` func which will inflate/ungzip any compressed artifacts, streams the 1st record if the artifact …
=> [Frontend] Node server artifact handler supports preview and handles both archived and unarchived (gzip/tarball) artifacts (#2172)

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/proxy.yaml
This enables using marketplace with workload identity similar to https://github.com/kubeflow/pipelines/pull/2614.
Cloud AI Platform pipelines doc actually provided a link to instructions setting up workload identity: https://cloud.google.com/ai-platform/pipelines/docs/configure-gke-cluster#grant-access, so we should better support this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3330)
=> Add hostNetwork for marketplace proxy-agent manifest

frontend/src/pages/ExperimentList.test.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/Page.tsx
/cc @chensun 
Fixes https://github.com/kubeflow/pipelines/issues/3296#issuecomment-603066897
/area frontend
/kind bug
=> [UI] Stops experiment list from leaking previous error message

backend/src/apiserver/server/experiment_server.go, backend/src/apiserver/server/experiment_server_test.go
- Fixes the bug where #3243 missed authorization check on `ListExperiment`
- Tested via UT and SDK manual testing.
/cc @IronPan @Bobgy 
Test image: gcr.io/chesu-dev/api-server:pr3341
=> [Backend][Multi-user] Add authorization check on ListExperiment

frontend/scripts/start-proxy-and-server.sh, frontend/server/app.test.ts, frontend/server/handlers/tensorboard.ts, frontend/server/k8s-helper.ts, frontend/src/components/viewers/Tensorboard.test.tsx, frontend/src/components/viewers/Tensorboard.tsx, frontend/src/components/viewers/__snapshots__/Tensorboard.test.tsx.snap, frontend/src/lib/Apis.test.ts, frontend/src/lib/Apis.ts, frontend/src/lib/OutputArtifactLoader.test.ts, frontend/src/lib/OutputArtifactLoader.ts, frontend/src/pages/Compare.tsx, frontend/src/pages/RunDetails.tsx
/area frontend
/kind feature
Part of https://github.com/kubeflow/pipelines/issues/3294
UI image: gcr.io/gongyuan-pipeline-test/dev/frontend@sha256:de35d56815503c37789150a13d0e724e2b681fbf748c679d5971aa0834fb0369
Feature Changes:
* UI gets namespace from run and sends to node server tensorboard apis
* Node server requires namespace argument for tensorboard apis
Engprod Changes:
* Allow UI node server local development to access minio artifact api in cluster
* Wrote missing tests for tensorboard apis in node server
* Fixed url query decoded twice problem and added a unit test for it:  https://github.com/kubeflow/pipelines/pull/3355/files#diff-bbd9ad97d5d99d826328e300b108a070R690-R694
Verification:
* Tested on https://kfpmu-3-23.endpoints.gongyuan-pipeline-test.cloud.goog/ …
=> [UI] Tensorboard support for multi user

backend/metadata_writer/src/metadata_helpers.py, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml, manifests/kustomize/README.md, manifests/kustomize/base/metadata/kustomization.yaml, manifests/kustomize/base/metadata/metadata-configmap.yaml, manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml, manifests/kustomize/base/metadata/metadata-envoy-service.yaml, manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml, manifests/kustomize/base/metadata/metadata-grpc-service.yaml
The metadata service deployed is a gRPC server.
Proper KF installation deploys both an HTTP server, naming the required
resources as 'metadata-deployment' and 'metadata-service', as well as a
gRPC server, naming the corresponding resources
'metadata-grpc-deployment' and 'metadata-grpc-service'.
KFP standalone installation manifests deploy solely the gRPC server, but
use naming identical to the KF's HTTP server one.
Applying them on top of an existing KF cluster breaks Metadata service.
In this PR we change the naming making it not diverge from a proper KF
installation. We also make MetadataWriter aware of that change.
Closes #2889.
---
@Bobgy, I wrote some upgrading instructions in `README.md` under `kustomize` directory trying to …
=> Manifests: Rename metadata gRPC server's resources to metadata-grpc-*

samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/README.md, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/cloudbuild.yaml, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/create_pipeline_version_and_run.py, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/download_dataset/Dockerfile, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/download_dataset/component.yaml, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/download_dataset/download_data.py, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/pipeline.py, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/submit_result/Dockerfile, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/submit_result/component.yaml, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/submit_result/submit_result.py, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/train_model/Dockerfile, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/train_model/component.yaml, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/train_model/train.py, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_html/Dockerfile, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_html/component.yaml, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_html/visualize.py, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_table/Dockerfile, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_table/component.yaml, samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_table/visualize.py
#3 piece for CI samples:
<To make the repo more easily reviewable, pr 2784(#2784) will be broken into smaller prs>
This sample is the kaggle sample for versioned pipeline CI. This would relieve the burden on kagglers to login, download, retrain, submit data every time there is a change with their code. By setting the CI pipeline in advance, the whole process of downloading, training, submitting would be triggered automatically to let kagglers focus on their algorithms.
- Use cloudbuild for CI process
- Use kaggle API token to authenticate to kaggle
- Use KFP SDK to connect to KFP API server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3021)
=> [Sample] CI Sample: Kaggle

backend/src/apiserver/common/util.go, backend/src/apiserver/common/util_test.go, backend/src/apiserver/list/list.go, backend/src/apiserver/list/list_test.go, backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go, backend/src/apiserver/server/run_server.go, backend/src/apiserver/server/run_server_test.go, backend/src/apiserver/server/test_util.go, backend/src/apiserver/server/util.go, backend/src/apiserver/server/util_test.go, backend/src/apiserver/storage/run_store.go
Fixes #3336
- Add ACL to `CreateRun`, `GetRun`, and `ListRuns`
- Adjust the rest Run APIs to use `Namespace` from `run_details` instead of from `resource_references`.
/cc @IronPan @Bobgy 
Test image: gcr.io/chesu-dev/api-server:pr3337
=> [Backend][Multi-user] Adjust/implement run api for multiuser support

sdk/python/kfp/_client.py
**Context**
A recent change in the `Client` code config loader added a preprocessing step to strip the protocol (`http://` or `https://`) from the host endpoint, in order to prevent some common user mistakes. It is currently implemented with `lstrip(regex_pattern)`.
**Bug**
`lstrip` does not support regexes but a set of characters to remove as leading characters. 
Meaning that characters included in the pattern would be wrongly removed, for example:
```python
host = "https://test.kubeflow-cluster.my.org.net"
host.lstrip(r'(https|http)://')
```
**Fix**
Use `re.sub` instead of `lstrip` to achieve the desired behavior.
=> Fix lstrip with regex bug in the KFP client

test/deploy-cluster.sh
Fixes this error:
>ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=Master version "1.14.10-gke.17" is unsupported.
=> Testing - Upgraded GKE master version to fix tests

samples/core/iris/iris.py, samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py, samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
to address the security issues when KFP is deployed to a private cluster without access to docker hub.
=> [Sample] Change preloaded TFX samples to use GCR images

frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx
/cc @IronPan 
/area frontend
Part of https://github.com/kubeflow/pipelines/issues/3290
The namespace resource reference is no longer needed, experiment will have namespace info already in PR: https://github.com/kubeflow/pipelines/issues/3273
=> [UI] No longer pass namespace to createRun api

sdk/python/kfp/_client.py
Turned out that IAP will break without the "https" protocol. So we have to limit the processing to only non-IAP case.
Part of #3280
/cc @numerology @rmgogogo 
/assign @numerology
=> [SDK] Skip host name preprocess for the IAP case

manifests/kustomize/base/application/application-controller-deployment.yaml, manifests/kustomize/base/argo/workflow-controller-deployment.yaml, manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml, manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml, manifests/kustomize/base/pipeline-application.yaml, manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml, manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml, manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml, manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml, manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml, manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml, manifests/kustomize/base/proxy/proxy-deployment.yaml, manifests/kustomize/env/dev/minio/minio-deployment.yaml, manifests/kustomize/env/dev/mysql/mysql-deployment.yaml, manifests/kustomize/env/gcp/gcp-configurations-patch.yaml, manifests/kustomize/env/gcp/minio/minio-gcs-gateway-deployment.yaml, manifests/kustomize/env/gcp/mysql/cloudsql-proxy-deployment.yaml, manifests/kustomize/namespaced/kustomization.yaml
I tried to deploy Kubeflow Pipelines but had some issues due to that the version on the deployment resource are /v1beta1 which is [deprecated since 1.16](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/). This PR suggest to fix that by updating the version.
=> Update deployment resource version from /v1beta1 -> /v1

sdk/python/kfp/_client.py
- Remove `namespace` input parameter from `run_pipeline` and `schedule_pipeline` since we can retrieve namespace info from the owning experiment
- Allow setting/getting user namespace in a context map (saved a local file), so that user doesn't have to specify it with every call that needs a namespace field. 
- Make `namespace` input parameter default to `None` for consistence. 
Part of #3290
=> [SDK][Multi-user] refine sdk for multi-user support

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml, manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
Problem: when cache-deployer deployment has any updates, Kubernetes will create a new instance first and stop the old one afterwards
Solution:
Adding strategy: type: Recreate makes sure Kubernetes first stops the old instance before starting the new one, so that there is only one instance running when cache-deployer deployment is updated and they won't conflict with each other.
/cc @rmgogogo @IronPan 
(we are using the same pattern for mysql deployment).
Reference:
* https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/#updating
=> [Cache] Change cache-deployer deployment to strategy recreate

components/aws/sagemaker/batch_transform/component.yaml, components/aws/sagemaker/common/_utils.py, components/aws/sagemaker/deploy/component.yaml, components/aws/sagemaker/ground_truth/component.yaml, components/aws/sagemaker/hyperparameter_tuning/component.yaml, components/aws/sagemaker/model/component.yaml, components/aws/sagemaker/train/component.yaml, components/aws/sagemaker/workteam/component.yaml
For all AWS sagemaker components if we don't pass 'endpoint_url' argument it used to default to empty string.
This empty string input throws an error when we call the boto3 client in [_utils.get_sagemaker_client()](https://github.com/kubeflow/pipelines/blob/7b55c2b8101ec2d08b5c4c2f3a0d490d3ff8c0ee/components/aws/sagemaker/common/_utils.py#L61)
Error message:
```
File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 261, in create_endpoint
raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: 
```
Fixed the issue by making endpoint_url default to None 
Uploaded the new docker container to [redbackthomson/aws-kubeflow-sagemaker](https://hub.docker.com/r/redbackthomson/aws-kubeflow-sagemaker/tags)
Tested the changes by creating a pipeline …
=> AWS sagemaker : Make 'endpoint_url' argument default to None instead of empty string 

frontend/src/lib/RunUtils.ts, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx
Fixes https://github.com/kubeflow/pipelines/issues/3290
After change in https://github.com/kubeflow/pipelines/pull/3403,
we can no longer get namespace from resource reference, instead read it from workflow metadata
Problem
now UI cannot read pod logs because it cannot get namespace when in multi user mode
/area frontend
=> [UI - multiuser] Fix pod log namespace source

frontend/src/atoms/ExternalLink.tsx, frontend/src/components/Router.tsx, frontend/src/lib/MlmdUtils.ts, frontend/src/pages/ExecutionDetails.tsx, frontend/src/pages/ExecutionList.tsx, frontend/src/pages/Page.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Mitigates https://github.com/kubeflow/pipelines/issues/3424 and https://github.com/kubeflow/pipelines/issues/3226
Demo: https://youtu.be/ARsCElYSqq8
Changes:
* Find corresponding ML metadata for pipeline run (context) and steps (execution) from Run Details page
* Refactor execution details page component to be portable
* Show execution details on Run Details' step ML Metadata tab
Current Limitation:
* ML Metadata from mlmd writer doesn't record pod name in execution custom property `kfp_pod_name`, so it isn't recorded at all. Therefore, this only supports tfx. (but we can support kfp dsl later too)
/area frontend
=> [UI] Show execution details in Run Details Page ML Metadata tab of steps

sdk/python/kfp/components/_yaml_utils.py
Fixing compatibility with PyYaml 5.3
=> SDK - Components - Restored the yaml formatting style

components/gcp/automl/create_dataset_for_tables/component.py, components/gcp/automl/create_dataset_for_tables/component.yaml, components/gcp/automl/create_model_for_tables/component.py, components/gcp/automl/create_model_for_tables/component.yaml
=> Components - Add model URL to AutoML - Create model/dataset for tables 

test/build-images.sh, test/check-build-image-status.sh, test/cloudbuild/batch_build.yaml, test/deploy-pipeline-lite.sh
Part of https://github.com/kubeflow/pipelines/issues/3256
Changes:
* All 3 presubmit tests will share one cloudbuild job for image building
* Add retry at most twice if the first build fails
* (not mentioned in title, but it's a simple change) Added retry to workload identity setup
Flakiness rate should be greatly reduced.
Previously, we had 3 presubmit tests and 1 cloudbuild job for each presubmit test.
If any one of them fails, developer need to retry at least one test.
With this PR, all 3 presubmit tests share one cloudbuild job and they can retry it 2 times (total 3 attempts).
e.g. current data for image building is averagely 10% jobs fail randomly.
Previous flakiness rate was 1-(1-10%)^3 = 27.1%.
With this PR, it will be 10%^3 = 0.1%.
=> [Testing] Reduce image build flakiness by share and retry cloudbuild jobs

test/deploy-pipeline-lite.sh, test/install-argo.sh
Part of https://github.com/kubeflow/pipelines/issues/3256
Example error log: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/3502/kubeflow-pipeline-e2e-test/1249953399206580227#1:build-log.txt%3A219
I'm going to quickly merge this by myself because it's a small obvious fix.
=> [Test] Fix concurrent IAM policy changes flakiness

sdk/python/kfp/dsl/_volume_op.py
Current VolumeOps can't specify volume_name which block user to use different PV (e.x. backend by Cloud Filestore/NFS).
This PR wants to unlock it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3314)
=> Enable binding new PVC to specific PV

manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml
Fixes https://github.com/kubeflow/pipelines/issues/3500
The problem was introduced in https://github.com/kubeflow/pipelines/pull/3108 and already fixed in https://github.com/kubeflow/pipelines/pull/3413, but envoy image rebuilding/release is not part of KFP release.
0.4.0 was still using the initial envoy with config routing to wrong server.
/cc @rmgogogo 
/assign @Ark-kun @dushyanthsc 
/cc @numerology 
Shall we create a 0.4.0 branch and patch 0.4.0 release?
=> [Deployment] Fix metadata envoy configuration

components/aws/sagemaker/batch_transform/component.yaml, components/aws/sagemaker/common/_utils.py, components/aws/sagemaker/deploy/component.yaml, components/aws/sagemaker/ground_truth/component.yaml, components/aws/sagemaker/hyperparameter_tuning/component.yaml, components/aws/sagemaker/model/component.yaml, components/aws/sagemaker/train/component.yaml, components/aws/sagemaker/workteam/component.yaml, samples/contrib/aws-samples/ground_truth_pipeline_demo/README.md
AWS ground_truth component expects active_learning_model_arn.txt to be always non-empty 
[component.yaml #L129](https://github.com/kubeflow/pipelines/blob/cfcd824ed1c7bb6924cee30b14e49d281f1d4a73/components/aws/sagemaker/ground_truth/component.yaml#L129)
But when we don't pass the optional argument "enable_auto_labeling", empty string is stored in [active_learning_model_arn.txt](https://github.com/kubeflow/pipelines/blob/cfcd824ed1c7bb6924cee30b14e49d281f1d4a73/components/aws/sagemaker/ground_truth/src/ground_truth.py#L71)
- [string variable which gets stored in active_learning_model_arn.txt](https://github.com/kubeflow/pipelines/blob/cfcd824ed1c7bb6924cee30b14e49d281f1d4a73/components/aws/sagemaker/ground_truth/src/ground_truth.py#L64) 
- [util function which returns that …
=> AWS sagemaker: fixed a bug in ground_truth and updated all components to use images from new docker hub repo

components/gcp/container/component_sdk/python/kfp_component/google/bigquery/_query.py
Working around an Argo bug.
Revert this when we upgrade to Argo version which has the fix: https://github.com/argoproj/argo/pull/1653
=> Components - Fixed BigQuery - Query component

backend/README.md, backend/update_requirements.sh, test/sample-test/README.md
This helps generating requirements for multiple requirements.in files.
It also fixes the locking issues that seem to be caused by mounting directories using Docker.
=> Infra - Improved the update_requirements script

backend/test/integration/run_api_test.go
Attempt to fix #3538
Per error message from the issue, we're comparing the value of pointers instead of the dereferenced values.
/cc @Ark-kun @hongye-sun @jingzhang36
=> [Test] fix TestRunApi integration test

sdk/python/kfp/_client.py
There's a bug introduced by #3417: `client.list_runs` will filter runs with empty namespace if neither `experiment_id` or `namespace` is specified. This breaks in single-user mode, as runs by default are under "kubeflow" namespace. 
Fix: only filter namespace when it holds a non-empty value.
/cc @Bobgy @IronPan @Ark-kun
=> [SDK] Fixing bug where client.list_runs filters on empty namespace by default.

backend/test/integration/run_api_test.go
Fixes #3538
When there're multiple elements in ResourceReferences, the order can be non-deterministic. So we need to sort it before checking the equality of run structs.
/cc @Ark-kun @hongye-sun @jingzhang36
=> [Test] Fix api-integration-tests flakyness

manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml, manifests/kustomize/env/dev/kustomization.yaml, manifests/kustomize/env/gcp/kustomization.yaml, manifests/kustomize/env/platform-agnostic/kustomization.yaml, manifests/kustomize/sample/README.md, manifests/kustomize/sample/kustomization.yaml
Here default it to "kubeflow" and add comments to make sure others won't hit the deployer-installation issue.
=> Clusterrolebinding is using namespace which not parametrized

manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
https://github.com/kubeflow/pipelines/pull/3540/files#diff-cd4ffa651ef617b07c17a8b45428a55cR29 is the culprit
Follow up presubmit test failure introduced in #3549 
Fixes https://github.com/kubeflow/pipelines/issues/3577
=> [Testing] Fix frontend integration test broken by #3540

test/manifests/dev/kustomization.yaml
I inspected test cluster and found the `pipeline-install-config` was generated in `default` namespace.
/cc @rmgogogo 
This PR fixes it.
=> [Testing] pipeline-install-config should be in kubeflow namespace

sdk/python/kfp/cli/pipeline.py
Fixing issue introduced in https://github.com/kubeflow/pipelines/pull/2879
=> SDK - CLI - Fixed incompatibility with Python 3.5

.release.cloudbuild.yaml
/cc @rmgogogo @IronPan 
We agreed to no longer use the compiled manifests.
So to fix current cloudbuild failure 
https://pantheon.corp.google.com/cloud-build/builds/57066be3-df89-4fc2-827a-bea4187789d6;step=94?project=ml-pipeline-test, I think we can remove them.
error message (caused by recent kustomize manifest folder structure refactoring)
```
Error: absolute path error in '/workspace/manifests/kustomize/base/crds' : evalsymlink failure on '/workspace/manifests/kustomize/base/crds' : lstat /workspace/manifests/kustomize/base/crds: no such file or directory
```
=> [Release] Fix cloudbuild: remove compiled manifests

frontend/src/lib/MlmdUtils.ts, frontend/src/pages/RunDetails.tsx
Mitigates https://github.com/kubeflow/pipelines/issues/3226
This makes https://github.com/kubeflow/pipelines/pull/3457 available for metadata written by metadata writer (implemented in https://github.com/kubeflow/pipelines/issues/3462).
~This is a rough implementation, I didn't successfully verify it e2e, because I was blocked by https://github.com/kubeflow/pipelines/issues/3552~
EDIT: verified e2e
/area frontend
=> [UI] Get execution details from metadata writer

frontend/README.md, frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx
small ui bug fix as a first merge request.
The yellow warning `Some parameters are missing values` set when creating a run was fixed to initial values, and did not get removed or re-added if a value was added or taken away for one of the params.
Also fixes table formatting in frontend README.md.
=> [UI] fix - create run missing-param warning not reacting to param value changes

sdk/python/kfp/_client.py
In order to be able to schedule recurring runs via the python client, this PR adds the methods
- `run_pipeline_recurring`
- `list_recurring_runs`
- `get_recurring_run`
to the client.
The private method `_create_job_config` is implemented to avoid code duplication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2978)
=> Add method to schedule a recurring run to python client

sdk/python/kfp/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py
Related to https://github.com/kubeflow/pipelines/pull/3578
=> SDK - Compiler - Include the SDK version information in the compiled workflows

components/aws/sagemaker/hyperparameter_tuning/README.md, components/aws/sagemaker/hyperparameter_tuning/component.yaml, components/aws/sagemaker/train/README.md, components/aws/sagemaker/train/component.yaml
Generally speaking 1 GB volume size is way too small. In general we recommend 25-30GB. I took this number from [default](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1119) mentioned in sagemaker python sdk
=> Fixing volume size default value from 1 to 30

backend/src/crd/controller/viewer/reconciler/reconciler.go, backend/src/crd/controller/viewer/reconciler/reconciler_test.go
/assign @IronPan @chensun 
/area backend
Resolves the problem described in https://github.com/kubeflow/pipelines/issues/3294#issuecomment-619562103
> After some troubleshooting, I found that it seems istio didn't automatically find out the traffic is in http, so authorization rules based on http properties didn't take effect. https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/
=> [Viewer] Service needs port name for istio

backend/test/integration/job_api_test.go, backend/test/integration/run_api_test.go
A follow up on https://github.com/kubeflow/pipelines/pull/3547/files#r411183276
We now have two ways to solve the same issue, and as discussed in linked comment, the sorting approach is likely better for code readability. 
/cc @Bobgy @jingzhang36 
=> [Test] Sort job resource references before equality check

backend/src/cache/deployer/deploy-cache-service.sh
Fixed the bug in the waiting forever mechanism. Previously it would restart the script if there is any Kubernetes connectivity problem. Should fix https://github.com/kubeflow/pipelines/issues/3609
The script no longer reinstalls the resources if the MutatingWebhookConfiguration already exists.
=> Cache - Stabilized the deployer script

sdk/python/kfp/dsl/_container_op.py
The API function seemed to be not correct, which is now fixed.
=> Fix container.set_image_pull_policy documentation string

sdk/python/kfp/_client.py
There is a bug in the expression that should check whether both or none of the required arguments is passed.
=> kfp_client: fix wrong check

sdk/python/kfp/components/_component_store.py, sdk/python/kfp/components/_components.py
The PR is a refactoring.
Split all load_component* methods in _components and _component_store into _load_component_spec* and creating task factory from that spec.
This makes it easier to load the spec without having to create task factory functions.
=> SDK - Components - Split load_component functions into loading the spec and creating task factory

backend/metadata_writer/requirements.in, backend/metadata_writer/requirements.txt
There was a backwards-incompatible MLMD server-side change that caused the get_artifacts_by_uri API to start silently returning empty lists of artifacts.
Fixes https://github.com/kubeflow/pipelines/issues/3656
=> Backend - Upgraded MLMD client to fix Metadata Writer

proxy/attempt-register-vm-on-proxy.sh
I watched the case Proxy not got generated/patched via Kustomize deployment frequently while never happen in MKP.
It could due to Kustomize apply configmap later that deployment. Maybe refer the configmap in the deployment is a better fix.
=> continue #3663, sleep a while to wait for configmap

sdk/python/kfp/gcp.py
* Add an operator to configure toleration of the taints the GKE automatically assigns to the GPU nodes.
* https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#gpu_pool says
=> Add an operator to configure toleration of the GKE GPU node taints

components/aws/sagemaker/THIRD-PARTY-LICENSES.txt, components/aws/sagemaker/codebuild/deploy.buildspec.yml, components/aws/sagemaker/codebuild/integration-test.buildspec.yml, components/aws/sagemaker/codebuild/scripts/deploy.sh, components/aws/sagemaker/codebuild/unit-test.buildspec.yml
Add CodeBuild `build-spec.yml` files for our new unit and integration test steps, as well as one for our deployment step.
All infrastructure will be configured on our end, but releasing these as reference for our internal testing guidelines.
=> [AWS SageMaker] Add CodeBuild Steps

components/kubeflow/katib-launcher/src/launch_experiment.py
Katib Experiment name should be unique else we get "Experiment Already Exists" error. This creates a problem when running a katib gridsearch experiment for the same ML model.
So, one simple solution is to append a UUID at the end of experiment name to avoid the conflict. 
I have updated the code in my branch to do just that. 
It takes experiment name provided by user in pipeline code and append a 32-character hexadecimal string at the end of it.
=> Katib Launcher Experiment Name Conflict

samples/core/pipeline_parallelism/pipeline_parallelism_limits.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/tests/compiler/compiler_tests.py
/cc @DmitryBe
Support `set_parallelism` for pipeline conf.  This is mostly to support `dsl.ParallelFor`.
See #3346
PS: Should we also support this inside the api-server? 
> NOTE  
> kfp sdk does not seems to support `steps`, hence step parallelism limits are not supported in this PR
=> Support execution throttling for executing the pipelines (#3346)

.travis.yml
There have been many persistent coveralls errors that are blocking our PRs. Disabling coveralls for now.
=> Travis - Disabled coveralls for python

backend/src/cache/deployer/cache-configmap.yaml.template, backend/src/cache/deployer/deploy-cache-service.sh
Workaround for #3701
I wonder what will be the cluster behavior when there are configs pointing to a non-existing service in non-existing namespace.
=> Cache - Add namespace to webhook config's name

sdk/python/kfp/components/structures/components.json_schema.json, sdk/python/kfp/components/structures/components.json_schema.outline.yaml
There were several syntax/structure errors (`CommandlineArgumentOrArrayType` instead of `StringOrPlaceholder`, Kubernetes schema refs and the top ref).
Also removed couple of obsolete items (source, schemaVersion).
=> Fixed the ComponentSpec schema

sdk/python/kfp/_client.py, sdk/python/kfp/cli/pipeline.py
* Implement the upload_pipeline_version method in kfp.Client
* Add 'kfp pipeline upload_version' to CLI
<details>
<summary>Verification logs with AI Platform Pipeline</summary>
* Upload a version with CLI
```bash
$ kfp --endpoint xxxxxxxx-dot-us-central2.pipelines.googleusercontent.com pipeline upload-version ./hello_world.py.yaml test-cli-3 f06973d6-bc75-4a10-8248-60eff8701129
The test-cli-3 version of the pipeline f06973d6-bc75-4a10-8248-60eff8701129 has been submitted
Pipeline Version Details
--------------------------
Pipeline ID   f06973d6-bc75-4a10-8248-60eff8701129
Version Name  test-cli-3
Uploaded at   2020-05-01T05:00:30+00:00
```
* Check the version on the Web UI
</details>
* Make it possible to upload a version of the pipeline with CLI
=> Make it possible to upload a version of the pipeline with CLI

components/aws/sagemaker/tests/integration_tests/.flake8, components/aws/sagemaker/tests/integration_tests/README.md, components/aws/sagemaker/tests/integration_tests/component_tests/test_model_component.py, components/aws/sagemaker/tests/integration_tests/component_tests/test_train_component.py, components/aws/sagemaker/tests/integration_tests/conftest.py, components/aws/sagemaker/tests/integration_tests/environment.yml, components/aws/sagemaker/tests/integration_tests/pytest.ini, components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-model/config.yaml, components/aws/sagemaker/tests/integration_tests/resources/config/simple-mnist-training/config.yaml, components/aws/sagemaker/tests/integration_tests/resources/definition/create_model_pipeline.py, components/aws/sagemaker/tests/integration_tests/resources/definition/training_pipeline.py, components/aws/sagemaker/tests/integration_tests/utils/__init__.py, components/aws/sagemaker/tests/integration_tests/utils/argo_utils.py, components/aws/sagemaker/tests/integration_tests/utils/kfp_client_utils.py, components/aws/sagemaker/tests/integration_tests/utils/minio_utils.py, components/aws/sagemaker/tests/integration_tests/utils/sagemaker_utils.py
As a developer, I want to have an easy to use testing framework for AWS SageMaker components so that we can maintain code quality and prevent regressions.
Hence I have created Pytest based integration tests for SageMaker components. Workflow of a test run:
1. User follows the README and completes the requirements.
1. User runs pytest command which triggers a pipeline run using KFP SDK for the user defined pipeline definition under resources directory
1. Test writer knows an approximate job completion time and output jobs/artifacts which would be created once the run is complete. Hence the test is configured to wait for run completion, download the output artifacts and verify the job/artifacts were created in AWS
This PR is a proof of concept for #3631. Looking for feedback
Notes: Some …
=> Integration tests for AWS SageMaker Components

frontend/src/lib/OutputArtifactLoader.ts, frontend/src/pages/RunDetails.tsx
Part of https://github.com/kubeflow/pipelines/issues/3114
Previous request waterfall:
With the improvement:
Improvements:
* executions are already fetched in RunDetails page
* some requests can be done in paralell.
This reduces 5 level request waterfall to 2 levels, a drastic improvement specially when network roundtrip delay is long.
/area frontend
=> [UI] Improve TFX artifact visualization speed

frontend/src/components/Router.tsx, frontend/src/components/__snapshots__/Router.test.tsx.snap, frontend/src/lib/MlmdUtils.ts, frontend/src/pages/ArtifactDetails.tsx, frontend/src/pages/ArtifactList.tsx, frontend/src/pages/ExecutionDetails.tsx, frontend/src/pages/ExecutionList.tsx, frontend/src/pages/RunDetails.tsx
Fixes https://github.com/kubeflow/pipelines/issues/2669
We shouldn't include type names in urls from the first place, because artifact/executions only use the id as unique identifier.
/area frontend
/cc @Ark-kun
=> [UI] Cleanup, remove types from urls in artifact/execution details page

backend/src/apiserver/resource/resource_manager_util.go
related : https://github.com/kubeflow/pipelines/issues/3542
related: https://github.com/kubeflow/pipelines/issues/3669
We used to call PatchPipelineDefaultParameter(*currentParam.Value) to replace the {{}} placeholder in currentParam.Value. 
It is reported that currentParam.Value could be nil pointer and the above call crashes api server.
So we check for nil pointer before  currentParam.Value is used. If this is a nil pointer, we switch to currentParam.Default, if currentParam.Default is not nil, we call PatchPipelineDefaultParameter(*currentParam.Default)
/assign @numerology Since I am not familiar with setting parameters, please let me know if we should simply do no-op when currentParam.Value is nil pointer (instead of switching to use currentParam.Default)
/cc @Bobgy 
/cc @rmgogogo
=> When patching the {{}} placeholder in parameter, check for possible nil pointer

frontend/src/components/Banner.test.tsx, frontend/src/components/Banner.tsx, frontend/src/components/Router.tsx, frontend/src/components/__snapshots__/Banner.test.tsx.snap, frontend/src/components/viewers/VisualizationCreator.test.tsx, frontend/src/components/viewers/VisualizationCreator.tsx, frontend/src/lib/OutputArtifactLoader.ts, frontend/src/pages/ArchivedExperiments.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Fixes https://github.com/kubeflow/pipelines/issues/3328
demo: https://youtu.be/Xo3OxBwV55U
Changes:
* Rename artifacts tab to visualizations tab
* Move inputs/outputs tab as the default tab (instead of visualizations)
* Show visualization doc link in the tab
* Show a warning banner when there are no visualizations
* Hide the visualization creator with an extra click because it's an advanced feature and shouldn't usually be used.
/kind feature
/area frontend
/area ux
=> [UI] Make visualization tab easier to understand

.travis.yml
Flake8 got an update and now fails for the existing code that we have.
This PR makes the flake8 test always succeed. (But the log can still be viewed)
=> Travis - Made flake8 test optional

sdk/python/kfp/components/_python_op.py, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
It's a standard python library (although not well supported) and it does not leave training spaces.
=> SDK - Prioritize lib2to3 when stripping type annotations

.cloudbuild.yaml, .release.cloudbuild.yaml, backend/Dockerfile, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml, manifests/kustomize/base/argo/cluster-scoped/workflow-crd.yaml, manifests/kustomize/base/argo/workflow-controller-configmap.yaml, manifests/kustomize/base/argo/workflow-controller-deployment.yaml, manifests/kustomize/base/argo/workflow-controller-role.yaml, test/check-argo-status.sh, test/install-argo.sh, test/sample-test/Dockerfile, test/tag_for_hosted.sh, third_party/argo/Dockerfile.argoexec, third_party/argo/Dockerfile.workflow-controller, third_party/argo/release.sh
Fixes https://github.com/kubeflow/pipelines/issues/3617
Fixes #3322
=> Upgraded Argo to v2.7.5

backend/src/apiserver/server/run_metric_util.go, backend/src/apiserver/server/run_metric_util_test.go
Fixes https://github.com/kubeflow/pipelines/issues/3655
Mitigates https://github.com/kubeflow/pipelines/issues/3499
Doc PR in https://github.com/kubeflow/website/pull/1950
FYI, why I did this: https://github.com/kubeflow/pipelines/issues/3499#issuecomment-627132988
Verified it works e2e using test image gcr.io/ml-pipeline-test/d73087f0a2d71aefc891cb269545c3062b9abf0a/api-server@sha256:3b4a1503412e930962e886856abf2fbea6ac31772abcc6aa54072dfef20fe66d
/cc @amygdala @numerology
=> [Backend] Allow capital letters and underscore in metric names

frontend/src/components/MinioArtifactPreview.test.tsx, frontend/src/components/MinioArtifactPreview.tsx
@Bobgy 
Fix bug in #3707 - MinioArtifactPreview should link to the full content of the artifact instead of the preview.
=> Fix bug in #3707 - href should show full artifact content

tools/metadatastore-upgrade/README.md, tools/metadatastore-upgrade/main.go
Fixes https://github.com/kubeflow/pipelines/issues/3284
As per this [published contract](https://docs.google.com/document/d/1gF-mx3lMyU9h7MAAOXP-KGV-BF-UabDsAlFrWNNhKBo/edit?usp=sharing) shared with the Kubeflow Pipelines community this tool provides Metadata Store upgrade support in KFP clusters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3295)
=> MetadataStore: Upgrade tool

frontend/src/components/DetailsTable.tsx, frontend/src/components/MinioArtifactPreview.tsx
Fixes https://github.com/kubeflow/pipelines/issues/2897
Instead of showing a hovering tip, I think it's a better UX if parameters and urls just show up as a whole. From my knowledge, these usages shouldn't include super-long strings that clutter the page too much.
If a parameter is too long, it should be a file instead. URLs have length limit intrinsically.
Demos:
When there are enough space:
When there isn't enough space:
=> [UI] Wrap parameter/urls on overflow

sdk/python/kfp/components/_components.py, sdk/python/tests/components/test_components.py, sdk/python/tests/components/test_data/retail_product_stockout_prediction_pipeline.component.yaml
The digest is calculated when loading the component from URL, file or text.
Slightly refactored component loading - streams are no longer used, only bytes.
TODO: Calculate the digest if missing
TODO: Report possible digest conflicts
=> SDK - Components - Calculate component hash digest

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/dsl/_component_bridge.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml, sdk/python/tests/dsl/component_bridge_tests.py
Previously, ContainerOp had strict requirements for the output names, so we had to convert all the names before passing them to the ContainerOp constructor. Outputs with non-pythonic names could not be accessed using their original names.
Now ContainerOp supports any output names, so we're now using the original output names.
However to support legacy pipelines, we're also adding output references with pythonic names.
=> SDK - Made outputs with original names available in ContainerOp.outputs

frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
bug found in https://github.com/kubeflow/pipelines/pull/3747#issuecomment-627652557, introduced in https://github.com/kubeflow/pipelines/pull/3707
/assign @eterna2 
Because <DetailsTable> didn't have a key, when clicking different steps, it shows outdated content from previously selected step.
=> [UI] Fix artifact preview with outdated content

frontend/src/pages/NewRun.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Fixes https://github.com/kubeflow/pipelines/issues/2897
/area frontend
/kind bug
Changes:
* Add tooltip on version selector
* Add tooltip on run list page's version name column
=> [UI] Show tooltip on long version names

backend/metadata_writer/src/metadata_helpers.py, backend/metadata_writer/src/metadata_writer.py
Previously only s3 artifacts were supported and only bucket and key were included (not endpoint, for example).
Related to https://github.com/kubeflow/pipelines/pull/3531
Related to https://github.com/kubeflow/pipelines/pull/3530
@Jeffwan WDYT?
/hold Until UX can parse the new format.
=> Metadata Writer - Preserve all Argo artifact information

frontend/server/app.test.ts, frontend/server/app.ts, frontend/server/configs.ts, frontend/server/handlers/tensorboard.ts, frontend/server/helpers/auth.ts
/cc @chensun @jlewi @yanniszark 
Part of https://github.com/kubeflow/pipelines/issues/3752
Make header configurable by `KUBEFLOW_USERID_HEADER` and `KUBEFLOW_USERID_PREFIX` options.
In addition to making the header configurable, I made some refactorings to make code more manageable:
* extracted an auth helper
* refactored unit tests to rely less on implicit values and reuse more common setup utils
=> [UI Server] Refactor for configurable auth header

sdk/python/kfp/components/_naming.py, sdk/python/tests/components/test_components.py
In some cases the input and output names need to be converted (for example, the input names need to be converted to python function parameter names).
With naive renaming, multiple inputs might be mapped to the same parameter name in some edge cases. The `generate_unique_name_conversion_table` creates a correct mapping.
However, in some really rare cases the resulting mapping could be confusing since it might rename an input whose name was already a correct parameter name and map a different input name to that parameter. E.g. {'AAA' -> 'aaa', 'aaa' -> 'aaa_2'}.
This PR fixes that. Names that do not change when applying the conversion_func will remain unchanged in the mapping. {'AAA' -> 'aaa_2', 'aaa' -> 'aaa'}.
=> SDK - Components - Improved stability of the input and output renaming

backend/Dockerfile, frontend/Dockerfile, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml, manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml, manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
/assign @IronPan @rmgogogo 
Part of https://github.com/kubeflow/pipelines/issues/3756
Added probes for UI, api, visualization servers. Operators will be added in a separate PR.
I verified this workaround works properly when istio mutual TLS is enabled.
=> [Servers] Add liveness and readiness probes

frontend/README.md, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml, manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml, manifests/kustomize/base/metadata/metadata-grpc-service.yaml
Part of https://github.com/kubeflow/pipelines/issues/3756
Add tcp probe to metadata grpc service.
(Use tcp probe, because it's the only support for grpc service.)
https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/
Using an extra CLI tool to probe grpc endpoint seems unnecessary at this moment. We can evaluate that later.
/cc @IronPan
=> Add probes to metadata grpc service

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/proxy.yaml
I tried to deploy Kubeflow Pipelines but had some issues due to that the version on the deployment resource are /v1beta1 which is deprecated since 1.16. This PR suggest to fix that by updating the version.
Related to https://github.com/kubeflow/pipelines/pull/3421
=> Update deployment resource version from /v1beta1 -> /v1 in gcp_marketplace

sdk/python/kfp/dsl/_component_bridge.py
Removing the component spec from component_ref (since it would be a duplicate), but making sure the whole spec if available in component_spec.
=> SDK - Moved some data from the component_ref annotation to the component_spec annotation

components/aws/sagemaker/tests/integration_tests/README.md, components/aws/sagemaker/tests/integration_tests/component_tests/test_batch_transform_component.py, components/aws/sagemaker/tests/integration_tests/component_tests/test_deploy_component.py, components/aws/sagemaker/tests/integration_tests/component_tests/test_hpo_component.py, components/aws/sagemaker/tests/integration_tests/component_tests/test_model_component.py, components/aws/sagemaker/tests/integration_tests/component_tests/test_train_component.py, components/aws/sagemaker/tests/integration_tests/environment.yml, components/aws/sagemaker/tests/integration_tests/pytest.ini, components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-batch-transform/config.yaml, components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-endpoint/config.yaml, components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-hpo/config.yaml, components/aws/sagemaker/tests/integration_tests/resources/config/simple-mnist-training/config.yaml, components/aws/sagemaker/tests/integration_tests/resources/definition/create_endpoint_pipeline.py, components/aws/sagemaker/tests/integration_tests/resources/definition/hpo_pipeline.py, components/aws/sagemaker/tests/integration_tests/resources/definition/transform_job_pipeline.py, components/aws/sagemaker/tests/integration_tests/utils/__init__.py, components/aws/sagemaker/tests/integration_tests/utils/kfp_client_utils.py, components/aws/sagemaker/tests/integration_tests/utils/minio_utils.py, components/aws/sagemaker/tests/integration_tests/utils/s3_utils.py, components/aws/sagemaker/tests/integration_tests/utils/sagemaker_utils.py
- Add tests for following components:
- Create Endpoint
- Hyperparameter Tuning job and 
- Batch Transform Job
- Can now run the tests in parallel: Added and tested [pytest-xdist](https://pypi.org/project/pytest-xdist/) plugin which can be used to run the tests in parallel . All the test currently take around 23 mins if run serially and 9 mins if run in parallel on my notebook
- Minor bug fixes and documentation
- Add some utility methods
=> AWS Sagemaker Components - enhance integration test coverage

test/deploy-cluster.sh
/cc @chensun @Ark-kun 
/area testing
This fixes the https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/3776/kubeflow-pipeline-e2e-test/1262573140995739651#1:build-log.txt%3A140
which blocks all presubmit tests
=> [Testing] Fix "1.14.10-gke.27" is unsupported

sdk/python/kfp/components_tests/test_components.py, sdk/python/kfp/components_tests/test_data/retail_product_stockout_prediction_pipeline.py, sdk/python/kfp/components_tests/test_graph_components.py, sdk/python/kfp/components_tests/test_python_op.py, sdk/python/kfp/components_tests/test_python_pipeline_to_graph_component.py, sdk/python/kfp/components_tests/test_structure_model_base.py
This makes tests easier to run in local dev scenarios.
Fixes https://github.com/kubeflow/pipelines/issues/3786
=> SDK - Components - Use relative imports for tests

backend/src/apiserver/common/config.go, backend/src/apiserver/common/const.go, backend/src/apiserver/main.go, backend/src/apiserver/server/experiment_server_test.go, backend/src/apiserver/server/job_server_test.go, backend/src/apiserver/server/run_server_test.go, backend/src/apiserver/server/util.go, backend/src/apiserver/server/util_test.go, backend/src/apiserver/server/visualization_server_test.go
Part of #3752
Make header configurable by KUBEFLOW_USERID_HEADER and KUBEFLOW_USERID_PREFIX options.
/cc @Bobgy @yanniszark
=> [Backend] Make user identity header configurable

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_pipeline_param.py, sdk/python/tests/dsl/pipeline_param_tests.py
Currently PipelineParam doesn't get replaced if it's part of a dict key. 
This is needed for example when the key of a configmap is derived from a pipeline input.
=> Allow PipelineParams in dict keys too.

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
Fixes #3545
Benefit of adding the permissions:
* swf custom resources have related sync events
* Error messages go away from scheduled workflow server
=> [ScheduledWorkflow] Fix events permission missing, fixes #3545

backend/metadata_writer/src/metadata_writer.py
Related issue: https://github.com/kubeflow/pipelines/issues/3405
Seems this is just text error, I can still write artifact and metadata into s3. But we can not easily download `mlpipeline-ui-metadata.tgz` easily because of the incorrect protocol. 
`argo_artifact_to_uri` does one thing, it get outputs value from `workflows.argoproj.io/outputs` and return an uri.
One example is 
```
{
"artifacts": [
{
"name": "mlpipeline-ui-metadata",
"path": "/mlpipeline-ui-metadata.json",
"s3": {
"endpoint": "s3.amazonaws.com",
"bucket": "jiaxin-kubeflow-pipeline-data",
"insecure": false,
"accessKeySecret": {
"name": "aws-secret",
"key": "AWS_ACCESS_KEY_ID"
},
"secretKeySecret": {
"name": "aws-secret",
"key": "AWS_SECRET_ACCESS_KEY"
},
"key": "artifacts/iris-classification-pipeline-9shz4/iris-classificatio …
```
=>  Infer artifact store endpoint in metadata writer

components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py, components/aws/sagemaker/train/src/train.py
Changing the default value for volume size from 1 to 30 GB.
=> Changing the default volume size to 30

.gitignore, components/aws/sagemaker/.gitignore, components/aws/sagemaker/codebuild/integration-test.buildspec.yml, components/aws/sagemaker/codebuild/scripts/construct_environment_array.sh, components/aws/sagemaker/codebuild/unit-test.buildspec.yml, components/aws/sagemaker/tests/integration_tests/.env.example, components/aws/sagemaker/tests/integration_tests/Dockerfile, components/aws/sagemaker/tests/integration_tests/README.md, components/aws/sagemaker/tests/integration_tests/conftest.py, components/aws/sagemaker/tests/integration_tests/environment.yml, components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-endpoint/config.yaml, components/aws/sagemaker/tests/integration_tests/resources/definition/create_endpoint_pipeline.py, components/aws/sagemaker/tests/integration_tests/resources/definition/create_model_pipeline.py, components/aws/sagemaker/tests/integration_tests/resources/definition/hpo_pipeline.py, components/aws/sagemaker/tests/integration_tests/resources/definition/training_pipeline.py, components/aws/sagemaker/tests/integration_tests/resources/definition/transform_job_pipeline.py, components/aws/sagemaker/tests/integration_tests/scripts/generate_iam_role, components/aws/sagemaker/tests/integration_tests/scripts/generate_trust_policy, components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Added the appropriate scripts to automate the deployment of our integration tests within CodeBuild.
- Spin up EKS and install OIDC
- Install KFP 
- Run PyTest with the appropriate parameters
I am still writing up a guide on how to run these integration tests within the container environment. This should unblock our CI for the moment, though.
=> [AWS SageMaker] Integration tests automation

frontend/src/components/viewers/ConfusionMatrix.tsx, frontend/src/components/viewers/__snapshots__/ConfusionMatrix.test.tsx.snap, frontend/src/lib/OutputArtifactLoader.test.ts, frontend/src/lib/OutputArtifactLoader.ts
Fixes https://github.com/kubeflow/pipelines/issues/3733
/area frontend
/kind bug
Note that the number for (target=NONE, predicted=ACTION) changed, with the bug it was 855, but after the fix it is 195.
195 is correct corresponding to schema and data:
```
// schema
{
"outputs": [
{
"labels": ["NONE", "ACTION"],
"source": "gs://gongyuan-test/fb13d79c-28b2-443e-96e2-30f9a7919dbb/data/confusion_matrix.csv",
"schema": [
{"type": "CATEGORY", "name": "target"},
{"type": "CATEGORY", "name": "predicted"},
{"type": "NUMBER", "name": "count"}
],
"type": "confusion_matrix", "format": "csv"
}
]}
// data
NONE,NONE,3800
NONE,ACTION,195
ACTION,NONE,855
ACTION,ACTION,1659
```
bug:
after fix:
Implementation:
The fix changed confusion matrix to be in a more conventional representation, with NONE labels from …
=> [UI] Fix confusion matrix wrong axes

frontend/global-setup.js, frontend/package.json, frontend/src/components/Trigger.test.tsx, frontend/src/components/Trigger.tsx, frontend/src/components/__snapshots__/Trigger.test.tsx.snap, frontend/src/lib/TriggerUtils.test.ts, frontend/src/lib/TriggerUtils.ts, frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Fixes #3761
/area frontend
/kind feature
Cloning schedule of recurring run wasn't implemented in UI, this PR implemented it.
I tried cloning two recurring runs in UI. They are the same as cloned one except for creation date.
when user uses cron schedule, current implementation only clones the cron expression, but cannot parse it to meaning like "once a day", it might confuse users on the option, but the cron expression is in fact the same as cloned one.
=> [UI] Also cloning recurring run schedule, fixes #3761

.travis.yml
TFX package is has inconsistent dependencies which causes the installation to be flaky and install different numpy version every time leading to failures.
=> Testing - Pin numpy version to fix TFX installation instability in Travis tests

components/aws/sagemaker/batch_transform/src/batch_transform.py, components/aws/sagemaker/common/_utils.py, components/aws/sagemaker/deploy/src/deploy.py, components/aws/sagemaker/ground_truth/src/ground_truth.py, components/aws/sagemaker/model/src/create_model.py, components/aws/sagemaker/tests/unit_tests/tests/test_batch_transform.py, components/aws/sagemaker/tests/unit_tests/tests/test_deploy.py, components/aws/sagemaker/tests/unit_tests/tests/test_ground_truth.py, components/aws/sagemaker/tests/unit_tests/tests/test_hpo.py, components/aws/sagemaker/tests/unit_tests/tests/test_model.py, components/aws/sagemaker/tests/unit_tests/tests/test_train.py, components/aws/sagemaker/tests/unit_tests/tests/test_workteam.py, components/aws/sagemaker/workteam/src/workteam.py
Added more tests for following components :
Deploy            (98% coverage)
Ground_truth  (98% coverage)
Workteam (96% coverage)
Model (97% coverage)
Batch Transform (98% coverage)
https://github.com/kubeflow/pipelines/issues/3782
```
====================================================================================== 94 passed, 3 warnings in 1.67s ======================================================================================
Name                                                      Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------------------
/app/batch_transform/src/batch_transform.py                  51      1    98%   75
/app/common/_utils.py                                       567     31    95%   62, 73-83, 88-92, …
```
=> [AWS SageMaker] Add more unit tests

.travis.yml
Add Argo CLI so that the validation introduced in #3094 is triggered.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/3123)
=> Testing - Using Argo validation in Travis tests

components/kubeflow/kfserving/Dockerfile, components/kubeflow/kfserving/component.yaml, components/kubeflow/kfserving/src/app.py, components/kubeflow/kfserving/src/kfservingdeployer.py
This PR adds the option to add an existing `service_account` to `V1alpha2PredictorSpec` when using the Kfserving pipeline component.  This is needed if you for example would like to fetch serialised models from s3 using aws credentials.
=> Kfserving component service account option

components/aws/sagemaker/tests/integration_tests/utils/kfp_client_utils.py
```
Integ test failure message 
else:
--
233 | time.sleep(timeout)
234 | response = client.get_run(run_id)
235 | >           status = response.run.status.lower() == status_to_check
236 | E           AttributeError: 'NoneType' object has no attribute 'lower'
```
=> fixing case when status is None

frontend/src/components/ArtifactLink.tsx, frontend/src/lib/Utils.test.ts, frontend/src/lib/Utils.tsx
This is a follow up PR of #3530, resolves some issues of #3405 
We need to have this PR to generate clickable artifact url for s3 URI. 
It's working now. Click link will automatically download file. (we may consider to redirect user to AWS S3 console later, this is good enough now.)
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
/cc @eterna2 @Ark-kun @Bobgy @gautamkmr
=> Generate clickable artifact url for s3 URI

backend/src/apiserver/server/util.go, backend/src/apiserver/server/util_test.go
---
Fixes #3752
The backend incorrectly parses the contents of the `KUBEFLOW_USERID_HEADER`.
Moreover, it totally ignores `KUBEFLOW_USERID_PREFIX`.
Currently, the backend gets the header, splits it on `:` and gets the 2nd element of the result.
The author of this part of code must have been carried away by google headers which look like this:
```
x-goog-authenticated-user-email: accounts.google.com:user
```
However, this is leads to errors for different values of the environment variables. For example:
```
KUBEFLOW_USERID_HEADER = "kubeflow-userid"
KUBEFLOW_USERID_PREFIX = "prefix"
```
In this case, the header should look like this:
```
kubeflow-userid: prefixuser
```
but the apiserver will raise errors.
This PR fixes this issue.
=> [Backend] Fix user identity extraction logic in getUserIdentity()

sdk/python/kfp/components/_data_passing.py, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
Otherwise serialization of the default values of the component/pipeline inputs is unstable on Python 3.5.
This will fix https://github.com/kubeflow/pipelines/pull/3832 failure on python3.5.
=> SDK - Components - Stabilize JSON serialization by sorting keys

sdk/python/kfp/_client.py
Maybe fixes https://github.com/kubeflow/pipelines/issues/3835#issuecomment-635195462
=> SDK - Client - Use temporary directory context for pipeline package

backend/src/apiserver/server/pipeline_server.go, backend/src/apiserver/server/pipeline_server_test.go
Invoke CreatePipeline always get an empty description. This is because the passing input parameter is not used and empty string is always passed in
=> Fix the missing description in the CreatePipelineAPI

components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_create_job.py, components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_train.py, components/gcp/container/component_sdk/python/tests/google/ml_engine/test__create_job.py, components/gcp/container/component_sdk/python/tests/google/ml_engine/test__train.py, components/gcp/ml_engine/train/README.md, components/gcp/ml_engine/train/component.yaml, components/gcp/ml_engine/train/sample.ipynb
Adds job_id parameter to ml_engine train component.
- job_id parameter takes precedence over job_id_prefix when defined.
- When set, job_id is known before task creation and can be consumed by other tasks while running.
- Does not interfere with current job_id_prefix when unset to avoid breaking pipelines which depend on it.
- Does _not_ modify for predict jobs which use the same pattern.
=> Adds job_id parameter.

components/aws/sagemaker/tests/integration_tests/component_tests/test_workteam_component.py
If minio artifact download fails the workteam is not being deleted.
=> Move the minio artifact download under try block

backend/api/experiment.proto, backend/api/job.proto, backend/api/pipeline.proto, backend/api/run.proto, sdk/python/kfp/_client.py
Fix typo in various proto file comments and `_client.py`.
There were a number of other auto-generated files with the typo as well.  I'm assuming don't need to fix any of those, but LMK if I missed something.
The ones I skipped included the files in `backend/api/swagger`, `frontend/src/apis/..*.ts`, and `backend/api/go_http_client`.
Addresses https://github.com/kubeflow/website/issues/1941 .
=> fix typo on sort order: 'des' --> 'desc'

components/third_party_licenses.csv
Error message in cloudbuild
```
--2020-06-04 02:47:51--  https://raw.githubusercontent.com/jquast/wcwidth/master/LICENSE.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-04 02:47:51 ERROR 404: Not Found.
```
=> [Testing] Fix build failure because wcwidth LICENSE url changed

backend/api/build_kfp_server_api_python_package.sh, backend/api/generate_api.sh, hack/check-release-needed-tools.sh, hack/check-tools-installed.sh, hack/release-imp.sh, hack/release.sh
Part of https://github.com/kubeflow/pipelines/issues/3729
api clients need version update, so we regenerate them on release
some scripting convention shift:
* instead of letting each script get a version passed in, scripts should read from repo root's VERSION file, because config value driven seems easier to manage, so when running each script, we don't need to pass in any parameters. @rmgogogo Thanks for the suggestion before, I think this is a good idea!
=> [Release] Regenerate api clients on release

sdk/python/kfp/components/_component_store.py, sdk/python/kfp/components/_key_value_store.py
ComponentStore(...).search searches for components by name in the configured component store. It prints the name and URL for components that match the given name.
Only components on GitHub are currently supported.
Example:
```
kfp.components.ComponentStore.default_store.search('xgboost')
>>> Xgboost train   https://raw.githubusercontent.com/.../components/XGBoost/Train/component.yaml
>>> Xgboost predict https://raw.githubusercontent.com/.../components/XGBoost/Predict/component.yaml
```
The `default_store` is configured with the main KFP component repo. The users can customize the store with their own repos and URL prefixes:
```
my_store = ComponentStore(
url_search_prefixes=[
'https://raw.githubusercontent.com/Ark-kun/kfp_components/master/components/', …
```
=> SDK - Components - Added ComponentStore search

.cloudbuild.yaml
I made a mistake in https://github.com/kubeflow/pipelines/pull/3921.
`$(cat /workspace/VERSION)` cannot be used in arguments, it has to be part of a bash script.
=> [Release] Fix $(cat VERSION) not in bash script

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/components/_data_passing.py
Fixes https://github.com/kubeflow/pipelines/issues/2534
Fixes https://github.com/kubeflow/pipelines/issues/2825
Fixes https://github.com/kubeflow/pipelines/issues/2840
Fixes https://github.com/kubeflow/pipelines/issues/3806
=> SDK - Compiler - Using properly serialized pipeline parameter defaults

sdk/python/kfp/compiler/_default_transformers.py
Only 63 chars are allowed. Previously the length was 64.
=> [SDK] Fixes the length of component digest label

sdk/python/kfp/dsl/_pipeline.py, sdk/python/kfp/onprem.py
Refer to #3906 
This PR fix the transform `mount_pvc` to only mount the PVC to ContainerOps only.
**Rationale-for-fix**
- instead of modifying `apply_op_transformer`  to only pass in ContainerOp, we should retain flexibility to modify any ops inside a pipeline. 
The implication is that dev will need to note that `apply_op_transformer` can pass in ResourceOp, VolumeOp, and ContainerOp. They will need to check the op and apply the transform appropriately.
I have also update the doc string for `apply_op_transformer` to reflect the change.
=> Fix #3906 - mount_pvc transform should ignore non-ContainerOps

backend/src/apiserver/model/BUILD.bazel, backend/src/apiserver/model/run.go, backend/src/apiserver/model/run_test.go
By supporting filter on the status of run (i.e., conditions field in our db), uses can list runs of particular status via our SDK. E.g.
import kfp
import json
client=kfp.Client(<host address>)
filter = json.dumps({'predicates': [{'key': 'status', 'op': 1, 'string_value': 'Succeeded'}]})
client.runs.list_runs(filter=filter)
Will give you all the runs with status being 'succeeded'.
Manual test with our sdk and local api server image using the above code snippet.
related: https://github.com/kubeflow/pipelines/issues/3591
=> [Backend] Filter run on status

components/aws/sagemaker/tests/integration_tests/resources/config/image-classification-groundtruth/config.yaml
Update the timeout for the GroundTruth integration test from 10 seconds to 1200 seconds.
=> [AWS SageMaker] Update GroundTruth integration test timeout

components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_client.py
Fix for https://github.com/kubeflow/pipelines/issues/3801. Updated client to use the in order to support more regions the component should switch to the projects.locations.templates API endpoint instead of the projects.templates endpoint it uses currently.
This is based upon the suggestion from @DennisVis
The project.locations.templates API is described [here](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.templates/launch).
=> Update Dataflow component _client.py to use projects.locations.templates API endpoint

backend/src/apiserver/common/config.go, backend/src/apiserver/server/experiment_server.go, backend/src/apiserver/server/job_server.go, backend/src/apiserver/server/run_server.go
In multi-user mode, allow read access to experiments/runs/jobs under flag MULTIUSER_SHARED_READ.
Manually verified in my dev cluster with image:
gcr.io/chesu-dev/api-server@sha256:91ece58a98ffe0f0796688ae2a593c5e2317e57d5037f93114978ce29aca943a
/assign @Bobgy @IronPan
=> [Backend][Mutli-user] Allow shared read in the special multi-user mode.

backend/src/cache/deployer/deploy-cache-service.sh
Fixes https://github.com/kubeflow/pipelines/issues/3815
=> Cache - Deployer should check whether the secret is installed

sdk/python/kfp/_client.py
Fixes #3630 
Synced with @chensun , we only need this refresh for inverse proxy style authentication because `gcloud auth print-access-token` has a 1 hour TTL while in `_get_auth_token()` we're using refresh token, which does not have such limit.
=> [SDK/client] Fixes authentication refreshing mechanism

backend/metadata_writer/src/metadata_helpers.py
We can finally move away from artifact properties to custom properties.
Fixes https://github.com/kubeflow/pipelines/issues/4001
=> Metadata Writer - Stopped using artifact properties

.style.yapf
Made the style config simpler and closer to the official [Google style guide](http://google.github.io/styleguide/pyguide.html). Here is the `google` preset:
https://github.com/google/yapf/blob/c4257ed87ce22311fe8f3c5e1fa3ea8e43579f82/yapf/yapflib/style.py#L416
P.S. Just found this old branch and decided to make a PR and cleanup the branch.
=> SDK - Simplified the style config

frontend/mock-backend/tsconfig.json
Refer to  #3980
This PR fix the tsconfig for the mockapi server to correctly reference the correct folder. 
I also note that there is inconsistency in the relative module import. Should we be using `../..` or `src/**/*`?
There is a mix, where majority follows the `../..` convention.
=> Fix #3980 - mockapi tsconfig should reference root dir correctly

components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py
Fix broken HPO component by including missing `sys` import
=> [AWS SageMaker] Add missing import statement

README.md
Looks like kfp stopped using the .org version ~1 year ago. Clicked on this link to get a sense for how the tests were running but took me to the incorrect link!
=> Update travis CI status badge to use .com version instead of outdated .org version

sdk/python/kfp/cli/run.py
When using command `kfp run submit`, we have to provide package_file or pipeline_id option.
But when using an existing pipeline with a specific version like 
`kfp run submit -p <pipeline_id> -e <experiment> -r <name> -w -v <version_id>
`
the version is being ignored because of the pipeline ID. So there is no way to run a specific pipeline version.
As said in _client.py **_create_job_config** function : 
>       version_id: The string ID of a pipeline version. 
>         If both pipeline_id and version_id are specified, pipeline_id will take precendence
>         This will change in a future version, so it is recommended to use version_id by itself.
which is inconsistent with **run_pipeline** function by the way which says 
> version_id will take precendence
So we should allow only version …
=> SDK/CLI: Allow to use version properly with kfp run submit

docs/source/kfp.dsl.rst
Previously many ContainerOp members inherited from baseOp were not shown.
=> Docs - Show inherited members in the kfp.dsl docs

.github/pull_request_template.md
better explanation on resolves issue syntax in PR template
**Checklist:**
- Do you want this PR cherry picked to release branch?
If yes, please either
* ask the approver to add label `cherrypick-approved`, so that release manager
will handle it in batch
* or create a cherry pick PR to the release branch after this PR is merged
(You can refer to [RELEASE.md](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option---git-cherry-pick) for how to do it.)
=> chore: recommend cherrypick-approved label in PR template

.github/pull_request_template.md
improve writing for cherry pick process
per suggestion by @joeliedtke in https://github.com/kubeflow/pipelines/pull/4029
**Checklist:**
If yes, please either
* (recommended) ask the approver to add label `cherrypick-approved`, so that release manager
will handle it in batch
* or create a cherry pick PR to the release branch after this PR is merged
(You can refer to [RELEASE.md](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option---git-cherry-pick) for how to do it.)
=> chore: improve writing for cherry pick process

.github/stale.yml
Set up stale bot to let us focus on important issues people continually care about. 
The configuration is copied from kubeflow repo: https://github.com/kubeflow/kubeflow/blob/master/.github/stale.yml.
Permissions for the bot has already been enabled for kubeflow organization, so I think we just need to add this config to let it start working.
**Checklist:**
If yes, please either
* (recommended) ask the approver to add label `cherrypick-approved`, so that release manager
will handle it in batch
* or create a cherry pick PR to the release branch after this PR is merged
(You can refer to [RELEASE.md](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option---git-cherry-pick) for how to do it.)
=> chore: set up stale bot to focus on important issues

.release.cloudbuild.yaml, manifests/kustomize/base/kustomization.yaml, manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml, test/cloudbuild/batch_build.yaml, test/deploy-pipeline-lite.sh
Metadata envoy image was built in every build but only release for marketplace. This change releases metadata-envoy image for OSS also in each release.
=> MetadataStore: Update to release metadata-envoy in each release

backend/README.md
Update the readme with the Bazel version since it don't work with the latest versions. See this issue for more info: https://github.com/kubeflow/pipelines/issues/3942
=> Docs - Mention the Bazel version requirements in the README.md

backend/src/apiserver/server/pipeline_server.go, backend/src/apiserver/server/pipeline_server_test.go
Pipeline API server panics when resourcekey is missing in the input. Adding validation to prevent the panic from happenning
=> Validate resourcekey to prevent apiserver being panic for invalid inputs

sdk/python/kfp/components_tests/test_components.py
Removed path resolving in two tests.
The `.resolve()` should be harmless, but I've seen these tests fail to work in some unusual strict hermetic systems. The test code file path was resolving to a tree which was different from the parent of the file, so the test could not find the test data.
=> SDK - Tests - Fixed two test failures in hermetic systems

sdk/python/kfp/components/_python_op.py, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
Previously the default image was set to an old version of tensorflow image. That image is now outdated. It's also framework-specific and pretty big.
We're switching to the official python image which is small, official and framework-agnostic.
The users can easily switch to the old behavior by just specifying `base_image='tensorflow/tensorflow:1.13.2-py3'` during the component creation.
This also allows us to use the image corresponding to the current python environment. This makes code pickling significantly safer.
Fixes https://github.com/kubeflow/pipelines/issues/4041
Closes: https://github.com/kubeflow/pipelines/issues/4062
=> SDK - Components - Python - Switched the default base image to python 3.7

sdk/python/kfp/compiler/_data_passing_using_volume.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/kfp/dsl/data_passing_methods.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/artifact_passing_using_volume.py, sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml, sdk/python/tests/compiler/testdata/test_data/consume_2.component.yaml, sdk/python/tests/compiler/testdata/test_data/process_2_2.component.yaml, sdk/python/tests/compiler/testdata/test_data/produce_2.component.yaml
Currently artifact passing is performed by Argo sidecar containers what download input data and upload output data to artifact repository (usually, S3-compatible blob storage like Minio).
The performance of this method is not optimal and it requires that pod disks have enough capacity to hold all artifact data.
This commit adds support for volume-based data passing.
This method involves using a single milti-write Kubernetes data volume to pass all intermediate data.
Parts of the volume are mounted to the input/output artifact directories, so when the user program reads and writes files, the files actually reside in the data volume.
This method improves the performance and reduces storage resource requirements.
The data volume must exist and support "READ_WRITE_MANY". (Or it can be an …
=> SDK - Compiler - Added support for volume-based data passing

manifests/kustomize/base/argo/kustomization.yaml, manifests/kustomize/base/argo/minio-artifact-secret.yaml, manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml, manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml, manifests/kustomize/env/gcp/minio-gcs-gateway/kustomization.yaml, manifests/kustomize/env/gcp/minio-gcs-gateway/minio-artifact-secret.env, manifests/kustomize/env/gcp/minio-gcs-gateway/minio-gcs-gateway-deployment.yaml, manifests/kustomize/env/platform-agnostic/minio/kustomization.yaml, manifests/kustomize/env/platform-agnostic/minio/minio-artifact-secret.env, manifests/kustomize/env/platform-agnostic/minio/minio-deployment.yaml
Use minio artifact secret as single source of truth, instead of putting default value of
accesskey=minio
accesssecret=minio123
everywhere.
**Verification:**
I searched for minio123, and it's now only occuring twice in kustomize manifests.
**Checklist:**
Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue …
=> refactor(deployment): use minio artifact secret as single source of truth

backend/src/apiserver/main.go, backend/src/apiserver/server/auth_server_test.go
Add a unit test and configure env var to take userid header prefix which can be an empty string.
Ref: https://godoc.org/github.com/spf13/viper#AllowEmptyEnv
Fixes https://github.com/kubeflow/pipelines/issues/4091
**Checklist:**
If yes, use one …
=> fix(backend): allow empty userid header prefix. Fixes #4091

components/ibm-components/watson/store/component.yaml, components/ibm-components/watson/train/component.yaml, components/ibm-components/watson/train/src/wml-train.py, samples/contrib/ibm-samples/watson/watson_train_serve_pipeline.py
Due to the security concern with TensorFlow 1.14, Watson ML has deprecated the support for it. Thus, changing the default TF version in the Watson ML example to 1.15. 
Reference: https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/pm_service_supported_frameworks.html
**Checklist:**
Use `part of` to indicate that a PR is working on …
=> Fix(component): Update default TensorFlow version for Watson ML example

sdk/python/kfp/_client.py
"The package_file '+ package_file + ' should ends with..." replaced by "The package_file '+ package_file + ' should end with..."
=> Fix typo in error message

components/kubeflow/kfserving/component.yaml, components/kubeflow/kfserving/src/kfservingdeployer.py
- Add a new `apply` action to kfserving component that can either create or patch the inferenceService. 
- Update image tag to v0.3.0 to align with kfserving release
- Add one second sleep to avoid race condition on the watch api until the next release with the api fixes (https://github.com/kubeflow/kfserving/pull/889)
**Checklist:**
Use `part …
=> fix(component): Add new apply action to kfserving component

.cloudbuild.yaml, .release.cloudbuild.yaml, test/postsubmit-tests-with-pipeline-deployment.sh
Part of #4046 
Related cloudbuild documentation: https://cloud.google.com/cloud-build/docs/view-build-results#gcloud.
Note that `sourceProvenance.resolvedRepoSource.commitSha` isn't available in Github App Trigger triggered cloudbuild tasks, that's strange, but we can first work around that by querying `substitutions.COMMIT_SHA`.
**Checklist:** …
=> test: postsubmit - fix cloudbuild job filtering. Part of #4046

sdk/python/kfp/components_tests/test_components.py
=> test(sdk): Components tests - Made test_load_component_from_url hermetic

sdk/python/kfp/components/_python_to_graph_component.py
=> fix(sdk): SDK - Components - Fixed the error message format string

backend/src/cache/deployer/deploy-cache-service.sh
I deleted kubeflow namespace, then reinstalled KFP 1.0.0-rc.4.
I found my cache-server cannot mount the tls secret.
After reading cache deployer code, the root cause seems to be a typo as fixed in the PR.
**Checklist:**
If yes, use one of the …
=> fix(cache): Fix cache deployer not regenerating secrets when secret not present

sdk/python/kfp/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py
Fixes https://github.com/kubeflow/pipelines/issues/4110
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch …
=> fix(sdk): Compiler - Fixed input artifact name sanitization when using raw string arguments. Fixes #4110

sdk/python/kfp/dsl/__init__.py, sdk/python/kfp/dsl/_component_bridge.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/dsl/component_bridge_tests.py
We have long advised our users to create reusable components.
Creating reusable components is as easy as creating ContainerOp instances, but the components are shareable, portable and are easier to support going forward.
=> feat(sdk): SDK - Deprecation warning when using ContainerOp

components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Fixes a bug where if the MinIO PID was not defined the script would exit early with `unbound variable: ${MINIO_PID}`. Instead, now, we default the variable to an empty string in the case it isn't defined.
**Checklist:**
If yes, use one of the …
=> fix(components): AWS SageMaker - Fix MinIO PID early exit

components/aws/sagemaker/Changelog.md, components/aws/sagemaker/THIRD-PARTY-LICENSES.txt, components/aws/sagemaker/batch_transform/component.yaml, components/aws/sagemaker/common/_utils.py, components/aws/sagemaker/deploy/component.yaml, components/aws/sagemaker/ground_truth/component.yaml, components/aws/sagemaker/hyperparameter_tuning/component.yaml, components/aws/sagemaker/model/component.yaml, components/aws/sagemaker/process/component.yaml, components/aws/sagemaker/tests/integration_tests/component_tests/test_batch_transform_component.py, components/aws/sagemaker/tests/integration_tests/component_tests/test_processing_component.py, components/aws/sagemaker/tests/integration_tests/component_tests/test_train_component.py, components/aws/sagemaker/tests/integration_tests/utils/argo_utils.py, components/aws/sagemaker/train/component.yaml, components/aws/sagemaker/workteam/component.yaml
Integration test checks if there is any error in fetching logs
=> [AWS SageMaker] Integ test to check CloudWatch logs print feature

contrib/samples/openvino/deployer/component.yaml
I was running some analysis on all sample components in KFP repo, and discovered that this one has some syntax error preventing correct parsing.
**Checklist:**
* **(Recommended.)** Ask the PR approver …
=> fix(sample): Fix syntax error in openvino sample component

sdk/python/kfp/compiler/compiler.py
Fixes https://github.com/kubeflow/pipelines/issues/3859
=> SDK - Compiler - Validating Argo validator

sdk/python/kfp/components/_structures.py
This allows the component authors to add custom annotation to particular component inputs or outputs.
For example, they can use the annotations to specify the data schema for structured data.
It's might also be a place to set other per-input information.
=> feat(sdk): SDK - Components - Added annotations to InputSpec and OutputSpec

sdk/python/kfp/components/_structures.py
This allows the pipeline authors to add custom annotations to particular tasks.
Annotations
You can use annotations to attach arbitrary metadata to the task objects. Clients such as tools and libraries can retrieve this metadata.
For example, they can use the annotations to differentiate between the main model training task and  the auxiliary CV training tasks.
It's might also be a place to set other per-task information like the task display name for the UX.
We've had several users requesting the ability to tag tasks and the annotations provide a way to do so.
This feature is expected to mostly be used by external tools, so there are no needed changes in the backend or frontend.
=> feat(sdk): SDK - Components - Added annotations to TaskSpec

components/gcp/container/component_sdk/python/tox.ini, test/presubmit-components-gcp.sh
=> test: Added presubmit unit tests for the GCP components

.travis.yml
Deep dove onto why the TFX pipeline tests were failing for the KFP SDK, see [this build](https://travis-ci.com/github/kubeflow/pipelines/jobs/360913188). Looks like it was because of an intermittent bug with `pip`, see [here](https://github.com/pypa/pip/issues/8583).
**tl;dr** on the upstream `pip` bug, if an existing version of a package is installed (in KFP SDK case, `google-auth==1.11.3`) then when a package (in our case `google-python-api-client==1.9.3`) is installed and it contains overlapping transitive dependency ranges on `google-auth` (from `kubernetes==11.0.0` we have `google-auth>=1.0.1`, see [here](https://github.com/kubernetes-client/python/blob/v11.0.0/requirements.txt), and from `google-api-core==1.21.0` we have …
=> test: Fix KFP SDK TFX tests by specifying transitive dependency to resolve google-auth mismatch

backend/src/apiserver/server/visualization_server.go, backend/src/apiserver/server/visualization_server_test.go
Fixes #4157 
When visualization server is not accessible, the error message only mentions: `Service not available`, this doesn't provide enough context and information for users/developers to debug.
When visualization server is not accessible, the error message is: `visualization server is not responsible`, which provides more information and context. 
`bazel test //backend/src/apiserver/server:go_default_test --test_filter=TestListRuns_Pagination --test_output=all`
**Checklist:**
* `chore: set up changelog …
=> fix(backend): fixes useless error message when visualization-server is not accessible. Fixes #4157

manifests/kustomize/base/pipeline/kustomization.yaml, manifests/kustomize/base/pipeline/ml-pipeline-ui-configmap.yaml, manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml, manifests/kustomize/base/pipeline/viewer-sa.yaml, manifests/kustomize/gcp-workload-identity-setup.sh, manifests/kustomize/sample/README.md, test/deploy-pipeline-lite.sh
Changes:
* workload identity setup script can be run both before and after deployment now because it creates KSAs if they don't exist
* added detailed instructions, including permission requirements for different KFP services
* gave tensorboard viewer its dedicated KSA, so we don't need to bind default KSA.
**Checklist:**
=> feat(deployment): GCP managed storage - detailed instructions to set up workload identity bindings before deployment

samples/contrib/aws-samples/README.md, samples/contrib/aws-samples/mnist-kmeans-sagemaker/README.md, samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
- Minimize inputs for mnist classification pipeline - remove unused inputs and inputs with default values for better user experience
- Bug fixes
- To processing component, current pipeline on master fails at batch transform
- Script used for prediction had missing imports and reference to dataset section which is not present anymore
- Updates to documentation and fixes
- Made s3 bucket as runtime input rather than compile time - easy for customer and to add integration tests
**Testing**
Manual
=> feat(components): [AWS SageMaker] Minimize inputs for mnist classification pipeline

sdk/python/requirements.txt
I've fixed the OpenAPI documentation generation and @Bobgy has generated the improved `kfp-server-api` package. However the documentation hasn't changed on the docs website since the `requirements.txt` was still pinning the old version.
P.S. The kfp-server-api dependency wasn't updated in https://github.com/kubeflow/pipelines/pull/3918/ and https://github.com/kubeflow/pipelines/pull/3566 We might want to add rules to require updating `requirements.in` and `requirements.txt` when changing the dependencies.
=> doc(sdk): Fixed documentation by updating the kfp-server-api dependency

frontend/server/app.ts, frontend/server/consts.ts, frontend/server/handlers/artifacts.ts, frontend/server/proxy-middleware.ts
When trying out multi user mode for Kubeflow 1.1. After the cluster is up and running for a while, suddenly all big enough ui proxy requests fail with error proxying with partial data. I suspected some behavior changed for Anthos Service Mesh (istio), because I tried removing all istio sidecars, the error doesn't show up.
However, I tried troubleshooting for a while and found this hack solution from https://github.com/chimurai/http-proxy-middleware/issues/171#issuecomment-439020716, it worked perfectly to my surprise.
Checking this in first to unblock Kubeflow 1.1 GCP release.
**Checklist:**
* `feat(backend): configurable service account. …
=> fix: all big enough ui proxy requests fail with error proxying with partial data

manifests/kustomize/base/argo/workflow-controller-configmap.yaml, manifests/kustomize/base/kustomization.yaml, manifests/kustomize/base/params.env, manifests/kustomize/env/platform-agnostic-pns/kustomization.yaml, manifests/kustomize/env/platform-agnostic-pns/params.env
Add `containerRuntimeExecutor` explicit type on `workflow-controller-configmap.yaml` configuration.  
`docker` is the default.
platform-agnostic-pns type configuration needed by Kind, K3s and Minikube.
Part of https://github.com/kubeflow/pipelines/issues/4256
Related to: https://github.com/kubeflow/website/pull/2056
**Checklist:**
* `feat(deployment): configurable containerRuntimeExecutor` fixes (part of) https://github.com/kubeflow/pipelines/issues/4256
example new PNS feature:
```
kubectl kustomize  manifests/kustomize/env/platform-agnostic-pns | grep containerRuntimeExecutor -A 5
containerRuntimeExecutor: pns
dbHost: mysql
dbPort: "3306"
mlmdDb: metadb
pipelineDb: mlpipeline
kind: ConfigMap
--
containerRuntimeExecutor: pns, …
```
=> feat(deployment): Add env/platform-agnostic-pns standalone deployment option

backend/build_api_server.sh
Fix empty space on the script, it could raise an error when using
different shell as zsh.
Just a typo on the shell script.
**Checklist:**
=> chore(backend): fixes typo empty space

sdk/python/kfp/_client.py
Updated `Client.get_pipeline_id()` to return `None` when no pipeline with provided name exists.
**Checklist:**
- [] Do you want this pull request (PR) cherry-picked into the current release branch?
* …
=> fix(sdk): TypeError in Client.get_pipeline_id() when pipeline does not exist

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml, manifests/kustomize/base/pipeline-application.yaml
KFP standalone should keep user data when application deleted.
There's currently a behavior difference when deleting KFP application from https://cloud.console.google.com/ai-platform/pipelines/clusters.
If AI Platform Pipelines is deleted, it keeps data in the cluster.
If KFP standalone is deleted, it deletes data too (non recoverable because underlying GCE persistent disk is auto deleted too). This behavior is very dangerous to me, especially when we document to users they should delete AI Platform Pipelines instance to upgrade.
**Checklist:**
=> feat(deployment): KFP standalone should keep user data when application deleted

backend/src/agent/persistence/client/pipeline_client_fake.go, backend/src/agent/persistence/worker/metrics_reporter.go, backend/src/agent/persistence/worker/metrics_reporter_test.go
Fixes https://github.com/kubeflow/pipelines/issues/3699
Changes:
* persistence agent only reads metrics artifact when it can find the output artifact in workflow status, so api server will not receive so many ReadArtifact requests that will fail for sure.
Manual Verification:
I deployed the persistence agent image: gcr.io/ml-pipeline-test/112bdfa56ddb54dbc05499d51ba6386362838459/persistenceagent@sha256:bc95106ebc84292652abb41b0088fa55a9b11dd3e6939d70c81b8ba64105568d on my cluster and verified running a few pipelines.
I can no longer see the confusing error messages while metrics are still reported properly.
**Checklist:**
=> fix(backend): reduce confusing ReadArtifact errors for metrics in api server. Fixes #3699

components/aws/emr/common/_utils.py
Remove needless arguments from submit_pyspark_job
Currently, submit_pyspark_job sends needless arguments to the EMR. 
We were trying to use this function but in `controller` EMR logs it produced output like that: 
```
2020-07-14T07:15:19.695Z INFO Ensure step 4 jar file command-runner.jar
2020-07-14T07:15:19.695Z INFO StepRunner: Created Runner for step 4
INFO startExec 'hadoop jar /var/lib/aws/emr/step-runner/hadoop-jars/command-runner.jar spark-submit --deploy-mode cluster command-runner.jar spark-submit s3://<redacted>/wordCount.py s3://<redacted>/word_excerpt.txt s3://<redacted>/output_wc.txt'
```
As you can see, there is multiple occurrence of 'command-runner.jar' and 'spark-submit'. 
**Checklist:**
* `fix(frontend): fixes empty …
=> fix(components): remove needless arguments from AWS EMR scripts

manifests/kustomize/README.md, manifests/kustomize/env/aws/OWNERS, manifests/kustomize/env/aws/README.md, manifests/kustomize/env/aws/aws-configuration-patch.yaml, manifests/kustomize/env/aws/config, manifests/kustomize/env/aws/kustomization.yaml, manifests/kustomize/env/aws/minio-artifact-secret-patch.env, manifests/kustomize/env/aws/params.env, manifests/kustomize/env/aws/secret.env, manifests/kustomize/env/aws/viewer-pod-template.json
Adopt standalone KFP solution on AWS by replacing `minio` with `S3` and `mysql` with `RDS`.
Fix #4337 
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to …
=> feat(manifest): add support for Standalone KFP on AWS. Fixes #4337

manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-clusterrole.yaml
Release - Back-port #4246 to master
The https://github.com/kubeflow/pipelines/pull/4246 PR has been merged to the release-1.0 branch instead of master. This commit fixes that
=> fix(cache): adds certificate approver permission to kubeflow-pipelines-cache-deployer-role. Fixes #4138 (#4246)

sdk/python/kfp/aws.py, sdk/python/tests/dsl/aws_extensions_tests.py
`use_aws_secret` didn't consider `AWS_REGION`, depends on the AWS SDK version and services to requests, some of the applications needs `AWS_REGION` to finish request. One example is Tensorflow. 
This PR adds an extra optional field `aws_region` in  `use_aws_secret` util for user who need it. 
**Checklist:**
Use `part of` to indicate that a PR …
=> feat(sdk): add aws region field in use_aws_secret in kfp sdk

components/kubeflow/dnntrainer/Dockerfile
Currently the build starts with python3-based tensorflow image, but then installs python2 and  all the packages.
This PR stops installing and using python2.
This change speeds-up the build significantly
=> fix(components): Simplified the build of the kubeflow - dnntrainer component. Fixes #4416

sdk/python/kfp/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/opsgroups.py, sdk/python/tests/compiler/testdata/opsgroups.yaml
There is a bug in the `Compiler` class when it resolves dependencies for `Op`s and `OpsGroup`s. The nature of this bug is the following: when a dependency is an `OpsGroup`, compiler fails with an uncaught exception because it tries to access the wrong variable. This diff fixes this bug by changing the variable to access.
[This gist](https://gist.github.com/sabiroid/08bb7d8e5a413f7d465bbb119df5449c) surfaces the bug and proves the fix:
* With the fix execution of [example.py](https://gist.github.com/sabiroid/08bb7d8e5a413f7d465bbb119df5449c#file-example-py) succeeds and produces a [correct yaml file](https://gist.github.com/sabiroid/08bb7d8e5a413f7d465bbb119df5449c#file-example-py-yaml).
* Without the fix the execution results in the [AttributeError …
=> fix(sdk): Fix opsgroups dependency resolution

backend/src/cache/deployer/cache-configmap.yaml.template
Reduced the timeout from 30 seconds to 5.
This should not be needed as most users tell us that pods work even when the cache service is not available. But there was at least one customer who experienced timeout failures when creating pods after the service was deleted, but not the webhook config.
=> fix(backend): Caching - Reduced the cache webhook timeout

backend/test/integration/job_api_test.go, backend/test/integration/upgrade_test.go
We list by created_at time, but its precision is 1 second.
Fixes #4419
=> test(backend): fix TestJobApis test is flaky. Fixes #4419

backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go
Fixes #4389 (partially).
When the workflow manifest file is deleted from s3 due to the retention policy, we were
getting this segmentation fault in the next createRun attempt for that pipeline:
```
I0831 06:36:53.916141       1 interceptor.go:29] /api.RunService/CreateRun handler starting
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x156e140]
goroutine 183 [running]:
github.com/kubeflow/pipelines/backend/src/common/util.(*Workflow).VerifyParameters(0xc000010610, 0xc00036b6b0, 0x0, 0xc00036b6b0)
backend/src/common/util/workflow.go:66 +0x90
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).CreateRun(0xc00088b5e0, 0xc00088b880, 0xc0009c3c50, 0xc000010450, 0x1) …
```
=> fix(backend): prevent seg fault if workflow manifest is deleted. Fixes #4389

backend/src/apiserver/main.go
The `MaxCallRecvMsgSize` of the backend gRPC server is [2GB](https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/main.go#L93)
But the `MaxCallRecvMsgSize` of its proxy server is not specified. So the default value has been set to [4MB](https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/main.go#L157)
So I have faced a problem that following codes don't work.
```python3
configuration = kfp_server_api.Configuration(
host = HOST
)
with kfp_server_api.ApiClient(configuration) as api_client:
api_instance = kfp_server_api.RunServiceApi(api_client)
api_response = api_instance.read_artifact(
run_id=RUN_ID,
node_id=NODE_ID,
artifact_name=ARTIFACT_NAME
)
```
The error message:
```
File …
```
=> fix(backend): add `MaxCallRecvMsgSize(math.MaxInt32)` to proxy server

backend/src/agent/persistence/worker/persistence_worker_test.go, backend/src/agent/persistence/worker/workflow_saver.go, backend/src/agent/persistence/worker/workflow_saver_test.go, backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go
Fixes #3584.
For clusters with existing native Argo Workflows, ml-pipeline logs were dirtied
with unneccessary stack traces due to "missing Run ID label" situation.
With this PR there will be no request to `apiserver` and we will have single line of info log in `persistenceagent` side with the Workflow name causing the situation.
It'll look like this:
```
time="2020-09-01T15:39:26Z" level=info msg="Skip syncing Workflow (workflow-20200901-05-10-7030-end2end): workflow does not have a Run ID label."
```
rather than:
```
I0831 22:52:48.218775       1 interceptor.go:29] /api.ReportService/ReportWorkflow handler starting
I0831 22:52:48.219095       1 error.go:218] Invalid input error: Workflow missing the Run ID label
github.com/kubeflow/pipelines/backend/src/common/util.NewInvalidInputError …
```
=> fix(backend): skip reporting native Argo workflows which do not have Run ID label. Fixes #3584

components/aws/sagemaker/tests/integration_tests/component_tests/test_deploy_component.py, components/aws/sagemaker/tests/integration_tests/component_tests/test_groundtruth_component.py, components/aws/sagemaker/tests/integration_tests/component_tests/test_workteam_component.py, components/aws/sagemaker/tests/integration_tests/environment.yml, components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests, components/aws/sagemaker/tests/integration_tests/utils/sagemaker_utils.py
These changes ensure that all `Create` tests run inside a `try/except/finally` loop. In case of any failure, this will delete any hanging resources - ensuring that we do not hit account limits in case of transient errors.
I have also updated the version of `pytest-xdist` to `2.1.0`, which supports custom markers. Previously our canaries were running the entire integration test suite. This version runs only the tests marked as canaries.
**Checklist:**
Use `chore` to …
=> chore(components): AWS SageMaker - Fix leaking resources

components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_batch_predict.py, components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_train.py, components/gcp/container/component_sdk/python/tests/google/ml_engine/test__train.py
Fixes https://github.com/kubeflow/pipelines/issues/4430
The issue was introduced in https://github.com/kubeflow/pipelines/pull/3850. That PR has added a new parameter in the middle of the the create_job function signature which can cause breaking changes as the parameter ordering changes.
=> fix(components): Fixed the GCP - ML Engine - Batch predict component. Fixes #4430

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml, manifests/kustomize/base/argo/workflow-controller-role.yaml
Add a permission to create events to argo-role.
The workflow-controller logs a message "Unable to create audit event: events is forbidden: User \"system:serviceaccount:kubeflow:argo\" cannot create resource \"events\" in API group \"\" in the namespace \"kubeflow\"" reason=WorkflowSucceeded" indicating that it fails to emit K8s events (https://github.com/argoproj/argo/issues/2274) 
This is a fix.
=> fix(backend): Add a permission to create events to argo-role

sdk/python/kfp/_client.py
Minor improvement to doc string of `create_run_from_pipeline_func ` and `create_run_from_pipeline_package`
**Checklist:**
* **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label …
=> chore: Corrects doc string of two client methods.

components/deprecated/dataflow/predict/component.yaml, components/deprecated/dataflow/tfdv/component.yaml, components/deprecated/dataflow/tfma/component.yaml, components/deprecated/dataflow/tft/component.yaml, components/deprecated/dataproc/analyze/src/analyze.py, components/deprecated/dataproc/base/Dockerfile, components/deprecated/dataproc/create_cluster/src/create_cluster.py, components/deprecated/dataproc/predict/src/predict.py, components/deprecated/dataproc/train/src/train.py, components/kubeflow/dnntrainer/component.yaml, components/kubeflow/dnntrainer/src/trainer/task.py, components/local/confusion_matrix/component.yaml, components/local/confusion_matrix/src/confusion_matrix.py, components/local/roc/component.yaml, components/local/roc/src/roc.py
Reverts kubeflow/pipelines#580
Hi @Ark-kun, I'm reverting this PR because component images do not have `pathlib` dep as discovered in https://github.com/kubeflow/pipelines/issues/4361#issuecomment-688662018.
Would you mind fixing it and resubmit the PR?
=> revert(components): refactor - De-hardcoded local output paths

backend/src/agent/persistence/client/pipeline_client.go, backend/src/apiserver/client/workflow_fake.go, backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go, backend/src/common/util/error.go
Fixes https://github.com/kubeflow/pipelines/issues/4484
> KFP API server should mark delete workflow not found errors as permanent, so persistence agent won't need to keep retrying them and can just drop outdated items from the queue.
The error happens only when persistence worker cannot update its work queue. The only reported case was caused by too many workflows in the cluster. The error messages are super long and recurring, so they make it impossible to find if there are other errors that caused persistence agent fail to GC workflows.
/area backend
=> fix(backend): persistence agent - workflow not found error should be a permanent error

manifests/kustomize/README.md, manifests/kustomize/env/aws/OWNERS, manifests/kustomize/env/aws/README.md, manifests/kustomize/env/aws/aws-configuration-patch.yaml, manifests/kustomize/env/aws/config, manifests/kustomize/env/aws/kustomization.yaml, manifests/kustomize/env/aws/minio-artifact-secret-patch.env, manifests/kustomize/env/aws/params.env, manifests/kustomize/env/aws/secret.env, manifests/kustomize/env/aws/viewer-pod-template.json
Part of #4361 
**Checklist:**
* …
=> chore(release): cherry pick #4350 to 1.0.1 release

.github/pull_request_template.md
The current PR template is kind of too long and starts to be distracting.
**CHANGES**:
* Included link to detailed instructions
* Commented inline explanations so that they don't show up in pull request body
=> chore: make Pull Request template conciser

sdk/python/kfp/cli/run.py
There are no any dependencies to argo in kfp python package.
However, kfp throws error when user tries to use it with `--watch` option.
```
root@caa4a6050d9b:/tmp# kfp --endpoint=$KUBEFLOW_DEV --iap-client-id=$KUBEFLOW_DEV_IAP run submit --watch --pipeline-id 882da26c-0685-4ebd-b844-b3ff79101c07 --experiment-name "run-$PIPELINE_NAME"
Run 57db449d-3beb-458b-b9f2-2cc20452c2e9 is submitted
+--------------------------------------+--------+----------+---------------------------+
| run id                               | name   | status   | created at                |
+======================================+========+==========+===========================+
| 57db449d-3beb-458b-b9f2-2cc20452c2e9 | run-   |          | 2020-09-17T12:07:24+00:00 | …
```
=> fix(sdk): added clearer error for case when user uses watch and argo isn't installed

samples/core/output_a_directory/output_a_directory.py
This sample shows how components can output directories
Outputting a directory is performed the same way as outputting a file: component receives an output path, writes data at that path and the system takes that data and makes it available for the downstream components.
To output a file, create a new file at the output path location.
To output a directory, create a new directory at the output path location.
=> feat(samples): Added "Output a directory" sample

sdk/python/kfp/components/_components.py, sdk/python/tests/dsl/component_bridge_tests.py
Pythonic-to-original output name mapping got a default value equal to the output's name. Solves #4514, this is the suggested solution described there. Also adds tests to check if the problem was resolved.
It seems it could be cherry-picked in the current release branch.
=> fix(sdk): Allow non-pythonic names for graph components' task's outputs. Fixes #4514.

samples/core/continue_training_from_prod/continue_training_from_prod.py
This sample demonstrates a common training scenario.
New models are being trained starting from the production model (if it exists).
This sample produces two runs:
1. The trainer will train the model from scratch and set as prod after testing it
2. Exact same configuration, but the pipeline will discover the existing prod model (published by the 1st run) and warm-start the training from it.
=> Samples - Added the continue_training_from_prod sample

sdk/python/kfp/_client.py
This PR adds an extra option to the `Client` which allows for context to be specified. This will only be used in the case that the client is built from a kube config and not in-cluster.
=> feat(sdk): optional context in kubenetes client

components/aws/sagemaker/tests/integration_tests/component_tests/test_groundtruth_component.py
Cleanup of workteams which are created in the `test_groundtruth_component` was failing since the addition of the terminate test. This test caused the first part of the `finally` block to fail and it never got to workteam cleanup. 
As a part of this fix, this cleanup command is only conditionally executed. 
**Checklist:**
=> chore(components): AWS SageMaker - Fix leaking Workteam(GroundTruth) resources

sdk/python/kfp/cli/cli.py, sdk/python/kfp/cli/experiment.py, sdk/python/kfp/cli/output.py, sdk/python/kfp/cli/pipeline.py, sdk/python/kfp/cli/run.py
Currently, the kfp cli prints the command output in the `table` format and it is tough to filter the output. Alternatively, support for additional output formats like JSON would be helpful for users to redirect the output to third-party libraries like `jq` to extract specific fields.
**Checklist:**
=> feat(sdk): Support to print the cli command output in json format

components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_launch_python.py
Dataflow will stop supporting Python 3 jobs before the end of the year [1]. Apache Beam EOLed its python3, Beam 2.24.0 was the last version with python 2 support [2].
This PR changes the python launcher to use the default python version instead of hardcoding to python2 and pip2. It will not impact users who are already using python2 in their virtual environments. It will allow users to also use python3 for their Dataflow pipelines. This fixes #2601, fixes https://github.com/kubeflow/kubeflow/issues/4894.
[1] https://cloud.google.com/python/docs/python2-sunset/#dataflow
[2] https://beam.apache.org/blog/beam-2.24.0/
**Checklist:**
[Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-rele …
=> fix(components): use default python version for launching dataflow jobs. Fixes #2601

sdk/python/kfp/cli/pipeline.py
Added optional argument `-d, --pipeline-description` to provide value for the pipeline description to be uploaded
```bash
$ kfp pipeline upload --help
Usage: kfp pipeline upload [OPTIONS] PACKAGE_FILE
Upload a KFP pipeline
Options:
-p, --pipeline-name TEXT        Name of the pipeline.
-d, --pipeline-description TEXT
Description for the pipeline.
--help                          Show this message and exit.
```
**Checklist:**
=> feat(sdk): Added optional argument to specify description for pipeline upload

components/gcp/bigquery/query/sample.ipynb, components/gcp/bigquery/query/to_CSV/README.md, components/gcp/bigquery/query/to_gcs/README.md, components/gcp/bigquery/query/to_table/README.md, components/gcp/dataflow/launch_python/README.md, components/gcp/dataflow/launch_python/sample.ipynb, components/gcp/dataflow/launch_template/README.md, components/gcp/dataflow/launch_template/sample.ipynb, components/gcp/dataproc/create_cluster/README.md, components/gcp/dataproc/create_cluster/sample.ipynb, components/gcp/dataproc/delete_cluster/README.md, components/gcp/dataproc/delete_cluster/sample.ipynb, components/gcp/dataproc/submit_hadoop_job/README.md, components/gcp/dataproc/submit_hadoop_job/sample.ipynb, components/gcp/dataproc/submit_hive_job/README.md, components/gcp/dataproc/submit_hive_job/sample.ipynb, components/gcp/dataproc/submit_pig_job/README.md, components/gcp/dataproc/submit_pig_job/sample.ipynb, components/gcp/dataproc/submit_pyspark_job/README.md, components/gcp/dataproc/submit_pyspark_job/sample.ipynb, components/gcp/dataproc/submit_spark_job/README.md, components/gcp/dataproc/submit_spark_job/sample.ipynb, components/gcp/dataproc/submit_sparksql_job/README.md, components/gcp/dataproc/submit_sparksql_job/sample.ipynb, components/gcp/ml_engine/batch_predict/README.md, components/gcp/ml_engine/batch_predict/sample.ipynb, components/gcp/ml_engine/deploy/README.md, components/gcp/ml_engine/deploy/sample.ipynb, components/gcp/ml_engine/train/README.md, components/gcp/ml_engine/train/sample.ipynb
Did a pass to replace all the instances of
`KFP_PACKAGE = 'https://storage.googleapis.com/ml-pipeline/release/0.1.14/kfp.tar.gz'`
and `!pip3 install $KFP_PACKAGE --upgrade`
with just a regular pip install of the kfp package.
However, I'm wondering about this snippet in the READMEs:
```
%%capture --no-stderr
!pip3 install kfp --upgrade
```
In this context (as opposed to the notebooks) the user would probably be doing the install from the command line.
While I'm at it should I remove the '%%' line and get rid of the '!'?  Or am I missing the point?
=> update kfp installation instructions for a number of gcp components

sdk/python/kfp/components/_data_passing.py
Some components are already using this type name and are starting to fail due to more strict type checking during constant argument serialization.
=> feat(sdk): Components - Added Bool as a known type name

components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_train.py, components/gcp/container/component_sdk/python/tests/google/ml_engine/test__train.py
[ai_platform.ipynb](https://github.com/kubeflow/pipelines/blob/master/samples/core/ai_platform/ai_platform.ipynb) is broken with the following runtime error:
```
Fire trace:
1. Initial component
2. Accessed property "train" (kfp_component/google/ml_engine/_train.py:18)
3. Called routine "train" (kfp_component/google/ml_engine/_train.py:18)
4. ('Cannot find target in dict:', '--job_dir_output_path', {u'trainingOutput': {u'consumedMLUnits': 0.06}, u'trainingInput': {u'runtimeVersion': u'1.13', u'region': u'us-central1', u'args': [u'--data-file-url', u'gs://chesu-kfp/reports.csv', u'--job-dir', u'gs://chesu-kfp'], u'pythonModule': u'trainer.task', u'jobDir': u'gs://chesu-kfp/train/output/1601963201/', u'packageUris': …
```
=> fix(components): fix ml_engine/train interface

components/aws/sagemaker/tests/integration_tests/component_tests/test_groundtruth_component.py, components/aws/sagemaker/tests/integration_tests/component_tests/test_model_component.py
- Remove canary marker from model test: Model Component is already covered as part of batch and endpoint test. Running multiple canaries simultaneously results in throttling from SageMaker
- List labelling jobs by workteam returns even if jobs are completed. Check in previous PR was wrong
**Testing**
```
pytest -n 7 -m "canary_test" --role-arn=<> --s3-data-bucket=<> --assume-role-arn=<>
```
=> chore(components): SageMaker integ test changes

sdk/python/kfp/cli/experiment.py, sdk/python/kfp/cli/pipeline.py, sdk/python/kfp/cli/run.py
Adds missing short options to be consistent with other cli subcommand options
**Checklist:**
=> feat(sdk): Adds missing short options to the cli

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/dsl/_component_bridge.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/compiler/compiler_tests.py
ContainerOp has no concept of inputs, so it loses any information about them such as input names and in some cases even the passed argument values (which are just injected into the command line).
This commit fixes that issue by preserving the paramater arguments map and ultimately storing it in an Argo template annotation.
Fixes https://github.com/kubeflow/pipelines/issues/4556
=> feat(sdk): Preserve parameter arguments and input names

sdk/python/kfp/components/modelbase.py, sdk/python/kfp/components_tests/test_structure_model_base.py
In Python 3.9 the open generic types like `typing.Dict` lack the `__args__` attribute.
=> fix(sdk): Components - Fixed ModelBase handling of open generic types in Python 3.9

sdk/python/kfp/components/_components.py, sdk/python/kfp/v2/dsl/component_bridge.py
A recent PR has added some changes that architecturally belonged to a different module (the component bridge). This has introduced unintended dependencies and couplings between the modules. This PR restores the module separation. It also makes the code simpler.
=> SDK - Restored module decoupling

sdk/python/kfp/components/_python_op.py
Python 3.9 has dropped support for `typing.NamedTuple(...)`.`_field_types` in favor of `__annotations__` which in turn does not exist in Python 3.5.
=> fix(sdk): Components - Fixed handling of typing.NamedTuple in Python 3.9

backend/src/cache/deployer/cache-webhook-config.v1.yaml.template, backend/src/cache/deployer/cache-webhook-config.v1beta1.v1.15.yaml.template, backend/src/cache/deployer/cache-webhook-config.v1beta1.yaml.template
The sideEffects field field became required in v1 version of the resource https://github.com/kubernetes/kubernetes/pull/79549
Also adding failurePolicy: Ignore, because the default value has changed to Fail in v1.16.
These changes are not needed for v1beta1, but I still add them for those cases as well for consistency.
Fixes https://github.com/kubeflow/pipelines/issues/4627
=> fix(backend): Caching - Fixed deployer failure on Kubernetes v1.16+. Fixes #4627

test/deploy-cluster.sh
I just found GCP regular channel has been on 1.17: https://cloud.google.com/kubernetes-engine/docs/release-notes.
But KFP hasn't been compatible with it. I tested KFP 1.0.3 on MKP auto created cluster (1.17) and cache deployer fails there.
We should change test default to make sure we stay compatible with regular channel.
/assign @Ark-kun @numerology @chensun 
**Checklist:**
=> test: use GCP cluster regular channel

sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/dsl/component_bridge_tests.py
The dsl.ContainerOp deprecation message should be visible to end users. Since Python3.2 Deprecation messages are ignored unless the at `__main__` stack level.  FutureWarnings should be used when the warning should be seen by the end users.
DeprecationWarning
> Base category for warnings about deprecated features when those warnings are intended for other Python developers (ignored by default, unless triggered by code in __main__).
FutureWarning
> Base category for warnings about deprecated features when those warnings are intended for end users of applications that are written in Python.
Ref : https://docs.python.org/3/library/warnings.html#warning-categories
PS: Deprecation can be seen if the python program(pipeline is compiled) is run with -Wall option. …
=> fix(sdk): fixes dsl.ContainerOp deprecation warning not shown

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/dsl/_container_op.py
Reverting most of the #2334 which inadvertently broke those artifacts by causing the names to be mangled.
KFP's DSL compiler prepends template names to output names to ensure global uniqueness of *input* names (DSL's ContainerOp does not have concept of inputs, so the inputs are generated during the compilation including input names). But prepending template names to the output names stops the backend from recognizing the `mlpipeline-ui-metadata` and `mlpipeline-metrics` artifacts.
=> fix(sdk): Fixed UI metadata and metrics

backend/metadata_writer/src/metadata_writer.py
Previously, Metadata Writer could only store input artifacts, but could not store input parameter arguments (since they were not available).
The SDK can now preserve parameter arguments in Argo template annotation.
The commit makes Metadata Writer extract information from that annotation and record it to MLMD.
Fixes https://github.com/kubeflow/pipelines/issues/4556
=> feat(backend): Metadata Writer - Record parameter argument values to MLMD

test/manifests/dev/proxy-agent-patch.yaml
Presubmit is failing at 401 for the staging inverse proxy, looks like there are permission issues.
**Checklist:**
=> test(proxy): use prod inverse proxy instance

proxy/get_proxy_url.py, proxy/get_proxy_url_test.py
- Fixed #4284
- Priority of potential proxy urls is being lost by deduplicating them using `set()` and as sets don't preserve order. This fix fixes this issue by checking if the current url is present in the potential url list before adding the current to the potential list
- Added `test_get_urls_priority` to validate this fix
- Modified existing tests as `urls_for_zone` now returns a `list` instead of a `set`
- Style formatted `proxy/*.py` with `yapf` using `.style.yapf` provided in the repo
**Checklist:**
=> fix(proxy): fixes GCP inverse proxy url priority. Fixes #4284

proxy/attempt-register-vm-on-proxy.sh
When looking at proxy-agent logs, I found
```
2020/10/28 03:34:25 Failed to read pending requests: "A proxy request failed: \"Get https://datalab-staging.cloud.google.com/tun/m/4592f092208ecc84946b8f8f8016274df1b36a14agent/pending: net/http: request canceled (Client.Timeout exceeded while awaiting headers)\""
```
The url `https://datalab-staging.cloud.google.com/tun/m/4592f092208ecc84946b8f8f8016274df1b36a14agent/pending` works, but it is a little weird, we should add a `/` before `agent/pending`.
**Checklist:**
=> chore(proxy): PROXY_URL should end with /

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
This keeps the minio service similar to the other minio resources and helps e.g. when defining a ServiceMonitor for the prometheus-operator.
**Checklist:**
- not really needed, just a minor change
=> chore(deployment): Add app=minio label to minio service

.gitignore, sdk/python/kfp/cli/pipeline.py, sdk/python/kfp/cli/run.py
When user wants to upload pipeline and create a run using kfp, they need to somehow retrieve pipeline-id by pipeline name.
From my point,  it would be good to get rid of this redundant step.
This PR is going to add pipeline-name option to `kfp run submit`.
There are also a few minor PEP8 fixes.
=> feat(sdk): added pipeline name option to kfp run submit

sdk/python/kfp/v2/dsl/importer_node.py, sdk/python/kfp/v2/dsl/importer_node_test.py
There was a bug around assertion. Parentheses were added for line-breaking, but it made assertion always true, since a non-empty tuple evaluates to `True`. There was also bugs in unit tests, so we didn't catch this. This PR fixes both.
**Checklist:**
=> chore(sdk): fix bug around assertion and test

sdk/python/kfp/cli/run.py
Fix print message for run submission with respect to output format
**Checklist:**
=> feat(sdk): Fix print message for run submission with respect to output format

components/aws/emr/submit_pyspark_job/src/submit_pyspark_job.py
When the pyspark job is sent to EMR, an ID is returned and is saved into the variable step_id. This variable was not passed correctly when writing this value into the /output.txt file
=> fix(components): sending pyspark jobs and set generated step_id to /output.txt from the generated EMR step

components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Retry delete EKS Cluster to make sure resources get deleted.
Error Message:
```
[ℹ]  eksctl version 0.19.0
[ℹ]  using region us-east-1
[ℹ]  deleting EKS cluster "sagemaker-kfp-2020-10-22-12-13-33-eks-cluster"
[ℹ]  deleted 0 Fargate profile(s)
[ℹ]  cleaning up LoadBalancer services
Error: cannot list Kubernetes Services: Get https://AB90DC635B6E4C329D1DBE27C4781F4C.gr7.us-east-1.eks.amazonaws.com/api/v1/services: dial tcp 54.205.70.3:443: i/o timeout
```
=> fix(components): AWS SageMaker - Retry delete EKS Cluster after Integ test failure 

sdk/python/kfp/compiler/compiler.py
adds a missing import in kfp compiler which caused 
```NameError: name 'warnings' is not defined``` when compilation for a pipeline fails in `kfp v1.1.0`
**Checklist:**
=> fix(sdk) - fixes missing import in KFP compiler

sdk/python/kfp/__init__.py, sdk/python/setup.py
- Bound kfp-pipeline-spec version to >=0.1.0, <0.2.0
- Tentatively release kfp 1.1.1rc1 (or we can skip and wait?)
**Checklist:**
=> chore(sdk): pin kfp-pipeline-spec version

sdk/python/kfp/_client.py
Currently the following happens when calling start pipeline from func: 
- provide an experiment name call  -> create_experiment with that name -> calls get_experiment and if get_experiment returns an exception then we consider it does not exists.
We catch any Exception with the try except when retrieving if an experiment exists or not:
https://github.com/kubeflow/pipelines/blob/c84f4da0f7b534e1884f6696f161dc1375206ec2/sdk/python/kfp/_client.py#L289
However that try except should only catch if the experiment does not exists so it should have raise a Value Error here:
https://github.com/kubeflow/pipelines/blob/c84f4da0f7b534e1884f6696f161dc1375206ec2/sdk/python/kfp/_client.py#L364
Since it can also get caught in the raise in case of missing params here: …
=> fix(sdk): fixes too broad except when retrieving experiments.

.github/stale.yml
I feel stale issues are closed too fast, bumping close period also to 90 days.
What do you think about it?
**Checklist:**
=> chore: update stale close period to 90d

components/kubeflow/kfserving/src/kfservingdeployer.py
fix https://github.com/kubeflow/kfserving/issues/1215
In the newer version of Knative, it's recommended to [configure a DNS endpoint](https://knative.dev/docs/install/installing-istio/#configuring-dns) instead of adding a host header. Also, the newer version of Knative also has a different url format that breaks the current url parsing. Therefore, we need to update the closing statements to follow the new standard. https://knative.dev/docs/install/installing-istio/#configuring-dns
**Checklist:**
=> fix(components): Fix kfserving component url parsing

sdk/python/kfp/dsl/_volume_snapshot_op.py, sdk/python/tests/dsl/volume_snapshotop_tests.py
related to : https://github.com/kubeflow/pipelines/issues/4674 
making api_version a parameter of `VolumeOp` defaulting to the previous hardcoded value
=> fix(sdk): VolumeOp has apiVersion as parameter

sdk/python/kfp/_auth.py
The SDK no longer needs the gcloud CLI installed. (Although the credentials still have to probably be set in some way).
=> feat(sdk): Client - Getting access token without gcloud CLI

frontend/src/lib/StatusUtils.test.tsx, frontend/src/lib/StatusUtils.ts
The UI was deciding whether a node was cached based on whether it was
pointing to some other node's output artifacts.
This works for nodes that correspond to pods, but leads to a wrong
decision for the rest of the nodes. For example, if the node is a Retry
one, it points to another node's outputs because it is that other node
that actually produced them.
We now apply this logic on pod-type nodes only.
Fixes #4814
/assign @Bobgy 
**Checklist:**
=> fix(frontend): Fix logic deciding if a node was cached. Fixes #4814

frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
Yaml file cannot show with Safari browser, as below picture.
**Root-Cause**: react-ace Editor doesn't support in Safari when height or width is a percentage
After fixed, both Chrome and Safari browser are OK now:
**Checklist:**
- [ x ] Do you want this pull request (PR) cherry-picked into the current release branch?
=> fix(frontend): Fix the yaml cannot show in Safari browser issue. Fixes #4727

test/presubmit-tests-tfx.sh
It looks like in `pip 20.3` it will scan through all available version of `promise` in order to get a compatible one. Then the test process failed due to a bad `promise` version. 
**Checklist:**
=> test: pin pip to fix a weird version resolution logic

sdk/python/kfp/v2/compiler/compiler.py, sdk/python/kfp/v2/compiler/compiler_test.py, sdk/python/kfp/v2/compiler/compiler_utils.py, sdk/python/kfp/v2/compiler/compiler_utils_test.py
Raise an error if pipeline.name doesn't conform to [a-z0-9][a-z0-9-]{0,127}.
**Checklist:**
=> chore(sdk.v2): Error out on invalid pipeline name

api/v2alpha1/pipeline_spec.proto, api/v2alpha1/python/setup.py
Add `deployment_spec` field which is a structure-typed field, and mark the old `deployment_config` field as deprecated in favor of the new field.
The problem with Any-typed field is that when multiple copies of the Python proto libraries are imported to the same Python environment, there will be a conflict because they share the namespace. And this is inevitable because in Any field we'll need the type url which encodes the proto package name.
**Checklist:**
=> [IR] Add deployment spec to IR spec.

sdk/python/kfp/components/_python_op.py, sdk/python/kfp/containers/_component_builder.py, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
Currently were running the python code inline using `python -c <code>`.
This has two issues:
1) Python does not show source code line in exception stack traces
2) inspect.getsource does not work. This method is used in PyTorch JIT for example.
We solve these issues by writing the code into a file before executing it.
The disadvantage of the new approach is that it adds complexity, a filesystem write operation and also requires the `sh` executable to be present (we could replace it with python-based program if needed).
Fixes https://github.com/kubeflow/pipelines/issues/4273
Fixes https://github.com/kubeflow/pipelines/issues/4849
=> feat(sdk): Components - Restored stack traces in lightweight python components. Fixes #4273, #4849

samples/core/dns_config/dns_config.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/tests/compiler/compiler_tests.py
Enable to set `dnsConfig` by SDK.
- Added a `dns_config` attribute to PipelineConf
- If dns_config is set, convert dns_config to k8s object at compile time
**Checklist:**
=> feat(sdk): Add settings of the dnsConfig field. Fixes #4836

frontend/src/lib/CompareUtils.test.ts, frontend/src/lib/CompareUtils.ts, frontend/src/lib/ParserUtils.ts, frontend/src/lib/WorkflowParser.ts
Fixes https://github.com/kubeflow/pipelines/issues/4107 and additionally ensures the display names used for the node in the graph UI and metrics UI match
=> fix(frontend): Use task_display_name annotation when displaying run metrics

sdk/python/kfp/dsl/_ops_group.py
Adds variable argument list to `GroupOp`'s `after` method so that it supports calling with multiple arguments while staying backwards-compatible. As per issue #4787.
It seems it could be cherry-picked in the current release branch.
=> feat(sdk): allow calling GroupOp.after with multiple ops

sdk/python/kfp/_client.py
make healthz exception visible in logs by default.
I noticed that `logging.info` do not show in logs by default, it's better to change it to exception, so that we can also see the exact exception information to facilitate debugging.
Context:
in https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-pipelines-periodic-functional-test/1339054226130604032#1:build-log.txt%3A271, the client fails with authz errors, but logs are empty when trying
**Checklist:**
=> fix(sdk): make healthz exception visible in logs by default

sdk/python/kfp/dsl/_resource_op.py, sdk/python/tests/dsl/resource_op_tests.py, sdk/python/tests/dsl/volume_op_tests.py
When calling the delete() method of a ResourceOp we need to ensure we do
not wait for its deletion.
The reason for this is described in [1]: If a pipeline creates a
resource which is being consumed by its steps (e.g., a PVC), the step
deleting the resource will hang waiting for the Kubernetes resource
deletion which, in turn, is waiting for the other steps to get deleted.
As a result, the pipeline never finishes.
This commit allows specifying flags for the ResourceOp kubectl commands
and defaults to the '--wait=false' flag for the deletion.
Specifying flags for a ResourceTemplate is not supported in Argo v2.7
that we currently deploy. But they will be once we upgrade to v2.11+
[2]. This does not affect the delete() method because we don't rely on
Argo's ResourceTemplate for it.
[1] …
=> fix(sdk): Do not wait for resource deletion

sdk/python/requirements.in, sdk/python/requirements.txt
- Bump `kfp-server-api` version to 1.1.2 in `requirements.in` (matching what's specified in [`setup.py`](https://github.com/kubeflow/pipelines/blob/bb0f33054ce217f48ccc1f02327cc8660eeb6596/sdk/python/setup.py#L34))
- Re-generate `requirements.txt`
**Checklist:**
=> chore(sdk): update requirements.txt

sdk/python/kfp/v2/compiler/compiler_test.py, sdk/python/kfp/v2/dsl/component_bridge.py
- Importer node will be auto attached only if InputUri placeholder is used.
**Checklist:**
=> chore (sdk.v2): Error out on using InputPath placeholder for artifacts require importer.

frontend/src/icons/statusCached.tsx, frontend/src/pages/Status.tsx, frontend/src/pages/__snapshots__/Status.test.tsx.snap
Change the icon used on cached steps to make them more intuitive.
The previously used CachedIcon (from material UI) can be easily confused
with some kind of 'loop' or 'sync'.
This commit changes the icon used to a combination of SuccessIcon and
CachedIcon from the material UI library. This clarifies that the step
actually ran successfully and its execution was cached.
**Checklist:**
=> fix(frontend): Change CachedIcon to something more intuitive

CONTRIBUTING.md
Fix #4934 
Added the guidelines of writing UT of golang part in Contrubuting.md
**Checklist:**
=> docs: Add the guidelines of writing UT of golang part in Contrubuting.md

components/gcp/container/Dockerfile, components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_client.py, components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_launch_python.py, components/gcp/container/component_sdk/python/setup.py, components/gcp/container/component_sdk/python/tests/google/dataflow/test__launch_python.py, components/gcp/container/component_sdk/python/tox.ini, components/gcp/dataflow/launch_python/component.yaml, components/gcp/dataflow/launch_python/sample.ipynb
- Update GCP component container to using Python 3.7, also upgrade apache-beam[gcp] version.
- Fix Dataflow client and sample.
Tested via Dataflow launch_python and launch_template sample notebooks.
Fixes #4959 
**Checklist:**
=> fix(components): Update GCP component container to Python 3.7. Fixes #4959 

components/kubeflow/kfserving/component.yaml, components/kubeflow/kfserving/src/kfservingdeployer.py
Currently, `InferenceService` resource watching timeout is hardcoded and there is no way to configure it. We have observed some pipeline failures in our environment when `kfserving` component has failed due to timing out waiting for a resource to become ready, which in our case can take more than the default timeout (120 seconds). This PR makes it configurable and retains the default functionality.
**Checklist:**
=> refactor(components): parametrize InferenceService resource watching timeout

components/kubeflow/kfserving/src/kfservingdeployer.py
In the recent Kubernetes version, V1ContainerPort protocol is no longer optional in some Kubernetes deployment. Thus we are seeing the below errors:
```
"causes":[{"reason":"FieldValueRequired","message":"Required value","field":"spec.default.predictor.custom.container.ports.protocol"}]
```
Add the default protocol value from k8s (TCP) will solve this issue. 
**Checklist:**
=> fix(components): Add default V1ContainerPort protocol value for the kfserving component

components/kubeflow/kfserving/src/kfservingdeployer.py
This PR adds support for specifying cpu and memory resource requests / limits in the default_custom_model_spec component argument to customize container resource specs. An example shown below 
default_custom_model_spec = {"name": "custommaskrcnn", "image": "imageurl", "resources": {"limits": {"cpu": "2", "memory": "4Gi"}}}
=> feat(components): Added support for specifying resources for custom model deployment

components/kubeflow/katib-launcher/component.yaml
See comment: https://github.com/kubeflow/pipelines/pull/4798#discussion_r528179256.
We can use `JsonObject` instead of `JSON` for Katib component output.
/assign @Ark-kun @Bobgy 
/cc @gaocegege @johnugeorge 
**Checklist:**
=> feat(components): Change Katib component output to JsonObject

sdk/python/kfp/cli/cli.py, sdk/python/kfp/cli/diagnose_me_cli.py, sdk/python/kfp/cli/experiment.py, sdk/python/kfp/cli/output.py, sdk/python/kfp/cli/pipeline.py, sdk/python/kfp/cli/run.py
The current release of kfp cli prints all the command outputs via print or logging statements, this PR fixes that to use `click.echo` statements taking advantage of the same click cli library to handle command produced outputs/errors.
~~Currently, all the commands output is printed on the console without any style formatting which can be changed to ANSI colored text on the console.~~
~~The changes on this PR replace the print statements with click style echo statements that enable us to format the output to be printed on the console.~~
~~RED - Error~~
~~GREEN - Success~~
~~YELLOW - Warning~~
**Checklist:**
=> feat(sdk): Replace logging and print statements with click echo statements for cli

backend/src/apiserver/config/config.json
Updated the current configurations to support the gap_markeplace deployment, see https://github.com/kubeflow/pipelines/commit/eeb7f8f04ac50351fd578a583a8ddc7df1e00bdd#r45867774
**Checklist:**
=> fix(backend): add default value for CRON_SCHEDULE_TIMEZONE

sdk/python/kfp/components/_python_op.py, sdk/python/kfp/components_tests/test_python_op.py
The component specification has always supported component annotations, but there was no way to specify them for the components generated from python. This PR fixes that.
=> feat(sdk): Components - Support annotations when creating components from python

sdk/python/kfp/v2/compiler/compiler.py, sdk/python/kfp/v2/compiler/main.py, sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.json, sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.py
Fixes:
- The `Compiler().compile` method accepts `pipeline_parameters` as an argument but doesn't actually use it.
- The compiler CLI tool does not even expose an interface to accept pipeline parameters.
**Checklist:**
=> fix(sdk.v2): Fix the bug where pipeline_parameters is not used.

components/kubeflow/launcher/Dockerfile
Post-submit build-each-commit is failing on building the KFP launcher component into Docker image:
https://pantheon.corp.google.com/cloud-build/builds/03befb37-3ff6-4283-aa1a-73dc9629ddb4;step=18?project=ml-pipeline-test
Because it uses Python 2.7 which doesn't recognize f-strings.
```
Installed /usr/local/lib/python2.7/dist-packages/pip-21.0-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
File "/usr/local/bin/pip", line 9, in <module>
load_entry_point('pip==21.0', 'console_scripts', 'pip')()
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line …
```
=> fix(component): Use Python3.6 to build KFP launcher component

components/local/base/Dockerfile
Components don't build due to Python2.7 being used: https://pantheon.corp.google.com/cloud-build/builds/b34906af-0485-43be-b994-3fdfab6a0f6b;step=29?project=ml-pipeline-test
Related to #5007 
**Checklist:**
=> fix(components): Update components/local/base/Dockerfile to use Python3

components/gcp/container/component_sdk/python/kfp_component/google/dataproc/_client.py, components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_client.py
This can fix the import error seen in post-submit tests (once released the container image).
```
sample-test-khpbv-717493055: xgboost-trainer-74ttn.onExit:	WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
sample-test-khpbv-717493055: xgboost-trainer-74ttn.onExit:	Traceback (most recent call last):
sample-test-khpbv-717493055: xgboost-trainer-74ttn.onExit:	  File "/usr/local/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
sample-test-khpbv-717493055: xgboost-trainer-74ttn.onExit:	    from google.appengine.api import memcache
sample-test-khpbv-717493055: xgboost-trainer-74ttn.onExit:	ModuleNotFoundError: No module named 'google.appengine'
sample-test-khpbv-717493055: …
```
=> fix(components): Disable cache_discovery in GCP component.

samples/core/xgboost_training_cm/xgboost_training_cm.py
1.2 is unsupported per: https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions
It comes with Python 2.7 which is causing issue as described here: https://github.com/kubeflow/pipelines/issues/5007#issuecomment-769637030
Bump it to 1.5 which comes with Python 3.7, and has a support lifecycle until 2022/04.
Will update the content of gs://ml-pipeline/sample-pipeline/xgboost/initialization_actions.sh separately.
Fixes part of #5007
**Checklist:**
=> fix(samples): Bump dataproc image version to 1.5 in xgboost_training_cm.py

sdk/python/kfp/dsl/_ops_group.py, sdk/python/tests/compiler/testdata/loop_over_lightweight_output.py, sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.py, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml, sdk/python/tests/compiler/testdata/parallelfor_pipeline_param_in_items_resolving.py, sdk/python/tests/compiler/testdata/parallelfor_pipeline_param_in_items_resolving.yaml, sdk/python/tests/compiler/testdata/uri_artifacts.yaml, sdk/python/tests/compiler/testdata/withitem_basic.py, sdk/python/tests/compiler/testdata/withitem_basic.yaml, sdk/python/tests/compiler/testdata/withitem_nested.py, sdk/python/tests/compiler/testdata/withitem_nested.yaml, sdk/python/tests/compiler/testdata/withparam_global.py, sdk/python/tests/compiler/testdata/withparam_global.yaml, sdk/python/tests/compiler/testdata/withparam_global_dict.py, sdk/python/tests/compiler/testdata/withparam_global_dict.yaml, sdk/python/tests/compiler/testdata/withparam_output.py, sdk/python/tests/compiler/testdata/withparam_output.yaml, sdk/python/tests/compiler/testdata/withparam_output_dict.py, sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
During compilataion ParallelFor components end up with randomized names,
which makes it very inconvenient to compare two versions of a pipeline.
This commit fixes this issue.
**Checklist:**
=> fix(sdk): compile ParallelFor in a deterministic manner

sdk/python/requirements.in, sdk/python/requirements.txt, sdk/python/setup.py
I was playing with KFP in Google Colab with Python 3.6.9 and PyYAML 3.13, hit a bug where artifact instanceSchema was generated as:
`"instanceSchema": "{properties: !!null '', title: kfp.Artifact, type: object}\n"`
instead of what we would expect:
`"instanceSchema": "properties:\ntitle: kfp.Artifact\ntype: object\n"`
Seems like this piece of [code](https://github.com/kubeflow/pipelines/blob/2f1db59798d1a4c49e5cba7ec60644eca3fe5175/sdk/python/kfp/dsl/serialization_utils.py#L16-L37) doesn't work as expect under PyYAML 3.13.
Installing PyYAML 5.3 fixed the problem.
**Checklist:**
=> fix(SDK): require PyYAML>=5.3

.github/renovate.json5
Moves `rangeStrategy` into a separate rule. It won't work as intended if combined with `updateTypes`.
**Checklist:**
=> chore: set npm rangeStrategy in separate rule

frontend/package-lock.json, frontend/package.json
Part of https://github.com/kubeflow/pipelines/issues/4682
A problem I saw:
renovate updated webpack, but not react-scripts. Then frontend fails to build because each version of `react-scripts` works with a specific chosen version of webpack.
Change in this PR:
Remove webpack from dependency, and include it via react-scripts's transitive dependency.
In this way, webpack's version will be decided by react-scripts, so they won't be out-of-sync during renovate auto-upgrade.
**Checklist:**
=> chore: remove webpack from dependency

sdk/python/kfp/compiler/_data_passing_rewriter.py, sdk/python/kfp/compiler/compiler.py
Make the error message more informative when the user tries to connect path placeholder with uri placeholder, which is not supported yet.
**Checklist:**
=> chore: Improve the error message when incompatible placeholders are connected

sdk/python/kfp/v2/compiler/compiler_test.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.py, sdk/python/kfp/v2/components/__init__.py
- This will be included in KFP SDK 1.4.0 release.
**Checklist:**
=> chore(sdk): Bring back kfp.v2.components as an alias to kfp.components

sdk/python/kfp/dsl/_pipeline.py, sdk/python/kfp/v2/compiler/compiler.py, sdk/python/kfp/v2/compiler/compiler_test.py, sdk/python/kfp/v2/compiler/main.py, sdk/python/tests/compiler/testdata/uri_artifacts.py
- Setting `pipeline_root`/`output_directory` via `@dsl.pipeline` decorator was added in v1 but not used in v2. Make it available in v2.
- Rename `output_directory` to `pipeline_root` in `@dsl.pipeline` decorator, so that it's consistent with `pipeline_root` argument in `Compiler.compiler()` method (also consistent with TFX if that matters).
- The `pipeline_root` in `Compiler.compile()` was previously a required argument, change it to optional as it no longer makes sense to enforce it when user can also set it via `@dsl.pipeline` decorator. Similarly, make it optional for compiler cli.
BREAKING CHANGE:
- Renaming `output_directory` to `pipeline_root` in `@dsl.pipeline` decorator. The background for naming it `output_directory` was to [avoid possible …
=> feat(sdk.v2): Allow set pipeline_root via @dsl.pipeline decorator. Make pipeline_root optional.

hack/release.sh
Looks like this piece of code was possibly accidentally deleted from [the last change](https://github.com/kubeflow/pipelines/commit/c484cfa46cfae1e9d11b5d00e0799b8e52c15e33#diff-051375546db9782e3debc25e0241edf1d5e5e2ec0f183dd8634ca5b2c8968bb8) on this file. But it was intentional to clone 
into a temporary location so that it doesn't interfere with your local repo per [release.md](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#L201)
=> chore: restore the clone step in release.sh

samples/tutorials/Data passing in python components.ipynb
There was an issue at 1.3.0 where pipeline failed to recognize backslash. Upgrade KFP SDK to 1.4.0 fix the issues.
**Checklist:**
=> fix(samples): Update KFP version in sample to fix backslash recognization issue.

components/kubeflow/kfserving/component.yaml, components/kubeflow/kfserving/src/kfservingdeployer.py
This PR adds support for specifying two new config variables Min Replicas and Max Replicas to define limits for the auto scaler to use for inference services. Works for both custom and pre-built model servers.
=> feat(components): Added support for specifying Min and Max replicas for inference services

sdk/python/kfp/components/_data_passing.py, sdk/python/kfp/components_tests/test_data_passing.py, sdk/python/kfp/components_tests/test_python_op.py
KFP SDK supports serializing pipeline parameters with the following types:
https://github.com/kubeflow/pipelines/blob/706c105c8ca3977a91b54d74caebe8ffb39f6aa7/sdk/python/kfp/components/_data_passing.py#L107-L116
However, it doesn't recognize type hints using `typing` module. For example:
```
from typing import List
def my_func(args: List[int]):
print(args)
```
This example results compile time error: `There are no registered serializers for type "typing.List[int]"`, even though we have serializer for `List`.
This change allows recognizing `typing.List[int]` as `List` and `typing.Dict[str, Any]` as `Dict`, etc.
**Checklist:**
[Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry- …
=> chore(sdk): allow serializing pipeline params with `typing` type hints

samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
Update the tfx image to fix issues with:
```
No module named 'tfx.dsl.components'
```
after updating I got issues with: 
```
ImportError: preprocessing_fn in /tfx-src/tfx/examples/chicago_taxi_pipeline/taxi_utils.py not found in import_func_from_source()
```
resolved after updating the path , which  is updated in version 0.27.0, more info [here](https://github.com/tensorflow/tfx/commit/e0cb043ff5d3a9fc33f20b1ce6348518e68352ff). 
**Checklist:**
=> fix(samples): Update tfx image. Fixes #5137

backend/src/apiserver/client_manager.go
This PR fixes the sql error when deploy KFP in ANSI_QUOTES sql mode. Fixes #5121
**Checklist:**
=> fix(backend): fixes sql error when deploy KFP in ANSI_QUOTES sql mode. Fixes #5121

backend/src/cache/server/mutation.go, backend/src/cache/server/mutation_test.go
Resolves this issue https://github.com/kubeflow/pipelines/issues/5137#issuecomment-785653750
Note, latest tfx pods no longer use the same command suffix like before, so we need a new signal to filter them out for caching.
**Checklist:**
=> fix(cache): do not cache TFX pods for newer TFX versions. Part of #5137

backend/src/apiserver/visualization/requirements.in, backend/src/apiserver/visualization/requirements.txt
@Ark-kun thanks, I verified TFMA 0.26 can correctly render evaluator artifact for TFX 0.27. I think we can go with this for release.
**Checklist:**
=> fix(visualization): downgrade tfma to 0.26

sdk/python/tests/local_runner_test.py
Fixes #5209.
In general, a UT should avoid having dependency on extra binaries (like docker).
Disable the test for now until either we install docker in the test environment, or we change the test to mock the docker command call.
**Checklist:**
=> fix(tests): Disable the SDK unittest that requires docker binary in local environment.

sdk/python/kfp/compiler/compiler.py
* `type_check` defaults to True but docstrings mentions the default value as False
=> fix(sdk): update default value for type_check in compiler docstrings

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/compiler/compiler_tests.py
This PR adds support for a backoff strategy in the retry policy of ContainerOps. A backoff strategy describes how the node retry should be delayed, between failures.
This work is based on the initial design of https://github.com/kubeflow/pipelines/pull/3880, which has been stuck for some time two to lack of activity from the original contributor. There is no intention at all to plagiarize the original work and get credit for that, so feel free to resume the discussion in the original PR, if you want.
Closes https://github.com/kubeflow/pipelines/issues/3590
**Checklist:**
=> feat(sdk): Support backoffs in retry strategy

components/sample/Python_script/component.yaml
The sample is small and might be easier to understand for Python users compared to the generated Lighweight components.
=> feat(components): Added a Python script sample

sdk/python/kfp/components/_python_op.py
Hi, guys.
I had an issue with change component.yaml file was changing even there was no code change.
I found that below lines were changed every time when i try to compile.
```yaml
def _deserialize_bool(s) -> bool:
from distutils.util import strtobool
return strtobool(s) == 1
def _serialize_json(obj) -> str:
if isinstance(obj, str):
return obj
import json
def default_serializer(obj):
if hasattr(obj, 'to_struct'):
return obj.to_struct()
else:
raise TypeError("Object of type '%s' is not JSON serializable and does not have .to_struct() method." % obj.__class__.__name__)
return json.dumps(obj, default=default_serializer, sort_keys=True)
```
I made an example code to reproduce this issue.
```python
from typing import NamedTuple
from pathlib import Path
from …
```
=> feat(sdk): Add sorted function to definitions to make constant result

sdk/python/kfp/dsl/dsl_utils_test.py
It seems like a trivial indentation error and it should become part of the test class.
**Checklist:**
- [v] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 
=> test: Fixes wrong indentation in 'dsl_utils_test.py'.

sdk/python/kfp/dsl/_component_bridge.py, sdk/python/kfp/dsl/importer_node.py
Fixes: #5263
The logic for inserting importer node heavily relies on inputs being properly type annotated -- importer node is for input artifact not connected to an upstream component while if an input is not type annotated or annotated using an arbitrary custom string, it's viewed as an artifact in v2. But such inputs in v1 could be parameters and importer logic shouldn't apply.
**Checklist:**
=> fix(sdk): only apply importer node when compiling to IR

components/gcp/ml_engine/deploy/component.yaml, components/gcp/ml_engine/train/component.yaml
I noticed a typo in default bool return type - small PR that fixes it.
**Checklist:**
=> chore(components): fix default return value and correct grammar

sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.py, sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
Fixes #5270 
The sdk compiler testdata `parallelfor_item_argument_resolving.py` does not need to put the brackets `[ ]` around the return statement. Having the extra brackets will cause the issue #5270.
**Checklist:**
=> fix(sdk/tests) fix parallelfor_item_argument_resolving compiler test, Fixes #5270 

backend/metadata_writer/src/metadata_helpers.py
Fixes https://github.com/kubeflow/pipelines/issues/5161
=> fix(backend): add brackets if metadata service host is ipv6.  Fixes (#5161)

sdk/python/kfp/dsl/_resource_op.py, sdk/python/tests/compiler/compiler_tests.py
Argo supports a field in the ResourceTemplate that makes the controller
add an owner reference of the workflow to the created resource since
v2.4.0 [1].
With the upgrade of Argo client [2] and deployment [3] we are now able
to exploit it.
We set it to 'false' by default on all ResourceOps (actually, leave it
empty) and 'true' for VolumeOps. This allows the garbage collection of
PVCs upon workflow cleanup without any further change [4].
[1] https://github.com/argoproj/argo/blob/v2.4.0/pkg/apis/workflow/v1alpha1/workflow_types.go#L1044-L1045
[2] https://github.com/kubeflow/pipelines/pull/4498
[3] https://github.com/kubeflow/pipelines/pull/3537
[4] https://github.com/kubeflow/pipelines/issues/1779
Closes #1779 
**Checklist:**
[Learn …
=> feat(sdk): Enable setting OwnerReference on ResourceOps. Fixes #1779

manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/deployment.yaml, manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/service.yaml, manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
@DavidSpek  @Bobgy  Please include it into Kubeflow 1.3. it is a trivial change like https://github.com/kubeflow/kubeflow/pull/5668 and strictly needed for https://github.com/kubeflow/manifests/pull/1756
ports below 1024 prevent runasnonroot, so we switch from 80 to 8080.
=> fix: runasnonroot for kubeflow-pipelines-controller

manifests/kustomize/third-party/mysql/kustomization.yaml, manifests/kustomize/third-party/mysql/mysql-deployment.yaml, manifests/kustomize/third-party/mysql/mysql-serviceaccount.yaml, test/tag_for_hosted.sh
@Bobgy sorry, but the heavy restructuring made it quite pointless to do a manual rebase of #5228 
docker.io/mysql:5.7 is an official dockerhub image. So there should not be rate limits AFAIK. But you can of course create gcr.io/ml-pipeline/mysql:5.7 . 
metadata-db that you want to merge with this mysql database currently uses mysql:8.0. But ml-pipeline does not work with 8.0
```
[julius@localhost ~]$ kubectl -n kubeflow logs ml-pipeline-7c56db5db9-ts547 -c ml-pipeline-api-server 
I0310 18:49:55.490470       8 client_manager.go:134] Initializing client manager
I0310 18:49:55.490564       8 config.go:50] Config DBConfig.ExtraParams not specified, skipping
(Error 1046: No database selected) 
[2021-03-10 18:49:55]  
(Error 1046: No database selected) 
[2021-03-10 18:49:55]  
(Error 1046: No …
```
=> feat(deployment): update mysql to 5.7 and support running as nonroot

.cloudbuild.yaml, .release.cloudbuild.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml, manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml, manifests/kustomize/env/platform-agnostic/kustomization.yaml, test/tag_for_hosted.sh
Follow up fix of https://github.com/kubeflow/pipelines/pull/5278.
It broke gcp marketplace postsubmit test.
It's likely the lost+found argument that's the root cause, but I think it's nice keeping both manifests in sync anyway.
EDIT: that was wrong, root cause in https://github.com/kubeflow/pipelines/pull/5301#issuecomment-799358066
**Checklist:**
=> chore: add missing places we need to upgrade mysql to 5.7

sdk/python/kfp/cli/pipeline.py
There was an typo error in cli/pipeline.py
```python
if bool(pipeline_id) == bool(pipeline_name):
raise ValueError("Need to suppy 'pipeline-name' or 'pipeline-id'")
```
Changed suppy to supply
**Checklist:**
=> chore (sdk) typo err in cli/pipeline suppy -> supply

sdk/python/kfp/_client.py, sdk/python/kfp/cli/experiment.py
In multi-user deployment, `kfp experiment list` was not working because namespace is not specified.
In `kfp/cli/experiment.py`, list function uses kfp_server_api directly, so there is no step to add namespace parameter.
In this change,
- `list` and `delete` function of `experiment.py` is modified to use kfp.Client's method.
- `delete_experiment` function is added to kfp.Client class.
**Checklist:**
=> feat(sdk): Make cli.experiment use kfp.Client methods instead of using kfp_server_api directly

backend/src/cache/server/mutation.go, backend/src/cache/server/mutation_test.go
V2 components handle caching using their own drivers, so we shouldn't run cache mutation webhook on it.
EDIT: you can try this cache-server image by gcr.io/ml-pipeline-test/4eb2828947a9d6a5566341e1001941369eee4225/cache-server@sha256:da9c38e339553bd98a512d6af4550ef56e789a53eecf16f8df2ce5daf5b66e5d
**Checklist:**
=> chore(v2/cache): cache mutation hook - skip v2 components

backend/src/agent/persistence/main.go, backend/src/apiserver/client/argo.go, backend/src/apiserver/client/kubernetes_core.go, backend/src/apiserver/client/swf.go, backend/src/apiserver/client_manager.go, backend/src/apiserver/common/config.go, backend/src/apiserver/main.go, backend/src/cache/client/kubernetes_core.go, backend/src/cache/client_manager.go, backend/src/cache/main.go, backend/src/common/util/client_parameters.go, backend/src/crd/controller/scheduledworkflow/main.go, backend/src/crd/controller/viewer/main.go, backend/test/integration/job_api_test.go
Fixes https://github.com/kubeflow/pipelines/issues/5095
Add flag options to specify QPS & burst of clients in multiple components including:
- API server
- cache server
- persistent agent
- scheduled workflow controller
- view controller
**Checklist:**
=> feat(backend): Add qps & burst options in clientset. Fix #5095

manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml, manifests/kustomize/base/installs/multi-user/kustomization.yaml, manifests/kustomize/base/installs/multi-user/view-edit-cluster-roles.yaml, manifests/kustomize/base/pipeline/multi-user/kustomization.yaml
Fixes #3513
Changes:
* rename `kubeflow-pipeline-edit` cluster role to `kubeflow-pipelines-edit` (Kubeflow Pipelines is the official brand)
* move subjectaccessreview related manifests to multi-user install folder, so it's builtin for KFP multi-user mode
* sync ml-pipeline cluster role with permissions needed in ml-pipeline role
**Checklist:**
=> feat(deployment): multi-user mode manifests for subject access review integration. Fixes #3513

samples/contrib/kubeflow-katib/early-stopping.ipynb
Related: https://github.com/kubeflow/katib/issues/1475.
We should change our image tag for the `docker.io/kubeflowkatib/mxnet-mnist` image to fix problems with MNIST dataset.
/cc @Bobgy @gaocegege @johnugeorge  @bvboca
**Checklist:**
=> fix(samples): Change Katib Trial image tag to v1beta1-45c5727

sdk/python/kfp/_local_client.py, sdk/python/tests/local_runner_test.py
Some of the issues also affected Linux.
=> fix(sdk): Local runner - Fixed the local runner on Windows

sdk/python/kfp/v2/compiler/compiler_utils.py
Fixes: `KeyError: 'pipelines.kubeflow.org/component_v2' in is_v2_component` whenusing components that have annotations.
=> fix(sdk): v2 - Compiler - Fixed the v2 component detection

manifests/kustomize/base/cache-deployer/kustomization.yaml, manifests/kustomize/base/cache/kustomization.yaml, manifests/kustomize/base/installs/multi-user/cache/kustomization.yaml
Add commonLabels to cache kustomizations. This is helpful for consumers who want to quickly get all objects related to the cache components, in order to remove them.
This change does not break backwards compatibility and follows the best practice of labelling all components of an app. @Bobgy what do you think?
=> chore(manifests): Add commonLabels to cache kustomizations

backend/src/cache/server/mutation.go, backend/src/cache/server/mutation_test.go
Output artifact/parameter names and paths are important and need to be considered.
=> fix(backend): Caching - Make the cache key depend on output names and paths

sdk/python/kfp/components/_key_value_store.py
from:
old_data = cache_value_file_path.write_bytes()
to:
old_data = cache_value_file_path.read_bytes()
Fixes #5288
=> fix(sdk): fix bug in store_value_bytes when read old data. Fixes #5288

manifests/kustomize/env/platform-agnostic-multi-user-pns/kustomization.yaml, manifests/kustomize/env/platform-agnostic-multi-user-pns/workflow-controller-configmap-patch.yaml
Due to https://github.com/kubeflow/pipelines/pull/5312 reverting back to the docker executor, this PR adds manifests for a multi-user installation using the PNS executor. This will probably be needed for many Kubeflow deployments with the upcoming 1.3 release. 
/cc @Bobgy
=> chore: Add platform-agnostic-multi-user-pns manifest

manifests/kustomize/README.md
For kubeflow version 1.4 the `env/platform-agnostic` dont rely on kubernetes `applications` so suggest that we look at the pods instead for the wait condition. 
**Checklist:**
=> fix(docs): updated readme wait condition

sdk/python/kfp/_client.py
The error originates from that `mysql` is [not case sensitve](https://dev.mysql.com/doc/refman/8.0/en/case-sensitivity.html) in the comparisons as I understand it for CHAR, VARCHAR, TEXT. 
```sql
ERROR 1062 (23000): Duplicate entry 'new-' for key 'idx_name_namespace'
```
where I use `new` as the experiment name.  
Will use lowercase for the comparisons as well. 
**Checklist:**
=> fix(sdk): faster get experiment by name respects casing. Fixes #5172

sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/dsl/component_bridge_tests.py
Enable raising `FutureWarning` when `dsl.ContainerOp` is used directly.
**Checklist:**
I guess it is better to fix this issue and release fixed version of SDK. However, since master branch has made breaking change,   we need more work to update the KFP SDK.
=> Fix(sdk): Enable FutureWarning with PipelineParam. Fix #5280

v2/test/Makefile, v2/test/README.md
Document a caveat I found when experimenting
**Checklist:**
=> test: clarify a caveat when running v2 sample test locally

sdk/python/kfp/components/_yaml_utils.py, sdk/python/kfp/containers_tests/testdata/expected_component.yaml
The special-casing resulted in component.yaml not being able to load
correctly. Now, both `{executorInput}` and `{executorInput: null}` work.
The latter is what is generated when saving components that have this
placeholder.
**Checklist:**
=> fix(sdk): Fix serialization of ExecutorInput.

backend/metadata_writer/src/metadata_writer.py
Fixes https://github.com/kubeflow/pipelines/issues/5413
The metadata-writer should use a different function to watch Pods, if
the namespace is empty, i.e, if it wants to watch Pods in all
namespaces.
/cc @Bobgy
=> metadata-writer: Fix multi-user mode

frontend/src/components/Trigger.test.tsx, frontend/src/components/Trigger.tsx, frontend/src/components/__snapshots__/Trigger.test.tsx.snap
On Safari, it will crash if user provides wrong data/time format in Run Trigger. It doesn't happen on Chrome because Chrome supports material-ui Input type: `date` and `time`. User cannot change the value to invalid format. But the same component is only TextField on Safari, its value is not restricted by the date or time format.
Shows the error message if user provides wrong date/time format, so web page won't crash as in https://github.com/kubeflow/pipelines/issues/5350.
**Checklist:**
=> fix(frontend): Avoid crashing, and show error message for invalid trigger date/time format. Fixes #5350

manifests/kustomize/base/installs/multi-user/istio-authorization-config.yaml
Add a rule that allows traffic to the Pipelines API-Server, when the `kubeflow-userid` header is not set.
This way, users can utilize ServiceAccountToken authentication to authenticate from their Notebooks / Pipelines, or other workloads.
=> feat(deployment): Allow traffic to the API-Server if the identity header is not set

backend/src/common/util/workflow.go, backend/src/common/util/workflow_test.go
=> fix(backend): api server panics on workflow with parameter without value. Fixes #5423

sdk/python/kfp/onprem.py
Description of your changes:
Add task in kfp.onprem to load k8s secrets as env vars.
This is a utility for on-prem users to be able to load k8s secrets as environment variables in a pipeline. Notably, it can be used for fetching passwords for any kind of backend storage that one wishes to use, e.g. Minio etc.
**Checklist:**
- [X ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 
=> feat(sdk/extensions): Add kfp.onprem.use_k8s_secret method that puts k8s secrets in env vars

components/gcp/bigquery/query/to_table/component.yaml
Delete an unnecessary required field `table` in Bigquery Component `to_table`.
It involves #4226, which has already been closed.
**Checklist:**
=> fix(components): Delete unused to_table component item

components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_client.py
Add bypass to fix recurring problems with BrokenPipeError in MLEngineClient class. It works in my custom build container and I am able to train models on ml engine without problems (only seeing warning from retry decorator). I on purpose name it "bypass" since it does not solve the root of the problem that seems to exist since 2016: https://github.com/googleapis/google-api-python-client/issues/218
**Checklist:**
=> fix(components): add bypass for BrokenPipeError in gcp ml engine client. Fixes #5085

sdk/python/kfp/v2/compiler/compiler.py, sdk/python/kfp/v2/compiler/compiler_test.py, sdk/python/kfp/v2/compiler/main.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.py
Use `package_path` instead of `output_path` in v2 compiler interface for consistency with v1 compiler.
**Checklist:**
=> feat(sdk.v2): use consistent argument name in v2 compiler

samples/test/fail_test.py, samples/test/two_step_test.py, samples/test/util.py, v2/test/Dockerfile, v2/test/components/run_sample.yaml, v2/test/sample_test.py
Changes:
* v2 sample test supports multiple test cases -- many samples need more than one set of tests, either testing both v1 and v2 compatible versions, or testing multiple set of arguments, as shown in https://github.com/kubeflow/pipelines/pull/5431
* use internal endpoint for accessing KFP API server -- so that when errors happen, we can see the detailed error log (we preserve URLs as external links by passing in an extra parameter called external_host)
**Checklist:**
=> test: v2 sample test supports multiple test cases & internal endpoint

components/kubeflow/kfserving/component.yaml, components/kubeflow/kfserving/src/kfservingdeployer.py
Adds `timeout` to PredictorSpec which specifies the number of seconds to wait before timing out a request to the component.
Ref issue - #5343 
**Checklist:**
=> chore(components): Added request timeout to KFServing component

components/kubeflow/kfserving/README.md, components/kubeflow/kfserving/src/kfservingdeployer.py
The output content should not exceed 4096 bytes, so this removes some unneeded fields from the output JSON.
Container termination messages are limited to 4096 bytes. Messages longer than that are truncated, or in the case of Tekton pipelines, one would get a `Error while handling results: Termination message is above max allowed size 4096, caused by large task result` error message.
The README was also updated to better inform about the needed KFServing version to use the component.
Closes: #5353
=> chore(components): Update README and reduce output size of KFServing component

manifests/kustomize/base/installs/multi-user/istio-authorization-config.yaml, manifests/kustomize/base/metadata/options/istio/destination-rule.yaml, manifests/kustomize/base/metadata/options/istio/istio-authorization-policy.yaml, manifests/kustomize/base/metadata/options/istio/kustomization.yaml, manifests/kustomize/base/metadata/options/istio/virtual-service.yaml, manifests/kustomize/env/platform-agnostic-multi-user-legacy/kustomization.yaml, manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml, manifests/kustomize/third-party/minio/options/istio/istio-authorization-policy.yaml
In https://github.com/kubeflow/pipelines/pull/5416, we no longer default to include base/metadata/base in several manifests -- making it an component people can compose.
Therefore, I think it's reasonable to also move its related istio config to one place.
Second change:
~~added common labels for all mlmd manifests~~ reverted this change, because it breaks upgrade
```
commonLabels:
app.kubernetes.io/name: ml-metadata
app.kubernetes.io/component: ml-metadata
```
**Checklist:**
=> refactor(deployment): move metadata-grpc-service istio config to its own folder

components/google-cloud/container/aiplatform/Dockerfile, components/google-cloud/google_cloud_components/aiplatform/remote_runner.py, components/google-cloud/google_cloud_components/aiplatform/utils.py
Switching to V2 artifact passing format using resource path instead of directly writing to GCS. This PR does not cover updating the metadata, we will do that in a separate follow up PR.
=> Use artifacts for resource name

components/google-cloud/google_cloud_components/aiplatform/remote_runner.py
Fixing the issue with artifact writing raises `FileNotFoundError`. The artifact path needs to be created prior to opening file for writing.
=> components: (google-cloud-sdk) Fix artifact FileNotFoundError

components/XGBoost/Predict/component.py, components/XGBoost/Predict/component.yaml, components/XGBoost/Predict/from_ApacheParquet/component.py, components/XGBoost/Predict/from_ApacheParquet/component.yaml
The type `Text` makes it a string parameter instead of an artifact in v2. 
Changing the type to make it compatible in both v1 and v2.
**Checklist:**
=> chore(components): Update XGBoost predict components output type.

sdk/python/kfp/_client.py
Hi maintainers,
I introduce the new environment variables for kfp oauth clients.
* `KF_PIPELINES_IAP_OAUTH2_CLIENT_ID`
* `KF_PIPELINES_APP_OAUTH2_CLIENT_ID`
* `KF_PIPELINES_APP_OAUTH2_CLIENT_SECRET`
The reason for this change is that I wanted to hide the information of OAuth2 Clients when users use kfp from their notebooks. I would like to set these environment variables via poddefaults, so that users can use kfp without being aware of the OAuth2 Client information.
----
**Checklist:**
=> feat(sdk): Introduce new environment variables for kfp oauth2 clients

.github/pull_request_template.md
we do not actively maintain release branches, so there is no need to notify this
**Checklist:**
=> chore: remove cherry pick process from pull request template

components/google-cloud/storage/download/component.yaml, components/google-cloud/storage/download_blob/component.yaml, components/google-cloud/storage/download_dir/component.yaml, components/google-cloud/storage/list/component.yaml, components/google-cloud/storage/upload_to_explicit_uri/component.yaml, components/google-cloud/storage/upload_to_unique_uri/component.yaml
Explicitly annotate URI types as String so they get treated
appropriately in v2.
**Checklist:**
=> fix(components): Update types for GCS components so it's compatible with v2.

backend/src/crd/controller/viewer/reconciler/reconciler.go, backend/src/crd/controller/viewer/reconciler/reconciler_test.go
Part of #5471 
When testing https://github.com/kubeflow/pipelines/issues/5471, I found viewer crd controller crashes with tensorboard image without tag. We should treat them as tensorflow v2.
**Checklist:**
=> fix(viewer): viewer crd controller panics using tensorboard image without tag. Part of #5471

components/google-cloud/container/aiplatform/cloudbuild.yaml
Switching to use Kaniko for image build with caching enabled. This is both faster than plan docker, it also automatically overwrites / detect destination project making it easy to run in various tests environments.
=> feat(components/google-cloud): Use Kaniko for image build

sdk/python/kfp/dsl/_pipeline_param.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
It's mentioned in the comment that 
https://github.com/kubeflow/pipelines/blob/f80f4785c7166de41182487b1c2fcf4563d5186c/sdk/python/kfp/dsl/_pipeline_param.py#L179-L183
However, this shouldn't apply to `value`, which is not even included in the serialization/deserialization process.
**Checklist:**
=> fix(sdk): Fix bug where empty string was not preserved as pipeline param default value.

samples/test/util.py, v2/test/sample_test.py
The tests timeout quite often, should we try double the timeout?
**Checklist:**
=> test: increase sample test timeout wait time.

sdk/python/kfp/dsl/_component_bridge.py, sdk/python/kfp/v2/compiler/compiler.py, sdk/python/kfp/v2/compiler/compiler_test.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
- Raises error when pipeline arguments are categorized as artifacts - the most common cause is missing type annotation.
- Raises error on passing an artifact to a parameter or vice versa. 
**Checklist:**
=> feat(sdk.v2): Raise error on artifacts vs. parameters mismatch in v2.

samples/test/reused_component_test.py, samples/test/util.py, v2/cmd/launch/main.go, v2/component/launcher.go
Changes:
* when int/float parameter has an extra newline, we can ignore it when parsing its value
* this fixes reused_component sample
**Checklist:**
=> chore(v2): fix int/float parameter parsing with extra newline and fix reused_component sample

backend/src/apiserver/client_manager.go, backend/src/apiserver/config/config.json, manifests/kustomize/base/installs/generic/pipeline-install-config.yaml, manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
This allows users to set an env variable DBCONFIG_DBMAXLIFETIME. It solves https://github.com/kubeflow/pipelines/issues/5329 
**Checklist:**
=> Add configurable connection max lifetime for MySQL

components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
Components - Goolge - AI Platform - Improved component generation
Generating YAML text from strings is very fragile.
It's more resilient to create components.structures.ComponentSpec object which can be serialized, loaded and instantiated.
=> chore(components): Goolge - AI Platform - Improved component generation

test/presubmit-tests-tfx.sh
Follow up on https://github.com/kubeflow/pipelines/issues/5614#issuecomment-835195983
@jiyongjung0 found out that likely https://github.com/tensorflow/tfx/tree/master/tfx/orchestration/kubeflow/proto is the one that hides `proto` from `proto-plus` package.
So we should run tests from the root directory instead of going into `tfx/orchestration/kubeflow/proto`
**Checklist:**
=> test: Update presubmit-tests-tfx.sh to run tests from src root.

components/google-cloud/google_cloud_pipeline_components/aiplatform/remote_runner.py, components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
Supporting input parameter types of union [ str, list[str] ], for example users can pass in 
```python 
ds_op = gcc_aip.ImageDatasetCreateOp(
project=PROJECT_ID,
display_name='flowers',
gcs_source='gs://...'
```
or
```python 
ds_op = gcc_aip.ImageDatasetCreateOp(
project=PROJECT_ID,
display_name='flowers',
gcs_source=['gs://sr1','gs://sr2'...],
```
=> feat(components/google-cloud): Support input type union[str,list[str]]

sdk/python/kfp/cli/run.py
Update to allow equal signs in parameters fixes: https://github.com/kubeflow/pipelines/issues/5577
**Checklist:**
=> fix(cli): update client to allow equal signs('=') in parameters. Fixes #5577

sdk/python/kfp/dsl/types.py, sdk/python/kfp/v2/compiler/compiler_test.py
- Outputs without type or typed as "Artifact" can be passed to inputs typed as any artifact type.
For example, output with type `Artifact` can be passed to input with type `Dataset`.
- Outputs typed as arbitrary name cannot be used in the same way.
For example, output with type `SomeArbitraryType` **cannot** be passed to input with type `Dataset`.
**Checklist:**
=> feat(sdk): Type checking to treat "explicit" generic artifact as any artifact type.

sdk/python/kfp/__init__.py, sdk/python/kfp/_client.py, sdk/python/kfp/_credentials.py
The changes of this PR and their rationale are described in detail in https://github.com/kubeflow/pipelines/issues/5138#issuecomment-797003710.
In a nutshell:
1. Introduce the `TokenCredentials` abstract class, as described in kubeflow/pipelines#4683
2. ~Introduce the `ServiceAccountTokenVolumeCredentials` class to authenticate using ServiceAccountTokens, which is part of kubeflow/pipelines#5138~
3. Extend the `Client` to (optionally) expect a `credentials` object
4. ~If the user provides no credentials and the client is running inside a pod, attempt to use `ServiceAccountTokenVolumeCredentials`~
/assign @Bobgy  
/assign @elikatsis 
/cc @yanniszark 
/cc @StefanoFioravanzo
**Checklist:**
[Learn more about cherry-picking updates into the release …
=> feat(sdk): Introduce the token credentials interface. Part of #4683

.readthedocs.yml, components/google-cloud/RELEASE.md, components/google-cloud/container/aiplatform/Dockerfile, components/google-cloud/container/aiplatform/cloudbuild.yaml, components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py, components/google-cloud/google_cloud_pipeline_components/version.py, components/google-cloud/setup.py
Creating the release branch for first official pypi release of google-cloud-pipeline-components
this includes
- Updated .readthedocs.yml file for documentation generation. 
- Updated version number 
- RELEASE.MD docs
- Point default docker to official docker image for this release.
=> chore(components/google-cloud): Create Release Branch for Google cloud pipeline components 0.1.0

sdk/python/kfp/_client.py
Update the Python SDK documentation for the cron_expression parameter to kfp.Client().create_recurring_run
- Correct the stated number of cron expression fields required
- Add a link to the documentation for the cron expression format
**Checklist:**
=> fix(sdk): Update documentation for cron_expression parameter to kfp.Client().create_recurring_run 

samples/core/XGBoost/xgboost_sample.py
Update XGboost sample to use Predict components updated by https://github.com/kubeflow/pipelines/pull/5491.
The output `predictions` will be recognized as artifact in v2 & v2 compatible mode.
**Checklist:**
=> sample: Update xgboost_sample.py to make it compatible in both v1 and v2.

manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml
@Bobgy sorry for the inconvenience. Migrated from https://github.com/kubeflow/manifests/pull/1886
Kupeflow profile quota support is broken in Kubeflow 1.3 because all pipelines fail. Someone forgot to update the configmap properly when updating Argo.
The out of sync Kubeflow Argo does not set ressource requests on the init and wait containers which is needed for Kubeflow profile quota support. Argo upstream does so properly as seen here: 
https://github.com/argoproj/argo-workflows/blob/26f08c10ae3b88b3ee438cd1aba2ba1241e35cf9/docs/workflow-controller-configmap.yaml#L152
Take for example the profile from the Kubeflow documentation https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#manual-profile-creation that creates a quota which will prevent all pods from starting if …
=> Fix pipelines with Kubeflow profile quota

backend/src/common/util/parameter_formatter.go, backend/src/common/util/parameter_formatter_test.go, go.mod, go.sum
Placeholder format: `{{$.scheduledTime.strftime('%Y-%m-%d')}}`
=> Backend - Added modern time formatters

sdk/python/kfp/components/_data_passing.py, sdk/python/kfp/components/_python_op.py, sdk/python/kfp/components/type_annotation_utils.py, sdk/python/kfp/components/type_annotation_utils_test.py, sdk/python/kfp/components_tests/test_data_passing.py, sdk/python/kfp/dsl/type_utils.py, sdk/python/tests/dsl/component_tests.py
-  Extract the real type from `typing.Optional[<type>]`.
Before this change, a function-based component, like shown below,
```
@component
def some_op(a: Optional[str] = None):
...
```
when saved to a component YAML, will generate the YAML spec as follows: 
```
name: Some op
inputs:
- {name: a, type: typing.Optional[str], optional: true}
...
```
There're two issues with this YAML spec.
1. `typing.Optional[str]` contains redundant info, given the input spec also has `optional: true`. 
2. `typing.Optional[str]` would be recognized as an artifact in v2. Although we could fix this issue separately, but I think a better fix is to get rid of `Optional` from the beginning. 
After this change, the same function-based component will generate the YAML as follows:
``` …
```
=> feat(sdk): special handling for type annotation using `typing.Optional`

components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
EKS 1.15 is deprecated
https://aws.amazon.com/premiumsupport/knowledge-center/eks-end-of-support-kubernetes-115/
=> chore(components): AWS SageMaker update eks cluster version for tests

frontend/src/components/Metric.tsx, frontend/src/components/__snapshots__/Metric.test.tsx.snap, frontend/src/lib/RunUtils.ts, frontend/src/pages/RunList.test.tsx, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
Remove ordering of the metrics so that metrics are displayed in the order it was defined rather than in an alphabetical order
fixes #5215 
**Checklist:**
=> fix(frontend): Remove alphabetical sorting of the metrics column. Fixes #5215

sdk/python/kfp/__init__.py, test/release/bump-version-in-place.sh
It was accidentally overwritten by https://github.com/kubeflow/pipelines/commit/1c66f93f5149a8d5ed7f33895d3ebc01e662d837
**Checklist:**
=> chore: restore KFP SDK version to 1.6.2, decouple SDK release from KFP main release.

backend/src/cache/deployer/Dockerfile
Part of  https://github.com/kubeflow/manifests/pull/1756
The /kfp/cache/deployer directory is used to download stuff and must be fully accessible for any user.
```
+ echo 'Start deploying cache service to existing cluster:'
+ NAMESPACE=kubeflow
+ MUTATING_WEBHOOK_CONFIGURATION_NAME=cache-webhook-kubeflowStart deploying cache service to existing cluster:
+ WEBHOOK_SECRET_NAME=webhook-server-tls
+ mkdir -p //bin
+ export 'PATH=//bin:/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
+ kubectl version --output json
+ jq --raw-output '(.serverVersion.major + "." + .serverVersion.minor)'
+ tr -d '"+'
+ server_version_major_minor=1.20
+ curl -s https://storage.googleapis.com/kubernetes-release/release/stable-1.20.txt
+ stable_build_version=v1.20.7
+ …
```
=> Fix the cache-deployer to run as non root

.readthedocs.yml, components/google-cloud/RELEASE.md, components/google-cloud/container/aiplatform/Dockerfile, components/google-cloud/container/aiplatform/cloudbuild.yaml, components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py, components/google-cloud/google_cloud_pipeline_components/version.py, components/google-cloud/setup.py
Releasing Google cloud pipeline components 0.1.1. Includes: 
*   Fix issue with latest version of KFP not accepting pipeline_root in kfp.compile.
*   Fix Compatibility with latest AI Platform name change to replace resource name class with Vertex AI
=> chore(components/google-cloud): Create Release Branch for Google cloud pipeline components 0.1.1

sdk/python/kfp/dsl/_component_bridge.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.json, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.py
- Fixing a missing case from https://github.com/kubeflow/pipelines/pull/5183. Any additional input param resulted from string concatenation needs to be explicitly added to the op's inputs list. Otherwise, it will be missed out when it's not the only input.
- Updating the test sample to cover the scenario that was broken before the fix.
**Checklist:**
=> fix(sdk.v2): Fix the bug where string concat inside a loop may break compilation.

sdk/python/kfp/compiler/compiler.py
One of our test samples hit error: "invalid spec: templates.[...].parameters[4].name 'pipeline-output-directory' is not unique").
**Checklist:**
=> fix(sdk): Avoid inserting duplicate input parameters in v2 compatible mode.

sdk/python/kfp/cli/pipeline.py
When you upload pipeline which doesn't have parameter using kfp command line tool, you can see this message.
```bash
❯ kfp pipeline upload -p iris-pipeline-ci-test examples/iris_pipeline_example.yaml
'NoneType' object is not iterable
```
After this pr merged, you can see this message.
```bash
❯ kfp pipeline upload -p iris-pipeline-ci-test examples/iris_pipeline_example.yaml
Pipeline Details
------------------
ID           ebb77e3f-5959-442e-aab1-4469b8ff7995
Name         iris-pipeline-ci-test
Description
Uploaded at  2021-05-24T07:08:03+00:00
+------------------+-----------------+
| Parameter Name   | Default Value   |
+==================+=================+
+------------------+-----------------+
```
Signed-off-by: ByungchanKim <kbc8894@gmail.com>
=> fix(cli): handle when pipeline.paramters is None

samples/core/exit_handler/exit_handler.py, samples/core/loop_parameter/loop_parameter.py, samples/core/loop_static/loop_static.py, sdk/python/kfp/_config.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/compiler/v2_compatible_compiler_test.py, sdk/python/kfp/dsl/_component_bridge.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/kfp/v2/compiler/compiler.py, sdk/python/kfp/v2/compiler/compiler_test.py
- Turn `is_compiling_for_v2` (previously apply to v2 compiler only) into a global config, and make it cover v2 compatible mode as well. 
- Also raise error when users construct `ContainerOp` instances directly from user code.
Fixes: #5688, #5727
**Checklist:**
=> feat(sdk): Better error message when compiling for v2. Fixes #5688, Fixes #5727

sdk/python/kfp/v2/google/experimental/custom_job.py
`replica_count` is an optional arg of run_as_aiplatform_custom_job and the default value is `None`.
However, if it not set, it raises `TypeError: '>' not supported between instances of 'NoneType' and 'int'`.
I added the check if replica_count is not None.
**Checklist:**
=> fix(sdk, v2): Fix error when replica_count isn't set

v2/cmd/launch/main.go, v2/component/launcher.go, v2/objectstore/object_store.go, v2/objectstore/object_store_test.go
Fixes #5680
Investigation and rationale are logged in #5680.
Changes:
* Makes default pipeline root configurable via key `defaultPipelineRoot` in a configmap named `kfp-launcher` in the same namespace as the pipeline run.
* Defaults minio service to the same namespace via `MINIO_SERVICE_SERVICE_HOST` env var. When not found, fallbacks to `minio-service.kubeflow:9000` (default service name of MinIO in full Kubeflow).
How this PR makes kfp v2 compatible run on Kubeflow:
1. For distributions using MinIO, now we can auto discover the minio service in kubeflow namespace.
2. For distributions not using MinIO, they can configure default pipeline root to other storage URL, e.g. for Kubeflow on GCP, we can default pipeline root to a GCS path during deployment via …
=> feat(v2): enable v2 compatible mode in full Kubeflow with zero config. Fixes #5680

manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml, manifests/gcp_marketplace/schema.yaml
Fixes #5717
According to the issue, schema.yaml default values should match values.yaml, because schema.yaml's default values are what actually take effect when users do not specify some fields.
Note, this PR is hard to verify, so we need to verify before next release.
**Checklist:**
=> fix(deployment): GCP AI Platform Pipelines -- correct default values when some fields left empty. Fixes #5717

manifests/kustomize/base/installs/generic/kustomization.yaml, manifests/kustomize/base/installs/generic/params.yaml, manifests/kustomize/base/installs/generic/pipeline-install-config.yaml, manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/deployment.yaml, manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py, manifests/kustomize/base/pipeline/kfp-launcher-configmap.yaml, manifests/kustomize/base/pipeline/kustomization.yaml, manifests/kustomize/hack/test.sh
Part of #5680, Fixes #5704
The field `defaultPipelineRoot` field in `pipeline-install-config` can be used to configure both multi-user mode and KFP standalone.
This PR depends on feature in https://github.com/kubeflow/pipelines/pull/5697.
**Checklist:**
=> feat(deployment): configurable v2 compatible mode default pipeline root. Part of #5680. Fixes #5704

sdk/python/kfp/_auth.py
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
Add HTTP status code check for token request response and throw an HTTPError instead of KeyError when the returned status is not 2xx
fixes https://github.com/kubeflow/pipelines/issues/4312
**Checklist:**
=> fix(sdk): Add http status code check for token requests. Fixes #4312

v2/Makefile, v2/metadata/client.go, v2/metadata/client_test.go
put pipeline context as parent of run context
Part of #5669 
**Checklist:**
=> chore(launcher): put pipeline context as parent of run context. Part of #5669

backend/Dockerfile.scheduledworkflow, backend/src/crd/controller/scheduledworkflow/main.go
I've tried to log the Location, it shows the default location is `Local` no matter what the CRON_SCHEDULE_TIMEZONE is.  Here's maybe a bug, the `util.GetLocation()` in `init()` depends on the viper's config, but the viper config will be initialized from environment variables in `initEnv()`. But the `initEnv()` is invoked in `main()` in current code. 
The Go execution order is `init()` goes first and then the `main()`, so the `util.GetLocation()` will be execute BEFORE the `initEnv()`, the viper does not load the config from environment variables in that moment.
This PR moves `initEnv()` into `init()` to make sure the `util.GetLocation()` to be executed after `initEnv()`, so that the location can be loaded properly.
fixes https://github.com/kubeflow/pipelines/issues/2653#issuecomment-854387 …
=> fix(scheduledworkflow): Set location to make CRON timezone work, Fixes #2653

components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/minio/component.py, components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/minio/executor.py, components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/types/standard_component_specs.py, components/PyTorch/pytorch-kfp-components/tests/test_minio.py
Issue: #5768
This PR is dependent on the #5767
We are working on adding support for PyTorch in Kubeflow Pipelines.
there are multiple components involved in the PyTorch pipeline.
This PR contains the code for uploading files/folders to minio
The idea is to package all the components as pytorch-kfp-components. It will be a pip package.
The code for the pip package is placed under - pipelines/components/PyTorch/pytorch-kfp-components folder.
Users can install the pip package from this folder and use it in the examples.
We are working on adding the remaining components and the examples as separate PRs.
Please review and let us know your comments.
**Checklist:**
=> feat(components): Adding Minio component for PyTorch - KFP

samples/test/metrics_visualization_v2_test.py, samples/test/two_step_test.py, samples/test/util.py, v2/component/runtime_info.go
=> chore(launcher): move artifact metadata to metadata struct field. Fixes #5788

components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_common_ops.py, components/gcp/container/component_sdk/python/tests/google/dataflow/test__launch_python.py, components/gcp/container/component_sdk/python/tests/google/dataflow/test__launch_template.py, components/google-cloud/Optimizer/Add_measurement_for_trial/component.py, components/google-cloud/Optimizer/Add_measurement_for_trial/component.yaml, components/google-cloud/Optimizer/Create_study/component.py, components/google-cloud/Optimizer/Create_study/component.yaml, components/google-cloud/Optimizer/Suggest_parameter_sets_based_on_measurements/component.py, components/google-cloud/Optimizer/Suggest_parameter_sets_based_on_measurements/component.yaml, components/google-cloud/Optimizer/Suggest_trials/component.py, components/google-cloud/Optimizer/Suggest_trials/component.yaml, sdk/python/kfp/v2/google/client/client_utils.py, sdk/python/kfp/v2/google/client/client_utils_test.py
Update deprecated `download_as_string` to `download_as_bytes`, since `download_as_string` is deprecated. 
https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.download_as_string
=> chore: update deprecated download_as_string to download_as_bytes

frontend/src/components/Trigger.test.tsx, frontend/src/components/Trigger.tsx, frontend/src/components/__snapshots__/Trigger.test.tsx.snap, frontend/src/pages/NewRun.test.tsx
Change the default value of recurring pipeline runs from 1 Minute to 1 Hour
Tests updated to reflect new default value. 
Fixes: #5748
Signed-off-by: Diana Atanasova <dianaa@vmware.com>
**Checklist:**
=> refactor(frontend) Set 1 Hour as a default value for recurring pipeline runs

sdk/python/kfp/_local_client.py
I have found that `LocalClient` is not working in docker mode.
Main cause was docker run argument with wrong position of single quote and double quote.
Below is the example code that i used.
```python
import os
from pathlib import Path
from functools import partial
from kfp import LocalClient
from kfp.components import OutputPath, func_to_container_op
from kfp.dsl import pipeline
@partial(
func_to_container_op,
base_image="python:3.8-alpine",
)
def print_msg(msg_dir: OutputPath(), msg: str):
print(msg)
with open(msg_dir, "w") as f:
f.write(msg)
@pipeline(
name="example",
description="example pipeline",
)
def simple_piepeline(msg):
print_msg(msg=msg)
client = LocalClient(Path(os.getcwd()) / "local")
docker_run = …
```
=> feat(sdk): set shell=False to run LocalClient both docker and local mode

components/aws/OWNERS, components/aws/sagemaker/OWNERS, samples/contrib/aws-samples/OWNERS
Adds all of the current maintainers for the AWS components to the greater AWS components OWNERS list. Also adds all of these maintainers to the list of AWS samples OWNERS.
**Checklist:**
=> chore(components) - Add SageMaker component owners to AWS owners list

v2/cmd/launch/main.go, v2/component/launcher.go, v2/component/runtime_info.go
Fixes #5882 
Changes:
* make launcher log more things by default, and one flag can be used to easily enable info logging
* fix some error handling
* add stricter validation for artifact `metadataPath`
**Checklist:**
=> chore(launcher): improve launcher logging & fix some error handling. Fixes #5882

sdk/python/kfp/v2/compiler/compiler.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.json, sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.py
If `exit_handler` is used, an error will occur at compile time because inputs are not set for tasks in that group(https://github.com/kubeflow/pipelines/issues/5854)
So, set input as well as `condition` subgroup.
**Checklist:**
=> fix(sdk compiler):Fix v2 compile for exit handler  Fixes #5854

samples/test/lightweight_python_functions_v2_pipeline.py, samples/test/lightweight_python_functions_v2_pipeline_test.py, sdk/python/kfp/dsl/_component_bridge.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json, sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py, sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json
- Fix default value of component input not picked up in v2 and v2 compatible mode.
- This PR also introduce a behavior change for v1. Current in v1, the default value from component input spec, e.g: https://github.com/kubeflow/pipelines/blob/e7c281bd65ca79c20c2ae52a4dc4798241333b53/components/XGBoost/Train/component.yaml#L33
appears to be informational only. While the source of truth is inside the container, e.g.:
https://github.com/kubeflow/pipelines/blob/e7c281bd65ca79c20c2ae52a4dc4798241333b53/components/XGBoost/Train/component.yaml#L71
Normally, the two would be in sync if the component.yaml is generated by the SDK. However, they could be different if user hand-write the yaml. 
If user doesn't provide a value or param reference for such optional input, …
=> fix(sdk): Fix default value of component input not picked up. Fixes #5880.

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml, manifests/gcp_marketplace/test/snapshot-base.yaml, manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml, manifests/gcp_marketplace/test/snapshot-managed-storage.yaml, manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml
reduce artifact name collision rate under heavy load by including date into artifact key format.
The problem this fixes:
when load is heavy, there's a higher chance of getting two different pods with the same name.
In such a case, the pod will be getting the same output artifact names, because {{workflow.name}}/{{pod.name}} is the same. Then this pod will be overwriting existing artifacts, which is bad. What's worse, GCS
buckets typically have a retention period when overwriting is forbidden, so the new Pod will fail
instead. This causes intermittent workflow execution failures.
The new fix reduces the rate of artifact name collision by including the date in artifact key format.
Backwards compatibility concern: the config change only affects new pipeline …
=> fix(deployment): reduce artifact name collision rate under heavy load

samples/contrib/pytorch-samples/cifar10/cifar10_pytorch.py
With the PTL String passing changes, the confusion matrix url can be passed via `script_args` parameter  and there is no need for an explicit Argument parser for the same.
This PR is to remove the extra argument from Argument parser. 
**Checklist:**
=> chore(components/pytorch) Cifar 10 example - Confusion matrix Fix

components/google-cloud/README.md
* Update readme to refer to Vertex AI instead of AIP Unified
**Checklist:**
=> chore(components/google-cloud): Refer to Vertex AI instead of AI Platform (Unified)

samples/core/visualization/markdown.py, samples/core/visualization/markdown_test.py
Partial https://github.com/kubeflow/pipelines/issues/5932
Ability to run same pipeline for v1 and v2 compatible, it will generate Markdown for UI visualization.
Command to initialize test:
```
python3 -m samples.core.visualization.markdown_test
```
**Checklist:**
=> feat(sample): Add markdown visualization example for v1 and v2 compatible

samples/core/visualization/hello-world.html, samples/core/visualization/html.py, samples/core/visualization/html_test.py
Partial https://github.com/kubeflow/pipelines/issues/5932
Ability to run same pipeline for v1 and v2 compatible, it will generate HTML for UI visualization.
Command to initialize test:
```
python3 -m samples.core.visualization.html_test
```
User needs to upload sample HTML file to gcs location and update html.py to provide gcs path, if they want to see example other than static inline string.
**Checklist:**
=> feat(sample): Add HTML sample for v1/v2 visualization

components/google-cloud/docs/source/google_cloud_pipeline_components.aiplatform.rst
API doc generation changes where omitted from master, this is to bring master update to 0.1.2, see discussion on #5887.
=> chore(components/google-cloud): Merge v0.1.2 API doc changes in master

frontend/src/lib/MlmdUtils.ts, frontend/src/pages/ExecutionDetails.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Fix #5675
In V1 pipeline, we show artifact names by reading from event.
In V2 pipeline, we hide ML Metadata tab because Input/Output tab has already shown the same information.
**Checklist:**
=> feat(frontend): Support new artifact name retrival and hide MLMD tab in v2 pipeline. Fix #5675

sdk/python/kfp/_client.py
When giving list/dict inputs as part of your pipeline arguments, these values are json serialied instead of casted to string.
=> feat(sdk): json serialization of dict/list items in run args, fixes #5896

samples/core/visualization/confusion_matrix.csv, samples/core/visualization/confusion_matrix.py, samples/core/visualization/confusion_matrix_test.py
Partial https://github.com/kubeflow/pipelines/issues/5932
Ability to run same pipeline for v1 and v2 compatible, it will generate confusion matrix for UI visualization.
Command to initialize test:
```
python3 -m samples.core.visualization.confusion_matrix_test
```
User needs to upload sample confusion_matrix.csv file to gcs location and uncomment the bottom line of confusion_matrix.py to provide gcs path, if they want to see example other than public content like GitHub raw URL.
**Checklist:**
=> feat(samples): Confusion Matrix sample for v1/v2 visualization

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/compiler/main.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/two_step.py
Fixes https://github.com/kubeflow/pipelines/issues/5840
The env var is useful when a user has decided to use v2 compatible mode by default.
The user can set up the following in .bashrc:
```
export KF_PIPELINES_COMPILER_MODE=V2_COMPATIBLE
```
I tested locally by installing `pip install -e sdk/python`.
And then dsl-compile
* without --mode flag
* with --mode flag
* without --mode flag, but set KF_PIPELINES_COMPILER_MODE env var
all of these cases worked as expected
**Checklist:**
=> feat(sdk/dsl/compiler): dsl-compile --mode flag to turn on V2_COMPATIBLE, defaults to KF_PIPELINES_COMPILER_MODE env var. Fixes #5840

.readthedocs.yml, components/google-cloud/RELEASE.md, components/google-cloud/container/aiplatform/Dockerfile, components/google-cloud/container/aiplatform/cloudbuild.yaml, components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py, components/google-cloud/google_cloud_pipeline_components/version.py
Releasing Google cloud pipeline components 0.1.3 which Includes:
*   Use correct dataset type when passing dataset to CustomTraining.
*   Bump google-cloud-aiplatform to 1.1.1
=> chore(components/google-cloud): Create Release Branch for Google cloud pipeline components 0.1.3

backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go, backend/src/apiserver/resource/resource_manager_util.go, backend/src/apiserver/server/api_converter.go, backend/src/apiserver/server/api_converter_test.go, backend/src/common/util/template_util.go, backend/src/common/util/template_util_test.go, backend/src/common/util/workflow.go, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml, sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml, v2/component/launcher.go
Fixes #5978 
The change unifies pipeline name and pipeline MLMD context name for v2 compatible mode.
Behavior:
* when v2 compatible pipelines are compiled, their pipeline names will be `pipeline/<name>` (name is taken from `@pipeline(name='xxxx')` annotation)
* when compiled pipelines are uploaded to KFP API server, their pipeline names will be renamed to the KFP pipeline resource name. Depending on whether the pipeline is shared or namespaced, pipeline name will be `namespace/<ns>/pipeline/<name>` or `pipeline/<name>`.
**Checklist:**
=> chore(v2): unify pipeline name between MLMD and KFP DB. Fixes #5978

sdk/python/kfp/_client.py, sdk/python/kfp/v2/google/client/client.py
- Change the default for `enable_caching` in v2 client to `None`, so that if it's not explicitly set by users, we will honor the compile time settings rather than override them. 
- Also update the docstring in v1 client for the same argument.
**Checklist:**
=> feat(sdk.v2): enable_caching in v2 client defaults to compile time settings.

sdk/python/kfp/dsl/dsl_utils.py
This is a enhancement to `dsl_util.py` to support `ExecutorInputPlaceholder`.
=> feat(sdk): Add support for executor input in dsl_util.py

sdk/python/kfp/compiler/compiler.py
Argo now have linting in offline mode: https://github.com/argoproj/argo-workflows/pull/5569, we now use:
https://github.com/kubeflow/pipelines/blob/df1ab4db5e72e2ddb6f098343a3faf51599087d1/backend/Dockerfile#L36
in the `Dockerfile` and since Argo 3.1.1 supports offline linting i suggest we updated the error message and set it to `offline`
**Checklist:**
=> chore: add offline linting

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml, manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml
Fixes #5718 
Argo emissary executor requires that each container has explicit command and args defined, refer to https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary.
Why we decide to adopt the breaking change? We'd have the same breaking change in bit.ly/kfp-v2-compatible and bit.ly/kfp-v2. So I think it aligns with KFP's long term goal, and it's OK to introduce the breaking change now.
**Checklist:**
=> feat!: use argo emissary executor by default. Fixes #5718

sdk/python/kfp/v2/google/client/client.py
AiPlatformClient will be deprecated in SDK release 1.9 (target end of September). 
Current AiPlatformClient are recommended to switch over to use [Vertex SDK's](https://github.com/googleapis/python-aiplatform) `PipelineJob` through
```
pip install google-cloud-aiplatform
```
=> feat(sdk): add deprecation warning for AiPlatformClient

samples/test/util.py
In general, we should avoid using mutable default arguments. It's a common mistake that may cause unexpected behavior at some point. See https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
**Checklist:**
=> chore: Avoid mutable default arguments

components/google-cloud/container/gcp/Dockerfile
With `-m` option, we don't need the `.py` suffix. 
When `.py` is included, it seems running fine, but there's an error like this:
```
Error while finding module specification for 'launcher.py' (ModuleNotFoundError: __path__ attribute not found on 'launcher' while trying to find 'launcher.py')
```
Removing the `.py` suffix fixes the issue.
**Checklist:**
=> chore(components): fix gcp launcher command

sdk/python/kfp/compiler/compiler.py
From the docs of argo lint: 
```
--kinds strings   Which kinds will be linted. Can be: workflows|workflowtemplates|cronworkflows|clusterworkflowtemplates (default [all])
```
To validate:
```
cd pipelines/samples/core/resource_spec
python runtime_resource_request.py
argo --offline=true --kinds=workflows lint runtime_resource_request.py.yaml
```
expected output:
```
no linting errors found!
```
Sorry that i missed it forgot, and looked at the integration test that passed only. Will see if I can make a test to check the validation as part of the test suite. . 
The offline linting is only able to handled `workflows`(which is the only argo resource type used in kubeflow of `workflows|workflowtemplates|cronworkflows|clusterworkflowtemplates` ), I missed this in …
=> chore(sdk): Argo lint requires '--kinds=workflows' argument for offline linting. 

components/gcp/container/Dockerfile
I saw the error otherwise
```
unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Failed building wheel for google-cloud-profiler
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i1on4ezh/google-cloud-profiler_b49199e7f8bd42c685afdffc8a4294bc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-
```
**Checklist:**
=> chore: Fix error building component

frontend/src/components/viewers/PagedTable.tsx, frontend/src/components/viewers/__snapshots__/PagedTable.test.tsx.snap
We noticed that the PagedTable component was rendering "duplicated values".
Basically it was not rendering the new data, it was comparing the changes with the new ones and creating the update patch.
The `key` for each row of the `TableRow` from material-ui should be unique, which was not being respected if we use the value from the data that should be rendered.
Basically this just uses the index from the sorted data as `key` for the `TableRow` component and that's it.
You can check this working here: https://codesandbox.io/s/zen-fermi-b2k6b?file=/demo.tsx
This is a small port from this repository with static data and labels, just for test purpose.
Please let us know if you do not agree, we are more than pleased to change accordingly your needs.
Thanks 🙇 …
=> fix(sorting): use array index as key for TableRow

components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/custom_job_remote_runner.py, components/google-cloud/tests/experimental/custom_job/test_custom_job.py, components/google-cloud/tests/experimental/remote/gcp_launcher/test_custom_job_remote_runner.py
Add 83% code coverage for `custom_job_remote_runner.py`
```
----------- coverage: platform linux, python 3.8.8-final-0 -----------
Name                                                                                                              Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------------------------------------------------------------------------
google_cloud_pipeline_components/__init__.py                                                                          2      0   100%
google_cloud_pipeline_components/aiplatform/__init__.py                                                              29      0   100%
google_cloud_pipeline_components/aiplatform/utils.py …
```
=> chore(components/google-cloud): Add uni tests for Custom_job_remote_runner

frontend/src/Css.tsx, frontend/src/components/Router.tsx, frontend/src/components/__snapshots__/Router.test.tsx.snap, frontend/src/lib/Buttons.ts, frontend/src/pages/PipelineDetailsV2.test.tsx, frontend/src/pages/PipelineDetailsV2.tsx, frontend/src/pages/v2/StaticCanvas.tsx
Fix https://github.com/kubeflow/pipelines/issues/6179
1. Page url: `https://kfp_domain/v2/pipeline/details`
2. Render reactflow canvas by default
3. Doesn't take pipeline ID yet, because we are blocked on backend API implementation.
Keeping the change simple in this PR, the main goal is to introduce the basic layout of V2 pipeline detail page. You can visit using `IR Pipeline` button after you enabled the V2 feature.
**Checklist:**
=> feat(frontend): Introduce pipeline detail v2 page. Fix #6179

components/google-cloud/docs/regenerate_source_rst.sh, components/google-cloud/docs/run_simple_http_server.sh, components/google-cloud/docs/source/google_cloud_pipeline_components.aiplatform.rst, components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.custom_job.rst, components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.remote.gcp_launcher.rst, components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.remote.rst, components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.rst, components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.tensorflow_probability.anomaly_detection.rst, components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.tensorflow_probability.rst, components/google-cloud/docs/source/google_cloud_pipeline_components.rst, components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/__init__.py, components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/__init__.py, components/google-cloud/setup.py
Update autogenerated docs (rts files) in preparation for upcoming release to include experimental folder as well as custom_job documentation. 
This change also includes 
- Update to setup.py package to include all submodules including experimental folder. 
- Scripts to help with regeneration of documentation as well as running local server for debugging under `google-cloud/docs/regenerate_source_rst.sh` and `google-cloud/docs/run_simple_http_server.sh` respectively.
=> chore(components/google-cloud): Update Sphinx docs for google-cloud-pipeline-components
