components/google-cloud/README.md

TW edits for the Google Cloud Pipeline Components readme doc
**Checklist:**

docs(components/google-cloud): updates Google Cloud Pipeline components readme.md

---

backend/src/cache/client_manager.go
backend/src/cache/main.go

This PR adds support to the cache server to take extra parameters, such as SSL support when connecting to external databases. 
CC @arllanos
**Checklist:**

Support extra params for cache server db connection

---

sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
sdk/python/kfp/compiler/v2_compat.py

- Release SDK 1.6.0-rc.0 (cutting on this PR).
- Pin launcher image to 1.6.0-rc.0 label.
**Checklist:**

release(sdk): release SDK 1.6.0-rc.0

---

v2/go-mod-licenses.yaml
v2/third_party/NOTICES/licenses.txt
v2/third_party/license_info.csv

/cc @capri-xiyue 
**Checklist:**

chore(v2/release): update licenses for kfp-launcher

---

sdk/python/kfp/dsl/component_spec.py
sdk/python/kfp/dsl/component_spec_test.py
sdk/python/kfp/dsl/dsl_utils.py
sdk/python/kfp/dsl/dsl_utils_test.py
sdk/python/kfp/dsl/importer_node_test.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_loops.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json

chore(sdk.v2): remove "task-" prefix

---

samples/test/two_step_test.py
test/deploy-cluster.sh
v2/cmd/launch/main.go
v2/component/launcher.go

added default pipeline root
**Checklist:**

fix(v2): added default pipeline root

---

test/presubmit-tests-tfx.sh

test: pin google-cloud-bigquery to make TFX presubmit work

---

sdk/python/kfp/compiler/compiler.py

chore(sdk): warn v2 compatible mode is Beta quality

---

sdk/python/kfp/__init__.py

release(sdk): Release KFP SDK 1.6.0

---

sdk/python/kfp/__init__.py
sdk/python/kfp/v2/google/client/client.py

release(sdk): release SDK 1.6.1 with minor fix in AIPlatformClient

---

api/v2alpha1/pipeline_spec.proto

Update IR documentations
**Checklist:**

Update IR documentations

---

sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
sdk/python/kfp/compiler/v2_compat.py

release: KFP SDK and v2 launcher 1.6.2

---

frontend/src/pages/GettingStarted.tsx
frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap

The link creates a Notebook with TF 2.3 instead of 2.1. I think that it might be better to just state that it is a notebook.
**Checklist:**

fix(frontend): Update the link text to the GCP CAIP Notebook

---

sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
sdk/python/kfp/compiler/v2_compatible_compiler_test.py

So that we don't need to update the test golden for every launcher image release.
**Checklist:**

test(sdk): v2 compatible UT to ignore launcher image label

---

components/google-cloud/dependencies.py
components/google-cloud/google_cloud_pipeline_components/aiplatform/remote_runner.py
components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
components/google-cloud/google_cloud_pipeline_components/version.py
components/google-cloud/tests/aiplatform/test_componets_compile.py
components/google-cloud/tests/aiplatform/test_remote_runner.py
components/google-cloud/tests/aiplatform/test_utils.py

fix(components): replace resource name class with vertex ai

---

samples/OWNERS

chore: Adding chensun in samples/OWNERS

---

components/google-cloud/RELEASE.md
components/google-cloud/google_cloud_pipeline_components/version.py
components/google-cloud/setup.py

* Update version number
* Add project email to `setup.py`
* Update `Release.MD`

chore(components/google-cloud): Post release clean up tasks

---

api/OWNERS
sdk/OWNERS

chore: Adding ji-yaqi to API & SDK OWNERS files, remove inactive members.

---

backend/src/apiserver/resource/resource_manager_util.go
backend/src/apiserver/resource/resource_manager_util_test.go

phase Fixes #5537
**Checklist:**

fix(backend): Fixed workflow cannot be retried with node xxx in Omitted

---

components/google-cloud/README.md
components/google-cloud/examples/README.md

- Update samples read me with a link to aiplatfrom samples
- Update main page ReadME with a link to API docs

chore(components/google-cloud): update readme with link to samples & api docs

---

components/google-cloud/container/aiplatform/Dockerfile
components/google-cloud/dependencies.py

fix(components/google-cloud): update version to include google-cloud-aiplatform fix

---

OWNERS

chore: Adding chensun in KFP root OWNERS

---

AUTHORS

Fixes https://github.com/kubeflow/pipelines/issues/5470
According to https://opensource.google/docs/releasing/authors/, add `AUTHORS` file, so that individual contributors can request to add their names centrally in this file. This PR only sets up the process. Anyone who has contributed before can request to add their names in a separate PR.
**Checklist:**

chore: set up AUTHORS file. Fixes #5470

---

samples/core/ai_platform/ai_platform.ipynb

Fixes https://github.com/kubeflow/pipelines/issues/5775
**Checklist:**

test(samples): fix ai_platform.ipynb. Fixes #5775

---

api/v2alpha1/python/setup.py

release(api): Bump kfp-pipeline-spec version to 0.1.8

---

sdk/python/kfp/compiler/_data_passing_rewriter.py

Found the placeholders may present in container env with https://github.com/kubeflow/pipelines/tree/master/components/google-cloud/google_cloud_pipeline_components
**Checklist:**

fix(sdk): resolve pipeline_root and run_uid placeholders in container env

---

.cloudbuild.yaml
.release.cloudbuild.yaml
backend/metadata_writer/requirements.in
backend/metadata_writer/requirements.txt
frontend/package-lock.json
frontend/package.json
manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
test/tag_for_hosted.sh
v2/Makefile
v2/test/requirements.txt

Needed by https://github.com/kubeflow/pipelines/pull/5785
**Checklist:**

feat: update MLMD to 1.0.0

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/tabs/MetricsTab.test.tsx
frontend/src/components/tabs/MetricsTab.tsx
frontend/src/components/viewers/ConfusionMatrix.tsx
frontend/src/components/viewers/MetricsVisualizations.tsx
frontend/src/components/wrappers/MetricsVisualizations.tsx

Partial https://github.com/kubeflow/pipelines/issues/5668.
Showing confusion matrix
Showing confusion matrix with ROC curve
**Checklist:**

feat(frontend): Support v2 confusion matrix visualization. Issue #5668

---

sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/v2_compat.py

release: KFP SDK and v2 launcher 1.6.3

---

sdk/python/build.sh

chore: update python version for build.sh

---

components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/visualization/component.py
components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/visualization/executor.py
components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/types/standard_component_specs.py
components/PyTorch/pytorch-kfp-components/tests/test_visualization.py

Signed-off-by: ankan94 <ankan@ideas2it.com>
Issue: #[5768](https://github.com/kubeflow/pipelines/issues/5768)
This PR is dependent on the #[5767](https://github.com/kubeflow/pipelines/pull/5767)
We are working on adding support for PyTorch in Kubeflow Pipelines.
there are multiple components involved in the PyTorch pipeline.
This PR contains the code for adding visualization in Kubeflow
The idea is to package all the components as pytorch-kfp-components. It will be a pip package.
The code for the pip package is placed under - pipelines/components/PyTorch/pytorch-kfp-components folder.
Users can install the pip package from this folder and use it in the examples.
We are working on adding the remaining components and the examples as separate PRs.
Please …

feat(components): Adding Visualization component for PyTorch - KFP

---

frontend/src/components/tabs/MetricsTab.test.tsx
frontend/src/components/viewers/MetricsVisualizations.tsx

Partial https://github.com/kubeflow/pipelines/issues/5668
Will need to be changed to use metadata after data move from customProperties to metadata.
**Checklist:**

feat(frontend): Support Scalar metrics in V2 compatible mode. Partial #5668

---

samples/core/volume_ops/volume_ops.py

feat(samples): volume ops example to not use container op. Part of #5687

---

components/google-cloud/google_cloud_pipeline_components/aiplatform/__init__.py

Adding components for 
* TimeSeriesDatasetCreateOp
* TimeSeriesDatasetExportDataOp
* AutoMLForecastingTrainingJobRunOp

feat(components/google-cloud): Add components for AutoMLForecasting

---

samples/core/pipeline_parallelism/pipeline_parallelism_limits.py

feat(samples): update set parallelism limit example to not use container op. Part of #5687

---

components/tensorflow/tensorboard/prepare_tensorboard/component.yaml
samples/core/visualization/tensorboard_gcs.py
samples/core/visualization/tensorboard_minio.py
samples/core/visualization/tensorboard_minio_test.py
sdk/python/kfp/compiler/v2_compat.py
sdk/python/kfp/dsl/_container_op.py

Part of #5666 
The pipeline properly generates the `mlpipeline-ui-metadata` artifact.
Content in the artifact is not fully correct, but the problem is unrelated to this PR, it's tracked in https://github.com/kubeflow/pipelines/issues/5830
```
$ gsutil cat gs://gongyuan-dev/v2-sample-test/data/samples_config-loop-item/pipeline-tensorboard-minio/pipeline-tensorboard-minio-spt2m/create-tensorboard-visualization/mlpipeline-ui-metadata
{
"outputs" : [{
"type": "tensorboard",
"source": "s3://mlpipeline/tensorboard/logs/489a0259-33f4-4d1a-845f-9b68f388c8c7",
"image": "gcr.io/deeplearning-platform-release/tf2-cpu.2-3:latest",
"pod_template_spec": {\"spec\": {\"containers\": [{\"env\": [{\"name\": \"AWS_ACCESS_KEY_ID\", \"valueFrom\": {\"secretKeyRef\": {\"name\": …
```

fix(sdk/compiler): v2 compat - fix mlpipeline-ui-metadata artifact. Part of #5666

---

components/gcp/container/component_sdk/python/kfp_component/google/dataflow/__init__.py
components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_client.py
components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_launch_flex_template.py
components/gcp/container/component_sdk/python/tests/google/dataflow/test__launch_flex_template.py
components/gcp/dataflow/launch_flex_template/README.md
components/gcp/dataflow/launch_flex_template/component.yaml
components/gcp/dataflow/launch_flex_template/sample.ipynb

1. Added an api to launch flex template jobs in the Dataflow client in the component_sdk.
2. Added a flex template launcher module: `_launch_flex_templates.py` similar to the existing `_launch_template.py` module based on the parameters specified in the REST API call for launching flex templates: https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.flexTemplates/launch
3. Corresponding component specification to support launching flex template based Dataflow jobs in the Kubeflow pipeline step.
**Checklist:**
- [ x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull- …

feat(sdk): Support launching Dataflow Flex templates from Kubeflow pipelines

---

v2/component/runtime_info_test.go
v2/test/presubmit-v2-go-test.sh

fixed presubmit v2 go test
**Checklist:**

test(v2): fixed presubmit v2 go test

---

frontend/src/components/UploadPipelineDialog.tsx
frontend/src/pages/NewPipelineVersion.tsx

Update location: 
Thank you @DavidSpek for reporting this!
**Checklist:**

fix(frontend): Update instruction link in upload pipeline page.

---

components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/trainer/executor.py
samples/contrib/pytorch-samples/Dockerfile-cpu
samples/contrib/pytorch-samples/bert/agnews_classification_pytorch.py
samples/contrib/pytorch-samples/requirements.txt

PyTorch tensorboard profiler plugin is broken and this PR contains the fix for it.
**Checklist:**

fix(components/pytorch) Pytorch - Tensorboard Profiler fix

---

v2/README.md

update README to match Makefile variable name.
**Checklist:**

chore: update document for LAUNCHER_IMAGE_DEV

---

samples/contrib/pytorch-samples/Dockerfile-cpu
samples/contrib/pytorch-samples/Dockerfile-gpu
samples/contrib/pytorch-samples/Pipeline-Bert.ipynb
samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb
samples/contrib/pytorch-samples/README.md
samples/contrib/pytorch-samples/bert/agnews_classification_pytorch.py
samples/contrib/pytorch-samples/bert/config.properties
samples/contrib/pytorch-samples/bert/requirements.txt
samples/contrib/pytorch-samples/cifar10/cifar10_pytorch.py
samples/contrib/pytorch-samples/cifar10/config.properties
samples/contrib/pytorch-samples/cifar10/requirements.txt
samples/contrib/pytorch-samples/install-dependencies.sh
samples/contrib/pytorch-samples/mino-secret.yaml
samples/contrib/pytorch-samples/package.json
samples/contrib/pytorch-samples/prerequisites.md

- Adds requirements.txt for mar generation 
- Notebook clean to skip root access
- Adds package.json
The PR adding requirments.txt in marfile for torchserve.
Enables dependencies to be installed without root acces in jupyter notebook.

feat(components/pytorch): Add requirement for mar generation

---

samples/test/lightweight_python_functions_v2_pipeline.py
samples/test/lightweight_python_functions_v2_pipeline_test.py

Pipeline run logs: 
**Checklist:**

test(sdk/v2compat): reproduce v2 py component default value does not work

---

backend/OWNERS

/assign @capri-xiyue
**Checklist:**

chore: add capri-xiyue to backend OWNERS

---

ROADMAP.md

Update KFP 2021 roadmap
**Checklist:**

doc: KFP 2021 roadmap

---

sdk/python/kfp/cli/run.py

Fixes #5806 
add timeout option to `kfp run submit`.
Currently, `kfp run submit` doesn't care about such run finished or not. It is an async request.
Also, 'kfp run submit -w` will stay forever if such run doesn't completed forever.
This pr's feature would be useful to someone who want to get notified just in time when run submit succeeded or failed and who knows approximate completion time of such run.
For those who use `kfp run submit -t <timeout>`, it means something wrong happens if such run won't finish in entered timeout.
- for example
- `kfp run submit -t 60` will wait 60 seconds max. or finished before 60 seconds if such run's status became one of ['succeeded', 'failed', 'skipped', 'error']
**Checklist:**

feat(sdk): add timeout option to kfp run submit. Fixes #5806

---

components/google-cloud/RELEASE.md
components/google-cloud/container/aiplatform/cloudbuild.yaml
components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
components/google-cloud/google_cloud_pipeline_components/version.py

- Update version.py 
- Update release notes
- Fix issue in docker build config.

chore(components/google-cloud): Post release updates

---

sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/v2_compat.py

chore: release KFP SDK and v2 launcher 1.6.4

---

components/gcp/dataflow/launch_python/sample.ipynb

- Fix broken Jupyter notebook of GCP Dataflow example.

chore: fix broken ipynb notebook

---

components/PyTorch/pytorch-kfp-components/setup.py
samples/contrib/pytorch-samples/bert/requirements.txt
samples/contrib/pytorch-samples/cifar10/requirements.txt
samples/contrib/pytorch-samples/requirements.txt

Current pytorch examples uses pytorch lightning 1.3.2
This PR contains code change for updating the pytorch lightning version to 1.3.7 - latest.
**Checklist:**

chore(components/pytorch) Updating pytorch lightning version to 1.3.7

---

.github/semantic.yml

Fixes https://github.com/kubeflow/pipelines/issues/5942
This bot will automate enforcement of this convention:
https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention
**Checklist:**

chore: configure semantic pull requests bot. Fixes #5942

---

components/google-cloud/OWNERS

Adding ji-yaqi to Approvers / Reviewers and updating list for google-cloud component folder.

chore(components/google-cloud): Update OWNERS

---

components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
components/google-cloud/tests/aiplatform/test_utils.py

fix(components/google-cloud): Use correct dataset type when passing dataset to Custom*Training. Fixes #5885

---

backend/Dockerfile
test/install-argo-cli.sh
test/sample-test/Dockerfile

Updates URL of argo release:
From: https://github.com/argoproj/argo/releases/download/v3.1.0/argo-linux-amd64.gz
To: https://github.com/argoproj/argo-workflows/releases/download/v3.1.0/argo-linux-amd64.gz
The argoproj/argo repository is now redirecting to argoproj/argocon21. argoproj/argo-workflows appears to be the updated URL.
**Checklist:**

test: use new argo CLI URL

---

go.mod

chore: clean up go.mod. 

---

README.md
backend/Dockerfile
components/aws/sagemaker/tests/integration_tests/Dockerfile
components/gcp/automl/prediction_service_batch_predict/component.py
components/gcp/automl/prediction_service_batch_predict/component.yaml
components/gcp/container/component_sdk/python/kfp_component/google/bigquery/_query.py
components/google-cloud/Optimizer/_samples/multi_stage_optimization_atomic_pipeline.py
components/google-cloud/Optimizer/_samples/multi_stage_optimization_pipeline.py
frontend/src/pages/NewRun.tsx
frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
frontend/third_party/argo-ui/argo_template.ts
sdk/python/kfp/cli/run.py
sdk/python/kfp/dsl/_container_op.py
sdk/python/kfp/dsl/_resource_op.py
sdk/python/tests/compiler/compiler_tests.py
test/install-argo.sh
third_party/license.txt

URLs referencing the argoproj/argo repository are redirecting to argoproj/argocon21. These URLs should be referencing argoproj/argo-workflows.
**Checklist:**

chore: Updates argoproj/argo URLs to argoproj/argo-workflows

---

sdk/python/kfp/containers/_container_builder.py

ContainerBuilder has kaniko executor image path hard set to the open GCR kaniko-project repository.
However, for users running Kubernetes with closed GCR repositories (aka only certain GCR repositories are allowlisted), this makes the default ContainerBuilder not possible to use. By parametrizing, we can allow users to overwrite the fields if needed.
At Twitter, we had to manually overwrite this field to replace it with an GCR path with the image re-uploaded on an allowlisted internal repository.
However this overwrite is using private APIs of this class. Instead of doing that, we would prefer to parametrize ContainerBuilder so that we don't have to rely on private APIs.

feat(sdk): Make kaniko_executor_image a parameter for ContainerBuilder

---

sdk/python/kfp/v2/google/client/client.py
sdk/python/kfp/v2/google/client/schedule.py

Make it possible to use a custom service account in the scheduled pipeline jobs.
**Checklist:**

feat(v2,sdk): Add service_account as args to create_schedule_from_job_spec

---

v2/test/sample_test.py

This should make the tests less flaky.

test: Added test case retries

---

backend/Dockerfile
backend/src/apiserver/config/sample_config.json
samples/v2/lightweight_python_functions_v2_pipeline/lightweight_python_functions_v2_pipeline.py

Added data passing sample, mostly a copy of https://github.com/kubeflow/pipelines/blob/master/samples/test/lightweight_python_functions_v2_pipeline.py
Added a parameter in sample_config.json to indicate compilation mode.

feat(backend): add V2 lightweight Python pipeline sample. Fixes #5689

---

RELEASE.md

docs(release): clean up retry cloudbuild task instructions

---

test/presubmit-tests-tfx.sh

test: Address TFX presubmit test failure

---

v2/cmd/launch/main.go
v2/component/launcher.go
v2/metadata/client.go

1. remove redundant mlmd call
2. fixed flag parse bug
**Checklist:**

chore(v2): remove redundant mlmd call and fixed flag parse bug

---

backend/metadata_writer/src/metadata_writer.py
backend/src/cache/server/mutation.go
backend/src/cache/server/mutation_test.go

fix(tfx): fix missing mlmd data when sdk label is overridden. Fixes #5303

---

RELEASE.md
test/release/README.md
test/release/release.sh

Reverts kubeflow/pipelines#5974
Refer to rationale in https://github.com/kubeflow/pipelines/issues/5954#issuecomment-879558287
/assign @NikeNano

revert: feat: change release tags to vX.Y.Z. Part of #5954

---

v2/cmd/launch/main.go

fixed print typo
**Checklist:**

chore(v2): fixed print typo

---

samples/test/config.yaml
samples/test/data_passing.py
samples/test/data_passing_test.py

Added data passing tests. This would be useful for checking the KFP-Tekton compatibility.

test(sdk): Added data passing tests

---

sdk/python/kfp/components/_python_to_graph_component.py

This functionality already exists in `create_component_from_func` adding it to `create_graph_component_from_pipeline_func` as well.

feat(sdk): Components - Added support for annotations to create_graph_component_from_pipeline_func

---

components/kfp/Run_component/_samples/sample_pipeline.py
components/kfp/Run_component/component.py
components/kfp/Run_component/component.yaml

This can be useful for dynamically running components or pipelines.

feat(components): KFP - Run component

---

backend/Dockerfile.visualization
backend/src/apiserver/visualization/requirements.in
backend/src/apiserver/visualization/requirements.txt
backend/src/apiserver/visualization/update_requirements.sh
developer_guide.md
frontend/src/lib/OutputArtifactLoader.ts

Fix #6053.
Reference PR to revert: https://github.com/kubeflow/pipelines/pull/5999
**Checklist:**

chore(visualization): Revert to tensorflow image because tfx image is too big. Fix #6053

---

components/google-cloud/setup.py

This feature is to add componet `*.yaml` files to the python package and distribution.

feat(components/google-cloud): Add yaml files to python package

---

components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_gcs/README.md
components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_gcs/component.yaml
components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_table/README.md
components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_table/component.yaml

Forked the `to_gcs` and `to_table components and applied a change to the datatype that switched out GCSPath for String and GCPProjectID to String.

fix: Forked and applied fix to BigQuery to_gcs and to_table components

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
manifests/kustomize/third-party/argo/upstream/manifests/base/crds/minimal/argoproj.io_clusterworkflowtemplates.yaml
manifests/kustomize/third-party/argo/upstream/manifests/base/crds/minimal/argoproj.io_cronworkflows.yaml
manifests/kustomize/third-party/argo/upstream/manifests/base/crds/minimal/argoproj.io_workfloweventbindings.yaml
manifests/kustomize/third-party/argo/upstream/manifests/base/crds/minimal/argoproj.io_workflows.yaml
manifests/kustomize/third-party/argo/upstream/manifests/base/crds/minimal/argoproj.io_workflowtemplates.yaml

workaround fix until [proper fix](https://github.com/kubernetes/kubernetes/issues/102749#issuecomment-871053506) propagates through the k8s versions in cloud providers
related PR
https://github.com/argoproj/argo-workflows/pull/6350
**Checklist:**

fix(deployment): workaround fix, 34s timeout bug for argo crd on k8s1.20+

---

frontend/src/components/Trigger.tsx
frontend/src/components/__snapshots__/Trigger.test.tsx.snap

- Add `target='_blank'` to the `a` tag.
- Also include `rel='noreferrer'` because of a secure risk: https://html.spec.whatwg.org/multipage/links.html#link-type-noopener
- Update snapshot with `npm test -u`.
- Fix issue https://github.com/kubeflow/pipelines/issues/6068.
**Checklist:**

fix(ui): fixes cron format go.doc link. Fixes #6068

---

frontend/src/pages/RunDetails.tsx

Fix #6065
Reference: https://www.typescriptlang.org/docs/handbook/enums.html#numeric-enums
**Checklist:**

fix(frontend): Fix the enum iterator of tabs. Fix #6065

---

samples/contrib/pytorch-samples/prerequisites.md

fix readme document
**Checklist:**

fix(components/pytorch): readme update

---

sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/v2_compat.py

chore: release KFP SDK and v2 launcher 1.6.5

---

sdk/python/kfp/v2/google/client/client.py
sdk/python/kfp/v2/google/client/schedule.py

Fixed several typos and removed not referred private functions in google client SDK
**Checklist:**

chore: Fixed typos and removed not referred private functions in google client SDK

---

components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/tfp_anomaly_detection.ipynb

- Add demo notebook with anomaly detection component for time series data
- Uses open source APIs in TensorFlow Probability
**Checklist:**

feat(components/google-cloud): Add tfp_anomaly_detection component

---

sdk/python/kfp/v2/google/client/client.py

Fix type hints of `create_run_from_job_spec` from `str` to `dict`. This PR close #6092 
**Checklist:**

fix(sdk): Fix type hints for create_run_from_job_spec. Fixes #6092

---

samples/core/sidecar/sidecar.py
test/build_image.yaml
test/component_test.yaml
test/e2e_test_gke_v2.yaml
test/frontend-integration-test/run_test.sh
test/sample-test/configs/sidecar.config.yaml
test/sample_test.yaml
test/upgrade_test_setup.yaml

the updated samples can be run on argo emissary executor
Part of https://github.com/kubeflow/pipelines/issues/5718
**Checklist:**

test: prepare samples to be emissary executor compatible. Part of #5718

---

sdk/python/kfp/v2/google/client/client.py
sdk/python/kfp/v2/google/client/schedule.py

For feature parity with `create_run_from_job_spec`.
**Checklist:**

feat(sdk.v2): add `enable_caching` option in `create_schedule_from_job_spec`

---

frontend/src/TestUtils.ts
frontend/src/features.ts
frontend/src/index.tsx
frontend/src/lib/Buttons.ts
frontend/src/lib/Utils.tsx
frontend/src/pages/PipelineList.test.tsx
frontend/src/pages/PipelineList.tsx

Partial #6073
Currently the way to configure feature flag is by editing the features.ts file. The experiment is hidden behind `v2` flag.
**Checklist:**

chore(frontend): Add feature flag mechanism to control v2 development. Partial #6073

---

frontend/src/lib/WorkflowParser.test.ts
frontend/src/lib/WorkflowParser.ts
frontend/src/pages/RunDetails.tsx
frontend/src/pages/Status.tsx

Partial #5977
When this is v2 compatible pipeline, and the MLMD execution state is cached, added cache state icon.
**Checklist:**

feat(frontend): Show cache icon for v2 compatible. Partial #5977

---

sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/v2_compat.py
sdk/python/tests/compiler/compiler_tests.py

chore: release KFP SDK and v2 launcher 1.6.6

---

test/presubmit-tests-tfx.sh

test: restore penguin_pipeline_kubeflow_test

---

v2/component/launcher.go
v2/metadata/client.go

add cached execution id
**Checklist:**

chore(v2): add cached execution id

---

v2/compiler/testdata/Makefile
v2/compiler/testdata/component_used_twice.json
v2/compiler/testdata/component_used_twice.py
v2/compiler/testdata/hello_world.json
v2/compiler/testdata/producer_consumer_param.json
v2/compiler/visitor.go
v2/compiler/visitor_test.go

Backend compiler: KFP v2alpha1 pipeline spec to argo workflow compiler.
I'll build backend compiler as the visitor pattern, this allows decoupling IR spec iteration code with validation/compilation code.
**Checklist:**

chore(v2): backend compiler -- visitor

---

components/gcp/dataflow/launch_python/component.yaml
components/gcp/ml_engine/deploy/component.yaml
components/gcp/ml_engine/train/component.yaml

fixed samples to be emissary compatible
**Checklist:**

test: fixed samples to be emissary compatible

---

components/gcp/bigquery/query/to_gcs/component.yaml
samples/core/ai_platform/ai_platform.ipynb
samples/core/dataflow/dataflow.ipynb

Fixed sample uri
**Checklist:**

fix(test): fixed sample uri

---

components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/component.yaml
components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/tfp_anomaly_detection.ipynb
components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/tfp_anomaly_detection.py

- Remove pandas dataframe row limit in tfp_anomaly_detection and advise users to set_memory_limit instead
- Add visualization for pipeline results
**Checklist:**

feat(components/google-cloud): Update tfp_anomaly_detection to accept input csvs and show visualization

---

components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/__init__.py
components/PyTorch/pytorch-kfp-components/setup.cfg

This PR contains changes for releasing a new version of pytorch-kfp-components pip package - https://pypi.org/project/pytorch-kfp-components/
**Checklist:**

chore(components/pytorch): pytorch-kfp-components version update

---

v2/Makefile
v2/README.md
v2/cmd/launcher-v2/main.go
v2/compiler/argo_test.go
v2/compiler/container.go
v2/component/launcher.go
v2/component/launcher_v2.go
v2/container/launcher-v2/Dockerfile.dev
v2/metadata/client.go

Fixes #6147 
This PR supports hello world sample -- input parameter placeholder & basic publisher.
**Checklist:**

chore(v2): v2 launcher with basic publisher. Fixes #6147

---

v2/Makefile
v2/README.md
v2/cmd/compiler/main.go
v2/compiler/argo.go
v2/compiler/argo_test.go
v2/compiler/container.go

Fixes https://github.com/kubeflow/pipelines/issues/6183
Changes:
* make images configurable, so people can use their own image registries
* refactor Makefile to document and simplify development workflow
* document development workflow
**Checklist:**

chore(v2): enable, simplify & document v2 development workflow. Fixes #6183

---

components/kubeflow/pytorch-launcher/Dockerfile
components/kubeflow/pytorch-launcher/sample.py
components/kubeflow/pytorch-launcher/src/__init__.py

Fixes review comments of PR #5170

fix(components/kubeflow): PyTorchJob launcher

---

components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/launcher.py
components/google-cloud/tests/experimental/remote/gcp_launcher/test_launcher.py

update launcher code & add unit test coverage to 96%. 
```
----------- coverage: platform linux, python 3.8.8-final-0 -----------
Name                                                                                                              Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------------------------------------------------------------------------
google_cloud_pipeline_components/__init__.py                                                                          2      0   100%
google_cloud_pipeline_components/aiplatform/__init__.py                                                              29      0   100%
google_cloud_pipeline_components/aiplatform/utils.py …
```

chore(components/google-cloud): Add unit tests for launcher.py

---

samples/contrib/pytorch-samples/Dockerfile
samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
samples/contrib/pytorch-samples/README.md
samples/contrib/pytorch-samples/cluster_build.md
samples/contrib/pytorch-samples/contributing.md
samples/contrib/pytorch-samples/local_build.md
samples/contrib/pytorch-samples/prerequisites.md

Update and restructure of readme docs.

fix(components/pytorch): Update Readme docs

---

samples/test/config.yaml
samples/test/util.py
samples/v2/hello_world.py
samples/v2/hello_world_test.py
sdk/python/kfp/dsl/_container_op.py
v2/Makefile
v2/compiler/argo.go
v2/compiler/argo_test.go
v2/compiler/container.go
v2/compiler/dag.go
v2/component/launcher_v2.go
v2/container/driver/Dockerfile
v2/container/driver/Dockerfile.dev
v2/container/launcher-v2/Dockerfile
v2/driver/driver.go
v2/metadata/client.go
v2/test/components/kaniko.yaml
v2/test/components/run_sample.yaml
v2/test/sample_test.py

Changes:
* let v2 sample test support v2 engine mode
* add hello world v2 sample as v2 engine sample test
* refactor dockerfiles to utilize caching, enable kaniko caching. Fixes #6063 
* add memory/cpu requests & limits to stablize v2 sample test
* minor fixes to v2 launcher, so that emitted MLMD data is compatible with v2 sample test util.
**Checklist:**

test(v2): v2 sample test supports v2 engine mode

---

components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/component.yaml
components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/tfp_anomaly_detection.ipynb
components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/tfp_anomaly_detection.py

- Fills in missing values from regularizing series in anomaly detection component
- Modifies visualization to account for placeholders from missing values
- Adds scoring scripts for Numenta Anomaly Benchmark (NAB)
**Checklist:**

feat(components/google-cloud): Add NAB scoring to tfp_anomaly_detection

---

frontend/README.md
frontend/src/components/Router.tsx
frontend/src/components/__snapshots__/Router.test.tsx.snap
frontend/src/features.ts
frontend/src/pages/FrontendFeatures.tsx

Fix #6073
Because frontend development for KFP v2 is huge, we will embed the changes which are hidden behind a flag. For easily disabling and enabling hidden features, create a secret page for feature flags toggling.
URL: http://localhost:3000/#/frontend_features
**Checklist:**

chore(frontend): Create a secret page for managing frontend features visibility. Fix #6073

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml

Reverts kubeflow/pipelines#5926

revert: "feat!: use argo emissary executor by default. Fixes #5718"

---

backend/Dockerfile

Fixes https://github.com/kubeflow/pipelines/issues/5689
**Checklist:**

chore(backend): pin sdk version to released version. Fixes #5689

---

samples/core/resource_spec/resource_spec.py
samples/core/visualization/tensorboard_minio.py
samples/test/util.py
sdk/python/kfp/dsl/_container_op.py
sdk/python/kfp/onprem.py

Changes:
* add a new op transformer -> "add_default_resource_spec", it adds default memory limit and request to ContainerOp that do not specify a resource spec
* change v2 sample test to specify cpu/memory request/limit on all tasks, so that they can run stably with enough resources
**Checklist:**

feat(sdk): add_default_resource_spec container op transformer

---

backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/apiserver/storage/run_store.go
backend/src/apiserver/storage/run_store_test.go
backend/src/common/util/error.go
go.mod
go.sum

fix(backend): argo workflow not found in KFP DB should be GCed. Part of #6189

---

components/OWNERS

chore: update component owner file

---

api/Makefile

chore: make directories before downloading api dependency proto

---

backend/src/crd/controller/scheduledworkflow/client/kube_client.go
samples/core/caching/caching.ipynb
samples/core/caching/caching_sample.py

Fix the spelling of "successful". This is technically user-facing in that it changes a status message in the scheduledworkflow crd.
**Checklist:**

fix: fix a spelling error

---

samples/test/config.yaml
samples/v2/producer_consumer_param_test.py
v2/cmd/launcher-v2/main.go
v2/compiler/argo.go
v2/compiler/argo_test.go
v2/compiler/container.go
v2/compiler/dag.go
v2/component/launcher.go
v2/component/launcher_v2.go
v2/driver/driver.go
v2/metadata/client.go
v2/metadata/converter.go

chore(v2): parameter passing. Fixes #6151

---

manifests/kustomize/README.md
manifests/kustomize/env/platform-agnostic-emissary/kustomization.yaml
manifests/kustomize/env/platform-agnostic-emissary/workflow-controller-configmap-patch.yaml
manifests/kustomize/env/platform-agnostic-multi-user-emissary/kustomization.yaml
manifests/kustomize/env/platform-agnostic-multi-user-emissary/workflow-controller-configmap-patch.yaml
manifests/kustomize/hack/test.sh

Part of https://github.com/kubeflow/pipelines/issues/5718
**Checklist:**

feat(deployment): provide platform-agnostic-emissary and platform-agnostic-multi-user-emissary as options

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
manifests/gcp_marketplace/schema.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
manifests/gcp_marketplace/test/snapshots.sh
manifests/gcp_marketplace/test/values-emissary.yaml

Part of https://github.com/kubeflow/pipelines/issues/5718
**Checklist:**

feat(deployment): gcp marketplace - provide emissary as an option. Part of #5718

---

sdk/python/kfp/dsl/_component_bridge.py
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/experimental_v2_component.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/experimental_v2_component.py
sdk/python/kfp/v2/components/experimental/__init__.py
sdk/python/kfp/v2/components/experimental/base_component.py
sdk/python/kfp/v2/components/experimental/base_component_test.py
sdk/python/kfp/v2/components/experimental/component_spec.py
sdk/python/kfp/v2/components/experimental/component_spec_test.py
sdk/python/kfp/v2/components/experimental/pipeline_task.py
sdk/python/requirements.in
sdk/python/setup.py

Define the base classes needed for KFP DSL v2. 
**Checklist:**

feat(sdk.v2): Define BaseComponent, ComponentSpec, and PipelineTask.

---

components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/tfp_anomaly_detection.ipynb

- Add seed to demo for reproducibility.
**Checklist:**

chore(components/google-cloud): Add seed to tfp_anomaly_detection

---

v2/Makefile

test: fix make push-launcher

---

v2/README.md

docs: v2 compatible release instructions

---

api/v2alpha1/pipeline_spec.proto

feat(api): Add env variable in ContainerSpec

---

sdk/python/tests/compiler/compiler_tests.py
sdk/python/tests/compiler/testdata/uri_artifacts.yaml

test(sdk): restore a v2-compatible unit test

---

samples/test/two_step.py
samples/test/two_step_test.py
v2/Makefile
v2/cmd/driver/main.go
v2/cmd/launcher-v2/main.go
v2/compiler/dag.go
v2/component/launcher.go
v2/component/launcher_v2.go
v2/driver/driver.go
v2/metadata/client.go
v2/metadata/client_test.go
v2/objectstore/object_store.go

Fixes #6152 
One change to call out:
* I'm changing the pipeline root value we store on pipeline run context. In the previous PR, it was the original pipeline root, but in this PR, it's changed to pipelineRoot/pipelineName/runID, because pipelineName and runID are not so easily accessible in launcher. The simplest solution I thought of is setting pipeline root as the actual prefix we take for all tasks in the pipeline run.
**Checklist:**

chore(v2): artifact passing via local path

---

backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go

chore(swf): fix recurring run + v2 compatible

---

.cloudbuild.yaml
.release.cloudbuild.yaml
components/release-in-place.sh
components/release.sh

stop releasing gcp components for a transition to use google-cloud/
**Checklist:**

chore: stop releasing gcp components

---

components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job_sample.ipynb

Adding a sample notebook with additional documentation on API interface.

chore(components/google-cloud): Add sample for Vertex AI custom job

---

components/google-cloud/google_cloud_pipeline_components/remote/aiplatform/remote_runner.py

fix(components/google-cloud): Fix parameter for TabularCreateDatasetOp breaks if it contains "="

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/config-snapshot.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml

Changes:
* default pipeline root to gcs when configured
* update config snapshot for emissary executor
**Checklist:**

chore(deployment): gcp mkp - default pipeline root to gcs when configured

---

backend/src/apiserver/resource/resource_manager_test.go
samples/test/simple_pipeline_without_importer_test.py
sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/_component_bridge.py
sdk/python/tests/compiler/testdata/uri_artifacts.yaml

Fixes: https://github.com/kubeflow/pipelines/issues/6307
**Checklist:**

feat(backend/sdk): Rename `pipeline-output-directory` to `pipeline-root`. Fixes #6307

---

frontend/src/components/ArtifactPreview.test.tsx
frontend/src/components/ArtifactPreview.tsx
frontend/src/components/MinioArtifactPreview.tsx
frontend/src/components/tabs/InputOutputTab.test.tsx
frontend/src/lib/Apis.test.ts
frontend/src/lib/Apis.ts

chore(frontend): Use `gs://` instead of `gcs://` for artifact link text. Fix #6308

---

components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/preprocess/component.yaml
components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/validate/component.yaml

**Add vertex forecasting preprocessing and validation components:**
- Validation component: validate one or more BigQuery tables with essential requirements that make sure the data can create a forecasting model or can be use for predictions.
- Preprocessing component: perform join, union, and other transformations on user data to generate a single BigQuery output table that will be consumed by training or prediction.

feat(components/google-cloud): Add vertex forecasting preprocessing and validation components.

---

samples/core/XGBoost/xgboost_sample.py
sdk/python/kfp/compiler/compiler.py

fix(sdk): pipeline name is required in v2 compatible mode. Fixes #6197

---

sdk/python/kfp/v2/dsl/__init__.py

chore(sdk): Export all artifact types from io_types in `dsl` package.

---

frontend/src/components/viewers/HTMLViewer.tsx

fix(frontend): Maximize width of HTML visualization. Partial #6296

---

components/PyTorch/pytorch-kfp-components/templates/ax_complete_trials_component.yaml
components/PyTorch/pytorch-kfp-components/templates/ax_generate_trials_component.yaml

Adds sqlAlchemy pip package to ax generate and complete trials components.
**Checklist:**

chore(components/pytorch): Add sqlalchemy pacakge to ax

---

proxy/Dockerfile
test/api-integration-test/Dockerfile
test/initialization-test/Dockerfile
test/sample-test/Dockerfile
test/sample-test/hack/update_requirements.sh
test/sample-test/requirements.txt

Part of https://github.com/kubeflow/pipelines/issues/6311#issuecomment-899224137
**Checklist:**

test: fix apt update "changed its 'Suite' value from 'stable' to 'oldstable'"

---

components/PyTorch/pytorch-kfp-components/setup.py

This PR is to update the development status of `pytorch-kfp-components` pip package.
**Checklist:**

chore(components/pytorch): Pytorch kfp components setup

---

samples/core/output_a_directory/output_a_directory_test.py
samples/test/after_test.py
samples/test/config.yaml
samples/test/lightweight_python_functions_v2_pipeline.py
samples/test/lightweight_python_functions_v2_pipeline_test.py
samples/test/lightweight_python_functions_v2_with_outputs.py
samples/test/lightweight_python_functions_v2_with_outputs_test.py
samples/test/metrics_visualization_v2_test.py
samples/test/parameter_with_format_test.py
samples/test/placeholder_concat_test.py
samples/test/reused_component_test.py
samples/test/two_step_with_uri_placeholder_test.py
v2/component/launcher_v2.go
v2/driver/driver.go

Part of https://github.com/kubeflow/pipelines/issues/6150
Some samples are still failing, I'll fix them in separate PRs. They are currently commented as `TODO(v2):`
**Checklist:**

test(v2): add more samples. Part of #6150

---

sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml
sdk/python/kfp/components/_python_op.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_metrics_outputs.json

The base-image for Python-based components may not have pip pre-installed.

fix(sdk): Ensure pip exists for lightweight Python-based components.

---

components/gcp/bigquery/query/to_CSV/component.yaml
components/gcp/bigquery/query/to_table/component.yaml
components/gcp/dataflow/launch_flex_template/component.yaml
components/gcp/dataflow/launch_template/component.yaml
components/gcp/dataproc/create_cluster/component.yaml
components/gcp/dataproc/delete_cluster/component.yaml
components/gcp/dataproc/submit_hadoop_job/component.yaml
components/gcp/dataproc/submit_hive_job/component.yaml
components/gcp/dataproc/submit_pig_job/component.yaml
components/gcp/dataproc/submit_pyspark_job/component.yaml
components/gcp/dataproc/submit_spark_job/component.yaml
components/gcp/dataproc/submit_sparksql_job/component.yaml
components/gcp/ml_engine/batch_predict/component.yaml
components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_gcs/component.yaml
components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_table/component.yaml
components/google-cloud/google_cloud_pipeline_components/experimental/dataflow/launch_python/component.yaml

fix(components/gcp): add explicit command for gcp components. Fixes #6252

---

README.md

docs: Update README for emissary and KFP 1.7. Partial #6306

---

frontend/src/pages/GettingStarted.test.tsx
frontend/src/pages/GettingStarted.tsx
frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap

feat(frontend): Add KFPv2 and tutorial link in Get Started page. Partial #6306

---

samples/test/lightweight_python_functions_v2_pipeline_test.py
samples/test/lightweight_python_functions_v2_with_outputs_test.py
samples/test/metrics_visualization_v2_test.py
v2/Makefile
v2/component/launcher.go
v2/component/launcher_v2.go

chore(v2): support output metadata file

---

samples/test/metrics_visualization_v2.py
samples/test/metrics_visualization_v2_test.py

test: Update visualization v2 to output HTML and Markdown. Partial #3970

---

components/google-cloud/RELEASE.md
components/google-cloud/google_cloud_pipeline_components/version.py

chore(components/google-cloud): Update GCPC SDK version

---

sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py

test(sdk): ignore kfp version in unit tests

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/v2_compat.py

chore: Release KFP SDK and v2 launcher 1.7.1

---

frontend/src/components/viewers/MetricsVisualizations.tsx

feat(frontend): Support v2 HTML/Markdown visualization. Fix #3970

---

samples/test/lightweight_python_functions_v2_with_outputs_test.py
samples/test/two_step_with_uri_placeholder_test.py
samples/test/util.py
v2/cmd/compiler/main.go
v2/compiler/argo.go
v2/driver/driver.go

chore(v2): support changing pipeline root

---

test/sample-test/configs/parameterized_tfx_oss.config.yaml

test: configure tfx sample push_destination arg

---

components/google-cloud/README.md
components/google-cloud/setup.py

Updating the `README.md` for the project with link to release notes and pushing the detailed update to PyPI package as long description following [TFX projects setup](https://pypi.org/project/tfx/) see [tfx/setup.py](https://github.com/tensorflow/tfx/blob/c284799c90cd609ace6cd7b699dde2d896a1779e/setup.py#L188) for more details.

feat(components/google-cloud): Include release notes in pypi

---

samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb

Partial #6138
TFX 1.2.0 adds worker pod ID to the custom_properities of execution, it allows UI to find the corresponding execution using argo workflow.
cc @jiyongjung0
**Checklist:**

feat(sample): Use TFX 1.2.0 for Taxi tips prediction sample. Partial #6138

---

frontend/src/mlmd/MlmdUtils.test.ts
frontend/src/mlmd/MlmdUtils.ts

fix for comment https://github.com/kubeflow/pipelines/issues/6138#issuecomment-898190223
Part of #6138 
**Checklist:**

feat(frontend): integrate with TFX 1.2.0 metadata & visualization, no longer support previous versions. Part of #6138

---

components/google-cloud/google_cloud_pipeline_components/experimental/__init__.py

**Fix FileNotFoundError when loading component yaml from file.:**
Change load_component_from_file method to load_component_from_url.
Also a small update on the docstring.
@SinaChavoshi @IronPan

fix(components/google-cloud): Fix FileNotFoundError when loading component yaml from file.

---

sdk/python/kfp/v2/google/client/client.py

chore(sdk): clean up the unused arg in AIPlatformClient docstring.

---

frontend/src/lib/v2/StaticFlow.ts

Partial #6397
Reference: https://github.com/kubeflow/pipelines/issues/6374
**Checklist:**

chore(frontend): Change edge type from animated to arrowclosed. Partial #6397

---

sdk/RELEASE.md
sdk/python/kfp/_client.py

- Add description to upload_pipeline_version in kfp.Client. 
- Requires #6393 to be released in backend for this to be useful.
Part of #6256

feat(sdk): Add description to upload_pipeline_version in kfp. Part of #6256

---

frontend/mock-backend/fixed-data.ts
frontend/mock-backend/mock-api-middleware.ts
frontend/src/pages/PipelineVersionList.test.tsx
frontend/src/pages/PipelineVersionList.tsx
frontend/src/pages/__snapshots__/PipelineVersionList.test.tsx.snap

Add version description to Pipeline Version list.
had to update snapshot for test. Not sure if I did that correctly
Also added some mocked data to more easily check UI looked good.

feat(frontend): Add version description to pipelineVersionList. Part of #6256

---

manifests/gcp_marketplace/schema.yaml

chore: GCP mkp does not default to root when the field is empty

---

components/gcp/bigquery/README.md
components/gcp/dataflow/README.md
components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_CSV/README.md
components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_CSV/component.yaml
components/google-cloud/google_cloud_pipeline_components/experimental/dataflow/launch_flex_template/component.yaml
components/google-cloud/google_cloud_pipeline_components/experimental/dataflow/launch_template/component.yaml

This is the initial version to move dataflow/bq components to google-cloud. 
Moving the code doesn't include the component to next GCPC release. 
As a next step, we need to review these APIs and update if needed.
/assign @neuromage @SinaChavoshi @kramachandran  
**Checklist:**

feat(components): move dataflow/bq component to google-cloud

---

components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/__init__.py
components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/preprocess/component.yaml

The corresponding command line flag is already supported by the container.

feat(components/google-cloud): add preprocessing_bigquery_dataset to the inputs of preprocessing component

---

.cloudbuild.yaml
.release.cloudbuild.yaml
backend/metadata_writer/requirements.in
backend/metadata_writer/requirements.txt
backend/requirements.in
backend/requirements.txt
backend/src/apiserver/visualization/requirements.txt
frontend/scripts/replace_protos.js
frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_pb.d.ts
frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_pb.js
manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
test/sample-test/requirements.txt
test/tag_for_hosted.sh
third_party/ml-metadata/ml_metadata/proto/metadata_store.proto
v2/Makefile

feat: upgrade MLMD to 1.2.0. Fix #6436

---

sdk/python/kfp/_client.py

Reverts kubeflow/pipelines#6395
because of https://github.com/kubeflow/pipelines/issues/6256#issuecomment-908025917

revert: "feat(sdk): Add description to upload_pipeline_version in kfp. Part of #6256"

---

sdk/python/kfp/_local_client.py
sdk/python/kfp/_runners.py

* Also exposes `pipeline_root` from `run_pipeline_func_on_cluster`. Fixes: https://github.com/kubeflow/pipelines/issues/6435
**Checklist:**

chore(sdk): Add Alpha feature notice for local client

---

api/v2alpha1/pipeline_spec.proto
sdk/python/kfp/dsl/_component_bridge.py
sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.py
sdk/python/kfp/v2/components/importer_node.py
sdk/python/kfp/v2/components/importer_node_test.py

feat(sdk.v2): Support `set_display_name` in v2.

---

samples/test/cache_v2_test.py
samples/test/config.yaml
samples/test/two_step_test.py
samples/test/two_step_with_uri_placeholder_test.py
samples/v2/pipeline_with_importer.py
samples/v2/pipeline_with_importer_test.py
v2/Makefile
v2/cmd/launcher-v2/main.go
v2/compiler/argo.go
v2/compiler/argo_test.go
v2/compiler/container.go
v2/compiler/executor.go
v2/compiler/importer.go
v2/compiler/testdata/importer.json
v2/compiler/visitor.go
v2/component/importer_launcher.go
v2/component/launcher.go
v2/component/launcher_v2.go
v2/driver/driver.go
v2/metadata/client.go
v2/metadata/client_test.go
v2/metadata/converter.go
v2/objectstore/object_store.go

- added importer support in compiler
**Checklist:**

feat(v2): added importer support

---

components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/component.yaml

This YAML is currently not be used. maintain it just for sample purpose. 
**Checklist:**

chore(components/google-cloud): update custom job component yaml to match the latest code

---

components/google-cloud/tox.ini

Updating Nox test environment for GCPC to python 3.9

chore(components/google-cloud): Update tox test env to Python 3.9

---

frontend/src/components/graph/Constants.ts
frontend/src/components/graph/SubDagNode.tsx
frontend/src/pages/v2/StaticCanvas.tsx

Partial #6301
Removed the need to use double click.
**Checklist:**

feat(frontend): Create an Expand button to open SubDAG. Partial #6301

---

samples/v2/pipeline_with_importer.py

Otherwise, it will block sdk release PR presubmit.
**Checklist:**

fix(samples): Add `kfp_package_path` to importer sample test.

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/v2_compat.py

chore: Release KFP SDK and v2 launcher 1.8.0

---

sdk/python/kfp/_client.py

Allow configuration of pipeline and operation service accounts from the pipeline dsl.
Resolves #6424.
**Checklist:**

feat(sdk): Configure pipeline run service account. Fixes #6424

---

sdk/RELEASE.md
sdk/python/kfp/dsl/_component_bridge.py
sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler/compiler_test.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py
sdk/python/kfp/v2/google/client/client_test.py
sdk/python/kfp/v2/google/client/runtime_config_builder.py
sdk/python/kfp/v2/google/client/runtime_config_builder_test.py
sdk/python/kfp/v2/google/client/testdata/pipeline_job.json

fix(sdk.v2): Support dict, list, bool typed input parameters from constant values and pipeline inputs.

---

frontend/src/Css.tsx
frontend/src/lib/Utils.tsx
frontend/src/pages/PipelineDetails.tsx
frontend/src/pages/PipelineDetailsV1.tsx
frontend/src/pages/PipelineDetailsV2.tsx

feat(frontend): Show Pipeline Spec in Pipeline Detail page. Fix #6279

---

samples/contrib/pytorch-samples/cifar10/cifar10_datamodule.py

`WebDataset.Dataset` has been deprecated in the new release - https://pypi.org/project/webdataset/0.1.74/ . Updating `Webdataset.Dataset` with `Webdataset.Webdataset` in dataloading.
```
File "cifar10/cifar10_pytorch.py", line 166, in <module>
trainer = Trainer(
File "/opt/conda/lib/python3.8/site-packages/pytorch_kfp_components/components/trainer/component.py", line 72, in __init__
Executor().Do(
File "/opt/conda/lib/python3.8/site-packages/pytorch_kfp_components/components/trainer/executor.py", line 88, in Do
data_module.setup(stage="fit")
File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
fn(*args, **kwargs)
File "/workspace/cifar10/cifar10_datamodule.py", line 93, in setup
wds.Dataset(
File …
```

chore(components/pytorch): Samples - Cifar10 webdataset fix

---

components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
components/google-cloud/google_cloud_pipeline_components/experimental/proto/gcp_resources.proto
components/google-cloud/tests/experimental/custom_job/test_custom_job.py

There are cases the upper cases and lower cases are not interchangable in SDK, and only lower case is supported. Use lower case to be consistent everywhere and avoid confusion
**Checklist:**

chore(components): update GCP_RESOURCES to lower case

---

components/kubeflow/kfserving/src/kfservingdeployer.py

Some data from model_status on kfservingdeployer component were removed because KFP is failing.
**Checklist:**

fix:  Remove some data from model_status when the size exceeds 3000

---

components/google-cloud/OWNERS

chore(components/GCP): update owners

---

sdk/python/tests/run_tests.sh

Not all tests are being run by the `run_tests.sh` script
**Checklist:**

chore(sdk): fix sdk/python/tests/run_tests.sh to run all the tests in the folder.

---

api/v2alpha1/pipeline_spec.proto

Add pipeline job id to the task final status proto.
**Checklist:**

feat(api): Update pipeline_spec.proto to add `pipeline_job_uuid` and `pipeline_job_name` in `PipelineTaskFinalStatus`

---

frontend/src/mlmd/MlmdUtils.test.ts
frontend/src/mlmd/MlmdUtils.ts
frontend/src/pages/ExecutionDetails.tsx

Fix #5977
- Show a link to pipeline run, and it will open the node that has corresponded Execution.
- Show a link to Original Execution, if this node has custom property (cached_execution_id).
https://user-images.githubusercontent.com/37026441/133162451-f3ed5cb8-d56c-4689-8b92-dfb474c32c9f.mov
**Checklist:**

feat(frontend): Show hyperlink from Execution to Pipeline Run detail page and Original Execution cache. Fix #5977

---

components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/custom_job_remote_runner.py
components/google-cloud/tests/experimental/remote/gcp_launcher/test_custom_job_remote_runner.py

Using the new GCP_RESOURCE proto for output of custom_job.

feat(components/google-cloud): Write proper GCP_RESOURCE parameter to the custom_job output

---

manifests/kustomize/OWNERS

chore: Update kustomize/manifests OWNERS

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/v2_compat.py

chore: Release KFP SDK and v2 launcher 1.8.2

---

backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/third_party_licenses/apiserver.csv
go.sum

Fixes https://github.com/kubeflow/pipelines/issues/6547
- Decompress workflow node statuses if compressed.
- Error on offloaded node statuses. If we want to support this case, I think we'd need to either connect the kfp server to the argo database or fetch the statuses using the argo server. 
**Checklist:**

fix(backend): Decompress workflow node statuses if necessary. Fixes #6547

---

components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
components/google-cloud/tests/experimental/custom_job/test_custom_job.py

Adding support for labels in custom job.

feat(components/google-cloud): Add support for labels in custom_job wrapper

---

manifests/kustomize/base/pipeline/ml-pipeline-apiserver-service.yaml

Adding "prometheus" annotation to ml-pipeline service.
it is a fix for: https://github.com/kubeflow/manifests/issues/2011
**Checklist:**

feat(backend): Adding prometheus annotations for ml-pipeline service

---

components/google-cloud/RELEASE.md
components/google-cloud/google_cloud_pipeline_components/version.py
components/google-cloud/tests/presubmit.sh

Includes:
- Update release notes
- Update version

chore(components/google-cloud): Post release v0.1.7 clean up

---

components/google-cloud/dependencies.py
components/google-cloud/google_cloud_pipeline_components/experimental/Optimizer/Suggest_trials/component.py
components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/__init__.py
components/google-cloud/tests/experimental/forecasting/test_forecasting_components_compile.py

feat(components/google-cloud): Add a new forecasting training component that uses the experimental flags

---

sdk/python/setup.py

FIxes: https://github.com/kubeflow/pipelines/issues/6511
**Checklist:**

chore(sdk): Add "Source" and "Changelog" links to kfp PyPi page

---

components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/custom_job_remote_runner.py
components/google-cloud/tests/experimental/custom_job/test_custom_job.py
components/google-cloud/tests/experimental/remote/gcp_launcher/test_custom_job_remote_runner.py

This is the fix how gcp_resouce proto is written to output .

fix(components/google-cloud):   Custom Job resource proto output is incorrect

---

components/google-cloud/examples/README.md

/assign @SinaChavoshi 
**Checklist:**

chore(components): update sample readme

---

components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/CustomTrainingJobOp_sample.ipynb
components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/__init__.py
components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/component.yaml
components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
components/google-cloud/tests/experimental/custom_job/test_custom_job.py

Changing the name for custom job wrapper to custom_training_job_op.

fix(components/google-cloud): Change run_as_vertex_ai_custom_job to custom_training_job_op

---

components/google-cloud/google_cloud_pipeline_components/aiplatform/model/upload_model/component.yaml
components/google-cloud/tests/aiplatform/integration/test_components_compile.py
components/google-cloud/tests/aiplatform/testdata/model_upload_pipeline.json

/assign @SinaChavoshi 
**Checklist:**

feat(components): add label field for model upload

---

backend/test/integration/pipeline_api_test.go

chore: add missing assert and remove duplicate package import in pipeline_api_test

---

backend/test/integration/pipeline_version_api_test.go
backend/test/integration/run_api_test.go
backend/test/integration/upgrade_test.go

Combine this to one PR since it was very few changes per file in this case. 
**Checklist:**

chore: add missing assert in pipeline_version_api_test.go, run_api_test.go and upgrade_test.go

---

backend/test/integration/job_api_test.go

chore: add condition check and missing error asserts in run_api_test.go

---

samples/test/util.py

Fixed #6640 
disable cache for v1 mode in sample test
**Checklist:**

fix: disable cache for v1 mode in sample test

---

api/v2alpha1/pipeline_spec.proto

Add PipelineTaskFinalStatus.pipeline_job_resource_name field.
**Checklist:**

chore(api): Add pipeline_job_resource_name

---

components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/CustomTrainingJobOp_sample.ipynb

chore(components): update custom job op doc

---

sdk/RELEASE.md
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
sdk/python/kfp/v2/components/types/type_utils.py
sdk/python/kfp/v2/components/types/type_utils_test.py

Preserve type names in `schemaTitle` for types under `google` namespace.
**Checklist:**

chore(sdk): Support artifact types under google namespace

---

components/google-cloud/google_cloud_pipeline_components/aiplatform/__init__.py

Remove this component since it's never been used.
The new [custom job](https://github.com/kubeflow/pipelines/blob/master/components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py) component is intend to replace this component
**Checklist:**

chore(components/google-cloud): remove custom python package training op

---

api/v2alpha1/pipeline_spec.proto

chore(api): Add default_value in ComponentInputsSpec.ParameterSpec and default_pipeline_root in PipelineSpec.

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/v2_compat.py

chore: Release KFP SDK and v2 launcher 1.8.4

---

components/google-cloud/dependencies.py

/assign @SinaChavoshi 
**Checklist:**

feat(components): bump kfp version

---

components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py

chore(components): Import module instead of functions; remove unneeded dependencies

---

components/google-cloud/google_cloud_pipeline_components/aiplatform/__init__.py

Reverts kubeflow/pipelines#6474

fix(components/google-cloud): REVERT - remove custom python package training op

---

sdk/RELEASE.md
sdk/python/kfp/v2/components/executor.py
sdk/python/kfp/v2/components/executor_test.py

fix(sdk.v2): Fix executor getting None as value when float 0 is passed in. Fixes #6636

---

test/kfp-functional-test/run_kfp_functional_test.py

Mitigates https://github.com/kubeflow/pipelines/issues/6815#issuecomment-955938098
**Checklist:**

test: skip archiving experiments because of perf problem

---

RELEASE.md

docs: Backend release doc update

---

RELEASE.md

We should update test-infra manifests after release.
**Checklist:**

docs: Add instruction to update kfp test-infra

---

components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests

- Kubernetes version 1.17 will be deprecated by EKS, bumping up verison to v1.18
**Checklist:**

chore: update eks version to 1.18 for aws sagemaker integration tests

---

sdk/python/kfp/dsl/_component.py

Fix invalid doc example of python_component function
**Checklist:**

fix(sdk): Fix invalid doc example of python_component

---

sdk/RELEASE.md
sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/google/client/client.py
sdk/python/kfp/v2/google/client/schedule.py
sdk/python/kfp/v2/google/experimental/custom_job.py

chore(sdk): Cherry pick #6844 and #6851 to sdk/release-1.8 branch

---

test/presubmit-tests-tfx.sh

Fixes: https://github.com/kubeflow/pipelines/issues/6860
**Checklist:**

test: fix kubeflow-pipelines-tfx-python37 test

---

sdk/python/kfp/dsl/types.py
sdk/python/kfp/v2/compiler/compiler_test.py

fix(sdk): Make `Artifact` type be compatible with any sub-artifact types bidirectionally

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py
sdk/python/kfp/dsl/types.py
sdk/python/kfp/v2/compiler/compiler_test.py

chore: Cherry pick #6859 and #6864 to sdk/release-1.8 branch

---

sdk/RELEASE.md
sdk/python/kfp/dsl/_container_op.py

chore(sdk): Remove redundant check in set_gpu_limit

---

test/presubmit-tests-tfx.sh

Fixes: https://github.com/kubeflow/pipelines/issues/6906
**Checklist:**

test: temporarily test tfx against a release branch

---

test/manifests/dev/kustomization.yaml
test/manifests/dev/workflow-controller-configmap-patch.yaml

We want to primarily test emissary executor
**Checklist:**

test: default to emissary executor

---

components/gcp/container/build_image.sh
components/kubeflow/dnntrainer/build_image.sh
components/kubeflow/launcher/build_image.sh
components/kubeflow/pytorch-launcher/build_image.sh
components/local/base/build_image.sh

Fix presubmit and postsubmit tests because cloud builder docker image has upgraded from ubuntu16 to 20
**Checklist:**

test: Use cp when rsync is unnecessary. Install rsync otherwise.

---

frontend/mock-backend/data/v2/pipeline/mock_lightweight_python_functions_v2_pipeline.json
frontend/mock-backend/data/v2/pipeline/mock_lightweight_python_functions_v2_pipeline_rev.json
frontend/mock-backend/data/v2/pipeline/pipeline_with_loops_and_conditions.json
frontend/mock-backend/data/v2/pipeline/xgboost_sample_pipeline.json
frontend/src/components/tabs/StaticNodeDetailsV2.tsx
frontend/src/data/test/mock_lightweight_python_functions_v2_pipeline.json
frontend/src/data/test/pipeline_with_loops_and_conditions.json
frontend/src/lib/v2/DynamicFlow.test.ts
frontend/src/lib/v2/StaticFlow.test.ts
frontend/src/lib/v2/WorkflowUtils.test.ts
frontend/src/lib/v2/WorkflowUtils.ts
frontend/src/pages/PipelineDetailsV2.tsx

Fix  #6778, #6672
Uses of new upload Pipeline API to submit PipelineSpec in json format. https://github.com/kubeflow/pipelines/pull/6513
https://user-images.githubusercontent.com/37026441/141829005-f83b59fb-d04b-4e62-a1fe-4407639d20b6.mov
This JSON format requires the proto of `PipelineSpec`, if this is not in correct form, error looks like below:
With the change, I switched proto entry from PipelineJob to PipelineSpec as well.
Minor: Fixed the PipelineSpec editor view formatting on the PipelineDetails page too.
**Checklist:**

feat(frontend): Upload V2 Pipelines. Fix PipelineSpec editor prettified view.

---

samples/OWNERS

chore: Update samples/OWNERS

---

backend/src/crd/controller/scheduledworkflow/controller.go
backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go

chore: break out submitNextWorkflowIfNeeded clean up from #4752

---

samples/core/output_a_directory/output_a_directory_test.py
samples/test/after.py
samples/test/lightweight_python_functions_v2_pipeline_test.py
samples/test/lightweight_python_functions_v2_with_outputs.py
samples/test/lightweight_python_functions_v2_with_outputs_test.py
samples/test/parameter_with_format_test.py
samples/test/placeholder_concat.py
samples/test/reused_component_test.py
samples/test/two_step_test.py
samples/test/two_step_with_uri_placeholder.py
samples/test/util.py
samples/v2/hello_world.py
samples/v2/lightweight_python_functions_v2_pipeline/lightweight_python_functions_v2_pipeline.py
samples/v2/pipeline_with_importer.py
samples/v2/producer_consumer_param.py

Fixes https://github.com/kubeflow/pipelines/issues/6928
**Checklist:**

test(sample): reenable samples tests run with V2_ENGINE mode

---

samples/test/lightweight_python_functions_v2_pipeline_test.py
sdk/RELEASE.md
sdk/python/kfp/v2/components/executor.py
sdk/python/kfp/v2/components/executor_test.py

fix(sdk.v2): Fix bug on executor input with default value.

---

sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_placeholders.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_placeholders.py

chore(sdk.v2): Add test sample for runtime placeholders

---

sdk/python/kfp/_client.py

This PR aims to fix the issue described in #6883. 
**Checklist:**

fix(sdk): refresh access token only when it expires. Fixes #6883

---

sdk/python/kfp/components/_python_op.py

See https://github.com/kubeflow/pipelines/pull/6911 and https://github.com/kubeflow/pipelines/pull/6911#issuecomment-973394950.
**Checklist:**

chore(sdk): Fix the warning message

---

sdk/python/kfp/_client.py

Cherry pick #6941 to sdk/release-1.8 branch
**Checklist:**

chore: Cherry pick #6941 to sdk/release-1.8 branch

---

samples/core/XGBoost/xgboost_sample.py

example failure: https://4e18c21c9d33d20f-dot-datalab-vm-staging.googleusercontent.com/#/runs/details/3b52ad66-b68b-4f7a-9500-abbe68ac8821
**Checklist:**

test(samples): fix xgboost sample OOM flakiness

---

go-licenses.yaml

Fixes post submit failure when building images
**Checklist:**

chore: update licenses

---

backend/src/apiserver/resource/client_manager_fake.go
backend/src/apiserver/server/experiment_server_test.go
backend/src/apiserver/server/list_request_util.go
backend/src/apiserver/server/pipeline_server_test.go
backend/src/apiserver/server/pipeline_upload_server_test.go
backend/src/apiserver/server/report_server_test.go
backend/src/apiserver/server/run_server_test.go
backend/src/apiserver/server/test_util.go
backend/src/apiserver/server/util.go
backend/src/apiserver/server/util_test.go
backend/src/apiserver/storage/default_experiment_store.go

test: clean up of api server tests

---

third_party/ml-metadata/update_version.sh
v2/Makefile
v2/test/requirements.txt

chore(mlmd): fix MLMD update scripts

---

OWNERS

chore: Update root OWNERS

---

sdk/RELEASE.md
sdk/python/kfp/_client.py
sdk/python/kfp/cli/cli.py
sdk/python/kfp/cli/diagnose_me_cli.py
sdk/python/kfp/cli/experiment.py
sdk/python/kfp/cli/pipeline.py
sdk/python/kfp/cli/recurring_run.py
sdk/python/kfp/cli/run.py

Cherry-picking #6934 to `sdk/release-1.8` as discussed [here](https://github.com/kubeflow/pipelines/pull/6934#pullrequestreview-819526308)

feat(sdk): Improve CLI experience for archiving experiments, managing recurring runs and listing resources (#6934)

---

sdk/RELEASE.md
sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_loops.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_loops.py
sdk/python/kfp/v2/components/for_loop.py

Verified that the compiled samples run correctly on Vertex Pipelines
**Checklist:**

fix(sdk.v2): fix regression on nested loops

---

sdk/python/kfp/cli/pipeline.py
sdk/python/kfp/cli/run.py

Fixes the bug in https://github.com/kubeflow/pipelines/pull/6934#issuecomment-984412593.
PR title is chore instead of "fix", because the bug is fixed before a release.
I verified these fixes locally, they resolve the error message.
**Checklist:**

chore(sdk): fix error 'ApiResourceReference' object has no attribute 'id'

---

frontend/mock-backend/fixed-data.ts
frontend/src/pages/RunDetailsRouter.tsx

Partial #6400, #6779
After https://github.com/kubeflow/pipelines/pull/7000 is merged, the frontend change is minimal for creating run and viewing run details based on Pipeline.
Note that for pipeline run to be successful, there are still some works:
**Checklist:**

feat(frontend): V2 create run from UI

---

sdk/python/kfp/_local_client.py

fix(sdk): cherry pick #6965 into sdk/release-1.8 branch

---

backend/src/apiserver/client/swf.go

chore: add missing error check in newOutOfClusterSwfClient

---

sdk/python/kfp/compiler/_data_passing_using_volume.py
sdk/python/tests/compiler/testdata/artifact_passing_using_volume.py
sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml

…thods (#6882)
* Update _data_passing_using_volume.py
* Update _data_passing_using_volume.py
* Update _data_passing_using_volume.py
* Update _data_passing_using_volume.py
* Update _data_passing_using_volume.py
* Update artifact_passing_using_volume.yaml
* Update artifact_passing_using_volume.py
* Update _data_passing_using_volume.py
**Checklist:**

chore: cherry pick #6882 into sdk/release-1.8 branch

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

Pending actual release from `sdk/release-1.8` branch.
**Checklist:**

chore: SDK release note for 1.8.10

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

chore: release SDK 1.8.10 from `sdk/release-1.8` branch

---

test/sample_test.yaml

AI Platform pipeline sample logic will be out-of-date because of the component support in KFPv2: https://github.com/kubeflow/pipelines/blob/master/samples/core/ai_platform/ai_platform.ipynb
Container build sample will be out-of-date because it will be replaced by containerOp: https://github.com/kubeflow/pipelines/blob/master/samples/core/container_build/container_build.ipynb
**Checklist:**

test: Disable ai_platform and container_build during post-submit test

---

sdk/python/kfp/v2/compiler/compiler_test.py
sdk/python/kfp/v2/components/pipeline_task.py

fix(sdk.v2): fix boolean error for inputs

---

manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml

Associated PR: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1364
Run `./presubmit.sh` or `OS=darwin-amd64  ./presubmit.sh` to validate snapshot difference.
**Checklist:**

test: Enable snapshot presubmit for gcp_marketplace

---

sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler/compiler_test.py

fix(sdk.v2)!: Block task dependency referencing tasks inside a sibling condition or loop group.

---

samples/core/resource_spec/resource_spec_test.py
samples/core/resource_spec/resource_spec_v2.py
v2/Makefile
v2/compiler/argo.go
v2/compiler/container.go
v2/compiler/dag.go
v2/compiler/testdata/hello_world.yaml
v2/compiler/testdata/importer.yaml

chore(v2): static memory & cpu resource limits

---

samples/core/condition/condition_v2.py
v2/Makefile
v2/cmd/driver/main.go
v2/driver/driver.go
v2/expression/expression.go
v2/expression/expression_test.go
v2/metadata/client.go

Part of #6159 
Note, this PR is only the first step, it implements driver features to support condition,
but it is still lacking necessary changes in compiler.
**Checklist:**

chore(v2): v2 condition sample and expression

---

manifests/gcp_marketplace/test/presubmit.sh

Default presubmit test to use alpine. We need to install necessary tools.
**Checklist:**

test: Update presubmit for GCP marketplace test

---

samples/README.md

Fix typo qualty -> quality
**Checklist:**

docs: Fix typo in sample README

---

frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.d.ts
frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.js

feat(frontend): Upgrade MLMD client to 1.5.0. Partial #7029

---

manifests/kustomize/base/installs/multi-user/api-service/cluster-role-binding.yaml
manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml

Partial #6014
Prepare for K8s 1.22 which deprecates v1beta1 API.
**Checklist:**

fix(manifests): Upgrade rbac to v1 for multi-user mode. Partial #6014

---

backend/requirements.txt
backend/src/apiserver/visualization/requirements.in
backend/src/apiserver/visualization/requirements.txt
test/sample-test/Dockerfile
test/sample-test/requirements.txt

test: fix test failing to find kfp

---

OWNERS
backend/OWNERS
backend/api/Makefile
test/api-integration-test/OWNERS
test/release/Makefile
v2/OWNERS

chore: change owner

---

samples/core/dataflow/dataflow.ipynb
samples/core/dataflow/dataflow_test.py
samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
samples/core/parameterized_tfx_oss/parameterized_tfx_oss_test.py
samples/test/config-integration.yaml
samples/test/utils/kfp/samples/test/utils.py
sdk/python/kfp/compiler/compiler.py
test/presubmit-tests-with-pipeline-deployment.sh
v2/test/Dockerfile
v2/test/Makefile
v2/test/integration-test.sh
v2/test/requirements-runner.txt
v2/test/sample-test.sh
v2/test/sample_test.py
v2/test/scripts/ci-env.sh
v2/test/scripts/upload_gcs_blob.py

Part of https://github.com/kubeflow/pipelines/issues/6377
Migrates the two sample integration tests to v2 sample test infra: https://github.com/kubeflow/pipelines/blob/ac14a3b610988d3234660bbcba0c41290417a718/test/sample_test.yaml#L54-L81.
Usage: `./v2/test/integration-test.sh`.
**Checklist:**

test: migrate sample integration test to v2 sample test infra

---

samples/test/README.md
samples/test/utils/kfp/samples/test/utils.py
sdk/python/kfp/_client.py
v2/test/Makefile
v2/test/README.md
v2/test/components/run_sample.yaml
v2/test/sample_test.py

Fixes #6377 
Change: this also removes custom env vars for configuring KFP endpoint and UI endpoint, because KF_PIPELINES_ENDPOINT and KF_PIPELINES_UI_ENDPOINT are existing features people can use to configure them.
**Checklist:**

test: update README of v2 sample test

---

test/presubmit-tests-tfx.sh

Fixes https://github.com/kubeflow/pipelines/issues/7142
**Checklist:**

test: fix tfx presubmit test. 

---

v2/README.md

chore: Update README for v2 dev guide

---

manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml

Fix typo in https://github.com/kubeflow/pipelines/pull/7137/files
**Checklist:**

fix(manifests): Fix typo in default executor name

---

components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/trainer/executor.py
components/PyTorch/pytorch-kfp-components/tests/iris/iris_classification.py
samples/contrib/pytorch-samples/bert/bert_train.py
samples/contrib/pytorch-samples/cifar10/cifar10_train.py
samples/contrib/pytorch-samples/requirements.txt

Upgrade Pytorch Lightning to 1.5.0
**Checklist:**

chore(components/pytorch): Upgrade PTL

---

manifests/gcp_marketplace/test/presubmit.sh

I am also using this PR to validate the oss-test-infra change https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1399
**Checklist:**

test: Check helm client version only for mktplace presubmit test

---

sdk/RELEASE.md
sdk/python/kfp/v2/components/types/artifact_types.py
sdk/python/kfp/v2/components/types/artifact_types_test.py

Customer reported a bug that `SlicedClassificationMetrics` artifact was not received correctly at runtime.
**Checklist:**

fix(sdk): Fix create_runtime_artifact not covering all types.

---

.cloudbuild.yaml

Partial #6184
Note: I built `ko` image and push to the container registry of same GCP project, which allows the new steps to be runnable.
New steps build KFPv2 images: launcher-v2, driver, compiler.
**Checklist:**

chore(v2): Build KFPv2 related images in .cloudbuild.yaml. Partial #6184

---

components/build_image.sh
components/test_load_all_components.sh

As it's still needed for gcp/local/kubeflow components.
**Checklist:**

chore(component): revert the build_image.sh file 

---

sdk/RELEASE.md
sdk/python/kfp/_client.py
sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/dsl/_container_op.py
sdk/python/kfp/v2/components/types/artifact_types.py
sdk/python/kfp/v2/components/types/artifact_types_test.py
sdk/python/setup.py
sdk/python/tests/compiler/compiler_tests.py
test/presubmit-tests-tfx.sh

chore(sdk1.8): cherry pick #6866, #7056, #7141, #7143, #7168, #7172, #7182 into sdk/release-1.8 branch.

---

sdk/python/kfp/__init__.py

Will cherry pick the change into `sdk/release-1.8` branch and release from the branch.
**Checklist:**

chore(sdk): Bump SDK version to 1.8.11

---

sdk/python/kfp/__init__.py

chore(sdk1.8): cherry pick #7202

---

OWNERS
backend/OWNERS
frontend/OWNERS
manifests/gcp_marketplace/OWNERS
manifests/kustomize/OWNERS
proxy/OWNERS
test/OWNERS
test/api-integration-test/OWNERS
third_party/OWNERS
v2/OWNERS
v2/test/OWNERS

chore: remove Bobgy from OWNERS

---

RELEASE.md

For frequently used environment variables during the release process, explicitly define the command for assigning those values.
**Checklist:**

fix(docs): Update release doc with env var assignment.

---

backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml

Attempt to fix executors randomly get OOMKilled
**Checklist:**

chore(backend): Increase launcher memory limit and request from 64Mi to 128Mi

---

samples/core/visualization/tensorboard_minio.py

The references local file was deleted by https://github.com/kubeflow/pipelines/pull/7183
We should have used a permanent link anyway.
**Checklist:**

fix(samples): Update tensorboard_minio.py to load component from a permanent link

---

backend/Dockerfile
backend/Dockerfile.cacheserver
backend/Dockerfile.persistenceagent
backend/Dockerfile.scheduledworkflow
backend/Dockerfile.viewercontroller
test/presubmit-backend-test.sh

chore(backend): Check for forbidden license during image build and in presubmit

---

.cloudbuild.yaml

test(postsubmit): fix v2 code path in could build

---

sdk/RELEASE.md
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
sdk/python/kfp/v2/components/importer_node.py

fix(sdk.v2): Fix importer not using correct output artifact type

---

backend/OWNERS

chore: update backend/OWNERS

---

backend/metadata_writer/src/metadata_writer.py
backend/src/cache/server/mutation.go
backend/src/cache/server/mutation_test.go
backend/src/cache/server/watcher.go

Fixes #7266
Manually tested the change fixes v1 caching on top of `1.8.0-rc.1`.
**Checklist:**

fix(backend): Fix v1 caching to read Argo template from container env. Fixes #7266

---

test/release/bump-version-in-place.sh

`components/release-in-place.sh` no longer exists.
**Checklist:**

chore: Update bump-version-in-place.sh

---

sdk/OWNERS

chore: Update sdk/OWNERS

---

manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/composite-controller.yaml

Remove the labelselector as discussed in https://github.com/kubeflow/manifests/issues/2133#issuecomment-1040084080
**Checklist:**

fix(backend): Update composite-controller.yaml to fix https://github.com/kubeflow/manifests/issues/2133

---

manifests/gcp_marketplace/test/presubmit.sh
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
manifests/gcp_marketplace/test/snapshots.sh

Helm2 has reached its EOL in 2020: https://helm.sh/blog/helm-v2-deprecation-timeline/
**Checklist:**

chore: upgrade to helm 3

---

sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_task_final_status.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_task_final_status.py

chore(sdk): Fix a minor bug in task final status test sample

---

sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_env.py
sdk/python/kfp/components/base_component_test.py
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/pipeline_task_test.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py
sdk/python/kfp/components/test_data/simple_yaml.yaml
sdk/python/kfp/components/yaml_component_test.py

Renames `ContainerSpec` and `PipelineTask` parameter names to be consistent with Kubernetes API.
**Checklist:**

feat(sdk)!: rename commands, arguments parameters to command, args

---

sdk/python/kfp/components/executor_test.py

This PR fixes a test that left a gs:// directory in the file system after running. Now the tests clean this up.
**Checklist:**

chore(sdk): fix test missing tempdir cleanup

---

backend/README.md
backend/third_party_licenses/apiserver.csv
backend/third_party_licenses/cache_server.csv
backend/third_party_licenses/persistence_agent.csv
backend/third_party_licenses/swf.csv
backend/third_party_licenses/viewer.csv
hack/install-go-licenses.sh
test/presubmit-backend-test.sh

The forked features have been merged back to the upstream go-licenses repo: [PRs](https://github.com/google/go-licenses/pulls?q=is%3Apr+author%3ABobgy+is%3Amerged+)! Yeah!
**Checklist:**

chore: use the upstream go-licenses tool

---

components/gcp/container/component_sdk/python/kfp_component/google/dataproc/_client.py

Applying the fix discovered by @greggdonovan from https://github.com/kubeflow/pipelines/issues/7363#issuecomment-1057465491
**Checklist:**

fix(components): fix legacy gcp dataproc component

---

components/gcp/container/Dockerfile
components/gcp/container/build_image.sh

Follow up fix for: https://github.com/kubeflow/pipelines/pull/7422
**Checklist:**

fix(components): fix gcp component build script

---

RELEASE.md

chore: Update RELEASE.md

---

sdk/python/kfp/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py
sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_resource_spec.py
sdk/python/kfp/components/component_decorator.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/types/type_annotations_test.py
sdk/python/kfp/deprecated/_local_client.py
sdk/python/kfp/deprecated/cli/experiment.py
sdk/python/kfp/deprecated/cli/recurring_run.py
sdk/python/kfp/deprecated/compiler/_data_passing_using_volume.py
sdk/python/kfp/deprecated/compiler/_op_to_template.py
sdk/python/kfp/deprecated/compiler/compiler.py
sdk/python/kfp/deprecated/compiler/main.py
sdk/python/kfp/deprecated/components/_components.py
sdk/python/kfp/deprecated/components_tests/test_python_op.py
sdk/python/kfp/deprecated/dsl/_component.py
sdk/python/kfp/deprecated/dsl/_component_bridge.py
sdk/python/kfp/deprecated/dsl/_container_op.py
sdk/python/kfp/deprecated/dsl/_volume_op.py
sdk/python/tests/compiler/testdata/artifact_passing_using_volume.py
sdk/python/tests/dsl/component_tests.py
sdk/python/tests/local_runner_test.py

Applies yapf formatting. I'm opting to do this before attempting to enforce pylint.
**Checklist:**

chore(sdk): apply yapf formatting

---

test/presubmit-formatting-sdk.sh

This is a pre-requisite for creating a CI/CD job that verifies yapf formatting, since the job will run this script.
My preference is to add CI/CD workflows incrementally as our codebase is ready for it (e.g., when tests start to pass). Yapf is an easy one to add first, since yapf will pass after #7414 is merged.
**Checklist:**

chore: create presubmit-formatting-sdk.sh script

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/deprecated/_client.py
sdk/python/kfp/deprecated/cli/experiment.py
sdk/python/kfp/deprecated/cli/pipeline.py
sdk/python/kfp/deprecated/cli/recurring_run.py
sdk/python/kfp/deprecated/components/_component_store.py
sdk/python/kfp/deprecated/components/_components.py

In #7436, we add contributing guidelines that encourage users to use docformatter.
This PR applies docformatter to our existing codebase so that users do not get docformatter errors unrelated to their changes when following our instructions.
**Checklist:**

chore(sdk): apply docformatter

---

CONTRIBUTING.md
sdk/README.md
sdk/python/requirements-dev.txt

- Updates and deduplicates README information to help contributors.
- Adds dockerized code formatting/checking scripts to kfp README.
**Checklist:**

docs(sdk): update contributing guidelines

---

api/v2alpha1/pipeline_spec.proto

Updates the `PipelineTaskFinalStatus` message to add the `pipeline_task_name` field.
**Checklist:**

feat(api): adds task name to PipelineTaskFinalStatus message

---

api/v2alpha1/python/setup.py

Also update Python requirements to drop Python 3.5 and 3.6 support since all downstream dependencies (KFP SDK and TFX) have dropped support for these versions.
**Checklist:**

chore: bump kfp-pipeline-spec version to 0.1.14

---

sdk/RELEASE.md
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/v2_component_with_pip_index_urls.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/v2_component_with_pip_index_urls.py
sdk/python/kfp/v2/components/component_decorator.py
sdk/python/kfp/v2/components/component_decorator_test.py
sdk/python/kfp/v2/components/component_factory.py
sdk/python/kfp/v2/components/component_factory_test.py

Cherry picks #7453
**Checklist:**

chore(sdk1.8): cherry pick (#7453)

---

sdk/RELEASE.md

Updates release notes.
**Checklist:**

chore(sdk): update 1.8.12 release notes

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

Update release notes.
**Checklist:**

chore(sdk): update release notes for 1.8.12 release

---

samples/core/volume_ops/volume_ops.py

Fix small typo in path in VolumeOp example.
**Checklist:**

fix:  typo in VolumeOps example

---

backend/src/apiserver/server/util.go
backend/src/apiserver/template/template.go
backend/src/apiserver/template/template_test.go
backend/src/apiserver/template/v2_template.go

Fixes issue #7455:
Support IR YAML format. 
**Checklist:**

feat(backend): support IR YAML format in API

---

sdk/RELEASE.md
sdk/python/requirements.in
sdk/python/requirements.txt

Part of https://github.com/kubeflow/pipelines/pull/7493

chore(deps): Upgrade google-cloud-storage to v2

---

sdk/python/requirements-dev.txt

**Description of your changes:** 
Adds three typestub libraries to requirements-dev.txt.
**Checklist:**

chore(sdk): include typestub libraries in requirements-dev.txt

---

sdk/python/kfp/compiler_cli_tests/compiler_cli_tests.py
sdk/python/setup.py

Renames `dsl-compile-v2` to `dsl-compile`.
Renames `dsl-compile` to `dsl-compile-deprecated`.
**Checklist:**
more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

feat(sdk)!: promote v2 compiler command and deprecate v1 command

---

sdk/python/setup.py

Enables programmatic discovery of packages. This PR does not have any change to package list except for including `kfp.v2`, which should have already been included.
This will help us avoid missing packages in the future.
**Checklist:**

chore(sdk): use setuptools.find_packages

---

frontend/src/features.ts

Originally: 
Feature flags map is using the existing key feature from localStorage.
After the change:
New default features flags will be added into the localStorage and the users' setup will be preserved.
**Checklist:**

feat(frontend): Support default feature flags update in localStorage. Fix #7379 

---

frontend/OWNERS

Welcome Joe Li to onboard frontend development!
@jlyaoyuli 
**Checklist:**

chore(frontend): Add Joe Li to be reviewer of frontend.

---

frontend/OWNERS

_With great power comes great responsibility.     - Uncle Ben_
/assign @jlyaoyuli 
**Checklist:**

chore(frontend): Add Joe Li an approver of KFP frontend

---

frontend/scripts/pipelinespec.sh
frontend/src/generated/pipeline_spec/pipeline_spec.ts
frontend/src/generated/pipeline_spec/pipeline_spec_pb.d.ts
frontend/src/generated/pipeline_spec/pipeline_spec_pb.js

Partial #7611
Update IR to the latest version in FE client. Update the script to create folder for google's rpc file as well.
**Checklist:**

chore(frontend): Update Pipeline Spec in TypeScript

---

frontend/src/features.ts
frontend/src/lib/v2/WorkflowUtils.ts
frontend/src/pages/PipelineDetails.tsx
frontend/src/pages/PipelineDetailsTest.test.tsx

Previously, v2 feature was disabled by default. After the change, a new feature key called v2_alpha is created to enable the v2 feature by default.
**Checklist:**

feat(frontend): Enable KFPv2 UI by default by creating a new feature key #7610

---

frontend/src/pages/RunDetailsV2.tsx

Previously, users cannot see the MLMD update in RunDetail page without refreshing. Now we pull MLMD every 10 seconds. We can potentially discuss the pulling latency, but adding this functionality to enable auto re-fetch.
/assign @jlyaoyuli 
**Checklist:**

feat(frontend): Automatically fetch MLMD for Run status update in V2.

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

Prepare for release.
**Checklist:**

chore(sdk): 2.0.0-alpha.3 release

---

backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/apiserver/resource/resource_manager_util.go
backend/src/apiserver/template/argo_template.go
backend/src/apiserver/template/template.go
backend/src/apiserver/template/v2_template.go
backend/src/common/util/execution_spec.go
backend/src/common/util/execution_spec_test.go
backend/src/common/util/execution_status.go
backend/src/common/util/scheduled_workflow.go
backend/src/common/util/workflow.go
backend/src/common/util/workflow_test.go
backend/third_party_licenses/cache_server.csv
backend/third_party_licenses/persistence_agent.csv
backend/third_party_licenses/swf.csv

issue: #6888
Create an abstraction interface to encapsulate util.Workflow and decouple the dependency of Argo Workflow pkg.
ExecutionSpec wraps the Workflow and other runtime engines in the future. ExecutionStatus is used to access status information.
**Checklist:**

feat(backend): Add ExecutionSpec Interface

---

sdk/python/kfp/client/client.py

Also does considerable clean up of type annotations and other code style aspects.
**Checklist:**

feat(sdk): make client return values consistent

---

sdk/python/kfp/utils/ir_utils.py
sdk/python/kfp/utils/ir_utils_test.py

Formats compiled JSON to multiple lines with indentation.
**Checklist:**

feat(sdk): compile JSON with formatting

---

sdk/python/kfp/cli/pipeline.py
sdk/python/kfp/client/client.py
sdk/python/kfp/client/client_test.py

Validates pipeline resource name client-side before submission to backend.
**Checklist:**

feat(sdk): validate pipeline resource name before submission

---

frontend/src/components/graph/SubDagLayer.tsx
frontend/src/lib/Buttons.ts
frontend/src/pages/__snapshots__/ArchivedRuns.test.tsx.snap

1. Fix incorrect cursor on "Layer" (change to unclickable) .
2. add informative description to "Restore" hover text.
**Checklist:**

fix(frontend): Change "Layer" to unclickable.

---

ROADMAP.md

Reference: https://docs.google.com/presentation/d/18NLhNTHNKywSX3sOGjCcXGiVtqX-o9EuO7oWN9ECPtY/edit?resourcekey=0-Pwz21btM3HhG53ZBY14ToA#slide=id.gfbb06f32f0_0_692
/assign @james-jwu 
**Checklist:**

chore: Add KFP 2022 Roadmap

---

api/v2alpha1/python/setup.py

Bumps `kfp-pipeline-spec` version.
**Checklist:**

chore: bump kfp-pipeline-spec to 0.1.15

---

manifests/kustomize/env/aws/README.md

The current hyperlink results in a 404. This updates the documentation to point to the updated URL. 
**Checklist:**

docs: fix rds documentation link

---

api/v2alpha1/cache_key.proto
api/v2alpha1/pipeline_spec.proto

Fixes proto imports.
Test with: `cd ./api && make`
**Checklist:**
follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

fix(ir): fix kfp-pipeline-spec proto imports

---

ROADMAP.md

chore: Update ROADMAP.md

---

samples/contrib/aws-samples/README.md

- Fix link for installing kubeflow on AWS
**Checklist:**

chore: fix link for installing kubeflow on AWS

---

frontend/src/lib/v2/WorkflowUtils.ts
frontend/src/pages/NewRunSwitcher.tsx
frontend/src/pages/PipelineDetails.tsx

We are moving from V2 to V2_ALPHA for any V2 features, so we can control them all with one flag.
**Checklist:**

fix(frontend): Move all V2 flag check to V2_ALPHA

---

sdk/OWNERS

chore(sdk): Update OWNERS

---

sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/pipeline_task_test.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py
sdk/python/kfp/components/types/type_utils.py
sdk/python/kfp/components/yaml_component_test.py

Enables reading in a primitive component definition from IR YAML.
**Checklist:**
request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

feat(sdk): enable read in component using IR

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

chore(sdk): 2.0.0-alpha.4 release

---

api/v2alpha1/python/setup.py

bump kfp-pipeline-spec minor version to 0.1.16, after adding `IteratorPolicy`
**Checklist:**

chore: bump kfp-pipeline-spec minor version to 0.1.16

---

samples/core/exit_handler/exit_handler_v2.py

fix(test): Make exit handler test install KFP SDK from source

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

Bumps kfp version to 2.0.0a5.
**Checklist:**

chore(sdk): bump kfp version to 2.0.0a5

---

samples/contrib/aws-samples/mnist-kmeans-sagemaker/README.md
samples/contrib/aws-samples/simple_train_pipeline/README.md

- old deeplearning link is now unavailable.
- Get new source from aws-samples-repo for kmeans jobs
**Checklist:**

chore: update source for aws samples input data

---

manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml

fix(manifests): Update snapshot to 2.0.0-alpha.2

---

backend/Dockerfile.viewercontroller

Part of https://github.com/kubeflow/pipelines/issues/7880
**Checklist:**

chore: Pin golang version in `backend/Dockerfile.viewercontroller`

---

sdk/python/kfp/registry/context/__init__.py
sdk/python/kfp/registry/context/kfp_pkg_dev.json
sdk/python/kfp/registry/registry_client.py
sdk/python/kfp/registry/registry_client_test.py

feat(kfp): implement config file support for registry client

---

sdk/python/kfp/compiler/_read_write_test_config.py
sdk/python/kfp/components/structures.py

Fixes extractction of docstring for description in component without `command` field.
**Checklist:**

fix(sdk): fix extract docstring in load component

---

sdk/python/kfp/compiler/_read_write_test_config.py
sdk/python/kfp/compiler/read_write_test.py
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/placeholders.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py

Fixes read/write logic for:
- `ExecutorInputPlaceholder`
- `OutputPathPlaceholder` and `OutputParameterPlaceholder`
And updates tests.
These changes include a significant refactoring and removal of duplicative logic in `structures.py` (and moved 
that logic to `placeholders.py`) for a net negative code line contribution.
**Checklist:**
request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

fix(sdk): fix placeholder read/write logic

---

sdk/python/kfp/compiler/_read_write_test_config.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_concat_placeholder.yaml
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_if_placeholder.yaml
sdk/python/kfp/compiler/test_data/pipelines/xgboost_sample_pipeline.yaml
sdk/python/kfp/components/pipeline_task.py

Fixes compilation of ifpresent placeholder and uses the preferred ifpresent and concat placeholder representation in IR.
**Checklist:**
our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

fix(sdk): fix ifpresent and concat placeholder compile

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

chore(sdk): bump kfp version to 2.0.0b0

---

components/aws/sagemaker/tests/integration_tests/conftest.py

chore: fix link to pytest-xdist docs

---

components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests

Tests are failing with an error where the control plane fails to stabilize, increasing timeout to check if that fixes the issue. 
Also updating the EKS version to 1.21. 
**Checklist:**

chore: update EKS version and increase the EKS cluster creation timeout

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md

The generic bug report issue template is both internally and externally inconsistent. This PR bring it into closer structural alignment with the remaining issue templates. Sorry for the nit! 🙃 
**Checklist:**

chore: standardize bug report issue template

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

* Bumps version
* Updates release notes
**Checklist:**

chore(sdk): bump kfp version to 2.0.0b1

---

samples/contrib/aws-samples/README.md

- Trust policy creation command needs {} to work properly and added --region to the describe cluster command.
**Checklist:**

chore: Update oidc commands to include region and add brackets for trust policy

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

Bumps version to 1.8.13 and sets release notes.
**Checklist:**

chore(sdk): Bump SDK version to 1.8.13

---

sdk/python/setup.py

Sets the `setuptools.setup` long description content type to 'text/markdown' so that PyPI 
can read markdown. For more info: 
https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata.
**Checklist:**
about the pull request title convention used in this 

chore(sdk): use markdown for long description content type v1

---

test/tools/clean-mysql-runs/README.md
test/tools/clean-mysql-runs/clean-mysql-runs.sh
test/tools/clean-mysql-runs/delete_old_runs.py
test/tools/clean-mysql-runs/truncate_cache.sql

Adds script to periodically clean up mysql run records to prevent spurious sample test failures.
**Checklist:**

chore(test): add test infra mysql run cleanup script

---

components/gcp/container/Dockerfile

Issue: kubeflow-pipeline-mkp-test times out as pip cannot finish installing the dependencies.
https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/8013/kubeflow-pipeline-mkp-test/1546902507245015040
```
Step #15 - "buildGcpGenericComponent": [0m[91mWARNING: google-api-core 2.8.2 does not provide the extra 'grpcgcp'
Step #15 - "buildGcpGenericComponent": [0m[91mWARNING: google-api-core 2.8.2 does not provide the extra 'grpcgcp'
Step #15 - "buildGcpGenericComponent": [0m[91mWARNING: google-api-core 2.8.2 does not provide the extra 'grpcgcp'
Step #15 - "buildGcpGenericComponent": [0m[91mWARNING: google-api-core 2.8.2 does not provide the extra 'grpcgcp'
Step #15 - "buildGcpGenericComponent": [0m[91mWARNING: google-api-core 2.8.2 …
```

fix(components): Pin pip version to fix apache-beam[gcp] installation issue

---

backend/README.md

chore: Avoid duplicate go-licenses tool installation instructions

---

.cloudbuild.yaml
.release.cloudbuild.yaml
manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
test/tag_for_hosted.sh

Fix vulnerability issue (CVE-2022-1292) found in existing mysql image.
Though we could reuse the existing image label without this change, it's safer to test the new image first while keep existing users unaffected.
**Checklist:**

fix: Update mysql image to fix CVE-2022-1292

---

manifests/gcp_marketplace/deployer/Dockerfile

Fix vulnerabilities CVE-2022-1292 and CVE-2021-45960 
**Checklist:**

fix: Update GCP marketplace deployer base image

---

test/sample-test/Dockerfile

Follow up on https://github.com/kubeflow/pipelines/pull/8009
**Checklist:**

test: update Argo cli version in sample test

---

components/kubeflow/common/launch_crd.py

fixes https://github.com/kubeflow/pipelines/issues/7984

fix(components): fix launch_crd.py to be compatible with kubernetes python SDK API. Fixes #7984

---

backend/src/cache/deployer/Dockerfile

Same image, pull from GCR instead of Docker hub.
**Checklist:**

chore(backend): Use cloud sdk from GCR as base image for cache deployer

---

backend/src/v2/test/Dockerfile
backend/src/v2/test/requirements-runner.txt

Fixes a dependency resolution issue created by a superfluous 
dependency on `tfx`.
**Checklist:**

test(sdk): fix v2 sample test dependency resolution

---

samples/test/config.yaml
samples/v2/pipeline_container_no_input.py
samples/v2/pipeline_container_no_input_test.py
sdk/python/kfp/compiler/_read_write_test_config.py
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/test_data/components/container_no_input.py
sdk/python/kfp/compiler/test_data/components/container_no_input.yaml
sdk/python/kfp/compiler/test_data/pipelines/container_component_with_no_inputs.py
sdk/python/kfp/compiler/test_data/pipelines/container_component_with_no_inputs.yaml
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/container_component.py
sdk/python/kfp/components/container_component_decorator.py
sdk/python/kfp/components/container_component_decorator_test.py
sdk/python/kfp/components/python_component.py
sdk/python/kfp/dsl/__init__.py

* Added baseline implementation of support container_component decorator (for function with no inputs)
* Added unit tests and complier tests for baseline implementation
**Checklist:**

feat(sdk): support container_component decorator for function with no inputs

---

.isort.cfg

Mentioned in https://github.com/kubeflow/pipelines/blob/master/sdk/CONTRIBUTING.md#formatting-imports-required, but missing from the repo.
**Checklist:**

chore: add the missing `.isort.cfg` file

---

.readthedocs.yml
docs/requirements.txt

There is currently a bug in requirements installation when generating the master branch docs.
I found a way to test builds and confirmed that this is a fix.
**Checklist:**
our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

fix(sdk): fixes requirements.txt discovery for sdk api reference docs

---

.github/renovate.json5

Renovatebot sends frequent pings in its PR. But the attention to it hasn't been high so far. We can depend on dependabot which is already working in place, we don't need two bots for dependency upgrade.
/cc @Ark-kun 
**Checklist:**

chore: Disable renovatebot

---

.github/ISSUE_TEMPLATE/BUG_BACKEND.md
.github/ISSUE_TEMPLATE/BUG_FRONTEND.md
.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/BUG_SDK.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md

/assign @IronPan @james-jwu @chensun 
**Checklist:**

chore: Update issue template.

---

frontend/src/components/NewRunParametersV2.tsx
frontend/src/components/tabs/InputOutputTab.tsx
frontend/src/pages/CompareV2.tsx
frontend/src/pages/NewRun.tsx
frontend/src/pages/NewRunV2.tsx
frontend/src/pages/PipelineDetailsV1.tsx
frontend/src/pages/PipelineDetailsV2.tsx
frontend/src/pages/RunDetailsV2.tsx

Make sure to resolve any styling and ts usage warnings during development.
**Checklist:**

fix(frontend): Resolve all warnings when running `npm run start`

---

sdk/python/kfp/compiler/compiler.py

Sorry, it's just a trivial docs change, but I thought I'd forget if/when I ever got around to making another PR. Feel free to roll into something else.
**Checklist:**

chore(sdk): change "PipelienSpec" to "PipelineSpec"

---

.github/renovate.json5

fix: Renovate json format. Fix #6772

---

frontend/.gitignore
frontend/Dockerfile
frontend/package-lock.json
frontend/package.json
frontend/scripts/yarn-licenses.sh
frontend/server/minio-helper.ts
frontend/server/package-lock.json
frontend/server/package.json
frontend/tailwind.config.js

Context: https://github.com/kubeflow/pipelines/pull/8092
- Replace license-checker with yarn. We can detect dependency licenses using `yarn licenses` and `yarn licenses generate-disclaimer`.
- Use `media` instead of false for tailwindcss `darkMode`.
- Upgrade `caniuse-lite`
- [Upgrade @types/node and note-fetch in frontend server](https://github.com/kubeflow/pipelines/pull/8101/commits/52b1f2be2283f3e40a6c582cd02cac52e0227255)
- Add `npm ci` in Dockerfile for frontend server
**Checklist:**

fix(frontend): Replace license-checker with yarn licenses.

---

frontend/src/pages/CompareV2.tsx

- Re-assign `zpChris`'s `TODO` to `zijianjoy`
**Notes:**
- Since my internship is ending, I'm re-assigning all bugs to my host `zijianjoy`.
**Checklist:**

chore(frontend): Re-assign TODO to `zijianjoy`

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

chore(sdk): bump kfp sdk version to 2.0.0b2

---

sdk/python/kfp/components/base_component_test.py
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/container_component_decorator.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/pipeline_task_test.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py

This PR rename the old ContainerSpec class to ContainerSpecImplementation and expose the new ContainerSpec API for users to author container_components with only `image`, `command` and `args` settings.  
**Checklist:**

feat(sdk): expose new ContainerSpec API 

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

Bumps version and updates 
release notes.
**Checklist:**
pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

chore(sdk): bump kfp version to 2.0.0-beta.3

---

sdk/python/kfp/compiler/test_data/components/container_with_artifact_output.py
sdk/python/kfp/compiler/test_data/components/container_with_artifact_output.yaml
sdk/python/kfp/components/container_component_artifact_channel.py
sdk/python/kfp/components/container_component_artifact_channel_test.py
sdk/python/kfp/components/placeholders.py
sdk/python/kfp/components/placeholders_test.py
sdk/python/kfp/components/structures.py

Create InputMetadataPlaceholder and OutputMetadataPlaceholder classes for accessing `.metadata` attribute for artifacts while authoring containerized components.
**Checklist:**

feat(sdk): add support for metadata placeholders

---

components/contrib/kubernetes/Create_PersistentVolumeClaim/component.yaml

Add namespace to PVC creation.
**Checklist:**

feat(components): add namespace to pvc creation

---

samples/OWNERS

Removes ji-yaqi from samples/OWNERS. Adds connor-mccarthy.
**Checklist:**

chore(sdk): update samples/ owners

---

backend/src/apiserver/resource/model_converter.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/apiserver/server/api_converter.go
backend/src/apiserver/server/api_converter_test.go
backend/src/apiserver/server/job_server_test.go
backend/src/apiserver/server/run_server_test.go
backend/src/apiserver/storage/job_store.go
backend/src/apiserver/storage/job_store_test.go
backend/src/apiserver/storage/run_store.go
backend/test/integration/job_api_test.go
backend/test/integration/run_api_test.go
backend/test/integration/upgrade_test.go

A continuation of #8085 
In #8085, RuntimeConfig was implemented for runs. In this PR, RuntimeConfig is implemented for jobs(a.k.a. RecurringRuns).
**Checklist:**

feat(backend): Implement RuntimeConfig in backend for jobs(RecurringRun)

---

sdk/RELEASE.md
sdk/python/kfp/compiler/_read_write_test_config.py
sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_outputs.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_outputs.yaml
sdk/python/kfp/components/graph_component.py
sdk/python/kfp/components/pipeline_task.py

feat(sdk): Support pipeline outputs

---

.cloudbuild.yaml
.release.cloudbuild.yaml
components/gcp/container/Dockerfile
components/gcp/container/build_image.sh
components/gcp/container/component_sdk/python/kfp_component/google/dataproc/_client.py

fix: cherry-pick changes to fix kubeflow-pipeline-mkp-test

---

.cloudbuild.yaml
.release.cloudbuild.yaml
components/gcp/container/Dockerfile
components/gcp/container/build_image.sh
components/gcp/container/component_sdk/python/kfp_component/google/dataproc/_client.py
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/gcp_marketplace/schema.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml

Upgrade argo for GCP Markerplace

---

sdk/python/README.md

Added type hints so that the example can be compiled.
Otherwise, the compiler would raise `TypeError: Missing type annotation for argument: a`.
**Checklist:**

chore: Fix the example pipeline in sdk/python/README.md

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/config-snapshot.yaml
manifests/gcp_marketplace/schema.yaml

Making emissary executor default for GCP Marketplace deployment
**Checklist:**

Make emissary executor default

---

sdk/python/README.md

Fixes README pipeline in KFP v1.
**Checklist:**

fix(docs): fix README pipeline example

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/config-snapshot.yaml
manifests/gcp_marketplace/schema.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml

- Sync argo.yaml in GCP Marketplace deployment
- Remove the checkbox for enabling emissary executor on Marketplace UI (emissary is default now)
**Checklist:**

chore: Update GCP Marketplace manifests

---

sdk/python/kfp/components/tasks_group.py

Fixes a small mistake from #8088.
**Checklist:**

fix(sdk): fix constructor signature on dsl.Condition

---

sdk/python/requirements-dev.txt
test/presubmit-isort-sdk.sh

Checks for unused imports in CI before checking sorting. Related to https://github.com/kubeflow/pipelines/pull/8123.
**Checklist:**

chore(sdk): add script to check for unused imports

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

chore(sdk): bump kfp version to 2.0.0-beta.4

---

sdk/python/kfp/components/tasks_group.py

Fixes an error and clarifies usage in control flow docstrings.
**Checklist:**

fix(sdk): fix dsl control flow docstrings

---

docs/_static/custom.css
docs/conf.py
docs/requirements.txt

Uses a new, modern theme for KFP SDK reference documentation version 2.0.0b4 and up.
Can be previewed here: https://kubeflow-pipelines.readthedocs.io/en/modernize-kfp-reference-docs/
**Checklist:**

feat(docs): use new sdk reference docs theme

---

docs/conf.py

fix(sdk): fix docs version reference

---

sdk/python/kfp/client/__init__.py
sdk/python/kfp/client/client.py
sdk/python/kfp/client/set_volume_credentials.py
sdk/python/kfp/client/set_volume_credentials_test.py
sdk/python/kfp/client/token_credentials_base.py
sdk/python/kfp/client/token_credentials_base_test.py

Migrates v1 auth to v2. Finishes PR started by #7497.
**Checklist:**

feat(sdk): migrate v1 auth to v2

---

sdk/python/kfp/components/pipeline_task.py
sdk/python/test_data/pipelines/xgboost_sample_pipeline.yaml

This PR keeps placeholder strings in command and args even if a default value is set.   
**Checklist:**

fix(sdk): keeping placeholder strings in command and args even if default value is set

---

components/aws/sagemaker/Dockerfile
components/aws/sagemaker/TrainingJob/samples/mnist-kmeans-training/mnist-kmeans-training-pipeline.py
components/aws/sagemaker/codebuild/deploy.buildspec.yml
components/aws/sagemaker/codebuild/integration-test.buildspec.yml
components/aws/sagemaker/codebuild/scripts/deploy.sh
components/aws/sagemaker/codebuild/unit-test.buildspec.yml
components/aws/sagemaker/common/generate_components.py
components/aws/sagemaker/tests/integration_tests/utils/minio_utils.py
components/aws/sagemaker/tests/unit_tests/Dockerfile

- Update codebuild ymls to login to public ecr instead of docker
- Run black on *.py files that were not formatted so that unit-test codebuild passes
**Not visible in PR**
- Added necessary permissions and policies for ci/cd to push to public-ecr cross account
**Checklist:**

chore(components): Update scripts to use public ecr instead of docker

---

sdk/python/kfp/components/structures.py

Fixes v1 component YAML output deserialization logic.
**Checklist:**

fix(sdk): fix v1 output deserialization

---

sdk/RELEASE.md

As per discussion in #8262, I am adding the PR in the notes for the future release.
**Checklist:**
- [x ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

chore: Add PR 8262 to sdk/RELEASE.md

---

sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/components/base_model.py
sdk/python/kfp/components/base_model_test.py
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/importer_node.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/placeholders.py
sdk/python/kfp/components/placeholders_test.py
sdk/python/kfp/components/structures.py

This PR renames private methods in IfPresentPlaceholders and ConcatPlaceholders for simpler API reference in documentation.  
**Checklist:**

chore(sdk): hide private methods in placeholders for simpler doc 

---

sdk/RELEASE.md
sdk/python/kfp/_auth.py
sdk/python/kfp/_client.py

* Same logic being applied as in #8262 (check it out for more details)
* Tested on KF 1.6.0
**Checklist:**

fix(sdk): Add OOB fix for v1.8 from #8262

---

sdk/python/kfp/components/executor.py
sdk/python/kfp/components/executor_test.py

Fixes an error with InputPath handling in executor.
**Checklist:**

fix(sdk): fix InputPath error in executor

---

sdk/python/kfp/components/executor.py
sdk/python/kfp/components/executor_test.py

Adds support for a google-specific artifact 
construction workaround.
**Checklist:**
follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

feat(sdk): add workaround for google artifact (support custom artifact types pt. 4)

---

sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.py
sdk/python/kfp/v2/components/importer_node.py
sdk/python/kfp/v2/components/importer_node_test.py

Implements #7660 in v1
**Checklist:**
convention. 

feat(sdk): add support for dynamic importer metadata in sdk v1

---

sdk/OWNERS

chore: Update sdk/OWNERS in sdk/release-1.8 branch

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py

Bump version and update release notes.
**Checklist:**

chore(sdk): 1.8.14 release

---

frontend/package.json
frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx

test(frontend): Enforce no warning standard in frontend development.

---

samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb

Changes cifar10 input json url path from commit to master branch.
**Checklist:**

chore(components/pytorch) - fix url paths

---

components/aws/sagemaker/tests/integration_tests/Dockerfile
components/aws/sagemaker/tests/integration_tests/environment.yml
components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests

`components/aws/sagemaker/tests/integration_tests/Dockerfile` - Updated eksctl and kubectl
`components/aws/sagemaker/tests/integration_tests/environment.yml` - Updated kfp sdk version
`components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests` - Updated kfp version and updated kfp installation to use cert-manager.
**Checklist:**

test: Upgrade kfp version in sagemaker component test

---

components/kserve/OWNERS
components/kubeflow/kfserving/OWNERS

Adding myself as the approver and @yhwang as the new reviewer since we are the one who mainly review and update the kserve component.
**Checklist:**

chore: update kserve component owners

---

sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/v2/__init__.py

Removes two unused linter comments.
**Checklist:**

chore(sdk): remove unused linter comments

---

test/presubmit-yapf-sdk.sh

Check single quote in formatting presubmit so that reviewer does not have to and so that it does not distract from code 
reviews.
**Checklist:**

chore(test): check single quote in formatting presubmit

---

test/OWNERS

chore: update test/OWNERS

---

.pre-commit-config.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml

* Replacing `partner_id` with the appropriate value. This change should be included in the next v1 and v2 releases.
* Includes minor changes to the yaml pre-commit hook to allow [multiple yaml definitions in a single document](https://github.com/pre-commit/pre-commit-hooks/blob/397156958867b10f165e20f5121285ff31a1d783/README.md#check-yaml) and exclude gcp_marketplace snapshots from [trailing-whitespace hook](https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace).
**Checklist:**

feat(backend): fix partner_id in GCP Marketplace application

---

samples/test/metrics_visualization_v2.py

The `sklearn` package is being deprecated: https://pypi.org/project/sklearn/
which causes v2-samples presumit test failure:
```
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.9/site-packages/kfp/components/executor_main.py", line 107, in <module>
executor_main()
File "/usr/local/lib/python3.9/site-packages/kfp/components/executor_main.py", line 103, in executor_main
executor.execute()
File "/usr/local/lib/python3.9/site-packages/kfp/components/executor.py", line 320, in execute
result = self._func(**func_kwargs)
File …
```

fix(samples): update sklearn package name

---

backend/src/v2/Makefile

To prevent accidentally pushing to the public images.
**Checklist:**

chore: require setting v2 image prefix in Makefile

---

CONTRIBUTING.md

chore: update contributing guideline

---

backend/src/common/util/execution_spec.go
backend/src/common/util/workflow.go
backend/src/common/util/workflow_test.go
backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go

v2 recurring run failed to schedule pods as Argo workflow controller reported error: 
> "invalid spec: templates.entrypoint.tasks.root templates.root.tasks.print-op-driver failed to resolve {{workflow.annotations.pipelines.kubeflow.org/components-comp-print-op}}"
To make v2 recurring run work, we need to pass the entire workflow--which contains `workflow.annotations`--rather than only `workflow.spec`.
**Checklist:**

fix(backend): Fix recurring run for v2 pipeline

---

docs/conf.py

Updating the reference docs version dropdown menu so that newer versions of the docs have references to previous versions.
Before:
After:
**Checklist:**

docs(sdk): add released versions to version dropdown

---

sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/component_factory_test.py
sdk/python/kfp/components/executor.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/types/custom_artifact_types.py
sdk/python/kfp/components/types/type_annotations.py
sdk/python/kfp/components/types/type_annotations_test.py

Supports lists of artifacts in component interfaces. Blocks 
use of output lists of artifacts for now.
**Checklist:**

feat(sdk): support list of artifacts annotations [list of artifacts support pt. 1]

---

api/v2alpha1/pipeline_spec.proto

Changes field name from #8466. Also updates comment to reduce likelihood of it going stale.
**Checklist:**

feat(IR): change is_list_of_artifacts proto field to is_artifact_list

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml

fix(manifests): Change mysql default binlog expire to 10 days. Fixes #8552

---

docs/conf.py

**Checklist:**
request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

chore(sdk): add KFP SDK 1.8.17 to docs dropdown

---

sdk/RELEASE.md
sdk/python/setup.py

fix(sdk): Fix sdk requirements for kubernetes v19 dependency

---

sdk/RELEASE.md

Moves an item from "Breaking Changes" to "Bug Fixes and Other Changes".
**Checklist:**

chore(sdk): fix 1.8.17 release notes

---

api/v2alpha1/pipeline_spec.proto

feat(IR): add is_optional field for input artifacts

---

sdk/python/kfp/components/executor.py
sdk/python/kfp/components/executor_test.py

Supports input lists of artifacts in Lightweight Python Components and Containerized Python components.
**Checklist:**

feat(sdk): add support for lists of artifacts in Python components [support lists of artifacts pt. 3]

---

sdk/python/kfp/components/types/type_utils.py

fixes #8586 by introducing special handling for `PipelineTaskFinalStatus` everywhere
**Checklist:**

fix(sdk): add special handling for PipelineTaskFinalStatus to get_parameter_type

---

docs/conf.py

chore(sdk): add 2.0.0b9 and 1.8.18 to docs

---

components/aws/OWNERS
components/aws/sagemaker/OWNERS
samples/contrib/aws-samples/OWNERS

Adds all current owners of AWS components to all owner files and removes those who are no longer owners.
**Checklist:**

chore(components): Update aws owners files to reflect current owners

---

components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests

Disables imdsv1 in ephemeral canary test
Dry run/patching is needed because eksctl does not have a flag (`-- flag`) to disable imdsv1.
ssm is enabled by default, removed the flag to prevent redundant warning.
**Checklist:**

test(components): disable imdsv1

---

backend/src/apiserver/server/job_server_test.go

Added tests for recurring run server.
**Checklist:**

test(backend): add recurring run tests

---

manifests/gcp_marketplace/OWNERS

chore: Add gkcalat to OWNERS of gcp_marketplace manifests

---

sdk/python/kfp/client/client.py

This PR tidies up the type hints in the client module.
**Checklist:**

chore(sdk): clean up client.py

---

manifests/kustomize/env/platform-agnostic-multi-user-pns/workflow-controller-configmap-patch.yaml
manifests/kustomize/env/platform-agnostic-pns/workflow-controller-configmap-patch.yaml

This PR just removes an inaccurate comment about docker in one of the manifests and standardizes the comments across two otherwise identical kustomize patches.
**Checklist:**

docs[manifests]: fix and standardize pns comments

---

sdk/python/kfp/cli/diagnose_me/utility.py
sdk/python/kfp/cli/diagnose_me/utility_test.py

This PR simplifies a CLI utility function by switching to `subprocess.run`.
Also, this PR includes unit tests for the same
**Checklist:**

chore(sdk): Improve CLI utility function

---

sdk/RELEASE.md

Feature was included in breaking changes.
**Checklist:**

chore(sdk): fix release notes

---

docs/conf.py

Remove 2.0.0b10 docs (yanked version).
**Checklist:**

chore(sdk): remove 2.0.0b10 docs

---

frontend/src/lib/Utils.test.ts
frontend/src/lib/Utils.tsx
frontend/src/pages/NewRun.tsx

This PR makes run parameters not to get cleared (or defaulted) on pipeline version change.
It affects NewRun page only if `cloneFromRun` param is provided.
Params are preserved only if they are presented in new version parameters by name.
**Checklist:**

fix(frontend): preserve run parameters on pipeline version change for cloned runs. Fixes #4944

---

.pre-commit-config.yaml

Fixes `isort`x`poetry` bug via `isort` [hotfix 5.11.5](https://github.com/PyCQA/isort/issues/2083#issuecomment-1408300628).
**Checklist:**

chore(sdk): fix isort version in pre-commit

---

backend/src/apiserver/resource/resource_manager.go
backend/test/integration/pipeline_api_test.go
backend/test/integration/upgrade_test.go

- Adding to read manifest from object store for pipeline versions with empty PipelineSpec field
- Test cases for creating runs and a job in the upgrade e2e test
- Fixes #8802 
**Checklist:**

fix(backend): fix run, job from empty manifest. Closes #8802.

---

test/frontend-integration-test/Dockerfile
test/frontend-integration-test/helloworld.spec.js
test/frontend-integration-test/package-lock.json
test/frontend-integration-test/package.json
test/frontend-integration-test/selenium-standalone-chrome-gcloud-nodejs.Docker/Dockerfile
test/frontend-integration-test/wdio.conf.js

frontend-integration-test uses a very old chromedriver (from 3 years ago), and was suspected to be a possible cause of presubmit tests flakiness. Also the main test library webdriverio is 4 major versions away from the latest. 
Upgrade the test infra to use the latest image and libraries. 
**Checklist:**

test(frontend): upgrade frontend integration test dependencies and base image.

---

backend/src/v2/test/requirements.txt

Fix postsubmit test error:
```
+++ dirname ./backend/src/v2/test/integration-test.sh
++ cd ./backend/src/v[2](https://oss.gprow.dev/view/gs/oss-prow/logs/kubeflow-pipelines-postsubmit-integration-
...
+ pip3 install --quiet -r requirements.txt
...
File "scripts/upload_gcs_blob.py", line [19](https://oss.gprow.dev/view/gs/oss-prow/logs/kubeflow-pipelines-postsubmit-integration-v2/1622768281360273408#1:build-log.txt%3A19), in <module>
import fire
ModuleNotFoundError: No module named 'fire'
make: *** [Makefile:39: upload] Error 1
```
**Checklist:**

fix(test): fix missing test dependencies

---

test/release/bump-version-in-place.sh

- Export `API_VERSION`
- Repeat API generation for `v1beta1` and `v2beta1`
**Checklist:**

fix(release): Add v1 and v2 proto generation. Closes #8818

---

test/deploy-cluster.sh
test/test-prep.sh
test/tools/project-cleaner/resource_spec.yaml

We have temporary issues creating test cluster in us-east1-b, switch to us-west1-b to unblock test and release.
**Checklist:**

chore(test): create test cluster in us-west1-b

---

frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx

The artifact node in run details page shouldn't display `finished at` information. 
Before:
After:

fix(frontend): Remove the "finished at" information for artifact node.

---

proxy/attempt-register-vm-on-proxy.sh

**Description of your changes:** Just fixes a typo.
**Checklist:**

fix(proxy): fixes typo

---

backend/api/v1beta1/python_http_client/setup.py
backend/src/v2/test/Dockerfile
backend/src/v2/test/sample-test.sh
sdk/python/kfp/deprecated/_client.py
test/sample-test/Dockerfile

chore(test): revert api changes to deprecated client

---

components/google-cloud/RELEASE.md
components/google-cloud/google_cloud_pipeline_components/experimental/automl/forecasting/bqml_arima_predict_pipeline.json
components/google-cloud/google_cloud_pipeline_components/experimental/automl/forecasting/bqml_arima_train_pipeline.json
components/google-cloud/google_cloud_pipeline_components/experimental/automl/forecasting/prophet_predict_pipeline.json
components/google-cloud/google_cloud_pipeline_components/experimental/automl/forecasting/prophet_trainer_pipeline.json
components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/automl_tabular_pipeline.json
components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/tabnet_hyperparameter_tuning_job_pipeline.json
components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/tabnet_trainer_pipeline.json
components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/wide_and_deep_hyperparameter_tuning_job_pipeline.json
components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/wide_and_deep_trainer_pipeline.json

Fix AutoML Table pipeline failing on importing model evaluation metrics.

Add GCPC 1.0.39 release commit

---

docs/conf.py

chore(sdk): add 1.8.19 docs

---

frontend/src/apisv2beta1/pipeline/api.ts
frontend/src/apisv2beta1/recurringrun/api.ts
frontend/src/apisv2beta1/run/api.ts

The main purpose of this PR is to generate the latest typescript API client to use the `listAllRuns` API in run list page.

chore(frontend): Regenerate TypeScript API client for the latest changes (add listAllRuns).

---

components/google-cloud/OWNERS

chore: add connor-mccarthy to GCPC owners

---

api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
api/v2alpha1/pipeline_spec.proto

Adds platform-specific wrapper protos to `kfp-pipeline-spec` package.
**Checklist:**

feat: add platform-specific configuration protos to `kfp-pipeline-spec` package

---

sdk/RELEASE.md
sdk/python/kfp/components/tasks_group.py
sdk/python/setup.py

Allows the python 3.11 version to be enabled, by fixing some test failures caused by the 3.11 new features
**Checklist:**

fix(sdk): Support python 3.11

---

components/google-cloud/OWNERS

chore(components): remove connor-mccarthy from GCPC owners

---

frontend/src/apisv2beta1/run/api.ts

Update TS API client to match the change in https://github.com/kubeflow/pipelines/pull/8920.

chore(frontend): Regenerate typescript API client to match the revert change in PR #8920

---

README.md

Kubeflow Pipelines start using Emissary Executor by default since 1.8
**Checklist:**

doc: Update README to reflect switch to Emissary Executor as default from Kubeflow Pipelines 1.8

---

manifests/kustomize/OWNERS

- Added `gkcalat` to the [OWNERS](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/OWNERS) file.
**Checklist:**

chore(manifests): Add gkcalat to OWNERS in manifest/kustomize

---

backend/src/apiserver/server/api_converter.go

fix(backend): Fix priority in spec source. Closes #8948

---

api/v2alpha1/python/setup.py

chore: release kfp-pipeline-spec 0.2.1

---

sdk/python/requirements.in

chore(sdk): pin kfp-pipeline-spec to 0.2.1

---

api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/pipeline_spec_builder_test.py
sdk/python/kfp/components/base_component.py
sdk/python/kfp/components/component_decorator_test.py
sdk/python/kfp/components/graph_component.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/pipeline_task_test.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py
sdk/python/kfp/components/yaml_component.py

Supports the `PipelineTask.platform_config` property for setting platform-specific features.
Future PRs will update the client and the documentation.
**Checklist:**
request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

feat(sdk): support compiling platform specific features

---

kubernetes_platform/python/README.md
kubernetes_platform/python/kfp/kubernetes/common.py
kubernetes_platform/python/kfp/kubernetes/secret.py
kubernetes_platform/python/kfp/kubernetes/volume.py
kubernetes_platform/python/setup.py
kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.py
kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.yaml
kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc.py
kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc.yaml
kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc_from_task_output.py
kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc_from_task_output.yaml
kubernetes_platform/python/test/snapshot/data/secret_as_env.py
kubernetes_platform/python/test/snapshot/data/secret_as_env.yaml
kubernetes_platform/python/test/snapshot/data/secret_as_vol.py
kubernetes_platform/python/test/snapshot/data/secret_as_vol.yaml
kubernetes_platform/python/test/snapshot/read_write_test.py
kubernetes_platform/python/test/snapshot/test_data_config.yaml
kubernetes_platform/python/test/unit/test_secret.py
kubernetes_platform/python/test/unit/test_volume.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
test/presubmit-test-kfp-kubernetes-library.sh

feat: implement `kfp-kubernetes` library

---

kubernetes_platform/OWNERS

Add myself to the OWNERS file
**Checklist:**

Add gkcalat to kubernetes_platform/OWNERS

---

api/v2alpha1/pipeline_spec.proto

Fix typo in IR field description

---

backend/Dockerfile.cacheserver
backend/Dockerfile.persistenceagent
backend/Dockerfile.scheduledworkflow

* Fixes https://github.com/kubeflow/pipelines/issues/8943
* Switching to the latest version of alpine image, fixed all the CVEs
* changed user from root to `appuser` because of the compliance issue  `(CIS_Docker_CE_v1.1.0 - 4.1) Image should be created with a non-root user`
Before:
```
Vulnerability
Critical: 2
High:     12
Medium:   4
Low:      0
Total:    18
Compliance
Critical: 0
High:     1
Medium:   0
Low:      0
Total:    1
```
After:
```
Vulnerability
Critical: 0
High:     0
Medium:   0
Low:      0
Total:    0
Compliance
Critical: 0
High:     0
Medium:   0
Low:      0
Total:    0
```
**Checklist:**

fix(backend): fix CVEs in persistenceagent, scheduledworkflow and cache-server. Fixes #8943

---

api/v2alpha1/pipeline_spec.proto

**Checklist:**
should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

feat: add TASK_FINAL_STATUS to PipelineSpec ParameterTypeEnum

---

api/v2alpha1/pipeline_spec.proto

feat: Add cpu_request and memory_request in pipeline_spec.

---

api/v2alpha1/pipeline_spec.proto

Fix display_name and description fields.

---

sdk/python/kfp/compiler/compiler.py

Reverts kubeflow/pipelines#9090

Revert "chore(sdk): update compiler type annotations"

---

backend/src/apiserver/server/pipeline_server_test.go
backend/src/apiserver/server/test/xgboost_sample_pipeline.yaml
backend/src/apiserver/server/util.go
backend/src/apiserver/server/util_test.go

Although we support [larger file sizes now](https://github.com/kubeflow/pipelines/blob/4e85352ed484db84dca5414f32c4a0c0eebf7c85/backend/src/apiserver/common/const.go#L62), the size for reading from URL is still constrained due to [package bufio's limit](https://pkg.go.dev/bufio#pkg-constants). This PR updated the related function for loading files from URLs, as well as added related unit tests.
Fixes #7652
**Checklist:**

fix(backend): support reading large doc from URL; Fixes #7652

---

components/aws/sagemaker/codebuild/integration-test.buildspec.yml
components/aws/sagemaker/tests/integration_tests/Dockerfile
components/aws/sagemaker/tests/integration_tests/resources/config/ack-training-job/config.yaml
components/aws/sagemaker/tests/integration_tests/resources/config/rlestimator-training/config.yaml
components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests

- use cached images for tools used to run the tests. Remove copy for pipelines repo because we dont want to run stale tests
- increase timeout for few tests
- add wait for cert-manager pods
**Checklist:**

chore(components): add test image cache

---

api/.gitignore
api/v2alpha1/python/setup.py

chore: release kfp-pipeline-spec 0.2.2

---

frontend/src/components/ExperimentList.test.tsx
frontend/src/components/ExperimentList.tsx
frontend/src/pages/ExperimentList.test.tsx
frontend/src/pages/ExperimentList.tsx
frontend/src/pages/NewRunSwitcher.tsx
frontend/src/pages/NewRunV2.test.tsx
frontend/src/pages/NewRunV2.tsx
frontend/src/pages/PipelineDetails.test.tsx
frontend/src/pages/PipelineDetails.tsx
frontend/src/pages/PipelineDetailsV2.test.tsx
frontend/src/pages/RecurringRunDetailsV2.test.tsx
frontend/src/pages/RecurringRunDetailsV2.tsx
frontend/src/pages/RecurringRunList.test.tsx
frontend/src/pages/RecurringRunList.tsx
frontend/src/pages/RunDetailsV2.test.tsx
frontend/src/pages/RunDetailsV2.tsx
frontend/src/pages/RunList.test.tsx
frontend/src/pages/RunList.tsx

chore(frontend): Integrate experiment and run (cross-functionality call) with v2 API

---

docs/conf.py

Incorporate release from https://github.com/kubeflow/pipelines/pull/9066
**Checklist:**
should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

docs(sdk): add KFP SDK 1.8.20 reference docs

---

sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/container_component_decorator_test.py

chore(sdk): set private _ir_type attribute on InputValuePlaceholder

---

sdk/python/kfp/dsl/__init__.py

/assign @connor-mccarthy
**Checklist:**

feat(sdk): Support PIPELINE_ROOT_PLACEHOLDER

---

kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.py
kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.yaml

Make components depends on volume, so that we can verify if volume actually works.
**Checklist:**

chore: make a more testable volume sample

---

kubernetes_platform/python/README.md
kubernetes_platform/python/setup.py

chore(sdk): add kfp-kubernetes documentation to PyPI

---

sdk/python/setup.py

chore(sdk): add kfp-kubernetes as kfp extras_require

---

samples/test/parameter_with_format_test.py

test: added verify_func in TestCase

---

frontend/src/components/UploadPipelineDialog.tsx

Before:
https://user-images.githubusercontent.com/56132941/233198178-1fa12678-490b-4d2f-83d9-1ec88aa36e36.mov
After: 
https://user-images.githubusercontent.com/56132941/233198211-4b751498-73de-4c47-b723-ac080d202a61.mov

fix(frontend): Replace obsoleted hyperlinks in new pipeline page.

---

components/aws/sagemaker/tests/integration_tests/component_tests/test_deploy_component.py
components/aws/sagemaker/tests/integration_tests/component_tests/test_train_component.py
components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py
components/aws/sagemaker/tests/integration_tests/pytest.ini

- Create shallow_canary marker to run a subset of canary_test in some regions.
- Include the following tests in shallow_canary: test_trainingjob, test_trainingjobV2, and test_create_endpoint
**Checklist:**

test(components): Add shallow_canary marker

---

sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/container_component_decorator_test.py

fix(sdk): fix handling of PipelineTaskFinalStatus in ir_type_ attribute hack

---

components/aws/sagemaker/tests/integration_tests/component_tests/test_deploy_component.py
components/aws/sagemaker/tests/integration_tests/requirements.txt
components/aws/sagemaker/tests/integration_tests/resources/config/ack-training-job/config.yaml
components/aws/sagemaker/tests/integration_tests/resources/config/assume-role-processing/config.yaml
components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-algo-mnist-processing/config.yaml
components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-endpoint/config.yaml
components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-update-endpoint/config.yaml

- Upgrade sagemaker package together with boto3 and pyyaml
- Change instance type for training and endpoint canary 
- Remove dependency on "sagemaker-sample-data-<region>" bucket.
**Checklist:**

test: Upgrade package versions and remove dependency on "sagemaker-sample-data-<region>" bucket

---

components/aws/sagemaker/tests/integration_tests/component_tests/test_deploy_component.py
components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py
components/aws/sagemaker/tests/integration_tests/utils/__init__.py

Only populate values that are necessary for shallow_canary.
**Checklist:**

test: fix "ValueError: Unsupported region". Only populate necessary values for shallow_canary

---

frontend/src/pages/RunDetailsV2.test.tsx
frontend/src/pages/RunDetailsV2.tsx

fix(frontend): Render run parameters in run details tab.

---

frontend/src/pages/NewRun.test.tsx
frontend/src/pages/NewRun.tsx

Before:
https://user-images.githubusercontent.com/56132941/235541290-9f0aa553-e92a-48e7-b394-6905f6594db4.mov
After:
https://user-images.githubusercontent.com/56132941/235541320-3893da99-7cdb-4058-9fde-5845b5313397.mov

fix(frontend): Redirect to recurring run list after creating v1 recurring run.

---

backend/test/v2/integration/upgrade_test.go
test/api-integration-test/run_test.sh
test/e2e_test_gke_v2.yaml
test/upgrade-tests.sh

Part of https://github.com/kubeflow/pipelines/issues/6168
**Checklist:**

[WIP] test: Add v2 upgrade test

---

frontend/src/data/test/create_mount_delete_dynamic_pvc.yaml
frontend/src/generated/pipeline_spec/index.ts
frontend/src/lib/v2/WorkflowUtils.test.ts
frontend/src/lib/v2/WorkflowUtils.ts

Part of #9192
Add unit test to validate the helper function getPipelineDefFromYaml().
Add a multi-doc yaml for unit test.

chore(frontend): Abstract the logic of retrieving pipeline definition in multi-doc yaml file.

---

components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_hosting.py
components/aws/sagemaker/tests/integration_tests/utils/sagemaker_utils.py

- Various bug fixes for shallow canary
**Checklist:**

test(components): fix Sagemaker component shallow canary

---

backend/src/common/client/api_server/v1/healthz_client.go
backend/test/integration/healthz_api_test.go

This change will also be ported to release-2.0-alpha branch to support conformance tests for KF 1.7, which is using alpha.7 version of KFP.

fix(conformance): enable healthz test in full Kubeflow.

---

frontend/Dockerfile

Fixes [CVE-2022-37434⁠](https://dso.docker.com/cve/CVE-2022-37434) exists in the current image: [node:14.18.2-alpine
](https://hub.docker.com/layers/library/node/14.18.2-alpine/images/sha256-32da6fccb2b5cb2ae235147872d0a490d2b49dfb7d250ee2366b2db939f6a8f8?context=explore)
**Checklist:**

chore: Update frontend image

---

proxy/Dockerfile

Fixes the following CVEs:
- CVE-2021-46848
- CVE-2022-32221
- CVE-2022-23521
- CVE-2022-41903
Manually built and swapped into a kfp 2.0.0-beta.1 deployment, no issue found.
**Checklist:**

chore: upgrade proxy agent image

---

frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx

Before:
https://user-images.githubusercontent.com/56132941/236517962-016f3c01-c4f4-43eb-88a1-be13a665a5fa.mov
After:
https://user-images.githubusercontent.com/56132941/236518272-0ac96d97-0529-47a5-8fb6-cef297670d69.mov

fix(frontend): Logs details is not changed when selected other execution node.

---

frontend/src/pages/NewRun.tsx
frontend/src/pages/NewRunSwitcher.tsx
test/frontend-integration-test/helloworld.spec.js

Pipeline with parameter:
https://user-images.githubusercontent.com/56132941/236520274-59e14588-16c3-405f-8676-a61f72f99067.mov
Before:
https://user-images.githubusercontent.com/56132941/236520391-209ffc1f-5dd8-4e5b-802d-5f6407f95de2.mov
After:
https://user-images.githubusercontent.com/56132941/236520596-705acb67-543c-4745-8a22-54b80cdc77f1.mov

fix(frontend): Parameter field is missing when creating run from run list

---

SECURITY.md

- Added SECURITY.md with instruction on how to report security vulnerabilities.
**Checklist:**

chore(repo): Add SECURITY.md. Fixes #9319.

---

frontend/src/pages/NewRun.tsx
frontend/src/pages/NewRunV2.tsx

Before:
`From recurring run list`
https://user-images.githubusercontent.com/56132941/236576998-176a6c3a-a4ec-4a4e-a45e-709e81cae62b.mov
`From v2 new run`
https://user-images.githubusercontent.com/56132941/236576672-b14c5e49-7a77-4974-9f64-ffc6eb5ab4cd.mov
After:
`From recurring run list`
https://user-images.githubusercontent.com/56132941/236576817-ba2d411e-17b8-4c08-8377-306f49ee3a49.mov
`From v2 new run`
https://user-images.githubusercontent.com/56132941/236577260-b0044c64-3706-461a-8fdb-5fd5fd945e58.mov

fix(frontend): Incorrect run type after pipeline is selected

---

frontend/src/components/Toolbar.tsx

fix(frontend): Buttons dislocated in narrow toolbar

---

frontend/src/components/tabs/RuntimeNodeDetailsV2.test.tsx
frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
frontend/src/components/tabs/StaticNodeDetailsV2.tsx
frontend/src/generated/platform_spec/kubernetes_platform/index.ts
frontend/src/lib/v2/NodeUtils.tsx
frontend/src/lib/v2/WorkflowUtils.test.ts
frontend/src/lib/v2/WorkflowUtils.ts
frontend/src/pages/RunDetailsV2.tsx

In KFP v2, we put volume mount information in **Task Details** tab in the side panel of run details

feature(frontend): Support volume mounts in KFP v2

---

docs/conf.py
sdk/RELEASE.md
sdk/python/kfp/__init__.py
sdk/python/kfp/client/client.py
sdk/python/requirements.in
sdk/python/requirements.txt

chore: release KFP SDK 2.0.0-beta.17

---

backend/src/common/client/api_server/healthz_client.go
backend/test/integration/healthz_api_test.go

* Enable healthz test in full Kubeflow.
This change will also be ported to release-2.0-alpha branch to support conformance tests for KF 1.7, which is using alpha.7 version of KFP.
* Fix build break due to recent refactoring.

fix(conformance): enable healthz test in full Kubeflow. (#9297)

---

components/aws/sagemaker/Changelog.md
components/aws/sagemaker/DataQualityJobDefinition/component.yaml
components/aws/sagemaker/Endpoint/component.yaml
components/aws/sagemaker/Endpoint/src/Endpoint_component.py
components/aws/sagemaker/EndpointConfig/component.yaml
components/aws/sagemaker/EndpointConfig/src/EndpointConfig_component.py
components/aws/sagemaker/ModelBiasJobDefinition/component.yaml
components/aws/sagemaker/ModelExplainabilityJobDefinition/component.yaml
components/aws/sagemaker/ModelQualityJobDefinition/component.yaml
components/aws/sagemaker/Modelv2/component.yaml
components/aws/sagemaker/Modelv2/src/Model_component.py
components/aws/sagemaker/MonitoringSchedule/component.yaml
components/aws/sagemaker/THIRD-PARTY-LICENSES.v2.txt
components/aws/sagemaker/TrainingJob/component.yaml
components/aws/sagemaker/TrainingJob/src/TrainingJob_component.py

feat(components): SageMaker V2 model monitor component release

---

backend/src/apiserver/common/utils.go
backend/src/apiserver/common/utils_test.go
backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/apiserver/server/pipeline_server.go
backend/src/apiserver/server/pipeline_server_test.go
backend/src/apiserver/server/pipeline_upload_server.go
backend/src/apiserver/server/pipeline_upload_server_test.go
backend/test/integration/pipeline_api_test.go
backend/test/integration/pipeline_version_api_test.go

- Added validation of the pipeline name in `spec.pipeline-info.name` that matches the MLMD requirements for the following calls:
- Upload pipeline (v1)
- Create pipeline (v1)
- Upload pipeline version
- Create pipeline version
- Added a few unit tests related to name validation
- Relaxes requirements for pipeline's `DisplayName`
- Removed irrelevant unit tests
- Removed logic for overwriting `spec.pipeline-info.name`
/CC @jlyaoyuli 
**Checklist:**

fix(backend): Add pipeline spec name validation and relax display name validation

---

frontend/src/pages/ExecutionList.test.tsx
frontend/src/pages/ExecutionList.tsx

#8987 
Before:
https://github.com/kubeflow/pipelines/assets/56132941/fca29f65-3256-48d6-ba1d-086ec16416d6
After:
https://github.com/kubeflow/pipelines/assets/56132941/ccb7cd32-7fc1-4023-9c79-7d7479823694

feature(frontend): Flatten and paginate the execution list

---

frontend/src/pages/PipelineDetails.tsx

Before:
https://github.com/kubeflow/pipelines/assets/56132941/b14b80bf-69a0-4f5c-aac4-51fd55df89a5
After:
https://github.com/kubeflow/pipelines/assets/56132941/005f0de6-ac80-4641-a421-dec7fa5e50e8

fix(frontend): Momentary "No graph to show" when pipeline/graph is loading.

---

frontend/src/components/CustomTable.tsx
frontend/src/pages/ResourceSelector.tsx
frontend/src/pages/__snapshots__/ResourceSelector.test.tsx.snap

Before:
https://github.com/kubeflow/pipelines/assets/56132941/b5d7aea9-305f-4571-9247-d480c1d6dacf
After:
https://github.com/kubeflow/pipelines/assets/56132941/7128e7f9-9eb7-4524-b45a-ceee1eeae5e1

fix(frontend): Filter of pipeline selector in create new run page is broken.

---

frontend/src/pages/ArtifactList.test.tsx
frontend/src/pages/ArtifactList.tsx

#8986 
Before
https://github.com/kubeflow/pipelines/assets/56132941/7af11850-cd29-45ee-bc34-06df7194463e
After
https://github.com/kubeflow/pipelines/assets/56132941/cad2de7b-274e-484a-ab10-a4f33c6a96d0

feature(frontend): Flatten and paginate the artifact list

---

frontend/src/components/tabs/StaticNodeDetailsV2.test.tsx
frontend/src/components/tabs/StaticNodeDetailsV2.tsx
frontend/src/generated/pipeline_spec/index.ts
frontend/src/lib/v2/WorkflowUtils.test.ts
frontend/src/lib/v2/WorkflowUtils.ts

Make the information in the container more readable to the users and much closer to what it looks like in IR.
IR:
Before:
After:

fix(frontend) Format container information in pipeline details side panel

---

frontend/src/pages/PipelineDetails.tsx

Before:
Button
https://github.com/kubeflow/pipelines/assets/56132941/538d3b57-061b-4a9f-819e-89f268df9a9d
Card
https://github.com/kubeflow/pipelines/assets/56132941/d9e02f9f-a759-4b3e-b19f-a90df2cfe167
After
Button
https://github.com/kubeflow/pipelines/assets/56132941/61cf90af-b5f4-42f5-b1a3-3c2873a7e2aa
Card
https://github.com/kubeflow/pipelines/assets/56132941/f20f330d-ff16-4b1b-8b95-6e212717f02e

fix(frontend): Show summary button and summary card in pipeline details is disappeared.

---

frontend/package.json

Make [js-green-licenses](https://github.com/google/js-green-licenses) happy.
**Checklist:**

chore: add license field to frontend/package.json

---

sdk/RELEASE.md
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/types/type_utils.py
sdk/python/test_data/components/component_with_task_final_status.py
sdk/python/test_data/components/component_with_task_final_status.yaml
sdk/python/test_data/test_data_config.yaml

Supports the following:
```python
from kfp import compiler
from kfp import components
@dsl.component
def exit_comp(status: dsl.PipelineTaskFinalStatus):
print(status)
package_path = __file__.replace('.py', '.yaml')
compiler.Compiler().compile(pipeline_func=exit_comp, package_path=package_path)
loaded_exit_comp = components.load_component_from_file(package_path)
```
**Checklist:**

feat(sdk): support compiling components with `dsl.PipelineTaskFinalStatus` type

---

samples/contrib/aws-samples/mnist-kmeans-sagemaker/README.md
samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py

`samples/contrib/aws-samples/mnist-kmeans-sagemaker/README.md` - Updated README to use v2 Sagemaker Hosting components
`samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py` - Updated pipeline to use v2 Sagemaker Hosting components
**Checklist:**

chore(components): Update Sagemaker sample to use v2 Hosting components

---

components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_monitoring_job_definition_component.py
components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_monitoring_schedule_component.py
components/aws/sagemaker/tests/integration_tests/utils/kfp_client_utils.py

- Add check for component output.
- Remove check for Sagemaker resource, instead, check for ACK CR.
**Checklist:**

test(component): Update integration test for Model Monitor component

---

third_party/license.txt

For binaries used in cache-deployer: https://github.com/kubeflow/pipelines/blob/8f96aae13809f0e4870696efa00450210edcbcd2/backend/src/cache/deployer/Dockerfile#L5-L8
**Checklist:**

chore: Add more licenses for cache-deployer image

---

docs/conf.py

docs(sdk): normalize docs dropdown format for rc

---

docs/conf.py

docs(sdk): fix branch tag in dropdown

---

sdk/RELEASE.md
sdk/python/requirements.in
sdk/python/setup.py

chore(sdk): loosen pyyaml version requirement

---

.golangci.yaml
.pre-commit-config.yaml
backend/README.md

- Added a popular golang linter `golangci-lint`, which is widely used across multiple popular projects
- Added a few sentences on code styling and formatting as well as best practices for developers
**Checklist:**

chore(backend): Add golangci-lint and pre-commit config

---

components/kserve/README.md
components/kserve/component.yaml
components/kserve/requirements.txt
components/kserve/src/kservedeployer.py

- Update KServe component to 0.10.1 to support Kubeflow 1.7 integration
- Update KServe samples to the new kfserving-examples gcs bucket.
- Lint the existing KServe component code.
**Checklist:**

chore(components): Update KServe component to 0.10.1 for kubeflow 1.7 support

---

components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_hosting.py
components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py

- `components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_hosting.py` -  check in components rather than controller
- `components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py` - Same as previous
**Checklist:**

test(components): Check the Sagemaker component output rather than Controller

---

components/aws/sagemaker/README.md

Revised page to align with AWS documentation's structure and content. 
See https://docs.aws.amazon.com/sagemaker/latest/dg/kubernetes-sagemaker-components-for-kubeflow-pipelines.html

docs(components): Update Sagemaker Component Readme

---

frontend/src/pages/NewExperiment.test.tsx
frontend/src/pages/NewExperiment.tsx

#9441 
Before:
https://github.com/kubeflow/pipelines/assets/56132941/d92c2b95-d767-4bcb-b05b-a673d0d66053
After:
https://github.com/kubeflow/pipelines/assets/56132941/83d98add-3eba-40cb-a9e6-1d3e6b548b5f

fix(frontend): Parameter is missing in run creation page. Closes #9441

---

sdk/hack/github_release.sh

chore: prefix sdk release tags with `sdk-`

---

test/deploy-pipeline-lite.sh
test/upgrade-tests.sh

chore: exclude `sdk-` tags when preparing base deployment for upgrade test

---

frontend/Dockerfile

chore: temporarily disable frontend license tool

---

frontend/src/pages/PipelineDetails.tsx
frontend/src/pages/PipelineDetailsV2.test.tsx

The selected version in summary card in incorrect after choosing another version.
Before:
https://github.com/kubeflow/pipelines/assets/56132941/bcb66426-49bf-4c6a-82a9-51c3aa27a7f4
After:
https://github.com/kubeflow/pipelines/assets/56132941/215fd447-f42c-4da4-bdc8-6c460e734733

fix(frontend): Incorrect selected version in summary card

---

backend/src/apiserver/model/task.go

fix(backend): fix column size of `StateHistory` in `task` table. Fixes: #9553

---

frontend/src/pages/PipelineDetails.test.tsx
frontend/src/pages/PipelineDetails.tsx

Before:
https://github.com/kubeflow/pipelines/assets/56132941/20f9fc46-2327-4cdd-971e-d16666c08ba0
After:
https://github.com/kubeflow/pipelines/assets/56132941/2323fffc-fa7d-48ce-bdf4-c1bb415e8d12

fix(frontend): Missing pipeline info for "Clone recurring run" after viewing pipeline

---

components/aws/sagemaker/tests/integration_tests/resources/config/rlestimator-training/config.yaml
components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests

- Increase timeout for git fetching to prevent 
- `error: git cmd = '/usr/bin/git fetch —depth=1 origin 2.0.0-alpha.7': exit status 128`
- Increase timeout for rlestimator-training to prevent 
- `run-id: xxx did not stop within specified timeout`
**Checklist:**

chore(test): Increase time out for git fetching and test run

---

frontend/src/pages/NewRun.tsx

Example pipeline with parameter:
https://github.com/kubeflow/pipelines/assets/56132941/6bee427d-994d-4740-bbe6-7ecfbaee37b5
Before:
https://github.com/kubeflow/pipelines/assets/56132941/90219076-8b04-4a3a-a0c2-d8b5ada3f1ea
After:
https://github.com/kubeflow/pipelines/assets/56132941/1c0c7675-4de2-476f-9aab-892a017dc622

fix(frontend): Parameter is missing after upload pipeline in pipeline selector

---

frontend/src/pages/NewRunSwitcher.tsx
frontend/src/pages/NewRunV2.test.tsx
frontend/src/pages/NewRunV2.tsx

Before:
https://github.com/kubeflow/pipelines/assets/56132941/f5e15a6d-dbb0-4ef1-a75c-8ad8ab1454b9
After:
https://github.com/kubeflow/pipelines/assets/56132941/e34c894a-014b-424d-b973-11dc9e7e9ec8

chore(frontend): Direct to v2 new run page by default

---

.readthedocs.yml
components/google-cloud/docs/.readthedocs.yml
components/google-cloud/docs/requirements.txt
components/google-cloud/docs/source/conf.py

improve gcpc v1 404 page

---

test/api-integration-test/Dockerfile
test/initialization-test/Dockerfile

test: pin an older golang image in building presubmit test images. Fixes #9650

---

sdk/RELEASE.md

This is a 2.0.0 change, not a later change. This is already captured by "Various changes to dependency versions relative to v1".
**Checklist:**

chore(sdk): remove click release note

---

sdk/hack/github_release.sh

fix(sdk): fix GitHub release script

---

sdk/python/README.md

fix(sdk): fix kfp sdk v2 readme

---

components/kserve/OWNERS
components/kserve/README.md

Update the list of active owners for the KServe component. @Tomcli and @yhwang are the current owners of the KServe component image. 
**Checklist:**

chore(components): Update KServe component with active owners

---

components/google-cloud/google_cloud_pipeline_components/v1/model/upload_model/component.yaml

Fixes #9607
Fixes #8881
**Checklist:**

fix(components): fix parent_model ignored in ModelUploadOp

---

sdk/python/kfp/compiler/pipeline_spec_builder.py

Remediate a single mypy finding in `sdk/python/kfp/compiler/pipeline_spec_builder.py`.
**Checklist:**

chore(sdk): resolve mypy finding

---

backend/src/apiserver/storage/db.go
backend/src/apiserver/storage/db_test.go
backend/src/apiserver/storage/experiment_store.go

Replace LEFT with INNER JOIN when Archive Experiment
Follow-up PR on https://github.com/kubeflow/pipelines/pull/9680
See [comment](https://github.com/kubeflow/pipelines/pull/9680#issuecomment-1633771148) 
**Checklist:**

fix(backend) Replace LEFT with INNER JOIN when Archive Experiment

---

sdk/python/kfp/components/__init__.py
test/gcpc-tests/run_all_gcpc_modules.py
test/presubmit-test-run-all-gcpc-modules.sh

\assign @chensun
**Checklist:**
our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

fix(sdk): fix GCPC break in KFP SDK

---

backend/src/apiserver/client_manager.go

Added indexes on the namespace column in run_details table
**Checklist:**

fix(backend): fix timeouts with list run api. Fixes #9780 

---

test/presubmit-test-sdk-upgrade.sh

test(sdk): add KFP SDK upgrade presubmit test

---

frontend/server/app.ts
frontend/server/configs.ts
frontend/server/handlers/artifacts.ts
frontend/server/handlers/domain-checker.ts
frontend/server/integration-tests/artifact-get.test.ts

1. Remove user query parameter string from server response.
2. Introduce ALLOWED_ARTIFACT_DOMAIN_REGEX to allow configuration of allowed domains querying.
3. By default, ALLOWED_ARTIFACT_DOMAIN_REGEX is match all. Default configuration is meant to be demo purpose and not for production.
4. Users can provide ALLOWED_ARTIFACT_DOMAIN_REGEX environment variable to restrict object storage endpoint querying domains.
**Checklist:**

fix(frontend): Introduce ALLOWED_ARTIFACT_DOMAIN_REGEX flag to prevent accessing undesired domains. Remove user input string from server response.

---

backend/src/apiserver/config/config.json

Manifest will provide DBCONFIG_CONMAXLIFETIME environment variable. Moving the config value back to stick with the original config setting.
**Checklist:**

fix(backend): Move ConMaxLifeTime back to DbConfig.ConMaxLifeTime.

---

samples/core/exit_handler/exit_handler.py
test/e2e_test_gke_v2.yaml
test/sample-test/Dockerfile
test/sample-test/run_sample_test.py
test/sample-test/sample_test_launcher.py

Fixes https://github.com/kubeflow/pipelines/issues/9883
**Checklist:**

test: upgrade e2e sample tests to using sdk v2

---

backend/src/agent/persistence/client/token_refresher.go
backend/src/agent/persistence/main.go

Issue: https://github.com/kubeflow/pipelines/issues/9891
**Checklist:**

Fix Persistence Agent SA Token time interval

---

frontend/package-lock.json

chore(frontend): Update caniuse-lite in package-lock.json

---

.github/stale.yml
.github/workflows/stale.yml

fix: Move stale GHA operation config to the right place

---

sdk/python/install_from_source.sh

chore(sdk): remove old file

---

sdk/python/test_data/test_data_config.yaml
test/sdk-execution-tests/sdk_execution_tests.py

test: fix sdk execution test

---

sdk/python/kfp/dsl/executor.py

chore(sdk): refactor python component executor

---

sdk/python/kfp/cli/utils/aliased_plurals_group.py
sdk/python/kfp/cli/utils/deprecated_alias_group.py
sdk/python/kfp/client/auth.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/read_write_test.py
sdk/python/kfp/dsl/component_factory.py
sdk/python/kfp/dsl/structures.py
sdk/python/kfp/dsl/types/custom_artifact_types.py
sdk/python/kfp/dsl/types/type_annotations.py
sdk/python/kfp/dsl/types/type_annotations_test.py
sdk/python/kfp/dsl/types/type_utils.py
sdk/python/test_data/pipelines/pipeline_with_google_artifact_type.py

Some opportunities for improvement I noticed while working on the component I/O changes. Some of these changes will improve the readability of the diff on that PR.
**Checklist:**

chore(sdk): test observability, refactorings, and cleanup

---

go.sum

chore: fix go mod file

---

.readthedocs.yml

docs(sdk): use build.os

---

components/kserve/README.md
components/kserve/component.yaml
components/kserve/requirements.txt

Update the KServe component to use the latest SDK for the Kubeflow 1.8 release.
**Checklist:**

chore(component): Update KServe component to support Kubeflow 1.8

---

backend/OWNERS
kubernetes_platform/OWNERS
test/OWNERS

Remove Linchin from approvers and reviewers
**Checklist:**

chore: Update OWNERS

---

sdk/python/kfp/compiler/compiler_test.py

Some initial deduplication in `compiler_test.py`. There's lots more than can be done in this file and this is a start.
**Checklist:**

chore(sdk): clean up compiler_test.py

---

backend/Dockerfile.driver
backend/Dockerfile.launcher
backend/src/v2/compiler/argocompiler/argo.go

- Release new launcher image to include changes from: https://github.com/kubeflow/pipelines/pull/9946
- Update both driver and launcher base image to fix the following CVEs: 
- CVE-2023-29405 
- CVE-2023-29402 
- CVE-2023-29404 
- CVE-2023-39533 
- CVE-2023-29403 
- CVE-2023-39318 
- CVE-2023-39319 
- CVE-2023-29409 
- CVE-2023-29406 
**Checklist:**

feat(backend): Update driver and launcher images

---

sdk/python/kfp/client/auth.py
sdk/python/kfp/client/auth_test.py
sdk/python/kfp/client/client.py
sdk/python/kfp/client/client_test.py

- Added a check for IPython
- Moved the `_is_ipython` method from `Client` class to `auth.py` as a function
- Moved associated tests and added tests for `get_auth_code`
**Checklist:**

fix(sdk): Fix OOB for IPython and refactor. Closes #10075.

---

sdk/python/kfp/client/auth.py

- Improve the message printed to users when SSH or IPython (e.g. Notebook) is detected during authentication.
**Checklist:**

chore(sdk): Improve a message printed for users. Closes #10100

---

docs/build_docs_locally.sh

docs(sdk): add KFP SDK reference docs local build script

---

pytest.ini

Add `pytest.ini` file with helpful test path defaults for running `pytest`.
**Checklist:**

chore(sdk): add pytest.ini file

---

backend/src/v2/driver/driver.go

feat(backend): Support consuming parent DAG input artifact

---

.readthedocs.yml

Follow-on to https://github.com/kubeflow/pipelines/pull/10170.
**Checklist:**
more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

docs(sdk): fix readthedocs build error, additional changes

---

sdk/CONTRIBUTING.md

Required after #10160, since specifying a test path will override the `pytest.ini` configuration.
**Checklist:**

chore(sdk): update CONTRIBUTING.md testing instructions

---

manifests/kustomize/third-party/application/application-controller-deployment.yaml

Tested manually.
**Checklist:**

chore(manifest): Update application-crd-controller image to fix CVEs

---

sdk/python/kfp/client/auth.py

Changes the location of the `import requests_toolbelt.adapters.appengine` statement for those who run KFP in an environment where `urllib3<2.0.0` ([required](https://github.com/kubeflow/pipelines/blob/9f278f3682662b24b46be2d9ef4a783bcc1f9b0c/sdk/python/requirements.in#L25C14-L25C14) by the KFP SDK) is not available, providing additional safety from https://github.com/kubeflow/pipelines/issues/9326#issuecomment-1535491761.
This change means only those invoking the KFP SDK client from within App Engine are strictly required to have `urllib3<2.0.0`.
**Checklist:**

chore(sdk): nest requests_toolbelt import

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py
sdk/python/test_data/pipelines/cross_loop_after_topology.py
sdk/python/test_data/pipelines/cross_loop_after_topology.yaml
sdk/python/test_data/test_data_config.yaml

Enables syntax like:
```python
@dsl.pipeline()
with dsl.ParallelFor([1, 2, 3]):
one = print_op(message='foo')
two = print_op(message='bar').after(one)
```
Also standardizes, condenses, and cleans up the topology validation tests in `compiler_test.py`.
**Checklist:**

feat(sdk): support `.after()` referencing task in `ParallelFor` group

---

api/v2alpha1/python/setup.py
kubernetes_platform/python/setup.py
kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.yaml
kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc.yaml
kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc_from_task_output.yaml
kubernetes_platform/python/test/snapshot/data/node_selector.yaml
kubernetes_platform/python/test/snapshot/data/secret_as_env.yaml
kubernetes_platform/python/test/snapshot/data/secret_as_vol.yaml
kubernetes_platform/python/test/snapshot/read_write_test.py
sdk/RELEASE.md
sdk/python/kfp/dsl/types/type_utils_test.py
sdk/python/setup.py

Support Python 3.12 in the KFP SDK.
**Checklist:**

chore(sdk): support Python 3.12

---

backend/OWNERS

Propose @Tomcli  to be the backend reviewer.
**Checklist:**

chore(backend): Propose Tomcli to be the backend reviewer

---

sdk/python/kfp/local/config.py
sdk/python/kfp/local/config_test.py

#localexecution
**Checklist:**

chore(sdk): remove cleanup param in local init

---

sdk/python/kfp/local/placeholder_utils_test.py

Adds test file which was omitted from #10298.
**Checklist:**

test(sdk): add placeholder_utils_test.py

---

test/kfp-kubernetes-execution-tests/requirements.txt
test/kfp-kubernetes-execution-tests/sdk_execution_tests.py
test/presubmit-kfp-kubernetes-execution-tests.sh

test(sdk): add `kfp-kubernetes` execution tests

---

sdk/python/kfp/local/task_dispatcher_test.py

chore(sdk): fix use of invalid escape sequence in tests

---

sdk/python/kfp/local/__init__.py
sdk/python/kfp/local/config.py
sdk/python/kfp/local/config_test.py
sdk/python/kfp/local/docker_task_handler.py
sdk/python/kfp/local/docker_task_handler_test.py
sdk/python/kfp/local/e2e_test.py
sdk/python/kfp/local/subprocess_task_handler_test.py
sdk/python/kfp/local/task_dispatcher.py
sdk/python/kfp/local/task_dispatcher_test.py
sdk/python/kfp/local/testing_utilities.py

Adds the `DockerRunner` to the `kfp.local` subpackage. Preferring the name `DockerRunner` to `ContainerRunner`, since this can be used to run more than just Container Components and Containerized Python Components.
**Checklist:**

feat(sdk): add DockerRunner #localexecution

---

sdk/python/kfp/local/logging_utils.py
sdk/python/kfp/local/logging_utils_test.py
sdk/python/kfp/local/task_dispatcher_test.py

Improves the presentation of strings in the local execution logging. All will be wrapped in single quotes.
**Checklist:**

fix(sdk): fix presentation of strings in local execution #localexecution

---

sdk/python/kfp/local/docker_task_handler.py

fix(sdk): remove redundant newline character in local `DockerRunner` logs

---

api/v2alpha1/python/setup.py

chore(sdk): depend on protobuf 4 in `kfp-pipeline-spec`

---

kubernetes_platform/python/docs/.readthedocs.yml

Fixes this issue: https://blog.readthedocs.com/use-build-os-config/
**Checklist:**

docs(sdk): fix `kfp-kubernetes` docs build error

---

samples/test/metrics_visualization_v2.py

Fixes: #10208 
Fix visualization metrics v2 sample
**Checklist:**

chore: Fix metrics visualization v2 sample

---

docs/source/kfp.rst
docs/source/local.rst
sdk/python/kfp/local/__init__.py

docs(sdk): add kfp.local to reference docs

---

.gitignore
sdk/python/kfp/dsl/pipeline_task.py
sdk/python/kfp/local/config.py
sdk/python/kfp/local/config_test.py
sdk/python/kfp/local/executor_input_utils.py
sdk/python/kfp/local/logging_utils.py
sdk/python/kfp/local/logging_utils_test.py
sdk/python/kfp/local/placeholder_utils_test.py
sdk/python/kfp/local/task_dispatcher.py
sdk/python/kfp/local/task_dispatcher_test.py
sdk/python/kfp/local/utils.py
sdk/python/kfp/local/utils_test.py

Performs some refactoring and cleanup of the local task execution code. This is a pure refactoring.
Partitioning out these changes will make the changes for local pipeline execution much easier to review.
**Checklist:**

chore(sdk): local task execution refactor + cleanup

---

backend/OWNERS

In recognition of @Tomcli's role as a seasoned KFP contributor with a proven track record of expertise and reliability.
**Checklist:**

chore: Add Tomcli as a backend approver

---

CONTRIBUTING.md

This PR depends on https://github.com/kubeflow/website/pull/3682.
This PR updates the legal info due to migration from CLA to DCO.
The new link points to the content added by [the PR that this PR depends on](https://github.com/kubeflow/website/pull/3682).
**Checklist:**

fix(docs): Updated legal info due to migration from CLA to DCO

---

backend/src/v2/compiler/argocompiler/container.go

chore(backend): Update kfp driver and launcher images

---

test/release/Dockerfile.release
test/release/Makefile
test/release/bump-version-docker.sh
test/release/release.sh

Part of #10579
Update release image following #10580
**Checklist:**

chore: Update release image

---

.github/ISSUE_TEMPLATE/config.yml

Fixes #4688
Add a template for users to ask questions
**Checklist:**

chore: Add Question issue template

---

backend/OWNERS

Promote @rimolive to be the KFP backend owner because he's leading the Red Hat KFP development team.
**Checklist:**

chore(backend): Promote @rimolive as the backend reviewer

---

kubernetes_platform/python/RELEASE.md

Enables OSS `kfp-kubernetes` contributors to perform step 1 to initiate the release process.
**Checklist:**

chore(sdk): make `kfp-kubernetes` release instructions public

---

backend/src/v2/compiler/argocompiler/container.go

chore(backend): update kfp launcher and driver images

---

backend/OWNERS

chore: Promote @rimolive as a backend approver

---

backend/src/v2/test/README.md
manifests/kustomize/README.md
manifests/kustomize/env/aws/README.md
manifests/kustomize/sample/README.md
manifests/kustomize/sample/kustomization.yaml

chore: Change command to apply manifests in the docs

---

.readthedocs.yml

Fix readthedoc build error:
```
ERROR: Package 'kfp' requires a different Python: 3.7.17 not in '<3.13.0,>=3.8.0'
```
**Checklist:**

chore: Upgrade Python version to 3.8 in readthedocs config

---

.github/OWNERS
scripts/OWNERS
test/OWNERS

This PR adds @rimolive, @hbelmiro and @DharmitD as approvers and reviewers for GitHub Actions.
They have been working on [migrating tests from Prow to GitHub Actions](https://github.com/kubeflow/pipelines/issues/10744).
PRs:
- https://github.com/kubeflow/pipelines/pull/10887
- https://github.com/kubeflow/pipelines/pull/10924
- https://github.com/kubeflow/pipelines/pull/10926
- https://github.com/kubeflow/pipelines/pull/10932
- https://github.com/kubeflow/pipelines/pull/10946
- https://github.com/kubeflow/pipelines/pull/10961
- https://github.com/kubeflow/pipelines/pull/10923
- https://github.com/kubeflow/pipelines/pull/10871
- https://github.com/kubeflow/pipelines/pull/10842
- https://github.com/kubeflow/pipelines/pull/10930
- https://github.com/kubeflow/pipelines/pull/10702 …

chore: Added @rimolive, @hbelmiro and @DharmitD as approvers and reviewers for GitHub Actions

---

.github/actions/kfp-cluster/action.yml
.github/actions/kfp-tekton-cluster/action.yml
.github/workflows/backend.yml
.github/workflows/e2e-test.yaml
scripts/deploy/github/deploy-kfp-tekton.sh

This PR adds a new GitHub action to be reused by test workflows. This is intended to avoid code duplication across multiple workflows.
**Checklist:**

test: Created a new GitHub action to reuse the creation of a KFP cluster

---

.github/workflows/frontend.yml

Resolves https://github.com/kubeflow/pipelines/issues/10879
Converts the Prow frontend test to a GH Action Workflow.
Here's a working GH Action run on my fork: https://github.com/DharmitD/data-science-pipelines-argo/actions/runs/9525123655/job/26258863870
PR to remove the frontend test from prow config: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2302
PR to remove frontend files not required anymore: https://github.com/kubeflow/pipelines/pull/10973
**Checklist:**

test: Migrate Frontend tests to a GHA Workflow 

---

kubernetes_platform/README.md

Add a note about protoc being required, and a note about which versions are known to work.
**Checklist:**

fix(docs): add note about protoc dependency and version

---

sdk/OWNERS

chore: Adding @gregsheremeta to SDK reviewers.

---

backend/OWNERS
frontend/OWNERS

also cleanup inactive owners
**Checklist:**

chore: Adding @HumairAK to backend and frontend reviewers

---

kubernetes_platform/OWNERS

follows up on #11042
a lot of SDK work takes place in kubernetes_platform as well :)
**Checklist:**

chore: Adding @gregsheremeta to SDK reviewers (kubernetes_platform)

---

kubernetes_platform/OWNERS

@chensun I'm opening I new PR because `kfp-kubernetes-execution-tests` is preventing https://github.com/kubeflow/pipelines/pull/11036 from being merged.

chore: adding @hbelmiro to kubernetes_platform/OWNERS

---

kubernetes_platform/OWNERS
sdk/OWNERS

Relevant PRs proposed by me:
https://github.com/kubeflow/pipelines/pull/11039
https://github.com/kubeflow/pipelines/pull/11121
Relevant PRs reviewed by me:
https://github.com/kubeflow/pipelines/pull/11005
https://github.com/kubeflow/pipelines/pull/10913
https://github.com/kubeflow/pipelines/pull/11071
https://github.com/kubeflow/pipelines/pull/11112
Relevant issues created by me:
https://github.com/kubeflow/pipelines/issues/11092
**Checklist:**

chore: Adding @DharmitD to SDK reviewers

---

README.md

Fixes #10983 and other broken links in the repository readme.
I have updated some broken links in the readme. I also removed the section referring to the versioning policy and feature stages as those links do not exist in this repo - please let me know if I can link to them somewhere else.
**Checklist:**

docs:fixing broken links in readme

---

backend/src/v2/compiler/argocompiler/container.go

Part of https://github.com/kubeflow/pipelines/issues/11148
**Checklist:**

chore(backend): update driver and launcher default images

---

OWNERS

chore: add PaulinaPacyna and ouadakarim as reviewers

---

frontend/src/components/NewRunParametersV2.tsx

Add support for empty string in pipeline parameters.
**Checklist:**

fix(ui): fixes empty string value in pipeline parameters

---

RELEASE.md

chore: Update RELEASE.md to remove obsolete instructions

---

api/v2alpha1/python/setup.py

Part of https://github.com/kubeflow/pipelines/issues/11148
**Checklist:**

chore: Release kfp-pipeline-spec 0.4.0

---

kubernetes_platform/python/docs/conf.py
kubernetes_platform/python/kfp/kubernetes/__init__.py

Part of https://github.com/kubeflow/pipelines/issues/11148
**Checklist:**

chore: release kfp-kubernetes 1.3.0

---

kubernetes_platform/python/RELEASE.md
kubernetes_platform/python/create_release_branch.sh
kubernetes_platform/python/release.sh

chore: update kfp-kubernetes release scripts and instructions

---

OWNERS

Remove PaulinaPacyna (me) from the reviewers
**Checklist:**

chore: Remove PaulinaPacyna from reviewers

---

OWNERS

chore: adding HumairAK to root OWNERS

---

backend/OWNERS

- https://github.com/kubeflow/pipelines/pull/10704
- https://github.com/kubeflow/pipelines/pull/10766
- https://github.com/kubeflow/pipelines/pull/10790
- https://github.com/kubeflow/pipelines/pull/10801
- https://github.com/kubeflow/pipelines/pull/10833
- https://github.com/kubeflow/pipelines/pull/10857
- https://github.com/kubeflow/pipelines/pull/10913
- https://github.com/kubeflow/pipelines/pull/11147
- https://github.com/kubeflow/pipelines/pull/11169
- https://github.com/kubeflow/pipelines/pull/11243
cc @HumairAK @chensun 
**Checklist:**

chore: adding @hbelmiro to backend reviewers

---

backend/src/v2/objectstore/config.go

Addresses #11280, adds back the default value of `true` for `ForcePathStyle`.
**Checklist:**

fix(backend): set default value to true for ForcePathStyle

---

.github/workflows/add-ci-passed-label.yml
.github/workflows/ci-checks.yml

-  Verified the issue mentioned in [#11307](https://github.com/kubeflow/pipelines/issues/11307) is not related to ci-check and add-ci-passed-label workflows. 
- This PR enables the ci-check and add-ci-passed-label workflows
**Checklist:**

test: Enabled ci-check and add-ci-passed-label workflows

---

.github/ISSUE_TEMPLATE/CHORE.md

Resolves https://github.com/kubeflow/pipelines/issues/11263
Adding a chore template
**Checklist:**
- [ X] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [X ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

adding chore as a new template. Fixes #11263

---

components/google-cloud/RELEASE.md
sdk/RELEASE.md

#11326 was a SDK change, but added release note to google-cloud component
**Checklist:**

chore: fix release note

---

.github/workflows/kfp-sdk-tests.yml
kubernetes_platform/python/setup.py
sdk/RELEASE.md
sdk/python/setup.py

Fixes: https://github.com/kubeflow/pipelines/issues/11365
**Checklist:**

chore(sdk): support Python 3.13

---

.github/workflows/periodic.yml

This PR fixes a conflict in artifact names in Periodic Functional Tests.
https://github.com/kubeflow/pipelines/actions/runs/12539974877/job/34966725514
**Checklist:**

chore(tests): fixed conflicting artifacts names

---

backend/OWNERS

I would like to nominate @mprahl & @gmfrasca  as a reviewer for backend. They both have shown in depth knowledge of the backend subcomponent, their reviews have been instrumental in assuring that only good quality PRs are merged.

nominate reviewers for backend

---

.github/workflows/image-builds.yml

Some dockerfiles were not accounted for in the build job. These are also expected to be patched as part of release: https://github.com/kubeflow/pipelines/blob/master/manifests/kustomize/hack/release.sh#L30-L35

add remaining dockerfiles to build workflow

---

backend/src/v2/compiler/argocompiler/container.go
manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
manifests/kustomize/base/cache-deployer/kustomization.yaml
manifests/kustomize/base/cache/cache-deployment.yaml
manifests/kustomize/base/cache/kustomization.yaml
manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/test_sync.py
manifests/kustomize/base/metadata/base/kustomization.yaml
manifests/kustomize/base/metadata/base/metadata-envoy-deployment.yaml
manifests/kustomize/base/pipeline/kustomization.yaml
manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
manifests/kustomize/env/gcp/inverse-proxy/proxy-deployment.yaml

Cherry Pick 4517cbe87271d1fe56f6786a6c17bddd2f3868eb to 2.4.0 release branch.

chore: switch to using gh container registry in manifests (#11526)

---

.github/workflows/ci-checks.yml

Upgraded the latest version of upload-artifact
**Checklist:**

test: fix CI failure by upgrading upload-artifact version

---

OWNERS

Remove ouadakarim from reviewers due to change in assignments.
**Checklist:**

chore: Remove ouadakarim from Kubeflow Pipelines reviewers

---

frontend/src/components/NewRunParametersV2.tsx

Fixes #11515.
fixed the issue.
current behavior after the fix with the same pipeline.

fix(frontend): fixes Default pipeline input params are missing from the GUI. Fixes #11515

---

frontend/src/pages/GettingStarted.test.tsx

Resolves #11568
**Checklist:**

chore(frontend) : Fix frontend failing ci test

---

backend/metadata_writer/src/metadata_helpers.py

- Moved an import statement from the middle of the code to top.
- Removed unused import statement.
**Checklist:**

chore(backend): fixed imports on metadata_helpers.py

---

manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml

This helps some users with upgrades see https://github.com/kubeflow/manifests/pull/3019
**Checklist:**

chore: improved securitycontext for mysql

---

.github/workflows/ci-checks.yml
backend/src/v2/compiler/argocompiler/container.go

Update launcher/driver to 2.4.1
**Checklist:**

update driver/launcher images for 2.4.1

---

backend/src/v2/compiler/argocompiler/container.go

Artifact of: https://github.com/kubeflow/pipelines/pull/11673
**Checklist:**

remove unused function

---

.github/resources/scripts/collect-logs.sh
.github/workflows/kfp-samples.yml

- Added `kubectl get pods` to the log collection to identify the failing pods more easily.
- Fixed steps that were not continuing to the log collection step
**Checklist:**

test: Fixed and improved log collection

---

backend/Dockerfile.cacheserver
backend/Dockerfile.viewercontroller

Add missing go.mod files from api and k8s_platform so cacheserver and viewercontroller
Test by performing `make images_all` in the `backend/` directory to verify all images successfully build.
See https://github.com/kubeflow/pipelines/pull/11629 for additional details
**Checklist:**

fix(backend): Include missing go.mod for cacheserver/viewercontroller images

---

.github/workflows/e2e-test.yml

This PR fixes the path to `collect-logs.sh` in `.github/workflows/e2e-test.yml`.
**Checklist:**

test: Fixed `collect-logs.sh` path

---

backend/src/v2/driver/driver_test.go

Some quick follow ups from https://github.com/kubeflow/pipelines/pull/11770
**Checklist:**

chore(backend): refactor driver tests

---

.github/resources/scripts/kfp-readiness/wait_for_pods.py

Added the result of `kubectl get pods` to logs when waiting for pods to get ready.
We can see it in action here: https://github.com/kubeflow/pipelines/actions/runs/14172762175/job/39700184455#step:4:2566.
**Checklist:**

test: Added the result of `kubectl get pods` to logs when waiting for pods to get ready

---

.github/resources/manifests/kubernetes-native/kustomization.yaml
.github/resources/manifests/kubernetes-native/overlays/apiserver-env.yaml
.github/resources/scripts/deploy-kfp.sh
.github/workflows/kfp-webhooks.yml
backend/src/apiserver/main.go
backend/src/apiserver/webhook/pipelineversion_webhook.go
backend/src/apiserver/webhook/pipelineversion_webhook_test.go
backend/test/integration/Makefile
backend/test/integration/README.md
backend/test/integration/webhook_test.go
manifests/kustomize/base/webhook/kustomization.yaml
manifests/kustomize/base/webhook/params.yaml
manifests/kustomize/base/webhook/pipelineversion-mutating-webhook-config.yaml
manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/kustomization.yaml
manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/patches/deployment.yaml
manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/patches/mutating-webhook.yaml
manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/kustomization.yaml
manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/patches/deployment.yaml
manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/patches/mutating-webhook.yaml
manifests/kustomize/env/dev-kind/kustomization.yaml
test/sdk-execution-tests/sdk_execution_tests.py

This mutating webhook adds labels to query pipeline versions by their pipeline ID and pipeline name, and adds an owner's reference to the pipeline it's a part of.
**Checklist:**

feat(backend): Add a mutating webhook for the PipelineVersion kind

---

.github/workflows/stale.yml

Stale action timers currently are over kill, too many relevant issues are constantly being closed and it's extremely annoying. It's also difficult to keep up with the spam.

increase stale action timers

---

api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
api/v2alpha1/pipeline_spec.proto
backend/src/agent/persistence/worker/metrics_reporter.go
backend/src/agent/persistence/worker/persistence_worker.go
backend/src/agent/persistence/worker/persistence_worker_test.go
backend/src/apiserver/server/api_converter_test.go
backend/src/apiserver/template/v2_template.go
backend/src/apiserver/visualization/server.py
backend/src/common/client/api_server/v1/run_client.go
backend/src/common/client/api_server/v1/visualization_client.go
backend/src/common/util/execution_spec.go
backend/src/common/util/parameter_formatter_test.go
backend/src/crd/controller/scheduledworkflow/controller.go
backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
backend/src/crd/samples/scheduledworkflow/parameterized.yaml

chore: Fix typos

---

.pre-commit-config.yaml
backend/src/v2/cmd/driver/main.go
backend/src/v2/cmd/launcher-v2/main.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/dag.go
backend/src/v2/compiler/argocompiler/importer.go
backend/src/v2/component/launcher_v2.go
backend/src/v2/component/launcher_v2_test.go
backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml

This reverts commit cd3e747b5de3d7e1e338e309cc57311dd4a91258.
Some execution tests in the master branch are failing. They did not execute against [this](https://github.com/kubeflow/pipelines/commit/cd3e747b5de3d7e1e338e309cc57311dd4a91258) PR. This PR reverts that commit. We will update CI, resubmit https://github.com/kubeflow/pipelines/commit/cd3e747b5de3d7e1e338e309cc57311dd4a91258, and resolve the tests.
**Checklist:**

Revert "feat(backend): implement logs as artifacts (#11762)"

---

.github/workflows/kfp-kubernetes-execution-tests.yml
.github/workflows/sdk-execution.yml
.pre-commit-config.yaml
backend/src/v2/cmd/driver/main.go
backend/src/v2/cmd/launcher-v2/main.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/dag.go
backend/src/v2/compiler/argocompiler/importer.go
backend/src/v2/component/launcher_v2.go
backend/src/v2/component/launcher_v2_test.go
backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
test/sdk-execution-tests/sdk_execution_tests.py

Resubmission of https://github.com/kubeflow/pipelines/pull/11762 with some CI changes as described [here](https://github.com/kubeflow/pipelines/pull/11807) and [here](https://cloud-native.slack.com/archives/C073N7BMLB1/p1744227282849299).
Haven't touched the GHAs in this repo much so wouldn't be surprised if there are some hiccups. Needless to say, totally open to input / feedback.
**Checklist:**

feat(backend): implement logs as artifacts + CI updates

---

.github/workflows/sdk-execution.yml
test/sdk-execution-tests/sdk_execution_tests.py

Removes a little bit of unused logic introduced by https://github.com/kubeflow/pipelines/pull/11809.
**Checklist:**

chore(tests): remove unused logic

---

backend/README.md

fix(docs): Use the latest driver and launcher images in the dev environment

---

sdk/python/requirements.in
sdk/python/requirements.txt

This PR widen the allowed versions of urllib3 to improve the compatibility with the broader ecosystem.
**Checklist:**

fix(deps): widen urllib3 upper bound to <3.0.0

---

backend/README.md

fix(docs): Remove Podman as backend README pre-req

---

.github/workflows/backend-visualization.yml
.github/workflows/e2e-test.yml
.github/workflows/frontend.yml
.github/workflows/gcpc-modules-tests.yml
.github/workflows/kfp-kubernetes-library-test.yml
.github/workflows/kfp-samples.yml
.github/workflows/kfp-sdk-runtime-tests.yml
.github/workflows/kfp-sdk-tests.yml
.github/workflows/kfp-webhooks.yml
.github/workflows/kubeflow-pipelines-manifests.yml
.github/workflows/presubmit-backend.yml
.github/workflows/sdk-component-yaml.yml
.github/workflows/sdk-docformatter.yml
.github/workflows/sdk-execution.yml
.github/workflows/sdk-isort.yml
.github/workflows/sdk-upgrade.yml
.github/workflows/sdk-yapf.yml
.github/workflows/upgrade-test.yml
.github/workflows/validate-generated-files.yml

Improved path filtering in the CI
**Checklist:**

chore(test): Improved path filtering in the CI

---

README.md

To achieve CNCF graduation, we need to work on the OpenSSF Best Practices. This PR will add a badge to monitor its status.
**Checklist:**

chore: Add the OpenSSF Best Practices badge

---

backend/src/v2/compiler/argocompiler/argo_test.go
backend/src/v2/compiler/argocompiler/testdata/hello_world_with_retry.yaml

Minor fix
In #11673, I forgot to enable the new specs and accidentally added a wrong test (from my experiments). This PR fixes that.
@HumairAK , since you're familiar with the context, could you please take a look?

fix component retry test

---

backend/Dockerfile
backend/Dockerfile.persistenceagent
backend/Dockerfile.scheduledworkflow
backend/Dockerfile.visualization

This PR optimizes the Dockerfiles for better use of the cache.
**Checklist:**

chore(backend): Optimized Dockerfiles

---

sdk/RELEASE.md

Some of the previous prs forgot to update the releas notes.

add missing release note updates to sdk main branch

---

backend/Dockerfile.visualization

This PR fixes an error in a Dockerfile
**Checklist:**

fix(backend): fixed Dockerfile

---

backend/Makefile
backend/README.md

Fixed support for Podman in Makefile.
**Checklist:**

chore(backend): fixed support for Podman in Makefile

---

.github/workflows/kfp-kubernetes-execution-tests.yml
.github/workflows/sdk-execution.yml
docs/versions.json
sdk/RELEASE.md
sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml

chore: (cherry-pick) Add SDK support for setting resource limits on older KFP versions

---

backend/test/integration/pipeline_api_test.go
backend/test/integration/pipeline_version_api_test.go
backend/test/integration/upgrade_test.go
backend/test/v2/integration/pipeline_api_test.go
backend/test/v2/integration/pipeline_version_api_test.go
backend/test/v2/integration/upgrade_test.go
backend/test/v2/resources/sequential-v2.py
backend/test/v2/resources/sequential-v2.yaml
backend/test/v2/resources/sequential.yaml

@HumairAK @chensun Integration tests are now failling because the external links used to test pipeline upload from URL and zip package are no longer available.
I added this temporary fix while we work on a definitive solution. We need this PR merged to unblock all the PRs.
**Checklist:**

chore: Fix integration tests

---

docs/versions.json
kubernetes_platform/python/docs/conf.py
kubernetes_platform/python/kfp/kubernetes/__init__.py
sdk/RELEASE.md
sdk/python/kfp/__init__.py

Reference PRs: 
https://github.com/kubeflow/pipelines/pull/11715/files
https://github.com/kubeflow/pipelines/pull/11380/files#diff-0885a83695c4f1e065a0bd01250d1a1dc5f5fc48a83b96aaa7579b4bc3a811d1
These will be timed to release with kfp 2.5 as there are some dependent changes. 
**Checklist:**

chore(sdk): kfp and kfp-kubernetes 2.13 & 1.5

---

ADOPTERS.md

chore: Adding Adopters file for CNCF graduation

---

frontend/src/pages/NewRunV2.test.tsx
frontend/src/pages/NewRunV2.tsx

Implements a checkbox UI component that enables automatic pipeline version selection for recurring runs, building upon @muzzlol's original work.
Key changes:
- ✨ Added "Use Latest Version" toggle functionality
- 🗑️ Removed localStorage dependency (per @mprahl's feedback)
- ♿ Improved version selector accessibility labels
- ✅ Added comprehensive test coverage
Closes #11581
```bash
Test Suites: 113 skipped, 1 passed, 1 of 114 total
Tests:       1613 skipped, 7 passed, 1620 total
Snapshots:   0 total
Time:        17.016 s
Ran all test suites with tests matching "Always Use Latest".
```
Based on current upstream codebase, while maintaining compatibility with @muzzlol's original  PR #11628 [commit c09bc4e](https://github.com/kubeflow/kubeflow/commit/c09bc4e)   approach to ensure backward …

feat(frontend): Add "Always Use Latest Version" option for recurring runs (fixes #11581)

---

OWNERS

Happy to endorse @droctothorpe as a maintainer & repo approver for KFP, he and his team's contributions have been an integral part of KFP in the past year. They have lead and implemented key areas of KFP from logging, to nested artifact tracking, addressing dsl collected, and much more. Excited to have him on board in helping lead KFP's roadmap as well as helping curate the community.
**Checklist:**

add maintainer to kfp

---

README.md

Medium blogs are moved to medium.com/data-science/*

chore: correct broken links in README.md 

---

tools/k8s-native/README.md
tools/k8s-native/migration.py

- This PR introduces a migration script that converts Pipeline and PipelineVersion objects from the database to the Kubernetes API.
- The script generates a YAML file containing the Kubernetes objects representing the pipelines and their versions in KFP, facilitating easy deployment.
**Checklist:**

feat(backend): Add migration script to create Pipeline and PipelineVersion objects from the database to Kubernetes API

---

ADOPTERS.md

Add the IBM Foundation Model Data Engineering Team. cc @roytman @yuanchi2807
**Checklist:**

chore: Add IBM Research Foundation Model Data Engineering team

---

.github/workflows/e2e-test.yml
.github/workflows/kfp-kubernetes-execution-tests.yml
.github/workflows/kfp-samples.yml
.github/workflows/sdk-execution.yml
.github/workflows/upgrade-test.yml

Some steps were not collecting logs in case of failures.
This PR fixes that.
**Checklist:**

chore(test): fixed log collection in tests

---

backend/src/v2/component/launcher_v2.go
backend/src/v2/component/launcher_v2_test.go

The getPlaceholders method [prepends](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/component/launcher_v2.go#L752) `placeholders["{{$}}"] = string(executorInputJSON) `to the placeholders map to put the full executorInputJSON as a template.
The [code](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/component/launcher_v2.go#L376) assumes that the {{$}} key will be processed first, since it inserts the entire JSON template into the argument string. Only after this replacement are individual placeholders (like {{$.inputs.parameters['some_param']}}) applied.
However, since Go maps [do not guarantee](https://go.dev/blog/maps#iteration-order) iteration order, the {{$}} key is often processed after other keys  As a result, some …

- fix(launcher): missing executorInput parameter values caused by {{$}} evaluation order

---

.github/actions/kfp-cluster/action.yml
.github/workflows/e2e-test.yml
.github/workflows/kfp-kubernetes-execution-tests.yml
.github/workflows/kfp-samples.yml
.github/workflows/kfp-webhooks.yml
.github/workflows/sdk-execution.yml
.github/workflows/upgrade-test.yml

chore(ci): clean up unnecessary parentheses and fix the formatting of the CI files

---

backend/README.md

Adds a GoLand-specific configuration for remotely debugging the driver.  This configuration includes an updated environment variable V2_DRIVER_COMMAND as well as the runtime arguments utilized when launching the api server  normally. 
**Checklist:**

docs: add GoLand-specific configs to backend Readme

---

manifests/kustomize/env/openshift/README.md

There may be a need to delete the `kubeflow` project from the cluster. I added the command here so people who may not be so familiar with OpenShift would know how.
**Checklist:**

docs(frontend): Added clean up section to openshift docs

---

manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml

This uses Kubernetes native liveness and readiness probes that is tool independent.
**Checklist:**

feat(frontend) Use native k8s probes for pipeline-ui

---

backend/src/v2/compiler/argocompiler/argo_test.go
backend/src/v2/compiler/argocompiler/dag.go
backend/src/v2/compiler/argocompiler/testdata/final_status_state.yaml
backend/src/v2/compiler/testdata/final_status_state.json
backend/src/v2/driver/driver_test.go
backend/src/v2/driver/resolve.go
samples/v2/pipeline_with_input_status_state.py
samples/v2/sample_test.py
sdk/RELEASE.md
sdk/python/kfp/dsl/executor.py

Add support for exit handlers to take input PipelineTaskFinalStatus.
fixes https://github.com/kubeflow/pipelines/issues/10917
**Checklist:**

feat(backend/sdk): support PipelineTaskFinalStatus input

---

manifests/kustomize/env/dev/api-server-patch.yaml
manifests/kustomize/env/dev/kustomization.yaml

Dev manifests should deploy latest development code.

user master for dev manifests

---

.github/workflows/e2e-test.yml
.github/workflows/gcpc-modules-tests.yml
.github/workflows/kfp-kubernetes-execution-tests.yml
.github/workflows/kfp-kubernetes-library-test.yml
.github/workflows/kfp-samples.yml
.github/workflows/kfp-sdk-tests.yml
.github/workflows/sdk-execution.yml
backend/src/v2/test/sample-test.sh
test/presubmit-tests-sdk.sh

Allow for proto changes to be tested against the CI by generate the `kfp-pipeline-spec` proto files and installing the package before pipeline compilation/submission. 
**Checklist:**

chore: update workflows to test proto changes in ci

---

backend/Dockerfile
backend/Dockerfile.driver
backend/Dockerfile.launcher
backend/Dockerfile.persistenceagent
backend/Dockerfile.scheduledworkflow

Fixed warnings in Dockerfiles.
**Checklist:**

chore(backend): Fixed warnings in Dockerfiles

---

CONTRIBUTING.md

chore(docs): change adrs to kep in contrib doc

---

docs/diagram/.gitignore
docs/diagram/Makefile
docs/diagram/kfp-db.mmd

Add the "Entity Relationship Diagram" of the database used by Kubeflow Pipelines for persisting its state. 
I have added a `makefile` to create the SVG from the `mermaid` diagram that's why the SVG is not included.
This is the rendered diagram:
**Checklist:**

feat(docs): erdiagram of kfp-db

---

manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml

Resolves https://github.com/kubeflow/pipelines/issues/11742. 
Kudos to @NJ3rsey for the fix.
**Checklist:**

fix(backend): increase max_metadata_size for ml-metadata grpc server

---

.github/workflows/sdk-isort.yml
.github/workflows/sdk-yapf.yml
samples/v2/sample_test.py
sdk/python/kfp/local/pipeline_orchestrator_test.py
sdk/python/kfp/local/task_dispatcher_test.py
sdk/python/test_data/pipelines/component_with_pip_index_urls.py

Also disable kfp-pipeline-spec source install,
but keep the utility code to install it again
for kfp sample tests.
**Checklist:**

chore(backend): resolve linting errors

---

docs/sdk/requirements.txt

This will resolve the current failing sphinx builds.

chore: update sphinx deps

---

.github/workflows/kfp-samples.yml
manifests/kustomize/third-party/seaweedfs/base/seaweedfs/seaweedfs-pvc.yaml
samples/v2/sample_test.py

- part of https://github.com/kubeflow/pipelines/pull/11965

Fix samples-test workflow

---

manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml

- Added SecurityContext at pod level in workflow-controller, adding it at pod level also applies SecurityContext for sidecar containers
- part of https://github.com/kubeflow/manifests/pull/3211#discussion_r2259897783
**Checklist:**

chore: Add security context at pod level for workflow-controller

---

proposals/README.md

Some topics that could use a separate reminder for folks to include or consider in their proposals
**Checklist:**

add more considerations for proposal readme

---

manifests/kustomize/third-party/seaweedfs/base/seaweedfs/seaweedfs-pvc.yaml

- part of https://github.com/kubeflow/pipelines/pull/11965

chore: Update seaweedfs pvc volume size

---

backend/Makefile
backend/README.md

This fixes a syntax error in the Makefile. Additionally, Delve stopped recognizing the breakpoints in VSCode, so this adds an additional VSCode launch.json configuration to solve this..
**Checklist:**

fix(docs): Fix driver remote debugging instructions

---

.github/actions/kfp-cluster/action.yml

fix(CI): Fix a variable reference typo in the GitHub workflow

---

.github/actions/kfp-cluster/action.yml
.github/resources/scripts/deploy-kfp.sh
.github/workflows/e2e-test.yml
.github/workflows/kfp-samples.yml

Add an e2e CI check to test KFP installations deployed with different minor versions of the Argo Workflow Controller.  For this instance, v3.6.7 (current) and v3.5.14 (previous) versions are used, but can be expanded and/or updated in the workflow defintion's input parameter
**Checklist:**

test: Run e2e CI tests using various versions of AWF. Fixes #12150

---

.github/workflows/api-server-tests.yml
backend/test/v2/api/flags.go
backend/test/v2/api/integration_suite_test.go

Merging #12148 without rebasing caused a syntax error.
**Checklist:**

fix(CI): Fix compilation error from merging out of order

---

.github/scripts/verify-argo-matrix.py
.github/workflows/docs-freshness.yml
README.md
third_party/argo/README.md

This adds a GitHub workflow to ensure the read me stays up to date.
**Checklist:**

docs: Document the supported Argo Workflows versions

---

backend/src/apiserver/filter/filter.go
backend/src/apiserver/filter/filter_test.go
backend/src/apiserver/storage/pipeline_store_kubernetes.go
backend/src/apiserver/webhook/pipelineversion_webhook.go
backend/src/apiserver/webhook/pipelineversion_webhook_test.go
backend/src/crd/kubernetes/v2beta1/pipeline_types.go
backend/src/crd/kubernetes/v2beta1/pipelineversion_types.go
backend/src/crd/kubernetes/v2beta1/pipelineversion_types_test.go
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
tools/k8s-native/migration.py

Each commit is merged to master. See each commit for details.
**Checklist:**

[release-2.14] Cherry-pick Kubernetes native API bug fixes

---

.github/workflows/image-builds-release.yml
RELEASE.md

CI: Add back a workflow to build release images

---

.github/workflows/image-builds-master.yml

This was accidentally disabled during the GitHub workflow refactoring.
**Checklist:**

fix(CI): Push built container images on the master branch

---

samples/v2/task_config.py

The sample test accidentally included a hardcoded path for for the KFP package.
**Checklist:**

fix(CI): Fix test-config sample CI failure

---

ADOPTERS.md

chore: add Sophotech to adopters list

---

manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
manifests/kustomize/base/installs/generic/postgres/pipeline-install-config.yaml
manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/deployment.yaml
manifests/kustomize/base/installs/multi-user/pipelines-ui/deployment-patch.yaml
manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml

- Part of https://github.com/kubeflow/pipelines/issues/12239#issuecomment-3284715990
- **Add `ARTIFACTS_PROXY_ENABLED` config**: New environment variable in `pipeline-install-config` (defaults to `"false"`)
**Checklist:**

feat: Make artifact proxy opt-in via ARTIFACTS_PROXY_ENABLED configuration

---

proposals/12147-mlmd-removal/protos/artifacts.proto
proposals/12147-mlmd-removal/protos/runs.json
proposals/12147-mlmd-removal/protos/runs.proto
proposals/12147-mlmd-removal/schema_changes.sql

These changes make various enhancements to the initial mlmd design proposal. See the changes and their descriptions for additional context.
**Checklist:**

chore: update mlmd removal proto/schema design

---

manifests/kustomize/base/installs/multi-user/view-edit-cluster-roles.yaml

It should be pipelineversions and not pipeline/versions. The former is now used in the Kubernetes native API and the latter is not used in the code currently.
**Checklist:**

fix(manifests): Fix a typo in the multi-user roles

---

frontend/package-lock.json
frontend/package.json

remediate CVE-2023-36665 and CVE-2022-25878 protobufjs
**Checklist:**

chore(frontend): remediate CVE-2023-36665 and CVE-2022-25878 protobufjs

---

.github/workflows/build-tools-images.yml
api/Makefile
backend/api/Dockerfile
backend/api/Makefile
backend/api/README.md
kubernetes_platform/Makefile
sdk/Makefile
test/release/Dockerfile.release
test/release/Makefile
test/release/bump-version-docker.sh
test/release/release.sh

All pushes to master and release branches will result in a tag of the name of the branch. PR CI also verifies the images build properly prior to merge.
This also fixes the Dockerfile syntax warnings.
**Checklist:**

fix(CI): Build the generator and release images on pushes

---

.github/actions/test-and-report/action.yml
backend/src/common/client/api_server/util.go
backend/test/config/flags.go
backend/test/end2end/e2e_suite_test.go
backend/test/end2end/pipeline_e2e_test.go
backend/test/end2end/utils/e2e_utils.go
backend/test/test_utils/pipeline_utils.go
backend/test/test_utils/test_utils.go
backend/test/v2/api/integration_suite_test.go
backend/test/v2/api/pipeline_run_api_test.go

chore: Replace sdk in pipeline files
