example/every-minute-cron.yaml, example/every-minute-periodic.yaml, install/manifests/pipelines-crd.yaml
Add manifests to run `scheduledworkflows` and its examples.
for examples:
```
$ go run resources/scheduledworkflow/*.go -kubeconfig $HOME/.kube/config
$ argo install
$ kubectl apply -f install/manifests/pipelines-crd.yaml
$ kubectl apply -f example/
$ kubectl get scheduledworkflows
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/6)
=> Add manifests for CRD, examples

Dockerfile, README.md, install/manifests/scheduledworkflow-crd.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/11)
=> Adding a Dockerfile to create the scheduled workflow container.

samples/kubeflow-tf/README.md
Fixed a link. Clarified YAML vs TAR format for workflow specification. Made other textual improvements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/130)
=> Updated the kubeflow-tf sample README

frontend/src/pages/RunDetails.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/147)
=> Prevents '0' from showing up on RunDetails config tab when pipeline has no parameters

frontend/src/icons/pipelines.tsx
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/121)
=> Adjusts the size and position of the pipelines icon

frontend/src/components/SideNav.test.tsx, frontend/src/components/SideNav.tsx, frontend/src/components/__snapshots__/SideNav.test.tsx.snap, frontend/src/pages/AllRunsList.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
Fixes: #71 
Keeps `Experiments` button/tab on the side-nav highlighted for all non-pipeline pages, including `RecurringRunDetails` and `Compare`.
Changes the title on the `AllRunsList` page to match that of the `ExperimentList` page and adds `Create new experiment` button to `AllRunsList`
Note that we probably should truly merge these pages at some point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/124)
=> Consolidate UI of toolbars for AllRunsList and ExperimentList

test/api-integration-test/run_test.sh, test/backend-unit-test/run_test.sh, test/build_image.yaml, test/e2e_test_gke.yaml, test/imagebuilder/build.sh, test/presubmit-tests-gce-minikube.sh, test/presubmit-tests.gke.sh, test/presubmit-tests.sh, test/sample-test/run_test.sh, test/sample_test.yaml, test/unit_test_gke.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/153)
=> activate public prow service account 

samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/155)
=> Update a sample notebook.

test/sample-test/run_kubeflow_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/152)
=> sample tests using the dataset in the corresponding test project

sdk/python/tests/components/test_components.py, sdk/python/tests/components/test_python_op.py
Also fixed compilation path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/151)
=> SDK/Tests - Removed sys.path manipulations.

frontend/src/components/PlotCard.tsx
Fixes #160 
Properly sizing the fullscreen viewer for HTML artifacts is difficult because we use iframes.
This is something of a workaround to ensure all viewers expand sufficiently in fullscreen mode until we can determine a better way to size them automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/167)
=> Sets min height/width of all fullscreen viewers to 80% 

test/minikube/install_and_start_minikube_without_vm.sh, test/minikube/install_docker_minikube_argo.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/183)
=> Tests - Upgrade Minikube and Kubernetes  for new Docker release

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/87)
=> Presubmit tests - Added presubmit SDK Components tests to Travis

sdk/python/kfp/compiler/compiler.py
This also avoids writing, closing and then reading again the same temporary file which is not always supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/172)
=> SDK/DSL-compiler - Compile without temporary files

sdk/python/kfp/compiler/_component_builder.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/components/_dsl_bridge.py, sdk/python/kfp/dsl/_component.py, sdk/python/kfp/notebook/_magic.py
Made all SDK import relative so that they files always refer to the sibling files instead of the installed package. This makes debugging and development easier since you can be sure the correct files are used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/156)
=> SDK - Relative imports

sdk/python/kfp/components/_components.py, sdk/python/tests/components/test_components.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/168)
=> SDK/Components - Removed the old argument syntax

samples/notebooks/Lightweight Python components - basics.ipynb
Got following error otherwise
```
TypeError: object of type 'NoneType' has no len()
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/201)
=> Update check experiment condition

frontend/mock-backend/package-lock.json, frontend/server/package-lock.json, frontend/src/components/UploadPipelineDialog.test.tsx, frontend/src/lib/Utils.ts, frontend/src/pages/NewExperiment.test.tsx, frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/PipelineSelector.tsx, frontend/src/pages/__snapshots__/NewExperiment.test.tsx.snap, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap, test/frontend-integration-test/helloworld.spec.js
With this PR, the `NewRun` file has nearly complete coverage (by lines).
A little cleanup is done within the `NewExperiment` test as well.
The `_prepareFormFromClone()` function in `NewRun` did not actually change except that the wrapping if-block was changed to just return on the negative condition.
We no longer attempt to change the query params in  `handleChange` when the pipelineID changes as it only would be called during a clone flow, and there's no real reason to do it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/242)
=> Adds NewRun tests

frontend/src/components/Router.tsx, frontend/src/pages/Page.tsx, frontend/src/pages/RecurringRunDetails.test.tsx, frontend/src/pages/RecurringRunDetails.tsx, frontend/src/pages/__snapshots__/RecurringRunDetails.test.tsx.snap
- Fixes a bug in `RecurringRunDetails` where an undefined `enabled` field shows both Enable and Disable buttons as active.
- Adds comprehensive test suite for `RecurringRunDetails`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/202)
=> Recurring run details tests

frontend/src/lib/RunUtils.ts, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/PipelineSelector.tsx, frontend/src/pages/RecurringRunsManager.tsx, frontend/src/pages/RunList.test.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
- Refactor `RunList` to have one code path for loading runs, which branches only to get the list of run IDs.
- Add comprehensive test suite for `RunList`.
- Refactor `extractMetricMetadata` into `RunUtils` for easier testing (not done yet).
- Explicitly hard code the initial sort column in all `CustomTable` instances, since this is no longer maintained by the parent component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/127)
=> Refactor RunList, add test suite

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/secret.py, sdk/python/tests/compiler/testdata/secret.yaml
This would allow specifying gcp secret to the container, for accessing all GCP API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/261)
=> Add gcp secret parameter to container op

sdk/python/kfp/compiler/_component_builder.py, sdk/python/tests/compiler/component_builder_test.py, sdk/python/tests/compiler/main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/228)
=> enable component build unit test

sdk/python/kfp/compiler/_component_builder.py
solves issue: #288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/292)
=> configure logger such that it shows correct colors for the logs

frontend/server/package-lock.json, frontend/server/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/271)
=> Upgrade @kubernetes/client-node

frontend/src/pages/PipelineDetails.tsx
Fixes: #301
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/302)
=> Allows copying of pipeline source from pipeline details page

frontend/mock-backend/mock-conditional-template.yaml, frontend/src/lib/StaticGraphParser.test.ts, frontend/src/lib/StaticGraphParser.ts, frontend/src/pages/PipelineDetails.tsx, frontend/third_party/argo-ui/argo_template.ts
Updates the `StaticGraphParser` and tests to work with the newly simplified format of conditional pipelines.
Note: this PR is looking to merge with `avolkov/Fixed-compilation-of-dsl.Conditional-2` **not** `master`.
Once this PR is merged, the entire branch will be merged all at once (#177) so that the compiler and frontend stay in sync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/293)
=> Update frontend handling of graphs

ml-pipeline/ml-pipeline/prototypes/ml-pipeline.jsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/291)
=> Update default pipeline version in ks package

sdk/python/kfp/_client.py, test/e2e_test_gke.yaml, test/sample-test/run_basic_test.py, test/sample-test/run_kubeflow_test.py, test/sample-test/run_test.sh, test/sample-test/run_tfx_test.py, test/sample-test/run_xgboost_test.py, test/sample_test.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/306)
=> configurable namespaces in sample test and python SDK

test/OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/299)
=> add ngao to test owner because frequent contributions to this directory, including e2e, sample tests and imagebuilder.

frontend/src/components/Toolbar.test.tsx, frontend/src/components/Toolbar.tsx, frontend/src/components/__snapshots__/Toolbar.test.tsx.snap, frontend/src/pages/ExperimentDetails.tsx, frontend/src/pages/PipelineDetails.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/264)
=> Update button styling for new experiment and new run

frontend/mock-backend/mock-conditional-template.yaml, frontend/src/lib/StaticGraphParser.test.ts, frontend/src/lib/StaticGraphParser.ts, frontend/src/pages/PipelineDetails.tsx, frontend/third_party/argo-ui/argo_template.ts, sdk/python/kfp/compiler/compiler.py, sdk/python/tests/compiler/testdata/coin.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/177)
=> SDK/DSL/Compiler - Improved compilation of dsl.Conditional - UX support done

sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/volume.py, sdk/python/tests/compiler/testdata/volume.yaml
We will have a gcpOp that add some default volumes to the container, and we should allow upper level ops inheriting gcpOp to add more volumes, envs if they want. 
A concrete example is having a op that read a GCS data and push to github. In this case I want to mount both GCP secret volume and Git secret volume.
TODO: we can add a batch method to add a list of resources, but that's not must have right now. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/312)
=> switch set() to add() for better inheritance.

.travis.yml, frontend/mock-backend/package-lock.json, frontend/package-lock.json, frontend/server/package-lock.json, frontend/src/components/viewers/Tensorboard.test.tsx, frontend/src/pages/__snapshots__/PipelineList.test.tsx.snap, frontend/src/pages/__snapshots__/RecurringRunDetails.test.tsx.snap
Some snapshot tests weren't correct because of a corner case with npm vs node versions. Some tests were also not working as intended (needed to wait a little more before getting to the right state), not sure how those got the good snapshots to begin with.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/317)
=> Use latest npm and node on travis, fix tests

sdk/python/kfp/compiler/_component_builder.py, sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_python_op.py, sdk/python/kfp/components/_structures.py, sdk/python/tests/components/test_components.py, sdk/python/tests/components/test_data/python_add.component.yaml, sdk/python/tests/components/test_python_op.py
No need for the longer name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/323)
=> SDK/Components - Renamed DockerContainer spec to to Container

frontend/src/Css.tsx, frontend/src/pages/PipelineDetails.tsx
Fixes: #289 
Now, when the summary is hidden, a "Show summary" button will appear at the bottom of the graph to reopen the card.
Additionally, added a small note reading "Static pipeline graph" to the bottom of the graph.
Summary shown:
Summary hidden:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/305)
=> Changes "Hide" button on Pipeline summary to fully hide the paper card

frontend/src/components/Router.tsx, frontend/src/components/Toolbar.test.tsx, frontend/src/components/Toolbar.tsx, frontend/src/components/__snapshots__/Toolbar.test.tsx.snap, frontend/src/pages/404.tsx, frontend/src/pages/AllRunsList.tsx, frontend/src/pages/Compare.tsx, frontend/src/pages/ExperimentDetails.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/ExperimentsAndRuns.tsx, frontend/src/pages/NewExperiment.test.tsx, frontend/src/pages/NewExperiment.tsx, frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/PipelineList.tsx, frontend/src/pages/PipelineSelector.tsx, frontend/src/pages/RecurringRunDetails.test.tsx, frontend/src/pages/RecurringRunDetails.tsx, frontend/src/pages/RecurringRunsManager.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/Status.tsx, frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap, frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap, frontend/src/pages/__snapshots__/Status.test.tsx.snap
- Makes `updateToolbar` accept a partial object of toolbar props.
- Adds a `pageTitle` property to toolbar props that accepts a string or a component.
- Uses the property to display the status icon next to run name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/287)
=> Add run status to page title

test/presubmit-tests.sh
Removed pipe from argo submit.
Only the last pipe command affects the exit pipeline code unless `set -o pipefail` is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/324)
=> Tests - Fixed the argo submit failure not failing the script

sdk/python/kfp/compiler/_component_builder.py, sdk/python/tests/compiler/testdata/kaniko.basic.yaml
Based on https://github.com/GoogleContainerTools/kaniko#kubernetes-secret this should work without additional setups. 
In future we should make the credential mounting configurable so it's not GCP specific.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/343)
=> mount gcp credentials for kaniko worker

frontend/src/pages/PipelineDetails.tsx
This is a follow-up to #305
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/353)
=> Fixes issue with footer overlapping side panel and fixes summary layout

test/presubmit-tests.sh
Since the script tracing is enabled, the logs are currently printed three times:
1. When they're assigned to the variable
2. When the printf command is traced
3. When the printf command executes
This makes the logs harder to understand.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/366)
=> Tests - Stop repeating the logs three times

frontend/server/package-lock.json, frontend/src/components/Toolbar.test.tsx, frontend/src/components/Toolbar.tsx, frontend/src/components/__snapshots__/Toolbar.test.tsx.snap
Fixes: #221 
Previously, when users created a run from a notebook and clicked the resulting link to see it in the UI, they would see an active, clickable back button but clicking it would have no effect.
Now, when there is no browser history, the back button is still present, but it is lighter gray and has no hover animation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/377)
=> Disables back button when there is no history

sdk/python/kfp/compiler/_component_builder.py, sdk/python/tests/compiler/component_builder_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/384)
=> remove fire dependency in the component image build

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/375)
=> Add Amy and Lak's Blogs Link to README

test/presubmit-tests-gce-minikube.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/367)
=> Tests - Improve Minikube source code copy process

samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/378)
=> update samples with dependency requirement in the component image build

test/frontend-integration-test/helloworld.spec.js
I've seen a few frontend integration test failures timing out waiting for test runs to start. Let's see if this takes care of it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/392)
=> Increase timeout waiting for test run to start

frontend/src/lib/WorkflowParser.test.ts, frontend/src/lib/WorkflowParser.ts
This adds support for artifact source urls that start with "minio://".  I have a custom pipeline step that needs to write HTML to the local minio store instead of gcs.  The artifacts API supports fetching urls from the local minio store, the url parser only supports "gs://".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/389)
=> Add support for minio hosted artifacts

README.md, components/README.md, samples/README.md, samples/basic/README.md, samples/kubeflow-tf/README.md, samples/tfx/README.md, samples/xgboost-spark/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/398)
=> Pointed doc links to Kubeflow website instead of wiki.

frontend/src/lib/OutputArtifactLoader.test.ts, frontend/src/lib/OutputArtifactLoader.ts, frontend/src/pages/Compare.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Adds a comprehensive test suite for the RunDetails component, which caught a few bugs, also fixed here:
- Gracefully handle missing fields on the workflow object when displaying its config fields.
- Also parse out the selected node's message field when calling `load`, which is called on refresh.
- If the message field is gone after refresh, remove the banner.
- Wait for the side pane's busy state to be set before proceeding to unset it.
Fixes #383.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/394)
=> RunDetails test suite, bug fixes

backend/Dockerfile
Fixes https://github.com/kubeflow/pipelines/issues/354
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/387)
=> Backend - Fixed handling of sample compilation failure

frontend/src/components/Graph.tsx, frontend/src/components/__snapshots__/Graph.test.tsx.snap, frontend/src/pages/PipelineDetails.test.tsx, frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
The only functional change is splitting out the try/catch block in the load function to make the errors more granular and user friendly. This also means the two fetch API calls are done in sequence instead of in parallel, but this isn't a big deal here since it's exactly two calls per page load.
Fixes https://github.com/kubeflow/pipelines/issues/379.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/380)
=> PipelineDetails page tests

contrib/components/openvino/model_convert/README.md, contrib/components/openvino/model_convert/containers/Dockerfile, contrib/components/openvino/model_convert/containers/convert_model.py, contrib/components/openvino/tf-slim/README.md, contrib/components/openvino/tf-slim/containers/Dockerfile, contrib/components/openvino/tf-slim/containers/slim_model.py, contrib/samples/openvino/model_optimizer/convert_model_pipeline.py, contrib/samples/openvino/tf-slim/README.md, contrib/samples/openvino/tf-slim/tf-slim.py
New component generating slim models which can be used in combination with other components for demo and testing purposes.
In the PR is included a sample pipeline linking TF slim models generation with OpenVINO model optimization and converting to IR format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/335)
=> added component with tf slim model generator and pipeline adjustments

test/sample-test/run_basic_test.py, test/sample-test/run_kubeflow_test.py, test/sample-test/run_tfx_test.py, test/sample-test/run_xgboost_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/417)
=> Failed the sample tests when it should

sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_structures.py, sdk/python/tests/components/test_components.py
This change adds support for loading and "materializing" components with optional inputs. The default values are not yet supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/214)
=> SDK/Components - Support for optional inputs

sdk/python/kfp/compiler/_component_builder.py
This changes the interface between PythonContainerOp and materializer from schema-less dict to `ComponentSpec`. This ensures the interface is not silently broken.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/396)
=> SDK/Components/PythonContainerOp - Switch from dict to ComponentSpec

sdk/python/kfp/_client.py
We're only supporting Python 3.5+. We never supported Python 2.
The reason I want to remove `six` is because it's not a included in the standard package python image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/425)
=> SDK/Client - Removed import six

frontend/src/Css.tsx, frontend/src/components/CustomTable.test.tsx, frontend/src/components/CustomTable.tsx, frontend/src/components/__snapshots__/CustomTable.test.tsx.snap, frontend/src/pages/RunList.test.tsx, frontend/src/pages/__snapshots__/RecurringRunsManager.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
To help with #149, this dims the list and shows a spinner while busy loading.
The snapshot test changes are all because the spinner shows up immediately when loading, so I had to add a bunch of promise flushes to stabilize them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/405)
=> Add loading spinner to custom table while loading items

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_ops_group.py, sdk/python/kfp/dsl/_pipeline_param.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/309)
=> SDK/DSL - Added support for conditions: !=,  <, <=, >=, >

sdk/python/build.sh
* Make the script fail on error.
* Support relative output paths: `./build.sh kfp.tar.gz`
* Support default output path (`./kfp.tar.gz`): `./build.sh`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/364)
=> SDK - Improve the python package build

sdk/python/kfp/components/_components.py, sdk/python/tests/components/test_components.py, sdk/python/tests/components/test_python_op.py
This realizes the outputs handling vision and solves problems with input and output name clashes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/388)
=> SDK/Components - Removed outputs from task factory function signature

sdk/python/kfp/compiler/_component_builder.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/463)
=> import bug

frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Fixes #75.
This PR adds cloning functionality in the `NewRun` component to support copying an embedded pipeline in the original run. When such a pipeline is found, switch controls show up (radio button group for now) to allow switching between the cloned run's pipeline, and choosing from the pipeline list.
@ajayalfred can you take a look at this? I needed something working that is still usable, feel free to change the design. I won't block the PR on the potential redesign though, we can iterate on it later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/465)
=> Support cloning runs created with an embedded pipeline

test/frontend-integration-test/helloworld.spec.js
Fixes #453.
The issue was that sometimes logs are grabbed too early, when they haven't been downloaded from the pod yet. This results in logs being just "1", which is the text of the line numbers gutter, which only has one line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/459)
=> Wait until logs appear right in e2e test

test/frontend-integration-test/helloworld.spec.js
Fixes #464.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/472)
=> Refresh while waiting for run to start

sdk/python/kfp/compiler/_component_builder.py, sdk/python/tests/compiler/component_builder_test.py
This is part of a bigger effort to make all output locations manageable in preparation for storage system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/424)
=> SDK/Components/PythonContainerOp - Make the local output path configurable

frontend/mock-backend/fixed-data.ts, frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Follow up on #75. Embedded pipeline spec is actually JSON not YAML.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/474)
=> Fix serializing cloned embedded pipeline

frontend/server/k8s-helper.ts
This fixes a bug where if logs only return a number, it's misinterpreted by express to be the status not the return content.
Fixes https://github.com/googleprivate/ml/issues/1390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/476)
=> Return string from pod logs

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/471)
=> Add article on Jupyter notebooks

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/kfp/gcp.py, sdk/python/tests/compiler/testdata/basic.py, sdk/python/tests/compiler/testdata/basic.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/491)
=> support tpu settings in dsl

frontend/src/lib/WorkflowParser.ts, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Fixes #331.
Fixes #92.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/496)
=> Show all run outputs in dedicated tab

components/dataflow/tfdv/src/validate.py, components/local/confusion_matrix/src/confusion_matrix.py, components/local/roc/src/roc.py, samples/tfx/taxi-cab-classification-pipeline.py
* Confusion matrix and ROC components support flexible target.
* Use single mode instead of 4 different modes for TFDV, TFMA, TFT, Predicton.
* TFDV output's schema path directly.
* Add Confusion Matrix and ROC components to tf taxi sample.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/518)
=> Improve TFX Taxi Sample and Components.

sdk/python/kfp/_client.py, test/sample-test/check_notebook_results.py
resolving https://github.com/kubeflow/pipelines/issues/506
/cc qimingj Ark-kun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/508)
=> Improve get_experiment and list_runs in the python sdk

frontend/src/components/Router.tsx, frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/PipelineDetails.test.tsx, frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Users will now be able to create a run directly from the pipeline details page.
If the pipeline was a regularly uploaded pipeline, the new run page will show the normal pipeline picker with the relevant pipeline preselected.
If the pipeline was part of a run created in a notebook or from the CLI, the new run page will instead show radio buttons allowing the user to continue with the relevant pipeline, or select a different one. Users can also change their minds about this and use the radio buttons to reselect the original pipeline.
Fixes #53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/507)
=> Add new run button to pipeline details

frontend/src/apis/experiment/api.ts, frontend/src/apis/pipeline/api.ts, frontend/src/apis/run/api.ts
No functional changes, just ran `npm run apis`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/524)
=> Regenerate swagger APIs

sdk/python/kfp/components/__init__.py, sdk/python/kfp/components/_component_store.py
Usage:
```
from kfp.components import ComponentStore
cs = ComponentStore()
cs.local_search_paths.append(str(Path(__file__).parent.joinpath('../../components/')))
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/519)
=> SDK/Components - Made component search locations configurable

components/OWNERS, samples/OWNERS, sdk/OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/531)
=> Add hongye-sun to OWNERS of samples, components, and sdk directories.

sdk/python/kfp/_client.py, test/sample-test/run_basic_test.py, test/sample-test/run_kubeflow_test.py, test/sample-test/run_tfx_test.py, test/sample-test/run_xgboost_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/529)
=> Change "namespace" param to "host" in kfp client so we can use Jupyter outside cluster.

test/sample_test_v2.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/499)
=> Add lightweight sample test

backend/src/agent/persistence/client/pipeline_client.go, backend/src/agent/persistence/main.go, backend/src/common/util/service.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/538)
=> fix persistence agent to use in cluster DNS instead of kube proxy to access API

frontend/src/lib/StaticGraphParser.ts, frontend/src/lib/WorkflowParser.ts, frontend/third_party/argo-ui/argo_template.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/541)
=> Hides TaskGroup nodes from runtime graphs and removes unnecessary edges in static graphs

backend/Dockerfile, backend/src/apiserver/main.go, pipeline/pipeline/pipeline-apiserver.libsonnet, test/presubmit-tests-with-pipeline-deployment.sh
Add a job to load sample to pipeline backend once. 
Reuse API server binary to load the samples since most code are shared. 
The corresponding kubeflow code change is here https://github.com/kubeflow/kubeflow/pull/2071
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/509)
=> add job to load sample

frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Previously, the `await` was not actually being applied to the API calls, so a run creation could fail, but the success snackbar would still be shown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/553)
=> Fixes await bug in create new run

components/local/roc/src/roc.py
If it is a binary classification, which is usually the case when ROC is involved, we either expect a "trueclass" value to indicate the value of the true class, or expect the data is like:
predicted, target, true, false
false,true,0.1,0.9
...
in which there is a "true" column for the probability, and "true" is a predicted class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/559)
=> Fix ROC Component

sdk/python/kfp/compiler/compiler.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/558)
=> remove duplicate volumes

backend/Dockerfile, backend/Dockerfile.persistenceagent, backend/Dockerfile.scheduledworkflow, developer_guide.md
* remove unused steps from dockerfile
* correct the document about building docker image
* use a latest stable alpine base image
* support other architectures
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/562)
=> update dockerfile and build steps

frontend/mock-backend/mock-api-middleware.ts, frontend/src/components/UploadPipelineDialog.test.tsx, frontend/src/components/UploadPipelineDialog.tsx, frontend/src/components/__snapshots__/UploadPipelineDialog.test.tsx.snap, frontend/src/pages/PipelineList.test.tsx, frontend/src/pages/PipelineList.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/554)
=> Enables uploading a pipeline via a URL

frontend/mock-backend/fixed-data.ts
Follow up on https://github.com/kubeflow/pipelines/pull/524/files. The `namespace` field has been removed from the proto, but it's still in the mock data for the frontend, so the project fails to build.
/assign @neuromage 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/564)
=> Fix frontend mock data after proto changes

sdk/python/kfp/compiler/_component_builder.py, sdk/python/kfp/compiler/_k8s_helper.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/components/_component_store.py, sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_dynamic.py, sdk/python/kfp/components/_structures.py, sdk/python/kfp/dsl/_ops_group.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/k8s_helper_tests.py
Add some comments; refactor convert_k8s_obj_to_json; remove unnecessary imports; add license to dsl_bridge.
As the Python SDK codebase becomes larger, it requires some cleaning to make it more readable. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/568)
=> Refactor Python SDK

backend/src/apiserver/server/run_server.go, backend/src/apiserver/server/run_server_test.go
Removes the experiment reference validation, and adds a test. Fixes https://github.com/kubeflow/pipelines/issues/560.
/area back-end
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/572)
=> Allow creating runs with no experiments

test/imagebuilder/Makefile
Just bringing it in line with Kubeflow original Makefiles. Nothing should change.
* No longer using `gcloud container images add-tag` after the push
* No longer adding `-dirty` if there are no changed files in the Docker context directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/500)
=> Tests - Updated image-builder Makefile

backend/src/apiserver/client_manager.go, backend/src/apiserver/config/config.json
The first time creating the table failed because service unavailable. Retry resolve the issue. 
F1221 08:21:25.810654       1 error.go:296] dial tcp 10.47.244.96:3306: connect: connection timed out
goroutine 1 [running]:
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.stacks(0xc0006b6300, 0xc000400000, 0x66, 0x9b)
/go/src/github.com/kubeflow/pipelines/vendor/github.com/golang/glog/glog.go:769 +0xd4
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.(*loggingT).output(0x263bee0, 0xc000000003, 0xc0006ae790, 0x239a356, 0x8, 0x128, 0x0)
/go/src/github.com/kubeflow/pipelines/vendor/github.com/golang/glog/glog.go:720 +0x329
github.com/kubeflow/pipelines/vendor/github.com/golang/glog.(*loggingT).printf(0x263bee0, 0xc000000003, 0x15d6c0d, 0x2, 0xc000543a60, 0x1, 0x1) …
=> retry on create table in api server

pipeline/pipeline/all.libsonnet
Fix for issue [#594](https://github.com/kubeflow/pipelines/issues/594)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/602)
=> fix for boostrapp problem

test/presubmit-tests-with-pipeline-deployment.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/588)
=> Deployment - Minikube support - Passing the platform parameter to kfctl

components/resnet-cmle/resnet/resnet_model/trainer/resnet_main.py, sdk/python/kfp/gcp.py
Set GCP credential for gcloud. Do not export TPU Model because a) Serving does not need TPU. b) Workaround a CMLE 1.9 issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/599)
=> First step to bring back CMLE sample.

frontend/src/components/CompareTable.tsx, frontend/src/components/PlotCard.tsx, frontend/src/components/viewers/ConfusionMatrix.tsx, frontend/src/components/viewers/ROCCurve.tsx, frontend/src/components/viewers/__snapshots__/ROCCurve.test.tsx.snap, frontend/src/pages/Compare.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/Compare.test.tsx.snap
Fixes #597.
The main problem here was that the PlotCard component was not pure. This was causing all plots to re-render fully whenever state changes on the compare page, which happens on collapsing/expanding sections, and on selecting/deselecting runs.
Simply extending `PureComponent` doesn't work here, since it gets an array of objects, so shallow comparison always fails. Implementing `shouldComponentUpdate` to properly check fixes this.
This PR also disables animations in thumbnailed ROC curve, and turns RunList and CompareTable into pure components, which reduces the number of re-renders when collapsing all compare page sections from 280+ to about 50. Some of these are still because of some react-vis axis mutations that I do not understand, but it's quite a bit more usable.
Tip: turn …
=> Compare perf - pure components, disable ROC curve thumbnail animations

sdk/python/build.sh
So people can use python to CRUD pipeline or job, from for example notebook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/628)
=> Generate pipeline and job python client as part of SDK

test/sample-test/run_test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/636)
=> fix deploy model name conflict in case of concurrent notebook sample test

backend/src/common/util/service.go, backend/test/test_utils.go
fixes #624 
I've verified the restarts no longer happen with this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/633)
=> Fix retrying logic which was causing persistenceagent to crash loop.

samples/basic/condition.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_dsl_bridge.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/compiler/testdata/coin.py, sdk/python/tests/compiler/testdata/coin.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/623)
=> Support replacable arguments in command as well (besides arguments) in container op.

.gitattributes
https://github.com/github/linguist#overrides
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/652)
=> Use linguist annotations to skip diffing generated files

frontend/tsconfig.json
Right now, the build fails if the generated Typescript definitions don't build according to our tsconfig file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/654)
=> Correctly ignore src/apis when building frontend

sdk/python/kfp/compiler/_component_builder.py, sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_python_op.py, sdk/python/kfp/components/_structures.py, sdk/python/kfp/components/modelbase.py, sdk/python/kfp/components/structures/kubernetes/v1.py, sdk/python/setup.py, sdk/python/tests/components/test_components.py, sdk/python/tests/components/test_graph_components.py, sdk/python/tests/components/test_structure_model_base.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/642)
=> SDK/Components - Reworked the component model structures.

frontend/mock-backend/mock-api-middleware.ts, frontend/src/apis/filter/api.ts, frontend/src/atoms/Input.tsx, frontend/src/components/CustomTable.test.tsx, frontend/src/components/CustomTable.tsx, frontend/src/components/__snapshots__/CustomTable.test.tsx.snap, frontend/src/lib/Apis.ts, frontend/src/pages/ExperimentList.test.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/PipelineList.test.tsx, frontend/src/pages/PipelineList.tsx, frontend/src/pages/RecurringRunsManager.test.tsx, frontend/src/pages/RecurringRunsManager.tsx, frontend/src/pages/ResourceSelector.test.tsx, frontend/src/pages/ResourceSelector.tsx, frontend/src/pages/RunList.test.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap, frontend/src/pages/__snapshots__/PipelineList.test.tsx.snap, frontend/src/pages/__snapshots__/RecurringRunsManager.test.tsx.snap, frontend/src/pages/__snapshots__/ResourceSelector.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
All lists, excluding the "last 5 runs" within the experiment list, will now include a filter bar.
Initially, filtering will be limited to the "name" column for each resource and will look for matching substrings, so "xgb" and "oos" will both match "xgboost-1".
This PR partially addresses #257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/656)
=> Add simple filtering by name to CustomTable

sdk/python/tests/components/test_python_op.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/664)
=> SDK/Tests - Fixed the output ordering instability in tests

frontend/mock-backend/mock-api-middleware.ts, frontend/src/components/SideNav.test.tsx, frontend/src/components/SideNav.tsx, frontend/src/components/__snapshots__/SideNav.test.tsx.snap, frontend/src/lib/Apis.test.ts, frontend/src/lib/Apis.ts
If the information is reachable, the side nav will now display the first 7 characters of the commit hash that the API server image was built from, and link to that commit.
Note to reviewers: hide whitespace changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/670)
=> Add build version to side nav

sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_dsl_bridge.py
Simple refactoring:
Most of the code was moved to `_dsl_bridge.create_container_op_from_task` and is less indented now.
* Renamed `_dsl_bridge._create_task_object` to `_create_container_op_from_resolved_task` and moved the output name sanitization there.
* Introduced the `_components._created_task_transformation_handler` handler that specifies the transformation function that is called when `TaskSpec` instance is created from `ComponentSpec`. Such transformation can for example convert `TaskSpec` to `ContainerOp`.
Rationale: When the pipeline author loads a component and uses it
```
train_test_op = load_component('TF - Train and evaluate')
...
train_test_task = train_test_op(train_data, test_data)
```
the `train_test_task` is not always container task. Sometimes it's a graph task. In this …
=> SDK/Components - Simplified _create_task_factory_from_component_spec function

frontend/src/components/SideNav.tsx, frontend/src/components/__snapshots__/SideNav.test.tsx.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/682)
=> Adds a link in the side nav to the KF 'usage-reporting' doc

frontend/src/lib/WorkflowParser.ts, frontend/src/pages/ExperimentList.test.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/RunList.test.tsx, frontend/src/pages/Status.test.tsx, frontend/src/pages/Status.tsx, frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap, frontend/src/pages/__snapshots__/Status.test.tsx.snap
- Last 5 runs status icons in `ExperimentList` will now show the run's start date.
- The status icon at the top of the `RunDetails` page shows start date.
- The status icons for individual steps in the runtime graph will show start and end date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/671)
=> Include date in run status tooltips

backend/src/apiserver/storage/job_store.go, backend/src/apiserver/storage/run_store.go
Move the filter on resource reference to the first select statement in the nested sql
```
SELECT subq.*, 
"[" 
|| Group_concat(r.payload, ",") 
|| "]" AS refs 
FROM   (SELECT rd.*, 
"[" 
|| Group_concat(m.payload, ",") 
|| "]" AS metrics 
FROM   (SELECT * 
FROM   run_details 
WHERE  uuid IN (SELECT resourceuuid 
FROM   resource_references AS rf 
WHERE  ( rf.resourcetype = ? 
AND rf.referenceuuid = ? 
AND rf.referencetype = ? ))) AS rd 
LEFT JOIN run_metrics AS m 
ON rd.uuid = m.runuuid 
GROUP  BY rd.uuid) AS subq 
LEFT JOIN (SELECT * 
FROM   resource_references 
WHERE  resourcetype = 'Run') AS r 
ON subq.uuid = r.resourceuuid 
WHERE  ( createdatinsec > ? 
OR ( createdatinsec = ? 
AND uuid >= ? ) ) 
GROUP  BY subq.uuid 
ORDER  BY createdatinsec ASC, 
uuid ASC 
LIMIT  2 
```
---
This change …
=> improve the list run query

sdk/python/kfp/components/_components.py
This is needed for the future storage system based on volume mounts:
If outputs were written to files in the same dir (e.g. `/outputs/out1.txt` and `/outputs/out2.txt`), then we cannot separate them and mount to the downstream task containers independently.
Writing outputs to `/outputs/out1/data` and `/outputs/out2/data` solves this problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/663)
=> SDK/Components - Added /data to the generated file paths

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/697)
=> Update changelog for release 0.1.8

samples/tfx/taxi-cab-classification-pipeline.py
use the workflow UID instead of name to avoid name collision after the name is truncated inside the deployer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/704)
=> randomize the deployment name to avoid collision

sdk/python/setup.py
This version has multiple bug fixes.
This seems to be the last release available for Debian 9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/691)
=> SDK - Update minimum Python version to 3.5.3

test/sample-test/run_resnet_cmle_test.py
The test is not added to the list to run automatically yet since it takes about 25 min.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/724)
=> Add CMLE sample test script.

pipeline/Dockerfile, test/presubmit-tests-with-pipeline-deployment.sh
This would align with kubeflow deployment version requirement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/693)
=> bump ks version in presubmit test 

sdk/python/kfp/components/_python_op.py
This makes Lightweight Python components more Python2 compatible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/717)
=> SDK/Components/Python - Made the typing.NamedTuple import optional

samples/basic/retry.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/retry.py, sdk/python/tests/compiler/testdata/retry.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/723)
=> Add "set_retry()" on ContainerOp.

frontend/mock-backend/fixed-data.ts, frontend/src/components/SideNav.test.tsx, frontend/src/components/UploadPipelineDialog.test.tsx, frontend/src/pages/Compare.test.tsx, frontend/src/pages/ExperimentDetails.test.tsx, frontend/src/pages/ExperimentList.test.tsx, frontend/src/pages/NewRun.test.tsx, frontend/src/pages/PipelineDetails.test.tsx, frontend/src/pages/PipelineList.test.tsx, frontend/src/pages/ResourceSelector.test.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/Status.test.tsx, frontend/src/pages/Status.tsx, frontend/src/pages/__snapshots__/Status.test.tsx.snap
Auto-refresh is paused when the window loses focus (blur) and is resumed
upon re-focus. Autorefresh is permanently terminated if the run has
stopped due to failure, error, being skipped, or succeeding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/722)
=> Auto-refreshes the run details page

sdk/python/kfp/components/_python_op.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/718)
=> SDK/Components/Python - Improved Python2 compatibility

sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_dsl_bridge.py, sdk/python/kfp/components/_naming.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/715)
=> SDK/Components - Added _naming._convert_to_human_name function

sdk/python/kfp/components/_dsl_bridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/710)
=> SDK/Components - More meaningful error when trying to convert graph component to ContainerOp

sdk/python/kfp/components/_structures.py, sdk/python/tests/components/test_components.py
Just replacing `PrimitiveTypes` with `str` and removing one test.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/711)
=> SDK/Components - Command line args can only be strings or placeholders

sdk/python/kfp/components/modelbase.py
This stops serialization of any additional attributes set on an object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/733)
=> SDK/Components - convert_object_to_struct now uses __init__ to get field list

sdk/python/kfp/components/modelbase.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/732)
=> SDK/Components - Improved error when type checking fails in constructor

components/dataproc/common/_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/735)
=> fix dataproc cluster version

developer_guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/743)
=> Updated dev guide for apiserver build with minikube.

.cloudbuild.yaml, backend/Dockerfile.viewercontroller
Also build it as part of the CloudBuild process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/740)
=> Add Dockerfile for building Viewer CRD controller.

frontend/src/Css.tsx, frontend/src/atoms/IconWithTooltip.test.tsx, frontend/src/atoms/IconWithTooltip.tsx, frontend/src/atoms/__snapshots__/IconWithTooltip.test.tsx.snap, frontend/src/components/Graph.test.tsx, frontend/src/components/Graph.tsx, frontend/src/components/__snapshots__/Graph.test.tsx.snap, frontend/src/lib/WorkflowParser.test.ts, frontend/src/lib/WorkflowParser.ts, frontend/src/lib/WorkflowParser.tsx, frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap, frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap, frontend/src/pages/__snapshots__/Status.test.tsx.snap
- displays spinner when no nodes have started
- adds info message to bottom of runtime graph indicating that it is
runtime and that the graph will update over time
- adds placeholder nodes at end of graph to indicate future progress
Example graph for unfinished run:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/734)
=> Improve runtime graph starting and running experience

frontend/src/TestUtils.tsx, frontend/src/lib/Buttons.ts, frontend/src/pages/AllRunsList.tsx, frontend/src/pages/Compare.test.tsx, frontend/src/pages/Compare.tsx, frontend/src/pages/ExperimentDetails.test.tsx, frontend/src/pages/ExperimentDetails.tsx, frontend/src/pages/ExperimentList.test.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/PipelineDetails.test.tsx, frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/PipelineList.test.tsx, frontend/src/pages/PipelineList.tsx, frontend/src/pages/RecurringRunDetails.test.tsx, frontend/src/pages/RecurringRunDetails.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/Compare.test.tsx.snap, frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
This PR refactors button action methods into the `Buttons` module, which fixes a few bugs, and allows for sharing common functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/758)
=> Add UI actions to Buttons module

backend/Dockerfile.viewercontroller
Let it build properly with Go modules, and also copy the source from
/vendor into the image for licensing requirements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/760)
=> Fix Dockerfile for viewer CRD image.

components/kubeflow/deployer/src/deploy.sh
fixes: #726
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/755)
=> Enhance deploy.sh to support local storage

test/presubmit-tests-with-pipeline-deployment.sh, test/sample-test/run_test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/778)
=> Revert GPU tests to unblock release

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/__init__.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/imagepullsecret.py, sdk/python/tests/compiler/testdata/imagepullsecret.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/745)
=> support pipeline level imagepullsecret in DSL

developer_guide.md
The old deployment way (bootstrapper.yaml/deploy.sh) has been removed, the pipeline is included in kubeflow now, but the developer guide is not updated accordingly. 
The PR to renew the deployment section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/771)
=> update developer guide to renew deployment section

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/797)
=> Update changelog for release 0.19

component_sdk/python/kfp_component/launcher/__init__.py, component_sdk/python/kfp_component/launcher/__main__.py, component_sdk/python/kfp_component/launcher/launcher.py, component_sdk/python/requirements.txt, component_sdk/python/run_test.sh, component_sdk/python/tests/launcher/__init__.py, component_sdk/python/tests/launcher/echo.py, component_sdk/python/tests/launcher/test_launcher.py
Added a dynamic python fire launcher module which can be used as entrypoint to KFP components. 
This will be used by GCP component as a single entrypoint to run all gcp commands.
For example, in mlengine create job spec:
`python -m kfp_component.launcher kfp_component.google.ml_engine create_job --project <project> --job <job_payload>`
The same entrypoint can also be used to launch from arbitrary python file. After argo artifact raw content store is supported, user can directly put python function as a file in container and use the same entrypoint to launch it:
`python -m kfp_component.launcher /tmp/script.py my_func --param1 <p1> --param2 <p2>`
--- …
=> Add Launcher module in component SDK

test/presubmit-tests-with-pipeline-deployment.sh
us-central-1 has lots of stockout happening. switch zone for less flaky test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/808)
=> switch test to us-west1

.cloudbuild.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/813)
=> Increase disk size and use high CPU machine type in cloud build

components/bigquery/query/build_image.sh, components/build_image.sh, components/dataflow/predict/build_image.sh, components/dataflow/tfdv/build_image.sh, components/dataflow/tfma/build_image.sh, components/dataflow/tft/build_image.sh, components/dataproc/analyze/build_image.sh, components/dataproc/create_cluster/build_image.sh, components/dataproc/delete_cluster/build_image.sh, components/dataproc/predict/build_image.sh, components/dataproc/train/build_image.sh, components/dataproc/transform/build_image.sh, components/local/confusion_matrix/build_image.sh, components/local/roc/build_image.sh
The PR includes:
1. a shared build_image.sh file shared by multiple component build script
2. Supports optionally pull latest image and use it as cache to build new docker image
The PR only converts build scripts which follow the same pattern. If it proves to work, I will create another task to convert other components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/815)
=> Improve docker image build perf by leveraging docker cache

frontend/src/pages/NewRun.tsx
Closes #612 
Now : 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/826)
=> Fixed validation in new run form when filling name then pipeline

frontend/package-lock.json, frontend/package.json, frontend/server/package-lock.json, frontend/server/package.json, frontend/src/components/CustomTable.tsx, frontend/src/pages/ExperimentList.test.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/PipelineList.tsx, frontend/src/pages/RecurringRunsManager.test.tsx, frontend/src/pages/RecurringRunsManager.tsx, frontend/src/pages/RunList.test.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/Status.test.tsx, frontend/src/pages/Status.tsx, frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap, frontend/src/pages/__snapshots__/RecurringRunsManager.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap, frontend/src/pages/__snapshots__/Status.test.tsx.snap, frontend/tsconfig.json
Also updates code around `CustomTable customRenderer` to make better use of `FunctionComponent` typings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/772)
=> Updates frontend to Typescript to 3.3.1

.gitignore
As pipeline bootstrapper has been removed in #739 , the gitignore file
and deployment guide should be updated as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/770)
=> Cleanup pipeline bootstrapper

frontend/src/components/UploadPipelineDialog.tsx, frontend/src/components/__snapshots__/UploadPipelineDialog.test.tsx.snap
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/830)
=> Sets 'Choose file' button width to avoid wrap

component_sdk/python/kfp_component/google/ml_engine/_train.py, component_sdk/python/tests/google/ml_engine/test__train.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/837)
=> add container image uris support in train API

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/840)
=> Update change log for v0.1.10 release

components/kubeflow/deployer/src/deploy.sh
While using deployer component to create a TF-Serving service, hit a issue that could not find base path for servable. Checked the details, that's caused by the export directory is hard code to `model_path/export/export` as below in [deploy.sh](https://github.com/kubeflow/pipelines/blob/master/components/kubeflow/deployer/src/deploy.sh#L101).
```
ks param set server modelPath "${MODEL_PATH}/export/export"
```
To let the deployer component to be reusable, we should enhance that because the model export path can be specified during tensorflow/estimator training from the offical [API](https://www.tensorflow.org/api_docs/python/tf/estimator/FinalExporter).
For the TFX taxi sample, the export path is specified `model_path/export/export` in training step, so update …
=> Enhance hard code for export dir in deploy component

.cloudbuild.yaml, .travis.yml, backend/Dockerfile, frontend/README.md, test/sample-test/Dockerfile
The old version had a bug (https://github.com/swagger-api/swagger-codegen/issues/8328) that are causing syntax error when running under python 3.7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/839)
=> Update swagger codegen version

component_sdk/OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/838)
=> Add owner file under component_sdk.

test/presubmit-tests-with-pipeline-deployment.sh
Copied from https://github.com/kubeflow/pipelines/pull/814
The original PR was blocked by github and travis integration bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/847)
=> Move e2e tests to us-east1

components/dataflow/tfdv/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/852)
=> freeze tfdv dependency

sdk/python/kfp/dsl/_container_op.py, sdk/python/kfp/dsl/_pipeline_param.py, sdk/python/tests/dsl/pipeline_param_tests.py
Move the deserialize/matching function of the pipelineparam to the same class of PipelineParam such that future changes are much easier whenever we need to modify the pipelineparam.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/841)
=> extract the pipelineparam deserialize function

frontend/mock-backend/fixed-data.ts, frontend/mock-backend/mock-api-middleware.ts, frontend/mock-backend/mock-recursive-template.yaml, frontend/src/components/Graph.tsx, frontend/src/lib/StaticGraphParser.test.ts, frontend/src/lib/StaticGraphParser.ts
With this change, `StaticGraphParser` no longer breaks when trying to lay out recursive pipelines.
This PR also adds a new mock template: `mock-recursive-template.yaml` which includes multiple instances of recursion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/845)
=> Support rendering recursive static DAGs

test/deploy-kubeflow.sh
We have cluster leaking, serviceaccount leaking, etc in the ml-pipeline-test. 
The reason is that when we push a new commit to the PR while the test is still running, our test infrastructure does not capture the signal and garbage collect the resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/863)
=> add sigint sigterm to the test

test/sample-test/Dockerfile
lack of python3-dev package in the sample test image.
Reason: google/cloud-sdk base image is updated on Feb 26h, 2019.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/871)
=> sample test image build failure

test/check-argo-status.sh, test/deploy-kubeflow.sh, test/deploy-pipeline.sh, test/install-argo.sh, test/postsubmit-tests-with-pipeline-deployment.sh, test/presubmit-tests-with-pipeline-deployment.sh, test/test-prep.sh
set -ex to avoid swallowing the errors silently
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/866)
=> fix bunch of issues in prow test

samples/ibm-samples/ffdl-seldon/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/835)
=> Fixing grammatical errors and references

backend/src/crd/controller/scheduledworkflow/main.go
To support run within a namespace, instead of requesting ClusterRole.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/851)
=> Allow users to specify namespace for Kubernetes informers

component_sdk/python/kfp_component/google/ml_engine/__init__.py, component_sdk/python/kfp_component/google/ml_engine/_client.py, component_sdk/python/kfp_component/google/ml_engine/_common_ops.py, component_sdk/python/kfp_component/google/ml_engine/_create_job.py, component_sdk/python/kfp_component/google/ml_engine/_create_model.py, component_sdk/python/kfp_component/google/ml_engine/_create_version.py, component_sdk/python/kfp_component/google/ml_engine/_delete_version.py, component_sdk/python/kfp_component/google/ml_engine/_deploy.py, component_sdk/python/kfp_component/google/ml_engine/_set_default_version.py, component_sdk/python/tests/google/ml_engine/test__create_version.py, component_sdk/python/tests/google/ml_engine/test__delete_version.py, component_sdk/python/tests/google/ml_engine/test__deploy.py
The PR includes changes:
* Add deploy and set_default commands
* Refactor the model and version name to be the full API path to be consistent with the API representation.
* Dump files in /tmp/kfp/output folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/864)
=> Refactor MLEngine code and add deploy and set_default commands

backend/src/apiserver/storage/BUILD.bazel
caught this by running `bazel build //backend/...` from root
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/883)
=> add missing dependency in bazel BUILD

sdk/python/kfp/components/_dsl_bridge.py, sdk/python/tests/components/test_components.py
Passing the environment variables to ContainerOp
When the DSL bridge code was written, ContainerOp did not support env, so we did not pass it. Now we're adding the passing code.
Added test that chacks that the env variables get to the ContainerOp.
The code is committed on top of https://github.com/kubeflow/pipelines/pull/712 and https://github.com/kubeflow/pipelines/pull/713, so see the last commit only: https://github.com/kubeflow/pipelines/commit/faebaf7dd3b602d90d8c445312c0033f9ad4f735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/877)
=> Passing the environment variables to container op

backend/Dockerfile, developer_guide.md
To make "kubectl logs" work for apiserver, instead of sshing into the apiserver pod.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/859)
=> apiserver glog uses -alsologtostderr

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/890)
=> Added support for default values to Lightweight python components

components/third_party_licenses.csv
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/896)
=> Added license for google-cloud-bigtable

component_sdk/python/kfp_component/google/dataflow/_common_ops.py, component_sdk/python/kfp_component/google/dataflow/_launch_template.py, component_sdk/python/tests/google/dataflow/test__launch_python.py, component_sdk/python/tests/google/dataflow/test__launch_template.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/878)
=> Dump job id  and change output to /tmp/kfp/output

sdk/python/kfp/_client.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/892)
=> Create experiment only if it's not exist.

test/frontend-integration-test/helloworld.spec.js
For some reason, clicking the logs tab immediately after opening the side pane doesn't register the click. This fix pauses for a second before clicking the tab.
Ran locally 10 times in a row successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/904)
=> Deflake frontend e2e test

sdk/python/kfp/dsl/_types.py, sdk/python/tests/dsl/main.py, sdk/python/tests/dsl/type_tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/886)
=> add core types and type checking function

component_sdk/python/kfp_component/google/ml_engine/_deploy.py, component_sdk/python/tests/google/ml_engine/test__deploy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/903)
=> Support customized export TF model folder names.

samples/tfx-oss/TFX Example.ipynb
Adding a notebook for running TFX Example from https://github.com/tensorflow/tfx/tree/master/examples/chicago_taxi_pipeline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/913)
=> Create TFX Example.ipynb

sdk/python/kfp/compiler/compiler.py
/assign @gaoning777  @hongye-sun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/900)
=> Configure artifact name and path separately

sdk/python/kfp/dsl/_pipeline.py
Before the fix it would generate names as follows:
name
name-2
name-2-3
After the fix:
name
name-2
name-3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/923)
=> Fixed small bug in DSL code that generates unique names for ops

sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_dsl_bridge.py, sdk/python/kfp/components/_naming.py
generate_unique_name_conversion_table replaces _make_name_unique_by_adding_index and simplifies code in several places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/716)
=> SDK/Components - Added naming.generate_unique_name_conversion_table 

samples/tfx-oss/README.md, samples/tfx-oss/TFX Example.ipynb
Addressed the issues described here: https://github.com/kubeflow/pipelines/pull/913
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/922)
=> Improved the TFX OSS notebook and README

components/sample/keras/train_classifier/component.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/933)
=> Keras - Train classifier: Changed the types to conform to the chosen type system

components/ibm-components/OWNERS, samples/ibm-samples/OWNERS
Add Tommy(Myself) as the approver for the IBM components and IBM samples.
cc: @animeshsingh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/915)
=> Add Tommy as the approver for the IBM components and samples.

backend/src/apiserver/server/test/malformed_zip2.zip, backend/src/apiserver/server/util.go, backend/src/apiserver/server/util_test.go
Currently the backend detects the pipeline payload type by looking at the file extension.
If we merge the https://github.com/kubeflow/pipelines/pull/855 PR, the DSL compiler will start produce files in ZIP format, but unless the pipeline author changes the code (which they realistically won't do), the file name and extension will remain the same: `.tar.gz`. This will cause the backend to stop accepting those compiled pipelines which will frustrate our users.
This PR replaces format checks based on file name with checks based on file signatures. This fixes the backwards compatibility problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/919)
=> Detecting file format using signature instead of file extension

sdk/python/kfp/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py
Fixes https://github.com/kubeflow/pipelines/issues/941
Also added tests for this case.
The issue was introduced in https://github.com/kubeflow/pipelines/pull/619 https://github.com/kubeflow/pipelines/pull/619/files#r245461691
There is another possible issue when sanitization function converts two different names to same name. This issue will be fixed later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/943)
=> SDK/DSL/Compiler - Fixed compilation when using ContainerOp.after

frontend/mock-backend/model-output/metadata.json, frontend/src/CSSReset.tsx, frontend/src/components/viewers/MarkdownViewer.tsx, frontend/src/components/viewers/__snapshots__/MarkdownViewer.test.tsx.snap
To make it easier to see code blocks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/935)
=> Add code formatting to markdown viewer

components/gcp/dataproc/create_cluster/component.yaml, components/gcp/dataproc/delete_cluster/component.yaml, components/gcp/dataproc/submit_hadoop_job/component.yaml, components/gcp/dataproc/submit_hive_job/component.yaml, components/gcp/dataproc/submit_pig_job/component.yaml, components/gcp/dataproc/submit_pyspark_job/component.yaml, components/gcp/dataproc/submit_spark_job/component.yaml, components/gcp/dataproc/submit_sparksql_job/component.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/956)
=> Add dataproc component yaml files

component_sdk/python/kfp_component/google/dataproc/_submit_hadoop_job.py, component_sdk/python/kfp_component/google/dataproc/_submit_hive_job.py, component_sdk/python/kfp_component/google/dataproc/_submit_pig_job.py, component_sdk/python/kfp_component/google/dataproc/_submit_pyspark_job.py, component_sdk/python/kfp_component/google/dataproc/_submit_spark_job.py, component_sdk/python/kfp_component/google/dataproc/_submit_sparksql_job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/962)
=> Set default values for payload objects in case of empty.

component_sdk/python/kfp_component/google/dataproc/_submit_spark_job.py, components/gcp/dataproc/submit_hadoop_job/component.yaml, components/gcp/dataproc/submit_spark_job/component.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/966)
=> Add missing main_class arg to spark job and set default values.

sdk/python/kfp/az.py, sdk/python/kfp/azure.py, sdk/python/tests/dsl/test_azure_extensions.py
Resolve #953 by adding a helper function to create environment variables based on the azure secret created during setup in https://github.com/kubeflow/kubeflow/pull/2676
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/954)
=> helper fn to add az secrets to container

component_sdk/python/kfp_component/core/_kfp_execution_context.py, component_sdk/python/kfp_component/google/dataproc/_client.py, component_sdk/python/kfp_component/google/dataproc/_submit_job.py, component_sdk/python/tests/google/dataproc/test__submit_job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/967)
=> Fix cancellation bug for dataproc job.

component_sdk/python/kfp_component/google/dataproc/_submit_spark_job.py, components/gcp/dataproc/create_cluster/README.md, components/gcp/dataproc/create_cluster/sample.ipynb, components/gcp/dataproc/delete_cluster/README.md, components/gcp/dataproc/delete_cluster/sample.ipynb, components/gcp/dataproc/submit_hadoop_job/README.md, components/gcp/dataproc/submit_hadoop_job/sample.ipynb, components/gcp/dataproc/submit_hive_job/README.md, components/gcp/dataproc/submit_hive_job/sample.ipynb, components/gcp/dataproc/submit_pig_job/README.md, components/gcp/dataproc/submit_pig_job/sample.ipynb, components/gcp/dataproc/submit_pyspark_job/README.md, components/gcp/dataproc/submit_pyspark_job/sample.ipynb, components/gcp/dataproc/submit_spark_job/README.md, components/gcp/dataproc/submit_spark_job/component.yaml, components/gcp/dataproc/submit_spark_job/sample.ipynb, components/gcp/dataproc/submit_sparksql_job/README.md, components/gcp/dataproc/submit_sparksql_job/sample.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/971)
=> Add documentation and sample notebook for dataproc components.

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_metadata.py, sdk/python/kfp/dsl/_pipeline_param.py, sdk/python/tests/dsl/pipeline_param_tests.py
op_to_template resolve the raw arguments by mapping to the argument_inputs but the argument_inputs lost the type information.
Add back the type information when argument_input pipeline_param is created.
Also, adjust the TypeMeta.from_dict_or_str to convert a json string back to TypeMeta
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/972)
=> Fix sample test failure because of the type information in the pipelineparam

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_metadata.py, sdk/python/kfp/dsl/_pipeline_param.py, sdk/python/tests/dsl/metadata_tests.py, sdk/python/tests/dsl/pipeline_param_tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/975)
=> Add unit tests pipelineparam

component_sdk/python/kfp_component/google/dataproc/_delete_cluster.py, component_sdk/python/tests/google/dataproc/test__delete_cluster.py
This is required to workaround exit handler bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/991)
=> Ignore not found error in delete cluster

component_sdk/python/kfp_component/google/ml_engine/_create_job.py
Fixes: https://github.com/kubeflow/pipelines/issues/944
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/986)
=> Add job_dir.txt as output files of CMLE trainning job.

component_sdk/python/kfp_component/google/dataflow/_client.py, component_sdk/python/kfp_component/google/dataflow/_common_ops.py, component_sdk/python/kfp_component/google/dataflow/_launch_python.py, component_sdk/python/kfp_component/google/dataflow/_launch_template.py, component_sdk/python/tests/google/dataflow/test__launch_python.py, component_sdk/python/tests/google/dataflow/test__launch_template.py
The PR improves dataflow component so that it doesn't need to iterate through all dataflow job list before starting a job.
The fix is important as some beam code doesn't accept job name as command line arg and we cannot reliably depend on the job name to track job status. After the change, the intermediate states are kept in a staging_dir that user provided. The staging_dir is an optional input.
After the PR, I will update component.yaml, document and sample to reflect this interface change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/985)
=> Improve dataflow job to use GCS to keep temp job states.

components/ibm-components/commons/config/component.yaml, components/ibm-components/ffdl/serve/component.yaml, components/ibm-components/ffdl/train/component.yaml, components/ibm-components/watson/deploy/component.yaml, components/ibm-components/watson/manage/monitor_fairness/component.yaml, components/ibm-components/watson/manage/monitor_quality/component.yaml, components/ibm-components/watson/manage/subscribe/component.yaml, components/ibm-components/watson/store/component.yaml, components/ibm-components/watson/train/component.yaml
Add component.yaml to every ibm-components, so users can have a better idea about each component and able to load components with `kfp.components`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/984)
=> Add component.yaml to every ibm-components

sdk/python/kfp/_client.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/968)
=>  Add optional pipeline_id to run_pipeline api

sdk/python/kfp/components/_components.py, sdk/python/tests/components/test_components.py
The component name is now always included in the task factory function docstring.
The name is already used as the function name, but when someone assigns it to the variable, the variable name replaces the original name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/976)
=> Added the component name to the docstring

test/deploy-kubeflow.sh, test/test-prep.sh
this might be introduced by accident during the refactoring
https://github.com/kubeflow/pipelines/pull/613/files#diff-8020d71fc47e179d2ef2b0a1bb13edcbR34
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/994)
=> use pending commit id for cluster and source code name

developer_guide.md
Instruction on building and pushing viewer CRD controller image is missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/981)
=> Add instruction on building viewer CRD controller image

samples/tfx-oss/README.md
In the tfx repo, taxi_pipeline_kubeflow_large.py has been renamed to [taxi_pipeline_kubeflow.py][1]. This commit updates the readme to reflect that change and also fixes a few minor typos.
[1]: https://github.com/tensorflow/tfx/blob/master/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1011)
=> Update TFX Pipeline Example Readme

component_sdk/python/kfp_component/google/ml_engine/_deploy.py, component_sdk/python/tests/google/ml_engine/test__deploy.py
The change includes:
* Expose optional model payload in the interface
* Fix exporter folder searching logic to not depend on hard-coded export dir name.
The new searching logic assumes that user will provide the model_uri is either the direct parent folder of a model file or the base export dir, which contains a list of timestamped sub-directories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1015)
=> Fix hard-coded model export dir name

sdk/python/kfp/components/_components.py
The bug was triggered when description is missing while the name is not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1012)
=> Fixed bug in docstring construction

sdk/python/kfp/compiler/compiler.py
Fixes https://github.com/kubeflow/pipelines/issues/825
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1009)
=> SDK/DSL/Compiler - Fixed handling of empty pipeline name

proxy/Dockerfile, proxy/OWNERS, proxy/attempt-register-vm-on-proxy.sh, proxy/get_proxy_url.py, proxy/get_proxy_url_test.py
This is the initial change to add a [proxy agent](https://github.com/google/inverting-proxy) for a kubeflow pipeline cluster. 
The container should be launched as a K8s Deployment in the same namespace that kubeflow is deployed. 
The agent runner will register to the proxy server and store the metadata in a ConfigMap. In a failover case that the agent die, the new agent should pick up the metadata from the ConfigMap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/988)
=> Add proxy agent runner for kubeflow pipeline

sdk/python/kfp/components/_structures.py
The `metadata` section contains the `annotations` and `labels` dictionaries.
Fixes https://github.com/kubeflow/pipelines/issues/1013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1023)
=> Added the metadata property to ComponentSpec

proxy/attempt-register-vm-on-proxy.sh
This reverts commit fdfde5454ec2b48df327d6a619fa54c1fd4c4dbe.
the commit was checked in by accident.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1042)
=> Revert "Register proxy agent using the service account endpoint"

components/sample/keras/train_classifier/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/934)
=> Keras - Train classifier: Improved the README.md

sdk/python/tests/components/test_components.py
Simplified the type compatibility tests by removing component inputs/outputs and properties that are not required for the tests to work.
Renamed (+split) some of the tests:
`test_type_check_all_with_types` -> `test_type_compatibility_check_for_simple_types` + `test_type_compatibility_check_for_types_with_parameters`
`test_type_check_with_lacking_types` -> `test_type_compatibility_check_when_input_type_is_missing` + `test_type_compatibility_check_when_argument_type_is_missing`
`test_type_check_with_inconsistent_types_property_value` -> `test_fail_type_compatibility_check_when_type_property_value_is_different`
`test_type_check_with_inconsistent_types_type_name` -> `test_fail_type_compatibility_check_when_simple_type_name_is_different` + …
=> SDK/Tests - Simplified type compatibility tests

components/kubeflow/deployer/Dockerfile
fixes: #241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1005)
=> upgrade ks in deployer to fix one block issue

proxy/attempt-register-vm-on-proxy.sh
The proxy server now has a /request-service-account-endpoint that gives an endpoint for a service account. 
This endpoint will work with GKE, in case a VM dies and the agent failover to another VM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1043)
=> Register proxy agent using the service account endpoint

sdk/python/kfp/components/_components.py
Adds support for handling public `gs://` links in `load_component_from_url`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1057)
=> SDK/Components - Handling public GCS URIs in load_component_from_url

components/dataflow/tfma/src/model_analysis.py
This way multiple column names can be passed in a single argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1044)
=> Allow passing comma-delimited column names

frontend/src/Css.tsx, frontend/src/components/Graph.tsx, frontend/src/components/__snapshots__/Graph.test.tsx.snap, frontend/src/lib/WorkflowParser.test.ts, frontend/src/lib/WorkflowParser.ts
See #1051 for discussion.
Fixes #1051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1059)
=> Improve runtime graph exit-handler node name

backend/src/apiserver/server/util.go, backend/src/apiserver/server/util_test.go
Fixes the bug in https://github.com/kubeflow/pipelines/pull/939
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1068)
=> Fixed a bug in tarball handling

.cloudbuild.yaml, .release.cloudbuild.yaml
This can be checked in after https://github.com/kubeflow/pipelines/pull/988 is merged
/hold 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/996)
=> add proxy agent image to cloud builder

frontend/src/components/SideNav.test.tsx, frontend/src/components/SideNav.tsx, frontend/src/components/__snapshots__/SideNav.test.tsx.snap
Set jupyterHubAvailable flag to always false so we don't show the link. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1046)
=> remove jupyter hub link from UI

component_sdk/python/kfp_component/google/bigquery/_query.py, component_sdk/python/tests/google/bigquery/test__query.py
The PR includes changes:
* Removes the code to dump results to local disk, as there is no any requirement for it,
* Dumps dataset_id and table_id so it can be orchestrate in subsequent steps.
* Only set job_config default value if it's not provided. This gives user the chance to change it as needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1062)
=> Allow bigquery component to export to table only

test/deploy-kubeflow.sh
/assign @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/995)
=> Pin specific version of kubeflow instead of using master

backend/src/cmd/ml/cmd/run.go, frontend/src/Css.tsx, frontend/src/apis/run/api.ts, frontend/src/components/Banner.tsx, frontend/src/icons/statusTerminated.tsx, frontend/src/lib/Buttons.ts, frontend/src/lib/WorkflowParser.ts, frontend/src/pages/Page.tsx, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/Status.test.tsx, frontend/src/pages/Status.tsx, frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap, frontend/src/pages/__snapshots__/Archive.test.tsx.snap, frontend/src/pages/__snapshots__/Status.test.tsx.snap, test/frontend-integration-test/helloworld.spec.js, test/frontend-integration-test/tensorboard-example.spec.js
Adds a `Terminate` button to the run details page, allowing users to request that the pipeline execution be stopped:
This action is irreversible and the user is asked to confirm before the command is issued:
Afterward, the `Terminate` button is disabled, and a warning banner is shown explaining that the run was terminated. The step that was executing when the pipeline terminated gets a special status icon indicating that it was stopped:
If there were multiple steps running when the pipeline was terminated, each will show the stopped icon:
The list pages will show terminated runs as `Failed`, and will not indicate that they are terminated due to #1040
--- …
=> Add run termination controls to ui

frontend/src/components/SideNav.tsx, frontend/src/components/__snapshots__/SideNav.test.tsx.snap
Spartakus is now run by Kubeflow core, so it doesn't make sense for Kubeflow Pipelines to include a link to its documentation; the main Kubeflow UI will handle that.
Fixes: #1073 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1074)
=> Removes link to Kubeflow privacy links as KFP no longer runs Spartakus

sdk/python/kfp/dsl/_pipeline_param.py
Minor fix: On the dict case of `extract_pipelineparams_from_any()`, the `return` statement is indented.
As a consequence, it is inside the `for` loop and results in function returning just after examining the first value of the dictionary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1076)
=> Fix wrong indentation in extract_pipelineparams_from_any()

.travis.yml, components/test_load_all_components.sh
This ensures that broken definitions are not submitted. (And that the SDK changes do not break existing components.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1045)
=> Test loading all component.yaml definitions

components/gcp/ml_engine/deploy/README.md, components/gcp/ml_engine/deploy/component.yaml
Fixed typos / spelling errors
Added a link to Cloud ML Engine runtime versions
Made some formatting (of required / optional) more consistent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1038)
=> Fixed some typos

components/ibm-components/ffdl/serve/component.yaml, components/ibm-components/ffdl/train/component.yaml
Adding metadata initial description for components targeting ibm opensource
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1071)
=> metadata for ibm components targeting opensource

components/ibm-components/watson/deploy/component.yaml, components/ibm-components/watson/manage/monitor_fairness/component.yaml, components/ibm-components/watson/manage/monitor_quality/component.yaml, components/ibm-components/watson/manage/subscribe/component.yaml, components/ibm-components/watson/store/component.yaml, components/ibm-components/watson/train/component.yaml
Metadata tags for watson components
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1072)
=> metadata tag for watson components

components/dataflow/predict/component.yaml, components/dataflow/tfdv/component.yaml, components/dataflow/tfma/component.yaml, components/dataflow/tft/component.yaml, components/kubeflow/deployer/component.yaml, components/kubeflow/dnntrainer/component.yaml, components/kubeflow/katib-launcher/component.yaml, components/local/confusion_matrix/component.yaml, components/local/roc/component.yaml, samples/kubeflow-tf/kubeflow-training-classification.py, samples/xgboost-spark/xgboost-training-cm.py
Added definitions for the following components:
`dataflow/predict`
`dataflow/tfdv`
`dataflow/tft`
`dataflow/tma`
`kubeflow/deployer`
`kubeflow/dnntrainer`
`kubeflow/katib-launcher`
`local/confusion_matrix`
`local/roc`
Also, the kubeflow-training-classification sample now loads the components from component files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/539)
=> Added component definition files for our components

sdk/python/kfp/compiler/_op_to_template.py
Restoring the https://github.com/kubeflow/pipelines/pull/900 change that was overwritten by https://github.com/kubeflow/pipelines/pull/879
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1067)
=> SDK - Configure artifact name and path separately (again)

components/ibm-components/commons/config/component.yaml, components/ibm-components/commons/config/src/config.py
Fixed the following issues:
* Checking that every command finishes successfully (non-zero return code)
* Fixed the path for the secret_name output (the program was producing variable paths different from the path in component.yaml)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1027)
=> Improved the "IBM - Create kubernetes secret" component

sdk/python/kfp/compiler/_k8s_helper.py
It looks like this `obj` -> `k8s_obj` rename was missed during a refactor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1088)
=> SDK - Fix obj name in K8s -> json conversion util

components/dataflow/tfma/component.yaml, samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb, samples/tfx/taxi-cab-classification-pipeline.py
From a277f87ea1d4707bf860d080d06639b7caf9a1cf to 2c2445df83fa879387a200747cc20f72a7ee9727
=> Rolling back TFMA image

test/sample-test/run_kubeflow_test.py, test/sample-test/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1096)
=> Fixed Kubeflow sample test

components/kubeflow/deployer/Dockerfile, components/kubeflow/deployer/src/deploy.sh
fixes: #1102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1103)
=> uprade tf-serving in deployer component

sdk/python/kfp/compiler/_op_to_template.py
This change makes the order of output artifacts stable in Python 3.5.
The sample test seems to be relying on the artifact ordering (it tries to read the first artifact without looking at the name).
With this change the order is always the preserved and stable.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1097)
=> Stabilized the artifact ordering during the compilation

sdk/python/kfp/components/_dsl_bridge.py, sdk/python/tests/components/test_components.py
Currently the annotations and labels are not passed from component to the `ContainerOp`. This PR fixes that.
Fixes https://github.com/kubeflow/pipelines/issues/1013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1077)
=> Passing the annotations and labels to the ContainerOp

components/kubeflow/katib-launcher/Dockerfile, components/kubeflow/katib-launcher/OWNERS, components/kubeflow/katib-launcher/component.yaml, components/kubeflow/katib-launcher/kubeflow_katib_launcher_op.py, components/kubeflow/katib-launcher/src/launch_study_job.py
1. sync up since katib directory org changed
2. add option deleteafterdone
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1118)
=> update katib laucher

backend/src/apiserver/model/run.go
Without setting to 0, the finished at field could be null if the argo workflow is already evicted from the cluster. 
This result in errors parsing the table. 
Alternatively we can use sql.NullInt64 type to parse the sql but that's less elegant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1140)
=> Set run model default timestamp to 0

backend/src/apiserver/config/sample_config.json
Removed the "Basic - Immediate Value" sample since it does not really serve any purpose - other samples also feature hard-coded arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1126)
=> Updated descriptions of pre-installed samples

frontend/src/apis/run/api.ts, frontend/src/lib/Utils.test.ts, frontend/src/lib/Utils.ts, frontend/src/pages/ExperimentDetails.test.tsx, frontend/src/pages/ExperimentDetails.tsx, frontend/src/pages/ExperimentList.test.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/RunList.test.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Updates frontend run API to match backend changes introduced in #1122 
From the ExperimentDetails and ExperimentList pages, calls to getRun and
getExperiment are removed.
From the RunList page, calls to getRun are removed.
Related to #149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1144)
=> Removes unnecessary API calls

samples/basic/exit_handler.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1109)
=> Updated the "Basic - Exit handler" sample

samples/basic/retry.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1111)
=> Updated the "Basic - Retry" sample

samples/notebooks/DSL Static Type Checking.ipynb, samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb, samples/notebooks/Lightweight Python components - basics.ipynb, samples/tfx-oss/TFX Example.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1117)
=> Updated the package version in the notebooks

samples/notebooks/DSL Static Type Checking.ipynb, test/sample-test/check_notebook_results.py, test/sample-test/run_test.sh, test/sample_test_v2.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1129)
=> add type checking sample to sample tests

sdk/python/setup.py
Fixes #1134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1137)
=> Allow later versions of dependencies to be used with Python KFP package.

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/compiler/main.py, sdk/python/kfp/dsl/_metadata.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/tests/dsl/pipeline_tests.py
Moved metadata-related code to _metadata.
`Pipeline.get_pipeline_functions` now returns the list of pipeline functions.
Now the pipeline name, description and other metadata is passed directly with the pipeline instead of a using global variables.
(The global pipeline list is still used by the command-line compiler.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1120)
=> SDK - Simplified the @pipeline decorator

backend/src/apiserver/filter/BUILD.bazel, backend/src/apiserver/filter/filter.go, backend/src/apiserver/filter/filter_test.go, backend/src/apiserver/list/list.go, backend/src/apiserver/list/list_test.go, backend/src/apiserver/storage/experiment_store_test.go
Fixes #1149 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1153)
=> Add filter to next page token so it applies to subsequently requested pages

sdk/python/kfp/aws.py, sdk/python/tests/dsl/aws_extensions_tests.py
Hi Team,
Add aws secrets in kfp. 
1. I notice if I run `sdk/python/tests/run_tests.sh`, my tests are not detected in the results?
2. Another thing is should I put this unit test file under `tests` folder directly? right now it's under `tests/dsl`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1133)
=> Add helper to easily add aws secrets

components/kubeflow/deployer/component.yaml, components/kubeflow/deployer/src/deploy.sh
Expose the "service-type" parameter, then user can define it as "ClusterIP" or "NodePort"
I check the code of "kubeflow/kubeflow/tf-serving/", that model has already support that in v0.4.0, so we just need expose it, it could work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1136)
=> Expose service-type as parameter

samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb, sdk/python/kfp/compiler/_k8s_helper.py, sdk/python/setup.py, test/sample-test/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1159)
=> new kubernetes packages contain breaking change, thus fixing the version in the sample test image

.cloudbuild.yaml
https://github.com/kubeflow/pipelines/pull/1124 deleted the image builds because resnet now uses the gcp components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1165)
=> delete the resnet image items

components/OWNERS
Have been reviewing many components and sample related PRs, and feel pretty confident addressing them
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1161)
=> Adding myself as a reviewer for components

backend/src/apiserver/client_manager.go, backend/src/apiserver/main.go, backend/src/apiserver/model/BUILD.bazel, backend/src/apiserver/model/default_experiment.go, backend/src/apiserver/resource/client_manager_fake.go, backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/server/run_server_test.go, backend/src/apiserver/storage/BUILD.bazel, backend/src/apiserver/storage/db_default_experiment_store.go, backend/src/apiserver/storage/db_fake.go, backend/src/apiserver/storage/db_status_store.go, backend/src/apiserver/storage/db_status_store_test.go, backend/src/apiserver/storage/default_experiment_store.go, backend/src/apiserver/storage/default_experiment_store_test.go, backend/src/apiserver/storage/object_store_util.go, backend/src/common/util/error.go, backend/test/initialization/BUILD.bazel, backend/test/initialization/flags.go, backend/test/initialization/initialization_test.go, backend/test/integration/experiment_api_test.go, test/api-integration-test/run_test.sh, test/e2e_test_gke_v2.yaml, test/initialization-test/Dockerfile, test/initialization-test/OWNERS, test/initialization-test/run_test.sh
This experiment is named `Default` and is used whenever a `CreateRun` request is received without specifying a containing experiment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1089)
=> Creates a default experiment at API server set up time

sdk/python/kfp/dsl/_component.py, sdk/python/kfp/dsl/_metadata.py
Moved metadata-related code to _metadata.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1166)
=> SDK - Simplified the @component decorator

samples/arena-samples/README.md, samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py, samples/kubeflow-tf/kubeflow-training-classification.py, samples/resnet-cmle/resnet-train-pipeline.py, samples/xgboost-spark/xgboost-training-cm.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1176)
=> release 0.1.17: update yaml tag in samples

sdk/python/kfp/_client.py
In the current implementation of `Client._is_ipython`, the only check performed is a simple attempted [import of the `IPython` package](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/_client.py#L85-L88
). However, this will fail in the case that the user (or container) has IPython installed, but the command is being executed from the normal Python interpreter.
This PR adds an extra call to `IPython.get_ipython`, which returns an instance of the running IPython kernel if any, and otherwise `None`. By raising an `ImportError` if `get_ipython` returns `None`, the existing logic kicks in and `Client._is_ipython` will return `False` as expected, whether IPython happens to be installed or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Make Python Client robust to existing IPython installations

sdk/python/kfp/compiler/main.py, sdk/python/kfp/dsl/_pipeline.py
This list was only used by the command-line compiler.
The command-line compiler can still collect the created pipelines by registering a handler function in `_pipeline_decorator_handlers`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1167)
=> SDK - Got rid of the global variable collecting all created pipelines

samples/basic/condition.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1108)
=> Updated the "Basic - Conditional" sample

backend/src/apiserver/metadata/metadata_store.go, backend/src/apiserver/metadata/metadata_store_test.go
Previously we assume the fields 'artifact_type' and 'artifact' always
exist. This change ensures we guard against the case when one or both of
these required fields aren't present. In those cases, referencing the missing field in the parse JSON map will result in a nil-pointer dereference error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1192)
=> Return error when ml-metadata serialized format does not match expected format.

frontend/src/lib/Buttons.ts, frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/PipelineList.tsx, frontend/src/pages/RecurringRunDetails.tsx
Also redirects after deleting pipeline from pipeline details page.
Fixes #1181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1185)
=> Fixes deletion of recurring runs

frontend/src/components/CustomTable.tsx, frontend/src/components/__snapshots__/CustomTable.test.tsx.snap, frontend/src/lib/Buttons.ts, frontend/src/pages/AllRunsList.tsx, frontend/src/pages/ExperimentList.test.tsx, frontend/src/pages/ExperimentList.tsx, frontend/src/pages/PipelineDetails.test.tsx, frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap, test/frontend-integration-test/helloworld.spec.js, test/frontend-integration-test/run_test.sh
Following #1089, this PR adds `Create run` button to Experiment/All run list pages.
Also updates the frontend integration test to include creating a run without selecting an experiment, and filtering the experiment list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1175)
=> Allow creating runs without experiments

component_sdk/python/requirements.txt, sdk/python/setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1201)
=> Fix package version conflict

sdk/python/tests/compiler/component_builder_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1169)
=> SDK/Tests - Properly closing tar files opened for writing

components/ibm-components/ffdl/train/src/train.py, components/kubeflow/katib-launcher/src/launch_study_job.py, components/kubeflow/launcher/src/launch_tf_job.py, components/kubeflow/launcher/test/test_launcher.py, sdk/python/kfp/_client.py, sdk/python/kfp/components/_yaml_utils.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/component_builder_test.py
This improves security and gets rid of security warnings.
See https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1170)
=> SDK - Replaced insecure yaml.load with yaml.safe_load

sdk/python/kfp/components/_structures.py
It has never been used and `ComponentSpec.metadata.annotations['source']` is a better place for such metadata.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1119)
=> SDK - Removed SourceSpec structure

sdk/python/kfp/components/_dsl_bridge.py, sdk/python/kfp/components/_structures.py
Sometimes it's useful to pass around the structure that only defines the interface of a component. 
Also improved the error message when trying to convert tasks to ContainerOp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1188)
=> SDK - Made ComponentSpec.implementation field optional

backend/src/agent/persistence/client/pipeline_client.go, backend/src/agent/persistence/main.go
In some clusters, service addr may not be formatted as "%s.%s.svc.cluster.local:%s". We need to a more flexible way to handle it. I checked approach in ml-pipeline-ui, which just make the entire FQDN configurable. But this change would bring incompatibility, as previously users may only config the service name while now need full name to make it work.
@IronPan thoughts?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/867)
=> Allow more flexible way to config the api server addr in persistence agent

components/ibm-components/watson/deploy/component.yaml, components/ibm-components/watson/manage/monitor_fairness/component.yaml, components/ibm-components/watson/manage/monitor_quality/component.yaml, components/ibm-components/watson/manage/subscribe/component.yaml, components/ibm-components/watson/store/component.yaml, components/ibm-components/watson/train/component.yaml, samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py
During run of pipelines, only first couple of words from comp names are displayed, and every step looks similar. So moving the verb ahead tells what each comp is doing in visual part
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1202)
=> Moving the component 'verbs' ahead of 'product/project'

samples/ibm-samples/watson/watson_train_serve_pipeline.py
Base it on components.yaml, and expose the parameters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1227)
=> modernize-wml-pipeline

backend/api/swagger/pipeline.upload.swagger.json
The UploadPipeline route is unique in that it's uses `multipart/form-data` passing style. 
This PR moves that specification from global setting to the route level. This makes it easier to combine this route with other routes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1225)
=> Swagger - Specifying content types on the route level

test/sample-test/run_kubeflow_test.py, test/sample-test/run_xgboost_test.py
The sample tests no longer depend on particular  file names inside the archive. Now they only depend on the artifact name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1196)
=> Testing/Sample - Made checking confusion matrix data more robust

samples/notebooks/quickstart.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1232)
=> clean up quickstart sample a bit

sdk/python/kfp/dsl/_container_op.py
Fixes https://github.com/kubeflow/pipelines/issues/1121
When you pass non-string arguments to the ContainerOp.command, they're passed as such to the resulting Argo workflow which then cannot be loaded in back-end due to the item types.
This PR ensures the items are converted to string.
We should probably also stop supporting non-list command type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1197)
=> SDK - Fixed the non-string items in the command-line arguments

components/ibm-components/commons/config/component.yaml, components/ibm-components/ffdl/serve/component.yaml, components/ibm-components/ffdl/train/component.yaml, samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py
Moving the verb in comp names before because of UI real estate, plus removing the space in metadata label value as Jupyter notebook driven pipelines are complaining about the space
metadata.labels: Invalid value: "Open Source": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1239)
=> Fixing comp names

components/ibm-components/commons/config/src/config.py, components/ibm-components/ffdl/serve/component.yaml, components/ibm-components/ffdl/train/component.yaml, components/ibm-components/watson/deploy/component.yaml, components/ibm-components/watson/manage/monitor_fairness/component.yaml, components/ibm-components/watson/manage/monitor_quality/component.yaml, components/ibm-components/watson/manage/subscribe/component.yaml, components/ibm-components/watson/store/component.yaml, components/ibm-components/watson/train/component.yaml, components/ibm-components/watson/train/src/wml-train.py, samples/ibm-samples/watson/watson_train_serve_pipeline.py
This PR contains the following fixes:
- In config component, add exception to `kubectl delete` when old secret is not present.
- Remove spaces in `metadata.labels` since Argo can't take labels with white space.
- Fix Watson train to not check on hard coded `created` text. Also parameterize author email field.
- Update Watson pipeline arguments to map with the correct component parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1246)
=> Fix Watson pipeline example 

backend/src/apiserver/main.go, backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go, backend/src/apiserver/storage/db_status_store.go, backend/src/apiserver/storage/default_experiment_store.go, backend/src/apiserver/storage/default_experiment_store_test.go, backend/src/apiserver/storage/experiment_store.go, backend/src/apiserver/storage/job_store.go, backend/src/apiserver/storage/pipeline_store.go, backend/src/apiserver/storage/run_store.go, test/frontend-integration-test/helloworld.spec.js
With this change, if the delete experiment API is called on the default
experiment, then the ID will also be removed from the default_experiments
table.
Additionally, if the default experiment doesn't exist and a new run is
created without an experiment, a new default experiment will be created,
and the run will be placed within this experiment.
This PR also fixes an issue in some of the backend store files where the connection to the database was not being closed. This wasn't much of an issue in production, but it appeared that in the test environment, only one connection was allowed, so failing to close the connection would cause subsequent queries to fail, claiming that the table no longer existed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Clear default exp table on delete and create default exp on run create if none exists

sdk/python/kfp/compiler/_component_builder.py, sdk/python/kfp/compiler/_k8s_helper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1247)
=> display kaniko log if failed

backend/api/build_kfp_server_api_python_package.sh, sdk/python/build.sh, sdk/python/build_kfp_server_api_package.sh, sdk/python/kfp/_client.py, sdk/python/setup.py
Separating the generated API client brings many benefits.
* It's much easier to build the main package - No need to install Java, download swagger-generator, and run the script that cobbles together a package in style of Frankenstein's monster. 
* No you can just run `python setup.py sdist` to build or `python setup.py install` to install the package
* This change is required for automatic API documentation generation services that need a package source in easy to install/use form
* This change also simplifies the `Client` code: Instead of having 5 separate but identical configuration classes and 5 separate but identical API client classes it now only has 1. …
=> SDK - Separated the generated api client package

components/arena/python/arena/_arena_distributed_tf_op.py, components/arena/python/arena/_arena_mpi_op.py, components/arena/python/arena/_arena_standalone_op.py, components/arena/python/build.sh, samples/arena-samples/standalonejob/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1251)
=> Update arena SDK version

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/basic.yaml, sdk/python/tests/compiler/testdata/coin.yaml, sdk/python/tests/compiler/testdata/compose.yaml, sdk/python/tests/compiler/testdata/default_value.yaml, sdk/python/tests/compiler/testdata/imagepullsecret.yaml, sdk/python/tests/compiler/testdata/immediate_value.yaml, sdk/python/tests/compiler/testdata/pipelineparams.yaml, sdk/python/tests/compiler/testdata/recursive_do_while.yaml, sdk/python/tests/compiler/testdata/recursive_while.yaml, sdk/python/tests/compiler/testdata/resourceop_basic.yaml, sdk/python/tests/compiler/testdata/retry.yaml, sdk/python/tests/compiler/testdata/sidecar.yaml, sdk/python/tests/compiler/testdata/volume.yaml, sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml, sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml, sdk/python/tests/compiler/testdata/volumeop_basic.yaml, sdk/python/tests/compiler/testdata/volumeop_dag.yaml, sdk/python/tests/compiler/testdata/volumeop_parallel.yaml, sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1260)
=> Marking the UI-metadata and Metrics artifacts as optional

sdk/python/kfp/notebook/_magic.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1215)
=> SDK - Preventing errors when importing kfp.notebook

frontend/src/components/viewers/PagedTable.test.tsx, frontend/src/components/viewers/PagedTable.tsx, frontend/src/components/viewers/__snapshots__/PagedTable.test.tsx.snap
Also moves functions declared within `PagedTable.tsx` file into the class itself, and exposes header row and pagination controls when table is small.
Bug fix change is just line 147: `let order = SortOrder.ASC;`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1261)
=> Properly alternate sorting in PagedTable between ascending and descending

test/postsubmit-tests-with-pipeline-deployment.sh, test/sample-test/run_test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1267)
=> update the image in the samples to use the new component images

frontend/src/index.tsx
This will prevent the pages from appearing gray when viewed within the
iframe of the greater Kubeflow console.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1281)
=> Sets the background color for KFP pages

sdk/python/kfp/components/_component_store.py, sdk/python/kfp/components/_components.py
Currently this information is not passed through and is lost after loading.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1090)
=> Retaining the component url, digest or tag when loading

frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap, test/frontend-integration-test/helloworld.spec.js
Changes are mainly around lines 272 and 445 of `NewRun.tsx`.
Other changes, are primarily cleanup and tests.
Fixes #1217
Examples of the toggle:
One-off:
Recurring:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1274)
=> Adds a toggle between one-off and recurring runs to NewRun page

components/arena/docker/arena_launcher.py, components/arena/python/arena/_arena_distributed_tf_op.py, components/arena/python/arena/_arena_mpi_op.py, components/arena/python/arena/_arena_standalone_op.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1268)
=> make pending timeout customizable

frontend/server/server.ts, frontend/src/lib/WorkflowParser.test.ts, frontend/src/lib/WorkflowParser.ts
I was working on more storage options for artifacts. Original idea was to add local and s3 for no-prem and aws users. Notice local is a little bit tricky because pipeline-UI can not access PVC actively.  After some discussion, we think ViewerCRD or minio would be choice for on-prem users.
S3 parts, I notice @DmitryBe has some work https://github.com/kubeflow/pipelines/pull/767.  I can not reach out to him and wait for few days. I borrow some code snippet and reuse minio client in this PR. 
I will have some corresponding changes in kubeflow/kubeflow later to mount AWS credential to ui pod.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1278)
=> Frontend - Add support for artifacts stored in S3

components/release.sh
This PR builds on top of https://github.com/kubeflow/pipelines/pull/1172 to update all component references in samples after updating the images in the components.
Now both changes are done automatically and in the same release PR.
The script now does the following:
1. Checks out the clean repo
2. Updates container image versions
3. Commits the container image update
4. Updates component versions
5. Commits the component version update
6. Then it optionally pushes the changes to a new release branch
7. Opens the web-browser with a pull request page ready
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1283)
=> Components - Updating component versions in samples during release

components/aws/athena/Dockerfile, components/aws/athena/query/component.yaml, components/aws/athena/query/src/query.py, components/aws/emr/Dockerfile, components/aws/emr/common/_utils.py, components/aws/emr/create_cluster/component.yaml, components/aws/emr/create_cluster/src/create_cluster.py, components/aws/emr/delete_cluster/component.yaml, components/aws/emr/delete_cluster/src/delete_cluster.py, components/aws/emr/submit_pyspark_job/component.yaml, components/aws/emr/submit_pyspark_job/src/submit_pyspark_job.py, components/aws/emr/submit_spark_job/component.yaml, components/aws/emr/submit_spark_job/src/submit_spark_job.py, samples/aws-samples/titanic-survival-prediction/README.md, samples/aws-samples/titanic-survival-prediction/titanic-survival-prediction.py
1. Add AWS EMR and Athena components
2. Add example to use EMR to run Spark pipelines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1286)
=> Add AWS EMR and Athena components

sdk/python/kfp/compiler/_component_builder.py, sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_python_op.py, sdk/python/kfp/components/modelbase.py, sdk/python/tests/components/test_graph_components.py, sdk/python/tests/components/test_structure_model_base.py
This is a purely renaming PR.
`to_dict` is more common method name and these methods are already consuming/producing dicts anyway.
P.S. I'm not renaming some other stand-alone functions in that file since they're used with non-dict structures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1290)
=> SDK - Renamed ModelBase.from_struct/to_struct to from_dict/to_dict

components/nuclio/README.md, components/nuclio/delete/component.yaml, components/nuclio/deploy/component.yaml, components/nuclio/invoker/component.yaml
add component to deploy & customize nuclio functions from code/notebook/zip/git, delete functions, and invoke running functions.
see: README.md and https://github.com/nuclio/nuclio-jupyter and https://github.com/nuclio/nuclio
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1295)
=> add nuclio components (to build/deploy, delete, invoke functions)

sdk/python/tests/components/test_python_op.py
Added process error code check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1291)
=> SDK - Failing faster in python_op tests

samples/notebooks/quickstart.ipynb
without this, the command `mkdir tmp/pipelines` fails and so does a later python cell that tries to use that directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1299)
=> Add -p to mkdir in quickstart

components/local/confusion_matrix/src/confusion_matrix.py, components/local/roc/src/roc.py
Add s3 and minio storage options in confusion_matrix and roc components.
Frontend s3 support has been added in this PR https://github.com/kubeflow/pipelines/pull/1278
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1285)
=> Make confusion_matrix and roc generic

WORKSPACE, backend/src/apiserver/resource/resource_manager.go, go.mod, go.sum
This PR is implementing part of the https://github.com/kubeflow/pipelines/issues/1250 plan.
Problem:
DSL-compiler has been auto-adding two artifacts to all pipeline tasks (including ones that do not actually outputs those artifacts). All out existing compiled pipelines have this problem.
Argo 2.3 makes missing output artifacts a reason for task failure.
The workaround for the existing pipelines is for backend to mark those two artifacts as optional.
P.S.
The `optional` property is only available starting with Argo 2.3, so I'm bumping the Argo version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1289)
=> Backend - Marking auto-added artifacts as optional

sdk/python/kfp/dsl/_pipeline_param.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/param_substitutions.py, sdk/python/tests/compiler/testdata/param_substitutions.yaml
If a `PipelineParam` was found twice in an Op, e.g. in `arguments` and in `volumes`, having different patterns (`None` vs anything) messed the `inputs` attribute (which uses `set()` on the extracted `PipelineParam`s).
The different `pattern`s may occur since `arguments` (as well as `command`) gets the `str()` representation of the `PipelineParam` **before** it gets sanitized.
I chose to generate a `pattern` in the constructor, if one is not provided.
Otherwise, we could use the `pattern` attribute in `__hash__` method, but it messes tests because it generally leads to duplicate entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1300)
=> Fix PipelineParam pattern bug

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_pipeline.py
* Remove the separated dictionaries for ContainerOps and ResourceOps
* Fix the sanitization performed by the compiler to iterate through ops
dict and do type-check for the special fields file_outputs and
attribute_outputs
~I found a bug which has to do with `PipelineParam` hashing.
`__hash__` method of `PipelineParam` now uses `pattern` attribute too.
If a `PipelineParam` was found twice in an Op, e.g. in `arguments` and in `volumes`, having different patterns messed the `inputs` attribute (which uses `set()` on the extracted `PipelineParam`s).~
I will open a separate PR for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1298)
=> Remove cops and rops pipeline attributes

backend/Dockerfile.persistenceagent
this config allow specifying what namespace the persistent agent listen to
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1308)
=> expose namespace config for persistent agent

frontend/server/server.ts, frontend/src/lib/Apis.ts, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Example UI:
Clicking on the link will take the user to the Stackdriver log viewer in GCP with a preset query to get just the logs for the relevant pod.
The changes in `RunDetails.test.tsx` are mostly refactoring/moving. Three new tests are: 
- `shows warning banner and link to Stackdriver in logs area if fetching logs failed and cluster is in GKE`
- `shows error banner atop logs area if fetching logs failed and getProjectId fails`
- `shows error banner atop logs area if fetching logs failed and getClusterName fails`
Related to #844 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1310)
=> Shows link to Stackdriver logs if logs retrieval fails and cluster is running in GKE

test/install-argo.sh, test/postsubmit-tests-with-pipeline-deployment.sh, test/presubmit-tests-with-pipeline-deployment.sh
Currently we have two Argo installation in out test clusters with two controllers. The controllers have different configurations and are conflicting.
This PR cleans up one of the Argo installations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1311)
=> Testing - Clean up the Argo controller that was used to build images

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/basic.yaml, sdk/python/tests/compiler/testdata/coin.yaml, sdk/python/tests/compiler/testdata/compose.yaml, sdk/python/tests/compiler/testdata/default_value.yaml, sdk/python/tests/compiler/testdata/imagepullsecret.yaml, sdk/python/tests/compiler/testdata/immediate_value.yaml, sdk/python/tests/compiler/testdata/param_substitutions.yaml, sdk/python/tests/compiler/testdata/pipelineparams.yaml, sdk/python/tests/compiler/testdata/recursive_do_while.yaml, sdk/python/tests/compiler/testdata/recursive_while.yaml, sdk/python/tests/compiler/testdata/resourceop_basic.yaml, sdk/python/tests/compiler/testdata/retry.yaml, sdk/python/tests/compiler/testdata/sidecar.yaml, sdk/python/tests/compiler/testdata/tolerations.yaml, sdk/python/tests/compiler/testdata/volume.yaml, sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml, sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml, sdk/python/tests/compiler/testdata/volumeop_basic.yaml, sdk/python/tests/compiler/testdata/volumeop_dag.yaml, sdk/python/tests/compiler/testdata/volumeop_parallel.yaml, sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
We should follow Argo's prefferred way to configure the artifact storage: https://github.com/argoproj/argo/blob/master/ARTIFACT_REPO.md#configure-the-default-artifact-repository and use a cluster-local configMap. This way the pipelines remain clean and portable: https://github.com/argoproj/argo/blob/master/examples/artifact-passing.yaml
Kubeflow deployer has already been pre-installing the configMap for several months: https://github.com/kubeflow/kubeflow/pull/2238
**This PR adds a breaking change.**
The pipelines compiled by this SDK will fail on KFP backend < v0.1.9. The issue can be easily fixed by adding the default artifact repository configuration configMap as described in https://github.com/argoproj/argo/blob/master/ARTIFACT_REPO.md#configure-the-default-artifact-repository (**You …
=> SDK - Stopped hard-coding artifact storage configuration in the pipeline packages

sdk/python/kfp/dsl/_container_op.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1314)
=> Fix typo in ContainerOp contructor's help string

sdk/python/kfp/gcp.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1306)
=> Add dsl support for preemptible vm/gpus

component_sdk/python/patches/http.patch, components/gcp/container/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1317)
=> add patch for metric collection

frontend/server/server.ts, manifests/namespaced-install.yaml, manifests/namespaced-install/kustomization.yaml, manifests/namespaced-install/ml-pipeline-ui-deployment-patch.yaml
I am deploying multiple kubeflow pipelines in a multi-cloud environment (AWS and Azure), and I am using minio-gateway as a proxy to Azure blob storage. 
I need to have configurable minio endpoint to support multiple kubeflow pipelines deployment. Currently, it is hard-coded to the `kubeflow` namespace. 
#1064 is part of my PR to make minio endpoint configurable from the kfp sdk.
#1319
This PR exposes the minio parameters as environment variables which allows me to deploy kubeflow pipelines to other namespaces.
- MINIO_ENDPOINT is composed from MINIO_HOST and MINIO_NAMESPACE so that we can do the following in the deployment yaml.
```yaml
env:
- name: MINIO_NAMESPACE
valueFrom:
fieldRef:
fieldPath: "metadata.namespace"
```
--- …
=> [Frontend] minio client in API server can be configured with environment variables

sdk/python/kfp/components/_dsl_bridge.py, sdk/python/tests/components/test_components.py, sdk/python/tests/dsl/aws_extensions_tests.py, sdk/python/tests/dsl/component_tests.py, sdk/python/tests/dsl/container_op_tests.py, sdk/python/tests/dsl/test_azure_extensions.py
`dsl.Pipeline` is a private compiler context object that should not be used outside the compiler (and compiler tests).
This PR removes most of the unnecessary uses of `dsl.Pipeline`.
Please turn on "Hide whitespace changes" in diff settings when looking at the diff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1229)
=> SDK - Removing unneeded uses of dsl.Pipeline

frontend/Dockerfile
the `npm run postinstall` on line 19 already installs the npm packages within the frontend/server/ dir
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1332)
=> Removes redundant npm install from FE Dockerfile

sdk/python/kfp/dsl/_pipeline.py
The explicit pipeline name and description are not really necessary since the name can be taken from the pipeline function name and the description - from the docstring.
The PR reduces the amount of boilerplate the pipeline creator needs to write to make a valid pipeline (that the command-line tools will recognize).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1335)
=> SDK - Made description and name parameters optional in the @pipeline decorator

frontend/src/atoms/Metric.tsx, frontend/src/components/Metric.test.tsx, frontend/src/components/Metric.tsx, frontend/src/components/__snapshots__/Metric.test.tsx.snap, frontend/src/lib/CompareUtils.test.ts, frontend/src/lib/CompareUtils.ts, frontend/src/lib/MetricUtils.test.ts, frontend/src/lib/MetricUtils.ts, frontend/src/lib/RunUtils.ts, frontend/src/pages/Compare.test.tsx, frontend/src/pages/Compare.tsx, frontend/src/pages/RunList.test.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/Compare.test.tsx.snap, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
The `CompareTable` is not sortable, which is not ideal for metrics. However, this isn't much of a problem if the number of runs being compared is small.
If we do want a sortable table, we'll have to decide if we want to build one that can sort along rows (rather than columns), or if we want to transpose the parameters and metrics tables on the compare page.
Fixes: #468
Initial table will look like this:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1284)
=> Adds metrics table to Compare page, creates Metric component

sdk/python/kfp/dsl/_container_op.py
Instead of doing
```
op = dsl.ContainerOp(...).after(step1).after(step2)....
```
make the following possible
```
op = dsl.ContainerOp(...).after(step1, step2, ...)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1346)
=> SDK/Compiler: Fix Ops after() method to handle multiple arguments

frontend/src/components/DetailsTable.test.tsx, frontend/src/components/DetailsTable.tsx, frontend/src/components/__snapshots__/DetailsTable.test.tsx.snap, frontend/src/lib/WorkflowParser.ts, frontend/src/pages/RunDetails.tsx
Augments `DetailsTable` to parse and pretty-print component inputs/outputs when they are JSON strings 
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1348)
=> Pretty print inputs and outputs json

frontend/server/server.ts, frontend/src/lib/WorkflowParser.test.ts, frontend/src/lib/WorkflowParser.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1339)
=> Add HTTP/HTTPS support in FE

sdk/python/kfp/dsl/_container_op.py
This change prevents errors in case the function does not return anything. Previously, the function had to always pass through the `ContainerOp` passed to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1226)
=> SDK/DSL - ContainerOp.apply method now supports functions that do not return anything

frontend/src/components/DetailsTable.test.tsx, frontend/src/components/DetailsTable.tsx, frontend/src/components/__snapshots__/DetailsTable.test.tsx.snap
In addition to objects and arrays, primitives such as '10', '"string"', 'null', 'true', and 'false' can all be parsed as JSON, but none of them warrant displaying with CodeMirror.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1366)
=> Do not render primitives as json

sdk/python/requirements.txt
requirements.txt needs to be consistent with setup.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1367)
=> SDK - Added the argo-models to requirements.txt

components/ibm-components/watson/train/component.yaml, components/ibm-components/watson/train/src/wml-train.py, samples/ibm-samples/watson/README.md
Add scheme to cos_endpoint for watson client and change deprecated author_email to author_name.
#1254 point 3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1259)
=> Fix watson train component

components/aws/sagemaker/deploy/component.yaml, components/aws/sagemaker/model/component.yaml, components/aws/sagemaker/train/component.yaml
Sagemaker is misspelled a few times as sagamaker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1386)
=> Fix naming from sagamaker to sagemaker

sdk/python/kfp/compiler/_component_builder.py
/assign @gaoning777 @Ark-kun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1394)
=> Cleanup code - Kaniko pod parameterization 

sdk/python/kfp/components/_python_op.py, sdk/python/setup.py, sdk/python/tests/components/test_python_op.py
Lightweight components convert a python function into a component usable as a pipeline step.
Previously, not every function could be converted - the function must be self-contained (not use imports, variables, functions and classes defined outside of the function).
This change removes those limitations.
Which dependencies are now captured alongside the function? All objects that are in the same python *module* as the function being converted to pipeline op.
* If the function is defined in a notebook, then all required functions and classes declared in that notebook can be captured.
* If the function is defined in a python file, then all required functions and classes declared in that file can be captured.
* If the function is defined in a python module, then all required functions and …
=> SDK - Capturing function dependencies when creating lightweight components

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1398)
=> Added the link to the SDK reference docs to README.md

sdk/python/kfp/_client.py
In case of IAP endpoint, the prefix is https instead of http. without the change the link will be resolved into 
http://https://foo.endpoints.bar.cloud.goog/pipeline
/assign @Ark-kun @hongye-sun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1400)
=> Fix auto generated resource link for DSL

components/aws/sagemaker/common/_utils.py
To address #1370
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1377)
=> Add HyperParameters back to SageMaker training job

sdk/python/kfp/dsl/_metadata.py
Problem:
Pipeline metadata extraction fails with error when the pipeline uses `PipelineParam` in the signature:
```python
@pipeline('name', 'description')
def my_pipeline(
my_param = PipelineParam(name='my-param', value='default value'),
):
...
```
This happens because the code in `_extract_*_metadata` considers the whole `PipelineParam` object as default value instead of getting the default value from its `.value` property.
This PR fixes this error.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1380)
=> Fixed the handling of PipelineParam-based default values in extract_metadata

samples/tfx/README.md, samples/tfx/taxi-cab-classification-pipeline.py
fixes: #721
Enhance pipeline TFX taxi sample to support on-prem cluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/749)
=> Enhance pipeline TFX taxi sample to support on-prem cluster

.travis.yml, samples/notebooks/DSL Static Type Checking.ipynb, samples/notebooks/Lightweight Python components - basics.ipynb, sdk/python/kfp/dsl/_metadata.py, sdk/python/kfp/dsl/types.py, sdk/python/requirements.txt, sdk/python/setup.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/dsl/component_tests.py, sdk/python/tests/dsl/pipeline_tests.py, sdk/python/tests/dsl/type_tests.py
This enables the dsl compiler to type checking the default values if the type contains the json schema.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1407)
=> add default value type checking

sdk/python/kfp/components/_python_op.py
Fixes https://github.com/kubeflow/pipelines/issues/1426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1429)
=> SDK - Dynamically installing cloudpickle module

manifests/README.md
/assign @paveldournov @Ark-kun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1432)
=> Update the doc to enable proxy agent by default

sdk/python/kfp/_client.py
This PR supports:
1. Optionally load auth config from kube config.
2. Make namespace to be configurable.
Fix https://github.com/kubeflow/pipelines/issues/1318
This PR can kind of fix https://github.com/kubeflow/pipelines/issues/1104 as well, except that it doesn't go through IAP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1443)
=> Load auth from kube config.

sdk/python/kfp/components/_python_op.py
This makes unit tests much faster.
Also:
Pined the version to 1.1.1.
Made the installation quiet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1434)
=> SDK - Only install cloudpickle if it's not available

components/kubeflow/katib-launcher/src/launch_study_job.py
The current Katib-launcher component will break using the component.yaml since the `outputfile`'s parent directory does not exist. Therefore, we need to create parent directory if it doesn't exist.
Note: This image is using python 2.7, so the `exist_ok ` parameter is not yet available for ` os.makedirs`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1441)
=> Fix Katib-launcher component with python file open issue

manifests/namespaced-install.yaml
This is generated by running
```
kubectl kustomize manifests/namespaced-install > manifests/namespaced-install.yaml
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1446)
=> update namespaced install manifest to include inverse proxy

samples/basic/pipeline_transformers.py, sdk/python/kfp/dsl/_pipeline.py, test/frontend-integration-test/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1440)
=> expose add_op_transformer in the PipelineConf and add an example

sdk/python/kfp/dsl/_metadata.py
resolves https://github.com/kubeflow/pipelines/issues/1417
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1439)
=> remove support for deserializing a string of a dict for typemeta

sdk/python/kfp/dsl/_container_op.py
Following [this discussion](https://github.com/kubeflow/pipelines/pull/749#issuecomment-493437097).
/cc @jinchihe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1353)
=> SDK/Compiler: Add add_pvolumes() method to ContainerOp

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/timeout.py, sdk/python/tests/compiler/testdata/timeout.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1465)
=> Add timeout out in dsl

backend/src/apiserver/client/sql.go, backend/src/apiserver/client_manager.go, backend/src/apiserver/config.go
add support to specify S3 and MySQL credentials and endpoints through environment variables (and secrets)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1455)
=> Apiserver s3 and MySQL env vars

sdk/python/kfp/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py
The handler is required by injecting metadata tracking steps for ContainerOps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1458)
=> Add op_to_templates_handler to compiler

sdk/python/kfp/dsl/_artifact_location.py, sdk/python/tests/compiler/testdata/artifact_location.py, sdk/python/tests/compiler/testdata/artifact_location.yaml, sdk/python/tests/dsl/artifact_location_tests.py
The current implementation generates an incorrect s3 output artifact snippet:
```
s3:
accessKeySecret:
key: ''
optional: true
bucket: mlpipeline
endpoint: minio-service.kubeflow:9000
insecure: true
key: runs/{{workflow.uid}}/{{pod.name}}/mlpipeline-metrics.tgz
secretKeySecret:
key: ''
optional: true
```
Instead it should be:
```
s3:
accessKeySecret:
key: accesskey
name: mlpipeline-minio-artifact
bucket: mlpipeline
endpoint: minio-service.kubeflow:9000
insecure: true
key: runs/{{workflow.uid}}/{{pod.name}}/mlpipeline-metrics.tgz
secretKeySecret:
key: secretkey
name: mlpipeline-minio-artifact
```
Related PR: https://github.com/kubeflow/pipelines/pull/1064
--- …
=> SDK/Compiler - Fix s3 artifact key names

components/ibm-components/spark/train_spark/src/spark-submit.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1470)
=> removing some creds

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_data/module1.py, sdk/python/tests/components/test_data/module2_which_depends_on_module1.py, sdk/python/tests/components/test_python_op.py
All func_to_* functions now accept the modules_to_capture parameter: List of module names that will be captured (instead of just referencing) during the dependency scan. By default the func.__module__ is captured.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1435)
=>  SDK - Controlling which modules are captured with Lightweight components

manifests/base/pipeline/ml-pipeline-viewer-crd-role.yaml, manifests/base/pipeline/ml-pipeline-viewer-crd-rolebinding.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1499)
=> use cluster role for viewer crd for now since viewer crd doesn't support namespaced deployemnt

component_sdk/python/kfp_component/google/ml_engine/__init__.py, component_sdk/python/kfp_component/google/ml_engine/_common_ops.py, component_sdk/python/kfp_component/google/ml_engine/_create_job.py, component_sdk/python/kfp_component/google/ml_engine/_wait_job.py, component_sdk/python/requirements.txt, component_sdk/python/setup.py, component_sdk/python/test-requirements.txt, component_sdk/python/tests/google/ml_engine/test__create_job.py, component_sdk/python/tests/google/ml_engine/test__wait_job.py, component_sdk/python/tox.ini
Extract wait job logic from create_job command and make it as an individual command.
This command can enable scenario when user has an existing component which submits a CMLE job. They can use the wait_job command to wait until the job finishes.
The command supports:
* Cancellation when the pipeline is cancelled.
* Fail if the job is in failed state.
* Output display metadata including job links and tensor-board link.
Some side changes are also included in the PR:
* Remove the need of requirements.txt file.
* Support pass args to pytest via tox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1505)
=> Add wait_job command

sdk/python/kfp/dsl/_pipeline_volume.py, sdk/python/tests/dsl/pipeline_volume_tests.py
This PR makes the creation of a `PipelineVolume` without specifying a `name` possible.
The `name` of the `volume` is an orchestration detail [1] that the user should be able to be agnostic about.
I also removed any unused imports from the `_pipeline_volume` module.
[1]: It is only needed for the matching of `volumeMount`s with the `volume` entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1402)
=> SDK/DSL: Make 'name' argument of a PipelineVolume omittable

sdk/python/kfp/components/_python_op.py
Due to its nature, Argo will replace any strings it encounters that are enclosed in double curly braces, which will make the code non-executable. To workaround this, the code is encoded in the Argo yaml template and decoded on the fly, before the execution.
Fixes #1453
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1476)
=> Base64 encode the pickled code

sdk/python/kfp/components/_python_op.py
Without this the output and error lines can be printed in wrong order and sometimes not printed at all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1510)
=> SDK - Improving python component logs by making stdout and stderr unbuffered

backend/Dockerfile, test/sample-test/Dockerfile, test/sample-test/run_test.sh
There is no longer a need to install Java, download and run swagger-codegen etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1444)
=> Build - Simplify python SDK package installation

sdk/python/kfp/_client.py
Adds the `Client.run_pipeline_func_on_kfp(func)` function that compiles the pipeline and submits it for execution on KFP-enabled cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1484)
=> SDK - Make it easier to compile and submit a pipeline run

sdk/python/kfp/components/_python_op.py
This refactoring is needed to allow using different code generators while sharing the same function signature analysis code.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1334)
=> SDK - Refactored _func_to_component_spec to split code generation from signature analysis

frontend/src/lib/WorkflowParser.test.ts, frontend/src/lib/WorkflowParser.ts, sdk/python/kfp/compiler/_op_to_template.py, sdk/python/tests/compiler/compiler_tests.py
Turns out, Kubernetes only allows a single slash character in annotation key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1526)
=> SDK+Frontend - Fixed the task display name annotation key

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
I've introduced code pickling to capture dependencies in https://github.com/kubeflow/pipelines/pull/1372
Later I've discovered that there is a serious opcode incompatibility between python versions 3.5 and 3.6+. See my analysis of the issue: https://github.com/cloudpipe/cloudpickle/issues/293
Due to this issue I decided to switch back to using source code copying by default and to continue improving it.
Until we stop supporting python 3.5 (https://github.com/kubeflow/pipelines/pull/668) it's better to disable code pickling by default.
Code pickling can be enabled by specifying `use_code_pickling=True` when calling `func_to_container_op`
--- …
=> SDK/Lightweight - Disabled code pickling by default

sdk/python/kfp/_client.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1522)
=> SDK - Fixed import

sdk/python/kfp/components/_components.py
This makes them more compatible with images that have non-root user (e.g. `apache/airflow`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1531)
=> SDK - Generated paths will be in /tmp by default

sdk/python/kfp/_client.py
`kfp.Client` now always exposes **all** server APIs.
`kfp.Client().runs.create_run(...)`
`kfp.Client().pipelines.create_pipeline(...)`
`kfp.Client().pipeline_uploads.upload_pipeline(...)`
etc.
New APIs are exposed automatically.
Fixes https://github.com/kubeflow/pipelines/issues/1130
Fixes https://github.com/kubeflow/pipelines/issues/1493
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1536)
=> SDK/Client - Added support for all APIs

component_sdk/python/kfp_component/core/_kfp_execution_context.py, component_sdk/python/tests/core/test__kfp_execution_context.py
1. Parameterize namespace from env
2. Log pod error instead of throwing the exception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1539)
=> Parameterize namespace and suppress pod error

README.md
Fix the broken API doc link url.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1496)
=> fix api doc link url

sdk/python/kfp/components/_python_op.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1524)
=>  SDK/Lightweight - Added python version compatibility checks

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1467)
=> SDK - Travis configuration for Python 3.5 and 3.7

sdk/python/kfp/components/_python_op.py
It's required to correctly handle None arguments or None default values (also needed for optional and variable-number inputs).
It's easier to understand and generates better command-line code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1534)
=> SDK/Lightweight -  Use argparse for command-line parsing

README.md, components/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1544)
=> Updated links in READMEs

sdk/python/kfp/dsl/_pipeline_volume.py, sdk/python/tests/dsl/pipeline_volume_tests.py
**Background**
CI builds are failing [a lot](https://travis-ci.com/kubeflow/pipelines/jobs/210674655#L1459) due to a flaky unit test. 
**Changes**
I used `sorted(dict.items())` to get a stable `str()` output.
**Test Plan**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1554)
=> Use sorted(dict.items()) for stable output

sdk/python/kfp/dsl/_pipeline_volume.py, sdk/python/tests/dsl/pipeline_volume_tests.py
**Background**
#1554 actually still doesn't work since the `self.to_dict()` output contains nested dictionaries so just `sort(dict.items())` won't work.
**Changes**
Used `json.dumps(dict, sort_keys=True)` instead.
**Test Plan**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1558)
=> Sort keys in nested dictionaries for fixing unit tests

frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
**Background**
#1310 added links to show Stackdriver logs. However, the links seem to be some Google-internal links. 
**Changes**
In this PR, I updated the links to using `console.cloud.google.com`.
**Test Plan**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1552)
=> Use GCP external Stackdriver links

manifests/base/pipeline/pipeline-runner-role.yaml
Supplement pipeline-runner permissions according to kubeflow/kubeflow#2556
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1570)
=> Manifests: Update pipeline-runner permissions

components/ibm-components/watson/train/component.yaml, components/ibm-components/watson/train/src/wml-train.py, samples/ibm-samples/watson/watson_train_serve_pipeline.py
We want to add an extra output to our Watson training component so that the next component can capture the model location within cloud object storage without installing the Watson client.
/assign @animeshsingh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1587)
=> Update Watson training component to output model location UID

frontend/server/k8s-helper.ts
Tested the result in two ways
(1) via pantheon UI, in Pod's yaml, we found https://screenshot.googleplex.com/41njRPZuQSh
(2) via shell in viewer's pod, we found user-gcp-sa.json file under /secret/gcp-credentials/ directory
https://screenshot.googleplex.com/cHCn1rcf4zq
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1603)
=> Set user credentials when creating viewer  object

samples/ai-platform/Chicago Crime Pipeline.ipynb, samples/ibm-samples/ffdl-seldon/ffdl_pipeline.ipynb, samples/notebooks/DSL Static Type Checking.ipynb, samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb, samples/notebooks/Lightweight Python components - basics.ipynb, samples/notebooks/Local Development Quickstart.ipynb, samples/nvidia-resnet/pipeline/Dockerfile, samples/tfx-oss/README.md, samples/tfx-oss/TFX Example.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1607)
=> Update samples to use the latest versions of the python SDK

backend/src/crd/controller/viewer/reconciler/reconciler.go, manifests/base/pipeline/ml-pipeline-viewer-crd-role.yaml, manifests/base/pipeline/ml-pipeline-viewer-crd-rolebinding.yaml, manifests/namespaced-install.yaml
Two changes: (1) in reconciler.go, the original r.Client.List without specifying namespace requires cluster scope role, and thus change it to use an explicit namespace (2) remove cluster role and cluster role binding from two places: namespaced_install.yaml and base/pipeline/ml-pipeline-viewer-crd-*.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1623)
=> viewer controller is now namespaced so no need for cluster role

frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Previously, there was a CircularProgress to indicate that the UI is busy within the [RunDetails.tsx](https://github.com/kubeflow/pipelines/blob/24aae0d08205d9fc8f06a5bcc41e7d066d623817/frontend/src/pages/RunDetails.tsx#L213) and [SidePanel.tsx](https://github.com/kubeflow/pipelines/blob/a8b910787824d5fe08fc98f9f0dd8be54ac66e8e/frontend/src/components/SidePanel.tsx#L81). This removes the CircularProgress from RunDetails.tsx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1625)
=> Removed duplicate CircularProgress within UI

developer_guide.md, manifests/base/argo/workflow-controller-configmap.yaml, manifests/base/argo/workflow-controller-deployment.yaml, manifests/base/minio/minio-deployment.yaml, manifests/base/mysql/mysql-deployment.yaml, manifests/namespaced-install.yaml, manifests/namespaced-install/workflow-controller-configmap.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1622)
=> switch third party images to GCR

backend/src/apiserver/client/sql.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1627)
=> propagate database password when init db connection

frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx
Fixes #162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1605)
=> Trims whitespace from pipeline params on creation of new run

components/aws/sagemaker/Dockerfile, components/aws/sagemaker/common/_utils.py, components/aws/sagemaker/common/hpo.template.yaml, components/aws/sagemaker/hyperparameter_tuning/Dockerfile, components/aws/sagemaker/hyperparameter_tuning/README.md, components/aws/sagemaker/hyperparameter_tuning/component.yaml, components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py, samples/aws-samples/mnist-kmeans-sagemaker/kmeans-hpo-pipeline.py
@Jeffwan @mbaijal @gautamkmr @kalyc
**Updated Dockerfile**
- Copies hyperparameter_tuning.py into the container 
- Updated install for boto3 and installs pyyaml
**Added Dockerfile for just HPO**
- Same as original but only copies the script for HPO in
**Added hyperparameter tuning component**
- hpo.template.yaml: template for API call request generation
- _utils.py: additional functions for hyperparameter tuning
- hyperparameter_tuning.py
- README: details inputs/outputs for the HPO component and how to run the sample
- component.yaml: the docker image used in this built from the HPO-only Dockerfile
**Sample pipeline (of just the HPO component)**
- Show sample usage for the HPO component for the K-Means algorithm using the MNIST dataset
- Uses all possible parameters, though some …
=> Add SageMaker HPO component and sample usage in a pipeline

frontend/src/lib/RunUtils.ts, frontend/src/pages/RunList.test.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
In the future, the list will be filterable by recurring run, but given that that is planned, I will close #1392 with this PR 
Example list with recurring run column:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1635)
=> Add recurring run column to run lists

backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go, backend/src/common/util/workflow.go, backend/src/common/util/workflow_test.go
Currently when persisting the runs spawned from a job, PersistentAgent stores more information than needed into the pipeline manifest, and also miss the TypeMetadata. This resulted in storing lots of runtime information that's not needed.
Example WorkflowSpec
```
"metadata":{
"name":"fffpw4fh-2-2911767673",
"namespace":"kubeflow",
"selfLink":"/apis/argoproj.io/v1alpha1/namespaces/kubeflow/workflows/fffpw4fh-2-2911767673",
"uid":"de23bd5c-a8c1-11e9-a176-42010a800233",
"resourceVersion":"3975687",
"generation":1,
"creationTimestamp":"2019-07-17T18:37:02Z",
"labels":{
"scheduledworkflows.kubeflow.org/isOwnedByScheduledWorkflow":"true",
"scheduledworkflows.kubeflow.org/scheduledWorkflowName":"fffpw4fh",
"scheduledworkflows.kubeflow.org/workflowEpoch":"1563388612", …
```
=> update persistent agence to only store the argo spec

component_sdk/python/test-requirements.txt, component_sdk/python/tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1577)
=> tox.ini: Add flake8 tests to find Python syntax errors and undefined names

frontend/src/components/Toolbar.tsx, frontend/src/lib/Buttons.ts, frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap, frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1637)
=> Sets min widths for buttons to avoid text wrapping

sdk/python/kfp/compiler/_component_builder.py, sdk/python/kfp/compiler/_gcs_helper.py, sdk/python/tests/compiler/component_builder_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1658)
=> move gcshelper out of component_builder

samples/basic/exit_handler.py
The fix sets is_exit_handler flag to True for exit handler step. Otherwise, it will create an additional step at the start of the DAG.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1665)
=> Fix exit handler sample

sdk/python/setup.py
The package was missing by mistake.
Fixes #1629
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1666)
=> Adding kfp.cil to kfp setup.py.

sdk/python/kfp/components/_python_op.py, sdk/python/kfp/components/_structures.py, sdk/python/tests/components/test_python_op.py
Previously it was impossible to pass None to components since it was being converted to the string "None".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1626)
=> SDK - Lightweight - Added support for "None" default values

frontend/src/components/viewers/Viewer.ts, frontend/src/components/viewers/ViewerContainer.tsx, frontend/src/components/viewers/VisualizationCreator.test.tsx, frontend/src/components/viewers/VisualizationCreator.tsx, frontend/src/components/viewers/__snapshots__/ViewerContainer.test.tsx.snap, frontend/src/components/viewers/__snapshots__/VisualizationCreator.test.tsx.snap
* Adds new PlotType (`VISUALIZATION_CREATOR`)
* Adds new Viewer component (`VisualizationCreator.tsx`)
* Adds unit tests for new Viewer component
* Includes snapshots
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1677)
=> Add new PlotType to Allow for Visualization Creation

backend/src/common/util/workflow.go, backend/src/common/util/workflow_test.go
This will prevent name collisions when cloning runs generated by jobs.
Related to #1266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1689)
=> Clears the workflow's name in GetWorkflowSpec and uses it for the GenerateName

sdk/python/kfp/compiler/_component_builder.py, sdk/python/tests/compiler/component_builder_test.py
This is part of the efforts to refactor the component build such that codegen is separated from the image build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1679)
=> Separate codegen from containerbuild

sdk/python/kfp/compiler/_component_builder.py, sdk/python/kfp/compiler/_container_builder.py, sdk/python/tests/compiler/component_builder_test.py, sdk/python/tests/compiler/container_builder_test.py, sdk/python/tests/compiler/main.py
separate the container build from the component build;
add support for directory build in the container builder
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1680)
=> Separate codegen from containerbuild 2

sdk/python/kfp/compiler/_container_builder.py, sdk/python/tests/compiler/container_builder_test.py
simplify the tar compression codes for the build files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1703)
=> Component build fix

samples/notebooks/Multiple outputs - basics.ipynb, sdk/python/kfp/compiler/_component_builder.py, sdk/python/tests/compiler/component_builder_test.py
Allows for build_python_component to use NamedTuples, fixing https://github.com/kubeflow/pipelines/issues/1580.
Adds sample specifically for https://github.com/kubeflow/pipelines/issues/1517, and for overall sample efforts https://github.com/kubeflow/pipelines/issues/1034.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1667)
=> Adding multiple outputs into sdk with sample

backend/Dockerfile, backend/Dockerfile.persistenceagent, backend/Dockerfile.scheduledworkflow, backend/Dockerfile.viewercontroller
This reduces the image size, reduces the attack surface and avoids security vulnerabilities.
Fixes https://github.com/kubeflow/pipelines/issues/1545
The image size is 80% smaller and it has probably no known vulnerabilities.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1699)
=> Backend - Starting the api-server container build from scratch

WORKSPACE, go.mod
Fixes https://github.com/kubeflow/pipelines/issues/1722
The [v0.13.2](https://github.com/google/ml-metadata/releases/tag/v0.13.2) release points to the [bd91e49a0898](https://github.com/google/ml-metadata/commit/becc26ab61f82bfe7c812894f56f597949ce0fdc) commit. The same one that was used in the `WORKSPACE` initially.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1725)
=> Backend - Updated the version of the ml metadata package

sdk/python/kfp/components/__init__.py, sdk/python/kfp/components/_airflow_op.py
This CL adds support for converting arbitrary Airflow operators to Pipelines components so that it can be used as a pipeline task.
```python
from airflow.operators.bash_operator import BashOperator
bash_op = kfp.components.create_component_from_airflow_op(BashOperator)
@pipeline()
bash_task = bash_op('echo "Hello from $SHELL"', xcom_push=True)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1483)
=> SDK - Using Airflow ops in Pipelines

samples/basic/execution_order.py
This sample is to address #665
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1668)
=> Adding a sample for explicitly defining the execution order

samples/Contrib/Secret/secret.py, samples/basic/secret.py
Adding a basic sample to address #993.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1676)
=> Container op mount secret sample

components/third_party_licenses.csv
Fixes CloudBuild failures.
pymongo is installed by Apache Beam which is used by TF Transform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1740)
=> Components - Added the pymongo license URL

sdk/python/kfp/dsl/_container_op.py
This is needed so that it can be chained:
```
task = op(...).set_display_name('Bla')
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1718)
=> SDK - ContainerOp.set_display_name should return self

sdk/python/kfp/components/_python_op.py
There was a bug introduced when moving to `argparse`-based command-line argument parsing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1726)
=> SDK - Lightweight - Fixed regression for components without outputs

components/aws/sagemaker/ground_truth/README.md, components/aws/sagemaker/hyperparameter_tuning/README.md, components/aws/sagemaker/workteam/README.md, samples/contrib/aws-samples/ground_truth_pipeline_demo/README.md, samples/contrib/aws-samples/ground_truth_pipeline_demo/mini-image-classification-pipeline.py, samples/contrib/aws-samples/mnist-kmeans-sagemaker/kmeans-hpo-pipeline.py, samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
**Summary**
Updated links to samples in READMEs and paths to components in sample pipelines to match new samples folder structure
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1741)
=> Refactor aws samples to match new folder structure

frontend/src/components/NewRunParameters.test.tsx, frontend/src/components/NewRunParameters.tsx, frontend/src/components/Router.tsx, frontend/src/components/__snapshots__/NewRunParameters.test.tsx.snap, frontend/src/lib/Buttons.ts, frontend/src/lib/RunUtils.ts, frontend/src/pages/NewRun.test.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/RecurringRunDetails.test.tsx, frontend/src/pages/RecurringRunDetails.tsx, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Fixes #1266 
Simplifies NewRun a little by separating out NewRunParameters into its own component.
There were a number of issues with the way recurring runs were handled in the frontend and backend that were addressed in this PR and the others referenced in #1266.
With this PR, users can no longer swap between one-off and recurring when cloning a run. Recurring runs and single runs are ostensibly similar but there are nuances to the way they are handled in the backend that makes treating them as interchangeable problematic.
Similarly, users can no longer switch Pipelines after reaching NewRun via cloning. This extra flexibility isn't worth the complexity it adds.
This PR also adds a `clone` button to the details page for a recurring run.
Keeping track of parameters within the Pipeline …
=> Fixes cloning of recurring runs

WORKSPACE, go.mod
Reverts kubeflow/pipelines#1725
Trying to fix test failures https://github.com/kubeflow/pipelines/issues/1745 (The can also be fixed by https://github.com/kubeflow/pipelines/issues/1728)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1747)
=> Revert "Backend - Updated the version of the ml metadata package"

backend/Dockerfile, backend/Dockerfile.persistenceagent, backend/Dockerfile.scheduledworkflow, backend/Dockerfile.viewercontroller
Reverts kubeflow/pipelines#1699
There are some unusual failures in https://github.com/kubeflow/pipelines/pull/1739, so let's rollback the CL for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1742)
=> Revert "Backend - Starting the api-server container build from scratch"

test/deploy-kubeflow.sh, test/deploy-pipeline.sh
If there is any issue in the code to be tested that causing the KFP components image fail to launch (CrashLoopBackOff for example), Kubernetes will by default keep the old pod running. The test will thus test against an official image instead.
Delete KFP will ensure the KFP to be tested either not start at all, or healthy. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1736)
=> Delete KFP component before reinstalling again

components/ibm-components/spark/store_spark_model/src/store_spark_model.py, components/ibm-components/watson/deploy/src/wml-deploy.py, components/ibm-components/watson/manage/subscribe/src/subscribe.py, components/ibm-components/watson/store/src/wml-store.py, components/ibm-components/watson/train/src/wml-train.py, samples/contrib/ibm-samples/openscale/README.md, samples/contrib/ibm-samples/openscale/credentials/creds.ini, samples/contrib/ibm-samples/watson/README.md, samples/contrib/ibm-samples/watson/credentials/creds.ini
Starting from Aug 1st, Watson ML requires IAM auth using the `apikey` for authentication. Thus, we need to update our client code and creds.ini to include `apikey` from now on. 
/assign @animeshsingh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1737)
=> Update Watson Machine Learning auth with IAM

backend/test/integration/job_api_test.go, backend/test/integration/run_api_test.go
The change ensures the result returned is deterministic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1769)
=> fix api server sort test 

backend/src/apiserver/storage/run_store.go
There are many error from Persistence Agent log 
"Permanent failure while syncing resource (kubeflow/resubmit-vptp6): CustomError (code: 1): Syncing Workflow (resubmit-vptp6): permanent failure: CustomError (code: 1): Error while reporting workflow resource (code: InvalidArgument, message: Report workflow failed.: Invalid input error: Failed to update run 82be5fa1-ce58-4819-a0a4-754fcbc258ac. Row not found. "
This is due to run not change in the database. Fix the logic in API server to not treat this as error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1765)
=> Not return error if run update doesn't change DB entry

backend/Dockerfile
Problem: Docker implicitly prepends "sh -c " to the RUN commands (no "-e"). Without "-e", the exit code of the shell script is the exit code of the last executed command. So the sample compilation script will only fail if the last sample failed the compilation.
Fix: Explicitly adding "set -e" to the command fixes the issue.
Fixes https://github.com/kubeflow/pipelines/issues/1735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1760)
=> Backend - Docker build should fail on sample compilation failures

backend/src/apiserver/config/sample_config.json
Related change https://github.com/kubeflow/pipelines/commit/b476a848d9894acc6212a88fcecd8df06e0d3cf6
/hold
Need investigate why test doesn't catch it. 
/assign @numerology @gaoning777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1805)
=> Fix the broken sample path in API

test/deploy-pipeline.sh
For more context see 
https://github.com/kubeflow/pipelines/pull/1805#issuecomment-520204987
We could remove this fix when ksonnet is deprecated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1807)
=> Fix test loophole for loading samples during KFP startup

backend/Dockerfile.persistenceagent, backend/src/agent/persistence/main.go, backend/src/agent/persistence/persistence_agent.go, backend/src/agent/persistence/worker/persistence_worker_test.go, backend/src/agent/persistence/worker/workflow_saver.go, backend/src/agent/persistence/worker/workflow_saver_test.go, backend/src/apiserver/resource/resource_manager.go, backend/src/apiserver/resource/resource_manager_test.go, backend/src/apiserver/resource/resource_manager_util.go, backend/src/apiserver/resource/workflow_fake.go, backend/src/apiserver/server/report_server_test.go, backend/src/common/util/consts.go, backend/src/common/util/workflow.go, test/frontend-integration-test/helloworld.spec.js
fix https://github.com/kubeflow/pipelines/issues/1706
with this change this issue seems no longer relevent https://github.com/kubeflow/pipelines/issues/1708
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1802)
=> Garbage collect the completed workflow after persisted to database

.travis.yml
Consistently getting the following error
```
/home/travis/build/kubeflow/pipelines/frontend/node_modules/coveralls/bin/coveralls.js:18
throw err;
^
Bad response: 405 <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pipelines-frontend@0.1.0 test:coveralls: `npm run test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pipelines-frontend@0.1.0 test:coveralls script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! …
```
=> Update npm test to not use coverall

test/README.md
argo cli no longer has argo install sub command. ref: https://github.com/argoproj/argo/blob/dc5491930e09eebe700952e28359deeb8e0d2314/CHANGELOG.md#220-2018-08-30
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1719)
=> Remove outdated argo install instruction

backend/src/apiserver/model/resource_reference.go
It would improve the list runs call which contains filtering on [ResourceType, ReferenceUUID, ReferenceType]
We've seen cases list runs take long to run when resource_reference table is large. 
```
SELECT
subq.*,
CONCAT("[", GROUP_CONCAT(r.Payload SEPARATOR ", "), "]") AS refs 
FROM
(
SELECT
rd.*,
CONCAT("[", GROUP_CONCAT(m.Payload SEPARATOR ", "), "]") AS metrics 
FROM
(
SELECT
UUID,
DisplayName,
Name,
StorageState,
Namespace,
Description,
CreatedAtInSec,
ScheduledAtInSec,
FinishedAtInSec,
Conditions,
PipelineId,
PipelineSpecManifest,
WorkflowSpecManifest,
Parameters,
pipelineRuntimeManifest,
WorkflowRuntimeManifest 
FROM
run_details 
WHERE
UUID in 
(
SELECT
ResourceUUID 
FROM
resource_references as rf 
WHERE
(
rf.ResourceType = 'Run' 
AND rf.ReferenceUUID = …
```
=> Create composite indexes [ResourceType, ReferenceUUID, ReferenceType]

backend/src/apiserver/storage/run_store.go
Original query 
```
SELECT
subq.*,
CONCAT("[", GROUP_CONCAT(r.Payload SEPARATOR ", "), "]") AS refs 
FROM
(
SELECT
rd.*,
CONCAT("[", GROUP_CONCAT(m.Payload SEPARATOR ", "), "]") AS metrics 
FROM
(
SELECT
UUID,
DisplayName,
Name,
StorageState,
Namespace,
Description,
CreatedAtInSec,
ScheduledAtInSec,
FinishedAtInSec,
Conditions,
PipelineId,
PipelineSpecManifest,
WorkflowSpecManifest,
Parameters,
pipelineRuntimeManifest,
WorkflowRuntimeManifest 
FROM
run_details
)
AS rd 
LEFT JOIN
run_metrics AS m 
ON rd.UUID = m.RunUUID 
GROUP BY
rd.UUID
)
AS subq 
LEFT JOIN
(
select
* 
from
resource_references 
where
ResourceType = 'Run'
)
AS r 
ON subq.UUID = r.ResourceUUID 
WHERE
UUID = 'a0af02a9-bacb-11e9-a841-42010ad4009a' 
GROUP BY
subq.UUID LIMIT 1;
```
This can be improved by moving the where …
=> Improve sql efficiency for getting the run

samples/contrib/image-captioning-gcp/README.md
Simple changes to README
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1828)
=> Update for sample repo restructuring

samples/core/lightweight_component/Lightweight Python components - basics.ipynb
Provide a clear example of subprocess pip install workaround in lightweight python component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1817)
=> Add subprocess pip install example in lightweight component example notebook

frontend/mock-backend/fixed-data.ts, frontend/src/apis/job/api.ts, frontend/src/apis/run/api.ts, frontend/src/lib/RunUtils.ts, frontend/src/pages/ExperimentDetails.tsx, frontend/src/pages/NewRun.tsx, frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/RunList.test.tsx, frontend/src/pages/RunList.tsx, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Uses `pipeline_name` in `pipeline_spec` when possible to avoid making additional API calls to retrieve the names.
Additionally, fixes bug in `ExperimentDetails` to remove redundant `getRuns` call.
Part of #1773
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1852)
=> Reduce getPipeline calls in RunList

backend/src/apiserver/visualization/exporter.py, backend/src/apiserver/visualization/roc_curve.py, backend/src/apiserver/visualization/server.py, backend/src/apiserver/visualization/snapshots/snap_test_exporter.py, backend/src/apiserver/visualization/test_exporter.py, backend/src/apiserver/visualization/test_server.py
Previously, dependency injection occurred by taking a JSON string and converting it to variables within a NotebookNode.
```python
arguments = '{"key": "value"}'
...
key = "value"
```
This would change this to become the following:
```python
arguments = '{"key": "value"}'
...
variables = json.loads(arguments)
```
This change also addresses typing issues that were present with the previous implementation. The Boolean and None types are [not directly supported by JSON](https://docs.python.org/3/library/json.html#encoders-and-decoders), instead `true`/`false` and `nil` are used in valid JSON while the previous implementation expected `True`/`False` and `None` to be provided as values. This is now fully supported and valid JSON is expected with the new implementation of `json.load`.
---
This …
=> Change how Variables are Provided to Visualizations

frontend/src/apis/run/api.ts, frontend/src/lib/RunUtils.ts, frontend/src/pages/RunList.tsx
Frontend now checks if a name is provided with a `resource_reference`. If a name is provided and it is a valid object within the resource reference (see if statement in PR), it will now be used to display the experiment name rather than making an additional API call to retrieve the experiment name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1824)
=> Reduce API usage by utilizing reference name in reference resource API

frontend/mock-backend/fixed-data.ts, frontend/src/lib/Utils.test.ts, frontend/src/lib/Utils.ts, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
As mentioned in #1823, we were unnecessarily taking the modulus of the hours resulting in incorrect durations for runs lasting > 24 hours
Fixes #1823
Changes to `RunList` are simply a variable renaming and can be ignored
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1827)
=> Fix run duration bug

sdk/python/kfp/dsl/_pipeline_param.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/dsl/pipeline_param_tests.py
Default values are only relevant when PipelineParam is used in the pipeline function signature and even in this case compiler captures them explicitly from the PipelineParam objects in the signature.
There seem to be no other uses for them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1469)
=>  SDK - Cleanup - Serialized PipelineParamTuple does not need value or type

sdk/python/kfp/compiler/_component_builder.py
Strings are usually compared using the `==` operator. The `is` operator compares references.
The problem was discovered in https://github.com/kubeflow/pipelines/pull/1721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1756)
=> SDK - Fixed string comparisons

backend/src/apiserver/client_manager.go, backend/src/apiserver/config/config.json, go.mod, go.sum
In some usecases, ml pipeline mysql database name to be configurable is desired for not rebuilding backend apiserver docker image. Current implementation does not supports this function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1714)
=> Let backend apiserver mysql dbname configurable

samples/contrib/ibm-samples/watson/source/model-source-code/tf-model/input_data.py
Discovered in #1721
__xrange()__ was removed in Python 3 in favor of an improved version of __range()__.  This PR ensures equivalent functionality in both Python 2 and Python 3.
```
./samples/contrib/ibm-samples/watson/source/model-source-code/tf-model/input_data.py:100:40: F821 undefined name 'xrange'
fake_image = [1.0 for _ in xrange(784)]
^
./samples/contrib/ibm-samples/watson/source/model-source-code/tf-model/input_data.py:102:41: F821 undefined name 'xrange'
return [fake_image for _ in xrange(batch_size)], [
^
./samples/contrib/ibm-samples/watson/source/model-source-code/tf-model/input_data.py:103:37: F821 undefined name 'xrange'
fake_label for _ in xrange(batch_size)]
^
```
@gaoning777 @Ark-kun Your reviews please.
--- …
=> IBM Watson samples: from six.moves import xrange

backend/src/apiserver/client_manager.go
The data stored in artifact storage are usually small. Using multi-part is not strictly a requirement. 
Change the default to true to better support more platform out of box.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1893)
=> Use single part as default

contrib/components/openvino/ovms-deployer/containers/evaluate.py
Discovered in #1721
```
./contrib/components/openvino/ovms-deployer/containers/evaluate.py:62:16: F821 undefined name 'e'
except e:
^
./contrib/components/openvino/ovms-deployer/containers/evaluate.py:63:50: F821 undefined name 'e'
print("Can not read the image file", e)
^
```
Your review please @Ark-kun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1876)
=> Undefined name 'e' in openvino

backend/src/apiserver/visualization/exporter.py
Generated visualizations that fail due to an error within Python code now render that error in the returned HTML rather than as a 500 error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1909)
=> Enable error propagation from nbconvert to frontend

backend/src/apiserver/client_manager.go
Gorm doesn't automatically change the type of a column. Following changes introduced a column type change which might not be effective for an existing cluster doing upgrade. 
https://github.com/kubeflow/pipelines/commit/4e43750c9dcebe37b75aedadd7b1c829b409caaa#diff-c4afa92d7e54eecff0a482cf57490aa8R40
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1905)
=> Change the type of resource reference payload column

sdk/python/kfp/compiler/_component_builder.py
Inlined functions only used in one place and removed dead code.
Maybe we should also move the `build_docker_image` function from `_component_builder.py` to `_container_builder.py`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1887)
=> Simplified the build_docker_image function

.travis.yml, backend/src/apiserver/visualization/roc_curve.py, backend/src/apiserver/visualization/snapshots/snap_test_exporter.py, backend/src/apiserver/visualization/test_exporter.py, backend/src/apiserver/visualization/tfdv.py, components/arena/python/arena/_arena_distributed_tf_op.py, components/aws/emr/create_cluster/src/create_cluster.py, components/aws/emr/submit_pyspark_job/src/submit_pyspark_job.py, components/aws/emr/submit_spark_job/src/submit_spark_job.py, components/aws/sagemaker/batch_transform/src/batch_transform.py, proxy/get_proxy_url.py, samples/contrib/aws-samples/ground_truth_pipeline_demo/mini-image-classification-pipeline.py, samples/contrib/resnet-cmle/resnet-train-pipeline.py, sdk/python/kfp/components/_dynamic.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/tests/dsl/component_tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1721)
=> Lint Python code for undefined names

sdk/python/kfp/components/_airflow_op.py
This PR fixes a bug in AirFlow op creation.
The `_run_airflow_op` helper function was not captured along with the `_run_airflow_op_closure` function, because they belong to different modules (`_run_airflow_op_closure` was module-less).
This was not discovered during the notebook testing of the code since in that environment the `_run_airflow_op` was also module-less as it was defined in a notebook (not in .py file).
TODO: Add sample tests for Airflow operators.
TODO: Think of how to unit-test the feature (it's non-trivial since it runs the airflow server and DB).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1911)
=> SDK - Airflow - Fixed bug in AirFlow op creation

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
The type was mistakenly serialized as `_ForwardRef('CustomType')`.
The input parameter types and single-output types were not affected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1875)
=> SDK - Lightweight - Fixed custom types in multi-output case

sdk/python/kfp/dsl/_resource_op.py, sdk/python/tests/compiler/compiler_tests.py
`delete` action for `ResourceOp` should not generate any `output parameters` (See [argo execResource method](https://github.com/argoproj/argo/blob/5331fc02e257266a4a5887dfe6277e5a0b42e7fc/cmd/argoexec/commands/resource.go#L30)).
- no exception are raised when `success_condition`, `failure_condition`, and `attribute_outputs` are provided when `action=="delete"`
- automatically generates `'{.metadata.name}'` and `{}` output parameters even when `attribute_outputs` is `None` and `action=="delete"`
Example of error thrown:
`This step is in Failed state with this message: successCondition, failureCondition and outputs are not supported for delete action`
```py
@dsl.pipeline()
def some_pipeline():
config_map = k8s.V1ConfigMap(
api_version="v1",
data={"foo": "bar"},
kind="ConfigMap", …
```
=> [Bug Fix] Delete ResourceOp should not have output parameters

backend/src/apiserver/client_manager.go, backend/src/apiserver/main.go, backend/src/apiserver/server/BUILD.bazel, backend/src/apiserver/server/visualization_server.go, backend/src/apiserver/server/visualization_server_test.go, manifests/kustomize/base/kustomization.yaml, manifests/kustomize/base/pipeline/kustomization.yaml, manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml, manifests/kustomize/base/pipeline/ml-pipeline-visualization-service.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1844)
=> Add visualization-server service to lightweight deployment

frontend/mock-backend/fixed-data.ts, frontend/mock-backend/json-runtime.ts
This PR allows developers to test UI changes that revolve around JSON data as an input/output for a component without having to write the input/output manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1895)
=> Add run with json data as input within fixed-data.ts for UI testing and development

backend/src/apiserver/visualization/server.py
Adds support for visualization kernel timeout to be specified via environment variables. This removes the previous necessity of having to build a new image to change the kernel timeout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1920)
=> Allow visualization kernel timeout to be specifiable via environment variables

frontend/server/k8s-helper.ts, frontend/server/server.ts, frontend/server/utils.ts
My kubeflow pipeline is running on AWS infrastructure and we do not allow aws access keys for security reasons. All our infrastructure access are controlled with kube2iam via pod annotations.
The current front-end server creates a hardcoded podTemplateSpec which uses gcp credentials. This result in the tensorboard viewer to be unable to access our logs stored in s3.
This PR adds an environment variable: `VIEWER_TENSORBOARD_POD_TEMPLATE_SPEC_PATH` which points to a local JSON file with a custom podTemplateSpec (e.g. pod annotation with kube2iam role). 
In kubernetes, custom podTemplateSpec can be achieved by creating a configmap and mounting to the `pipeline-ui` pod.
> I was also thinking of supporting YAML. But that would meant an additional dependency. Cuz it is more inituitive to write …
=> [front-end-server] Allow viewer:tensorboard podTemplateSpec to be customizable

frontend/src/pages/PipelineDetails.tsx, frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
Implement suggestion in #1919 to add pipeline id to pipeline summary card.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1927)
=> Add pipeline id to pipeline summary card

sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_dsl_bridge.py, sdk/python/kfp/dsl/_component.py, sdk/python/kfp/dsl/_metadata.py, sdk/python/kfp/dsl/_pipeline_param.py, sdk/python/kfp/dsl/types.py, sdk/python/tests/dsl/component_tests.py, sdk/python/tests/dsl/metadata_tests.py, sdk/python/tests/dsl/pipeline_param_tests.py, sdk/python/tests/dsl/pipeline_tests.py
The PipelineParam no longer exposes the private TypeMeta class
Fixes https://github.com/kubeflow/pipelines/issues/1420
The refactoring PR is part of a series of PR which unifies the metadata and specification types.
All the tests continue to pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1930)
=> SDK - Refactoring - Replaced the TypeMeta class

.gitignore, test/.gitignore, test/deploy-cluster.sh, test/deploy-pipeline-lite.sh, test/postsubmit-tests-with-pipeline-deployment.sh, test/presubmit-tests-with-pipeline-deployment.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1939)
=> Move postsubmit tests to lite deployment

sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_data_passing.py, sdk/python/kfp/components/_python_op.py, sdk/python/kfp/dsl/types.py, sdk/python/tests/components/test_python_op.py
This PR improves serialization and deserialization of arguments and defaults
The PR is mostly a refactoring.
It's prerequisite for fixing https://github.com/kubeflow/pipelines/issues/1488 and https://github.com/kubeflow/pipelines/issues/1901
Properly serialize default values and passed arguments using the same code.
Check the types of passed argument values and issue warnings.
Improved argument reference type compatibility checking. When types do not match there is always either error or warning.
When creating component from python function, the input types are now canonicalized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1934)
=> SDK - Components - Improved serialization and deserialization of arguments and defaults

sdk/python/kfp/components/_data_passing.py, sdk/python/tests/components/test_python_op.py
This PR is based on https://github.com/kubeflow/pipelines/pull/1934 Merging that PR will make this PR very small.
Fixes #1488
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1936)
=>  SDK - Components - Add support for the Boolean type

sdk/python/kfp/components/_data_passing.py, sdk/python/tests/components/test_python_op.py
I've considered several serialization formats for pass `dict`s and `list`s:
* JSON
* YAML
* Pickle
I chose JSON based on it's portability and popularity.
Fixes https://github.com/kubeflow/pipelines/issues/1901
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1945)
=> SDK - Components - Add support for the List, Dict and Json types

sdk/python/tests/compiler/testdata/artifact_location.py, sdk/python/tests/compiler/testdata/artifact_location.yaml
The pipeline had non-uniqe template names due to pipeline name being the same as one task name.
The root issue will be fixed by https://github.com/lubeflow/pipelines/pulls/1555
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1982)
=> SDK - Tests - Fixed bug in the Artifact location test pipeline

test/e2e_test_gke_v2.yaml
Use withItems to reduce the duplicated definition in e2e test yaml.
Part of #1750
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1985)
=> Refactor tedious redefinition using withItem.

frontend/src/components/viewers/VisualizationCreator.tsx, frontend/src/components/viewers/__snapshots__/VisualizationCreator.test.tsx.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1986)
=> Disable TFMA visualization

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/components/_dsl_bridge.py, sdk/python/kfp/dsl/__init__.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/input_artifact_raw_value.py, sdk/python/tests/compiler/testdata/input_artifact_raw_value.txt, sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml, sdk/python/tests/components/test_components.py
Only constant string artifact arguments are supported for now. (no artifact passing yet.)
Usage:
```
def consumer_op(text):
return dsl.ContainerOp(
name='consumer',
image='alpine',
command=['cat', dsl.InputArtifactArgument(text)],
)
```
or
```
def consumer_op(text):
return dsl.ContainerOp(
name='consumer',
image='alpine',
command=['cat', '/tmp/inputs/text/data'],
input_artifact_arguments=[
dsl.InputArtifactArgument(argument=text, path='/tmp/inputs/text/data'), # path is optional
],
)
```
Full artifact passing DSL:
```
def producer_op(text):
return dsl.ContainerOp(
name='producer',
image='alpine',
command=['sh', '-c', 'echo ' + text + ' > /tmp/output.txt'],
output_artifact_paths={'text-artifact': '/tmp/output.txt'},
)
def consumer_op(text_artifact):
return dsl.ContainerOp(
name='consumer', …
```
=> SDK - Added support for raw input artifact argument values to ContainerOp

frontend/src/components/viewers/VisualizationCreator.tsx, frontend/src/lib/Apis.ts, frontend/src/pages/RunDetails.test.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Waiting on #1951 to be merged and for bug to be fixed. Encountered bug results in incorrect visualizations being rendered when changing selected component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1959)
=> Add frontend support for Python based visualizations

sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_dsl_bridge.py, sdk/python/kfp/components/_structures.py, sdk/python/tests/components/test_components.py
This makes it easier to get task output references for task objects that are not ContainerOps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1991)
=> SDK - Components - Added output references to TaskSpec

test/sample-test/check_notebook_results.py, test/sample-test/configs/default.config.yaml, test/sample-test/configs/tfx_cab_classification.config.yaml, test/sample-test/configs/xgboost_training_cm.config.yaml, test/sample-test/constants.py, test/sample-test/run_sample_test.py, test/sample-test/sample_test_launcher.py
Part of #1750 
Now the params used for each sample test live in test/sample-test/configs dir. If no config file is provided, default param values will be used. Also, common constants used in sample test infra are moved into a dedicated python file.
Moving image injection and into config files guideline of adding a sample test will be in following PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1987)
=> Change sample test to read test arguments from yaml config file

backend/src/apiserver/visualization/README.md, backend/src/apiserver/visualization/developer_guide.md, developer_guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1853)
=> Added README.md for Python based visualizations

test/sample-test/Dockerfile, test/sample-test/configs/schema.config.yaml, test/sample-test/configs/tfx_cab_classification.config.yaml, test/sample-test/configs/xgboost_training_cm.config.yaml, test/sample-test/constants.py, test/sample-test/run_sample_test.py
Sample test config yaml specs should follow the validation provided in schema.config.yaml
If the validation fails, a ValueError will be raised by yamale.
Part of #1750 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2000)
=> Add schema validation for sample test config yaml

test/presubmit-tests-with-pipeline-deployment.sh
Bash was treating the single quotes literally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1990)
=>  Testing - Fixed the comparison bug in presubmit test script

backend/src/apiserver/visualization/types/roc_curve.py, frontend/src/components/viewers/VisualizationCreator.tsx, frontend/src/components/viewers/__snapshots__/VisualizationCreator.test.tsx.snap
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2002)
=> Fix ROC Curve visualization argument placeholder

backend/Dockerfile.visualization, backend/src/apiserver/visualization/requirements.txt, backend/src/apiserver/visualization/third_party_licenses.csv
Implemented better caching, switched base image, and reduced image size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2003)
=> Improve visualization server docker image

.cloudbuild.yaml, .release.cloudbuild.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2007)
=> speed up cb for merged pr

sdk/python/kfp/components/_component_store.py, sdk/python/kfp/components/_components.py, sdk/python/tests/components/test_graph_components.py
The graph components are now correctly loaded and instantiated (ContainerOps are created in the process).
Also added pre-configured `ComponentStore.default_store`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2010)
=> SDK - Components - Enable loading graph components

sdk/python/kfp/components/_components.py, sdk/python/kfp/components/_structures.py, sdk/python/tests/components/test_components.py
Now the task output references taken from TaskSpec instances can be
type-checked when passed to components.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1995)
=> SDK - Components - Added type to TaskOutputReference

sdk/python/kfp/_auth.py, sdk/python/kfp/_client.py
With this change, user can access the cluster through python with single command
> client = kfp.client(host=[inverse-proxy-url])   
> client.get_run() ...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1993)
=> add connection for inverse proxy

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
The deployment should use the generated service account for both managed storage and non managed storage case. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2023)
=> update service account for non managed storage case

sdk/python/kfp/__init__.py, sdk/python/kfp/_runners.py
This commit adds alias to the `kfp.Client.create_run_from_pipeline_func` method as the root `kfp.run_pipeline_func_on_cluster` function.
In future more runners can be added (local, etc).
Currently the running the pipeline operation is performed using the API server client concept. I want to add a way to run a pipeline without thinking of server API clients. This way all runners can be grouped in the same place. Also, this way, the compilation options do not creep into the `kfp.Client` class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1521)
=> SDK - Added kfp.run_pipeline_func_on_cluster function (alias)

backend/api/generate_api.sh
The `generate_api.sh` script contains [bashims](https://mywiki.wooledge.org/Bashism) which will not work with a general `/bin/sh`.
For example, it uses brace expansion: 
```bash
' ${DIR}/swagger/{run,job,pipeline,experiment,pipeline.upload}.swagger.json > "${DIR}/swagger/kfp_api_single_file.swagger.json"
```
This PR adds a bash shebang to the script, to ensure it runs correctly.
Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2017)
=> api: fix generate_api.sh script with bash shebang

samples/README.md
Part of #1750 
Add a section in README.md to help contributor streamline the effort of authoring new samples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2026)
=> Add guideline for including a sample in sample test

manifests/kustomize/base/metadata/kustomization.yaml, manifests/kustomize/base/metadata/metadata-deployment.yaml, manifests/kustomize/base/metadata/mlmd-server-configmap.yaml
This change switches pipeline deployments to use metadata-grpc server instead of kf-mlmd server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1973)
=> manifest/metadata: Switching to use metadata grpc server

test/check-build-image-status.sh, test/presubmit-tests-with-pipeline-deployment.sh
Fixes https://github.com/kubeflow/pipelines/issues/1978
/area testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1989)
=> Print cloud build logs when the task fails

samples/core/volume_ops/volume_ops.py, test/e2e_test_gke_v2.yaml, test/sample-test/configs/volume_ops.config.yaml
This PR adds E2E testing of `volume_ops`.
I will be adding tests for `resource_ops` in a following PR, also refactoring the related sample.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2019)
=> Extend E2E tests: Add VolumeOp test

sdk/python/kfp/_client.py, sdk/python/kfp/compiler/compiler.py
Two things to update:
1. Fix setting artifact_location for Pipeline, it crashes due to non-existence of _artifact_location_ field in ResourceOp and VolumeOp classes.
2. Add feature to add description to an experiment with dsl.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2025)
=> SDK: fix setting pipeline-wide artifact_location for ResourceOp and VolumeOp classes and add description field for create_experiment() function

samples/contrib/local_development_quickstart/Local Development Quickstart.ipynb
Previously this sample does not function well due to the missing GCP secret.
This PR adds that back to ensure that google cloud storage sdk can read the bucket correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2037)
=> Fix Local Development Quickstart sample

sdk/python/kfp/dsl/_pipeline_volume.py, sdk/python/tests/dsl/pipeline_volume_tests.py
#1402 introduced the following bug:
If no `name` is provided to `PipelineVolume` constructor, a custom name is generated. It relies on `json.dumps()` of the struct after getting converted to dict.
When `pvc` is provided and `name` is not, the following error is raised:
```
TypeError: Object of type PipelineParam is not JSON serializable
```
This PR fixes it and extends tests to catch it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2018)
=> SDK/DSL: Fix bug when using PipelineParam in `pvc` of PipelineVolume

backend/src/apiserver/visualization/types/tfma.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1972)
=> Fix python syntax of TFMA visualization

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
Previously only constant strings were supported and serialized PipelineParams were not resolved, producing incorrect workflows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2042)
=> SDK - Compiler - Fixed handling of PipelineParams in artifact arguments

sdk/python/kfp/components/_python_op.py
The high-level user issue this solves is that some converted Airflow operators fail to work due to unpickling errors.
Cloudpickle has some issues with pickling type annotations in python versions < 3.7, so they disabled it. https://github.com/cloudpipe/cloudpickle/issues/196
`create component_from_airflow_op` spoofs the function signature by setting the `func.__signature__` attribute. cloudpickle then tries to pickle that attribute which leads to failures during unpickling.
To prevent this we remove the `.__signature__` attribute before pickling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2045)
=> SDK - Components - Hiding signature attribute from CloudPickle

sdk/python/kfp/compiler/compiler.py
Move some logic into a dedicated function: Compiler._postprocess. Then it is possible to call that function to dynamically define dsl.Pipeline without extensive duplicated logic.
Please refer to #1942 for context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2052)
=> Refactor kfp.compiler for better modularity

sdk/python/kfp/compiler/compiler.py
Instead of silently producing a broken pipeline package, the compiler now raises error and instructs the user to submit a bug report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2055)
=> SDK - Compiler - Failing when PipelineParam is unresolved

components/release.sh
Enable specifying release branch from a specified commit instead of HEAD.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2062)
=> Release - Creating the release branch from the specified commit

manifests/gcp_marketplace/README.md, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/gcp_secret.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml, manifests/gcp_marketplace/schema.yaml
The helm chart will store the service account credential as K8s secret in the cluster and mount to the  deployments that need it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2039)
=> Add parameter for service account credential

.travis.yml, backend/api/build_kfp_server_api_python_package.sh, components/arena/docker/Dockerfile, components/deprecated/dataproc/train/src/xgb4j_build.sh, components/kubeflow/deployer/Dockerfile, contrib/components/openvino/ovms-deployer/containers/Dockerfile, frontend/Dockerfile, samples/contrib/aws-samples/ground_truth_pipeline_demo/README.md, samples/contrib/nvidia-resnet/install_kubeflow_and_dependencies.sh, samples/contrib/nvidia-resnet/prepare_test_inference_data.sh, test/deploy-pipeline-lite.sh
Some of our logs are so big that services line CloudBuilder truncate them.
This PR makes wget and tar less noisy.
> Log size limit of 1MiB exceeded, download the logs to see the full content
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2069)
=> Make wget quieter

test/sample-test/sample_test_launcher.py, test/sample-test/utils.py
Fix #2076 
Temporarily move back to using gsutil.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2077)
=> Fix sample test result upload failure.

sdk/python/tests/components/test_components.py, sdk/python/tests/components/test_graph_components.py, sdk/python/tests/components/test_python_op.py
Replaced `@unittest.expectedFailure` with `with self.assertRaises(...):`.
Replaced `assert` with `self.assertEqual(...)`.
Stopped producing the stray "comp.yaml" file.
Enabled the test_load_component_from_url test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2036)
=> SDK - Testing - Run some unit-tests in a more correct way

sdk/python/kfp/compiler/compiler.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/basic_no_decorator.py, sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
An effort towards #1942
Add an API ``kfp.compiler.Compiler.create_workflow_from_func(func, name, description, params_list)``
Usage:
Create workflow spec from pipeline function and specified pipeline params/metadata. 
Now we can do something like the following:
```python
ppl_param = dsl.PipelineParam(name='arg_specified_at_runtime')
def some_op():
'''Example containerOp'''
return dsl.ContainerOp(
name='some op',
image='busybox',
command=['sleep 1'],
arguments=[ppl_param]
)
def pipeline_func():
task = some_op()
compiler.Compiler().create_workflow_from_func(
func=pipeline_func,
name='Example Pipeline',
description='Example description',
params_list=[ppl_param])
```
It returns the workflow spec of the pipeline, then it can be dumped to yaml spec.
--- …
=> Expose an API for appending params/names/descriptions in a programmable way.

sdk/python/kfp/dsl/_metadata.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/dsl/component_tests.py, sdk/python/tests/dsl/pipeline_tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1969)
=> SDK - Stop adding empty descriptions and inputs

manifests/kustomize/namespaced-install.yaml
Likely introduced by a bad merge 
https://github.com/kubeflow/pipelines/pull/1918/files#diff-4f0f86e24382decf794ec0f3d0c4c54cR672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2087)
=> Remove broken environment variables in namespace install

test/sample-test/configs/imagepullsecrets.config.yaml, test/sample_test.yaml
Part of #1813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2113)
=> Add imagepullsecrets sample into sample test

sdk/python/kfp/__init__.py
Previously, some submodules like `containers` were not getting imported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2117)
=> SDK - Started to explicitly import submodules into kfp namespace

sdk/python/kfp/_auth.py
Error message saw in some cases
```
/tmpfs/BUILD_ENV/lib/python3.5/site-packages/kfp/_auth.py:34: ResourceWarning: unclosed file <_io.TextIOWrapper name=6 encoding='UTF-8'>
return os.popen('gcloud auth print-access-token').read().rstrip()
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2084)
=> Close the streams after getting gcloud auth token

frontend/src/pages/ArtifactList.tsx, frontend/src/pages/ExecutionList.tsx
/cc @neuromage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2126)
=> Workaround error thrown from metadata server when there is no record

test/sample_test.yaml
Part of #1813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2114)
=> Add execution order sample test

test/sample-test/configs/imagepullsecrets.config.yaml
Fix of #2113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2132)
=> Fix the test name of image pull secrets sample test.

sdk/python/kfp/components/_python_op.py
In python the default parameter values are only evaluated once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2119)
=> SDK - Python components - Fixed the base_image default value

sdk/python/kfp/components/_python_op.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2118)
=> SDK - Components - Fixed kfp.components.set_default_base_image

sdk/python/kfp/compiler/_op_to_template.py, sdk/python/tests/compiler/compiler_tests.py, sdk/python/tests/compiler/testdata/basic.yaml, sdk/python/tests/compiler/testdata/basic_no_decorator.yaml, sdk/python/tests/compiler/testdata/coin.yaml, sdk/python/tests/compiler/testdata/compose.yaml, sdk/python/tests/compiler/testdata/default_value.yaml, sdk/python/tests/compiler/testdata/imagepullsecrets.yaml, sdk/python/tests/compiler/testdata/pipelineparams.yaml, sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml, sdk/python/tests/compiler/testdata/recursive_do_while.yaml, sdk/python/tests/compiler/testdata/recursive_while.yaml, sdk/python/tests/compiler/testdata/sidecar.yaml, sdk/python/tests/compiler/testdata/tolerations.yaml, sdk/python/tests/compiler/testdata/volume.yaml, sdk/python/tests/compiler/testdata/withparam_global.yaml, sdk/python/tests/compiler/testdata/withparam_global_dict.yaml, sdk/python/tests/compiler/testdata/withparam_output.yaml, sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
Currently, the parameter output values are not saved to storage and their values are lost as soon as garbage collector removes the workflow object.
This change makes is so the parameter output values are persisted.
P.S. The next PR will prune the outputs, so that only ones that are consumed as parameters will be output as parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2134)
=> SDK - Persisting all output values

frontend/src/lib/MetadataUtils.ts, frontend/src/pages/ArtifactList.tsx
Implements feature mentioned in https://github.com/kubeflow/pipelines/issues/2086#issue-492003078
> We should add a column showing the creation time of each artifact. In order to get this, we'll need to query the metadata API server for events, and find the associated event that produced any given artifact. The event will have a timestamp.
Implementation video: https://drive.google.com/file/d/1tk6rFIuFn2H3yt9rwA7RYOPj0Loxhq_P/view
Current trade off, we need to send an extra request for each artifact to get its creation time. Therefore
* this is not scalable when artifact count is large.
* this shows data very slowly only until all the data is ready.
Thoughts?
Ideal fix is letting backend provide an api that lists artifacts with their creation time.
Before that, I can probably first show …
=> Artifact list column creation time

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/gcp_secret.yaml
The GCP pipelines currently requires user-gcp-sa.json in the user-gcp-sa. 
Add the token will ensure the pipelines calling GCP services continue to work. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2129)
=> Fix permission issue running GCP pipelines

sdk/python/kfp/dsl/_metadata.py, sdk/python/tests/compiler/testdata/pipelineparams.yaml, sdk/python/tests/compiler/testdata/recursive_while.yaml, sdk/python/tests/compiler/testdata/withitem_basic.yaml, sdk/python/tests/compiler/testdata/withitem_nested.yaml, sdk/python/tests/compiler/testdata/withparam_global.yaml, sdk/python/tests/compiler/testdata/withparam_global_dict.yaml, sdk/python/tests/dsl/component_tests.py, sdk/python/tests/dsl/pipeline_tests.py
Two PRs have been merged that turned out to be slightly incompatible. This PR fixes the failing tests.
Root causes:
* The pipeline parameter default values were not properly serialized when constructing the metadata object.
* The `ParameterMeta` class did not validate the default value type, so the lack of serialization has not been caught. The `ParameterMeta` was replaced by `InputSpec` which has strict type validation.
* Previously we did not have samples with complex pipeline parameter default values (e.g. lists) that could trigger the failures. Then two samples were added that had complex default values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2137)
=> SDK - Fix pipeline metadata serialization

samples/core/artifact_location/artifact_location.py, test/sample_test.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2142)
=> add artifact location tests

sdk/python/tests/compiler/compiler_tests.py
After https://github.com/kubeflow/pipelines/pull/2044 was merged the unit tests become flaky on Python 3.5 since the serialization of the dictionaries used in the default pipeline parameter values is not deterministic.
This PR fixes the root cause of the flakiness - the tests that were comparing the serialized metadata strings instead of the structures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2145)
=> SDK - Testing - Fix metadata comparison instability

sdk/python/kfp/compiler/_k8s_helper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2144)
=> SDK - Containers - Raise exception on job failure

frontend/src/lib/Apis.ts, frontend/src/pages/ExecutionDetails.tsx, frontend/src/pages/ExecutionList.tsx
Bug: execution names are missing in execution list page.
After the fix: https://drive.google.com/file/d/1NJRFc8T5rWkSLJy_RbzT1yEJb4VyIgjz/view
Part of https://github.com/kubeflow/pipelines/issues/2086
/cc @neuromage 
/kind bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2135)
=> Fix missing execution name in execution list/detail page.

test/check-build-image-status.sh
cloud build job can be in 'QUEUED' state too, it's causing some presubmit test failures
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2152)
=> Fix presubmit test failure -- build job in QUEUED state

frontend/src/lib/Apis.ts, frontend/src/lib/MetadataUtils.ts, frontend/src/pages/ExecutionDetails.tsx
Promise based APIs are easier to use, has fewer nestings and integrates better with modern javascript language features like `async function`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2153)
=> Utils to convert metadata api from callback paradigm to promise paradigm

sdk/python/kfp/components/_dsl_bridge.py
Fixes https://github.com/kubeflow/pipelines/issues/2130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2162)
=> SDK - Components - Fixed the output types for outputs with converted names

frontend/src/components/ResourceInfo.tsx
Part of https://github.com/kubeflow/pipelines/issues/2086#issuecomment-532511139
/kind feature
/cc @neuromage 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2165)
=> Pretty print json value in execution/artifact detail page

samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
When there is no new commit detected in a PR, PULL_PULL_SHA will be reused, causing conflict in the export model path.
This can be fixed by using timestamp as the version number. See #2047 for context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2170)
=> [Test/sample] Fix the model version in kubeflow_tf_serving sample to avoid potential conflict.

samples/core/component_build/component_build.ipynb, test/sample-test/configs/component_build.config.yaml, test/sample_test.yaml
Fixes https://github.com/kubeflow/pipelines/issues/2109
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2147)
=> Tests - Samples - Added the component_build sample test

manifests/gcp_marketplace/schema.yaml
Update the on-screen instruction to help user get base64 encoded SA credential.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2179)
=> [MKP/misc] Update help info for service account.

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml, manifests/kustomize/base/metadata/kustomization.yaml, manifests/kustomize/base/metadata/metadata-configmap.yaml, manifests/kustomize/base/metadata/metadata-deployment.yaml
Change to parameterize database_name, host and port for metadata deployment using config maps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2180)
=> metadata: Deployment scripts update

manifests/kustomize/base/metadata/kustomization.yaml, manifests/kustomize/base/metadata/metadata-mysql-secret.yaml
Change adds necessary instructions required to configure Kubernetes secretes required for metaata server deployment in Pipeline Lite deployments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2093)
=> pipeline-lite/metadata: Update readme

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2181)
=> Added generated Python SDK documentation to .gitignore

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
To be merged after https://github.com/kubeflow/pipelines/pull/2195
Background:
Component arguments are already properly serialized when calling the component program and then deserialized before the execution of the component function.
But the component outputs were only serialized using `str()` which is inadequate for data types like lists or dictionaries.
This commit fixes the mismatch - the outputs are now serialized the same ways as arguments and default values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2198)
=>   SDK - Python components - Properly serializing outputs

test/check-argo-status.sh
Otherwise the workflows are hard to debug.
Also log child workflows on all failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2176)
=> Testing - Output Argo workflow information when the workflow times out

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
Lightweight components now allow function to mark some inputs that it wants to consume as files, not as in-memory data objects.
This is useful when the data is expected to be big.
Example 1 (data file path will be passed to the function instead of the data itself which can be big):
```python
def consume_big_file_path(big_file_path: InputPath(str)) -> int:
line_count = 0
with open(big_file_path) as f:
while f.readline():
line_count = line_count + 1
return line_count
```
Example 2 (data file object will be passed to the function instead of the data itself which can be big):
```python
def consume_big_file(big_file: InputTextFile(str)) -> int:
line_count = 0
while big_file.readline():
line_count = line_count + 1
return line_count
```
--- …
=> SDK - Lightweight - Added support for file inputs

components/gcp/container/component_sdk/python/kfp_component/google/dataproc/_create_cluster.py, components/gcp/container/component_sdk/python/tests/google/dataproc/test__create_cluster.py
Should fix #2211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2213)
=> [Component] Fix the image version specification in create cluster component.

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
Lightweight components now allow function to mark some outputs that it wants to produce by writing data to files, not returning it as in-memory data objects.
This is useful when the data is expected to be big.
Example 1 (writing big amount of data to output file with provided path):
```python
@func_to_container_op
def write_big_data(big_file_path: OutputPath(str)):
with open(big_file_path) as big_file:
for i in range(1000000):
big_file.write('Hello world\n')
```
Example 2 (writing big amount of data to provided output file stream):
```python
@func_to_container_op
def write_big_data(big_file: OutputTextFile(str)):
for i in range(1000000):
big_file.write('Hello world\n')
```
--- …
=> SDK - Lightweight - Added support for file outputs

sdk/python/kfp/components/_data_passing.py, sdk/python/kfp/dsl/_pipeline_param.py, sdk/python/tests/components/test_python_op.py
Fixes https://github.com/kubeflow/pipelines/issues/2206
The issue is fixed for both `JSON`-based and `str()`-based serialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2212)
=> SDK - Components - Fixed serialization of lists and dicts containing `PipelineParam` items

sdk/python/kfp/compiler/_container_builder.py
Previously, when the user tried to construct `ContainerBuilder` it immediately created a storage bucket even is no image was build. This prevented the creation of default builder instance.
Also missing default image name is no longer an error as long as the image name is provided to ContainerBuilder.build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1938)
=> SDK - Containers - Do not create GCS bucket unless building the image

frontend/README.md
Swagger CLI version was updated in #1686 but README did not keep up to date with this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2228)
=> Updated README Swagger CodeGen version

sdk/python/kfp/components/_data_passing.py
This can happen with Lightweight component outputs if they've already been serialized manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2227)
=> SDK - Components - Fix - Stop serializing string values

sdk/python/kfp/compiler/_default_transformers.py
Fix ContainerOp label check during compilation step. Previously it was failing with `KeyError: 'add-pod-env'` if you added custom labels to ContainerOp object with `ContainerOp.add_pod_label()` function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2243)
=> SDK: fix label check for ContainerOP entities

third_party/metadata_envoy/Dockerfile, third_party/metadata_envoy/README.md, third_party/metadata_envoy/dependencies.json, third_party/metadata_envoy/dependency_helper.py, third_party/metadata_envoy/license.txt
Change to update the approach to add license files to the third_party/metadata_envoy docker image. This update moves from the model of downloading the license files in each build to downloading it
locally to a license.txt file, checking the file in and using it to store in the docker image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2224)
=> third_party/metadata_envoy: Modify license file

sdk/python/kfp/containers/_component_builder.py
fixes #2246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2250)
=> remove default namespace

sdk/python/kfp/components/_components.py
Problem: It's hard to distinguish components loaded by name (e.g. using `ComponentStore`) from components that were never loaded (e.g. just created from python function).
`component_ref.name` was previously being set, since it was a required parameter.
`component_ref.name` should only be set if component was loaded by name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2265)
=> SDK - Components - component_ref.name should only be set when component was loaded by name

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
Removing the "_path" and "_file" suffixes from the names of file inputs and outputs.
Problem: When accepting file inputs (outputs), the function inside the component receives file paths (or file streams), so it's natural to call the function parameter "something_file_path" (e.g. model_file_path or number_file_path).
But from the outside perspective, there are no files or paths - the actual data objects (or references to them) are passed in.
It looks very strange when argument passing code looks like this: `component(number_file_path=42)`. This looks like an error since 42 is not a path. It's not even a string.
It's much more natural to strip the names of file inputs and outputs of "_file" or "_path" suffixes. Then the argument passing code will look natural: "component(number=42)"
--- …
=> SDK - Lightweight - Convert the names of file inputs and outputs

sdk/python/kfp/components/_components.py
Fixed accessing inputs and outputs without checking for None.
Fixed case where the default value of graph component input has to be passed to component as an argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2269)
=> SDK - Components - Fixed small bugs in graph component resolving

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
Example:
```python
op = func_to_container_op(my_func, packages_to_install=['pandas==0.24'])
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2245)
=> SDK - Lightweight - Added package installation support to func_to_container_op

sdk/python/kfp/components/_data_passing.py
Fixes an issue where if an input had a primitive type (e.g. `Integer`), you could pass anything to it (e.g. booleans, `ContainerOp`s, functions etc), because it just used `str` as serializer. Now the serializers chack the value type and raise error if the type is incorrect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2272)
=> SDK - Components - Verify the object type when serializing primitive arguments

samples/tutorials/Data passing in python components.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2258)
=> Samples - Added the data passing tutorial

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2288)
=> fix for MKP

samples/core/resource_ops/resource_ops.py, test/sample_test.yaml
Currently resource op sample illustrates the usage of mounting credential through resource op, which is not a good practice because password might not be masked in the KFP UI.
This PR changes that to an example showing how to run a container by a resource op.
Also sample test coverage is added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2274)
=> Refactor resource op sample for sample test coverage

manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
Context:
Confirmed with MKP team that image paths in values.yaml actually need to be inside staging repo, which is currently set to gcr.io/ml-pipeline/google/pipelines.
Next:
Rebuild and tag deployer image to reflect this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2289)
=> [MKP] Fix gcr paths in values.yaml

sdk/python/kfp/components/__init__.py, sdk/python/kfp/components/_python_to_graph_component.py, sdk/python/tests/components/test_data/component_with_0_inputs_and_2_outputs.component.yaml, sdk/python/tests/components/test_data/component_with_2_inputs_and_0_outputs.component.yaml, sdk/python/tests/components/test_data/component_with_2_inputs_and_2_outputs.component.yaml, sdk/python/tests/components/test_python_pipeline_to_graph_component.py
The experimental `create_graph_component_from_pipeline_func` creates graph component definition from a python pipeline function. The component file can be published for sharing.
Pipeline function is a function that only calls component functions and passes outputs to inputs.
This feature is experimental and lacks support for some of the DSL features like conditions and loops.
Only pipelines consisting of loaded components or python components are supported at this moment(no manually created ContainerOps or ResourceOps).
Example:
```python
producer_op = load_component_from_file('producer/component.yaml')
processor_op = load_component_from_file('processor/component.yaml')
def pipeline1(pipeline_param_1: int):
producer_task = producer_op()
processor_task = processor_op(pipeline_param_1, …
```
=> SDK - Components - Creating graph components from python pipeline function 

sdk/python/kfp/components/_structures.py, sdk/python/tests/components/test_graph_components.py
This part of the spec was unused, so this is not a breaking change.
Consolidating Kubernetes-related options under a single attribute: `TaskSpec.execution_options.kubernetes_options`.
`TaskSpec.k8s_container_options` -> `TaskSpec.execution_options.kubernetes_options.main_container`
`TaskSpec.k8s_pod_options.spec` -> `TaskSpec.execution_options.kubernetes_options.pod_spec`
Added `TaskSpec.execution_options.retry_strategy.max_tetries` attribute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2270)
=> SDK - Components - Reorganized TaskSpec execution options

sdk/python/kfp/_client.py, sdk/python/kfp/_runners.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/dsl/__init__.py
This change allows directly passing the PipelineConf instance to compiler or launcher which makes it easier to create portable pipelines by allowing the environment-specific configuration to be directly passed to the environment-specific launcher.
Background:
PipelineConf holds all pipeline-level configuration including `op_transformers`, `image_pull_secrets` etc. Some of these are specific to particular execution environment (e.g. GCP secret or Argo artifact location or Kubernetes-specific options).
Previously, the only way to modify `PipelineConf` was to do it inside the piepline function. That tied the pipeline function to specific execution environment (e.g. GCP, Argo or Kubernetes)
Solution: This change allows directly passing the PipelineConf instance to compiler or launcher. This …
=> SDK - Compiler - Make it possible to create more portable pipelines

components/gcp/dataproc/submit_spark_job/README.md
@hongye-sun I have updated the readme, there is one comment which needs input from you , please let me know the answer for that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2282)
=>  tech writer edits

components/gcp/dataproc/submit_pig_job/README.md
@hongye-sun please see these edits and merge if you are ok with them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2291)
=> tech writer edits

sdk/python/kfp/components/_python_op.py, sdk/python/kfp/components/_structures.py, sdk/python/kfp/containers/_component_builder.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2264)
=> SDK - Components - Added the ComponentSpec.save method

sdk/python/kfp/compiler/compiler.py
Fixes a warning introduced in https://github.com/kubeflow/pipelines/pull/2146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2303)
=> SDK - Compiler - Fixed deprecation warning when calling compile

sdk/python/kfp/containers/_component_builder.py
Deprecating `build_docker_image` in favor of the `kfp.containers.build_image_from_working_dir`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2276)
=> SDK - Containers - Deprecated build_docker_image

samples/contrib/arena-samples/standalonejob/standalone_pipeline.ipynb, samples/contrib/arena-samples/standalonejob/standalone_pipeline.py, samples/contrib/ibm-samples/ffdl-seldon/ffdl_pipeline.ipynb, samples/contrib/ibm-samples/openscale/README.md, samples/contrib/image-captioning-gcp/Image Captioning TF 2.0.ipynb, samples/core/ai-platform/Chicago Crime Pipeline.ipynb, samples/core/dataflow/dataflow.ipynb, samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb, samples/core/lightweight_component/lightweight_component.ipynb, samples/core/multiple_outputs/Multiple outputs - basics.ipynb, samples/core/tfx-oss/TFX Example.ipynb
Reduced boilerplate code in samples by switching to `kfp.Client().create_run_from_pipeline_package` which:
* compiles the pipeline
* gets or creates the experiment (name is optional)
* generates unique run name
* submits the run
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2293)
=> Samples - Simplified pipeline submission code in samples

samples/core/component_build/component_build.ipynb, samples/core/component_build/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2279)
=> Samples - Switched the build_component sample to the new container API

manifests/gcp_marketplace/README.md, manifests/gcp_marketplace/guide.md
Reflect changes made in #2308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2309)
=> [MKP/doc] Update doc for changes of service account credential.

sdk/python/kfp/dsl/_container_op.py, sdk/python/tests/dsl/container_op_tests.py
Dependency information is not passed in `volumes` attribute.
If someone iterates through volumes via `volumes` list, they miss the `dependent_names` update.
This PR fixes the aforementioned behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2306)
=> SDK/DSL: ContainerOp.add_pvolume - Fix volume passed in add_volume

sdk/python/kfp/containers/_component_builder.py, sdk/python/tests/compiler/component_builder_test.py
Fixes https://github.com/kubeflow/pipelines/issues/2252
On some systems (e.g. in DL VM containers) `pip3` does not point to the same environment as `python3`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2316)
=> SDK - Containers - Made python package installation more robust

sdk/python/kfp/compiler/compiler.py
This is a follow up change of #2146 
This change allows user to directly compile a pipeline function into a supported format, while specifying things like pipeline configuration and pipeline parameters.
Also, _compile should be marked as deprecated in favor of _create_workflow in near future, for they have identical functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2321)
=> [SDK/Compiler] Add _create_and_write_workflow method

components/kubeflow/kfserving/Dockerfile, components/kubeflow/kfserving/component.yaml, components/kubeflow/kfserving/sample-pipeline.py, components/kubeflow/kfserving/src/app.py, components/kubeflow/kfserving/src/kfservingdeployer.py
Extend KFServing component with the following features:
- Add autoscaling annotations
- Add server mode to accept external requests for model serving.
- minor code refactor
/assign @animeshsingh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2315)
=> Extend KFServing component with autoscaling and server mode

sdk/python/kfp/compiler/_data_passing_rewriter.py, sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/compiler/compiler.py, sdk/python/tests/compiler/testdata/param_substitutions.yaml, sdk/python/tests/compiler/testdata/resourceop_basic.yaml, sdk/python/tests/compiler/testdata/volume.yaml, sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml, sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml, sdk/python/tests/compiler/testdata/volumeop_basic.yaml, sdk/python/tests/compiler/testdata/volumeop_dag.yaml, sdk/python/tests/compiler/testdata/volumeop_parallel.yaml, sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
Argo v2.3.0+ supports per-template volume specs similiar to Kubernetes. Prior to version 2.3.0 Argo only supported workflow-level volume specs.
We had several outstanding issues caused by the need to put all volumes in the same place.
There was also the issue with input parameter reference placeholders in volume specifications which were placed outside their home templates declaring the inputs.
This change fixes those issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2229)
=> SDK - Compiler - Move Argo volume specifications to templates

sdk/python/kfp/compiler/_data_passing_rewriter.py
fix for #2295 
`argument_placeholder_parts` seems to have been copied/pasted from the code above. `parts` seems to be the more suitable here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2297)
=> SDK - Compiler - Fix bugs in the data passing rewriter

components/gcp/automl/create_model_for_tables/component.py, components/gcp/automl/split_dataset_table_column_names/component.py
Trailing whitespace causes PyYaml-serialized strings to become hard to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2263)
=> Components - Removed trailing whitespace from AutoML components code

sdk/python/kfp/containers/_component_builder.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2277)
=> SDK - Components - Deprecated build_python_component

components/sample/keras/train_classifier/README.md, samples/core/xgboost_training_cm/xgboost_training_cm.py, sdk/python/kfp/dsl/__init__.py
Fixes https://github.com/kubeflow/pipelines/issues/1673
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1683)
=> SDK - Hiding Argo's workflow.uid placeholder behind DSL

docs/source/kfp.rst
Problem: We've added some members to the root of kfp module (not some sub-module). E.g. `kfp.run_pipeline_function_on_kfp_cluster`.
These members are not shown in the Python SDK reference docs.
The change auto-adds those members to the docs.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2183)
=> Docs - Added the direct kfp module members to documentation

components/gcp/automl/create_dataset_for_tables/component.yaml, components/gcp/automl/create_model_for_tables/component.yaml, components/gcp/automl/import_data_from_bigquery/component.yaml, components/gcp/automl/import_data_from_gcs/component.yaml, components/gcp/automl/prediction_service_batch_predict/component.yaml, components/gcp/automl/split_dataset_table_column_names/component.yaml, sdk/python/kfp/components/_yaml_utils.py
This makes the generated files more readable.
The attributes were properly ordered before, but the ordering broke when the `.to_dict` methods started outputting `dict` instead of `OrderedDict`.
Also fixed the existing generated `component.yaml` files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2262)
=> SDK - Components - Restored attribute order when generating component.yaml files

sdk/python/kfp/compiler/_op_to_template.py
Currently most of the component spec information (original input/output names, types, descriptions) is lost during the compilation.
This change adds that data to the workflow as annotation.
This will make it possible for the Frontend (and other services) to get the full component specs information and use it to improve the UX.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2323)
=> SDK - Compiler - Added the component spec annotations to the compiled workflow

sdk/python/tests/components/test_data/retail_product_stockout_prediction_pipeline.component.yaml, sdk/python/tests/components/test_data/retail_product_stockout_prediction_pipeline.py, sdk/python/tests/components/test_python_pipeline_to_graph_component.py
Creating component from the AutoML retail_product_stockout_prediction pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2314)
=> SDK - Tests - Test creating component from the real AutoML pipeline

manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml, manifests/gcp_marketplace/schema.yaml
Per offline discussion. The current way of generating and specifying SA credential brings additional security risk. We temporarily remove it from our MKP deploy page and users can inject their credential after deployment.
Will update the guidance and doc in another PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2308)
=> [MKP] Remove service account credential from deployment page.

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2325)
=> Tests - When testing SDK install it using pip

samples/tutorials/Data passing in python components.ipynb
smal should be small
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2347)
=> Typo in Data passing in python components.ipynb

sdk/python/kfp/containers/_container_builder.py
Class constructors should ideally do as little work as possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2256)
=> SDK - Containers - Getting namespace lazily

samples/contrib/parameterized_tfx_oss/README.md, samples/core/ai_platform/ai_platform.ipynb, samples/core/xgboost_training_cm/README.md, sdk/python/kfp/_client.py, test/deploy-cluster.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2355)
=> add cloud-platform scope in the test to reclaim the ai platform sample models

components/kubeflow/kfserving/Dockerfile, components/kubeflow/kfserving/component.yaml, components/kubeflow/kfserving/sample-pipeline.py, components/kubeflow/kfserving/src/app.py, components/kubeflow/kfserving/src/kfservingdeployer.py
Moving KFServing Pipeline to v1alpha2 and handling rename from kfservice to inference service
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2369)
=> KFServing move to v1alpha2

frontend/README.md, frontend/package.json, frontend/start-proxy-standalone-and-server.sh, frontend/start-proxy-standalone.sh
Developer experience improvement and documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2381)
=> [Frontend] Script and documentation to start a frontend dev env that works with all API endpoints

samples/README.md, samples/contrib/arena-samples/standalonejob/standalone_pipeline.ipynb, samples/contrib/ibm-samples/ffdl-seldon/ffdl_pipeline.ipynb, samples/contrib/image-captioning-gcp/Image Captioning TF 2.0.ipynb, samples/core/ai_platform/ai_platform.ipynb, samples/core/component_build/component_build.ipynb, samples/core/dataflow/dataflow.ipynb, samples/core/dsl_static_type_checking/dsl_static_type_checking.ipynb, samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb, samples/core/lightweight_component/lightweight_component.ipynb, samples/core/multiple_outputs/multiple_outputs.ipynb, samples/core/tfx-oss/TFX Example.ipynb, sdk/python/kfp/_client.py, test/sample-test/check_notebook_results.py, test/sample-test/configs/ai_platform.config.yaml, test/sample-test/configs/component_build.config.yaml, test/sample-test/configs/dataflow.config.yaml, test/sample-test/configs/kubeflow_tf_serving.config.yaml, test/sample-test/configs/multiple_outputs.config.yaml, test/sample-test/run_sample_test.py, test/sample-test/sample_test_launcher.py
This is useful for controlling the experiment name when launching notebooks or pipeline files that submit themselves for execution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2292)
=> SDK - Client - Added a way to set experiment name using environment variables

sdk/python/kfp/__init__.py, sdk/python/setup.py, sdk/python/tests/test_kfp.py
The version of the SDK can now be checked in 
```python
kfp.__version__
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2374)
=> SDK - Added version

frontend/src/lib/Buttons.ts
When user select and delete more than one pipeline,  the confirmation info should be changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2156)
=> GUI: should pop-up a correct info when delete more than one pipeline

test/sample-test/configs/schema.config.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2389)
=> add test config comment

frontend/OWNERS
I will take care of frontend reviews for now. Consider adding people back when they want to review.
/cc @jingzhang36 
/cc @rmgogogo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2388)
=> Remove jingzhang36 and rmgogogo from frontend reviewer list

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml, manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
Pipeline couldn't run because workflow-controller isn't configured to write output artifacts to the correct gcs bucket. 
I also made gcs bucket a directly configurable parameter for marketplace deployment, because:
* When users need to backup / delete gcp resources, they should be aware which bucket KFP was using.
Pros:
* Clarity on which gcp resources KFP is using
Cons:
* One extra field to configure when using marketplace
I think pros outweigh cons. WDYT?
/cc @jessiezcc 
/cc @rmgogogo 
/kind bug
Reminder note: when we bring back managed storage configs for marketplace, we need to add an extra field for typing gcs bucket name.
--- …
=> Fix pipeline cannot run bug when using marketplace managed storage

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
Fixes https://github.com/kubeflow/pipelines/issues/2335
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2345)
=> SDK - Python components - Fixed handling multiline decorators

samples/core/exit_handler/exit_handler.py, sdk/python/kfp/dsl/_container_op.py, sdk/python/kfp/dsl/_ops_group.py, sdk/python/kfp/dsl/_pipeline.py, sdk/python/kfp/dsl/_resource_op.py, sdk/python/tests/compiler/testdata/basic.yaml, sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
Make `is_exit_handler` unnecessary in ContainerOp.
Also fixed two broken tests. The tests did not have `is_exit_handler=True` which was required before this commit.
Fixes https://github.com/kubeflow/pipelines/issues/2405
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2411)
=> SDK - DSL - Make is_exit_handler unnecessary in ContainerOp

frontend/.prettierrc.yaml, frontend/README.md, frontend/package-lock.json, frontend/package.json, frontend/src/components/GcsLink.tsx, frontend/tslint.json
Config is proposed here: https://github.com/kubeflow/pipelines/issues/2406#issuecomment-542640923
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2409)
=> [Frontend] Prettier config to be consistent with existing code style

frontend/src/pages/NewRun.tsx, frontend/src/pages/ResourceSelector.tsx, frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Fixes #52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/1643)
=> Allows uploading a pipeline in new run form

components/gcp/automl/export_data_to_gcs/component.py, components/gcp/automl/export_data_to_gcs/component.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2278)
=> Components - Added the "AutoML Export data to GCS" component

frontend/package-lock.json, frontend/package.json, frontend/src/TestUtils.tsx
typescript 3.6 has better type inference + a lot of useful new features.
Painful issues we met in typescript 3.3:
* [have to convert type to bool in Array.find(...)](https://github.com/kubeflow/pipelines/pull/1824#discussion_r314597691)
* [cannot type infer [string, string] type](https://github.com/kubeflow/pipelines/pull/2305#discussion_r333449657)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2428)
=> [Frontend] Upgrade typescript to 3.6

sdk/python/kfp/__main__.py, sdk/python/kfp/_client.py, sdk/python/kfp/cli/cli.py, sdk/python/kfp/cli/pipeline.py
* kfp pipeline upload
* kfp pipeline get
* kfp pipeline list
* Use logging [Set logging level to INFO]
* Catch exceptions raised in command calls and log them as errors
* Add comment for TODO kfp pipeline delete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2340)
=> SDK/CLI: Implement kfp pipeline group

test/sample-test/sample_test_launcher.py
Current post-submit tests are failing due to wrong arg name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2439)
=> [Test] Fix post-submit test

backend/src/crd/controller/viewer/reconciler/reconciler.go, backend/src/crd/controller/viewer/reconciler/reconciler_test.go
This PR fixes https://github.com/kubeflow/pipelines/issues/2440. Adding `--bind_all` option allows  tensorboard to serve on all public interfaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2441)
=> Add --bind_all option for tensorboard

.pylintrc, .style.yapf, CONTRIBUTING.md
This is part of the efforts stated in #2442 
The plan is as follows:
1. Make it clear in [contributing guidance](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md) that we chose google python style and help contributors correctly configure their IDE to adopt it smoothly. @Bobgy can you help update the frontend part?
2. Make sure the configuration is acceptable to everyone.
3. Sent out linting PRs to fix current formatting issues.
4. Add pylint check to Travis CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2446)
=> [Request for comments] Add config for yapf and pylintrc

sdk/python/kfp/_client.py, sdk/python/kfp/compiler/_k8s_helper.py, sdk/python/kfp/compiler/_op_to_template.py, sdk/python/kfp/compiler/compiler.py, sdk/python/kfp/containers/_container_builder.py, sdk/python/kfp/containers/_k8s_job_helper.py, sdk/python/tests/compiler/k8s_helper_tests.py, sdk/python/tests/dsl/artifact_location_tests.py
One part was only used by container builder and provided higher-level API over K8s Client.
Another was used by the compiler and did not use the kubernetes library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2333)
=> SDK - Refactoring - Split the K8sHelper class

sdk/python/requirements.txt, sdk/python/setup.py
Cloudpickle is used by the `func_to_container_op(..., use_code_pickling=True)` and `create_component_from_airflow_operator`.
`setup.py` installs it, but requirements.txt did not have it.
Long-term fix: We need to make `setup.py` use `requirements.txt`. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2437)
=> SDK - Setup - Added cloudpickle to requirements

frontend/src/components/CustomTable.tsx, frontend/src/components/CustomTableRow.tsx, frontend/src/components/__snapshots__/CustomTable.test.tsx.snap, frontend/src/pages/PipelineList.tsx, frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Fixes https://github.com/kubeflow/pipelines/issues/2443
/kind bug
/priority p0
Recommends reviewer ignore the first reformat commit:
https://github.com/kubeflow/pipelines/pull/2444/files/ce24d442de1542866915ada42108dfb3fe092e46..f73cd2d26743f793d4917b13ac3eb2787b84e25a
**Verification:**
The following are all possible combinations of props that affect custom table layout. I've verified all columns align correctly and expand button shows correctly.
UPDATE: after the screenshots, I also fixed wrong inactive color in headers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2444)
=> Fix CustomTable.tsx layout problems

frontend/src/lib/StaticGraphParser.test.ts, frontend/src/lib/StaticGraphParser.ts, frontend/src/lib/WorkflowParser.ts
The display name shall be retrievable from metadata.annotations.pipelines.kubeflow.org/task_display_name from each components in workflow yaml spec.
For review, use [this link](https://github.com/kubeflow/pipelines/pull/2459/commits/4a69583bd3ca1fa770de1ad802d4bf6700ad200a) to avoid seeing unrelated format changes.
**Before the fix:**
**After the fix:**
/kind feature
/cc @numerology
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2459)
=> [Frontend] UI shows specified task display name in PipelineDetail page

components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_common_ops.py, components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_wait_job.py
For CMLE steps associated with a gcs folder, only train step shall show Tensorboard. Thus add option to avoid outputting a Tensorboard artifact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2466)
=> Add option to hide tensorboard artifact

sdk/python/kfp/cli/diagnose_me/__init__.py, sdk/python/kfp/cli/diagnose_me/gcp.py, sdk/python/kfp/cli/diagnose_me/gcp_test.py, sdk/python/kfp/cli/diagnose_me/kubernetes_cluster.py, sdk/python/kfp/cli/diagnose_me/kubernetes_cluster_test.py, sdk/python/kfp/cli/diagnose_me/utility.py, sdk/python/kfp/cli/diagnose_me/utility_test.py
RFC - specially let me know if this seems like a good location. This PR only contains the core libraries will follow up with the cli runner and additional libraries in a separate PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2417)
=> Adding the core libraries for diagnose_me tool.

sdk/python/kfp/components/_python_op.py, sdk/python/tests/components/test_python_op.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2473)
=> SDK - Python components - Fixed bug when mixing file outputs with return value outputs

frontend/src/components/LogViewer.tsx, frontend/src/pages/RunDetails.tsx, frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Bug double scrollbar:
Bug cannot scroll horizontally (introduced by me in an earlier PR), notice in the screenshot, log lines are long, but there is no horizontal scrollbar:
Bug "not scrolling to bottom", when user goes to log viewer tab, it should go to the bottom line of logs. However, it goes to a few pixels above that.
This fixes three of them.
Demo: https://drive.google.com/file/d/1xpZYI5QYlbzBquGxxKGfF4ukL91WA1MM/view
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2480)
=> [Frontend] Fix log viewer double scrollbar bug + not scrolling to bottom bug

sdk/python/kfp/_client.py
The new format is now 
36a59b5371d6ab2-dot-us-west1.notebooks.googleusercontent.com
Remove the part that break the SDL to use a more generic matching string 
/assign @numerology @hongye-sun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2486)
=> Fix inverse proxy matching regex

backend/src/apiserver/client_manager.go, backend/src/apiserver/model/pipeline.go
Fixes https://github.com/kubeflow/pipelines/issues/2485
Note: migration step learned from existing one: https://github.com/kubeflow/pipelines/blob/7aaecb150114d358c886ab85f01f327428b2a253/backend/src/apiserver/client_manager.go#L207
/cc @jingzhang36 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2492)
=> Fix pipeline description 255 characters length limit

manifests/kustomize/base/pipeline/pipeline-runner-role.yaml
Considering with the issue [2455](https://github.com/kubeflow/pipelines/issues/2455)
Since now Seldon is a default component in kubeflow toolkits, it would be nice if we add seldondeployment clusterrole for pipeline-runner when initializing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2458)
=> clusterrole for pipeline-runner with seldondeployments

manifests/gcp_marketplace/guide.md
update inverse proxy custom permission setting and role setting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2493)
=> update inverse proxy custom permission setting and role setting

frontend/mock-backend/mock-api-server.ts, frontend/src/lib/Apis.ts, frontend/src/pages/ArtifactList.tsx, frontend/src/pages/ExecutionList.tsx
Fixes https://github.com/kubeflow/pipelines/issues/2504
Change summary:
metadata UI didn't respect returning a promise when data is ready. I refactored it to use promise now. Therefore, now `CustomTable` can correctly know when loading finishes based on the promise.
Screencast: https://drive.google.com/file/d/1Bd4uqh_Da39mEGEvW_Z-gCgTEJqk9agA/view
/cc @numerology 
/kind bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/pipelines/2508)
=> [UI] Fix metadata tabs loading state
