sdk/python/kfp/v2/google/client/client.py
sdk/python/kfp/v2/google/client/schedule.py

Since the region of App Engine is fixed to a single region for a GCP project and unable to change the region, we want to make a vertex pipeline and cloud scheduler job in the difference regions, Taiwan and Tokyo.
App Engine Location: https://cloud.google.com/appengine/docs/locations
Now we can provide a region of pipeline to `AIPlatformClient.create_schedule_from_job_spec`, but it attempts to create scheduler job to the same region. So, it fails if app engine is located in the difference region of vertex AI pipeline.
In this pull request, we can provide `app_engine_region` parameter to the function that cloud scheduler job is created in. If it's not provided, the job is created in the same region of vertex pipeline. This change is compatible with current behavior and not breaking change. …

fix(sdk): google client, Enable to provide app engine region that scheduled job is created in

---

frontend/mock-backend/tsconfig.json
frontend/package-lock.json
frontend/package.json

Fix #6212
mock-backend build rule fails with error: internal link: http://gpaste/6208061350871040
Because of TypeStrong/ts-node#138, we cannot use absolute path import in src/ unless we use this library: https://www.npmjs.com/package/tsconfig-paths.
Another way is to change all imports to relative paths, but that is less optimal.
**Checklist:**

fix(frontend): mock-backend didn't understand absolute path import in frontend/src/. Fix #6212

---

api/v2alpha1/google/rpc/status.proto
api/v2alpha1/pipeline_spec.proto

`PipelineTaskFinalStatus` is the value format for `TaskFinalStatus`, which is used by Exit handler.
https://github.com/kubeflow/pipelines/blob/97b9bdb530adaf824ff9aee14ff1a8ac70eb063e/api/v2alpha1/pipeline_spec.proto#L260
**Checklist:**

feat(api): Add PipelineTaskFinalStatus to pipeline_spec.proto

---

test/tools/project-cleaner/project_cleaner.sh

Fixing failing issue of project_cleaner.
There is an API change by gcloud compute package when upgrading from 0.89.0->0.90.0.
Check this new change using golang image:
```
docker run -it  -v $(pwd):$(pwd) -w $(pwd) docker.io/library/golang:1.16.6-alpine /bin/sh
```
**Checklist:**

test: Remove upgrade command in project_cleaner

---

components/google-cloud/tests/aiplatform/test_componets_compile.py
components/google-cloud/tests/experimental/remote/gcp_launcher/test_custom_job_remote_runner.py
components/google-cloud/tests/presubmit.sh

Adding teardown / clean up step to a few unit tests that where leaving a residue after execution. 
Also changing the test install script to install `google-cloud-aiplatform` sdk from master instead of dev branch.

chore(components/google-cloud): Clean up unit tests

---

v2/test/sample_test.py

Fixes issues in https://github.com/kubeflow/pipelines/pull/6202#issuecomment-893858671

test: Remove old v2 launcher building steps.

---

components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/launcher.py
components/google-cloud/tests/experimental/custom_job/test_custom_job.py
components/google-cloud/tests/experimental/remote/gcp_launcher/test_launcher.py

This is to add a temporary fix ( until KFP v2.0) work around in custom job to avoid the error key not found when output is not part of the args.

fix(components/google-cloud): Add temporary work around for key not found during compile

---

components/PyTorch/pytorch-kfp-components/setup.py

Due to the dependency on pytorch job operator with PTL master, the pytorch-kfp-components pip package was referenced to the master branch of pytorch-lightning.
The changes are released as part of pytorch-lighthing 1.4.0 release. Updating the plugin with pytorch-lightning 1.4.0 and above as dependency.
**Checklist:**

chore(components/pytorch): Updating pytorch-kfp-component dependency list

---

.readthedocs.yml
components/google-cloud/RELEASE.md
components/google-cloud/google_cloud_pipeline_components/aiplatform/remote_runner.py
components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/Dockerfile
components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/cloudbuild.yaml
components/google-cloud/google_cloud_pipeline_components/remote/__init__.py
components/google-cloud/google_cloud_pipeline_components/remote/aiplatform/Dockerfile
components/google-cloud/google_cloud_pipeline_components/remote/aiplatform/__init__.py
components/google-cloud/google_cloud_pipeline_components/remote/aiplatform/cloudbuild.yaml
components/google-cloud/google_cloud_pipeline_components/version.py

Creating release branch for Google cloud pipeline components 0.1.4. This release  includes:
* Experimental component for tfp_anomaly_detection.
* Experimental module for Custom Job Wrapper.
* Fix to include YAML files in PyPI package.
* Restructure the google_cloud_pipeline_components.  
Note this release branch contains the following cherry picked change : 
Module `remote_runner.py` was added back to `google_cloud_pipline_components.aiplatform` to mitigate the hard coded path in pypi release package. An internal issue is tracking the update to eliminate needing this change in future releases.

chore(components/google-cloud): Create Release Branch for google-cloud-pipeline-components-0.1.4

---

v2/cmd/driver/main.go
v2/cmd/launcher-v2/main.go
v2/cmd/launcher/main.go
v2/compiler/argo_test.go
v2/compiler/container.go
v2/component/launcher.go
v2/component/launcher_v2.go
v2/config/env.go
v2/driver/driver.go
v2/metadata/client.go
v2/metadata/client_test.go

Part of #6152 
Reasoning: pipeline root should be read from config only once (config may be modified), and then preserved in pipeline run context. All the tasks in one pipeline should use the same pipeline root.
The refactoring also makes pipeline root easier to access, so that when building KFP v2, I can get pipeline root from both the driver and the launcher, because both places need it.
**Checklist:**

refactor(v2): save pipeline root to pipeline run context. Part of #6152

---

sdk/python/kfp/dsl/_container_op.py

Fixes the bug introduced by PR #6268 
Fixes #6311

fix(sdk): Fix compiler bug for legacy outputs mlpipeline-ui-metadata and mlpipeline-metrics. Fixes #6311 

---

frontend/src/components/tabs/MetricsTab.test.tsx
frontend/src/components/viewers/MetricsVisualizations.tsx

chore(frontend): Change from `name` to `display_name` for visualization. Fix #6346

---

sdk/python/kfp/components/_components.py
sdk/python/kfp/components_tests/test_components.py

Only yaml component may not have command, so warn during component loading.
Fixes #4800
**Checklist:**

chore(sdk): Warn on container component without command. Fixes #4800

---

components/PyTorch/pytorch-kfp-components/setup.py
components/PyTorch/pytorch-kfp-components/tox.ini
samples/contrib/pytorch-samples/Dockerfile
samples/contrib/pytorch-samples/requirements.txt

This PR contains the following build fixes
1. Removed unused packages from `pytorch-kfp-components` - `setup.py` file 
2. Removed PTL, torchmetric installation from `Dockerfile` to `requirements.txt`
3. Pinning `matplotlib` version to `3.4.2` temporarily, unitl the stable version
4. Pinning `pytorch-lightning` verison to `1.4.2` - to avoid code breakage due to frequent PTL release cycle.
Tested with test pip package - https://test.pypi.org/project/pytorch-kfp-components/4.3.12/
**Checklist:**

chore(components/pytorch): pytorch samples build fixes

---

sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/v2_compatible_compiler_test.py
sdk/python/tests/compiler/compiler_tests.py

Block using importer in KFP OSS since importer doesn't have a normal container implementation yet.
Fixes: https://github.com/kubeflow/pipelines/issues/6323
**Checklist:**

fix(sdk): block dsl.importer usage in KFP OSS. Fixes: #6323

---

components/aws/sagemaker/tests/integration_tests/Dockerfile

Integration Tests are currently failing with the following error - 
```
=> ERROR [ 2/12] RUN apt-get update && apt-get install -y --no-install-recommends     curl     wget     git     jq                                                                                                                                      2.6s
------
> [ 2/12] RUN apt-get update && apt-get install -y --no-install-recommends     curl     wget     git     jq:
#6 0.655 Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
#6 0.678 Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
#6 0.798 Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
#6 1.065 Reading package lists...
#6 1.752 E: Repository …
```

fix(Dockerfile): fixes the dockerfile by allowing `apt-get update` to ignore releaseinfo changes.

---

components/google-cloud/dependencies.py
components/google-cloud/docs/requirements.txt

Fix read the docs issue by explicitly adding `google-api-core<2dev,>=1.21.0`, as a requirement for `google-cloud-pipeline-components`.

fix(components/google-cloud): Google cloud pipeline components 0.1.4

---

components/PyTorch/pytorch-kfp-components/setup.py

Fixing pytorch-kfp-components - `setup.py` . Adding a missing comma in development classifier.
**Checklist:**

chore(components/pytorch): pytorch-kfp-components setup.py update

---

sdk/python/kfp/containers/_container_builder.py
sdk/python/kfp/containers/_k8s_job_helper.py

Python Kubernetes SDK doesn't handle well tokens that expire. [GCP default authentication](https://github.com/kubernetes-client/python-base/blob/b4d3aad42dc23e7a6c0e5c032691f8dc385a786c/config/kube_config.py#L577) has set its own custom refresh token, but for other kubernetes API authentication mechanisms it's not trivial to implement.
In order to customize authentication, users of the python sdk can customize the [client configuration object](https://github.com/kubernetes-client/python/blob/master/kubernetes/client/configuration.py) to set a custom `refresh_api_key_hook` and provide it to `load_kube_config`.
With this change, in ContainerBuilder, we can inject a custom client configuration that will be used by the client to check the kaniko execution.
I …

feat(sdk): Surface kubernetes configuration in container builder

---

samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb

{} Placeholder doesn't work well in component parameters and
it is better to have it as a runtime parameter for flexibility.
See also https://github.com/kubeflow/pipelines/issues/6311#issuecomment-900245391
**Checklist:**

chore: use a runtime parameter for pusher destination in the TFX example.

---

manifests/gcp_marketplace/schema.yaml

Part of #6294 
before the PR, it looked like the following on the UI, basically the format doesn't support markdown, so I have to reduce the number of links and what content to include here:
**Checklist:**

docs(gcp): ai platform pipelines use emissary tooltip update

---

sdk/python/kfp/v2/google/client/client.py
sdk/python/kfp/v2/google/client/schedule.py

When AI platform SDK creates a scheduled job, it makes a Cloud scheduler job and a cloud function to proxy from scheduler job to AI platform endpoint. Now the service account of the function is fixed to the service account of App Engine default. So the function fails to call AI platform endpoint when it does not have appropriate permission.
In this pull request, we'll be able to attach a  individual service account to the function that should have access to call the AI Platform endpoint. If the parameter is not specified, the SDK does not give the parameter to cloud functions API and the default service account will be used by default.
**Checklist:**

feat(google client): Enable to specify the service account to proxy function of scheduler in google client sdk

---

manifests/kustomize/third-party/argo/installs/cluster/kustomization.yaml
manifests/kustomize/third-party/argo/installs/cluster/workflow-controller-clusterrolebinding-patch.json

In default situation on deploying with kustomize, the ClusterRoleBinding of "service account" argo is bound to namespace `argo`, the workflow-controller can not access the configmap `workflow-controller-configmap` in namespace `kubeflow`, we should modify it to  namespace `kubeflow`.
The error log of workflow-controller
```
time="2021-08-17T08:54:24Z" level=info msg="index config" indexWorkflowSemaphoreKeys=true
time="2021-08-17T08:54:24Z" level=info msg="cron config" cronSyncPeriod=10s
time="2021-08-17T08:54:24.143Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-08-17T08:54:24.156Z" level=info msg="Get configmaps 403"
time="2021-08-17T08:54:24.156Z" level=fatal msg="Failed to register watch for controller config map: configmaps …
```

fix(manifests): replace argo ClusterRoleBinding namespace

---

components/google-cloud/google_cloud_pipeline_components/experimental/__init__.py

**Add methods for creating forecasting preprocessing and validation components:**
- Add two methods to create components from yaml file.
- Add initial documentation for the components.

feat(components/google-cloud): Add methods for creating forecasting preprocessing and validation components

---

backend/api/experiment.proto
backend/api/job.proto
backend/api/pipeline.proto
backend/api/run.proto
backend/api/task.proto

Links that include a line break don't render correctly in generated docs. This patch removes line breaks to fix broken docs links.
Note: I haven't figured out how to regenerate all the docs and code yet. If this change makes sense, I could use some pointers on doing that, or maybe somebody else can regenerate the docs.
**Checklist:**

chore: fix broken links

---

backend/src/apiserver/resource/resource_manager.go
backend/src/common/util/workflow.go

Fixes #6067, #6200
Instead of always overwriting `"sidecar.istio.io/inject"` annotation in runtime, set the annotation if the key does not exist.
By this change, users can use Istio service mesh optionally to enable communication between pipelines and another micro services. Without this change, the communication can cause errors like `RBAC: access denied` even with appropriate routing.
In pipeline SDK, enabling Istio service mesh is as easy as
```python
@kfp.dsl.pipeline(name=PIPELINE_NAME)
def dpf_pipeline():
debug_task = debug_op()
debug_task.add_pod_annotation("sidecar.istio.io/inject", "true")
debug_task.add_pod_annotation("proxy.istio.io/config", '{ "holdApplicationUntilProxyStarts": true }')
```
As written in [doc on Argo …

fix(backend): recognize "sidecar.istio.io/inject" annotation to use Istio service mesh optionally. Fixes #6200

---

api/v2alpha1/pipeline_spec.proto

Updates the pipeline_spec.proto to use google.protobuf.Value instead of pipelines Value for parameter fields. Replaces PrimitiveTypeEnum with ParameterTypeEnum, to help clarify that parameters can contain more than primitive typed data.
**Checklist:**

feat(api): Updates pipeline_spec.proto to use google.protobuf.Value

---

sdk/python/kfp/cli/run.py

Fixes #6315
- to get more detailed information when using kfp run get CLI
**Checklist:**
**Screenshot**
- for example

feat(sdk): detail option to kfp run get. Fixes #6315

---

components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py

Add support for Proto Plus serialization / deserialization. This is specifically used in `ModelUploadOp` for model explainability parameters.

feat(components/google-cloud): Support Proto Plus serialization

---

components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/__init__.py

Update the default value of preprocessing_bigquery_dataset from None to empty string.
When the default value is set to None, the component compile function throws ValueError: No value provided for input preprocessing_bigquery_dataset

fix(components/google-cloud): Fix the default value of preprocessing_bigquery_dataset

---

sdk/python/kfp/components_tests/test_components.py
sdk/python/kfp/containers_tests/component_builder_test.py
sdk/python/kfp/containers_tests/test_build_image_api.py
sdk/python/kfp/v2/google/client/schedule_test.py
sdk/python/requirements-test.txt
sdk/python/setup.py
sdk/python/tests/compiler/compiler_tests.py
sdk/python/tests/compiler/component_builder_test.py
sdk/python/tests/compiler/container_builder_test.py

I noticed that we're installing `mock`, which is now available in the stdlib. This patch drops the `mock` dependency and imports it from `unittest`.
**Checklist:**

chore(sdk): Import mock from stdlib and drop dependency.

---

components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.forecasting.rst
components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.rst

This is to add the new experimental forecast feature to Sphinx API docs

chore(components/google-cloud): Add model forecast documentation to Sphinx docs

---

components/google-cloud/dependencies.py

Increasing the min version for google-cloud-aiplatform to 1.4.0

chore(components/google-cloud): Update google-cloud-aiplatform min version to 1.4.0

---

components/google-cloud/tox.ini

Removing rule to fix #6485 failing tests.

chore(components/google-cloud): Remove W504 from flake8 rules to match auto format

---

sdk/RELEASE.md
sdk/python/kfp/dsl/_component_bridge.py
sdk/python/kfp/dsl/_container_op.py
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_env.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_env.py
sdk/python/setup.py

In v1, the `add_env_variable()` method takes an input of type `kubernetes.client.models.V1EnvVar`, which does not fit for Vertex Pipelines. So we add a new method `set_env_variable()` for v2.
The new method accepts a pair of `name` and `value` from constant values, but not from `PipelineParam`. The same limitation also exists in v1 `add_env_variable()`.
**Checklist:**

feat(sdk.v2): Support container environment variable in v2.

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/v2_compatible_compiler_test.py
sdk/python/tests/compiler/compiler_tests.py

chore(sdk): remove dead code on importer check in v1.

---

backend/src/apiserver/client_manager.go
backend/src/apiserver/config/config.json
manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml

The apiserver config parser uses `viper.GetDuration` to parse the mysql
connection lifetime variable. The `viper.GetDuration` function uses
`cast.ToDuration`, which uses `cast.ToDurationE`, which assumes
durations to be in nanoseconds if they don't explictly include a unit.
Since the default lifetime in the kustomize manifest is `120`, we
expire connections after 120ns, which is probably unintended. To make
this more clear, this patch includes duration units in the default
values, and drops the `Secs` suffix from the configuration variables,
since the code doesn't assume that durations are in seconds.
See
https://github.com/spf13/cast/blob/22b2b540ce2e240dd3565d1238df82136be02051/caste.go#L68-L72.
Fixes #6492.
cc @Bobgy 
**Checklist:**

fix(backend): Fix connection lifetime default and variable names.

---

sdk/RELEASE.md
sdk/python/requirements.in
sdk/python/requirements.txt
sdk/python/setup.py

Attempt to align with `kfserving` and support versions of `kubernetes` Python SDK `> 13`, we're (Zillow that is) now running KFP on Kubernetes `v1.18` (likely soon `v1.19+` as EKS is deprecating things quickly!) so trying to upgrade the SDK client. Figured I'd also just update all the requirements pinned in the `requirements.txt`.
This would also align with the strategy from `kfserving`, see [here](https://github.com/kubeflow/kfserving/blob/master/python/kfserving/requirements.txt#L6). This also conforms to the policy that seems to have been set where an upper bound is desired, introduced in [this PR](https://github.com/kubeflow/pipelines/pull/5258/files). This should update the tests to cover the latest releases of the `kubernetes` package ([PyPI …

fix(sdk): Update upper bound on kubernetes constraint in Python SDK

---

sdk/RELEASE.md
sdk/python/kfp/components/_components.py
sdk/python/kfp/components/_data_passing.py
sdk/python/kfp/components/_python_op.py
sdk/python/kfp/v2/components/component_factory.py

The problem is that to turn an input value like `"[]"` into a `python` `List` type you need to use something like `json.loads`. To tell `argparse.ArgumentParser` to use `json.loads` `kfp` must be able to map the input type to this deserializer function, it does this in the `get_deserializer_code_for_type_struct` method (see code [here](https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/components/_data_passing.py#L149)). Unfortunately the `type_name_to_deserializer` cannot possibly contain all the `List[<type>]` combinations so if you have a type hint that uses `List[str]` instead of just `List` you need to run the `type_annotation_utils.get_short_type_name` to strip `List[<type>]` to just `List` so we can map to the appropriate serializer …

fix(sdk): Get short name of complex input/output types to ensure we can map to appropriate de|serializer

---

sdk/RELEASE.md
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/v2_component_with_optional_inputs.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/v2_component_with_optional_inputs.py
sdk/python/kfp/v2/components/executor.py
sdk/python/kfp/v2/components/executor_test.py
sdk/python/kfp/v2/components/types/type_annotations.py
sdk/python/kfp/v2/components/types/type_annotations_test.py

The issue is `_is_parameter` would return `False` on annotation `Optional[str]`:
https://github.com/kubeflow/pipelines/blob/a0b18eb9e8da25c7b81b0b75cf0f39297c809d20/sdk/python/kfp/v2/components/executor.py#L167-L173
As a result, we would not set the value in `func_kwargs`: 
https://github.com/kubeflow/pipelines/blob/a0b18eb9e8da25c7b81b0b75cf0f39297c809d20/sdk/python/kfp/v2/components/executor.py#L265-L266
The fix is to strip off `Optional[]` before passing the annotation to `_is_parameter` and `_get_input_parameter_value`.
**Checklist:**

fix(sdk.v2): fix `Optional` type hint causing executor to ignore user inputs for parameters.

---

components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
components/google-cloud/tests/experimental/custom_job/test_custom_job.py

This PR includes adding support for Service Account , Encryption key, and Network, Tensorboard, and Base Training Dir from Vertex AI Training API in `run_as_vertex_ai_custom_job()`.

feat(components/google-cloud): Expose all Custom Job parameters via Custom Job wrapper 

---

manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/composite-controller.yaml
manifests/kustomize/third-party/metacontroller/base/kustomization.yaml
manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml

@Bobgy @zijianjoy @orugantichetan
Fixes #5578
I
*  upgraded to 2.0.4
*  removed insane permissions (e.g. privileged root container)
*  removed insane cpu and memory ressources (4 cores 4 GB)
*  restricted the namespaces to kubeflow profile namespaces
*  Reduced to a sane amount of logging
*  Omitted networkattachmentdefinitions for rootless istio-cni on Openshift and i did not update the profile-controller accordingly. I can still add them if someone is interested. This would also add something to pipelines-profile-controller sync.py https://istio.io/latest/docs/setup/platform-setup/openshift/#additional-requirements-for-the-application-namespace. I can also create a second pull request for that. In the same pull request i could also add the poddefault for authentication with …

feat(deployment): update and secure metacontroller

---

sdk/RELEASE.md
sdk/python/kfp/v2/components/component_factory.py

* Add test for empty `packages_to_install_command`
* Don't return `pip install` with no packages
If an empty list is provided no command should be returned to avoid a
broken command eg. `pip install      `
**Checklist:**

fix(sdk.v2): Component is invalid if `packages_to_install` empty and `install_kfp_package=False`

---

sdk/RELEASE.md
sdk/python/kfp/v2/components/executor.py
sdk/python/kfp/v2/components/executor_test.py

This function would fail under two scenarios:
- typed `list` or `dict` output parameters (ie. `Dict[str, str]`) raised an incorrect `ValueError`
- using `list` or `dict` rather than `List` or `Dict` raised an incorrect `ValueError` ([PEP 585](https://www.python.org/dev/peps/pep-0585/#terminology))
**Checklist:**

fix(sdk.v2): fixes broken output parameter type checking in `_handle_single_return_value`

---

.readthedocs.yml
components/google-cloud/RELEASE.md
components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
components/google-cloud/google_cloud_pipeline_components/remote/aiplatform/Dockerfile
components/google-cloud/google_cloud_pipeline_components/remote/aiplatform/cloudbuild.yaml
components/google-cloud/google_cloud_pipeline_components/version.py

* Add support for labels in custom_job wrapper. 
* Add a component that connects the forecasting preprocessing and training components.
* Write GCP_RESOURCE proto for the custom_job output.
* Expose Custom Job parameters Service Account, Network and CMEK via Custom Job wrapper.
* Increase KFP min version dependency.
* AUpdate documentations for GCPC components.
* Update typing checks to include Python3.6 deprecated types.

chore(components/google-cloud): Create Release Branch for Google cloud pipeline components 0.1.7

---

sdk/RELEASE.md
sdk/python/kfp/_client.py

Removed duplicate fn as recommended by upstream issue [#6586](https://github.com/kubeflow/pipelines/issues/6586) 
**Checklist:**

fix(sdk): removed duplicate function. Fixes #6586

---

sdk/RELEASE.md
sdk/python/kfp/dsl/_volume_op.py

Ideally, `VolumeOp` should create a unique PVC for each run. But in the case where the same PVC has to be re-used for recurring runs `generate_name` argument can be set to `False`.
Fixes: https://github.com/kubeflow/pipelines/issues/6562
**Checklist:**

feat(sdk): Enable re-use of PVC with VolumeOp

---

sdk/RELEASE.md
sdk/python/kfp/_local_client.py
sdk/python/requirements.in
sdk/python/tests/local_runner_test.py

Fix #6598 
Pass additional docker options to local runner through ExecutionMode,  e.g.:
```
run_pipeline_func_locally(
_pipeline,
{},
execution_mode=LocalClient.ExecutionMode(mode="docker",
docker_options=["-e", "foo=bar"])
)
```
**Checklist:**

feat(sdk): Local runner supports additional docker options. Fixes #6598

---

components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/prepare_data_for_train/component.py
components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/prepare_data_for_train/component.yaml

This PR enables all types ( int, float, str, bool, dict, list ) to be accepted by ai platform components as pipeline parameter.

fix(components/google-cloud): Pipeline parameters with type Int cannot be passed to aiplatform components

---

backend/src/agent/persistence/client/pipeline_client.go

The following fields are unexported: 
```
basePath              string
mlPipelineServiceName string
mlPipelineServicePort string
```
but not set, https://github.com/kubeflow/pipelines/blob/ed3453f7940b7f95e6c0ef02f44626f8eb55cdbf/backend/src/agent/persistence/client/pipeline_client.go#L70-L75
**Checklist:**

chore: remove unused fields in the persistence client

---

test/component_test.yaml
test/e2e_test_gke_v2.yaml
test/sample_test.yaml

Reverts kubeflow/pipelines#6618
The networking of Test infra should get fixed. We don't need this workaround anymore.

test: Revert "fix: Add workaround init container to fix test infra"

---

components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py

This is to address the issue when component has not input the custom job errors out with 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-daac6e47c769> in <module>
----> 1 custom_job_distributed_training_op= gcpc.experimental.custom_job.custom_training_job_op(distributed_train_mnist)
/opt/conda/lib/python3.7/site-packages/google_cloud_pipeline_components/experimental/custom_job/custom_job.py in custom_training_job_op(component_spec, display_name, replica_count, machine_type, accelerator_type, accelerator_count, boot_disk_type, boot_disk_size_gb, timeout, restart_job_on_worker_restart, service_account, network, worker_pool_specs, encryption_spec_key_name, …
```

fix(components/google-cloud): Fix custom job wrapper error on empty input spec.

---

components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/README.md
components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/prepare_data_for_train/component.yaml

The python-based component has docstring in the original python method. But when converted to yaml by create_component_from_func method, the docstring didn't show up in the description field. This pr manually copies the docstring to the description field.

feat(components/google-cloud): Add description for prep data for train component.

---

manifests/kustomize/base/installs/multi-user/view-edit-cluster-roles.yaml

@elikatsis  @zijianjoy 
This also fixes  bug https://github.com/kubeflow/pipelines/issues/6649
@Bobgy Currently the jupyterlab user has no way to cleanup his workspace
With this change e.g. 
```
kubectl -n $NAMESPACE delete workflows -l 'workflows.argoproj.io/completed=true' # for argo
```
works
**Checklist:**

feat: allow the default-editor to edit argo workflows and fix bug #6649

---

sdk/python/kfp/v2/google/client/schedule.py

When scheduling a job with vertex pipelines, the name of the job is not reflected in the pipeline name.
e.g. `pipeline_pipeline_51f3dbec_-0-1-a-a-a` (I defined pipeline name as `test`)
This is because try to read a non-existent attribute from the compiled json.
https://github.com/kubeflow/pipelines/blob/ed2ba1a6b3efb9aa2623ce211e87982fa7b8be1c/sdk/python/kfp/v2/google/client/schedule.py#L123
The correct attribute path is `pipelineSpec/pipelineInfo/name` .
I think we should add the name or displayName attribute to compiled json at compile time, or add these attribute with schedule.py.
**Checklist:**

fix(sdk): fix cloud scheduler's job name

---

sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/google/client/client.py
sdk/python/kfp/v2/google/experimental/custom_job.py

Warning for upcoming changes in 2.0.0. 
1. v2 compiler: APIs imported from the v1 namespace (e.g. `kfp.dsl`, `kfp.components`, etc) will not be supported by the v2 compiler since v2.0.0. Please consider switching to v1 namespace with v1 compiler, or switching to v2 completely. 
2. Custom job from experimental folder will be removed. Please consider using [Vertex AI SDK](https://github.com/googleapis/python-aiplatform) for custom jobs and other functionalities. 
3. AIPlatformClient will be deprecated in 2.0.0. Please consider using [PipelineJob in Vertex AI SDK](https://github.com/googleapis/python-aiplatform#pipelines) for submitting pipelines.

chore(sdk): add deprecation warnings for v2

---

backend/src/crd/controller/viewer/main.go

maxNumViewers is per namespace not entire cluster.
[This PR](https://github.com/kubeflow/pipelines/pull/1623/files#diff-36da225a16f9c6742cee006c2554b6ef6836c9ab2b509a5169b5d3a4acc36977)
changed the scope from cluster to namespace.

docs(backend): fix incorrect maxNumViewers help text

---

manifests/kustomize/base/installs/multi-user/viewer-controller/cluster-role.yaml

Because of 
https://github.com/kubeflow/pipelines/blob/b7fd47f70bb842def10f8f1f1f36728b9928ce0b/backend/src/crd/controller/viewer/reconciler/reconciler.go#L114 the controller must be able to set finalizers on viewers.
otherwise you will get errors similar to
```
I1110 15:54:53.322352       1 reconciler.go:75] Reconcile request: dev-1/viewer-f517727e9516176c0e181234afcf45c8cfdf1735
I1110 15:54:53.327982       1 reconciler.go:87] Got instance: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:viewer-f517727e9516176c0e181234afcf45c8cfdf1735 GenerateName: Namespace:dev-1 SelfLink:/apis/kubeflow.org/v1beta1/namespaces/dev-1/viewers/viewer-f517727e9516176c0e181234afcf45c8cfdf1735 UID:1b80573e-7b0b-4a22-84d0-d9f8e48daf96 ResourceVersion:206118893 Generation:1 …
```

fix(deployment): the viewer controller does not work because of missing permissions

---

sdk/RELEASE.md
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/v2_component_with_optional_inputs.json
sdk/python/kfp/v2/components/base_component.py
sdk/python/kfp/v2/components/base_component_test.py
sdk/python/kfp/v2/components/component_factory.py
sdk/python/kfp/v2/components/structures.py
sdk/python/kfp/v2/components/structures_test.py

fix(sdk.v2): Fix regression on optional inputs

---

sdk/python/kfp/compiler/_data_passing_using_volume.py
sdk/python/tests/compiler/testdata/artifact_passing_using_volume.py
sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml

I made changes such that mlpipeline-ui-metadata and mlpipeline-metrics are always kept as artifacts, such that the webinterface can access and display them even if we use a kubernetes volume as data passing method.
@Bobgy  we could also extend this to allow the user to specify additional outputs that should also be kept as artifacts.
```
....
pipeline_configuration = kfp.dsl.PipelineConf()
from kubernetes.client.models import V1Volume, V1PersistentVolumeClaimVolumeSource
from kfp.dsl import data_passing_methods
pipeline_configuration.data_passing_method = data_passing_methods.KubernetesVolume(
volume=V1Volume(
name='artefacts',
persistent_volume_claim=V1PersistentVolumeClaimVolumeSource("{{workflow.name}}-%s" % 'artefacts'),
),
path_prefix='artefacts/'
) …
```

fix(sdk): visualizations and metrics do not work with data_passing_methods

---

v2/Makefile
v2/cmd/compiler/main.go
v2/compiler/argo.go
v2/component/launcher_v2.go

Changes
* v2 backend compiler now accepts PipelineSpec with the `--spec` flag. This makes it easier to run compiled specs. When submitting a PipelineJob, use the `--job` flag instead.
Future Plan (outside of this PR):
* Other tests are pending migration in https://github.com/kubeflow/pipelines/issues/6928
**Checklist:**

chore(v2): support pipeline parameter defaults + running specs directly

---

sdk/python/kfp/components/_python_op.py
sdk/python/kfp/v2/components/__init__.py

This PR fixes the problem that importing `kfp.v2.components.create_component_from_func` fails although `kfp.components.create_component_from_func_v2()` shows a warning saying "Please use `kfp.v2.components.create_component_from_func()` instead.".
https://github.com/kubeflow/pipelines/blob/1.7.1/sdk/python/kfp/components/_python_op.py#L875-L880
**Checklist:**

chore(sdk): Fix a warning message

---

sdk/RELEASE.md
sdk/python/requirements.in
sdk/python/setup.py

google-auth recently published a 2.0.0 release which removed support for Python 2.7. google-auth now requires Python >=3.6. No other breaking changes were made. You can see the full list of changes [here](https://github.com/googleapis/google-auth-library-python/commit/560cf1e).
I'm opening this as @kweinmeister mentioned the `google-auth<2` pin is making it difficult to resolve dependencies with some Google AI libraries.
**Motivation:**
google-auth is a dependency of many different libraries that interact with Google APIs. Increasing the time and number of packages with compatible pins on google-auth lowers the chance end developers who use multiple libraries will see dependency conflicts. 
If possible, please also retain compatibility with 1.x.x versions …

chore(sdk): allow google-auth < 3

---

samples/test/lightweight_python_functions_v2_with_outputs_test.py
sdk/RELEASE.md
sdk/python/kfp/v2/components/structures.py

Too much hassle to use Union types in pydantic. Likely not worth using it to specify parameter types for input default.
pydantic will attempt to 'match' any of the types defined under Union and will use the first one that matches.
https://pydantic-docs.helpmanual.io/usage/types/#unions
**Checklist:**

fix(sdk.v2): Avoid pydantic union bug

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler.py
sdk/python/tests/compiler/compiler_tests.py

Part of https://github.com/kubeflow/pipelines/issues/6829
**Checklist:**

feat(sdk)!: Deprecate V2 compatible mode in v1 compiler

---

frontend/src/pages/PipelineDetails.test.tsx
frontend/src/pages/PipelineDetails.tsx

Partial https://github.com/kubeflow/pipelines/issues/6779
Currently KFP Pipeline Detail page has a Delete button which is always enabled. But actually if you don't select a pipeline version, the button does nothing and redirect you to the Pipeline List page. So we should disable the Delete button if this button does nothing.
**Checklist:**

feat(frontend): Disable delete button if no pipeline version is not selected

---

sdk/RELEASE.md
sdk/python/kfp/_client.py
sdk/python/kfp/cli/cli.py
sdk/python/kfp/cli/diagnose_me_cli.py
sdk/python/kfp/cli/experiment.py
sdk/python/kfp/cli/pipeline.py
sdk/python/kfp/cli/recurring_run.py
sdk/python/kfp/cli/run.py

At Zillow we use the `kfp` CLI to manage pipeline compilation, upload, submission and creating recurring runs. This change open sources what we've been using internally for the last year or so to round out that interface some more 😄 
This also contributes some improvements to the type hinting within the `kfp.Client` object too so hopefully this will make it into the API docs to improve folks understanding of the types those methods return!
FYI we're back on `kfp == v1.5.1` so I've done my best to rebase this atop `master`.

feat(sdk): Improve CLI experience for archiving experiments, managing recurring runs and listing resources

---

README.md

Minor change. It's better to refer to the Argo Workflows subproject of Argo.

docs: Argo -> Argo Workflows

---

samples/test/util.py
v2/cmd/driver/main.go
v2/compiler/argo.go
v2/compiler/argo_test.go
v2/compiler/container.go
v2/compiler/dag.go
v2/driver/driver.go
v2/metadata/client.go
v2/metadata/client_test.go
v2/test/README.md
v2/test/components/run_sample.yaml

Previously, each KFP DAG execution had a corresponding context to group child tasks.
This PR changes it to:
Each child task has a custom property "parent_dag_id" with the parent DAG execution ID as value.
We no longer need the context, because MLMD has supported flexible filter queries on custom properties. We can get all child tasks of a DAG using custom_property.parent_dag_id = xxx filter.
Right now, MLMD does not have index on custom properties, so we also add a filter to run context for perf optimization.
TODO: We also need to update frontend to use the new format.
**Checklist:**

refactor(v2): executions use parent_dag_id custom property for DAG - task relationship

---

frontend/src/components/CustomTable.tsx
frontend/src/mlmd/Api.ts
frontend/src/mlmd/MlmdUtils.ts
frontend/src/pages/ArtifactList.tsx
frontend/src/pages/ExecutionList.tsx

Partial https://github.com/kubeflow/pipelines/issues/6901
- Fix artifact name not showing up, and execution state not showing up issues.
- Put `[unknown]` text if workspace/name is empty.
- We should probably remove the grouping of Workspace in order to enable pagination for MLMD executions and artifacts list. Plus that KFPv2 doesn't have workspace name to allow a valid grouping. cc @Bobgy to provide guidance on this. Reference: https://github.com/kubeflow/pipelines/issues/6901
**Checklist:**

fix(frontend): Fulfill name/state/workspace for MLMD Executions and Artifacts list.

---

samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb

With KFP 1.8 release, we are upgrading MLMD to 1.4.0, which enforced a TFX upgrade. And it broke the post-submit of parameterized_tfx_oss pipeline, which is using the old version of TFX. This PR move away from hardcoded version to dynamic value which relies on tfx library version.
cc @jiyongjung0 
**Checklist:**

fix(samples): Use TFX library version for parameterized_tfx_oss. Fix #6974

---

backend/src/apiserver/template/template.go
backend/src/apiserver/template/template_test.go
backend/src/apiserver/template/v2_template.go
v2/compiler/argo.go
v2/compiler/argo_test.go
v2/compiler/testdata/hello_world.json

Fix #6972
In KFPv2, the pipeline template name is in format of `namespace/<namespace>/pipeline/<pipelinename>` or `pipeline/<pipelinename>`. The `/` symbol is disallowed by Argo. Therefore we will remove those prefix when writing `generateName` in Argo workflow. We also check whether the <pipelinename> is valid before creating pipeline object.
**Checklist:**

chore(backend.v2): Honor Argoworkflow generateName format, only use pipeline template name. Fix #6972

---

samples/core/loop_output/loop_output_test.py
samples/core/loop_output/loop_output_v2.py
samples/core/loop_static/loop_static_v2.py
samples/test/lightweight_python_functions_v2_pipeline_test.py
samples/test/metrics_visualization_v2_test.py
samples/test/two_step_with_uri_placeholder_test.py
samples/test/util.py
v2/Makefile
v2/cmd/driver/main.go
v2/compiler/argo.go
v2/compiler/argo_test.go
v2/compiler/container.go
v2/compiler/dag.go
v2/compiler/testdata/hello_world.yaml
v2/compiler/testdata/importer.yaml
v2/driver/driver.go
v2/metadata/client.go

Part of https://github.com/kubeflow/pipelines/issues/6160
This adds basic sub-DAG and iterator support.
The following advanced features will be supported separately:
* DAG publisher (set DAG final status as succeed or failure)
* artifact iterator
* parameter/artifact aggregation
**Checklist:**

feat(v2): iterator and sub-DAG basic support

---

manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-role.yaml

As a follow up of https://github.com/kubeflow/pipelines/pull/6892 this must also be changed in the namespace level role for standalone pipelines.

 fix(deployment): the viewer controller does not work because of missing permissions

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml

We should use Secret to store minio access token, instead of clear text in resource yaml.
**Checklist:**

chore(manifests): Use Secret for GCP marketplace minio manifests

---

samples/core/XGBoost/xgboost_sample.py
v2/cmd/driver/main.go
v2/compiler/argo.go
v2/compiler/common.go
v2/compiler/container.go
v2/compiler/dag.go
v2/compiler/executor.go
v2/compiler/importer.go
v2/compiler/proto.go
v2/compiler/testdata/hello_world.yaml
v2/compiler/testdata/importer.yaml
v2/component/constants.go
v2/component/importer_launcher.go
v2/driver/driver.go

Part of #6159 
This refactoring makes the implementation adhere to [bit.ly/kfp-v2](bit.ly/kfp-v2), because some fields of pod spec should come from driver dynamically.
Change: previously, we generate container executor templates directly in the workflow, now the container driver has an output of podSpecPatch that decides the pod spec. So the logic to determine pod spec has been moved to container driver.
Benefits:
* save generated workflow template size, because container executor template can now be generic, since podspecpatch can determine everything dynamically.
* using the generic container executor template also simplifies compiler implementation to prepare for #6159 
* in the future, this opens up the possibility to implement #7046 
**Checklist:**

refactor(v2): driver decides container spec via pod spec patch

---

manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
test/sample-test/check_notebook_results.py

Address comment in https://github.com/kubeflow/pipelines/pull/5864
cc @jacobmalmberg
**Checklist:**

fix(manifests): Remove redundant secret value in profile controller

---

samples/core/multiple_outputs/multiple_outputs.ipynb
samples/core/multiple_outputs/multiple_outputs_test.py
samples/test/config.yaml
samples/test/utils/kfp/samples/test/utils.py
samples/test/utils/setup.py
sdk/python/kfp/compiler/main.py
sdk/python/kfp/v2/compiler/main.py

Part of #6377 
This also helps writing documentation as notebooks, because now we can easily test these notebooks.
* This PR implements notebook support for v2 sample test.
* samples/core/multiple_outputs/multiple_outputs.ipynb is added to v2 sample test as the first example.
We can add a sample test using a notebook with a pipeline defined (similar to importing a pipeline func from a python pipeline file). The notebook is not expected to have any side effect operations.
An additional feature is added that, notebook cells with a tag named "skip-in-test" will be skipped when running in the test, so that the notebook can be fully self-contained without affecting testability.
we use nbconvert to convert the notebook to python file and then compile the …

test(v2): v2 sample test supports notebooks

---

components/kserve/Dockerfile
components/kserve/OWNERS
components/kserve/README.md
components/kserve/component.yaml
components/kserve/requirements.txt
components/kserve/src/kservedeployer.py

I have added a KServe component for KServe 0.7.0
I have added it in a separate directory so the existing KFServing component can be accessed easily still because it is still used in the current Kubeflow releases.
Two questions:
- This component was made by  copying the KFServing component and updating it for KServe. I didn't copy the `OWNERS` file because I don't know what the etiquette is here. Should I just keep the same `OWNERS` file?
- Currently the `component.yaml` still points to the old image `quay.io/aipipeline/kfserving-component:v0.5.1`. This should be updated somehow but this should be done by a Kubeflow member with access to the right docker repo right?
**Checklist:**

feat(components): Add a KServe component

---

samples/core/dataflow/dataflow_test.py
samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
v2/test/integration-test.sh
v2/test/sample-test.sh

Part of https://github.com/kubeflow/pipelines/issues/6377
Changes to resolve permission issues:
* Sent https://github.com/kubeflow/testing/commit/1d0d06f1deddfbe33721355682126eebdf8b1d35 to add dataflow permission to the test cluster service account.
* Sent kubeflow/testing@de705d1 to add serviceAccount.actAs permission of compute default SA to vm SA.
**Checklist:**

test: fix integration-v2 test

---

sdk/RELEASE.md
sdk/python/setup.py

Updates the maximum absl version to 1.x for more compatibility. There is no breaking change in absl between 0.12 and 1.0 [CHANGELOG](https://github.com/abseil/abseil-py/blob/main/CHANGELOG.md).
Please see #7171 for the related issue.
**Checklist:**

fix(sdk): bumps up absl version to 1.x for compatibility with TF 2.8+. Fixes #7171

---

manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/test_sync.py

It's not a good idea to print the logs with indent, we should remove the indent.
It's better to keep the msg as single line.
```
Received request:
{
"apiVersion": "v1",
"kind": "Namespace",
"metadata": {
"annotations": {
"owner": "mask@example.com"
},
...
```
1. When we debug with `kubectl logs`, this is not developer friendly
2. This is not friendly for log tools also.
**Checklist:**

fix(Profile Controller): Disable indent when json dumps

---

api/Makefile
api/v2alpha1/python/generate_proto.py
api/v2alpha1/python/setup.py

These changes add the ability to publish a source tarball in addition to the wheel file when creating a release for the `kfp-pipeline-spec` python package. These changes were necessary in order to publish the package in conda-forge. 
See related issue here : https://github.com/conda-forge/staged-recipes/pull/16307
**Checklist:**

chore(build): Add source dist to kfp-pipeline-spec python package

---

backend/README.md

The latest release from Bobgy was build with local dependencies and doesn't work for others.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xb88438]
goroutine 1 [running]:
github.com/google/go-licenses/v2/licenses.Libraries.func1(0xc00ad1ac80, 0xc00abe1500)
/home/gongyuan_kubeflow_org/github/google/go-licenses/v2/licenses/library.go:101 +0xf8
golang.org/x/tools/go/packages.Visit.func1(0xc00ad1ac80)
/home/gongyuan_kubeflow_org/go/pkg/mod/golang.org/x/tools@v0.1.5/go/packages/visit.go:26 +0x396
golang.org/x/tools/go/packages.Visit.func1(0xc00c57b400)
/home/gongyuan_kubeflow_org/go/pkg/mod/golang.org/x/tools@v0.1.5/go/packages/visit.go:33 +0x332 …
```

chore: update go-licenses installation path in backend/README.md

---

sdk/RELEASE.md
sdk/python/kfp/_client.py

Currently when using `kfp pipeline list-versions --filter "..." $pipeline_id` it breaks with:
```
list_pipeline_versions() got an unexpected keyword argument 'filter'
```
Looks like adding the `filter` was just missed when it was added into the SDK :)

fix(sdk): Add in filter to list_pipeline_versions SDK method

---

frontend/src/pages/GettingStarted.tsx
frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap

Cloud AI Platform Notebook was migrated to Vertex AI workbench and the URL has changed.
**Checklist:**

fix(frontend): fixes link to Vertex AI workbench in GettingStarted page.

---

manifests/kustomize/env/gcp/cloudsql-proxy/cloudsql-proxy-deployment.yaml

When deploying on GKE 1.20, I see this error:
```
The Deployment "cloudsqlproxy" is invalid: spec.template.spec.containers[0].livenessProbe.httpGet.port: Invalid value: "8090": must contain at least one letter or number (a-z, 0-9)
```
I need to remove the double quote in order to make deployment successful.
I am expecting to include this for 1.8.0 release.
**Checklist:**

fix(manifests): Use number for cloudsql liveness port

---

components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests

Description of your changes:
Kubernetes version 1.18 will be deprecated by EKS, bumping up verison to v1.19

chore: update eks version to 1.19 for aws sagemaker integration tests

---

backend/src/cache/deployer/webhook-create-signed-cert.sh

Fixed https://github.com/kubeflow/pipelines/issues/7093
`signerName: kubernetes.io/kube-apiserver-client` only can create client certificates. However, we need to create certificates for server auth, so we need to change the singer name to `signerName: kubernetes.io/kubelet-serving`
From: https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers
Section 3:
> kubernetes.io/kubelet-serving: signs serving certificates that are honored as a valid kubelet serving certificate by the API server, but has no other guarantees. Never auto-approved by [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/).
Also, with the new CertificateSigningRequest V1 API, …

fix(backend): make cache-deployer generate CSR using kubelet-serving signerName

---

.cloudbuild.yaml
.release.cloudbuild.yaml

KFP SDK is currently released via a separate process, there's no need to build it during the backend release build.
**Checklist:**

chore: skip building KFP sdk and python components in cloudbuild

---

backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/common/util/error.go

Adds validation so that the user cannot activate a Run that belongs to Archived Experiment.
Fixes: https://github.com/kubeflow/pipelines/issues/7014
Signed-off-by: Diana Atanasova <dianaa@vmware.com>
**Checklist:**

feat(backend): Forbid unarchive runs that belog to archived experiment

---

manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml

For newer kubernetes versions you also need to specify scheduledworkflows/finalizers or you will get the following error:
```
workflows.argoproj.io \"sum-recurringk9twk-1-273993078\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>	
```
**Checklist:**
@bobgy @zijianjoy this is the same as in https://github.com/kubeflow/pipelines/pull/7031

fix(backend): missing permissions for scheduled workflows

---

RELEASE.md
sdk/RELEASE.md
sdk/python/requirements.in
sdk/python/setup.py

Tests removed at: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1470
Fixes https://github.com/kubeflow/pipelines/issues/6687

feat(sdk)!: drop support for python 3.6

---

sdk/python/kfp/__init__.py
sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py

Not intended for an actual release. But in case someone install the SDK from GitHub master HEAD, they'd better get a version different from a stable release version. This helps remove potential confusion in debugging, telemetry, etc.
**Caveat:**
After this change. For users install SDK from GitHub master HEAD and use v2 Python lightweight component.
The code 
```python
@component
def my_component(...):
...
```
needs to be updated to 
```python
@component(
kfp_package_path='git+https://github.com/kubeflow/pipelines.git@master#subdirectory=sdk/python',
)
def my_component(...):
...
```
Otherwise, pipeline will fail at runtime, as it will try to `pip install kfp==2.0.0-alpha.0`, which does not exist on PyPi.
**Checklist:**

chore(sdk): bump version to 2.0.0-alpha.0

---

backend/metadata_writer/requirements.in
backend/metadata_writer/requirements.txt
backend/metadata_writer/src/metadata_writer.py

In #4347 it was mentioned that there is a memory leak in `metadata-writer`, we are certainly seeing similar behavior given the cache variables (code [here](https://github.com/kubeflow/pipelines/blob/master/backend/metadata_writer/src/metadata_writer.py#L136)) are not bounded by an upper limit and the same with the "debug" files dumped to `/tmp` this causes `memory.working_set` to slowly rise and `memory.cache` to do so also. 
This change introduces a bounded size via an LRU cache (limited to 5k items for each, open to discussion on implementation of this), so that we can avoid any OOM issues entirely! Looking at the discussion on #4347 the current resolution is simply to let it OOM and the `ReplicaSet` to restart it, this works great but we have alerting …

fix(backend): AIP-5634: Add in LRU cache and temp file rotation for metadata-writer. Relates to #4347

---

backend/src/apiserver/common/config.go
backend/src/apiserver/config/config.json
backend/src/apiserver/server/run_server_test.go
backend/src/apiserver/template/template.go

Fix #7336
Due to the change in https://github.com/kubeflow/pipelines/pull/6689/files#diff-2bc2047e64f4bb524fb40748997d97f0c96c1c8884a87c81ffa3a7177f8cf0f1R195-R206, we cannot use the env var `DefaultPipelineRunnerServiceAccount` to set service account in multi-user mode. It is because the previous change will try to read a env var flag `pipeline-runner` instead of `DefaultPipelineRunnerServiceAccount` as this is deleted: https://github.com/kubeflow/pipelines/pull/6689/files#diff-47d6ab6bca869e0559465170316707ceda42f65103bd0d4e93519294305e62d1. But we should keep the flag.
**Checklist:**

fix(backend): Read env var for default service account in multi-user mode. Fix #7336

---

samples/core/tfx-oss/TFX Example.ipynb

**Problem:**
In this commit https://github.com/tensorflow/tfx/commit/cd029714cb3a9818273c6b2c67a1d3f271f1584f, TFX removed a kubeflow gcp example for Chicago taxi data. However, it is still referenced in this "TFX on KubeFlow Pipelines Example", e.g. https://raw.githubusercontent.com/tensorflow/tfx/master/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_kubeflow_gcp.py (broken link).
**Solution:**
Replace references to taxi tfx kubeflow example with penguin tfx kubeflow example.
**Checklist:**

fix(samples): Replace deprecated tfx kubeflow example

---

sdk/RELEASE.md
sdk/python/requirements.in
sdk/python/requirements.txt
sdk/python/setup.py

Require google-api-core>=1.31.5, >=2.3.2, to avoid the bug exists before these versions. See the python-api-core release notes for details.
- https://github.com/googleapis/python-api-core/releases/tag/v1.31.5
- https://github.com/googleapis/python-api-core/releases/tag/v2.3.2
KFP SDK does not have a direct dependency on `google-api-core`, but gets it via `google-cloud-storage`, which got the same fix (https://github.com/googleapis/python-storage/commit/e9aab389f868799d4425133954bad4f1cbb85786) but not released yet. Until we can depend on a newer version of `google-cloud-storage`, we need to temporarily pin `google-api-core` versions from our end.
**Checklist:**

fix(sdk): require google-api-core>=1.31.5, >=2.3.2

---

sdk/RELEASE.md
sdk/python/kfp/components/component_decorator.py

feat(sdk)!: throw error for output_component_file

---

sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/main.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/pipeline_spec_builder_test.py
sdk/python/kfp/components/for_loop.py
sdk/python/kfp/components/pipeline_channel.py
sdk/python/kfp/components/pipeline_task_test.py

Removes unused imports and unused variables from v2.
This is mostly done via [autoflake](https://github.com/PyCQA/autoflake) (with some additional modifications):
```sh
autoflake --in-place --remove-all-unused-imports --remove-unused-variables -v --exclude=__init__.py sdk/python/kfp/compiler/*.py sdk/python/kfp/compiler_cli_tests/*.py sdk/python/kfp/components/*.py sdk/python/kfp/dsl/*.py sdk/python/kfp/v2/*.py
```
_Note_: The variable `output` in [this codeblock](https://github.com/kubeflow/pipelines/blob/82d17ff616c5975f537dacf6c461040f2406e7e8/sdk/python/kfp/components/executor.py#L111-L121) is not currently doing anything. I left this unchanged, since 1) it's possible one path through this block could result in a `ValueError` and 2) I'm not totally …

chore(sdk): remove unused imports and variables

---

sdk/python/kfp/components/base_component.py
sdk/python/kfp/components/base_component_test.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/pipeline_task_test.py

Renames `PipelineTask` `arguments` parameter to `args` to be consistent with #7391.
**Checklist:**

chore(sdk): rename PipelineTask arguments parameter to args

---

components/gcp/container/build_image.sh

Got a postsubmit build error on installing rsync
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/r/rsync/rsync_3.1.3-8ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
```
Looking at the usage, it seems like it could be replaced via `cp`.
**Checklist:**

fix(components): remove rsync usage in gcp container build

---

sdk/RELEASE.md
sdk/python/kfp/cli/cli.py

Fixed issue where `kfp components build` command required a connection to a KFP API server
**Checklist:**

fix(sdk): no longer require KFP client for kfp components build

---

sdk/python/MANIFEST.in

Fixing error:
```
Collecting kfp==2.0.0a0
Using cached kfp-2.0.0-alpha.0.tar.gz (268 kB)
ERROR: Command errored out with exit status 1:
command: /usr/local/google/home/chesu/venv/test/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0i_km_15/kfp_ac9354e6bcc444ea81153188eb58d5fa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0i_km_15/kfp_ac9354e6bcc444ea81153188eb58d5fa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b0m3cjp6
cwd: /tmp/pip-install-0i_km_15/kfp_ac9354e6bcc444ea81153188eb58d5fa/
Complete output (7 lines): …
```

fix(sdk): include requirements.in in sdk manifest

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler.py

The wrong import caused setting the wrong SDK version in `pipeline_spec.sdk_version`:
https://github.com/kubeflow/pipelines/blob/481b108319fe998847c5b8bbb26782b0fb3707f8/sdk/python/kfp/compiler/compiler.py#L279
which is
https://github.com/kubeflow/pipelines/blob/481b108319fe998847c5b8bbb26782b0fb3707f8/sdk/python/kfp/deprecated/__init__.py#L15
**Checklist:**

fix(sdk): fix wrong kfp import causes wrong sdk_version being set in pipeline_spec.

---

sdk/RELEASE.md
sdk/python/kfp/client/client.py

In KFP SDK 2.0.0-alpha.1, we supported submitting pipeline IR in JSON format. This PR switches to supporting pipeline IR in YAML format instead.
**Checklist:**

feat(sdk)!: Support submitting pipeline IR in yaml format via `kfp.client`

---

sdk/RELEASE.md
sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_task_final_status.py
sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_task_final_status.yaml
sdk/python/kfp/components/executor.py
sdk/python/kfp/components/executor_test.py
sdk/python/kfp/components/task_final_status.py
sdk/python/requirements.in
sdk/python/requirements.txt

feat(sdk): Add pipeline_task_name to PipelineTaskFinalStatus

---

sdk/RELEASE.md
sdk/python/requirements.in
sdk/python/requirements.txt

Fix the pip conflicts **warning** if the user also installed latest `google-cloud-storage`
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. 
This behaviour is the source of the following dependency conflicts.
kfp 1.8.11 requires google-cloud-storage<2,>=1.20.0, but you have google-cloud-storage 2.2.1 which is incompatible.
```
According to the change log https://github.com/googleapis/python-storage/blob/main/CHANGELOG.md#200-2022-01-12
The only breaking change is **Remove Python 2 Support**, which should be fine for `kfp`
**Checklist:**

chore(deps): Bump google-cloud-storage to 2.2.1

---

sdk/python/kfp/client/client.py

Missed this in my previous PR: https://github.com/kubeflow/pipelines/pull/7458. 
Discovered this while trying `create_run_from_pipeline_func` and manually verified the fix work.
**Checklist:**

fix(sdk): fix yaml support `create_run_from_pipeline_func`

---

sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py
sdk/python/kfp/deprecated/cli/components.py
sdk/python/kfp/utils/__init__.py
sdk/python/kfp/utils/ir_utils.py
sdk/python/kfp/utils/ir_utils_test.py
sdk/python/setup.py

This PR removes `pydantic` from the component serialization process. A separate PR will remove use of the `pydantic` `BaseModel` and the `pydantic` library from dependencies.
**Checklist:**
our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

chore(sdk): stop using pydantic for serialization

---

sdk/RELEASE.md
sdk/python/kfp/client/client.py

Test code for reviewer, if desired:
```python
from kfp.client import Client
c = Client()
es = c.list_experiments()
experiment_id = 
es.to_dict()['experiments'][0]['id']
print("ARCHIVE", 
c.archive_experiment(experiment_id=experiment_id))
print("GET", 
c.get_experiment(experiment_id=experiment_id))
print("UNARCHIVE", 
c.unarchive_experiment(experiment_id=experiment_id))
print("GET", 
c.get_experiment(experiment_id=experiment_id))
pipeline_id = 
c.list_pipelines().to_dict()['pipelines'][0]['id']
print(c.list_pipeline_versions(pipeline_id=pipeline_id))
```
**Checklist:**
follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-c …

feat(sdk): add .list_pipeline_versions and .unarchive_experiment methods to Client

---

api/v2alpha1/pipeline_spec.proto

feat(api): Update IR with RetryPolicy

---

samples/test/utils/kfp/samples/test/utils.py
sdk/python/kfp/cli/compile.py
sdk/python/kfp/compiler_cli_tests/compiler_cli_tests.py
sdk/python/setup.py

Uses `click` for `dsl-compile` command, instead of `argparse`. A 
future PR will migrate `dsl-compile` to the main `kfp` namespace.
Notes for reviewer:
- Tests continue to pass
- The CLI signature is the same, though the help messages vary 
slightly:
Before:
```txt
usage: dsl-compile [-h] --py PY [--function FUNCTION]
[--pipeline-parameters PIPELINE_PARAMETERS]
[--namespace NAMESPACE] --output OUTPUT
[--disable-type-check]
optional arguments:
-h, --help            show this help message and exit
--py PY               local absolute path to a py file.
--function FUNCTION   The name of the function to compile if 
there are
multiple.
--pipeline-parameters PIPELINE_PARAMETERS
The pipeline parameters in JSON dict 
format.
--namespace NAMESPACE
The namespace for …
```

chore(sdk): use click for dsl-compile command

---

sdk/python/kfp/client/client.py

The PR adds `archive_run`, `unarchive_run`, and `delete_run` methods to the `Client` class. It just consumes the associated methods in the Python client. No additional logic. Please let me know if you'd like me to add it the v1 client as well.
It also tidies up some of the type hints and docstrings. 
Once this is merged, I can contribute a discrete PR to update [this](https://github.com/kubeflow/pipelines/blob/master/test/sample-test/run_resnet_cmle_test.py#L119) test and potentially others that don't clean up artifacts.
**Checklist:**

feat(sdk): add archive, unarchive, and delete run methods and tidy docstrings

---

sdk/python/kfp/cli/experiment.py
sdk/python/kfp/cli/pipeline.py
sdk/python/kfp/cli/recurring_run.py
sdk/python/kfp/cli/run.py

Adds the following functionality to the CLI per the V1 -> V2 CLI migration plan:
- run archive
- run unarchive
- run delete
- recurring-run enable
- recurring-run disable
- pipeline get-version
- experiment unarchive
Also:
- cleans up single/double quote inconsistency
- improves informativeness of output for user
**Checklist:**

feat(sdk): add client methods to cli

---

frontend/src/pages/PipelineDetailsV2.tsx

Since IR payload is in yaml format, switch to use yaml mode in Editor component.
/assign @jlyaoyuli 
**Checklist:**

fix(frontend): Use yaml mode for PipelineSpec editor view

---

backend/src/common/client/api_server/experiment_client.go
backend/src/common/client/api_server/job_client.go
backend/src/common/client/api_server/pipeline_client.go
backend/src/common/client/api_server/pipeline_upload_client.go
backend/src/common/client/api_server/run_client.go
backend/src/common/client/api_server/util.go
backend/src/common/client/api_server/visualization_client.go
backend/test/initialization/initialization_test.go
backend/test/integration/experiment_api_test.go
backend/test/integration/flags.go
backend/test/integration/job_api_test.go
backend/test/integration/run_api_test.go
backend/test/integration/upgrade_test.go
backend/test/test_utils.go

Added 3 flags:
- isDebugMode is enables HTTP request/response logging
- IsKubeflowMode enables the tests in full Kubeflow mode
- resourceNamespace: the namespace/profile under which the test
resources are created
Added a new HTTP client that uses SA token volume projection auth. The
test pods will be set up to project SA token.
Plumbed everything through for experiment API tests. The other tests
will be enabled in subsequent PRs.

feat(conformance): Enable experiment API tests in KF mode.

---

sdk/RELEASE.md
sdk/python/kfp/cli/cli.py
sdk/python/kfp/cli/cli_test.py
sdk/python/kfp/cli/component.py
sdk/python/kfp/cli/diagnose_me_cli.py
sdk/python/kfp/cli/dsl_compile.py
sdk/python/kfp/cli/experiment.py
sdk/python/kfp/cli/pipeline.py
sdk/python/kfp/cli/recurring_run.py
sdk/python/kfp/cli/run.py
sdk/python/kfp/cli/utils/parsing.py
sdk/python/kfp/cli/utils/parsing_test.py
sdk/python/kfp/client/client.py

Makes several improvements to the KFP CLI help text, including:
- Programatically retrieving option help text from docstrings.
- Making command descriptions more consistent.
- Cleaning up existing docstrings.
This PR also adds basic smoke tests for each command group of the CLI to ensure they 
run and retrieve help text correctly.
**Checklist:**
more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

feat(sdk): improve cli help text

---

sdk/python/kfp/cli/cli_test.py
sdk/python/kfp/cli/dsl_compile.py

Deprecates `dsl-compile` in favor of `kfp dsl compile`.
**Checklist:**

feat(sdk): deprecate dsl-compile

---

backend/test/integration/pipeline_api_test.go

Pipelines are not namespaced, so the changes are quite straightforward.

feat(conformance): adapt pipeline API tests to KF environment

---

backend/test/integration/experiment_api_test.go
backend/test/integration/run_api_test.go
backend/test/test_utils.go

- Undid earlier refactoring in test_util.go. I think having the util
function to take a parameter structure is much more readable than
constructing api parameters in the util function.

feat(conformance): adapt run api tests to KF env

---

backend/src/common/client/api_server/visualization_client.go
backend/test/integration/job_api_test.go
backend/test/integration/run_api_test.go
backend/test/integration/upgrade_test.go
backend/test/integration/visualization_api_test.go
backend/test/test_utils.go

- Adapted job, rn, upgrade and visualization tests
- Undid earlier change where I had to pass in empty string to indicate
that resource reference should not be overridden because experiment id
is specified
- Updated visualization client to support SA token projection auth

feat(conformance): adapt remaining tests to KF env

---

sdk/python/kfp/registry/registry_client_test.py

Use the standard library `unittest.mock` instead of external dependency `mock`. Otherwise, tests fail outside of the test environment when the user does not first run `pip install mock`.
**Checklist:**

chore(sdk): use unittest.mock instead of mock

---

backend/src/cache/main.go

Provide option to specify the TLS filename 
Then we will use cert-manager created in the manifests repo for cache 
(Work in Progress: Will move this to KFP repo) https://github.com/kubeflow/manifests/pull/2186
Fixes issue : https://github.com/kubeflow/manifests/issues/2165

fix(cache): Change kfp cache cert names to match cert-manager

---

api/v2alpha1/pipeline_spec.proto

Adds the `is_optional` field to ParameterSpec proto.
**Checklist:**

feat(IR): add is_optional to ParameterSpec proto

---

sdk/python/kfp/cli/pipeline.py

Fixes incorrect implementation of upload pipeline version.
**Checklist:**
should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

fix(sdk): fix CLI upload pipeline version

---

backend/src/apiserver/main.go
backend/src/common/client/api_server/healthz_client.go
backend/test/integration/healthz_api_test.go

1. explicit content type with application/json on healthz response.
2. add healthz client api under common/client for integration test
3. add integration test for healthz endpoint
**Checklist:**

fix(backend): fixes healthz response by adding json content type. Fixes #7525

---

manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml

Co-authored-by: moorthy156 <narayanamoorthy.mari@gmail.com>
When we pivoted from an in-cluster mysql deployment to an externally hosted RDS instance for the metadata store, we ran into a scenario where the ml-pipeline-apiserver pod entered a crash loop because it didn't have a long enough grace period to complete its database migration.
This pod is unique in that its startup time is variable depending on whether or not a migration needs to occur. A [startup probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) is perfect for this, since it offers a grace period in the event of a migration, but doesn't delay pod readiness when a migration does not need to happen.
Relevant issue: …

feat[deployment]: add startup probe to pipeline API deployment

---

api/v2alpha1/pipeline_spec.proto

- Adds `IteratorPolicy` message to IR proto definition, containing a single `parallelism_limit` field of type `int32`.
- Adds a `iterator_policy` field of `IteratorPolicy` type to `PipelineTaskSpec` IR definition, used for controlling ParallelFor iterator task parallelism limit.
- Also removes trailing white spaces in proto file
**Checklist:**

feat(IR): adds IteratorPolicy to PipelineTaskSpec proto for support of parallelism setting on ParallelFor

---

sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py

Fixes a bug in loading if-present placeholders from v1 YAML components. This bug was related to a logic error in the recursive processing of nested concat and if-present placeholders.
**Checklist:**

fix(sdk): fix load v1 if present placeholder

---

sdk/python/setup.py

Sets the `setuptools.setup` long description content type to 'text/markdown' so that PyPI 
can read markdown. For more info: 
https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata.
**Checklist:**

chore(sdk): use markdown for long description content type

---

frontend/src/pages/RunList.test.tsx
frontend/src/pages/RunList.tsx

- Fix #7827 
1. Add filter functionality for run lists with a run ID list mask
2. Add tests to verify that the filter mechanism for `RunList.tsx` works correctly in all cases
**Screen Recording:**
_This screencast shows both the "Runs" tab and the Run Comparison page working correctly (though only the latter needed a fix)._
https://user-images.githubusercontent.com/7987279/171758270-80080e81-4df8-4bf0-804d-8db4a5d61e8b.mp4
**Notes:**
- This issue occurred because the filtering mechanism typically occurs through the [`listRuns` API](https://github.com/kubeflow/pipelines/blob/340318625c527836af1c9abc0fd0d76c0a466333/frontend/src/apis/run/api.ts#L1725), but since that method does not have support for the `runIdListMask`, when a mask exists each run is fetched …

fix(frontend): Fix run comparison filter

---

manifests/kustomize/env/cert-manager/base/cache-cert-issuer.yaml
manifests/kustomize/env/cert-manager/base/cache-cert.yaml
manifests/kustomize/env/cert-manager/base/cache-webhook-config.yaml
manifests/kustomize/env/cert-manager/base/kustomization.yaml
manifests/kustomize/env/cert-manager/base/params.yaml
manifests/kustomize/env/cert-manager/cluster-scoped-resources/kustomization.yaml
manifests/kustomize/env/cert-manager/dev/delete-cache-deployer.yaml
manifests/kustomize/env/cert-manager/dev/kustomization.yaml
manifests/kustomize/env/cert-manager/dev/namespace.yaml
manifests/kustomize/env/cert-manager/dev/params.yaml
manifests/kustomize/env/cert-manager/platform-agnostic-multi-user/delete-cache-deployer.yaml
manifests/kustomize/env/cert-manager/platform-agnostic-multi-user/kustomization.yaml

- Manifests for using cert-manager for the certificate required by cache-server
- Created a cert-manager directory under env instead of adding the manifests under aws since this issue was [also found on Mercedes Benz distribution of Kubernetes](https://github.com/kubeflow/manifests/issues/2165#issuecomment-1096633299). This means with the current implementation(which does not use cert-manager), caching will not work on any k8s distribution which issues certificates for CSRs with signerName `kubernetes.io/kubelet-serving` only to kubelets
- Addressed comments from #7779
**Testing:**
- Manually tested both standalone installation and multi user with Kubeflow installed with a custom built cache-server image since there are changes to …

feat(backend): use cert-manager for cache server cert

---

sdk/python/kfp/components/structures_test.py

I missed a path that needed to be updated in my review of #7849. `unittest` fails to catch this, while `pytest` reliably catches this. I am unsure why this is. I will make changes to prevent similar failures in the future in a separate PR.
**Checklist:**

chore(sdk): fix component compilation test path

---

sdk/README.md
sdk/python/kfp/components/structures_test.py
sdk/python/requirements-dev.txt
sdk/python/requirements-test.txt
test/presubmit-tests-sdk.sh

#7868 fixed a break in our unit tests that `unittest` did not pick up. To avoid this sort of break in the future and to leverage the benefits of `pytest` over `unittest`, this PR switches our KFP SDK unit tests to use `pytest` as the command line executable, as it is fully compatible with tests written using the `unittest` library.
Note the much more readable test output compared to previous `unittest` executions.
**Checklist:**

chore(sdk): use pytest instead of unittest for test execution

---

frontend/src/pages/Compare.test.tsx
frontend/src/pages/Compare.tsx
frontend/src/pages/CompareV1.test.tsx
frontend/src/pages/CompareV1.tsx

1. Show a page error when selected runs are a mix of v1 and v2 (and the v2 feature flag is enabled), as referenced in [this GitHub discussion](https://github.com/kubeflow/pipelines/pull/7793#discussion_r883989251)
2. Show a page error when there are fewer than two selected runs, or greater than ten selected runs
- This is only achievable for the user by hard-coding the URL, but I decided to handle that edge case regardless to be thorough
3. Display an info banner on the v1 page when the v2 feature flag is disabled and all runs are v2, notifying the user that in order to view any useful information they must enable the v2 feature flag
**Screencast:**
https://user-images.githubusercontent.com/7987279/172077141-724d08b0-f676-4359-82e4-bcaf28c01f5d.mp4
_The …

feat(frontend): Update compare page and banner states based on run versions and count

---

components/google-cloud/google_cloud_pipeline_components/container/v1/gcp_launcher/upload_model_remote_runner.py

[ModelUploadOp](https://google-cloud-pipeline-components.readthedocs.io/en/google-cloud-pipeline-components-1.0.7/google_cloud_pipeline_components.v1.model.html#google_cloud_pipeline_components.v1.model.ModelUploadOp) allows users to specify `explanation_metadata` so that they may provide a list of features and labels to be used with Explainable AI on model upload. This currently works fine for models built with TensorFlow, but for models built using scikit-learn or xgboost, the list of features provided in the `explanation_metadata` argument are dropped.
Because features and outputs provided in `explanation_metadata` should be empty for scikit-learn/xgboost produced models ([per the API spec](https://cloud.google.com/vertex-ai/docs/explainable-ai/configuri …

fix(components): Preserve empty features in explanation_spec

---

frontend/src/pages/CompareV1.tsx

- Fix #7855
**Screencast:**
https://user-images.githubusercontent.com/7987279/172735401-8a6c7dc2-2689-4df3-93f8-2e6be9b5ff3a.mp4
_The screencast shows how the Refresh button on the Run Comparison page now updates the run list table._
**Notes:**
- I modeled the changes off of the code in `AllRunsList.tsx`, as shown here: https://github.com/kubeflow/pipelines/blob/e7dbbcb3b43006fc60c335f814b87b776f4cee96/frontend/src/pages/AllRunsList.tsx#L79-L85 However, I left in the existing call to `this.load()` because that handles the banner refresh.
- I didn't add any new tests as the table is handled by a separate component - please let me know if I should add something to verify this fixed behavior.
**Checklist:**

fix(frontend): Fix Run Comparison refresh button

---

sdk/RELEASE.md
sdk/python/kfp/v2/compiler/compiler.py
sdk/python/kfp/v2/compiler/compiler_test.py
sdk/python/kfp/v2/compiler/compiler_utils.py
sdk/python/kfp/v2/compiler/compiler_utils_test.py
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_retry.json
sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_retry.py
sdk/python/requirements.in

Adds support for retry policy message when compiling pipelines to IR in the v1 version of the KFP SDK.
**Checklist:**

feat(sdk): add retry policy support for IR compilation support in kfp==1.8

---

sdk/python/kfp/components/pipeline_context.py
sdk/python/kfp/components/pipeline_context_test.py

Provides an informative exception when `@pipeline` is called instead of `@pipeline()`.
/cc @ironpan
**Checklist:**

feat(sdk): throw informative exception on uncalled @pipeline decorator

---

components/aws/sagemaker/tests/integration_tests/Dockerfile

The current eksctl version fails to spin up an EKS 1.21 cluster. 
```
[Creating EKS] Launching EKS cluster sagemaker-kfp-.......>
--
46 | Error: invalid version, supported values: 1.15, 1.16, 1.17, 1.18, 1.19
```
Updated to eksctl 0.86.0. 
**Checklist:**

chore: update the eksctl version required for latest eks version

---

samples/test/config.yaml

The KFP v2 BE does not yet support the new IR concat placeholder struct syntax. Commenting out until this feature is added in the KFP BE beta.3 release.
**Checklist:**

test(samples): skip concat placeholder test

---

backend/src/apiserver/client/minio.go
backend/src/apiserver/client_manager.go
backend/src/apiserver/storage/minio_client.go
backend/src/apiserver/storage/minio_client_fake.go
backend/src/apiserver/storage/object_store.go
backend/src/apiserver/storage/object_store_test.go
backend/third_party_licenses/apiserver.csv
go.mod
go.sum

- Minio-go versions v6.0.53 and up support IRSA, updating the version to gain these benefits.
Have used docker to create an image with these changes and deployed them on a fresh eks cluster. Everything worked as expected with existing behavior and usage of minio i.e(using static aws credentials). Successfully ran the sample pipelines included and verified upload of data.
Additionally the minio-go changes that included support for IRSA which were included in minio-go version v6.0.53 and up are already included and part of the base minio version which we are using so we will not need to update it and thus will not face licensing issues. Minio included the support for it https://github.com/minio/minio/tree/RELEASE.2019-03-06T22-47-10Z while we are using a …

feat(backend): update minio-go to support irsa

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_retry.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_retry.yaml
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py
sdk/python/requirements.in

Adds retry policy support to KFP v2 SDK.
**Checklist:**

feat(sdk): add retry policy support to kfp v2

---

sdk/RELEASE.md
sdk/python/kfp/client/client.py
sdk/python/kfp/client/client_test.py
sdk/python/kfp/deprecated/cli/cli.py

feat(sdk/client): implements overriding caching options at submission

---

sdk/python/kfp/components/yaml_component.py
sdk/python/kfp/components/yaml_component_test.py

The `kfp.components` module was using `str` and `bytes` interchangeably, had incorrect type annotations, and opportunities to improve error messages and docstrings.
This PR fixes these, as well as improves tests.
**Checklist:**

fix(sdk): fixes kfp.components module type annotations, docstrings, and string/bytes processing

---

.pre-commit-config.yaml
docs/source/dsl.rst
sdk/python/kfp/__init__.py
sdk/python/kfp/cli/utils/parsing_test.py
sdk/python/kfp/client/__init__.py
sdk/python/kfp/client/client.py
sdk/python/kfp/compiler/__init__.py
sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/components/__init__.py
sdk/python/kfp/components/base_component.py
sdk/python/kfp/components/component_decorator.py
sdk/python/kfp/components/importer_node.py
sdk/python/kfp/components/pipeline_channel.py
sdk/python/kfp/components/pipeline_context.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/pipeline_task_test.py
sdk/python/kfp/components/python_component.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/task_final_status.py
sdk/python/kfp/components/tasks_group.py
sdk/python/kfp/components/types/artifact_types.py
sdk/python/kfp/components/types/type_annotations.py
sdk/python/kfp/components/yaml_component.py
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/registry/__init__.py
sdk/python/kfp/registry/registry_client.py

This PR refreshes the KFP SDK's public API 
docstrings. This includes:
- Updating what is considered part of our public api 
via the `__all__` special module variables
- Adds module docstrings for all public modules.
- Removes stale v1 language
- Adds significant number of usage examples
- Improves some of the conventions, including:
- Tone of argument descriptions
- Not including parameter type strings in docstring
- Using code style like `this` when referring to 
parameters, other package objects, 
programmatic names, or defaults
- Order of parameters and example code
- Style of example code
**Checklist:**
follow our title convention. [Learn more about the pull request title convention used in this …

docs(sdk): refresh SDK public API docstrings

---

backend/src/apiserver/model/db_status.go
backend/src/apiserver/model/default_experiment.go

The `db_statuses` and `default_experiments` models in the backend apiserver do not contain primary keys. This prevents the apiserver from being deployed with MySQL with Group Replication enabled ([as MySQL with Group Replication requires primary keys](https://lefred.be/content/mysql-group-replication-and-table-design/)). This change add the `primary_key` tag to the sole column in these tables (`db_statuses` and `default_experiments`).
**Checklist:**

chore(backend): modify default_experiments and db_statuses tables to have primary keys. Fixes #8014

---

sdk/python/kfp/components/base_component.py

Because `kwargs` is a dictionary, and `task_inputs` starts off empty, it's not possible to get multiple values for a key. 
**Checklist:**

chore(sdk): remove the unreachable validation code

---

frontend/server/configs.ts

Currently the S3 endpoint in the frontend server config is hard coded to `s3.amazonaws.com`.
This endpoint is not valid for China regions (`s3.amazonaws.com.cn`), preventing users in those regions from accessing artifacts via the KFP UI. 
This PR supports reading the endpoint as a passable environment variable `AWS_S3_ENDPOINT` so that users can specify the endpoint that is compatible with their region. If no `AWS_S3_ENDPOINT` variable is found, the default `s3.amazonaws.com` endpoint will be used.
**Checklist:**

fix(frontend): make frontend server config s3 endpoint url configurable via environment variable. Fixes #7995

---

components/google-cloud/RELEASE.md
components/google-cloud/google_cloud_pipeline_components/version.py
samples/test/config.yaml
samples/v2/pipeline_container_no_input.py
samples/v2/pipeline_container_no_input_test.py
samples/v2/two_step_pipeline_containerized.py
samples/v2/two_step_pipeline_containerized_test.py
sdk/python/kfp/compiler/_read_write_test_config.py
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/test_data/components/container_io.py
sdk/python/kfp/compiler/test_data/components/container_io.yaml
sdk/python/kfp/compiler/test_data/components/container_no_input.py
sdk/python/kfp/compiler/test_data/components/container_no_input.yaml
sdk/python/kfp/compiler/test_data/components/container_with_artifact_output.py
sdk/python/kfp/compiler/test_data/components/container_with_artifact_output.yaml
sdk/python/kfp/compiler/test_data/pipelines/container_component_with_no_inputs.py
sdk/python/kfp/compiler/test_data/pipelines/container_component_with_no_inputs.yaml
sdk/python/kfp/compiler/test_data/pipelines/two_step_pipeline_containerized.py
sdk/python/kfp/compiler/test_data/pipelines/two_step_pipeline_containerized.yaml
sdk/python/kfp/components/__init__.py
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/component_factory_test.py
sdk/python/kfp/components/container_component.py
sdk/python/kfp/components/container_component_decorator.py
sdk/python/kfp/components/container_component_decorator_test.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/dsl/__init__.py

The first 16 commits handling functions with no inputs are already reviewed and approved in https://github.com/kubeflow/pipelines/pull/7973. 
**Checklist:**

feat(sdk): supporting bring your own container for arbitrary input and outputs 

---

docs/index.rst
docs/source/cli.rst
sdk/python/kfp/cli/cli.py
sdk/python/kfp/cli/cli_test.py
sdk/python/kfp/cli/compile_.py
sdk/python/kfp/cli/component.py
sdk/python/kfp/cli/dsl.py
sdk/python/setup.py

This PR cleans up a few aspects of the [KFP CLI reference docs](https://kubeflow-pipelines.readthedocs.io/en/master/source/cli.html) discovered while working on the kubeflow.org docs. After this PR the docs will:
- use expanded "Command Line Interface" for title of section (instead of "kfp CLI")
- not show an alpha feature stage notice in docs or cli help text
- hide the deprecated `--engine argument` on `kfp component build`
- currently show the `kfp dsl compile` command as such, instead of as `kfp dsl dsl-compile`
**Checklist:**

docs(sdk): clean up kfp v2 cli reference docs

---

.pre-commit-config.yaml
sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/test_data/components/unsupported/output_named_tuple.py
sdk/python/kfp/components/yaml_component_test.py
sdk/python/kfp/v2/compiler.py
sdk/python/kfp/v2/components.py
sdk/python/kfp/v2/dsl.py

Some pull requests create unused imports. This PR provides a pre-commit hook to automate the removal of unused imports to make code safer and PRs more effective.
**Safer code:** Some imports have desired (or undesired) side-effects. If we have spurious unused imports, it can challenging to know which "unused" imports we need and which we don't. Spurious imports are also superfluous code.
**Effective PRs:** Commenting on unused imports is also not meaningful PR feedback.
**Checklist:**

chore(sdk): add pre-commit hook to remove unused imports

---

sdk/RELEASE.md
sdk/python/kfp/compiler/_read_write_test_config.py
sdk/python/kfp/compiler/test_data/components/container_with_concat_placeholder.py
sdk/python/kfp/compiler/test_data/components/container_with_concat_placeholder.yaml
sdk/python/kfp/compiler/test_data/components/container_with_if_placeholder.py
sdk/python/kfp/compiler/test_data/components/container_with_if_placeholder.yaml
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/component_factory_test.py
sdk/python/kfp/components/container_component_artifact_channel.py
sdk/python/kfp/components/container_component_artifact_channel_test.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py

1. Extract the `ContainerComponentArtifactChannel` class into a separate file in order to move the validation logic for ContainerSpec into its constructor.
2. Add compiler tests for if and concat placeholder on `container_component` to ensure the compatability.
/cc @connor-mccarthy 
**Checklist:**

chore(sdk): Add test for if and concat placeholder and validate artifact channel usage

---

sdk/python/kfp/compiler/test_data/components/container_with_concat_placeholder.py
sdk/python/kfp/compiler/test_data/components/container_with_if_placeholder.py
sdk/python/kfp/components/placeholders.py
sdk/python/kfp/components/structures_test.py
sdk/python/kfp/dsl/__init__.py

This PR exposes `IfPresentPlaceholder` and `ConcatPlaceholder` to kfp.dsl and add examples to show how they could be used to author containerized components.  
**Checklist:**

feat(sdk): expose IfPresentPlaceholder and ConcatPlaceholder to kfp.dsl

---

sdk/RELEASE.md
sdk/python/kfp/compiler/_read_write_test_config.py
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_parallelfor_parallelism.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_parallelfor_parallelism.yaml
sdk/python/kfp/components/tasks_group.py
sdk/python/kfp/components/tasks_group_test.py

- Updated ParallelFor under tasks_group to handle parallelism setting
- Updated Compiler to compile non-default parallelism setting in ParallelFor into iteratorPolicy in IR
- Added related tests
**Checklist:**

feat(sdk): Support Parallelism in ParallelFor in KFP SDK V2

---

samples/test/utils/kfp/samples/test/utils.py
sdk/RELEASE.md
sdk/python/kfp/compiler/_read_write_test_config.py
sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/pipeline_spec_builder_test.py
sdk/python/kfp/compiler/read_write_test.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_in_pipeline.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_in_pipeline.yaml
sdk/python/kfp/compiler/test_data/pipelines/pipeline_in_pipeline_complex.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_in_pipeline_complex.yaml
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/graph_component.py
sdk/python/kfp/components/pipeline_context.py
sdk/python/kfp/components/pipeline_context_test.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/utils.py
sdk/python/kfp/components/utils_test.py

- Support re-using a pipeline in another pipeline (aka graph component).
- Refactoring compiler code, and move pipeline compiling trigger to `@pipeline` decorator.
**Checklist:**

feat(sdk)!: Implement Graph Component

---

sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_gcpc_types.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_importer_and_gcpc_types.py
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/importer_node.py
sdk/python/kfp/components/types/artifact_types.py
sdk/python/kfp/components/types/type_utils.py
sdk/python/kfp/components/types/type_utils_test.py

Renames artifact class attributes from `.TYPE_NAME` to 
`.schema_title` and `.VERSION` to `.schema_version`.
Also renames variables and parameters throughout to be consistent.
**Checklist:**

feat(sdk): rename kfp artifact attributes (support custom artifact types pt. 1)

---

sdk/RELEASE.md
sdk/python/kfp/compiler/_read_write_test_config.py
sdk/python/kfp/compiler/compiler.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/read_write_test.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_in_pipeline_complex.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_in_pipeline_complex.yaml
sdk/python/kfp/compiler/test_data/pipelines/pipeline_in_pipeline_loaded_from_yaml.py
sdk/python/kfp/compiler/test_data/pipelines/pipeline_in_pipeline_loaded_from_yaml.yaml
sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_outputs.py
sdk/python/kfp/components/base_component.py
sdk/python/kfp/components/graph_component.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py
sdk/python/kfp/components/yaml_component.py

- Support loading pipeline from yaml to use as a component.
- Fix bug where InputSpec ignores artifacts inputs from IR.
- Fix bug where executor label and component name may not be merged correctly due to name collision.
**Checklist:**

feat(sdk): Support loading pipeline from yaml

---

sdk/python/kfp/client/client.py

This PR implements a tiny change that enables deep link printing outside of IPython. It also adds some missing quotation marks that wrap around the link in three of the constructed `html` variables. Lastly, it adds `target="_blank"` attributes to the pipeline details html values to standardize things. 
[Here's](https://github.com/kubeflow/pipelines/issues/8141) a link to the relevant issue.
**Checklist:**

feature(sdk): print links outside of ipython. Fixes #8141

---

sdk/python/setup.py

The poetry package manager executes `setup.py` differently than pip, which means that `__file__` is initialized to just `setup.py`, which means that `where` would be set to the empty string. The proposed change has been tested with both pip and poetry.
**Checklist:**

fix(sdk): make sdk installable with poetry

---

backend/src/common/util/execution_spec.go
backend/src/common/util/workflow.go
backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go

Instead of changing the WorkflowResource.Spec to string, use interface{} to allow backward compatibility.
Add type casting and marshal/unmarshal to properly handle old swf CRs.
I also cleaned up duplicate imports in `workflow.go` 
fixed issue found here: https://github.com/kubeflow/pipelines/pull/8050#issuecomment-1245793840
Signed-off-by: Yihong Wang <yh.wang@ibm.com>
**Checklist:**

fix(backend): fix backward compatibility in scheduledworkflow

---

sdk/python/kfp/client/auth.py
sdk/python/kfp/client/client.py

On February 16 2022, Google [announced](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html) plans to make Google OAuth interactions safer by using more secure OAuth flows. The migration guide is available [here](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration). The issue was previously reported in #7474.
The proposed solution is based on the loopback flow and it fetches an authentication code from the response url. This method has been deprecated for mobile apps, but it is still the recommended workaround for desktop apps. Although we might need to change this in the future, I propose to include this change in the next release to unblock Kubeflow users. A similar solution was proposed in #7526.
There are two scenarios:
1. SSH connection …

fix(sdk): Replace OOB authentication with loopback flow

---

sdk/python/kfp/components/importer_node.py
sdk/python/kfp/components/importer_node_test.py
sdk/python/test_data/pipelines/pipeline_with_dynamic_importer_metadata.py
sdk/python/test_data/pipelines/pipeline_with_dynamic_importer_metadata.yaml
sdk/python/test_data/test_data_config.yaml

Enables dynamic metadata (passed from pipeline parameter and other inputs) for importer.
**Checklist:**

feat(sdk): enable dynamic importer metadata

---

backend/src/apiserver/resource/resource_manager.go

Fixes https://github.com/kubeflow/pipelines/issues/8256
Manually verified the change resolves the aforementioned issue:
**Checklist:**

fix(backend): Fix "Unknown execution spec" error. Fixes #8256

---

frontend/src/lib/v2/StaticFlow.ts

Because of early return, the DAG visualization usually lacks some edges which are declared in the IR.
Before the fix:
After the fix:
**Checklist:**

fix(frontend): Fix the issue when drawing dependentTask for task-to-task edges.

---

sdk/python/kfp/components/component_decorator_test.py
sdk/python/kfp/components/component_factory.py

Fixes a bug where a component with a `NamedTuple` output with a `Dict` 
data type would fail to compile.
**Checklist:**

fix(sdk): fix NamedTuple output with Dict/List bug

---

components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests

The standalone cert manager deployment initially creates 2 ml-pipeline pods and patches one and terminates the other. `kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/cert-manager/dev?ref=$KFP_VERSION"` takes around ~1-2 minutes to create one ml pipeline pod and terminate the other. I have put in a sleep statement to make sure that the other pipeline pod terminates before the kubectl wait statement. Without this there is a chance of the ephemeral integration test failing if both the ml pipeline pods aren't ready.
**Checklist:**

test: Make ephemeral sagemaker component tests more stable

---

sdk/python/kfp/cli/component.py

Fix typo in docstring of cli/component : Pypi -> PyPI

fix(sdk): Fix PyPi typo in cli/component docstring

---

sdk/python/kfp/cli/component.py

Utility files may not have KFP component definition, which is completely normal and should be allowed.
Fixes https://github.com/kubeflow/pipelines/issues/8353
**Checklist:**

fix(sdk): Fix "No KFP components found in file" error. Fixes #8353

---

frontend/src/components/graph/Constants.ts
frontend/src/lib/v2/DynamicFlow.ts
frontend/src/lib/v2/StaticFlow.ts

- PipelineSpec has a `output` field which maps the `outputDefinition` of a DAG to the inner task and artifact.
- If this is an Artifact output from a SubDAG, identify its subtask and artifact so the node status and side panel can find the corresponding Artifact in MLMD.
Before: 
After:
**Checklist:**

fix(frontend): Surface output artifact of a SubDAG by reading subtask

---

.cloudbuild.yaml
.release.cloudbuild.yaml
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
test/tag_for_hosted.sh

Upgrading MySQL to 8.0-debian. Reasons:
- Current MySQL 5.7 has several critical vulnerabilities:
- [CVE-2020-35527 ](https://security-tracker.debian.org/tracker/CVE-2020-35527)
- [CVE-2022-37434 ](https://security-tracker.debian.org/tracker/CVE-2022-37434)
- [CVE-2021-20223 ](https://security-tracker.debian.org/tracker/CVE-2021-20223)
- KFP already offers support for MySQL 8.0 via managed storage options (e.g. on [GCP](https://github.com/GoogleCloudPlatform/kubeflow-distribution/blob/master/kubeflow/apps/pipelines/kustomization.yaml#L24)). This has been already tested.
- Other Kubeflow components already support MySQL 8.0 (e.g. [katib](https://github.com/kubeflow/katib/blob/7bf39225f7235ee4ba6cf285ecc2c455c6471234/manifests/v1beta1/components/mysql/mysql.y …

fix(backend): Upgrade mysql to 8.0.26

---

backend/src/cache/server/mutation.go
backend/src/cache/server/watcher.go

A regression introduced by https://github.com/kubeflow/pipelines/pull/8270. 
User cache setting `P0D` (0 in seconds, meaning disable caching) was overridden by the default global cache config (-1 in seconds, meaning infinite caching staleness).
Fixes #8366
**Checklist:**

fix(backend): Fix user cache setting P0D ignored by cache server. Fixes #8366

---

frontend/src/lib/Utils.tsx

As already remarked by @jlyaoyuli in https://github.com/kubeflow/pipelines/issues/7655 , `Buffer` is not available in the browser, hence the error occurs.
I could reproduce the error with a large graph which triggers the compressed transfer. Changing the decompression as in this PR resolved the issue for my test.

fix(frontend): Use browser-compatible atob instead of Buffer for frontend graph decompression. Fixes #7655

---

sdk/python/kfp/cli/components.py
sdk/python/kfp/cli/components_test.py

Adds a CLI flag to allow the user to skip `docker build` step in `kfp components build`
Addresses #8382 for SDK version 1.8
If accepted, I will recreate the same mechanism in master for SDK version 2
**Checklist:**

feat(sdk): add --build-image option to 'kfp components build' to allow users to skip docker build. Fixes #8382 for 1.8

---

sdk/python/kfp/cli/component.py
sdk/python/kfp/cli/component_test.py

Adds a CLI flag to allow the user to skip docker build step in `kfp component build`
Addresses https://github.com/kubeflow/pipelines/issues/8382 for SDK version 2.0
**Checklist:**

feat(sdk): add --build-image option to 'kfp components build' to allow users to skip docker build. Fixes #8382 for 2.0

---

backend/src/apiserver/server/api_converter.go

This PR enables including the namespace of a pipeline as a resource reference in the Pipeline API response. For more details and the main drive for it, PTAL https://github.com/kubeflow/pipelines/issues/4197#issuecomment-1282259019.
**Checklist:**

feat(backend): Include namespace in Pipeline API model. Part of #4197

---

components/aws/sagemaker/tests/integration_tests/environment.yml
components/aws/sagemaker/tests/integration_tests/resources/config/ack-training-job/config.yaml

Conda uses the latest pytest version unless specified in enviorment.yml. The latest pytest version will not work with xdist=2.1.0 because the latest pytest version dropped support for a package that xdist was using(https://docs.pytest.org/en/stable/changelog.html). As a result the integration tests/continuously running tests fail.  
`components/aws/sagemaker/tests/integration_tests/environment.yml` - Update xdist to use the latest version.
`components/aws/sagemaker/tests/integration_tests/resources/config/ack-training-job/config.yaml` - Increase timeout to reduce flakiness in continuously running tests.
**Checklist:**

Test: Update pytest xdist dependency in Sagemaker KFP integration test

---

components/kserve/component.yaml
components/kserve/src/kservedeployer.py

Add KServe component flag to disable storing CRD status into output parameters. This way users can choose to not produce the KServe CRD status in case the status is too big or have sensitive information. 
related: #8320
cc @nachogarciam 
**Checklist:**

feat(components): add KServe component flag to disable storing CRD status into output parameters

---

test/deploy-cluster.sh

e2e test failing with error:
> ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.23. This is to prepare for the removal of Dockershim in Kubernetes v1.24. We recommend that you migrate to image types based on Containerd (examples). For more information, contact Cloud Support.
https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/8403/kubeflow-pipeline-e2e-test/1587496737537265664
**Checklist:**

fix(test): unable to create test cluster

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/read_write_test.py
sdk/python/kfp/components/component_decorator_test.py
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/container_component_artifact_channel_test.py
sdk/python/kfp/components/importer_node.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/pipeline_task_test.py
sdk/python/kfp/components/placeholders.py
sdk/python/kfp/components/placeholders_test.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py
sdk/python/kfp/components/v1_modelbase.py

This PR simplifies the implementation of in-memory placeholders, as well as simplifies/removes logic rendered unnecesary by the changes to placeholders.
This change is primarily driven the realization that we do not need to deserialize placeholder strings from IR into the placeholder objects that are used for serialization, as they do not offer us anything after the initial serialization due to the immutability of loaded PipelineSpec.
**Checklist:**

refactor(sdk): simplify placeholders and logic

---

components/test_load_all_components.sh
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/placeholders.py
sdk/python/kfp/components/placeholders_test.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py

This PR:
- Adds a check to prevent `then` or `else_` arguments to `IfPresentPlaceholder` from 
being lists if the `IfPresentPlaceholder` is within a `ConcatPlaceholder`.
- Fixes a bug in handling of `then` and `else_` when either is a string element (instead of 
a list of elements)
**Checklist:**

fix(sdk): fix nested placeholders and block illegal IfPresent form in Concat

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/test_data/pipelines/xgboost_sample_pipeline.yaml

Fixes a bug where default values for boolean inputs were sometimes 
serialized as numbers (e.g., `1.0` for `true`) instead of booleans.
**Checklist:**

fix(sdk): fix boolean default value serialization bug

---

sdk/python/kfp/components/base_component.py
sdk/python/kfp/components/base_component_test.py
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py

Similar to #8415.
This removes some trickery in the definition and usage of `InputSpec` that was originally 
intended to make deserialization from v1 component YAML turnkey. The v1 backward compatibility 
handling we have added since them makes this no longer helpful and decreases the clarity of the 
code.
**Checklist:**

refactor(sdk): simplify InputSpec

---

sdk/RELEASE.md
sdk/python/setup.py

Missed where versions are specified in #8470.
To test these changes:
`pip install -e sdk/python`
`pip show google-auth` should be `2.14.1`
**Checklist:**
follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

chore(sdk): continuation of bumping google-auth dependency

---

sdk/python/kfp/dsl/__init__.py

feat(sdk): add pipeline job placholders for scheduled runs

---

sdk/python/kfp/components/executor.py

Fixes a bug where an exception is thrown (non-deterministically) if multiple workers attempt to write to the same file using gcsfuse as the driver. This may or may not be a gcsfuse bug, but either way let's work around it for now in the KFP SDK.
**Checklist:**

fix(sdk): fix multiple workers writing with gcsfuse bug [KFP SDK v2]

---

sdk/python/kfp/components/placeholders.py
sdk/python/kfp/components/placeholders_test.py
sdk/python/kfp/components/structures.py
sdk/python/test_data/components/container_with_placeholder_in_fstring.py
sdk/python/test_data/components/container_with_placeholder_in_fstring.yaml
sdk/python/test_data/test_data_config.yaml

Enables use of primitive placeholders in f-string. ConcatPlaceholder and IfPresentPlaceholder still cannot be used in an f-string.
**Checklist:**

feat(sdk): enable use of primitive placeholders in f-string

---

sdk/python/kfp/client/client.py
test/presubmit-sdk-execution-tests.sh

Revert KFP SDK `client.py` changes from #8403.
**Checklist:**

fix(sdk): revert premature client changes

---

api/v2alpha1/pipeline_spec.proto
api/v2alpha1/python/setup.py

Adds is_list_of_artifact field to PipelineSpec to enable KFP SDK compiler to type check components that use lists of artifacts after they are loaded from IR YAML.
**Checklist:**

feat(sdk): add is_list_of_artifacts field to PipelineSpec [lists of artifacts support pt. 2]

---

backend/api/v1beta1/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_parameters.go
backend/api/v1beta1/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_version_parameters.go
backend/api/v1beta1/swagger/kfp_api_single_file.swagger.json
backend/api/v1beta1/swagger/pipeline.upload.swagger.json
backend/src/apiserver/server/pipeline_upload_server.go

This is the backend part pushed by https://github.com/kubeflow/pipelines/pull/8196. See the aforementioned PR and the linked issued for details.
This PR is part of the overarching idea to support namespaced pipeline definitions.
The whole idea is thoroughly analyzed and exposed in this design doc: https://docs.google.com/document/d/1fM4y2L1IVqVj-iiNjYFRRktdCh7FQXgU2XpaYLaqt-A/edit?resourcekey=0-kd5loyP7w3PBD0ug6ECmLQ#
Objective of this PR is to:
1. Fix backend authentication for upload requests in order to properly authenticate users to upload pipeline definitions in specific namespaces
2. Update the swagger definitions accordingly for the upload APIs and generate the code for the relevant clients
Part of #4197
**Checklist:**

feat(backend): Upload namespaced pipeline definitions. Part of #4197

---

sdk/python/kfp/client/client.py
sdk/python/kfp/client/client_test.py

Co-authored-by: droctothorpe <mythicalsunlight@gmail.com>
This PR (in response to[ this issue](https://github.com/kubeflow/pipelines/issues/8126)) implements small tests for various methods in `Client`, providing 51% coverage. This includes tests for `wait_for_run_completion`, `_is_ipython`, `get_experiment`, `create_experiment`, and `get_kfp_healthz`. Functions that just make pass through calls to the Python HTTP client have been avoided. 
We are very open to any feedback so let us know if there are any additional requirements. 
**Checklist:**

test(sdk): implement small tests for Client class

---

backend/src/apiserver/server/api_converter.go
backend/src/apiserver/server/api_converter_test.go

Fixes a potential error caused by #8480 with experiment storage status. Allows the API converter to convert V1 storage state into API types.
**Checklist:**

fix(backend): fixes a potential upgrade/downgrade error

---

sdk/python/kfp/components/base_component.py
sdk/python/kfp/components/base_component_test.py
sdk/python/kfp/components/pipeline_task.py

Fixes a KFP SDK v2 behavior that results in broken user code when using KFP SDK v2 with `google_cloud_pipeline_components`.
Specifically, this issue occurs when a component's `.pipeline_spec` method is accessed within a pipeline function. This happens if a user uses 
`create_custom_training_job_op_from_component` within the pipeline function body:
```python
@dsl.component
def print_op(input_text: str = 'test_input_text'):
print(input_text)
@dsl.pipeline
def pipeline_custom_job():
custom_job_print_op = create_custom_training_job_op_from_component(print_op)
custom_job_print_op(
input_text='test_text', project='managed-pipeline-test', display_name='custom_job_v1')
```
**Checklist:**
repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md# …

fix(sdk): fix bug when referencing component.pipeline_spec in a pipeline body

---

sdk/python/kfp/client/client.py

This PR fixes the print statement in the retry logic of `get_kfp_healthz` to properly specify `max_attempts` instead of `sleep_duration`.
**Checklist:**

fix(sdk): print max_attempts instead of sleep_duration

---

sdk/python/kfp/v2/components/executor.py
sdk/python/kfp/v2/components/executor_test.py

#8454 attempted to fix a `FileExistsError` thrown from within KFP SDK code that occurs when multiple workers are writing to the same file in a distributed training strategy.
The previous fix was a probabilistic fix that works most of the time, but not all of the time. This new fix should work all of the time when running pipelines on Vertex Pipelines.
**Checklist:**

fix(sdk): new fix for multiple workers writing with gcsfuse bug [KFP SDK v1]

---

sdk/RELEASE.md
sdk/python/kfp/components/executor.py
sdk/python/kfp/components/executor_test.py

#8455 attempted to fix a FileExistsError thrown from within KFP SDK code that occurs when multiple workers are writing to the same file in a distributed training strategy.
The previous fix was a probabilistic fix that works most of the time, but not all of the time. This new fix should work all of the time when running pipelines on Vertex Pipelines.
**Checklist:**

fix(sdk): new fix for multiple workers writing with gcsfuse bug [KFP SDK v2]

---

sdk/python/kfp/components/executor.py

Make the executor write `executor_output.json` for more possible chief worker node labels.
**Checklist:**

fix(sdk): make executor output writer more permissive [sdk v2]

---

sdk/python/kfp/v2/components/executor.py

Make the executor write `executor_output.json` for more possible 
chief worker node labels.
**Checklist:**

fix(sdk): make executor output writer more permissive [sdk v1]

---

sdk/RELEASE.md
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py
sdk/python/kfp/components/types/type_utils.py
sdk/python/kfp/components/types/type_utils_test.py

Fixes two errors related to handling of v1 component YAML defaults:
- Boolean types with defaults as strings (e.g., `"True"`/`"true"`/`"False"`/`"false"`) could be loaded in, but could not be compiled.
- Struct/Array types were loaded in, but not compiled correctly (compiled as a `google.protobuf.Value.string_value` instead of `google.protobuf.Value.struct_value` and `google.protobuf.Value.list_value`, respectively.
This PR fixes both and relocates all v1 component YAML default handling logic to the v1 component YAML deserialization code from v2 IR YAML compilation code.
**Checklist:**

fix(sdk): fix deserializing v1 component yaml defaults

---

backend/src/cache/main.go
manifests/kustomize/base/cache/cache-deployment.yaml

Previously the webhook listened on a fixed port, 8443, which can clash with other services when the webhook is run on the host network in Kubernetes, which is required when using some CNI implementations, notably Calico on EKS [1].
Enable configuration of the webhook listen port via the program flags.
[1] https://projectcalico.docs.tigera.io/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking
**Checklist:**

feat(backend): Make cache-server webhook port number configurable

---

backend/src/apiserver/filter/filter_test.go
backend/src/apiserver/list/list_test.go
backend/src/apiserver/model/job.go
backend/src/apiserver/model/run.go
backend/src/apiserver/server/list_request_util.go
backend/test/integration/job_api_test.go
backend/test/integration/run_api_test.go

Fixes #8654.
With this PR, users can now filter runs with `finished_at`; Additionally, users can filter recurring runs (f.k.a. jobs) using 	`updated_at` and `description`, similar to what we now have with runs.
**Checklist:**

feat(backend): add support for "finished_at" and others in filter. Fixes #8654

---

sdk/RELEASE.md
sdk/python/requirements.in

Fixes #8666.
Looking at the [change list of PyYAML 6.0](https://github.com/yaml/pyyaml/blob/6.0/CHANGES#L7-L18), I believe those changes have no impact to kfp SDK.
**Checklist:**

feat(sdk): Accepts higher PyYAML versions

---

api/v2alpha1/python/setup.py

Bumps `kfp-pipeline-spec` version to `0.2.0`. This is to resolve an error where (in the absence of this change) previous version of the KFP SDK might get "too new" a version of `kfp-pipeline-spec`, write the newer PipelineSpec (IR YAML), and submit to an "older" version of the KFP OSS BE which does not support the new IR YAML.
**Checklist:**

chore(sdk): bump kfp-pipeline-spec

---

sdk/python/requirements.in
sdk/python/requirements.txt

Pins [`kfp-pipeline-spec`](https://pypi.org/project/kfp-pipeline-spec/) to an exact version, since this is the contract between a given KFP SDK version and the BE. We don't want old version of the SDK to write new fields and to have the BE reject the new unsupported field (even if the new field backward compatible from a proto perspective).
Also see https://github.com/kubeflow/pipelines/pull/8744.
**Checklist:**

chore(sdk): pin kfp-pipeline-spec exactly

---

frontend/src/components/Router.tsx
frontend/src/components/__snapshots__/Router.test.tsx.snap
frontend/src/pages/NewRunV2.tsx
frontend/src/pages/PipelineDetails.test.tsx
frontend/src/pages/PipelineDetails.tsx
frontend/src/pages/RecurringRunDetails.test.tsx
frontend/src/pages/RecurringRunDetails.tsx
frontend/src/pages/RecurringRunList.tsx
frontend/src/pages/RecurringRunsManager.tsx
frontend/src/pages/RunList.tsx

Enable pipeline details logic to retrieve `template string` from pipeline manifest in recurring run and then using it to configure DAG in pipeline details page.
Before:
https://user-images.githubusercontent.com/56132941/213337299-b7570a94-0768-42b5-afd4-8827e6544956.mov
After:
https://user-images.githubusercontent.com/56132941/213337382-1d71f6fe-a40b-41b6-a337-a75f680b85c5.mov

fix(frontend): Show pipeline details for an existing recurring run without pipeline / pipeline version.

---

test/deploy-cluster.sh
test/frontend-integration-test/README.md
test/frontend-integration-test/helloworld.spec.js
test/frontend-integration-test/run_test.sh

The goal of this PR is to improve debugging experience for the frontend integration test.
1. Changes the flow of the FE e2e test. The test waits for 90 seconds before opening run details page to verify run's status.
1. Adds local debugging option that would be of a great value for those who face failed tests.
1. Uploads test artifacts to the GCS bucket (this was missing, although artifacts are created).
**Checklist:**

fix(test): Add frontend integration test manual run

---

sdk/RELEASE.md
sdk/python/kfp/client/client.py
sdk/python/kfp/client/client_test.py

This PR fixes a bug where pipelines submitted through the client using `upload_pipeline` that don't have a name passed to the method are not named correctly.
**Checklist:**

fix(sdk): fix upload_pipeline when no pipeline name is provided

---

frontend/src/pages/NewRun.test.tsx
frontend/src/pages/NewRun.tsx
frontend/src/pages/__snapshots__/NewRun.test.tsx.snap

The main purpose of this PR is disable users to choose pipeline version if they haven't selected pipeline. (Current UI logic will pop an error message)
Before:
https://user-images.githubusercontent.com/56132941/216479645-ec297c1c-e60b-4326-ac31-301a165e7d56.mov
After:
https://user-images.githubusercontent.com/56132941/216479678-69ed08e6-e6ac-44a3-aa31-4f4358770c69.mov

fix(frontend): Disable choosing pipeline version if pipeline is empty.

---

frontend/src/pages/NewPipelineVersion.tsx
frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap

Current UI incorrectly displays that pipeline description field is required 
Before:
After:

fix(frontend): Change the pipeline description field as optional.

---

backend/api/v1beta1/python_http_client/setup.py
test/sample-test/Dockerfile

`kfp` (sdk) from HEAD and `kfp-server-api` from HEAD may not always be compatible. This could happen anytime API changes, and SDK may not integrate with API changes at the same time. 
**Checklist:**

test: install compatible `kfp-server-api` and `kfp` packages

---

sdk/RELEASE.md
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/pipeline_task_test.py
sdk/python/test_data/pipelines/pipeline_with_resource_spec.py

Deprecates pipeline task `.set_gpu_limit` in favor of `.set_accelerator_limit`, since limits can be set for both GPUs and TPUs.
**Checklist:**

feat(sdk): deprecate .set_gpu_limit in favor of .set_accelerator_limit

---

frontend/src/components/NewRunParametersV2.test.tsx
frontend/src/components/NewRunParametersV2.tsx

Previously, KFP directly use proto type as error message of parameter field. The main purpose of this change is change the type in the text more readable, which aligns with MP's design.
The changes as follow:
```
NUMBER_INTEGER -> integer
NUMBER_DOUBLE -> double
BOOLEAN -> boolean
STRING -> string
LIST -> list
STRUCT -> map / dict
```
Before:
After:

fix(frontend): Change the prompt and error message of parameter field into more readable text

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/test_data/pipelines/pipeline_with_task_using_ignore_upstream_failure.py
sdk/python/test_data/pipelines/pipeline_with_task_using_ignore_upstream_failure.yaml
sdk/python/test_data/test_data_config.yaml

Introduces a new syntax for pipeline tasks to consume outputs from the upstream task while at the same time ignoring if the upstream tasks succeeds or not. Similar to an exit handler but with the included ability to parse inputs to the exit task.
sample syntax
```
@dsl.pipeline()
def my_pipeline(sample_input1: str = 'message'):
task = fail_op(message=sample_input1)
clean_up = print_op(message=task.output).ignore_upstream_failure()
```
**Checklist:**

feat(sdk): Ignore upstream failure

---

manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml

Updated the env variable from MINIO_NAMESPACE to NAMESPACE as in `backend/Dockerfile.viewercontroller`. This fixes an error that happens when you use a custom namespace instead of the default kubeflow, and the ml-pipeline-viewer-crd deployment goes into CrashLoopBackOff.
**Checklist:**

fix(deployment): fix custom namespace for viewer crd deployment. Fixes #7714

---

backend/src/apiserver/server/api_converter.go
backend/src/apiserver/server/api_converter_test.go

- Removed namespace validation when converting to v2 API pipeline message
**Checklist:**

fix(backend): Allow empty namespace in pipelines. Fixes #8840.

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/component_factory_test.py
sdk/python/kfp/components/container_component_artifact_channel_test.py
sdk/python/kfp/components/placeholders.py
sdk/python/kfp/components/placeholders_test.py
sdk/python/kfp/components/structures.py

Supports using lists of artifacts in Custom Container Components by enabling writing of placeholders of the form `"{{$.inputs.artifacts['input_name']}}"` via the following syntax:
```python
@dsl.container_component
def comp(input_list: Input[List[Artifact]]):
return dsl.ContainerSpec(image='alpine', command=['echo'], args=[input_list])
```
Also, write the [`isArtifactList` field](https://github.com/kubeflow/pipelines/blob/1e1a02066ac64cf6ac88d763f16d717219b52576/api/v2alpha1/pipeline_spec.proto#L181) all components types.
Creating output lists of artifacts is not yet supported, but will be supported by https://github.com/kubeflow/pipelines/pull/8808/. This change will also include type checking logic.
**Checklist:**
pull request title convention used in …

feat(sdk): support input list of artifacts in Custom Container Components [lists of artifacts support pt. 4]

---

frontend/server/app.ts
frontend/server/configs.ts

Currently, the frontend server can only proxy either v1 or v2 API request to backend. The main changes of this PR as follow:
1. Separate v1 and v2 API version and version prefix in `configs.ts`
2. Add additional logic in `app.ts` for proxying v2 API request.
https://user-images.githubusercontent.com/56132941/219529919-ebab5c3f-c982-4fb4-8361-9dc36299d9cf.mov

chore(frontend): Support v1 and v2 API request simultaneously in the frontend server

---

sdk/RELEASE.md
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/test_data/pipelines/pipeline_with_params_containing_format.yaml

fix(sdk): fix bug when passing data between tasks using f-strings

---

sdk/python/kfp/components/component_factory_test.py
sdk/python/kfp/components/types/type_annotations.py

Fixes a regression since `2.0.0b4` where use of `dsl.OutputPath('MyCustomType')` cannot be compiled. Same for `dsl.InputPath`. With this fix the input/output type is represented as a `system.Artifact`, consistent with the last working implementation.
**Checklist:**

fix(sdk): fix unknown artifact string in dsl.OutputPath/dsl.InputPath

---

sdk/RELEASE.md
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py
sdk/python/test_data/pipelines/pipeline_with_env.py
sdk/python/test_data/pipelines/pipeline_with_env.yaml

fix(sdk): Fix environment variable set in component yaml lost during compilation. Fixes #8884

---

sdk/RELEASE.md
sdk/python/kfp/components/executor.py

fix(sdk): fix attribute error for Containerized Python Components

---

manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
manifests/gcp_marketplace/test/snapshot-base.yaml
manifests/gcp_marketplace/test/snapshot-emissary.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml

Follow up on https://github.com/kubeflow/pipelines/pull/8553, the reduction in log expiration appears to be insufficient. Disable binlog as we don't really use it at this moment.
Part of https://github.com/kubeflow/manifests/issues/2402
Manually tested in my own cluster, verified that binlog is disabled after the change:
```shell
mysql> SHOW BINARY LOGS;
ERROR 1381 (HY000): You are not using binary logging
mysql> SHOW MASTER LOGS;
ERROR 1381 (HY000): You are not using binary logging
```
**Checklist:**

fix(manifests): disable mysql binlog

---

frontend/src/components/CustomTable.test.tsx
frontend/src/components/CustomTable.tsx
frontend/src/pages/ExperimentList.test.tsx
frontend/src/pages/ExperimentList.tsx

The main purpose of this PR is change the old filter in listExperiment() v2 API. Also, it can validate the frontend integration tests in https://github.com/kubeflow/pipelines/pull/8939

chore(frontend): Use v2 filter in listExperiment() v2 API

---

backend/src/apiserver/server/api_converter_test.go

The test was [flaky](https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/8978/kubeflow-pipeline-backend-test/1635359652906536960). 
Switch to use `cmp.Equal` per https://stackoverflow.com/a/45222521/20172751
**Checklist:**

test: Fix flaky test Test_toModelTasks_wf

---

sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/pipeline_task_test.py
sdk/python/test_data/pipelines/pipeline_with_resource_spec.py

Deprecates pipeline task `.add_node_selector_constraint` in favor of `.set_accelerator_type`, 
since accelerators can be set on multiple platforms.
**Checklist:**

feat(sdk): deprecate .add_node_selector_constraint in favor of .set_accelerator_type

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py

Allowing optional cput_limit and memory_limit. Since we have seen issue like this: https://screenshot.googleplex.com/3isooxvhLtdkjEv
**Checklist:**

fix(sdk): cpu_limit and memory_limit can be optional

---

kubernetes_platform/python/kfp/kubernetes/volume.py
kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.yaml
kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc.yaml
kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc_from_task_output.yaml
sdk/python/kfp/components/pipeline_channel.py
sdk/python/kfp/components/pipeline_channel_test.py

Fixes a bug where `kfp.kubernetes.mount_pvc` doesn't set task dependencies when `pvc_name` is produced by an upstream task.
**Checklist:**

fix: support setting task dependencies via kfp.kubernetes.mount_pvc

---

test/frontend-integration-test/Dockerfile
test/frontend-integration-test/selenium-standalone-chrome-gcloud-nodejs.Docker/Dockerfile

Suspect [the frontend-integration-test failure](https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/9024/kubeflow-pipeline-e2e-test/1638628723034951680) was due to using old version of node.
[@wdio/junit-reporter@8.6.6](https://www.npmjs.com/package/@wdio/junit-reporter/v/8.6.6) was released 2 days ago, likely explains why the test started failing [since March 20](https://oss.gprow.dev/job-history/gs/oss-prow/pr-logs/directory/kubeflow-pipeline-e2e-test?buildId=) without any related code change from our side.
Update node to v16, also update `standalone-chrome` to latest.
Logs from failed test:
```
integration-test-w7g2d-805499231: npm WARN notsup Unsupported engine for @wdio/junit-reporter@8.6.6: wanted: {"node":"^16.13 || >=18"} …
```

test: Update frontend-integration-test image

---

backend/src/apiserver/resource/resource_manager_util_test.go
backend/src/apiserver/server/api_util.go
backend/src/apiserver/server/job_server_test.go
backend/src/apiserver/server/run_server_test.go
backend/src/apiserver/storage/object_store.go
backend/src/apiserver/template/argo_template.go
backend/src/apiserver/template/template.go
backend/src/apiserver/template/template_test.go
backend/src/apiserver/template/v2_template.go
backend/src/common/client/api_server/run_client.go
backend/src/common/client/api_server/util.go
backend/src/common/util/execution_spec.go
backend/src/common/util/execution_spec_test.go
backend/src/common/util/workflow.go
backend/src/common/util/workflow_test.go
backend/src/v2/cmd/compiler/main.go
backend/src/v2/compiler/argocompiler/argo_test.go
backend/third_party_licenses/apiserver.csv
backend/third_party_licenses/cache_server.csv
backend/third_party_licenses/persistence_agent.csv
backend/third_party_licenses/swf.csv
go.mod
go.sum

The package `github.com/ghodss/yaml` is no longer actively maintained. See discussion in https://github.com/ghodss/yaml/issues/75 and https://github.com/ghodss/yaml/issues/80. [`sigs.k8s.io/yaml`](https://github.com/kubernetes-sigs/yaml) is a permanent fork of `github.com/ghodss/yaml`. It is actively maintained by Kubernetes SIG, and also widely used in K8s projects.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.
**Checklist:**

chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

---

sdk/python/kfp/client/client.py

Currently, `create_run_from_pipeline_func` and `create_run_from_pipeline_package` accept an `experiment_name` parameter and lookup the experiment ID with a backend call via `create_experiment`.
This tiny PR lets users pass the experiment ID directly as an optional alternative, circumventing the extra call, and improving alignment between these methods and `create_recurring_run`.
It also decouples the experiment handling logic from the run name handling logic. They were interleaved previously. 
**Checklist:**

feat(sdk): add experiment_id parameter to create run methods

---

sdk/RELEASE.md
sdk/python/kfp/components/structures.py
sdk/python/kfp/components/structures_test.py
sdk/python/kfp/components/types/type_utils.py

Fixes a bug where non-canonical representations of v1 component YAML 
generic types were loaded as artifacts. These types include:  
`List[str]`, `typing.List[str]`, `Dict[str]`, `typing.Dict[str, str]`
**Checklist:**

fix(sdk): fix loading non-canonical type strings from v1 component YAML

---

sdk/python/kfp/__init__.py
sdk/python/kfp/compiler/compiler_test.py

Users should be able to decorate a pipeline via:
```python
@kfp.dsl.pipeline
def p():
...
```
Because they can do:
```python
@kfp.v2.dsl.pipeline
def p():
...
```
Currently, `kfp.dsl.pipeline` throws an exception. This PR fixes this.
**Checklist:**

fix(sdk): support accessing `.dsl` attribute on `kfp` module object

---

components/aws/sagemaker/tests/integration_tests/Dockerfile

See this error when installing argo. Updating other packages to latest stable versions in Docker file.
```
Step 8/23 : RUN curl -sSL -o /usr/local/bin/argo https://github.com/argoproj/argo-workflows/releases/download/v2.8.0/argo-linux-amd64  && chmod +x /usr/local/bin/argo
--
595 | ---> Running in 7a4483923c1d
596 | curl: (60) SSL certificate problem: certificate has expired
597 | More details here: https://curl.haxx.se/docs/sslcerts.html
598 |  
599 | curl failed to verify the legitimacy of the server and therefore could not
600 | establish a secure connection to it. To learn more about this situation and
601 | how to fix it, please visit the web page mentioned above.
602 | The command '/bin/sh -c curl -sSL -o /usr/local/bin/argo …
```

test(Component): update argo-workflow version

---

frontend/src/apisv2beta1/filter/api.ts
frontend/src/apisv2beta1/pipeline/api.ts

Backend add the missing parameters `body` in createPipelineVersion. Frontend then need to regenerate new TS client.

chore(frontend): Regenerate TS client for backend changes on createPipelineVersion

---

backend/src/v2/compiler/argocompiler/dag.go

Since #9059, the backend test has been rather flaky. After some investigation, it turned out that the tasks inside the root dag had a random order, and an added unit test in #9059 exposed this issue. This PR fixed the issue by ordering the tasks alphabetically.
**Checklist:**

test(backend): fix flaky backend test

---

backend/src/apiserver/server/api_converter.go

Caused flakiness in the backend test  in #9075 due to random order of the keys in the underlying `map[string]`
Similar to #9079.
**Checklist:**

chore(backend): fix flakiness in toModelTasks function

---

frontend/src/pages/NewRunSwitcher.tsx
frontend/src/pages/NewRunV2.test.tsx
frontend/src/pages/NewRunV2.tsx
frontend/src/pages/PipelineDetails.test.tsx
frontend/src/pages/PipelineDetails.tsx
frontend/src/pages/RecurringRunDetailsRouter.tsx
frontend/src/pages/RecurringRunDetailsV2.test.tsx
frontend/src/pages/RunDetailsRouter.tsx
frontend/src/pages/RunList.test.tsx
frontend/src/pages/RunList.tsx

In the latest backend changes, `pipeline_id` is also added in the return value of run and recurring run. In addition, `pipeline_id` and `pipeline_version_id` are wrapped as `pipeline_version_reference`. The main purpose of this PR is modifying frontend implementation to match the changes.

chore(frontend): Change pipeline_version_id field in run / recurring run

---

sdk/RELEASE.md
sdk/python/kfp/components/placeholders.py
sdk/python/kfp/components/placeholders_test.py

Container Components may now pass top-level artifact metadata fields directly to container commands/args, eliminating the need to parse the metadata struct in the container logic. For example, `echo` obtains the `'value'` string directly via `artifact.metadata['key']`:
```python
from kfp.dsl import Dataset, Input
@dsl.container_component
def echo(artifact: Input[Dataset]):
return dsl.ContainerSpec(
image='alpine', command=['echo', artifact.metadata['key']])
@dsl.pipeline
imp = dsl.importer(
artifact_uri='gs://ml-pipeline-playground/shakespeare1.txt',
artifact_class=Dataset,
reimport=False,
metadata={'key': 'value'})
echo(artifact=imp.output)
```
**Checklist:**
title convention. [Learn more about the pull request title …

feat(sdk): support direct indexing into top-level of artifact metadata struct in Container Components

---

sdk/python/kfp/cli/experiment.py
sdk/python/kfp/cli/output.py
sdk/python/kfp/cli/pipeline.py
sdk/python/kfp/cli/recurring_run.py
sdk/python/kfp/cli/run.py
sdk/python/kfp/client/client.py
sdk/python/kfp/client/client_test.py
sdk/python/requirements.in
sdk/python/requirements.txt

Migrate SDK client to use v2beta1 API.
Manually tested all public method with most commonly used arguments.
**Checklist:**

feat(SDK)!: SDK client v2beta1 API integration. Fixes #8706

---

docs/conf.py
sdk/RELEASE.md
sdk/python/kfp/__init__.py
sdk/python/kfp/client/client.py

chore: release SDK 2.0.0b14

---

sdk/RELEASE.md
sdk/python/kfp/cli/component_test.py
sdk/python/kfp/components/utils.py

Prepends the `module_directory` to sys.path. `module_directory` is [WindowsPath](https://docs.python.org/3/library/pathlib.html#pathlib.WindowsPath) object on windows, hence casting to string as sys.path doesn't support pathlib objects.
**Checklist:**

fix(sdk): fixes module not found error for containerized python components. Fixes #8385

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/components/component_factory.py
sdk/python/kfp/components/graph_component.py
sdk/python/kfp/components/pipeline_context.py
sdk/python/test_data/pipelines/pipeline_with_nested_conditions_yaml.py
sdk/python/test_data/pipelines/pipeline_with_nested_conditions_yaml.yaml
sdk/python/test_data/pipelines/pipeline_with_ontology.yaml
sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml

The `@dsl.pipeline` decorator now accepts `display_name` and `description` arguments. These are compiled to IR YAML.
```python
@dsl.pipeline(
display_name='Human readable name',
description='My description. Decorator argument takes precedence over docstring',
)
"""Will use docstring description when decorator description is not provided.
In this case, description is provided to decorator is docstring is unused.
"""
...
```
**Checklist:**

 feat(sdk): support `display_name` and `description` in `@dsl.pipeline` decorator

---

backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
samples/test/config.yaml
samples/v2/pipeline_with_secret_as_env.py
samples/v2/pipeline_with_secret_as_env_test.py
samples/v2/pipeline_with_secret_as_volume.py
samples/v2/pipeline_with_secret_as_volume_test.py

* Supports using secrets in two ways: as a mounted volume, or as an environment variable
* Adds one sample test for each way
Tests done:
* Manually tested reading the value of a secret mounted as volume
* Manually tested accessing the value of a secret as an environment variable
Note:
For the sample test, we use an existing secret existing in the cluster, rather than creating a new one.
**Checklist:**

feat(backend): support secrets

---

sdk/python/kfp/client/client.py

The method should work with either providing `pipeline_package_path` or providing both `pipeline_id` and `version_id`.
Before the fix, if one provides `pipeline_id` and `version_id`, it causes the below error:
```
client.run_pipeline(
File "/usr/local/google/home/chesu/git/pipelines/sdk/python/kfp/client/client.py", line 727, in run_pipeline
job_config = self._create_job_config(
File "/usr/local/google/home/chesu/git/pipelines/sdk/python/kfp/client/client.py", line 979, in _create_job_config
pipeline_spec=pipeline_doc.to_dict(),
AttributeError: 'NoneType' object has no attribute 'to_dict'
```
Manually tested.
**Checklist:**

fix(SDK): fix `client.run_pipeline` with `pipeline_id` and `version_id` gives error

---

frontend/src/pages/NewRunV2.test.tsx
frontend/src/pages/NewRunV2.tsx

After the concept of `default_version` is removed in v2 API, listPipelineVersions() need to be called after pipeline is selected to retrieve the latest pipeline version.
Pipeline with parameter:
https://user-images.githubusercontent.com/56132941/233697396-0d1aff73-1954-4d2c-8fdc-3ecef900f8e1.mov
Parameter field is missing:
https://user-images.githubusercontent.com/56132941/233697731-286df3c8-43ab-4bad-9301-a95001795b56.mov
After this PR:
https://user-images.githubusercontent.com/56132941/233698044-ca7be78d-a77a-4465-aec1-77cebf09a71a.mov

fix(frontend): Parameter field is missing after choosing another v2 pipeline

---

sdk/python/kfp/cli/component.py
sdk/python/kfp/cli/component_test.py

Add the `--platform` option to `kfp component build` to choose container build architecture. Fixes #8883 
**Checklist:**

fix(sdk): allow user to choose platform for component container build. Fixes #8883

---

frontend/src/pages/NewRunV2.tsx

In the new run page, we allow user to change experiment selection. With the updated experiment, search string in URL is changed as well. Previously, the scenario of cloning recurring run is not handled, which lead to the missing pipeline information issue after changing experiment.
Before:
https://user-images.githubusercontent.com/56132941/234348697-7d5a2d46-ca27-4450-8959-7b8c10c89c24.mov
After:
https://user-images.githubusercontent.com/56132941/234348765-b6b22b63-c3e3-49f6-8c54-ebda24b4113d.mov

fix(frontend): Missing pipeline info while cloning recurring run.

---

frontend/src/pages/NewRunSwitcher.tsx
frontend/src/pages/NewRunV2.test.tsx

This is a regression bug caused by https://github.com/kubeflow/pipelines/pull/9123. Main reason is the incorrect in-line expression used to determine template string. This PR fixes the logic and add short comment to describe the source of template string and specify the priority!

fix(frontend): fail to clone SDK-created run / recurring run

---

frontend/src/lib/v2/WorkflowUtils.ts

Previously, we directly use the return value from safeLoad(), which is PipelineSpec, to draw the graph. However, after the concept `platform_spec` is introduced, the return value from safeLoad() will become a nested structure, and the PipelineSpec we use to draw graph is stored in `pipeline_spec` field.

fix(frontend): Render graph for yaml file containing platform_spec

---

frontend/src/components/tabs/RuntimeNodeDetailsV2.test.tsx
frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
frontend/src/pages/RunDetailsV2.tsx

Successfully get logs:
1. Run is succeeded
2. Run is succeeded from cached execution
3. Run is failed 
Fail to get logs:

feature(frontend) Support Logs tab in KFP v2

---

backend/src/apiserver/server/api_converter.go
backend/src/apiserver/server/api_converter_test.go
backend/src/apiserver/server/report_server.go
backend/src/common/util/execution_status.go
backend/src/common/util/workflow.go

Limit the direct Workflow data struct access to `common.util` and use `ExecutionSpec` and `ExecutionStatus` in other places. Create a data struct to represent the node status information in ExecutionStatus and add an API to access this information.
**Checklist:**

feat(backend): avoid downcast and use ExecutionSpec if possible

---

frontend/src/lib/Apis.ts
frontend/src/pages/NewPipelineVersion.test.tsx
frontend/src/pages/NewPipelineVersion.tsx

Before:
https://user-images.githubusercontent.com/56132941/236584340-3b9dd663-490c-4460-839a-36383286b213.mov
After:
https://user-images.githubusercontent.com/56132941/236584359-60af7471-3d37-4739-9d93-a6dcebc15821.mov

fix(frontend): Failed pipeline version creation should not generate an empty pipeline.

---

backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/template/template.go
backend/src/apiserver/template/v2_template.go

Thanks to @chensun who found that when creating a job without the required parameters, the backend returns a 500 error (internal server error), instead of an invalid input error. 
Error message:
This PR changes the error code/type. Also changes some other error messages so they are of the right type and more clear. 
Verified manually that the error messages are correct.
**Checklist:**

fix(backend): change format of some backend error message

---

backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/server/run_server.go
backend/src/apiserver/storage/run_store.go
backend/src/apiserver/storage/run_store_test.go

- Removed `experimentId` from some of the functions in run server
- Removed redundant calls to DB, which should improve performance
**Checklist:**

chore(backend): Remove deprecated experiment id from run server's endpoints

---

frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
frontend/src/components/tabs/StaticNodeDetailsV2.test.tsx
frontend/src/components/tabs/StaticNodeDetailsV2.tsx

Currently, we use `Open workflow` on the button for expanding Sub-DAG. The term `Workflow` is a little confusing, so we change to `Open Sub-DAG`.
Before:
After:

fix(frontend): Rename button in pipeline/run details side panel

---

frontend/src/pages/RunDetailsV2.tsx

(Correct) Run is not finished:
Before fix:
After fix:

fix(frontend): No values in "Finished at" & "Duration" when run is finished

---

frontend/src/pages/NewExperiment.tsx
frontend/src/pages/NewPipelineVersion.tsx
frontend/src/pages/NewRun.tsx
frontend/src/pages/NewRunV2.tsx
frontend/src/pages/__snapshots__/NewExperiment.test.tsx.snap
frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap
frontend/src/pages/__snapshots__/NewRun.test.tsx.snap

We already use asterisk to indicate required field, so `(optional)` can be removed.
Before:
After:

fix(frontend): Remove redundant "(optional)" text in the optional input fields.

---

frontend/src/components/ExperimentList.tsx
frontend/src/components/__snapshots__/ExperimentList.test.tsx.snap

fix(frontend): Change the empty message of archived experiment list.

---

frontend/src/lib/Buttons.ts
frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap

Before
https://github.com/kubeflow/pipelines/assets/56132941/ab418e89-3f88-4f4a-87e2-1576f72ddfb4
After
https://github.com/kubeflow/pipelines/assets/56132941/314f112c-6f43-457b-b169-7a1870cad354

fix(frontend): Make the hover text for "Archive" button more informative

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/test_data/pipelines/pipeline_as_exit_task.yaml
sdk/python/test_data/pipelines/pipeline_with_task_final_status.yaml
sdk/python/test_data/pipelines/pipeline_with_task_final_status_yaml.yaml

Merge after [kfp-pipeline-spec](https://pypi.org/project/kfp-pipeline-spec/) 0.2.2 is released and the field is supported by at least one pipeline execution backend.
**Checklist:**

feat(sdk): support writing `TASK_FINAL_STATUS` parameter type

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py

Fix compilation of boolean constant passed to component.
Previously, compiling a pipeline like the one below would result in the boolean cast to an int. This is 
resolved.
```python
@dsl.pipeline
my_comp(boolean=True)
```
**Checklist:**

fix(sdk): fix compilation of boolean constant passed to component

---

sdk/python/kfp/client/client.py

close #9406 
The sdk client `wait_for_run_completion` has to sleep for at least one iteration no matter state of the run. Optimize the function to check the state right after and return the run response if ready.
**Checklist:**

fix(sdk): Optimize wait_for_run_completion sdk function to skip an extra wait

---

frontend/src/components/Router.tsx
frontend/src/pages/ExecutionList.test.tsx
frontend/src/pages/ExecutionList.tsx
frontend/src/pages/ExecutionListRouter.tsx
frontend/src/pages/ExecutionListSwitcher.tsx
frontend/src/pages/ExecutionListSwticher.test.tsx

We supported `Flat` view and pagination feature for the execution list in our last rc release. However, we hope that the original `Group` view can be preserved as well. The main purpose of this PR is adding a little tab on the top of execution list for users to switch between both views.
[Demo]
https://github.com/kubeflow/pipelines/assets/56132941/c57d97c9-855d-40d5-9489-19e58ea4c205

feature(frontent): Support both "Flat" and "Group" view for Execution list

---

frontend/server/app.ts
frontend/server/configs.ts
frontend/server/handlers/pod-logs.ts
frontend/server/k8s-helper.ts
frontend/server/workflow-helper.test.ts
frontend/server/workflow-helper.ts

Add an UIConfig param to specify the container name in a pod where logs are retrieved. The default container name for the Argo is `main`. However, in Tekton, the main container name contains the `step-` prefix. Make this configurable to support other orchestrations.
**Checklist:**

feat(frontend): make container name configurable

---

frontend/src/pages/PipelineDetails.tsx

The pipeline version name in page title should be changed as well after switching to another pipeline version.
Before:
https://github.com/kubeflow/pipelines/assets/56132941/ec699e27-d07e-41f1-9a55-e9c2347d7432
After:
https://github.com/kubeflow/pipelines/assets/56132941/2df6f260-3ea0-4374-86fe-cfcf672055a3

fix(frontend): Incorrect page title after switching to another pipeline version.

---

sdk/RELEASE.md
sdk/python/kfp/components/executor.py
sdk/python/kfp/components/executor_test.py

FIx. `ValueError: Function XXX returned value of type <class 'int'>; want type <class 'float'>`
Fixes: https://github.com/kubeflow/pipelines/issues/9442
**Checklist:**

fix(sdk): relax executor type checking

---

backend/src/apiserver/template/template.go
backend/src/apiserver/template/template_test.go
backend/src/apiserver/template/testdata/hello_world.yaml
backend/src/apiserver/template/v2_template.go
backend/src/v2/metadata/client.go
backend/third_party_licenses/apiserver.csv
backend/third_party_licenses/cache_server.csv
backend/third_party_licenses/persistence_agent.csv
backend/third_party_licenses/swf.csv
backend/third_party_licenses/viewer.csv
go.mod
go.sum

Upgrade to `gopkg.in/yaml.v3` to avoid converting string "y" to boolean "true".
Fixes #9451
**Checklist:**

fix(backend): upgrade to `gopkg.in/yaml.v3` to fix boolean support. Fixes #9451

---

frontend/src/pages/NewRun.tsx

Before:
https://github.com/kubeflow/pipelines/assets/56132941/d29145ba-04e4-4645-be8b-bb4c862914a5
After:
https://github.com/kubeflow/pipelines/assets/56132941/81ecdd19-1aab-437d-a050-a7fb9d72a044

fix(frontend): Run name should be empty if no pipeline is selected

---

frontend/src/pages/NewPipelineVersion.test.tsx
frontend/src/pages/NewPipelineVersion.tsx

Based on #9449
Previously, we don't support run name, which is partly from pipeline name, with non-English characters and special characters. A name precheck for pipeline display name (user-typed input) is set to avoid invalid name.
Currently, there's no limitation for run name any more. The precheck for pipeline name can be eliminated as well.
Both of run and pipeline can accept any characters

feature(frontend): Support non-English characters and special characters in pipeline "display" name

---

frontend/src/pages/PipelineDetails.test.tsx
frontend/src/pages/PipelineDetails.tsx

We have 2 possible source for pipeline details (from version and from run). For the details from run (clone existing run or SDK-created run), action should be `Clone run` rather `Create run`. Also, we shouldn't allow `Upload version` in this case, because pipeline is not existed.
Pipeline details from version:
https://github.com/kubeflow/pipelines/assets/56132941/94ca9ab1-1617-4d82-8eb9-69da9c801538
Pipeline details from run (SDK-created run)
https://github.com/kubeflow/pipelines/assets/56132941/0133fa5e-a609-48ef-acb7-a121081a0a4f
Pipeline details from run (clone existing run)
https://github.com/kubeflow/pipelines/assets/56132941/c780a086-6a52-4687-8022-014585924e47
Pipeline details from run (after fix)
https://github.com/kubeflow/pipelines/assets/56132941/118341c2-0cad-4736-84ab-a99cdf28 …

fix(frontend): Toolbar in pipeline details (from run) should only have "Clone run" button

---

frontend/src/pages/NewRun.test.tsx
frontend/src/pages/NewRun.tsx

The enable / disable logic of choose button in pipeline version box was changed in #8831 , and cause the bug.
Before:
https://github.com/kubeflow/pipelines/assets/56132941/5aae95ef-e96f-47b3-984b-1308f43d9e96
After:
https://github.com/kubeflow/pipelines/assets/56132941/608cdf2f-2f1c-4906-8bce-f1f1fe8cd3f9

fix(frontend): Choose button is disable even if pipeline is already selected (after uploading a new pipeline)

---

frontend/src/components/PipelineSpecTabContent.tsx
frontend/src/pages/PipelineDetailsV1.tsx

fix(frontend): Make pipeline definition in YAML tab more readable

---

frontend/src/components/ArtifactPreview.test.tsx
frontend/src/components/ArtifactPreview.tsx
frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx

This issue is because of the uncaught error (from parseStoragePath() helper) in ArtifactPreview.
Also, instead of displaying error banner for unsupported artifact URI, we decide to directly render it.
Before:
https://github.com/kubeflow/pipelines/assets/56132941/1d370f5f-6e69-4d3c-90fb-9bc689bb51ce
After:
https://github.com/kubeflow/pipelines/assets/56132941/a0730837-4df5-445e-bd38-cca0a56b2179

fix(frontend): Unexpected page crash when clicking artifact node.

---

backend/src/v2/objectstore/object_store.go

Use the aws-go-sdk credentials.ChainProvider to support IRSA in kfp v2. This functionality is already supported in V1, this pr aims to keep parity with v1 as IRSA is supported in v1 backend https://github.com/kubeflow/pipelines/blob/f167e15c3ca9b2120f8bb2283b0f3974439fef2f/backend/src/apiserver/client/minio.go#L30 Similar work was done for V1 frontend here https://github.com/kubeflow/pipelines/pull/8651. The goal is to maintain IRSA support in Kubeflow Pipelines as V2 goes GA following the effort to support S3 Integration for Artifact Storage (IRSA) in this issue https://github.com/kubeflow/pipelines/issues/8502.
**Checklist:**

feat(backend): Implement aws-go-sdk crendentials to support IRSA for s3 in V2

---

backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/component/launcher_v2.go

@jlyaoyuli found that when a task fails, the launcher does not publish the execution, leading the status of the task to remain `running`.  This PR fixes that by moving the publish function into a defer function, so it is always carried out, even if the task fails.
Manually tested that failed status is reported.
Note:
Need to build and update launcher image once the PR is approved. 
**Checklist:**

fix(backend): publish launcher execution even if it fails

---

sdk/RELEASE.md
sdk/python/requirements.in
sdk/python/setup.py

Part of #9543 
Loosen python kubernetes version requirement. This PR is for v1 SDK.
**Checklist:**

chore(sdk): loosen python kubernetes version requirement for v1

---

sdk/RELEASE.md
sdk/python/requirements.in

Part of https://github.com/kubeflow/pipelines/issues/9543
Loosen python kubernetes version requirement. This PR is for v2 SDK.
**Checklist:**

chore(sdk): loosen python kubernetes version requirement

---

backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go

replaces #9414
During the discussion I found that we do not support cache for createpvc/deletepvc. This PR
* adds cache for createpvc/deletepvc
* include pvc name in the cache fingerprint, if the pvc is includes a UUID 
Manually tested that cache is enabled with createpvc/deletepvc.
**Checklist:**

fix(backend): enable cache for create/delete PVC

---

frontend/src/components/NewRunParametersV2.tsx
frontend/src/pages/NewRunV2.test.tsx
frontend/src/pages/NewRunV2.tsx

Before:
https://github.com/kubeflow/pipelines/assets/56132941/d37e820f-3436-4116-a42c-938c2e84d7a1
After:
https://github.com/kubeflow/pipelines/assets/56132941/d60d0f10-9c11-4e3a-bd8a-12ca9dfa36af

fix(frontend): Pipeline Root is not used when provided during New Run creation

---

frontend/src/pages/PipelineDetails.test.tsx
frontend/src/pages/PipelineDetails.tsx

For the case that API call returns error, the page text should be **"No graph to show"** rather than **"Currently loading pipeline information"**.
For example, an empty pipeline will get error from getPipelineVersion() call.
Before:
https://github.com/kubeflow/pipelines/assets/56132941/b1e0a9b5-b89a-4ecd-b9f3-af2f9001395e
After:
https://github.com/kubeflow/pipelines/assets/56132941/d1d3c4e4-2e63-4630-8189-d0c13d30e680

fix(frontend): Incorrect page text for empty pipeline.

---

frontend/src/pages/NewRun.test.tsx
frontend/src/pages/NewRun.tsx
frontend/src/pages/__snapshots__/NewRun.test.tsx.snap

Error text should be **"A pipeline must be selected"** when no pipeline is selected.
Before:
After:

fix(frontend): Mismatched error text in new run page

---

frontend/src/pages/PipelineDetails.tsx

In the pipeline details page, users can switch between different versions; however, pipeline version is not updated after clicking `Create run` button.
Before:
https://github.com/kubeflow/pipelines/assets/56132941/72285dc8-6d2a-429e-83a8-77fa73727c87
After:
https://github.com/kubeflow/pipelines/assets/56132941/f575cf0a-ace0-4eb1-8802-7c2032e895e0

fix(frontend): Pipeline version is not updated in new run page

---

frontend/src/pages/NewRun.test.tsx
frontend/src/pages/NewRun.tsx

Before:
https://github.com/kubeflow/pipelines/assets/56132941/1289ee8a-f1e9-46d7-883c-538efed6a45c
After:
https://github.com/kubeflow/pipelines/assets/56132941/e7cc34b4-cad3-4042-8c40-1a17777b47f4

fix(frontend): Choose version button is greyed out after closing pipeline selector

---

frontend/src/pages/NewRunV2.test.tsx
frontend/src/pages/NewRunV2.tsx

Before:
https://github.com/kubeflow/pipelines/assets/56132941/b317e7a3-02de-4b8b-91c7-ce1dfbd95c60
After:
https://github.com/kubeflow/pipelines/assets/56132941/b5f35ba1-efb5-4719-a948-d58258730972

fix(frontend): Choose version button should be disabled if no pipeline is selected

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py
sdk/python/kfp/components/pipeline_task.py
sdk/python/kfp/components/types/type_annotations.py

Fixes a bug where a nested ParallelFor loop could not iterate over an output created in a shallower ParallelFor loop. For example, the following previously threw an `InvalidTopologyException`, but now does not:
```python
from typing import List
@dsl.component
def str_to_list(string: str) -> List:
return [string]
@dsl.component
def identity(string: str) -> str:
return string
@dsl.pipeline
with dsl.ParallelFor(['a', 'b', 'c']) as itema:
t1 = str_to_list(string=itema)
with dsl.ParallelFor(t1.output) as itemb:
identity(string=itemb)
```
**Checklist:**

fix(sdk): fix bug when iterating over output from upstream task in nested parallelfor loops

---

frontend/src/pages/NewRunSwitcher.tsx
frontend/src/pages/NewRunV2.test.tsx

When the user enter the new run page from experiment details page, it means that the experiment is selected. The text field of experiment name should be automatically filled.
Before:
https://github.com/kubeflow/pipelines/assets/56132941/5c087a45-579a-46b0-aa39-1758c8403448
After:
https://github.com/kubeflow/pipelines/assets/56132941/e4a56290-f79f-4d72-bdd0-b9ab943bbccd

fix(frontend): Display experiment name if experiment is selected

---

sdk/python/kfp/cli/component.py

Without this commit, `kfp component build` doesn't print any error messages that docker emits, e.g. if docker push fails.
Docker 20.10.21
kfp 2.0.0-rc.1
Just implement the example for a containerized python component from [the kubeflow docs](https://www.kubeflow.org/docs/components/pipelines/v2/components/containerized-python-components/#3-build-the-component).
If you now try to build and push the component image as described in the docs using: `kfp component build src/ --component-filepattern my_component.py` with an invalid target_image string, you will see an error message in the logs. Without this PR, you'd just get "Built and pushed component container <image name>", which isn't the case.

fix(sdk): print docker error messages

---

sdk/python/kfp/client/client.py
sdk/python/kfp/client/client_test.py

The name is used display name and doesn't carry special requirements. UI has removed the validation already. Removing it from SDK client side as well.
**Checklist:**

chore(sdk): relax name validation when upload pipeline

---

backend/src/v2/metadata/client.go
backend/src/v2/metadata/client_test.go

Related: #9586 
MLMD will complain for primary key (parent context id + child context id) conflict if PutParentContexts() is called multiple times. The fix is to check this relationship exists before calling PutParentContexts(). If this relationship already exists, we should not return error. 
**Checklist:**

fix(backend): Avoid multiple PutParentContexts on the same primary key.

---

frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx

Fixing #9593
Replacing `.split('\n')` with `.split(/[\r\n]+/)` to ensure lines are properly split. 
After fixing the split argument:

fix(frontend): Splitting logsDetails into lines based on CR and LF. Fixes #9593

---

test/deploy-cluster.sh

Fixes https://github.com/kubeflow/pipelines/issues/9704
Temporarily switch to GKE stable release channel to unblock presubmit tests. This should buy us some time (~3 months) until we find alternatives to building test images (#9706).
**Checklist:**

test: Use GKE stable release channel to unblock presubmit tests. Fixes #9704. Part of #9706.

---

frontend/src/pages/ExperimentDetails.tsx
frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap

fix(frontend): Recurring run card in experiment details page

---

backend/src/apiserver/storage/db.go
backend/src/apiserver/storage/db_test.go
backend/src/apiserver/storage/experiment_store.go

One of the requests used for Archiving Experiments is rewritten to use inner join for better performance, instead of using nested select. The fix leverage 'SQLDialect' interface, because the new Mysql request is not supported by SQLite Dialect (used for testing). 
There are other MySQL requests that use nested requests in Archive Experiment, but only the most problematic one reported by this [comment](https://github.com/kubeflow/pipelines/issues/6815#issuecomment-955935043) (bobgy) is fixed in the PR. 
The other requests are not optimized, as the `resource_reference` table will be deprecated soon - once `v2beta1` is available. 
Issue: https://github.com/kubeflow/pipelines/issues/6845
**Note**: Archive experiments need to be enabled back in test infra. The change done in this …

fix(backend): Fix performance issue within a mysql request

---

manifests/kustomize/third-party/postgresql/README.md
manifests/kustomize/third-party/postgresql/base/kustomization.yaml
manifests/kustomize/third-party/postgresql/base/pg-deployment.yaml
manifests/kustomize/third-party/postgresql/base/pg-pvc.yaml
manifests/kustomize/third-party/postgresql/base/pg-secret.yaml
manifests/kustomize/third-party/postgresql/base/pg-service.yaml
manifests/kustomize/third-party/postgresql/base/pg-serviceaccount.yaml

This is a default deployment yaml folder for a postgresql database. There are two deployment approaches in KFP: standalone and full Kubeflow. This folder can be used for full kubeflow, and can serve as an example for standalone manifest as well.
Related: #7512
**Checklist:**

feat(manifests): Add a postgresql deployment manifest in third-party folder

---

components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_hosting.py
components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_monitoring_job_definition_component.py
components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_monitoring_schedule_component.py
components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py
components/aws/sagemaker/tests/integration_tests/utils/ack_utils.py

- In the past, `k8s_client` is created before the pipeline run, and passed in `_get_resource(k8s_client, job_name, plural)`. This  could cause 401 unauthorized error when `_get_resource` and `_delete_resource`.
- This PR refactors the following methods, which will create a new k8s client during each call:
- `def _get_resource(k8s_client, job_name, plural)` to `def _get_resource(job_name, plural)`
- `def _delete_resource(k8s_client, job_name, plural, wait_periods=10, period_length=20):` to `def _delete_resource(job_name, plural, wait_periods=10, period_length=20)`
**Checklist:**

test(components): fix k8s_client 401 unauthorized error

---

frontend/src/pages/PipelineDetails.test.tsx
frontend/src/pages/PipelineDetails.tsx

Part of #9731 
Previously, we update the URL with `pipelineVersionId` obtained in getSelectedVersion(), and it will cause to re-render the page, which brings out several redundant API calls. The PR is removing the URL update logic to avoid those calls. Also, the getPipelineVersion() in _getTemplateString() is not necessary either, so it's removed as well.

chore(frontend): Avoid redundant v2 API call in PipelineDetails.

---

frontend/src/pages/PipelineDetails.test.tsx
frontend/src/pages/PipelineDetails.tsx

Before:
https://github.com/kubeflow/pipelines/assets/56132941/55c99d6e-4d9a-4cf4-8a83-5468dfe50b3d
After:
https://github.com/kubeflow/pipelines/assets/56132941/5d67a453-40cb-4408-9aef-592231abd8bb

fix(frontend): Missing pipeline version name in new run page.

---

sdk/python/kfp-dsl/kfp/dsl/executor.py
sdk/python/kfp-dsl/kfp/dsl/types/artifact_types.py
sdk/python/kfp-dsl/runtime_tests/executor_test.py

Cleans up some outdated and unnecessary artifact code in the KFP SDK. Specifically:
- Removes a note about v2 pipelines. Since this applies throughout the entire KFP SDK, its inclusion in `artifact_types.py` suggests there's something special about this file.
- remove superfluous `super().__init__` calls in `artifact_types.py`
- removes logic and tests for handling `google`-namespaced artifact types that has never been used and will never be used by the GCPC SDK.
**Checklist:**
should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

chore(sdk): clean up artifact code

---

.github/workflows/stale.yml

As [stale-bot is deprecated](https://github.com/probot/stale), we need to migrate to [Stale GHA](https://github.com/actions/stale)
**Checklist:**

chore: Add config for stale GHA

---

test/deploy-cluster.sh

e2e test failing due to 1.25.10-gke.1200 is no longer supported. ~~Now change the pinned version to 1.25.10-gke.2100, which is what GKE would auto-upgrade to from an 1.25 version.~~
Use version 1.25 instead to allow auto upgrade, as @chensun suggested in the comments.
Error message:
https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/9798/kubeflow-pipeline-upgrade-test/1689342821942693888#1:build-log.txt%3A129
GKE release note:
https://cloud.google.com/kubernetes-engine/docs/release-notes#2023-r17_version_updates
**Checklist:**

chore(test): change hard-coded GKE version to 1.25

---

backend/src/agent/persistence/client/pipeline_client.go
backend/src/agent/persistence/client/token_refresher.go
backend/src/agent/persistence/client/token_refresher_test.go
backend/src/agent/persistence/main.go
backend/src/apiserver/auth/authenticator_token_review.go
backend/src/apiserver/common/const.go
backend/src/apiserver/server/report_server.go
manifests/kustomize/base/installs/multi-user/persistence-agent/cluster-role.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-role.yaml

1. Add authentication and authorization logic to PipelineAPI PeportServer's methods - [reportworkflow](https://github.com/kubeflow/pipelines/blob/a634eef3ec541ee64eb0220d5db12b82f682479e/backend/src/apiserver/server/report_server.go#L47C24-L47C38) & [reportSheduledWorkflow](https://github.com/kubeflow/pipelines/blob/a634eef3ec541ee64eb0220d5db12b82f682479e/backend/src/apiserver/server/report_server.go#L78C24-L78C47) and
2. Force Persistence Agent to authenticate itself through Service Account Token Volume Projection when calling the above methods.
Issue: https://github.com/kubeflow/pipelines/issues/8074
**Checklist:**

feat(backend) Enable auth between pesistence agent and pipelineAPI (ReportServer)

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/pipeline_channel.py
sdk/python/kfp/dsl/pipeline_context.py
sdk/python/kfp/dsl/tasks_group.py
sdk/python/kfp/dsl/tasks_group_test.py
sdk/python/test_data/pipelines/if_elif_else.py
sdk/python/test_data/pipelines/if_elif_else.yaml
sdk/python/test_data/pipelines/if_elif_else_complex.py
sdk/python/test_data/pipelines/if_elif_else_complex.yaml
sdk/python/test_data/pipelines/if_else.py
sdk/python/test_data/pipelines/if_else.yaml
sdk/python/test_data/test_data_config.yaml

Supports authoring pipelines that use `dsl.If`, `dsl.Elif`, and `dsl.Else`. For example:
```python
@dsl.pipeline
def flip_coin_pipeline():
flip_coin_task = flip_coin()
with dsl.If(flip_coin_task.output == 'heads'):
print_and_return(text='Got heads!')
with dsl.Elif(flip_coin_task.output == 'tails'):
print_and_return(text='Got tails!')
with dsl.Else():
print_and_return(text='Draw!')
```
Note that `dsl.If` is merely an alias for `dsl.Condition`. `dsl.Elif` and `dsl.Else` are new functionality.
**Checklist:**

feat(sdk): support dsl.If, dsl.Elif, and dsl.Else

---

frontend/src/pages/NewRun.test.tsx
frontend/src/pages/functional_components/NewExperimentFC.tsx

- Remove the need for `setErrorMessage`, directly set the error message in html based on experiment name availability.
- Remove the need for `useEffect` for `setLatestVersion`, replaced with `useQuery` because `getLatestVersion()` is an API call.
- Add explanation for places where we need to disable `react-hooks/exhaustive-deps`.
- `setErrMsgFromApi` to undefined if the create experiment call is successful.
- Extended timeout for NewRun test since jest has been upgraded implicitly to 27. It is the version which `modern` fake timer has become default.
**Checklist:**

chore(frontend): Improve structure of NewExperimentFC.

---

frontend/src/lib/v2/DynamicFlow.test.ts
frontend/src/lib/v2/DynamicFlow.ts

Fix: https://github.com/kubeflow/pipelines/issues/9611
The `metadata.Execution` object does not store, the task name, but the task display_name used. When calling [getTaskNameToExecution](https://github.com/kubeflow/pipelines/blob/ba322abb010d832539d57e90c34be0557f550252/frontend/src/lib/v2/DynamicFlow.ts#L373), you get a map of `display_name -> executions[]`. The frontend was using the task name as key, leading to undefined execution.

Fix(frontend): content is not available

---

backend/src/v2/component/launcher_v2.go

Try to fix #7629
Print of `ls -la` after kfp-launcher created a dir
```
total 288
drwxrwxrwt 1 root root   4096 Aug 29 20:47 .
drwxr-xr-x 1 root root   4096 Aug 29 20:47 ..
drw-r--r-- 2 user user   4096 Aug 29 20:47 kfp <------ 0644 mode
-rw------- 1 root root 278952 Aug 16 20:34 tmp7xutvpq1
[KFP Executor 2023-08-29 20:47:56,221 INFO]: Looking for component `square` in --component_module_path `/tmp/tmp.Y2OeYEVRGv/ephemeral_component.py`
[KFP Executor 2023-08-29 20:47:56,221 INFO]: Loading KFP component "square" from /tmp/tmp.Y2OeYEVRGv/ephemeral_component.py (directory "/tmp/tmp.Y2OeYEVRGv" and module name "ephemeral_component")
[KFP Executor 2023-08-29 20:47:56,222 INFO]: Got executor_input:
{
"inputs": {
"parameterValues": {
"x": 2
}
},
"outputs": { …
```

fix(backend): OutPutPath dir creation mode Fixes #7629

---

backend/src/agent/persistence/client/scheduled_workflow_client.go
backend/src/common/util/scheduled_workflow.go

Trying to fix #9809 which also became an issue for our deployment. The k8s go client does not return APIVersion and Kind in some situations (see https://github.com/kubernetes/client-go/issues/308) - when debugging this, APIVersion and Kind could be retrieved on first pass over but afterwards the information is missing. I assume that this has something to do with the cache, but I am not sure.
Regarding the change: As far as I can tell, kind in APIVersion are fixed anyway in the place that I add the information, since these are `v1beta1.ScheduledWorkflow` objects.

fix(backend): Sync scheduled workflows v1 if APIVersion and Kind are missing. Fixes #9809

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/dsl/tasks_group.py
sdk/python/test_data/pipelines/if_elif_else.yaml
sdk/python/test_data/pipelines/if_elif_else_complex.py
sdk/python/test_data/pipelines/if_elif_else_complex.yaml
sdk/python/test_data/pipelines/if_else.yaml

This change is a pre-requisite for collecting outputs from conditional branches. Each conditional branch (if, elif, else) must be wrapped in a common outer pipeline which can surface "one of" the inner task outputs via [`value_from_oneof`](https://github.com/kubeflow/pipelines/blob/45fe8e86583646143d1685d9e04d887ff27440ee/api/v2alpha1/pipeline_spec.proto#L165) for parameters and [`artifact_selectors`](https://github.com/kubeflow/pipelines/blob/45fe8e86583646143d1685d9e04d887ff27440ee/api/v2alpha1/pipeline_spec.proto#L124) for artifacts.
No functional change. There is a UI change.
**Checklist:**

chore(sdk): wrap conditional branch groups in outer pipeline

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/test_data/pipelines/if_elif_else_complex.yaml
sdk/python/test_data/pipelines/parallelfor_fan_in/conditional_producer_and_consumers.yaml
sdk/python/test_data/pipelines/parallelfor_fan_in/nested_with_parameters.yaml
sdk/python/test_data/pipelines/parallelfor_fan_in/parameters_complex.yaml
sdk/python/test_data/pipelines/parallelfor_fan_in/parameters_simple.yaml
sdk/python/test_data/pipelines/parallelfor_fan_in/pipeline_producer_consumer.yaml

Non-functional fix. The return type of a `dsl.ParallelFor` group that has a `dsl.Collected` on it had an incorrect return type. The pipeline would still run, but the output was technically incorrect.
**Checklist:**

fix(sdk): fix incorrect sub-DAG output type when using `dsl.Collected`

---

backend/src/apiserver/main.go
backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/apiserver/server/api_util_test.go
backend/src/apiserver/server/experiment_server_test.go
backend/src/apiserver/server/fakes_test.go
backend/src/apiserver/server/job_server_test.go
backend/src/apiserver/server/pipeline_server_test.go
backend/src/apiserver/server/pipeline_upload_server_test.go
backend/src/apiserver/server/run_server.go
backend/src/apiserver/server/run_server_test.go
backend/src/apiserver/server/visualization_server_test.go
backend/src/common/util/metrics.go
backend/third_party_licenses/apiserver.csv
backend/third_party_licenses/cache_server.csv
backend/third_party_licenses/driver.csv
backend/third_party_licenses/launcher.csv
backend/third_party_licenses/persistence_agent.csv
backend/third_party_licenses/swf.csv
backend/third_party_licenses/viewer.csv
go.mod
go.sum

- Added metrics related to failed and successful workflow runs to be exported to Prometheus in ResourceManager.
- These new metrics can be filtered by each Namespace (`profile`) and by DisplayName (`workflow`)
- Improvements in how the gauge registers the count by using a Collector.
- Checks a specific metric when deleting a run if has already reached the minimum value of 0.
Tests are also updated to reflect the new changes
**Checklist:**

feat(backend): Added metrics to be collected from failed/successful workflows

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/for_loop.py
sdk/python/kfp/dsl/pipeline_channel.py
sdk/python/kfp/dsl/pipeline_channel_test.py
sdk/python/kfp/dsl/pipeline_context.py
sdk/python/kfp/dsl/tasks_group.py
sdk/python/test_data/pipelines/if_elif_else_complex.py
sdk/python/test_data/pipelines/if_elif_else_complex.yaml
sdk/python/test_data/pipelines/if_elif_else_with_oneof_parameters.py
sdk/python/test_data/pipelines/if_elif_else_with_oneof_parameters.yaml
sdk/python/test_data/pipelines/if_else_with_oneof_artifacts.py
sdk/python/test_data/pipelines/if_else_with_oneof_artifacts.yaml
sdk/python/test_data/pipelines/if_else_with_oneof_parameters.py
sdk/python/test_data/pipelines/if_else_with_oneof_parameters.yaml
sdk/python/test_data/test_data_config.yaml

Supports collecting outputs from conditional branches in a pipeline using `dsl.OneOf`. For example:
```python
@dsl.component
def flip_coin() -> str:
import random
return 'heads' if random.randint(0, 1) == 0 else 'tails'
@dsl.component
def print_and_return(text: str) -> str:
print(text)
return text
@dsl.pipeline
def flip_coin_pipeline() -> str:
flip_coin_task = flip_coin()
with dsl.If(flip_coin_task.output == 'heads'):
print_task_1 = print_and_return(text='Got heads!')
with dsl.Else():
print_task_2 = print_and_return(text='Got tails!')
oneof = dsl.OneOf(print_task_1.output, print_task_2.output)
print_and_return(text=oneof)
return oneof
```
There are three future work items to consider following this PR:
1. Migrate the `dsl.Collected` …

feat(sdk): support collecting outputs from conditional branches using `dsl.OneOf`

---

sdk/RELEASE.md
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/dsl/for_loop.py
sdk/python/kfp/dsl/importer_node_test.py

Fix bug where a `dsl.importer` argument is provided by a loop variable. For example:
```python
@dsl.component
def make_args() -> list:
return [{'uri': 'gs://foo'}]
@dsl.pipeline
with dsl.ParallelFor(make_args().output) as data:
dsl.importer(artifact_uri=data.uri, artifact_class=Dataset)
```
**Checklist:**

fix(sdk): fix bug when `dsl.importer` argument is provided by loop variable

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/component_factory.py
sdk/python/kfp/dsl/executor.py
sdk/python/kfp/dsl/executor_test.py
sdk/python/kfp/dsl/types/artifact_types.py
sdk/python/kfp/dsl/types/artifact_types_test.py
sdk/python/kfp/dsl/types/type_annotations.py
sdk/python/kfp/dsl/types/type_annotations_test.py
sdk/python/test_data/pipelines/pythonic_artifact_with_single_return.py
sdk/python/test_data/pipelines/pythonic_artifact_with_single_return.yaml
sdk/python/test_data/pipelines/pythonic_artifacts_with_list_of_artifacts.py
sdk/python/test_data/pipelines/pythonic_artifacts_with_list_of_artifacts.yaml
sdk/python/test_data/pipelines/pythonic_artifacts_with_multiple_returns.py
sdk/python/test_data/pipelines/pythonic_artifacts_with_multiple_returns.yaml
sdk/python/test_data/test_data_config.yaml
test/sdk-execution-tests/requirements.txt
test/sdk-execution-tests/sdk_execution_tests.py

Supports a Pythonic artifact authoring syntax, creating unity between the parameter and artifact authoring experiences.
```python
from kfp.dsl import Dataset, Model
@dsl.component
def train_model(dataset: Dataset) -> Model:
with open(dataset.path) as f:
dataset_lines = f.read()
trained_model = ...
model_artifact = Model(uri=dsl.get_uri())
trained_model.save(model_artifact.path)
return model_artifact
```
**Checklist:**

feat(sdk): support a Pythonic artifact authoring style

---

sdk/python/kfp/compiler/compiler_test.py

#10067 incidentally fixed #9320 that was surfaced by GCPC users. This change adds a test to ensure the original issue does not return.
**Checklist:**

chore(sdk): add test for key error bug resolved in #10067

---

components/kserve/README.md
components/kserve/component.yaml
components/kserve/src/kservedeployer.py

* Extending kserve component predictor to use a fixed runtime version and specific resource requests/limits
* Verified, that all frameworks listed [here](https://github.com/kubeflow/pipelines/blob/master/components/kserve/src/kservedeployer.py#L41-L50) expose `resources` and `runtime_version`
**Checklist:**

feat(components) Extend kserve component

---

sdk/RELEASE.md
sdk/python/kfp/__init__.py
sdk/python/kfp/dsl/component_factory.py
sdk/python/kfp/dsl/component_factory_test.py
sdk/python/kfp/init_test.py

Adds Python 3.7 EOL warning when:
- The KFP SDK is imported into an environment running Python 3.7  
- The `dsl.component` decorator is called without an explicit `base_image` argument
**Checklist:**

chore(sdk): add Python 3.7 EOL notice

---

sdk/python/kfp/compiler/read_write_test.py

- Remote the ` (<type>)` from the docstring args, which are redundant since there are type annotations.
**Checklist:**

chore(sdk): Remove the ` (<type>)`from docstring args.

---

sdk/python/kfp/client/client.py

The type annotation for the `credentials` argument of the `kfp.Client` constructor is wrong, it should be `TokenCredentialsBase`, not string.
**Checklist:**

fix(sdk): type annotation for client credentials

---

sdk/python/kfp/cli/component_test.py

Test was failing locally due to mixing use of an isolated filesystem with a test that assumed we 
were not using an isolated filesystem.
**Checklist:**

chore(sdk): fix local test failure

---

.readthedocs.yml

Fixes this issue: https://blog.readthedocs.com/use-build-os-config/
**Checklist:**
more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

docs(sdk): fix readthedocs build error

---

backend/src/apiserver/model/pipeline.go
backend/src/apiserver/model/pipeline_version.go

fix #7568
Pipeline and PipelineVersion Description column value should be optional, if the Description column type set to not null, it will occur an error when inserting a pipeline record with empty description.
**Checklist:**

fix(backend): Pipeline and PipelineVersion Description column value should be optional.

---

sdk/python/kfp/local/__init__.py
sdk/python/kfp/local/config.py
sdk/python/kfp/local/config_test.py

Local execution PR 1. Adds public API (added, but kept private until local execution is fully usable) and configuration objects.
**Checklist:**

feat(sdk): add local execution config #localexecution

---

sdk/RELEASE.md
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/component_factory.py
sdk/python/kfp/dsl/placeholders.py
sdk/python/kfp/dsl/placeholders_test.py
sdk/python/kfp/dsl/structures.py
sdk/python/kfp/dsl/structures_test.py

Adds support for an executor output path placeholder and executor input message placeholder.
**Checklist:**

feat(sdk): add executor output path and executor input message placeholders

---

frontend/server/configs.ts
frontend/server/integration-tests/artifact-get.test.ts

* Currently with the default object store i.e. minio, we have an option `MINIO_SSL` to specify useSSL variable value while creation of client using minio configs but we don't have a way to specify value of useSSL for aws configs.
* Added an option to specify the `useSSL` variable in AWS configs. This will be used to create client using aws configs.
* This change should not impact any existing users as I kept the default value same.
**Checklist:**

frontend: Add an option to specify useSSL variable for aws

---

frontend/src/pages/NewRunSwitcher.tsx
frontend/src/pages/NewRunV2.test.tsx
frontend/src/pages/PipelineDetails.test.tsx
frontend/src/pages/PipelineDetails.tsx

Fix #10153 
The main cause is because pipelines created by v1 before upgrading don't have `pipelnie_spec` field in `pipeline_version` object.
Adding getTemplate() and getPipelineVersionTemplate() call back in both `PIpelineDetails.tsx` and `NewRunSwticher.tsx` enables reading the template_string in old pipelines.
Before:
https://github.com/kubeflow/pipelines/assets/56132941/0a6bcad1-c941-47f0-8e79-4060d0a0acfe
After:
https://github.com/kubeflow/pipelines/assets/56132941/8cf4c458-e210-4078-8f5e-6083ff08ed7d

fix(frontend): Support running old v1 pipeline. Fix #10153

---

samples/v2/pipeline_with_secret_as_env.py
samples/v2/pipeline_with_volume.py

Examples `samples/v2/pipeline_with_secret_as_env.py` and `samples/v2/pipeline_with_volume.py` were not in a working state.

chore(sample): fix pipeline with secrets examples

---

backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/compiler/argocompiler/container.go

Resolves https://github.com/kubeflow/pipelines/issues/10229
Parameterizing the v2 launcher and driver images so it's possible to extend/provide fixes to the code.
**Testing instructions:**
Follow instructions listed [here](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/README.md#developing-kfp-v2) and run a `make install-compiler` to ensure that the changes compile correctly.
Save the code changes locally and build an API Server image
Deploy KFP using steps listed here and replace the API Server image with the above image. Make sure API Server still comes up correctly.
**Checklist:**

feat(backend): Parameterizing v2 Launcher and Driver Images

---

sdk/python/kfp/dsl/pipeline_task.py
sdk/python/kfp/dsl/pipeline_task_test.py
sdk/python/kfp/local/task_dispatcher.py

Local execution PR 2.
Adds the skeleton code for invoking local execution (behind a feature flag).
If a component is called outside of a pipeline, it will be executed by `task_dispatcher.run_single_component`. The `PipelineTask` has handling for local execution.
**Checklist:**

feat(sdk): add local execution skeleton #localexecution

---

sdk/python/kfp/dsl/base_component.py
sdk/python/kfp/dsl/base_component_test.py
sdk/python/kfp/dsl/pipeline_task.py
sdk/python/kfp/dsl/types/type_utils.py
sdk/python/kfp/dsl/utils.py
sdk/python/kfp/local/config.py
sdk/python/kfp/local/executor_input_utils.py
sdk/python/kfp/local/executor_input_utils_test.py
sdk/python/kfp/local/placeholder_utils.py
sdk/python/kfp/local/task_dispatcher.py
sdk/python/kfp/local/task_dispatcher_test.py
sdk/python/kfp/local/testing_utilities.py

More local execution changes. The main changes are to add some local execution validation + tests, as well as the code to construct the local executor input.
**Checklist:**

feat(sdk): add local task dispatcher validation and ExecutorInput construction #localexecution

---

test/presubmit-component-yaml.sh
test/presubmit-sdk-execution-tests.sh
test/presubmit-test-kfp-kubernetes-library.sh
test/presubmit-test-run-all-gcpc-modules.sh

Installs `kfp-pipeline-spec` from source in KFP SDK tests.
**Checklist:**

test(sdk): install `kfp-pipeline-spec` from source in `kfp` sdk tests

---

samples/core/loop_output/loop_output.py
sdk/python/kfp/deprecated/dsl/_component_bridge.py
sdk/python/kfp/deprecated/dsl/type_utils.py
sdk/python/kfp/deprecated/dsl/types.py

Fixes: #10282
replacing `kfp.components.types` with `kfp.dsl.types` as the package is relocated.
**Checklist:**
- [ x ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

fix(sdk): use kfp.dsl.types to replace kfp.components.types Fixes #10282

---

sdk/python/kfp/dsl/component_factory.py
sdk/python/kfp/dsl/executor.py
sdk/python/kfp/dsl/executor_test.py
sdk/python/kfp/local/config.py
sdk/python/kfp/local/config_test.py
sdk/python/kfp/local/status.py
sdk/python/kfp/local/subprocess_task_handler.py
sdk/python/kfp/local/subprocess_task_handler_test.py
sdk/python/kfp/local/task_dispatcher.py
sdk/python/kfp/local/task_handler_interface.py
sdk/python/kfp/local/task_handler_interface_test.py
sdk/python/kfp/local/testing_utilities.py

Add subprocess task handler to the task dispatcher.
There are basic tests, but will add more comprehensive E2E local execution tests once we support accessing outputs on locally executed tasks. There several other TODOs included throughout.
**Checklist:**

feat(sdk): add subprocess task handler #localexecution

---

sdk/python/kfp/dsl/types/artifact_types.py
sdk/python/kfp/local/e2e_test.py
sdk/python/kfp/local/executor_input_utils.py
sdk/python/kfp/local/executor_input_utils_test.py
sdk/python/kfp/local/executor_output_utils.py
sdk/python/kfp/local/executor_output_utils_test.py
sdk/python/kfp/local/placeholder_utils.py
sdk/python/kfp/local/placeholder_utils_test.py
sdk/python/kfp/local/subprocess_task_handler.py
sdk/python/kfp/local/task_dispatcher.py
sdk/python/kfp/local/task_dispatcher_test.py
sdk/python/kfp/local/testing_utilities.py

Adds the code that collects and surfaces the outputs from locally executed tasks on the `task.output` and `task.outputs['<key>']`.
This constitutes E2E local execution for the subprocess task handler. For this reason, we also now include E2E tests.
Forthcoming PRs will add the container task handler, logging, and a few more changes.
**Checklist:**

feat(sdk): add local execution output collection #localexecution

---

sdk/python/kfp/local/e2e_test.py
sdk/python/kfp/local/logging_utils.py
sdk/python/kfp/local/logging_utils_test.py
sdk/python/kfp/local/subprocess_task_handler.py
sdk/python/kfp/local/task_dispatcher.py
sdk/python/kfp/local/task_dispatcher_test.py

Add comprehensive logging for local execution.
**Checklist:**

feat(sdk): add local execution logging #localexecution

---

backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
backend/src/v2/metadata/client.go
backend/src/v2/metadata/client_test.go

The kfp-driver now recognizes query params and assembles bucket names correctly.
See #10318

feat(backend): preserve querystring in pipeline root (fixes #10318)

---

sdk/python/kfp/local/executor_output_utils.py
sdk/python/kfp/local/executor_output_utils_test.py

Matches logic on remote backend.
**Checklist:**

feat(sdk): add special `dsl.OutputPath` read logic #localexecution

---

sdk/python/kfp/local/logging_utils.py
sdk/python/kfp/local/task_dispatcher_test.py

In a notebook, `stderr` prints above `stdout`. For the logs to present sequentially and interleave correctly in a notebook, they must both write to the same place. We choose to write to `stdout`, consistent with `print`.
**Checklist:**

chore(sdk): write local execution logs to stdout #localexecution

---

sdk/python/kfp/local/docker_task_handler.py
sdk/python/kfp/local/docker_task_handler_test.py
sdk/python/kfp/local/executor_output_utils.py
sdk/python/kfp/local/executor_output_utils_test.py
sdk/python/kfp/local/placeholder_utils.py
sdk/python/kfp/local/placeholder_utils_test.py
sdk/python/kfp/local/subprocess_task_handler.py
sdk/python/kfp/local/task_dispatcher.py

Adds support for locally running Container Components using the local `DockerRunner`. The primary changes are to add support for most Container Components placeholder types.
Also:
- Removes the artificial blocker on Container Component execution in the `DockerRunner`'s task handler
- Fixes case where empty commands or args will throw an error
- Corrects erroneous the image pull logic, which previously attempted to pull even when local image was found
- Permits the case when `executor_output.json` is not written, which is typical for Container Components
**Checklist:**

feat(sdk): support local Container Component execution #localexecution

---

sdk/RELEASE.md
sdk/python/kfp/dsl/pipeline_task.py
sdk/python/kfp/local/__init__.py
sdk/python/kfp/local/testing_utilities.py

Remove local execution feature flag.
**Checklist:**

feat(sdk): remove local execution feature flag #localexecution

---

sdk/python/kfp/local/executor_output_utils.py
sdk/python/kfp/local/subprocess_task_handler_test.py

It should be permitted for a user to specify a `dsl.OutputPath` to which the output is not written. This PR fixes a key error when this is the case.
**Checklist:**

fix(sdk): permit empty local execution outputs #localexecution

---

sdk/python/kfp/local/docker_task_handler_test.py
sdk/python/kfp/local/placeholder_utils.py
sdk/python/kfp/local/placeholder_utils_test.py

Adds support for the `dsl.ConcatPlaceholder` and `dsl.IfPresentPlaceholder` in local execution of Container Components.
**Checklist:**

feat(sdk): support Concat and IfPresent placeholder in local container component execution #localexecution

---

sdk/python/kfp/local/subprocess_task_handler_test.py

Adds a test for local execution of optional parameters (e.g., `my_comp(x: Optional[str] = None)`.
**Checklist:**

test(sdk): add test for local execution of `None` default parameter #localexecution

---

kubernetes_platform/python/setup.py
sdk/RELEASE.md
sdk/python/requirements.in
sdk/python/requirements.txt

#protobuf4
This PR makes the `kfp` and `kfp-kubernetes` changes together, since that plays most nicely with our simple test triggering logic.
**Checklist:**

chore(sdk): depend on protobuf 4 in `kfp` and `kfp-kubernetes`

---

kubernetes_platform/python/create_release_branch.sh
kubernetes_platform/python/docs/conf.py
kubernetes_platform/python/release.sh

- Adds `kfp-kubernetes` docs versions to master.
- Updates the instructions printed out by the script.
Also need to update the release instructions to say "update the `kfp-kubernetes docs version` on the master branch.
**Checklist:**

chore(sdk): update `kfp-kubernetes` docs versions and release scripts

---

sdk/python/kfp/cli/diagnose_me/utility_test.py

Fix string quotes to pass formatting presubmit.
**Checklist:**

fix(sdk): fix string quotes

---

backend/src/v2/metadata/client.go

Fixing [issue 9878](https://github.com/kubeflow/pipelines/issues/9878). Because default implementation of MLMD fetches 20 executions in one request, when there is over 20 executions in single DAG tasks could fail.
This change fetches next page automatically if NextPageToken exists so there is no missing execution.
**Checklist:**

fix(backend): MLMD pagination on getting executions of DAG

---

sdk/RELEASE.md
sdk/python/kfp/dsl/pipeline_task.py
sdk/python/kfp/dsl/types/type_utils.py
sdk/python/kfp/local/dag_orchestrator.py
sdk/python/kfp/local/executor_input_utils.py
sdk/python/kfp/local/executor_input_utils_test.py
sdk/python/kfp/local/graph_utils.py
sdk/python/kfp/local/graph_utils_test.py
sdk/python/kfp/local/io.py
sdk/python/kfp/local/io_test.py
sdk/python/kfp/local/logging_utils.py
sdk/python/kfp/local/logging_utils_test.py
sdk/python/kfp/local/pipeline_orchestrator.py
sdk/python/kfp/local/pipeline_orchestrator_test.py
sdk/python/kfp/local/placeholder_utils.py
sdk/python/kfp/local/placeholder_utils_test.py
sdk/python/kfp/local/task_dispatcher.py
sdk/python/kfp/local/task_dispatcher_test.py

Enables running a pipeline locally:
```python
from kfp import local
local.init(runner=local.SubprocessRunner())
@dsl.component
def add(a: int, b: int) -> int:
return a + b
@dsl.pipeline
def my_pipeline(num: int) -> int:
t1 = add(a=num, b=2)
t2 = add(a=t1.output, b=3)
return t2.output
task = my_pipeline(num=1)
print(f'Got result: {task.output}')
```
Currently:
- Only sequential pipelines are supported. Control flow features (`dsl.Condition`, `dsl.ParallelFor`, and `dsl.ExitHandler`) are not supported yet.
- `dsl.importer`is not supported yet.
- Pipeline-in-pipeline is not supported yet.
- Passing data via f-strings is not supported.
**Checklist:**

feat(sdk): support local pipeline execution

---

sdk/python/kfp/local/executor_input_utils.py
sdk/python/kfp/local/executor_input_utils_test.py
sdk/python/kfp/local/pipeline_orchestrator_test.py
sdk/python/kfp/local/placeholder_utils.py
sdk/python/kfp/local/placeholder_utils_test.py

Support f-strings in local pipeline execution.
```python
from kfp import local
local.init(runner=local.SubprocessRunner())
@dsl.component
def identity(string: str) -> str:
return string
@dsl.pipeline
def my_pipeline(string: str = 'baz') -> str:
op1 = identity(string=f'bar-{string}')
op2 = identity(string=f'foo-{op1.output}')
return op2.output
task = my_pipeline()
assert task.output == 'foo-bar-baz'
```
**Checklist:**

feat(sdk): support f-strings in local pipeline execution

---

sdk/RELEASE.md
sdk/python/kfp/dsl/structures.py
sdk/python/kfp/dsl/types/artifact_types.py
sdk/python/kfp/dsl/types/custom_artifact_types.py
sdk/python/kfp/dsl/types/type_annotations.py
sdk/python/kfp/dsl/types/type_utils.py
sdk/python/kfp/local/dag_orchestrator.py
sdk/python/kfp/local/importer_handler.py
sdk/python/kfp/local/importer_handler_test.py
sdk/python/kfp/local/pipeline_orchestrator_test.py
sdk/python/kfp/local/placeholder_utils.py
sdk/python/kfp/local/task_dispatcher.py

Support for local execution of `dsl.importer`:
```python
local.init(local.SubprocessRunner(), pipeline_root=ROOT_FOR_TESTING)
@dsl.component
def artifact_printer(a: Dataset):
print(a)
@dsl.pipeline
def my_pipeline() -> Dataset:
imp_op = dsl.importer(
artifact_uri='/local/path/to/dataset',
artifact_class=Dataset,
metadata={
'foo': 'bar',
})
artifact_printer(a=imp_op.outputs['artifact'])
return imp_op.outputs['artifact']
```
**Checklist:**

feat(sdk): support for local execution of `dsl.importer`

---

sdk/RELEASE.md
sdk/python/kfp/local/dag_orchestrator.py
sdk/python/kfp/local/pipeline_orchestrator.py
sdk/python/kfp/local/pipeline_orchestrator_test.py

Supports locally executing pipelines in pipelines.
For example:
```python
from kfp import local
local.init(runner=local.SubprocessRunner())
@dsl.component
def square(x: float) -> float:
return x ** 2
@dsl.component
def add(x: float, y: float) -> float:
return x + y
@dsl.component
def square_root(x: float) -> float:
return x ** .5
@dsl.pipeline
def square_and_sum(a: float, b: float) -> float:
a_sq_task = square(x=a)
b_sq_task = square(x=b)
return add(x=a_sq_task.output, y=b_sq_task.output).output
@dsl.pipeline
def pythagorean(a: float = 1.2, b: float = 1.2) -> float:
sq_and_sum_task = square_and_sum(a=a, b=b)
return square_root(x=sq_and_sum_task.output).output
result = pythagorean().output
print("The result is: {result}")
``` …

feat(sdk): support local execution of pipelines in pipelines

---

backend/src/apiserver/model/run.go
backend/src/apiserver/model/task.go
backend/src/apiserver/storage/default_experiment_store_test.go
backend/src/apiserver/storage/job_store_test.go
backend/src/apiserver/storage/run_store_test.go
backend/src/apiserver/storage/task_store_test.go

resolves: #10429
Reference to the col names: https://github.com/kubeflow/pipelines/blob/d4c43f77bc38080506794377647ce5b1d9f18bdf/backend/src/apiserver/storage/run_store.go#L496 and https://github.com/kubeflow/pipelines/blob/d4c43f77bc38080506794377647ce5b1d9f18bdf/backend/src/apiserver/storage/run_store.go#L517

fix(backend): correct run field map col names

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py

fix(sdk): fix bug where `dsl.OneOf` with multiple consumers cannot be compiled

---

backend/src/apiserver/resource/resource_manager.go

This fixes a bug introduced in https://github.com/kubeflow/pipelines/pull/9317/commits/cbb86ba64c94d4a9de45927d0b6273ab645e88f6 where an InternalServerError causes the ml-pipeline pod to crash https://github.com/kubeflow/pipelines/issues/10267
The if-else contains an err re-assignment, which can make the err become nil when it enters the else statement. This causes issue as the err was specifically checked against nil before the if/else, and the err's property will be accessed in the else clause, causing segfault equivalent error
Minimal example showing the re-assignment https://go.dev/play/p/52EY9LWNZUJ
**Checklist:**

Fix(backend): fix timeout for internal server error. Fixes #10267

---

components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests

- Do not use a fixture for the kfp client
- Upgrade ACK version
- Uninstall standalone kfp to cleanup resources.
**Checklist:**

test(components): Reduce sagemaker component test flakiness

---

README.md

fixes #10475 
Update the Kubeflow Pipelines on Tekton blog since the previous blog no longer exist. This blog demonstrates how we optimized KFP on Tekton and the same principle can be applied to the Argo backend as well.
**Checklist:**

chore(README): Update Kubeflow Pipelines on Tekton blog

---

backend/src/v2/cmd/driver/execution_paths.go
backend/src/v2/cmd/driver/main.go
backend/src/v2/cmd/driver/main_test.go

Fixes: https://github.com/kubeflow/pipelines/issues/9678
I propose these changes as an initial solution, but I'm not sure it's the best one. So, feel free to recommend a better one and I'll be happy to implement it.
This PR modifies the driver so it creates the needed files with default values when `IterationCount` and `Condition` are `nil`.
The errors happen because we return an `Execution` without setting `IterationCount` and `Condition` here:
- https://github.com/kubeflow/pipelines/blob/87db18e3a1df08a23a71f872dc8dac6b4bfb9a95/backend/src/v2/driver/driver.go#L175
- https://github.com/kubeflow/pipelines/blob/87db18e3a1df08a23a71f872dc8dac6b4bfb9a95/backend/src/v2/driver/driver.go#L343
Which prevents it from creating the files here:
- …

fix(backend): fixes "cannot save parameter" error message. Fixes #9678

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/dsl/for_loop.py
sdk/python/kfp/dsl/for_loop_test.py

Adds additional test for [\#10441](https://github.com/kubeflow/pipelines/pull/10441)
**Checklist:**

test: Add ParallelFor compile test over single artifact.

---

backend/src/apiserver/server/pipeline_upload_server.go

This is the backend fix of #10311.
I propose following solution but feel free to recommend a better one.
When uploading pipeline which already exists, it returns HTTP 500 error (internal server error) while it should return 409 error (conflict error). In order to solve this problem, I insert a branch by error code using `util.IsUserErrorCodeMatch`.
**Checklist:**

fix(backend): Fixes response status of http error code when uploading duplicate pipeline [Fixes  #10311]

---

.github/stale.yml
.github/workflows/stale.yml

daysUntilClose is set to 90 days. This is too much for an issue to keep opened as there is daysUntilStale set to 90 days. That would keep an issue opened for 6 months, and now there are +600 issues opened in the repository.
We need to start working on keeping the repository healthy.
**Checklist:**

chore: Change stalebot rules

---

backend/api/v2beta1/recurring_run.proto
backend/api/v2beta1/run.proto

This helps in resolving [10451](https://github.com/kubeflow/pipelines/issues/10451) . This just changes the comment for a deprecated field to reflect the same status so that website API docs will reflect the same once it is updated.
**Checklist:**

fix: Modified the comment/text for pipeline_version_id

---

backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
backend/api/v2beta1/swagger/recurring_run.swagger.json
backend/api/v2beta1/swagger/run.swagger.json

Continuation of the modifications made in the PR [10581](https://github.com/kubeflow/pipelines/pull/10581)
This will help resolve issue #10451 . This will help us generate the new API docs with the correction.
**Checklist:**

fix: Modified the swagger json files according to the modified proto files.

---

third_party/metadata_envoy/Dockerfile
third_party/metadata_envoy/envoy.yaml

Upgrades envoy metadata proxy from 1.12 to 1.27 since 1.12 is no longer supported and is not receiving patches. I chose 1.27 because it's the version supported by the istio version I am using [istio docs](https://istio.io/latest/docs/releases/supported-releases/#supported-envoy-versions)
This is my first PR here! I might need some help validating that this doesn't break anything.
closes #10578 
**Checklist:**

fix(metadata envoy): upgrade envoy and config from 1.12 to 1.27

---

samples/core/loop_output/loop_output.py

After PR #10494, all the parallel loop input type has to be `List`. The current loop_output.py example still output as `str` which causes the following errors:
```shell
Cannot iterate over a single parameter using `dsl.ParallelFor`. Expected a list of parameters as argument to `items`.
```
Thus, fix the loop_output.py example to output type `List[str]`.
**Checklist:**

fix(samples): Fix the loop_output.py example to handle the new parallel loop type requirement

---

components/kserve/Dockerfile
components/kserve/README.md
components/kserve/component.yaml
components/kserve/requirements.txt

Update kserve component to v0.12.0 to prepare for the Kubeflow 1.9 release.
**Checklist:**

chore(components): Update kserve component to v0.12.0

---

samples/v2/pipeline_with_secret_as_env.py
samples/v2/pipeline_with_secret_as_volume.py

these samples currently only work on the Google Cloud distribution because of hardcoded secret name that only pre-exists there. 
1 extract the hardcoded secret name to a const to make it a little easier to change
2 add a note about it.
**Checklist:**

chore(sample): add note about secret needing to be pre-created

---

backend/src/v2/component/importer_launcher.go
backend/src/v2/component/launcher_v2.go
backend/src/v2/component/launcher_v2_test.go
backend/src/v2/config/env.go
backend/src/v2/config/env_test.go
backend/src/v2/config/gcs.go
backend/src/v2/config/minio.go
backend/src/v2/config/s3.go
backend/src/v2/config/testdata/provider_cases.yaml
backend/src/v2/driver/driver.go
backend/src/v2/metadata/client.go
backend/src/v2/metadata/client_fake.go
backend/src/v2/metadata/client_test.go
backend/src/v2/objectstore/config.go
backend/src/v2/objectstore/object_store.go
backend/src/v2/objectstore/object_store_test.go
go.mod

resolves most of: https://github.com/kubeflow/pipelines/issues/9689 and https://github.com/kubeflow/pipelines/issues/10651
the mlpipeline endpoint hardcoding is not addressed here.
This pr extends the kfp-launcher config to support configurations for supporting different credentials for s3/minio/gcs for different path prefixes. The config is parsed in the driver, and passed to executor via mlmd context custom property.
A fleshed out kfp-launcher configmap can look like this:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
name: kfp-launcher
namespace: kubeflow
data:
defaultPipelineRoot: "s3://my-s3-bucket-1/pipelines"
providers: |
<provider_config>
```
where the `<provider_config>` can look like:
```yaml
s3:
default:
endpoint: "s3.amazonaws.com"
region: …
```

feat(backend): add namespace & prefix scoped credentials to kfp-launcher config for object store paths

---

frontend/Dockerfile
frontend/package-lock.json
frontend/package.json

Resolves: https://github.com/kubeflow/pipelines/issues/10770
Furthers: https://github.com/kubeflow/pipelines/issues/10777 
Note while [node 18 is still in maintenance](https://nodejs.org/en/about/previous-releases), this is not the latest 18.x release, which is 18.20.2 as of this writing. I was encountering issues with 18.19 and 18.20, so I settled for 18.18 to resolve the current build issues. But we update to the latest as a follow up.
`@craco/craco` also needed a minor version bump, and package-lock.json was updated via `npm i --package-lock-only`, with the following env: 
```
{
npm: '9.8.1',
node: '18.18.2',
}
```
I'm not well versed in frontend so if this is not the right way, let me know and I can update it.
**Checklist:**

chore: upgrade node to v18

---

.github/workflows/periodic.yml

Fixes #10745. I have added the workflow file and tried running it locally, but I guess there is some issue with the package versions in `requirements.txt`. 
Error Log:
```
|   × Preparing metadata (pyproject.toml) did not run successfully.
|   │ exit code: 1
|   ╰─> [40 lines of output]
|       Traceback (most recent call last):
|         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
|           main()
|         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
|           json_out['return_val'] = hook(**hook_input['kwargs'])
|         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in …
```

feat(GH workflow): migrate periodic functional tests to GH actions

---

backend/Makefile
backend/api/Makefile
test/imagebuilder/Makefile
test/release/Makefile

Implementes #10724
Introduces some variables to various backend Makefiles, which can be overridden to allow developers to change the container build engine and target image tags.  Defaults are still maintainted to preserve consistency.
**Checklist:**

chore: Add Container Engine and Image Tag parameters to backend Makefiles

---

backend/src/apiserver/client/minio.go
backend/src/apiserver/client_manager/client_manager.go

Resolve: https://github.com/kubeflow/pipelines/issues/10800
**Checklist:**

chore: add meaningful logs to client initialization.

---

test/kfp-functional-test/kfp-functional-test.sh

GitHub CI periodic functional tests proposed in https://github.com/kubeflow/pipelines/pull/10751 currently fail due to insufficient permissions: 
This PR modifies test file to be compatible with GitHub actions.
**Checklist:**

test: fix CI failure for periodic functional tests

---

.github/workflows/periodic.yml

Periodic Functional Tests are running every 5 minutes currently, which is causing a lot of spam. Reducing the frequency to have it run once in a day at midnight.
**Checklist:**

chore: Update Periodic Functional Tests to run once a day

---

backend/src/apiserver/client/util.go
backend/src/apiserver/main.go

Resolves https://github.com/kubeflow/pipelines/issues/10832
**Checklist:**

chore: server should skip sample load if path DNE

---

kubernetes_platform/python/README.md

Referring the [kfp-kubernetes Reference Documentation](https://kfp-kubernetes.readthedocs.io/en/kfp-kubernetes-1.2.0/#configmap-as-environment-variable) the "ConfigMap: As environment variable" example contains incorrect key_name in kubernetes.use_config_map_as_env() code block.
Modification: secret_key_to_env to config_map_key_to_env
Supporting reference for modification: [use_config_map_as_env code reference](https://github.com/kubeflow/pipelines/blob/master/kubernetes_platform/python/kfp/kubernetes/config_map.py#L26)
Updated the README.md, this change should be reflected in kfp-kubernetes readthedocs.

docs: modified the ConfigMap as Env variable example in README.md with right key_name within use_config_map_as_env() block.

---

sdk/python/kfp/registry/context/kfp_pkg_dev.json
sdk/python/kfp/registry/registry_client.py
sdk/python/kfp/registry/registry_client_test.py

The scopes are defined in registry context file. Additional scopes must be comma separated.
Fixes #8878. Previous PR #8895 was approved, but tests failed and became stale.
I fixed the tests, and confirmed it worked for my case. Using a GCP Service Account with RegistryClient no longer requires me to explicitly provide the required scopes.
**Checklist:**

fix(sdk): Add required auth scopes to RegistryClient for GCP service accounts credentials

---

manifests/kustomize/env/platform-agnostic-multi-user-legacy/kustomization.yaml
manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml

This is a noop for most people as they use legacy sorting in kustomize. If however, people use fifo sorting via sortOptions in the root kustomization.yaml, the order of resources becomes important so that the CompositeController CRDs are deployed before the CRs.
**Checklist:**

fix(manifests): Move metacontroller to the top in kustmization.yaml

---

.github/workflows/presubmit-backend.yml
test/presubmit-backend-test.sh

Resolves https://github.com/kubeflow/pipelines/issues/10867
Converts the Prow backend test to a GH Action Workflow.
Here's a working GH Action run on my fork: https://github.com/DharmitD/data-science-pipelines-argo/actions/runs/9390063669
**Checklist:**

test: Migrate Backend tests to a GHA workflow

---

backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
backend/src/v2/compiler/argocompiler/testdata/create_pod_metadata.yaml
backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml

This is a shared pr with @gregsheremeta, picking this pr up from [here](https://github.com/kubeflow/pipelines/pull/10538) due to the expressed urgency by the community to have this issue prioritized. 
credit to @gregsheremeta for the changes, I just fixed the test cases and rebased. 
Fixes: https://github.com/kubeflow/pipelines/issues/5673
Fixes: https://github.com/kubeflow/pipelines/issues/7345
---
Comments by @gregsheremeta from the original PR: 
> Launcher writes input artifacts to root paths /gcs, /minio, and /s3. These paths are not accessible by non-root users by default, which is problematic in locked-down Kubernetes installations and/or OpenShift. https://github.com/kubeflow/pipelines/issues/5673#issuecomment-901045901
> Mount an EmptyDir scratch …

feat(backend): mount EmptyDir volumes for launcher write locations

---

kubernetes_platform/Makefile

On Fedora, which runs SELinux, mounting the container to the local filesystem results in permission issues because the labels mismatch: `make: stat: Makefile: Permission denied`
To fix this, change the directory mount to use the `-v` syntax and add the `:z` option at the end. Ref:
https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
**Checklist:**

fix(kubernetes_platform): fix api-generator docker mount for SELinux

---

backend/Dockerfile

This PR updates [backend/Dockerfile](https://github.com/kubeflow/pipelines/blob/bf5104fcff6a6c2db8d8e39522c04eca1bb3fc93/backend/Dockerfile#L30) to use Python 3.8 since Python 3.7 is no longer supported by https://bootstrap.pypa.io/pip/3.7/get-pip.py.
```
ERROR: This script does not work on Python 3.7 The minimum supported Python version is 3.8. Please use https://bootstrap.pypa.io/pip/3.7/get-pip.py instead.
Error: building at STEP "RUN wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py": while running runtime: exit status 1
```
**Checklist:**

chore: Updated Python image to 3.8 in backend/Dockerfile

---

components/google-cloud/google_cloud_pipeline_components/_implementation/starry_net/evaluation/evaluation.yaml
components/google-cloud/google_cloud_pipeline_components/_implementation/starry_net/upload_model/upload_model.yaml

Expose starry_net yaml to GitHub
Fix GitHub test error:
```
>       with open(file_path, 'r') as component_stream:
E       FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/google_cloud_pipeline_components/_implementation/starry_net/evaluation/evaluation.yaml'
/usr/local/lib/python3.8/site-packages/kfp/components/load_yaml_utilities.py:53: FileNotFoundError
```
Signed-off-by: Googler <nobody@google.com>

Expose starry_net yaml to GitHub

---

backend/src/v2/component/importer_launcher.go
backend/src/v2/component/launcher_v2.go
backend/src/v2/config/env.go
backend/src/v2/metadata/client.go
backend/src/v2/metadata/client_fake.go
backend/src/v2/objectstore/config.go
backend/src/v2/objectstore/object_store.go
frontend/server/aws-helper.test.ts
frontend/server/aws-helper.ts
frontend/server/handlers/artifacts.ts
frontend/server/integration-tests/artifact-get.test.ts
frontend/server/k8s-helper.ts
frontend/server/minio-helper.test.ts
frontend/server/minio-helper.ts
frontend/server/utils.ts
frontend/server/workflow-helper.ts
frontend/src/components/ArtifactPreview.tsx
frontend/src/components/MinioArtifactPreview.tsx
frontend/src/components/tabs/InputOutputTab.tsx
frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
frontend/src/components/viewers/MetricsVisualizations.tsx
frontend/src/lib/Apis.test.ts
frontend/src/lib/Apis.ts
frontend/src/lib/OutputArtifactLoader.test.ts
frontend/src/lib/OutputArtifactLoader.ts
frontend/src/mlmd/MlmdUtils.ts
frontend/src/pages/RunList.test.tsx

Frontend Follow up to: https://github.com/kubeflow/pipelines/pull/10625
Resolves the object storage portion of: https://github.com/kubeflow/pipelines/issues/9689 
Changes to backend: 
* For each artifact, add an artifact property in mlmd that keeps track of how to track down where it is located (i.e. which provider, where are the credentials, etc.). This is the same information that is stored as a context property, introduced in #1065, but because each artifact is not tied to a specific context (import or cached artifacts for example), we propogate these to their artifact properties (when newly created within a context). 
* We assume import artifacts will leverage the environment for it's credentials (e.g. via IRSA), this means both the user executor pod, …

feat(frontend&backend): Add UI support for object store customization and prefixes

---

backend/src/v2/README.md

This PR just removes some deprecated documentation from the backend/src/v2 README file.
**Checklist:**

docs(backend): Remove deprecated v2 compatibility mode docs

---

.github/workflows/backend.yml
api/go.mod
backend/api/Dockerfile
go.mod
go.sum
kubernetes_platform/go.mod
kubernetes_platform/go.sum
test/tools/project-cleaner/go.mod
third_party/ml-metadata/go.mod
third_party/ml-metadata/go.sum

Resolves https://github.com/kubeflow/pipelines/issues/10912
**Checklist:**

Upgrade go version to 1.21

---

.github/workflows/sdk-yapf.yml

Resolves https://github.com/kubeflow/pipelines/issues/10925
Converts the KFP SDK YAPF test to a GH Action Workflow.
Here's a working GH Action run on my fork: https://github.com/DharmitD/data-science-pipelines-argo/actions/runs/9672832818
PR to remove the KFP SDK YAPF test from prow config: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2310
**Checklist:**

test: Migrate KFP SDK YAPF test to a GHA Workflow

---

.github/workflows/periodic.yml
test/kfp-functional-test/kfp-functional-test.sh

Hopefully last fix for periodic functional tests. Current problems (https://github.com/kubeflow/pipelines/issues/10851):
1. Tests fail in GH workflows as they try to connect to the same GCP cluster that prow tests run on. The corresponding environment is not configured in GitHub.
2. Tests fail in prow as they try to run `sudo` which is not available on python3.7-slim (runs on debian).
Solutions:
1. For GH actions, use the kind cluster defined in the workflow file to run the test instead of GCP test cluster. This requires actually installing kfp on this kind cluster. I copypasted installation from the [backend test workflow file](https://github.com/kubeflow/pipelines/blob/master/.github/workflows/backend.yml). Let me know if there is a simpler/faster …

test: install kfp on github periodic functional tests workflow

---

.github/workflows/rerun-pr-jobs.yaml

The following commands are supported by this action:
`/rerun-all` - rerun all failed workflows.
`/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.
Some notes:
The PR either must have an `ok-to-test` label present on the PR, or the user who writes a command must be an organization member, or repo owner, contributor, or collaborator.
Typically `ok-to-test` can/should only be applied by repo reviewers/approvers to prevent spam and abuse.
Reference: https://github.com/estroz/rerun-actions
cc @chensun @zijianjoy @connor-mccarthy 
**Checklist:**

chore: Add an option to re-run GHA workflows

---

.github/workflows/backend-visualization.yml

Resolves: https://github.com/kubeflow/pipelines/issues/10985
PR to remove the tests from GoogleCloudPlatform/oss-test-infra:
- https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2316
**Checklist:**

test: Moved KFP backend visualization tests to GitHub Actions

---

.github/workflows/sdk-upgrade.yml

Resolves https://github.com/kubeflow/pipelines/issues/10987
Converts the KFP SDK Upgrade test to a GH Action Workflow.
Here's a working GH Action run on my fork: https://github.com/DharmitD/data-science-pipelines-argo/actions/runs/9862965921/job/27234673632
PR to remove the KFP SDK Upgrade test from prow config: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2317
**Checklist:**

test: Migrate KFP SDK Upgrade Test to GHA

---

.github/workflows/kfp-sdk-runtime-tests.yml

Resolves https://github.com/kubeflow/pipelines/issues/10987
Converts the KFP SDK Runtime Code test to a GH Action Workflow.
Here's a working GH Action run on my fork: https://github.com/DharmitD/data-science-pipelines-argo/actions/runs/9863919827/job/27237733585
PR to remove the KFP Execution test from prow config: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2318
**Checklist:**

test: Migrate KFP SDK Runtime Code Test to GHA

---

sdk/python/kfp/dsl/tasks_group.py

**Due to https://github.com/kubeflow/pipelines/pull/11005#issuecomment-2239295707, depends on:**
- https://github.com/kubeflow/pipelines/pull/10975
- https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2313
Resolves https://github.com/kubeflow/pipelines/issues/10187
The issue happens when an ExitHandler has a parameter that depends on other task.
```python
from kfp.dsl import PipelineTaskFinalStatus
@dsl.component
def test_step_a(input: str) -> str:
return "step-a"
@dsl.component
def test_step_b(input: str, status: PipelineTaskFinalStatus):
print("step-b")
@dsl.component
def test_step_c(input: str) -> str:
return "step-c"
@dsl.pipeline
def test_pipeline():
pre_task = test_step_a(input="pre")
exit_task = test_step_b(input=pre_task.output)  <--- Here's the problem …
```

fix(sdk): Throw 'exit_task cannot depend on any other tasks.' error when an ExitHandler has a parameter dependent on other task

---

sdk/python/kfp/cli/dsl.py

fix(docs): IR -> Pipeline Spec
**Checklist:**

fix(docs): IR -> Pipeline Spec

---

.github/workflows/kfp-sdk-tests.yml
sdk/python/kfp/cli/component_test.py

Resolves https://github.com/kubeflow/pipelines/issues/10987
Converts the KFP SDK tests to a GH Action Workflow.
Here's working GH Action run on my fork: https://github.com/DharmitD/data-science-pipelines-argo/actions/runs/10080983836
PR to remove the KFP Execution test from prow config: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2329
**Checklist:**

test: Migrate KFP SDK Tests to GHA

---

api/Makefile
kubernetes_platform/Makefile
sdk/CONTRIBUTING.md

Furthers: https://github.com/kubeflow/pipelines/issues/10993 
Add detailed instructions for contributors on how they can set up their sdk development environment.

add dev docs for kfp/sdk

---

.github/workflows/kfp-kubernetes-library-test.yaml
.github/workflows/kfp-kubernetes-test.yaml
test/presubmit-test-kfp-kubernetes-library.sh

Resolve https://github.com/kubeflow/pipelines/issues/11008
**Implementation notes:**
Removes also the code into oss-test-infra: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2322
Due that we added `sudo` in the bash script. The following GHA are failing and are expected
```
kfp-kubernetes-test-python38	47c82a8	link	true	/test kfp-kubernetes-test-python38
kfp-kubernetes-test-python310	47c82a8	link	true	/test kfp-kubernetes-test-python310
kfp-kubernetes-test-python311	47c82a8	link	true	/test kfp-kubernetes-test-python311
kfp-kubernetes-test-python39	47c82a8	link	true	/test kfp-kubernetes-test-python39
kfp-kubernetes-test-python312	47c82a8	link	true	/test kfp-kubernetes-test-python312
```
**Checklist:**
- [ X ] The title for your pull request …

test: Add script and GitHub Action for kfp-kubernetes-library

---

samples/core/loop_parallelism/loop_parallelism.py
samples/core/loop_parameter/loop_parameter.py

The type hint on `loop_parallelism` is incorrect, leading to a failure in compiling with the latest version of `kfp` Version: 2.8.0. Without this MR you get the following error:
```bash
...
raise InconsistentTypeException(error_text)
kfp.dsl.types.type_utils.InconsistentTypeException: Incompatible argument passed to the input 's' of component 'print-op': Argument type 'NUMBER_INTEGER' is incompatible with the input type 'STRING'
```
I also took the time to fix `loop_parameter.py` 
It was throwing this error without the changes applied in this MR
```python
raise ValueError(
ValueError: Cannot iterate over a single parameter using `dsl.ParallelFor`. Expected a list of parameters as argument to `items`.
```
**Checklist:**

fix: Incorrect typing in samples/cores/loop_parallism and fixing loop_parameter examples

---

.github/workflows/e2e-test.yaml

Fixes: https://github.com/kubeflow/pipelines/issues/11069
Tests were failing due to lack of disk space. This PR changes the workflow so each test suite runs on its own runner.

chore: Fixed e2e tests

---

api/v2alpha1/pipeline_spec.proto

Adds the fields resource_cpu_limit, resource_cpu_request, resource_memory_limit, resource_memory_request, resource_accelerator_type, and resource_accelerator_count.
**Checklist:**

feat(api): Add new ResourceSpec proto fields to support dynamic values.

---

kubernetes_platform/python/README.md

Fix environment variable names 
The current code is using `os.environ['my-secret']` but we are setting the environment variable to be `SECRET_VAR`
```
kubernetes.use_secret_as_env(task,
secret_name='my-secret',
secret_key_to_env={'password': 'SECRET_VAR'})
```
The code  `os.environ['my-secret']` will return an error
```
print(os.environ['my-secret'])
File "/usr/lib64/python3.9/os.py", line 679, in __getitem__
raise KeyError(key) from None
KeyError: 'my-secret'
```
The goal of this PR is to fix the doc issue.
**Checklist:**
- [ X ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-t …

docs: Fix environment variables names

---

.github/workflows/kubeflow-pipelines-manifests.yml
manifests/kustomize/hack/presubmit.sh

Moved `kubeflow-pipelines-manifests` to GitHub Actions.
Resolves #[11051](https://github.com/kubeflow/pipelines/issues/11051)
**Implementation Notes**
-  Removed installation for kustomize and installed 5.2.1 version as it comes with 5.4.3 version in google-github-actions/setup-gcloud@v2:latest
-  Added a step to install kpt as its not available in google-github-actions/setup-gcloud@v2:latest
**PR to update GoogleCloudPlatform/oss-test-infra**
- https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2336
**Checklist:**

test: Moved kubeflow-pipelines-manifests to GitHub Actions

---

.github/workflows/e2e-test.yaml

Fix for #10885
In this case, the fail_op task fails as intended, and the ExitHandler task is executed afterward to handle the exit. The log entry "Exit handler has worked!" confirms that the ExitHandler worked as expected after the failure.
It is the "fail" log from the fail-ops task that indicates that the task performed as expected:
As a result of this failure, we were able to obtain the following result:
"message": "Exit handler has worked!"

fix: re-enable exit hanler test.

---

frontend/server/configs.ts
frontend/server/handlers/pod-logs.ts
frontend/server/workflow-helper.test.ts
frontend/server/workflow-helper.ts
frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
frontend/src/lib/Apis.test.ts
frontend/src/lib/Apis.ts
frontend/src/pages/RunDetails.test.tsx
frontend/src/pages/RunDetails.tsx

This PR solves https://github.com/kubeflow/pipelines/issues/10036 by making it possible to inject the AWF `keyFormat`, which determines where archived workflow container logs are saved, into the UI via `configs.ts` / env vars so that the UI retrieves them from the correct location.
Currently, for v2, the UI is looking in the wrong object store path (which is hard-coded) and coming up empty. We could update the hard-coded path, but loading it from `configs.ts` makes it more future proof and flexible in case end users want to modify the `keyFormat` for any reason.
This is an interim solution that's still a huge improvement over the current state of affairs (logs are inaccessible in v2 once the AWF CR has been GCed), but it has two important drawbacks that we …

fix(frontend): retrieve archived logs from correct location

---

backend/Dockerfile

added check in build-images.sh to check if the build has failed then kill the process with error.
fix https://github.com/kubeflow/pipelines/issues/11102

test: Fail fast when image build fails on tests #11102

---

backend/Makefile

Add image_driver and image_launcher targets to backend Makefile (and add to image_all as well)
**Checklist:**

chore: Add make targets for building driver and launcher images

---

backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
backend/third_party_licenses/apiserver.csv
backend/third_party_licenses/driver.csv
go.mod
go.sum
kubernetes_platform/python/kfp/kubernetes/__init__.py
kubernetes_platform/python/kfp/kubernetes/empty_dir.py
kubernetes_platform/python/test/snapshot/data/empty_dir_mounts.py
kubernetes_platform/python/test/snapshot/data/empty_dir_mounts.yaml
kubernetes_platform/python/test/unit/test_empty_dir_mounts.py

Update kfp backend and kubernetes sdk to support mounting EmptyDir volumes to task pods.
(Based on #10892 and needs rebase after that is merged first)
Inspired by #10427
Fixes: #10656
**Checklist:**

feat(Backend + SDK): Update kfp backend and kubernetes sdk to support EmptyDir

---

backend/src/v2/metadata/client.go

This PR wraps the `Failed GetContextByTypeAndName` error for better troubleshooting.
```
F0814 12:59:37.779133      17 main.go:81] KFP driver: driver.RootDAG(pipelineName=iris-training-pipeline, runID=362fd86b-1b90-45d3-a2be-bb16b498055a, runtimeConfig, componentSpec) failed: Failed GetContextByTypeAndName(type="system.Pipeline", name="iris-training-pipeline")
```
```
F0814 13:20:09.099942      18 main.go:81] KFP driver: driver.RootDAG(pipelineName=iris-training-pipeline, runID=2beffed7-7680-4f2f-b531-1b7a6bf7c7b8, runtimeConfig, componentSpec) failed: Failed GetContextByTypeAndName(type="system.Pipeline", name="iris-training-pipeline"): rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: …
```

chore: Wrapped "Failed GetContextByTypeAndName" error for better troubleshooting

---

.github/workflows/backend.yml
.github/workflows/e2e-test.yml
.github/workflows/kfp-kubernetes-execution-tests.yml
.github/workflows/kfp-samples.yml
.github/workflows/kubeflow-pipelines-integration-v2.yml
.github/workflows/periodic.yml
.github/workflows/sdk-execution.yml
.github/workflows/upgrade-test.yml
scripts/deploy/github/deploy-kfp-tekton.sh
scripts/deploy/github/deploy-kfp.sh
scripts/deploy/github/helper-functions.sh
scripts/deploy/github/kfp-readiness/wait_for_pods.py

This PR replaces the bash function that checks the readiness of the KFP deploy with a Python script that relies on the Kubernetes API.
Resolves: https://github.com/kubeflow/pipelines/issues/11160
Resolves: https://github.com/kubeflow/pipelines/issues/11161
**Checklist:**

test: Improvements to wait_for_pods function

---

frontend/src/pages/ResourceSelector.tsx
frontend/src/pages/__snapshots__/ResourceSelector.test.tsx.snap

fixes filter pipeline text box shows error when typing anything in it.
fix for issue #10241.
just did small change to use the V2 code instead the V1

fix(frontend): fixes filter pipeline text box shows error when typing anything in it. Fixes #10241

---

frontend/server/app.ts
frontend/server/configs.ts
frontend/server/handlers/artifacts.ts
frontend/server/integration-tests/artifact-get.test.ts
frontend/server/minio-helper.ts
manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml

Resolves: https://github.com/kubeflow/pipelines/issues/11058
This change allows KFP UI to fallback to UI host namespace when no namespaces are provided when referencing the artifact object store provider secret, in default kubeflow deployments this namespace is simply "kubeflow", however the user can customize this behavior by providing the environment variable "SERVER_NAMESPACE" to the KFP UI deployment.
Further more, this change addresses a bug that caused URL parse to fail when parsing endpoints without a protocol, this will support such endpoint types as <ip>:<port> for object store endpoints, as is the case in the default kfp deployment manifests.

correct artifact preview behavior in UI

---

.github/pull_request_template.md

Added the DCO link to the PR template.
**Checklist:**

chore: Added DCO link to PR template

---

RELEASE.md

chore: Add instructions for releasing driver and launcher images

---

sdk/runtime_tests/execute_commands_args_test.py

Fixes: https://github.com/kubeflow/pipelines/issues/11156
[Tests passing on my branch after a push](https://github.com/hbelmiro/data-science-pipelines/commit/6e713d2b6f96a443c2a8bfc0e04bc973aab5c9ee):
**Checklist:**

test: Fixed `kfp-runtime-tests` to run on master branch

---

backend/src/v2/component/launcher_v2.go
backend/src/v2/driver/driver.go

Resolves: https://github.com/kubeflow/pipelines/issues/11168
As mentioned in the issue above, there is also an unnecessary call to emissary which should have been removed once we upgraded to the Argo version that supported adding emissary calls to podspecpatches (as per the inline todo comments). This change addresses that as well as a separate commit. 
Before: 
After: 
**Checklist:**

(fix): reduce executor logs

---

sdk/python/kfp/client/client.py
sdk/python/kfp/client/client_test.py
sdk/python/requirements.in
sdk/python/requirements.txt

The Python generated code for kfp-server-api had changes in service method name from 2.0.5 to 2.1.0:
Updating the client code to adopt the changes. 
**Checklist:**

feat(sdk)!: Pin kfp-pipeline-spec==0.4.0, kfp-server-api>=2.1.0,<2.4.0

---

backend/src/apiserver/config/config.json
backend/src/cache/server/mutation.go
backend/src/cache/server/mutation_test.go
manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml
manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
manifests/kustomize/base/installs/generic/postgres/pipeline-install-config.yaml
samples/core/resource_ops/resource_ops.py
samples/test/placeholder_concat.py
samples/test/placeholder_if.py
samples/test/placeholder_if_v2.py

Resolve: https://github.com/kubeflow/pipelines/issues/10615#issuecomment-2315801652 
I didn't do any manual test, but seems like a safe change. There is effectively no difference between these images: 
```bash
~ $ podman image diff --format json registry.k8s.io/busybox gcr.io/google-containers/busybox
{}
~$ podman image diff --format json registry.k8s.io/busybox k8s.gcr.io/busybox
{}
```
This change was applied via a sed replace like manner.

replaced deprecated image repos with registry.k8s.io

---

kubernetes_platform/python/README.md
kubernetes_platform/python/docs/conf.py

The entry page for kfp-kubernetes was a little lacking. Clean it up a bit.
**Checklist:**

chore(docs): clean up kfp-kubernetes documentation index page

---

frontend/src/pages/RunDetails.tsx
frontend/src/pages/RunDetailsRouter.tsx

This PR addresses [#10590](https://github.com/kubeflow/pipelines/issues/10590). V1 Run details were unexpectedly reloading when users navigated away from the page.
This is because the loading state is derived from a query that happens in `RunDetailsRouter.tsx`, which then determines whether to show the loading message or `RunDetails.tsx`. When the loading state occurs, the `RunDetails` component is unmounted because of this condition.
To address this issue, I have established a prop for `EnhancedRunDetails` called `isLoading`. This prop is derived from the same query as before, but the condition is now leveraged within the render method of the `RunDetails` component itself, therefore preventing the component from unmounting.
**Checklist:**

fix(ui): Fixes V1 Run detail unnecessary reloading. Fixes #10590

---

frontend/src/pages/NewRunSwitcher.tsx

Fixes #10897.
i found that whenever a V2 pipeline is chosen for a new run, then there is a check whether v1Template is fetching and because it is not a v1 pipeline then the message is seen for long time.
so basically what i did is check whether the v1 template is fetching only when the pipeline is v1 and not v2, which cause in significant reduce in the loading time.

fix(frontend): first time choosing a pipeline definition is VERY slow. Fixes #10897

---

sdk/python/test_data/pipelines/xgboost_sample_pipeline.py
sdk/python/test_data/pipelines/xgboost_sample_pipeline.yaml

This PR is also reverting the files deletion that are required to run CI tests.
**Checklist:**

chore: fix CI by adding a dependency of python/sdk for the e2e-test

---

.pre-commit-config.yaml
backend/src/apiserver/visualization/types/tfdv.py
components/aws/athena/query/src/query.py
components/google-cloud/google_cloud_pipeline_components/container/v1/aiplatform/remote_runner.py
components/google-cloud/google_cloud_pipeline_components/v1/hyperparameter_tuning_job/component.py
proxy/get_proxy_url.py
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/deprecated/compiler/v2_compatible_compiler_test.py
sdk/python/kfp/deprecated/components/type_annotation_utils.py
sdk/python/kfp/deprecated/components_tests/test_python_op.py
sdk/python/kfp/deprecated/dsl/_ops_group.py
sdk/python/kfp/dsl/executor.py
sdk/python/kfp/dsl/for_loop.py
sdk/python/kfp/dsl/placeholders_test.py
sdk/python/kfp/dsl/tasks_group_test.py
sdk/python/kfp/dsl/types/type_annotations.py
sdk/python/kfp/local/config_test.py
test/sample-test/sample_test_launcher.py
test/sample-test/unittests/utils_tests.py

This PR fixes SyntaxError issues in Python3.12 and deprecations in previous versions.
In python3.12, using escape sequences outside of raw strings has been [moved from a deprecation warning into a syntax error](https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes). As such, I've added a linter to track down cases where we still have this issue and fixed all said reported issues.
<details>
<summary>The original list was as follows:</summary>
```
backend/src/apiserver/visualization/types/tfdv.py:78:122: W605 invalid escape sequence '\/'
components/aws/athena/query/src/query.py:66:42: W605 invalid escape sequence '\/'
components/google-cloud/google_cloud_pipeline_components/container/v1/aiplatform/remote_runner.py:91:44: W605 invalid escape …
```

refactor: fix invalid escape sequences

---

.github/workflows/kubeflow-pipelines-integration-v2.yml

This PR fixes the kubeflow-pipelines-integration-v2 based on the [original prow job](https://github.com/GoogleCloudPlatform/oss-test-infra/commit/bf9dccfc18d00feaca019333775194d027ba6cc1#diff-30095b445aa0ad17f1bc23514587283b5ad03959f815fb48e42bdeee2b39c066).
**Checklist:**

test: Fixed kubeflow-pipelines-integration-v2 workflow

---

sdk/python/kfp/cli/cli_test.py
sdk/python/kfp/cli/compile_.py
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/dsl/base_component.py
sdk/python/kfp/dsl/pipeline_context.py
sdk/python/kfp/dsl/pipeline_task.py

Allow setting a default of execution caching disabled via a compiler CLI flag and env var.
Resolves https://github.com/kubeflow/pipelines/issues/11092
CLI Update (kfp dsl compile):\
A new flag `--disable-execution-caching-by-default` is added. When set, this flag disables caching for all pipeline tasks by default. Behavior specified in pipeline code still takes precedence.
A corresponding Environment Variable `KFP_DISABLE_EXECUTION_CACHING_BY_DEFAULT` is added as well.
By default, tasks default to caching enabled if the pipeline code doesn't specify a desired behavior via set_caching_options. For example:
```
@dsl.pipeline(name='my-pipeline')
task_1 = create_dataset()
task_2 = create_dataset()
task_1.set_caching_options(False)
```
In …

feat(sdk): Allow disabling default caching via a CLI flag and env var

---

.github/workflows/rerun-pr-jobs.yml

This PR sets a pinned version for `estroz/rerun-actions`.
**Checklist:**

chore: pinned estroz/rerun-actions version

---

backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/apiserver/server/fakes_test.go
backend/src/apiserver/server/pipeline_upload_server_test.go

Fixes #10509 
The PipelineSpec definition is currently stored in two places, DB and ObjStore, creating the potential for a competing source-of-truth problem.  The ObjStore copy doesn't appear to actually be used/retrieved anywhere, so remove it from the list of responsibilities
**Checklist:**

feat(backend): Remove PipelineSpec Template storage from ObjStore responsibilies. Fixes #10509

---

backend/src/v2/driver/driver.go

In driver, random string is added when uri paths for output artifacts are generated. This should ensure that when component of certain name is executed in parallel (either with ParallelFor or just simply calling it multiple times in @pipeline), its outputs are always stored to different paths.

fix(backend): randomizing output uri path to avoid overwriting. Fixes #10186

---

backend/src/apiserver/server/experiment_server_test.go

Address failing backend unit tests introduced from: https://github.com/kubeflow/pipelines/commit/374b18bc3366a51f4b92821cdb3a942bc12343a0
This snuck in since the pr wasn't rebased.

correct lastrun unittest timestamps

---

kubernetes_platform/python/RELEASE.md

chore(doc): Update kfp-kubenetes release instructions.

---

scripts/deploy/github/build-images.sh
scripts/deploy/github/deploy-kfp.sh
scripts/deploy/github/kfp-readiness/wait_for_pods.py

This PR is an MVP which gets the images built and deployments patched to use those images. **The PR is intended to be iterated on with more formalization / improvement in the future** while also getting testing working in the meantime. This addition is related to #11239, but also makes changes related to `apiserver`, `persistenceagent`, and `scheduledworkflow` images, more discussion will be added to that issue.
The PR primarily modifies the scripts in `scripts/deploy/github/` which are used by the [GitHub action here](https://github.com/CarterFendley/pipelines/blob/627a3dbb7e5f0758877fb3b4681e59a88fe3b840/.github/actions/kfp-cluster/action.yml). The `kubectl patch` command is used to patch deployment images, and `kubectl set env` to modify environment variables.
**Other changes**
Some …

feat(workflows): use built images in Github workflows

---

.github/workflows/add-ci-passed-label.yml
.github/workflows/ci-checks.yml

-  Introduced a GitHub Action workflow to validate the successful completion of all CI checks.
-  Automatically adds a ```ci-passed``` label once all CI checks have passed.
-  Removes the ```ci-passed``` label when the pull request is either synchronized or reopened.
**PR to update GoogleCloudPlatform/oss-test-infra**
https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2392
**Checklist:**

test: Integrate Git Hub Action Results into Tide

---

api/v2alpha1/pipeline_spec.proto

Add two fields in SinglePlatformSpec: platform and config.
This will be used by Platform Specifc features and currently used by Vertex Preflight validations.
**Checklist:**

feat: add fields in SinglePlatformSpec

---

.github/workflows/add-ci-passed-label.yml
.github/workflows/ci-checks.yml

-  Increased the retry count to support long-running tests.
- Added a label check to ensure the ci-check runs only when the ```needs-ok-to-test``` label is absent.
- The workflow is triggered when the ```ok-to-test``` label is present.

test: Resolve ci-check failures in long-running CI tests

---

test/presubmit-tests-sdk.sh

Resolves the failing KFP SDK Tests -https://github.com/kubeflow/pipelines/actions/runs/11351867593/job/31573385411
-  Used python virtual environment to install python packages in the test.
**Checklist:**

test: Fix failing SDK tests by creating Python virtual environment

---

.github/workflows/add-ci-passed-label.yml.disabled
.github/workflows/ci-checks.yml.disabled

This PR disables the ci-check and add-ci-passed-label workflows since their lack of stability.
**Checklist:**

test: Disabled ci-check and add-ci-passed-label workflows.

---

frontend/src/pages/NewRunV2.tsx
frontend/src/pages/functional_components/NewExperimentFC.tsx

feat(frontend): add create experiment button when selecting experiment. Fixes https://github.com/kubeflow/pipelines/issues/5737

Add-Create-Experiment-button-when-selecting-experiement-final

---

components/google-cloud/RELEASE.md
sdk/python/kfp/dsl/component_decorator.py
sdk/python/kfp/dsl/component_factory.py
sdk/python/test_data/components/component_with_pip_install_in_venv.py
sdk/python/test_data/components/component_with_pip_install_in_venv.yaml

This commit introduces the ability to run the component inside a virtual environment, which is particularly useful when the Python system site package directory is read-only, causing pip to fail during the installation of kfp and other dependencies.
To bypass this issue, a writable temporary directory is selected to create a virtual environment that inherits the global system site packages. The entire workflow is then executed from within this virtual environment.
Furthermore, a new field, `use_venv`, has been added to the component decorator, with a default value of `False`.
Signed-off-by: Sébastien Han <seb@redhat.com>
**Checklist:**

feat(component): execute in a virtual env

---

sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/component_factory.py
sdk/python/kfp/dsl/graph_component.py
sdk/python/kfp/dsl/pipeline_config.py
sdk/python/kfp/dsl/pipeline_context.py

KFP v1 supported setting pipeline-level configuration via a `PipelineConf` class. This class was deprecated and no replacement was added to KFP v2.
Add new PipelineConfig class to support setting pipeline-level configuration in KFP v2.
Note: I discussed this approach with @chensun in the KFP Community meeting on August 14 ([agenda](https://bit.ly/kfp-meeting-notes), [recording](https://drive.google.com/file/d/1LmpNI6sJAcFZEj1-F2kl_s3BlkiP1v_i/view?usp=sharing&resourcekey=0-wxEZBbugQhoDerN0eXuWiw)). He gave preliminary approval for this approach.
[Here's an example](https://github.com/kubeflow/pipelines/pull/11113) of how it would be used.
Followup to #11333.
**Checklist:**

feat(sdk): add PipelineConfig to DSL to re-implement pipeline-level config

---

backend/src/apiserver/server/api_converter.go
backend/src/apiserver/server/job_server_test.go

Fixes a small typo in error text for max concur out of range error, and related test
**Checklist:**

chore(backend): typo in max concurrency error text

---

backend/src/v2/cmd/driver/main.go
backend/src/v2/component/launcher_v2.go
backend/src/v2/driver/driver.go
backend/src/v2/metadata/client.go
backend/src/v2/metadata/client_fake.go
backend/src/v2/metadata/client_test.go
backend/src/v2/objectstore/object_store.go
samples/v2/sample_test.py
samples/v2/subdagio/__init__.py
samples/v2/subdagio/artifact.py
samples/v2/subdagio/artifact_cache.py
samples/v2/subdagio/mixed_parameters.py
samples/v2/subdagio/multiple_artifacts_namedtuple.py
samples/v2/subdagio/multiple_parameters_namedtuple.py
samples/v2/subdagio/parameter.py
samples/v2/subdagio/parameter_cache.py
samples/v2/subdagio/parameter_oneof.py
sdk/python/kfp/compiler/pipeline_spec_builder.py

This PR:
- Implements input resolution for outputs that come from (multiple layers of) nested DAGs. Without this, the usefulness of pipelines as components is severely compromised. This is achieved by recording the relationship between DAGs and their producer subtasks in MLMD as custom properties, which are consumed and resolved downstream by `resolveInputs` in `driver.go`.
- Begins functional decomposition in `driver.go`, paving the way for small tests.
- Implements extensive large test cases to validate the many different scenarios. The full set of test cases is summarized in a table below. These test cases are not incorporated into CI yet but will be once #11239 is resolved.
- Implements extensive, togglable debug level logs throughout the driver and …

feat(backend): implement subdag output resolution

---

manifests/kustomize/base/installs/multi-user/istio-authorization-config.yaml

This upstreams our changes in https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/base/installs/multi-user/istio-authorization-config.yaml for oauth2-proxy in Kubeflow 1.9/1.9.1. It is an exact copy of the file and must be included in the next KFP release or it will break our synchronization scripts at https://github.com/kubeflow/manifests/blob/master/hack/synchronize-kubeflow-manifests.sh. for the 1.10 release.
closes https://github.com/kubeflow/manifests/issues/2804
@HumairAK @rimolive @kimwnasptd

chore: upstream our authorization changes for oauth2-proxy

---

.github/workflows/add-ci-passed-label.yml

-  This PR addresses the issue with adding ci-passed label during PR Synchronization. Reference PR [#11354](https://github.com/kubeflow/pipelines/pull/11354)
-  The issue was caused by the parallel execution of the ```reset_ci_passed_label``` and ```add_ci_passed_label``` steps in the "Add CI Passed Label" GitHub Action workflow.
-  The workflow has been updated to execute the ```reset_ci_passed_label``` and ``add_ci_passed_label`` steps sequentially, ensuring that the ci-passed label is correctly added on PR synchronization.
**Checklist:**

test: Fix ci-passed label update on PR synchronization

---

backend/Dockerfile
backend/Dockerfile.cacheserver
backend/Dockerfile.conformance
backend/Dockerfile.driver
backend/Dockerfile.launcher
backend/Dockerfile.persistenceagent
backend/Dockerfile.scheduledworkflow
backend/Dockerfile.viewercontroller

This PR modifies the Dockerfiles to download dependencies earlier. That way the download layers can be cached and subsequent builds will be faster when dependencies don't change.
**Checklist:**

chore: Added cached layer for Go dependencies to Dockerfiles

---

sdk/RELEASE.md
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/test_data/components/output_metrics.yaml
sdk/python/test_data/pipelines/lightweight_python_functions_with_outputs.yaml
sdk/python/test_data/pipelines/pipeline_with_metrics_outputs.yaml

The auto-population of metrics artifact was a comprised workaround to enable Vertex run comparison feature with only client side changes. 
This causes unintentional behaviors. And with the introduction of loop aggregation, this becomes more problematic when it tries to aggregate and surface out large number of metrics artifacts. 
**Checklist:**

feat(sdk)!: stop auto-populating metrics as dag output

---

sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml

In [this](https://github.com/kubeflow/pipelines/pull/11075/files#diff-10e2c4a2ff87025a7653623f21bfe47a39844ba69f8117b4d82d8902ae5893ddR776-R782) PR, new API fields were introduced to set accelerator resources via pipeline spec. Note that `type` and `count` were deprecated. However in the follow up implementation pr [here](https://github.com/kubeflow/pipelines/pull/11097/files#diff-42a6e18d166f33d4a0992ab9609966d24389846045972a99e9f286bba08d4014R665-R668) we can see that these fields are removed entirely from the compilation step. This has basically broken setting accelerator types in KFP, because [the driver is expecting](https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/driver/driver.go#L449-L457) `type` and `count` to be present, and these are thus not being set at all. …

fix(sdk): accelerator type setting in kfp

---

backend/src/common/util/pipelinerun.go

minor enhancment:
[pipelinerun](https://github.com/kubeflow/pipelines/blob/master/backend/src/common/util/pipelinerun.go#L50) is wrapper around the Tekton client.
Removed mentions of  Agro Workflow for avoiding confusing

chore(backend): remove mentions of Argo Workflows from the pipelinerun

---

frontend/server/configs.ts
frontend/server/handlers/pod-logs.ts
frontend/server/k8s-helper.ts
frontend/server/workflow-helper.test.ts
frontend/server/workflow-helper.ts
manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml

Argo Workflows supports the ability to specify an artifact repository for archived logs uniquely for each namespace rather than just globally as documented [here](https://argo-workflows.readthedocs.io/en/latest/configure-artifact-repository/).
This PR adds support for this functionality to the KFP UI. If a workflow runs and...
1. The corresponding pods are deleted
2. The corresponding workflow is deleted
3. There is an `artifact-repositories` configmap in the target namespace that provides a unique, namespaced `keyFormat`
...this PR ensures that logs are still accessible in the UI. This functionality is disabled by default to avoid unnecessary network calls (for end users who don't leverage namespace-specific `artifact-repositories`). It can be toggled on …

feat[frontend]: implement artifact-repositories configmap support

---

sdk/RELEASE.md
sdk/python/kfp/cli/cli.py

This PR exposes `existing_token` option of `kfp.Client` to the CLI.
Resolves: https://github.com/kubeflow/pipelines/issues/11399
**Checklist:**

feat(cli): expose existing_token client property

---

backend/metadata_writer/requirements.txt
backend/metadata_writer/src/metadata_writer.py

* Handles client side timeouts (`urllib3.exceptions.ReadTimeoutError`) of `k8s_watch.stream` to prevent crashes of `metadata-writer` pod. Without this `metadata-writer` pod fails in cases when a connection error causes a client timeout. This should fix #8200.
* Adjusts the client side timeout according to [the recommendations of Kubernetes Python client authors](https://github.com/kubernetes-client/python/blob/master/examples/watch/timeout-settings.md). 
>It is recommended to set this [server] timeout value to a higher number such as 3600 seconds (1 hour).
>It is recommended to set this [client] timeout value to a lower number (for eg. ~ maybe 60 seconds).
* The benefit of this for the `metadata-writer` use case is that, currently, with a client side …

fix(backend): handle client side HTTP timeouts to fix crashes of metadata-writer. Fixes #8200

---

.dockerignore

Since [we're copying all files into the images](https://github.com/kubeflow/pipelines/blob/9ccec4c7d1aff4d2bfdb20cf4fd1f9d64b8632f4/backend/Dockerfile#L27), when we change anything in a Dockerfile, the container engine invalidates the cached layer at the `COPY . .` point. That makes subsequent builds unnecessarily long having to copy and build everything again, even when no source code was changed.
This PR adds Dockerfiles to `.dockerignore` so they are ignored when running `COPY . .`. That way we leverage the existing caches when no source code was changed.
**Checklist:**

chore: Added Dockerfiles to .dockerignore

---

frontend/server/app.test.ts
frontend/server/configs.ts
manifests/kustomize/env/gcp/gcp-configurations-patch.yaml

-  UI presents errors when deployed outside GKE as pointed in #11260.
- _DISABLE_GKE_METADATA_ was set true as default and patched for GKE environments
- Tests were also adjusted
Fixes: #11247 & #11260
Duplicated from #11321 to include tests.
**Checklist:**

fix(ui): Disable GKE Metadata as default Fixes: #11247, fixes #11260 

---

.github/workflows/ci-checks.yml

This change will ensure that CI check wf always uses the one in the base repository. Read more about it [here](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target).

chore: have ci check run from default branch

---

.github/workflows/pr-commands.yml

This is a workflow that, when a user comments on a pr it will do the following: 
1. If the comment is `/ok-to-test` it will: 
* Check if the user is a member or owner of the org, 
* if they are, then it will approve any pending runs for this PR 
* if they are not, nothing happens, a comment is left on the pr notifying the user of the requirements
2. If the comment is not '/ok-to-test` the workflow will not schedule a job, but will still show up under Actions for the repo
3. Because we use issue_comment trigger, it can be triggered on issue comments as well, if a user does `/ok-to-test` on an issue, then the workflow fails silently 
The workflow is written to be extendible to other commands as the need arises. It's a very simple workflow, and in the future …

chore: add workflow to approve pr runs

---

backend/src/v2/driver/driver.go

The `return` statement was missing when `id == 0`.
e26d3ec5e fix(backend): return error properly
commit e26d3ec5ed06aa13cfdf6a45234945ac04634969
Author: Sébastien Han <seb@redhat.com>
Date:   Mon Dec 2 11:42:49 2024 +0100
fix(backend): return error properly
The `return` statement was missing when `id == 0`.
Signed-off-by: Sébastien Han <seb@redhat.com>
**Checklist:**

fix(backend): return error properly

---

sdk/RELEASE.md
sdk/python/kfp/cli/component.py
sdk/python/kfp/cli/component_test.py

Fixes #11164  by adding error handling for image build/push failures in the KFP SDK. Now, errors trigger a clear error message and a non-zero exit code, ensuring accurate feedback to users.
**Checklist:**

fix(sdk): Add error handling. Fixes #11164

---

backend/src/v2/driver/driver.go

5bb5a6005 fix(backend): remove unused function argument
commit 5bb5a60057112b189ba0536a181ce20781c44fa3
Author: Sébastien Han <seb@redhat.com>
Date:   Mon Dec 2 15:07:30 2024 +0100
fix(backend): remove unused function argument
`outputDefinitions` has not been used since
`collectOutPutParametersFromCache()` was removed in
0be57c38802b85d0b09b703e60b1b3131a1b9863.
Signed-off-by: Sébastien Han <seb@redhat.com>
**Checklist:**

fix(backend): remove unused function argument

---

.github/workflows/pr-commands.yml

chore: Fix pr-commands.yml to enable /ok-to-test alongside other commands

---

sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml

Introduced back the functions to convert k8s size values to float, but moved to kfp.dsl.utils
fixes #11390 
**Checklist:**

fix(sdk): Backport fixes in kubeflow/pipelines#11075

---

backend/src/v2/compiler/argocompiler/argo_test.go
backend/src/v2/compiler/argocompiler/dag.go
backend/src/v2/compiler/argocompiler/testdata/multiple_parallel_loops.yaml
backend/src/v2/compiler/testdata/multiple_parallel_loops.json

Fixes #8718
Adds the `Parallelism` item to a DAG template if specified by a task's IteratorPolicy (ie ParallelFor w/ a parallelism limit).
**Checklist:**

feat(backend): Add Parallelism Limit to ParallelFor tasks. Fixes #8718

---

backend/src/v2/driver/driver.go
backend/src/v2/driver/util.go
backend/src/v2/driver/util_test.go
sdk/RELEASE.md
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/dsl/pipeline_task.py

Resolves #11391 
This change allows component base images to be parameterized using runtime pipeline parameters. The container images can be specified within an @pipeline decorated function, and takes precedence over the @component(base_image=..) argument.
This change also adds logic to resolve these runtime parameters in the argo driver logic. It also includes resolution steps for resolving the accelerator type which functions the same way but was missing the resolution logic. The resolution logic is a generic workaround solution for any run time pod spec input parameters that cannot be resolved because they cannot be added dynamically in the argo pod spec container template.
**Checklist:**

feat(sdk/backend): enable parameterization of container images

---

api/v2alpha1/pipeline_spec.proto
api/v2alpha1/python/setup.py

Introduce cache_key for cache key customization for issue #11328 
Doc: https://docs.google.com/document/d/1oNgYyFYondaVSFf9Pd3Q9uVzaqBr5wrOMHKgX9MMa78/edit?tab=t.0
**Checklist:**

feat: Introduce cache_key for cache key customization

---

CONTRIBUTING.md
adrs/KFP-ADR-0001-use-architecture-decision-records-for-kfp.md
adrs/OWNERS
adrs/README.md
adrs/template.md

This PR adds a new directory for storing future ADRs for KFP. 
I propose we start following this method of recording new architecture decisions that are made in KFP. Please see the first architecture doc around the benefits of this approach, and the decision making process around it. 
Historically it has been very difficult to keep track of how decisions have been made on the project, for example things like V2, IR, decision to add Tekton, etc, are all in docs that are not hollistically tracked anywhere, and it's not clear exactly who owns them. This is an attempt to improve this process. 
**Checklist:**

chore: add adr template/docs

---

backend/src/apiserver/client/argo.go
backend/src/apiserver/client/swf.go
backend/src/apiserver/client/util.go
backend/src/cache/client/kubernetes_core.go
backend/src/common/util/execution_client.go
backend/src/common/util/service.go
backend/src/v2/driver/driver.go

This makes it so that the API server will first try the in-cluster configuration and fallback to a kubeconfig. This is helpful when the API server is running outside of the cluster (e.g. locally) so you don't need to create token files.
**Checklist:**

fix(backend): Allow initializing the Kubernetes client with a kubeconfig

---

sdk/python/requirements.in
sdk/python/requirements.txt

chore(sdk): Upgrade kfp-pipeline-spec to 0.6.0 (#11434)
**Checklist:**

chore(sdk): Upgrade kfp-pipeline-spec to 0.6.0 (#11434)

---

.github/actions/kfp-cluster/action.yml
.github/workflows/e2e-test.yml

[From Kubeflow 1.10, all components must support 3 versions of Kubernetes](https://github.com/kubeflow/community/issues/767#issuecomment-2512189405). This PR adds versions 1.30 and 1.31 of Kubernetes to KFP end-to-end tests. With that, KFP supports Kubernetes from 1.29 to 1.31.
**Checklist:**

chore: Added Kubernetes 1.30 and 1.31 to e2e tests

---

.github/workflows/kfp-samples.yml
.github/workflows/upgrade-test.yml
.gitignore
backend/Makefile
backend/README.md
manifests/kustomize/env/dev-kind/forward-local-api-endpoint.yaml
manifests/kustomize/env/dev-kind/kustomization.yaml
tools/kind/kind-config.yaml

This provides instructions to provision a kind cluster with all components deployed except for the API server. The API server can then be run locally through VSCode for debugging and fast development.
**Checklist:**

chore: Add instructions to develop the API server locally with kind

---

.github/workflows/kfp-kubernetes-execution-tests.yml
.github/workflows/periodic.yml
.github/workflows/sdk-execution.yml

For some reason, my IDE didn't find all the occurrences of `.github/actions/kfp-cluster` when I sent https://github.com/kubeflow/pipelines/pull/11450.
This PR is a follow-up of https://github.com/kubeflow/pipelines/pull/11450.
**Checklist:**

chore: Added Kubernetes 1.30 and 1.31 to other tests

---

samples/test/README.md
sdk/python/test_data/README.md
test/README.md
test/kfp-functional-test/README.md

- Remove obsolete information related to Prow tests, and gcloud dependency, since we've moved to GH Action Workflows/ Kind.
- Add details related to the newly added GHA workflows and how to replicate them locally/manually using Kind clusters.
Resolves https://github.com/kubeflow/pipelines/issues/11061
**Checklist:**

chore: Update test READMEs to reflect correct information on testing workflows

---

manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml

Based on [this](https://github.com/metacontroller/metacontroller/releases/tag/v4.11.21) release the docker image of the metacontroller is being deprecated and need to be updated.
**Checklist:**

chore: Update image for metacontroller 

---

backend/src/apiserver/model/cron_schedule.go
backend/src/apiserver/model/job.go
backend/src/apiserver/model/periodic_schedule.go
backend/src/apiserver/template/template.go

This PR fixes the issue where `CronSchedule` and `PeriodicSchedule` structs were incorrectly evaluated as non-empty even when their fields were all nil. The issue arose because direct struct comparison with `(CronSchedule{})` or `(PeriodicSchedule{})` does not account for the semantics of pointer fields being `nil`, `""` or `0`.
**Checklist:**

fix(backend): modelToCRDTrigger was not including periodic schedule correctly

---

manifests/kustomize/base/cache/cache-deployment.yaml
manifests/kustomize/base/metadata/base/metadata-envoy-deployment.yaml
manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml
manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml
manifests/kustomize/third-party/minio/base/minio-deployment.yaml
manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml

upstream what we have in https://github.com/kubeflow/manifests/tree/master/contrib/security/PSS to make PSS enforcable
and enjoy a rootless Kubeflow https://github.com/kubeflow/manifests/issues/2528
**Checklist:**

chore:  Add securitycontext for PSS PoC (rootless Kubeflow)

---

.github/workflows/kfp-sdk-tests.yml
test/presubmit-tests-sdk.sh

SDK Tests have been broken since December 18th.
https://github.com/kubeflow/pipelines/actions/runs/12399881929/job/34615777065
This PR fixes that.
**Checklist:**

test: fixes SDK tests

---

.github/workflows/kfp-samples.yml
.github/workflows/kfp-sdk-tests.yml

SDK Tests uses a matrix function from GHA to test multiple Python versions, but these values must be added as string. This caused SDK Tests to fail because it tries to test SDK under Python 3.1 instead of Python 3.10.
**Checklist:**

chore(test): Fix SDK tests

---

backend/src/apiserver/resource/resource_manager.go

When creating recurring runs, the `ScheduledWorkflow` CR is created with no namespace set.
This PR changes the `CreateJob` method so the namespace is set in the `Job` before creating the `ScheduledWorkflow`.
**Checklist:**

chore(backend): Fixed namespace in job creation

---

backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/template/template_test.go
backend/src/apiserver/template/v2_template.go

When creating recurring runs, the ScheduledWorkflow CR is created with no ServiceAccount set.
This PR fixes that.
**Checklist:**

chore(backend): Fixed ServiceAccount in job creation

---

backend/src/apiserver/client/scheduled_workflow_fake.go
backend/src/apiserver/list/list.go
backend/src/apiserver/list/list_test.go
backend/src/apiserver/main.go
backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go

Resolves: https://github.com/kubeflow/pipelines/issues/11296
This PR changes apiserver to patch existing `ScheduledWorkflow` CRs for each `Job` on startup to reflect the current KFP version deployed.
1. Create recurring runs
2. Make sure the recurring runs are running
3. Patch their `swf` CRs to force failures
3.1 Get the `swf` CRs
```shell
kubectl get swf
NAME                             AGE
heya8gqgg                        27m
howdyxt5fj                       26m
runofpipelinewithconditio5zwcj   60m
```
3.2 For each `swf` patch them with an invalid workflow spec to force failures. At this point, the recurring runs will start to fail due to the invalid spec.
```shell
kubectl patch scheduledworkflow heya8gqgg --type='merge' -p '{"spec":{"workflow":{"spec":{"dynamicKey1":"dynamicValue1","dy …
```

fix(backend): Synced ScheduledWorkflow CRs on apiserver startup

---

backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
backend/third_party_licenses/apiserver.csv
backend/third_party_licenses/driver.csv
backend/third_party_licenses/launcher.csv
go.mod
go.sum
sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml

The API introduced new fields prefixed with Resource (e.g. ResourceCpuLimit) to replace the old fields without the prefix. The Driver hadn't been updated to honor those fields but the SDK started using them which led to unexpected behavior.
The Driver now honors both fields but prioritizes the new fields. The SDK now only sets the new fields.
The outcome is that resource limits/requests can now use input parameters.
Note that pipeline_spec_builder.py was doing some validation on the limits/requests being set, but that's already handled in the user facing method (e.g. set_cpu_limit).
Resolves:
https://github.com/kubeflow/pipelines/issues/11500
**Checklist:**

feat(sdk/backend): Add support for placeholders in resource limits

---

.gitignore
backend/Dockerfile.driver
backend/Makefile
backend/README.md
backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/dag.go

This makes the driver command configurable so that Delve can be used to execute the driver binary and adds Make targets to build the Driver image for debugging.
**Checklist:**

chore: Add instructions to remote debug the Driver pods

---

.github/workflows/e2e-test.yml
backend/src/v2/compiler/argocompiler/argo_test.go
backend/src/v2/compiler/argocompiler/common.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/dag.go
backend/src/v2/compiler/argocompiler/testdata/exit_handler.yaml
backend/src/v2/compiler/testdata/Makefile
backend/src/v2/compiler/testdata/exit_handler.json
test/sample-test/run_sample_test.py
test/sample-test/sample_test_launcher.py

As described in #10917, exit handlers were implemented as dependent tasks that always ran within an Argo Workflow. The issue is that this caused the pipeline to have a succeeded status regardless of if the tasks within the exit handlers all succeeded.
This commit changes exit handlers to be exit lifecycle hooks on an Argo Workflow so that the overall pipeline status is not impacted.
Resolves:
https://github.com/kubeflow/pipelines/issues/11405
**Checklist:**

fix(backend): Use an Argo Workflow exit lifecycle hook for exit handlers

---

backend/OWNERS

I would like to nominate @hbelmiro as an approver for backend. In the past year @hbelmiro has been instrumental in helping curate, review, and provide various other contributions to not just KFP as a whole but also specifically the backend subcomponent.
Some recent PRs: 
https://github.com/kubeflow/pipelines/pull/11481
https://github.com/kubeflow/pipelines/pull/11480
https://github.com/kubeflow/pipelines/pull/11469
Some example of PR reviews by @hbelmiro: 
https://github.com/kubeflow/pipelines/pull/11278
https://github.com/kubeflow/pipelines/pull/11289
https://github.com/kubeflow/pipelines/pull/11363
https://github.com/kubeflow/pipelines/pull/11368
https://github.com/kubeflow/pipelines/pull/11361
https://github.com/kubeflow/pipelines/pull/11356 …

nominate approver & reviewer for backend

---

frontend/src/pages/PipelineDetailsV2.tsx
frontend/src/pages/RunDetailsV2.tsx
frontend/src/pages/v2/DagCanvas.tsx

Fixes https://github.com/kubeflow/pipelines/issues/11325.
i changed the selection functions that are passed to DagCanvas and ReactFlow.
this is the behavior after the fix:
https://www.loom.com/share/713c1ec886e24550a1746784e4e347fe?sid=25ead37a-db5c-4f74-a334-205e2d453981

fix(frontend): Detailed information of nodes is not displayed when clicking the node. Fixes #11325

---

.github/workflows/sdk-execution.yml
sdk/python/test_data/test_data_config.yaml
test/sdk-execution-tests/sdk_execution_tests.py

The SDK execution tests were not run on the PR CI that fixed the pipeline run state to be failed even when an exit handler is run after a failed component.
This also makes the SDK execution tests run whenever the backend compiler code is modified to help prevent a similar issue.
**Checklist:**

Fix the failing exit handler SDK execution tests

---

backend/src/v2/compiler/argocompiler/container.go
manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
manifests/kustomize/base/cache-deployer/kustomization.yaml
manifests/kustomize/base/cache/cache-deployment.yaml
manifests/kustomize/base/cache/kustomization.yaml
manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/test_sync.py
manifests/kustomize/base/metadata/base/kustomization.yaml
manifests/kustomize/base/metadata/base/metadata-envoy-deployment.yaml
manifests/kustomize/base/pipeline/kustomization.yaml
manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
manifests/kustomize/env/gcp/inverse-proxy/proxy-deployment.yaml

This change switches majority of the images coming from gcr repository to the ghcr repository. For this, various manifests were updated, as well as the hardcoded launcher/driver images. All images that are regularly updated during the release process have been switched over to ghcr.
Note: I will follow up with updates to release instructions once we are done with the 2.4 release. 
**Checklist:**

chore: switch to using gh container registry in manifests

---

backend/src/v2/driver/driver.go
samples/v2/Makefile
samples/v2/pipeline_with_volume_no_cache.py
samples/v2/pipeline_with_volume_no_cache_test.py

Resolves #10188
When setting enable_caching=false, KFP Driver still tries to create the cache entry. Added a condition to ensure cache entry will only get created if enable_caching=true.
**Checklist:**

fix(backend): Fix enable_caching issues when handling PVC creation/deletion

---

backend/src/v2/README.md

The backend README.md file had the comment:
"Install sample test python dependencies (require Python 3.7 or 3.8 due to [ml-metadata limitation](https://github.com/google/ml-metadata/issues/139))"
However, visiting the link reveals this MLMD issue was resolved over a year ago. Moreover, the MLMD repository advises users that it supports Python 3.9, 3.10, and 3.11 (https://github.com/google/ml-metadata). Therefore, requiring Python 3.7 or 3.8 here is bad for a few reasons.
I have removed the comment in parentheses, as it is outdated.
**Checklist:**

fix(backend): removed old version comment

---

sdk/python/kfp/dsl/component_decorator.py

One of the parameters (`target_image`) to the `kfp.dsl.component` decorator had a word missing in the docstring, which made it confusing. This PR adds the word. 
**Checklist:**

fix(sdk): dsl.component docstring typo

---

sdk/python/requirements.in
sdk/python/requirements.txt
test/kfp-functional-test/requirements.txt

Bumps requests-toolbelt from 0.9.1 to 1.0.0 (fixes #10470)
**Checklist:**

chore: bump requests-toolbelt to 1.0.0

---

backend/src/apiserver/config/config.go
backend/src/apiserver/config/config_test.go
backend/src/apiserver/config/sample_config.json
backend/src/apiserver/config/testdata/sample_pipeline.yaml
backend/src/apiserver/main.go
backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/storage/pipeline_store.go

Resolve: https://github.com/kubeflow/pipelines/issues/11541
This change adds additional sampleconfig options that provide support for uploading new Pipelines and PipelineVersion samples. To accommodate this and backwards compatibility the structure of the samples config has been changed. Configs following the old format will continue to be supported.
Sample config code is also moved to its own file so as not to bloat main.go
In order to handle conflicts, and detecting pipeline/pipelineVersion existence, additional db queries are made per pipeline and pipeline version at apiserver startup.
**Checklist:**

feat(backend): add support for uploading new sample pipeline vers

---

README.md

This pull request fixes a minor typo in the Kubeflow Pipelines documentation. Specifically:
- The word "**reagd**" was corrected to "**read**" in the sentence: "To learn how to build and deploy Kubeflow Pipelines from source code, read the developer guide".
Ensuring the documentation is clear and free from errors is essential for improving the developer experience, especially for new contributors.
Thank you for reviewing this PR!

Fix typo in documentation for contribution and developer guide

---

backend/src/v2/README.md
samples/test/utils/kfp/samples/test/utils.py
sdk/python/kfp/cli/utils/parsing_test.py
sdk/python/kfp/client/client.py

To help users connect to KFP, the code referenced this doc link 
- https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/ which givers a 404. 
The correct link looks to be 
- https://www.kubeflow.org/docs/components/pipelines/user-guides/core-functions/connect-api/
I have updated the code to reference the correct link instead. The most important place where this needed to be fixed is in the sdk Client class docstring, since users reference this when they need help connecting.
**Checklist:**

fix: Update broken api-connect link

---

.github/workflows/e2e-test.yml
.github/workflows/upgrade-test.yml
backend/test/integration/db_test.go

This PR replaces the `${NAMESPACE}` variable with `kubeflow`.
For some reason, some tests were being skipped and started to run when I added the namespace. That required me to forward ports and change one test.
**Checklist:**

chore(test): Fixed namespace in tests

---

backend/README.md

This PR makes the following improvements to the `backend/README.md` file, which are broadly aimed at making the file more user friendly (easier to follow and clearer to understand):
1. Added an Overview section (intro) to make it more clear what the readme's purpose is.
2. Added a Prerequisites section to help people know up-front what they need. (In the future, it may be good to give even more details here, for example on versions). The `go-licences` pre-req is particularly important to building the docker image--without it users wait for the build to fail, then troubleshoot.
3. Organized content into major sections with more appropriate header levels.
4. The `Code Style` section was in the previously in the middle of the 'building and testing' …

docs(backend): improved backend README

---

.github/resources/manifests/argo/kustomization.yaml
.github/resources/manifests/tekton/kustomization.yaml
.github/resources/scripts/build-images.sh
.github/resources/scripts/kfp-readiness/wait_for_pods.py
backend/Dockerfile

The image registry was changed to GitHub Container Registry in the 2.4 release.
**Checklist:**

fix(CI): Use the correct image registry for replacements in integration tests

---

backend/src/apiserver/server/api_util_test.go
backend/src/apiserver/server/pipeline_server_test.go
backend/src/apiserver/server/util.go
backend/src/apiserver/server/util_test.go
backend/src/apiserver/server/visualization_server.go
backend/src/apiserver/template/template_test.go
backend/src/cache/server/admission.go
backend/src/common/client/api_server/util.go
backend/src/common/util/tgz.go
backend/src/v2/cmd/compiler/main.go
backend/src/v2/cmd/driver/main.go
backend/src/v2/compiler/argocompiler/argo_test.go
backend/src/v2/compiler/tektoncompiler/tekton_test.go
backend/src/v2/compiler/visitor_test.go
backend/src/v2/component/launcher_v2.go
backend/src/v2/config/env.go
backend/src/v2/objectstore/object_store.go
backend/test/integration/job_api_test.go
backend/test/integration/pipeline_api_test.go
backend/test/integration/pipeline_version_api_test.go
backend/test/integration/run_api_test.go
backend/test/integration/upgrade_test.go
backend/test/v2/integration/pipeline_version_api_test.go
backend/test/v2/integration/recurring_run_api_test.go
backend/test/v2/integration/run_api_test.go
backend/test/v2/integration/upgrade_test.go
test/tools/project-cleaner/main.go

The `ioutil` package was deprecated in go 1.16 (see [here](https://pkg.go.dev/io/ioutil)). This PR replaces it's function calls with function calls from the `os` and `io` packages (as recommended). 
**Checklist:**

chore(deps): replace deprecated ioutil with os and io in tests

---

backend/src/apiserver/resource/resource_manager_test.go
backend/src/v2/compiler/argocompiler/argo.go

Fixes: https://github.com/kubeflow/pipelines/issues/11574
**Checklist:**

fix(backend): Replaced hardcoded ServiceAccount with default config

---

frontend/README.md

resolves: https://github.com/kubeflow/pipelines/issues/11566
**Checklist:**

docs: change node version from 14 to 22 in frontend project

---

manifests/kustomize/third-party/metacontroller/base/cluster-role-binding.yaml
manifests/kustomize/third-party/metacontroller/base/cluster-role.yaml
manifests/kustomize/third-party/metacontroller/base/kustomization.yaml
manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml

This fixes the metacontroller after https://github.com/kubeflow/pipelines/pull/11474 for multi-user KFP as done in https://github.com/kubeflow/manifests/pull/2953/
@hbelmiro 
@tarekabouzeid @biswassri I did not get feedback for a week in https://github.com/kubeflow/manifests/issues/2970#issuecomment-2647615231, so I created https://github.com/kubeflow/pipelines/pull/11608 to at least fix the broken upstream KFP. Afterwards you can still upgrade metacontroller from 2.6.1 to 4.x

fix(backend): the metacontroller is broken since #11474

---

.github/workflows/kfp-sdk-tests.yml
sdk/python/kfp/cli/utils/parsing.py

Resolve #11558 
**Checklist:**

chor(test) : Fix kfp-sdk-test for different python versions

---

backend/src/apiserver/template/v2_template.go
backend/src/v2/cmd/driver/main.go
backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/dag.go
backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
backend/src/v2/compiler/argocompiler/testdata/create_pod_metadata.yaml
backend/src/v2/compiler/argocompiler/testdata/exit_handler.yaml
backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
backend/src/v2/compiler/argocompiler/testdata/importer.yaml
backend/src/v2/compiler/argocompiler/testdata/multiple_parallel_loops.yaml
backend/src/v2/driver/driver.go
samples/v2/pipeline_with_placeholders.py
samples/v2/sample_test.py
sdk/python/kfp/dsl/__init__.py

This adds support for the following placeholders in the KFP backend.
- dsl.PIPELINE_JOB_NAME_PLACEHOLDER
- dsl.PIPELINE_JOB_RESOURCE_NAME_PLACEHOLDER
- dsl.PIPELINE_JOB_ID_PLACEHOLDER
- dsl.PIPELINE_TASK_NAME_PLACEHOLDER
- dsl.PIPELINE_TASK_ID_PLACEHOLDER
Resolves:
https://github.com/kubeflow/pipelines/issues/10453
**Checklist:**

feat(backend): Add support for job and task placeholders in the KFP backend

---

backend/src/v2/cacheutils/cache.go

The go func grpc.WithInsecure() was deprecated. This replaces the deprecated code line.
**Checklist:**

chore(backend): updated deprecated grpc func

---

backend/README.md

This adds a couple of small formatting changes as a follow-up to PR #11511. The changes were suggested by @HumairAK (thanks Humair!).
**Checklist:**

docs(backend): small formatting improvements

---

developer_guide.md

The docker cmd for non-x86_64 machines in the docs was missing the path (.), and it needed the `--platform` specified. This should help devs building on Mac architectures.
**Checklist:**

docs(backend): fixed docker cmd in docs for non-amd64

---

backend/Dockerfile
backend/Dockerfile.driver
backend/Dockerfile.launcher
backend/Dockerfile.persistenceagent
backend/Dockerfile.scheduledworkflow
go.mod
go.sum

This adds a simple change to allow our CI to reference the local proto packages. This will prevent ci failures when: 
* a proto file is changed 
* code using golang proto built packages are affected by such a change
* builds fail because it's referencing the golang proto packages remotely and not the updated changes 
Instead, this pr will now reference the updated proto changes locally present within the PR itself. 
**Checklist:**

chore: use local proto go packages for ci

---

backend/Dockerfile
backend/Dockerfile.cacheserver
backend/Dockerfile.conformance
backend/Dockerfile.driver
backend/Dockerfile.launcher
backend/Dockerfile.persistenceagent
backend/Dockerfile.scheduledworkflow
backend/Dockerfile.viewercontroller
backend/Makefile
go.mod

CVE-2024-45336 is fixed by using `go 1.22.12` (upgraded from 1.22.0).
See:
https://github.com/golang/go/commit/b72d56f98d6620ebe07626dca4bb67ea8e185379
https://github.com/advisories/GHSA-7wrw-r4p8-38rx
**Checklist:**

fix(backend): upgrade go version to 1.22.12 to fix CVE-2024-45336

---

.github/resources/scripts/collect-logs.sh
.github/workflows/backend.yml
.github/workflows/e2e-test.yml
.github/workflows/kfp-kubernetes-execution-tests.yml
.github/workflows/kfp-samples.yml
.github/workflows/periodic.yml
.github/workflows/sdk-execution.yml
.github/workflows/upgrade-test.yml

- Resolves #11063
**Checklist:**

(test) : Collect and upload logs when test fails for k8s

---

frontend/src/pages/NewPipelineVersion.tsx
frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap

Restricted the file explorer to only show .yaml, .yml, .zip, and .tar.gz files instead of all files when selecting pipeline files to improve user experience.
**Checklist:**

fix(frontend): restrict file explorer to show only .yaml, .yml, .zip, and .tar.gz files

---

.github/workflows/kfp-samples.yml
backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/compiler/argocompiler/argo_test.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/testdata/hello_world_run_as_user.yaml
backend/src/v2/component/importer_launcher.go
backend/src/v2/component/launcher_v2.go
backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
backend/src/v2/test/sample-test.sh
samples/v2/modelcar_import/Dockerfile
samples/v2/modelcar_import/modelcar_import.py
samples/v2/sample_test.py
sdk/python/kfp/dsl/types/artifact_types.py
sdk/python/kfp/dsl/types/artifact_types_test.py

This allows dsl.import to leverage Modelcar container images in an OCI repository. This works by having an init container prepull the image and then adding a sidecar container when the launcher container is running. The Modelcar container adds a symlink to its /models directory in an emptyDir volume that is accessible by the launcher container. Once the launcher is done running the user code, it stops the Modelcar containers.
This approach has the benefit of leveraging image pull secrets configured on the Kubernetes cluster rather than require separate credentials for importing the artifact. Additionally, no data is copied to the emptyDir volume, so the storage cost is just pulling the Modelcar container image on the Kubernetes worker node.
Note that once …

feat(backend): Add support for importing models stored in the Modelcar format (sidecar)

---

backend/src/v2/driver/driver.go
backend/src/v2/metadata/client.go

This PR resolves [#11572](https://github.com/kubeflow/pipelines/issues/11572)
Subdags are being updated as soon as the first task within the subdag completes, which is incorrect behavior. The subdag status should only be updated once all tasks have completed.
This fix ensures that the subdag status is updated only after all tasks have been executed.
**Checklist:**

fix(backend): fixes DAG status update to reflect completion of all tasks

---

backend/src/v2/cmd/driver/main.go
backend/src/v2/cmd/launcher-v2/main.go
backend/src/v2/compiler/argocompiler/argo_test.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/dag.go
backend/src/v2/compiler/argocompiler/importer.go
backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
backend/src/v2/compiler/argocompiler/testdata/create_pod_metadata.yaml
backend/src/v2/compiler/argocompiler/testdata/exit_handler.yaml
backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
backend/src/v2/compiler/argocompiler/testdata/hello_world_log_level.yaml
backend/src/v2/compiler/argocompiler/testdata/hello_world_run_as_user.yaml
backend/src/v2/compiler/argocompiler/testdata/importer.yaml
backend/src/v2/compiler/argocompiler/testdata/multiple_parallel_loops.yaml
backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml

Design changes have been made since the original description, see [this comment](https://github.com/kubeflow/pipelines/pull/11278#issuecomment-2670098661) for updated usage
---
---
This PR adds the ability to change log level in the driver / launcher containers. This is implemented in a similar pattern as the overrides for driver / launcher images. Specifically, you can add the following environment variables to the `ml-pipeline` deployments:
```yaml
spec:
containers:
- env:
- name: DRIVER_LOG_LEVEL
value: "3"
- name: LAUNCHER_LOG_LEVEL
value: "3"
```
**Note:** A numerical value such as the literal `3` not `"3"` here will be invalid deployment spec and validation on the spec will fail causing `kubectl edit` to reject it with the message: `error: deployments.apps "ml-pipeline" is invalid`. …

feat(backend): configurable log level for driver / launcher images

---

backend/src/v2/compiler/argocompiler/dag.go
backend/src/v2/compiler/argocompiler/testdata/multiple_parallel_loops.yaml
backend/src/v2/driver/driver.go
samples/v2/parallel_after_dependency.py
samples/v2/parallel_consume_upstream.py
samples/v2/sample_test.py

* Updated `resolveUpstreamArtifacts` to use `getDAGTasks` to allow for it parse through parallelFor DAG contexts to retrieve the appropriate producerTask. This fixes #11520, it seems that the call with the filter to `GetExecutionsInDAG` was not reverted back to the same as it is in `resolveUpstreamParameters` in #11196.
* Updated the argocompiler for the `iteratorTask` section. The additional "-loop" added to the task associated with the parallelFor DAG breaks the dependency validation that the argoworkflows API calls in the submission of the pipeline. This partially resolves #10050 for the `.after()` usage of a parallelTask. The implementation for `dsl.Collected` in the backend will be coming in a follow-up PR.
cc: @droctothorpe 
**Checklist:**

fix(backend): parallelFor resolve upstream inputs. Fixes #11520

---

frontend/src/components/NewRunParametersV2.tsx

This PR resolves #11632
Optional pipeline inputs were incorrectly marked as a required field.
This fix ensures that the optional pipeline inputs are not marked as a required field.
**Checklist:**

fix(frontend): fixes optional pipeline inputs. Fixes #11632

---

manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/decorator-controller.yaml
manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/kustomization.yaml
manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
manifests/kustomize/third-party/metacontroller/base/cluster-role.yaml
manifests/kustomize/third-party/metacontroller/base/crd.yaml
manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml

Upgrading metacontroller manifests to v4.11.22 according to this [PR](https://github.com/kubeflow/manifests/pull/2988/) in Kubeflow manifests and this [issue](https://github.com/kubeflow/manifests/issues/2970).
This entails changing metacontroller type from composite to decorator, as since metacontroller v3, it's not supported to watch namespaces which is preventing creating necessary K8s objects for KFP multi tenancy.
cc @juliusvonkohout  @hbelmiro @HumairAK 
**Checklist:**

fix(manifests): Upgrading metacontroller to v4.11.22

---

backend/src/apiserver/server/list_request_util.go
backend/src/common/util/json.go
backend/src/common/util/pipelinerun.go
backend/src/common/util/workflow.go
backend/src/v2/cmd/driver/main.go
backend/src/v2/cmd/driver/main_test.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/visitor.go
backend/src/v2/compiler/visitor_test.go

When new proto api fields are added to the spec, these break the driver due to unknown field constraints. For example: 
Today the driver understands this kubernetes execution config: 
```yaml
platforms:
kubernetes:
deploymentSpec:
executors:
exec-some-component:
configMapAsEnv:
- configMapName: my-configmap    # this exists in the api today
```
Now suppose we are on kfp 2.4, and in 2.5 we add support for a new field, deprecated the old field `configMapName`: 
```yaml
platforms:
kubernetes:
deploymentSpec:
executors:
exec-some-component:
configMapAsEnv:
- configMapName: my-configmap           # this is now deprecated and configNameParameter is preferred
configNameParameter:
runtimeValue:
constant: my-configmap
```
And we add backend support for the new …

fix(backend): ignore unknown fields for pb json unmarshaling

---

proposals/11551-kubernetes-native-api/README.md

This proposesd a Kubernetes native API for pipelines and pipeline versions. This uses the KEP format in anticipation of #11535.
Here is a [demo](https://youtu.be/o3C4Cm127Qk?si=Z-fSkc12-K8iIZBS&t=274) of a prototype with this design.
**Checklist:**

docs: Add a KEP for a Kubernetes native API for pipelines

---

api/OWNERS
backend/OWNERS
kubernetes_platform/OWNERS
sdk/OWNERS

I would like to nominate the following individuals for reviewer status to the respective component areas.
@droctothorpe - Reviewer for sdk/backend components (contribs: [[1]](https://github.com/search?q=+repo%3Akubeflow%2Fpipelines++author%3Adroctothorpe+&type=pullrequests), [[2]](https://github.com/search?q=+repo%3Akubeflow%2Fpipelines++commenter%3Adroctothorpe+&type=pullrequests))
@zazulam - Reviewer for sdk/backend components (contribs: [[1]](https://github.com/search?q=+repo%3Akubeflow%2Fpipelines++commenter%3Azazulam+&type=pullrequests), [[2]](https://github.com/search?q=+repo%3Akubeflow%2Fpipelines++author%3Azazulam+&type=pullrequests))
@CarterFendley - Reviewer for workflows/ci (contribs: [[1]](https://github.com/search?q=+repo%3Akubeflow%2Fpipelines …

chore: nominate sdk/backend reviewers

---

kubernetes_platform/python/README.md

This PR adds documentation for set_image_pull_secrets added in https://github.com/kubeflow/pipelines/pull/10427
**Checklist:**

docs: Add documentation for set_image_pull_secrets

---

.github/workflows/sdk-execution.yml
test/sdk-execution-tests/requirements.txt
test/sdk-execution-tests/sdk_execution_tests.py

Often times, pods could not be scheduled because of insufficient CPU and the worker runs out of temporary disk space.
**Checklist:**

Limit the number of parallel tests in SDK execution tests

---

.github/workflows/kfp-samples.yml
.github/workflows/kfp-sdk-runtime-tests.yml
.github/workflows/sdk-execution.yml
backend/src/v2/test/sample-test.sh
backend/src/v2/test/scripts/ci-env.sh
test/kfp-kubernetes-execution-tests/sdk_execution_tests.py
test/presubmit-tests-sdk.sh
test/sdk-execution-tests/sdk_execution_tests.py

The KFP SDK execution tests weren't using the SDK from the pull request. Additionally, this commit adds support for choosing the right SDK in forks.
**Checklist:**

Use the correct SDK version in the SDK execution tests CI

---

.github/workflows/kfp-kubernetes-execution-tests.yml
test/kfp-kubernetes-execution-tests/sdk_execution_tests.py
test/sdk-execution-tests/sdk_execution_tests.py

This also now uses the in repo SDK for "k8s execution tests".
**Checklist:**

Fix format string in get_kfp_package_path

---

backend/src/apiserver/server/list_request_util.go
backend/src/common/util/pipelinerun.go
backend/src/common/util/workflow.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/visitor.go
backend/src/v2/compiler/visitor_test.go

In 9afe23e7 we introduced blackend dropping of unknown fields for unmarshalling, but going forward we want to handle this more on a case by case basis. In the case for driver we should drop them because by this point the api server has declare the pipeline spec is acceptable, so the driver should not fail here. As such we keep driver changes, but revert those utilized by the api server.
**Checklist:**

chore: partially revert 9afe23e7

---

test/kfp-kubernetes-execution-tests/sdk_execution_tests.py
test/sdk-execution-tests/sdk_execution_tests.py

On pushes to the master branch, PULL_NUMBER was an empty string.
**Checklist:**

Ignore empty PULL_NUMBER environment variables in SDK tests

---

backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/container_test.go
backend/src/v2/compiler/argocompiler/testdata/hello_world_with_retry.yaml
backend/src/v2/compiler/testdata/hello_world_with_retry.json

**Checklist:**
close https://github.com/kubeflow/pipelines/issues/9950 
In this [PR](https://github.com/kubeflow/pipelines/pull/11585), the manual retry via the Pipeline Run UI Page button was fixed.
However [set_retry]( https://kubeflow-pipelines.readthedocs.io/en/latest/source/dsl.html#kfp.dsl.PipelineTask.set_retry) at the execution level still does not work (for a different reason).
**Description of changes**: 
- `retryPolicy` is present in the generated KFP Pipeline Spec, but it is not translated into the Argo Workflow spec. Argo Workflows uses the [retryStrategy](https://argo-workflows.readthedocs.io/en/latest/retries/) instead.
- `retryPolicy` from the KFP Pipeline spec is mapped into the Argo Workflow spec under dag.task.input.retryPolicy, but Argo …

fix(backend) fix execution-level retry on the Argo Workflows backend

---

frontend/src/lib/Utils.tsx

This PR closes a tiny edge case in backwards compatibility with AWF `POD_NAMES` `v1` as described in [this](https://github.com/kubeflow/pipelines/issues/11681) issue.
**Testing evidence:**
Given a run with the following workflow manifest...
```yaml
Name:         basic-v1-lzq5k
Namespace:    kubeflow
...
Annotations: 
...
workflows.argoproj.io/pod-name-format: v1
API Version:  argoproj.io/v1alpha1
```
...(note that `API Version` is _not_ `v1` and note the presence of the `workflows.argoproj.io/pod-name-format` annotation) where `POD_NAMES` is set to "v1" on the workflow controller, here's the result when you click on the logs tab and you're running the UI from the tip of master:
And here's the result when you try to access logs for the exact same run after …

fix(frontend): compatibility with pod_names v1

---

manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/deployment.yaml

This PR and
- https://github.com/kubeflow/pipelines/pull/11656
- https://github.com/kubeflow/pipelines/pull/11585
- https://github.com/kubeflow/pipelines/pull/11578
- https://github.com/kubeflow/pipelines/pull/11673 is also worth a look
- https://github.com/kubeflow/pipelines/pull/11678 is also worth a look
Should make the KFP 2.4.1 release @hbelmiro @HumairAK 
I am running this for a long time on 3.12 and the integration test is also successful https://github.com/kubeflow/manifests/pull/3014
See also https://github.com/kubeflow/manifests/issues/3010#issuecomment-2677977953
See also https://github.com/akagami-harsh/manifests/blob/test-pss/experimental/security/PSS/patches/kubeflow-pipelines-profile-controller.yaml

Chore: fix the PPC image for the dockerhub ratelimit and add the securitycontext

---

manifests/kustomize/third-party/minio/base/minio-deployment.yaml

Copy of https://github.com/kubeflow/manifests/pull/3045
See also https://github.com/kubeflow/manifests/issues/3040 for more information.

fix: minio fsgroup for popular clusters

---

manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/deployment.yaml
manifests/kustomize/base/metadata/base/metadata-envoy-deployment.yaml
manifests/kustomize/base/metadata/overlays/db/metadata-db-deployment.yaml
manifests/kustomize/base/metadata/overlays/postgres/metadata-db-deployment.yaml
manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml

Fix Istio sidecar injection configuration by moving from deprecated annotations to the recommended labels approach. 
This PR addresses multiple Pipelines components that were using the annotation approach, ensuring proper sidecar injection behavior with the current Istio versions.
Issue: https://github.com/kubeflow/manifests/issues/2798
Part of PR: https://github.com/kubeflow/manifests/pull/3044
**Checklist:**

Fix Istio sidecar injection by moving from annotations to labels

---

frontend/README.md
frontend/src/index.tsx

This PR provides instructions for how to run the UI on your host machine and proxy to a cluster where KFP is deployed in **multi-user mode**. It also fixes a few small typos in the frontend README.
**Checklist:**

docs(ui): add multi-user proxy instructions

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py

Up to date, properly following the contributor's guide copy of PR https://github.com/kubeflow/pipelines/pull/9969.
This pull request addresses the issue of ensuring unique component names when merging component specifications from a sub-pipeline into a main pipeline configuration. The changes ensure that each component in the merged pipeline has a unique name, thus preventing conflicts and collisions that can occur when components from sub-pipelines are integrated into the main pipeline.
**Checklist:**

fix(sdk): avoid conflicting component names in DAG when reusing pipelines

---

backend/src/v2/component/launcher_v2.go
backend/src/v2/driver/driver_test.go
sdk/python/kfp/dsl/types/artifact_types.py
sdk/python/kfp/dsl/types/artifact_types_test.py

Forward slashes are invalid characters in a path and can't be escaped. This uses underscores instead.
**Checklist:**

bug(backend,sdk): Use a valid path separator for Modelcar imports

---

.github/workflows/pr-commands.yml

Comment body injected directly in GitHub action which can cause code execution with write permission on the repository
**Checklist:**

fix(CI) Github action is vulnerable to code execution via `comment body`

---

manifests/kustomize/base/cache/cache-deployment.yaml
manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
manifests/kustomize/third-party/argo/upstream/manifests/base/workflow-controller/workflow-controller-deployment.yaml
manifests/kustomize/third-party/minio/base/minio-deployment.yaml
manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml

related to https://github.com/kubeflow/manifests/pull/3050
**Checklist:**

Fix PSS restricted warnings

---

backend/metadata_writer/src/metadata_helpers.py

Replaced the previous workaround for checking if the DB is empty with mlmd_store.get_context_types(), as the upstream issue (#28) is now resolved.
Signed-off-by: Abhinav Sai D <abhinavsai491@tutanota.com>
**Checklist:**

fix(metadata-writer): use mlmd_store.get_context_types() instead of workaround

---

.github/workflows/rerun-pr-jobs.yml

https://github.com/estroz/rerun-actions is [no longer maintained](https://github.com/estroz/rerun-actions/pull/3).
It has a bug that prevents us from re-running specific tests.
There was a discussion in the past about forking https://github.com/estroz/rerun-actions in the Kubeflow org, but it didn't advance.
I fixed the bug on my fork. We can use it while the Kubeflow fork is not ready.
**Checklist:**

chore(test): Replaced the unmaintained rerun action

---

.github/workflows/rerun-pr-jobs.yml

`ubuntu-20.04` is going to be deprecated this month.
**Checklist:**

chore(test): Bumped ubuntu runner to 24.04 in rerun-pr-jobs.yml

---

sdk/RELEASE.md
sdk/python/requirements.in
sdk/python/requirements.txt

Allow google-cloud-storage 3.x which was released on January 29, 2025 : https://pypi.org/project/google-cloud-storage/3.0.0/
**Checklist:**

fix(sdk): allow google-cloud-storage < 4

---

sdk/python/kfp/dsl/types/artifact_types.py
sdk/python/kfp/local/importer_handler.py

Warn about oci:// not supported too.
AFAIU no remote schema is currently supported for Local. This patch
consolidates all possible values under an Enum and then checks the
supplied url against all possible prefixes.
**Checklist:**

fix(local): warn about oci:// not supported too

---

backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/driver/driver.go
samples/v2/component_with_optional_inputs.py
samples/v2/component_with_optional_inputs_test.py

If the pipeline run is submitted without specifying an optional parameter and there is no default, it was not handled by the driver. The approach taken is explicitly set null for these values and let the driver handle if the component parameter has a default that can be used.
**Checklist:**

Handle optional pipeline inputs in the driver

---

sdk/python/kfp/dsl/pipeline_task.py

Adds some missing info to the docs on `set_container_image`, clarifying that dynamic images can be used.
**Checklist:**

docs: mention that `set_container_image` works with dynamic images

---

.pre-commit-config.yaml
backend/src/v2/cmd/driver/main.go
backend/src/v2/cmd/launcher-v2/main.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/dag.go
backend/src/v2/compiler/argocompiler/importer.go
backend/src/v2/component/launcher_v2.go
backend/src/v2/component/launcher_v2_test.go
backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml

This PR updates the backend driver and launcher to support execution logs as proper artifacts. This makes logs available after pod and workflow garbage collection and closes many relevant open issues, such as https://github.com/kubeflow/pipelines/issues/11761, https://github.com/kubeflow/pipelines/issues/11357, and https://github.com/kubeflow/pipelines/issues/10036.
The changes were based on [this design proposal](https://docs.google.com/document/d/1GeMTWGHqHO5YLxr_S77McW6Gl4doMoOTMW2m8mODFsY/edit?usp=sharing) that was approved on a community call.
To our pleasant surprise, the UI does not render log artifacts as nodes in the graph. Here's a screenshot for reference:
As you can see, the dataset artifact gets a dedicated node and the log artifact does not. …

feat(backend): implement logs as artifacts

---

backend/src/v2/compiler/argocompiler/container.go
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
manifests/kustomize/hack/release.sh

This change relies on manifest yamls to specify the launcher & driver that is pinned to a specific KFP version. The goal is to decouple having to build launcher/driver at separate stages relative to api server.
This is accomplished by setting the hardcoded default to point to "latest" and during release, api server is built with this hardcoding, and the images for driver/launcher are patched into manifests post build along with the other images.
The apiserver deployment manifest is reformatted using yq so the next time the release.sh is ran, the user is not surprised by the entire file reformatting unexpectedly.
A PR with update to the release docs will follow. 
**Checklist:**

update driver & launcher image handling

---

.github/workflows/kfp-kubernetes-execution-tests.yml
.github/workflows/sdk-execution.yml

This PR follows a suggestion documented [here](https://github.com/actions/runner-images/issues/2840#issuecomment-1284059930) to free up 8GB of space on `/dev/root` on the sdk execution test runners. This is intended to address disk space issues that have surfaced intermittently during CI.
**Checklist:**

fix(tests): free up space in some test runners

---

manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml
manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml

If the run is associated with a ScheduledWorkflow and the OwnerReferencesPermissionEnforcement admission controller is on, it requires the update verb on scheduledworkflows/finalizers to set the proper owner reference.
I manually test this on an OpenShift cluster which has OwnerReferencesPermissionEnforcement on by default. See this for more details:
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
**Checklist:**

fix(backend): Fix run submissions with OwnerReferencesPermissionEnforcement on

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml

For context, the commit 70aaf8a9a469607dc6e4aad58d40b39c75363b99 removed support for the old fields (without a resource_ prefix). This was added back in commit 6ebf4aae0335424d3bc88175fd06a2b2ba05251f but done in a way that broke any usage of pipeline input parameters but was to support the current KFP backend which did not yet support the new fields. In commit 7c931ae20197b2309d7a8462f6ce099882a8f915, the old fields were removed again but added support for the new field in KFP backend.
This commit addresses the case where a user is using a new SDK but with a KFP backend prior to 2.4.
**Checklist:**

fix(sdk): Add SDK support for setting resource limits on older KFP versions

---

backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
kubernetes_platform/python/kfp/kubernetes/toleration.py
kubernetes_platform/python/test/unit/test_tolerations.py

It is a very reasonable usecase the user may want to provide as input a list of tolerations instead of a single toleration object. In fact, it is probably more preferable that we don't foce the user to add a new input for each new toleration entry for one of more tasks. This PR makes it so the input tolerations_json call will accept both, either a single or list of toleration input parameters. All tolerations, whether hardcoded, input list, input dicts, are appeneded into a flat list by driver.
**Checklist:**

feat(backend/sdk): add backend support for toleration lists.

---

backend/src/common/util/error.go

Prior to this change, if a user requested a pipeline version that no longer exists, it'd cause a whole stack trace to be displayed in the logs. For benign errors, this now is a single info log.
Before:
```
I0430 16:22:03.808263 1259085 error.go:278] ResourceNotFoundError: PipelineVersion ecc2da09-e6ee-4417-bb3c-5e909b335542 not found
github.com/kubeflow/pipelines/backend/src/common/util.NewResourceNotFoundError
/home/mprahl/git/pipelines/backend/src/common/util/error.go:170
github.com/kubeflow/pipelines/backend/src/apiserver/storage.(*PipelineStore).getPipelineVersionByCol
/home/mprahl/git/pipelines/backend/src/apiserver/storage/pipeline_store.go:863
github.com/kubeflow/pipelines/backend/src/apiserver/storage.(*PipelineStore).GetPipelineVersionWithStatus …
```

fix(backend): Stop logging the strack trace on benign user errors

---

backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/importer.go

This allows the launcher command to be overridden with the V2_LAUNCHER_COMMAND environment variable. This is useful if you need to override the command to launch Delve for debugging or you have a situation that requires using a different binary in the container image based on the environment.
**Checklist:**

feat(backend): Allow the launcher command to be configurable

---

backend/src/v2/component/launcher_v2.go
backend/src/v2/driver/driver.go
backend/src/v2/metadata/client.go
samples/v2/collected_artifacts.py
samples/v2/collected_parameters.py
samples/v2/sample_test.py
sdk/python/kfp/dsl/executor.py

Jumping off from #11627, these changes resolve #10050 in regards to the using `dsl.Collected` for both parameters and artifacts in pipelines. Currently for artifacts, the executor needs to be updated in the sdk and have a release prior to tests being enabled. As for parameters that should work out of the box with solely backend changes.
This PR introduces a few new methods to help ease with detecting and resolving collected inputs as well as cleaning up some of the shared logic between `resolveUpstreamParameters` & `resolveUpstreamArtifacts`.
A few things to keep in mind:
A **parallelFor** creates `x+1` dags, where `x` is the number of iterations. The extra dag is something I like to refer to as the **parallelFor** **_Head_** dag, being that it only …

feat(backend/sdk): enable dsl.Collected for parameters & artifacts

---

sdk/python/requirements-dev.txt

The command `pip install -r sdk/python/requirements-dev.txt` as suggested in `CONTRIBUTING.md` was failing with Python version 3.11.11 with the error:
```python
ImportError: cannot import name 'formatargspec' from 'inspect'
(/Users/ddowler/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/inspect.py)
hint: This usually indicates a problem with the package or the build environment.
help: `wrapt` (v1.13.3) was included because `pylint` (v2.12.2) depends on `astroid` (v2.9.3) which depends on `wrapt`
```
Upgrading `pylint` fixed this SDK install error.
**Checklist:**

fix(sdk): fix pip install for dev

---

backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/compiler/argocompiler/argo_test.go
backend/src/v2/compiler/argocompiler/container.go
backend/src/v2/compiler/argocompiler/testdata/hello_world_with_retry_all_args.yaml
backend/src/v2/compiler/testdata/hello_world_with_retry_all_args.json
samples/v2/pipeline_with_retry.py
samples/v2/sample_test.py

This PR improves how the retryStrategy field is set in the argo workflow spec. When a component with setRetry enabled is included in a pipeline, two single separate container and executor templates are added - retry-system-container-executor and retry-system-container-impl. All four retryStrategy fields (duration, factor maxDuration and limit) are input as parameters into these templates, in order to allow the reuse (previously, separate templates were created for every unique retryStrategy configuration).
If the input pipeline contains no components with setRetry enabled, these two templates will not be created. 
**Checklist:**
- [x ] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)

feat(backend): parameterize retryStrategy  input in Argo workflow

---

backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go

We want to be able to handle empty cases for tolerations/node selector gracefully. In the case of non lists (i.e. just one toleration struct), the empty case will fail currently with:
```
message: 'task ''my-pipeline-bmkd5.root.some-component.executor'' errored: Pod "my-pipeline-bmkd5-system-container-impl-4081191241" is invalid: spec.tolerations[0].operator: Invalid value: "": operator must be Exists when `key` is empty, which means "match all values and all keys"'
```
Tolerations list case is handled already implicitly but we just wrap it with an explicit check, and also add some test cases in this pr. 
**Checklist:**

chore: handle empty tolerations dict/lists parrameterization 

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/compiler_utils.py

Fixes: #10592.
`compiler_utils.get_dependencies` function validates `name` attribute each task in `_channel_inputs`. The bug is that it tries to retrieve the `name` attribute even if the task is `None`.
A similar fix was already introduced in another PR #11476. However, the contributor has not responded to the requests to rebase and to add tests for months.
**Checklist:**

fix(sdk): Resolves issue when using ParallelFor with param and depending tasks

---

test/presubmit-tests-sdk.sh

KFP SDK tests stopped working due to [`click` 8.2.0](https://github.com/pallets/click/releases/tag/8.2.0), which changed its behaviour.
> If help is shown because no_args_is_help is enabled (defaults to True for groups, False for commands), the exit code is 2 instead of 0. https://github.com/pallets/click/pull/1489 https://github.com/pallets/click/pull/1489
The above change makes tests that verify exit code fail.
This PR changes how dependencies are installed, so the tests run with the correct dependency ([8.1.8](https://github.com/kubeflow/pipelines/blob/5bc1a9bed1482ed55291f2de293e21efd7f3670e/sdk/python/requirements.txt#L16)).
**Checklist:**

chore(tests): fix KFP SDK tests

---

backend/src/apiserver/client_manager/client_manager.go
backend/src/apiserver/common/config.go
backend/src/apiserver/main.go

- Introduces two new CLI flags to enable support for the Kubernetes native API implementation.
- Converts pipeline names and versions to Kubernetes-compatible format before creating them as resources in Kubernetes.
**Checklist:**

feat(backend): Add CLI flags to support Kubernetes native API implementation

---

backend/test/v2/integration/cache_test.go

Adjusted the timeout from 3 to 4 minutes and the polling interval from 10 to 5 seconds in the cache integration test. This ensures more robust testing by allowing sufficient time for operations to complete while increasing polling frequency.
This change aims to fix the [flakiness](https://github.com/kubeflow/pipelines/actions/runs/15027471234/job/42231657464) in the test.
**Checklist:**

chore(test): Update cache test timeout and polling intervals

---

hack/update-toc.sh
proposals/11551-kubernetes-native-api/README.md
proposals/11875-pipeline-workspace/README.md

Many Kubeflow Pipelines (KFP) pipelines require passing large amounts of data between components. Doing so with artifact
inputs and outputs introduces overhead and requires additional S3 storage. The primary workaround is to create a
persistent volume claim (PVC) for the pipeline run but this requires Kubernetes knowledge, can be complicated, and hard
to clean up. This also doesn't work if the pipeline is run locally.
Abstracting this away with a new feature of KFP workspaces that provides shared storage between components for the
duration of a pipeline run would greatly enhance the user experience.
**Checklist:**

docs(KEP): Propose a new pipeline run workspace feature

---

developer_guide.md
manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml

This switches to the docker hosted mysql. Based on some quick research, it seems github action runners are exempt from docker rate limiting: [[1]](https://github.com/docker/hub-feedback/issues/2414#issuecomment-2744665417)
Note that there have been some hiccups in the past though: [[1]](https://github.com/actions/runner-images/issues/1445#issuecomment-2413558369)
**Checklist:**

chore(backend): upgrade mysql to 8.4

---

api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
api/v2alpha1/pipeline_spec.proto

- This PR introduces support for workspace configuration within the PipelineConfig, enabling users to customize workspace settings for pipeline runs.
- It adds new WorkspaceConfig and KubernetesWorkspaceConfig message types to pipeline_spec.proto.
- The PipelineConfig message is updated to include an optional workspace field.
**Checklist:**

feat(proto): Add WorkspaceConfig and KubernetesWorkspaceConfig message types to pipeline_spec proto

---

.github/workflows/kfp-samples.yml

Fixes flaky test behavior in kfp-samples.
This PR addresses disk space issues that have appeared in KFP Samples runs in CI.
**Checklist:**

fix(tests): free up space in kfp samples test workflow

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/pipeline_config.py

This PR updates the dsl.PipelineConfig class to support configuring a pipeline workspace using the newly introduced WorkspaceConfig and KubernetesWorkspaceConfig message types in pipeline_spec.proto
**Checklist:**

feat(sdk): update PipelineConfig to reflect new workspace Protobuf changes

---

backend/src/v2/client_manager/client_manager.go
backend/src/v2/client_manager/client_manager_fake.go
backend/src/v2/cmd/launcher-v2/main.go
backend/src/v2/component/launcher_v2.go
backend/src/v2/component/launcher_v2_test.go

- testing happy and unhappy paths for calling NewLauncherV2
- adding LauncherV2Dependencies struct to enable dependency injection
**Checklist:**

test(backend): Add unit test for NewLauncherV2

---

backend/src/apiserver/resource/resource_manager.go

This PR fixes several minor typos in backend/src/apiserver/resource/resource_manager.go:
Changes "gabarage-collected" to "garbage-collected" Changes "successfull" to "successful"
Fixes "successfully workflows runs" and "failed workflows runs" to "successful workflow runs" and "failed workflow runs" Corrects "reties" to "retries"
These changes improve code clarity and documentation quality. No functional code changes were made.

fix(apiserver): fix typos in resource_manager.go:

---

sdk/python/kfp/local/config.py
sdk/python/kfp/local/config_test.py
sdk/python/kfp/local/docker_task_handler.py

At the time of this writing, the KFP SDK local pipeline run functionality doesn't support authentication mechanisms, [as documented here](https://www.kubeflow.org/docs/components/pipelines/user-guides/core-functions/execute-kfp-pipelines-locally/). For cloud platforms such as GCP, authentication just involves [supplying authentication files to the runtime filesystem of the container](https://cloud.google.com/docs/authentication/application-default-credentials?hl=en#personal). 
Docker's [container running interface](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run) already supports everything necessary for the developer to propagate such credentials to the container runtime, so as far as the above …

feat(sdk): Add Support for Docker Container Run Arguments

---

manifests/kustomize/third-party/seaweedfs/README.md
manifests/kustomize/third-party/seaweedfs/base/seaweedfs/seaweedfs-deployment.yaml
test/seaweedfs/namespace_isolation_test.sh

Part of https://github.com/kubeflow/pipelines/pull/11965

chore: Add SeaweedFS gateway to remote object storage documentation

---

backend/src/apiserver/config/config.json
backend/src/apiserver/main.go
backend/src/apiserver/resource/resource_manager.go
backend/src/apiserver/resource/resource_manager_test.go
backend/src/apiserver/server/pipeline_upload_server_test.go
backend/src/apiserver/template/template.go
backend/src/apiserver/template/template_test.go
backend/src/apiserver/template/v2_template.go
backend/src/apiserver/webhook/pipelineversion_webhook.go
backend/src/common/client/api_server/v1/pipeline_client.go
backend/src/common/util/k8s_patches.go
backend/src/common/util/k8s_patches_test.go
backend/src/crd/kubernetes/v2beta1/pipelineversion_types.go
backend/src/v2/compiler/argocompiler/argo.go
backend/src/v2/compiler/argocompiler/argo_test.go
backend/src/v2/compiler/argocompiler/argo_workspace_test.go
backend/src/v2/compiler/argocompiler/testdata/hello_world_pvc_workspace.yaml
backend/src/v2/compiler/testdata/hello_world_pvc_workspace.json
backend/src/v2/compiler/visitor.go
backend/test/integration/pipeline_api_test.go
backend/test/integration/pipeline_version_api_test.go
backend/test/integration/upgrade_test.go

Part of: https://github.com/kubeflow/pipelines/issues/12053
Resolve: https://github.com/kubeflow/pipelines/issues/12058
- This PR is part of the ongoing work on the [Pipeline Run Workspace feature](https://github.com/kubeflow/pipelines/issues/12053).
- This introduces support for defining default PersistentVolumeClaim (PVC) configurations at the API server level to preconfigure workspace settings for users.
- The compiler automatically injects `volumeClaimTemplates` into Argo Workflows when a workspace is defined in the pipeline.
- Defaults from the API server config are used unless overridden by user-defined settings in the pipeline.
Example config.json -
```
{
"Workspace": {
"VolumeClaimTemplateSpec": {
"accessModes": ["ReadWriteMany"], …
```

feat(backend): update Argo Workflow Compiler to create workspace PVCs

---

proposals/12020-model-registry-integration/README.md

This document proposes integrating Kubeflow Pipelines (KFP) with the Kubeflow Model Registry to enable automated model registration during pipeline execution workflows. The integration would provide a simple model.register() API in the KFP SDK that abstracts away Model Registry connection details and authentication, while automatically populating KFP-specific metadata for proper model lineage tracking.
**Checklist:**

docs: Add a proposal for Model Registry integration

---

backend/src/apiserver/common/utils.go
backend/src/apiserver/main.go
backend/src/apiserver/server/experiment_server_test.go
backend/test/integration/job_api_test.go
backend/test/integration/run_api_test.go
backend/test/integration/upgrade_test.go

[This change](https://github.com/kubeflow/pipelines/commit/cc35187dff270008c6bef505c828f442773ec97d) introduced a breaking change where the API was setting default values for unknown fields, this has side effects that break certain elements of the UI - namely the namespace field for experiments struct is set to `""` instead of simply omitted, which prevents artifacts from being previewed, see before and after of the experiments struct: 
Before this fix (but post proto changes): 
```json
{
"experiment_id": "18e06f92-3c6c-43d2-a5d4-6208c602c1ce",
"display_name": "Default",
"description": "All runs created without specifying an experiment will be grouped here.",
"created_at": "2025-08-02T22:03:06Z",
"namespace": "",    <---- this is added when we don't omit …
```

fix(backend): omit unknown fields in json marshaling

---

kubernetes_platform/python/create_release_branch.sh

we always include the pb2  files now so this will fail if we try to run the create_release_branch.sh script

chore: ignore adding pb2.py files for kfp-k8s docs

---

backend/src/v2/compiler/visitor.go
backend/src/v2/component/constants.go
backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
backend/src/v2/driver/resolve.go
proposals/11875-pipeline-workspace/README.md
samples/v2/pipeline_with_workspace.py
samples/v2/sample_test.py
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/constants.py
sdk/python/kfp/local/config.py
sdk/python/kfp/local/config_test.py
sdk/python/kfp/local/pipeline_orchestrator.py
sdk/python/kfp/local/pipeline_orchestrator_test.py
sdk/python/kfp/local/placeholder_utils.py
sdk/python/kfp/local/placeholder_utils_test.py

This resolves https://github.com/kubeflow/pipelines/issues/12077
**Summary**
**SDK Change:**
Added a new placeholder constant:
dsl.WORKSPACE_PATH_PLACEHOLDER = "/kfp-workspace"
**Container Driver Change:**
- Detects if any input parameter equals dsl.WORKSPACE_PATH_PLACEHOLDER. 
- Also detects if any input or output path starts with /kfp-workspace. 
- If matched, the driver injects the volume mount for the shared workspace PVC into the Pod spec.
**Checklist:**

feat(backend/sdk): define and use dsl.WORKSPACE_PATH_PLACEHOLDER for workspace access

---

frontend/Dockerfile

**Checklist:**
Hi Team,
We are porting Kubeflow and Kserve components for the Power architecture.
Since the Alpine base image is not supported on Power, we have introduced the following build argument in frontend/Dockerfile:
`ARG BASE_IMAGE=alpine`
This allows us to specify an alternative base image i.e. bookworm at build time.
The image can now be build on power using below command:
`docker build --rm -t kfp-frontend-ppc64le:$PACKAGE_VERSION --build-arg BASE_IMAGE=bookworm -f frontend/Dockerfile .`

feat: Updated dockerfile to support Power

---

proposals/12147-mlmd-removal/README.md
proposals/12147-mlmd-removal/design-details.md
proposals/12147-mlmd-removal/protos/artifacts.proto
proposals/12147-mlmd-removal/protos/runs.json
proposals/12147-mlmd-removal/protos/runs.proto
proposals/12147-mlmd-removal/schema_changes.sql

Part of: #11760 
**Checklist:**

propose removing mlmd from kfp

---

backend/README.md
manifests/kustomize/env/dev-kind/kustomization.yaml

The network policies were preventing the node ports from being accessible from localhost. Additionally, the environment variables changed for how to configure object store host and port.
**Checklist:**

fix(docs): Fix local development after the SeaweedFS migration

---

.github/workflows/upgrade-test.yml
backend/src/apiserver/webhook/pipelineversion_webhook.go
backend/src/apiserver/webhook/pipelineversion_webhook_test.go

This just truncates the label value to 63 characters if it's too long. Since this is a label for convenience and not relied upon in the code for filtering, this is a safe change.
**Checklist:**

fix(backend): Fix mutating webhook when pipeline name label value is too long

---

frontend/server/minio-helper.test.ts
frontend/server/minio-helper.ts

This PR adds a custom credential provider to the minio client instantiation for the node server handling artifact uploads.
Currently, the credential resolution is limited to:
- Static configuration
- Provider info strings  
- AWS credential chain
This doesn't fully support enterprise environments that use:
- Custom credential APIs
- Dynamic or short lived (rotating) credentials
The change is small, focused, and fully backward compatible without any code changes to any existing minio client creation logic.
**Checklist:**

feat(frontend): Add custom credential provider 

---

backend/src/agent/persistence/worker/metrics_reporter_test.go
backend/src/common/util/workflow.go

This fixes metrics reporting for v1 pipeline runs that log metrics. Previously the wrong node id was sent to the api server.
You can verify this with this sample pipeline: 
<details><summary>sample.py</summary>
<p>
```python
from typing import NamedTuple
import kfp
from kfp.components import create_component_from_func
def train_op() -> NamedTuple('Outputs', [('mlpipeline_metrics', 'Metrics')]):
import json
import random
from pathlib import Path
accuracy = random.uniform(0.7, 0.99)
metrics = {
"metrics": [
{
"name": "accuracy",
"numberValue": accuracy,
"format": "PERCENTAGE"
}
]
}
return [json.dumps(metrics)]
train_component = create_component_from_func(
func=train_op,
base_image="python:3.9"
)
@dsl.pipeline(
name="Simple Metric Logging …
```

chore(backend): correct node id for metrics reporting

---

.github/workflows/kfp-samples.yml
.github/workflows/readthedocs-builds.yml
.github/workflows/sdk-upgrade.yml
api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
api/v2alpha1/pipeline_spec.proto
backend/src/v2/driver/container.go
backend/src/v2/driver/driver.go
backend/src/v2/driver/driver_test.go
backend/src/v2/driver/k8s.go
backend/src/v2/driver/k8s_test.go
backend/src/v2/driver/resolve.go
backend/test/proto_tests/testdata/generated-1791485/pipeline_spec.json
samples/v2/sample_test.py
samples/v2/task_config.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/compiler/pipeline_spec_builder_test.py
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/component_decorator.py
sdk/python/kfp/dsl/component_factory.py
sdk/python/kfp/dsl/component_task_config.py
sdk/python/kfp/dsl/executor.py
sdk/python/kfp/dsl/structures.py
sdk/python/kfp/dsl/task_config.py
sdk/python/kfp/dsl/types/type_utils.py

This PR introduces a powerful new feature that allows KFP tasks to forward their task configuration (resources, environment variables, node selectors, tolerations, affinity, volumes) to external workloads like Kubeflow TrainJobs, rather than applying them only to the task pod itself. This is particularly valuable for scenarios where the KFP task is launching another Kubernetes workload (e.g. `TrainJob`, `Job`, etc).
**Checklist:**

feat(sdk/backend): Support forwarding task configuration to external workloads

---

frontend/server/minio-helper.ts

This change modifies the AWS credential resolver to not cache the credentials that are taken from [ini files](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html). More information about this config can be found [here](https://github.com/aws/aws-sdk-js-v3/blob/756643ecd734b143ded1f46997ca7c3488cda313/packages/credential-provider-ini/src/fromIni.ts#L51-L55).
Context (why is this change necessary): When using AWS Assumed Roles, credentials/tokens are shortlived. The credentials file is routinely updated so that expired credentials are not used. This change forces the credential provider to always pull the latest credentials from disk, otherwise, expired credentials could be used from the cache.
**Testing**
1. I have a deployment of Kubeflow …

fix(ui): Disable caching for AWS credential files

---

backend/src/v2/driver/driver.go
samples/v2/pythonic_artifacts_test_pipeline.py
samples/v2/sample_test.py

This adds backend support for Pythonic artifacts.
Resolves:
https://github.com/kubeflow/pipelines/issues/12098
**Checklist:**

feat(backend): Add support for Pythonic artifacts

---

proposals/12238-notebook-component/README.md

This proposal introduces a first-class `@dsl.notebook_component` decorator that lets users build Kubeflow Pipelines
(KFP) components directly from Jupyter notebooks. The decorator embeds a `.ipynb` file into the component and executes
it at runtime via `nbclient`, with parameters injected as a prepended cell. This provides a simple path for
notebook-centric workflows to run in KFP without requiring separate packaging or bespoke wrappers.
**Checklist:**

doc: Add a KEP for Jupyter notebook components

---

sdk/python/kfp/compiler/compiler_test.py
sdk/python/kfp/compiler/pipeline_spec_builder.py
sdk/python/kfp/dsl/pipeline_config.py

This PR introduces `semaphoreKey` and `mutexName` fields in `PipelineConfig` to support pipeline-level concurrency controls in KFP SDK.
This PR should be merged only after https://github.com/kubeflow/pipelines/pull/11384 gets merged. 
**Testing instructions**
Create a Python virtualenv and install the SDK and IR YAML API packages locally:
```
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install wheel setuptools protobuf grpcio grpcio-tools
$ pip install -r sdk/python/requirements-dev.txt
$ pip install -e api/v2alpha1/python
$ pip install -e sdk/python
```
Use the [example code](https://gist.github.com/DharmitD/57a04c25e4211ffb9cf8891ddb34e1ce) to compile
```
$ kfp dsl compile --py main.py --output main.yaml
```
You should be able to compile and …

feat(SDK): Add SemaphoreKey and MutexName fields to DSL

---

backend/src/apiserver/server/util.go
backend/src/apiserver/server/util_test.go
proposals/12238-notebook-component/README.md
samples/v2/embedded_artifact.py
samples/v2/notebook_component_mixed.py
samples/v2/notebook_component_simple.py
samples/v2/notebooks/README.md
samples/v2/notebooks/nb_eval_metrics.ipynb
samples/v2/notebooks/nb_train_simple.ipynb
samples/v2/notebooks/nb_train_with_params.ipynb
sdk/python/kfp/dsl/__init__.py
sdk/python/kfp/dsl/component_decorator.py
sdk/python/kfp/dsl/component_factory.py
sdk/python/kfp/dsl/executor.py
sdk/python/kfp/dsl/notebook_component_decorator.py
sdk/python/kfp/dsl/notebook_component_decorator_test.py
sdk/python/kfp/dsl/notebook_helpers.py
sdk/python/kfp/dsl/templates/__init__.py
sdk/python/kfp/dsl/templates/notebook_executor.py
sdk/python/kfp/dsl/types/type_annotations.py
sdk/python/kfp/local/pipeline_orchestrator_test.py
sdk/python/kfp/local/subprocess_task_handler.py
sdk/python/requirements-dev.txt
sdk/python/setup.py
test_data/compiled-workflows/embedded_artifact.yaml
test_data/compiled-workflows/notebook_component_mixed.yaml
test_data/compiled-workflows/notebook_component_simple.yaml
test_data/pipeline_files/valid/critical/embedded_artifact.yaml
test_data/pipeline_files/valid/critical/notebook_component_simple.yaml
test_data/pipeline_files/valid/notebook_component_mixed.yaml

Implements [KEP-12238: Jupyter Notebook Components](https://github.com/kubeflow/pipelines/blob/master/proposals/12238-notebook-component/README.md)
- Introduce @dsl.notebook_component for notebook-driven components
- Embeds a .ipynb (or a dir with one .ipynb) into the component
- Binds dsl.run_notebook(**kwargs) to execute via nbclient at runtime
- Streams cell outputs; injects parameters (Papermill semantics)
- Installs default runtime deps when unspecified: nbclient, ipykernel, jupyter_client
- Add embedded artifact support for lightweight components
- Tar+gzip and base64-embed files/dirs; extract to temp dir at runtime
- Prepend extracted dir to sys.path; expose __KFP_EMBEDDED_ASSET_DIR/FILE
- Warn when compressed payload >1MB
- Add EmbeddedInput[...] …

feat(sdk): Add notebook components and embedded artifacts support
